In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
import pickle

import numpy as np
import pandas as pd

from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from pandas.tseries.offsets import MonthEnd, MonthBegin
from maricovault.MaricoDB import MaricoSnowflake

from joblib import Parallel, delayed

In [2]:
def get_dbconnection(db_name): 

    KEY_VAULT_NAME = "prod-pwd"
    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection

In [3]:
dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

### Helper Functions

In [4]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

def demand_driver_realign_pskus(data, channel):
    """
    Realign the old pskus to new pskus and return updated data.

    Args:
        data: pandas dataframe
        - master dataframe having all the pskus
    
    Return:
        data: pandas dataframe
        - dataframe 
    """
    realignment_data = realignment_df.copy()
    realignment_data.columns = realignment_data.columns.str.lower()
    realignment_data = realignment_data[
        (realignment_data["channel"] == channel)
        | (realignment_data["channel"] == channel + " B2C")
        | (realignment_data["channel"] == "ALL")
    ]

    data["parent_material_code"] = data["parent_material_code"].astype(int)

    for grp, grp_data in realignment_data.groupby(by=["psku old", "asm"]):
        old_psku, old_asm = grp
        new_psku = grp_data["psku new"].values[0]
        if old_asm != "ALL":
            condition = (data["parent_material_code"] == old_psku) & (
                data["asm_area_code"] == old_asm
            )
        else:
            condition = data["parent_material_code"] == old_psku

        data.loc[condition, "parent_material_code"] = new_psku

    return data

### Push heuristic data

In [ ]:
# df = pd.read_excel('/data/aman_singh/acuuracy_check/All_combination_Nov25_live_with_festivals((Autorecovered-312166393861403186)).xlsb', sheet_name = 'Base')
# df

,key,month_date,pred_prophet,pred_rf,pred_value_prophet,pred_value_rf,channel,asm_area_code,depot_code,parent_material_code,...,RF_Recency NS Heuristic Val,RF_Final Heursitic Val,Remark,Missing,ALL Planning Principle,NON ALL Planning Principle,Skip basis PP,Heuristic > 2x Model,Diff,Comparison
0,BCE1_D231_718589,45991,5.264959,2.7,0.000237,0.000122,ECOM,BCE1,D231,718589,...,0.000203,0.000203,NaN,0,0,0,0,0,0.0,P3M
1,BCE1_D231_718589,46022,4.547336,3.6,0.000205,0.000162,ECOM,BCE1,D231,718589,...,0.000203,0.000203,NaN,0,0,0,0,0,0.0,P3M
2,BCE1_D231_718589,46053,7.053803,2.7,0.000317,0.000122,ECOM,BCE1,D231,718589,...,0.000203,0.000203,NaN,0,0,0,0,0,0.0,P3M
3,BCE1_D231_718589,46081,5.662848,1.8,0.000255,0.000081,ECOM,BCE1,D231,718589,...,0.000203,0.000203,NaN,0,0,0,0,0,0.0,P3M
4,BCE1_D231_718589,46112,0.000000,2.7,0.000000,0.000122,ECOM,BCE1,D231,718589,...,0.000203,0.000203,NaN,0,0,0,0,1,0.0,P3M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164365,QCW2_D463_810125,46022,NaN,NaN,NaN,NaN,QCOM,QCW2,D463,810125,...,0.000069,0.000092,NaN,1,0,0,0,1,0.0,P3M
164366,QCW2_D463_810125,46053,NaN,NaN,NaN,NaN,QCOM,QCW2,D463,810125,...,0.000069,0.000092,NaN,1,0,0,0,1,0.0,P3M
164367,QCW2_D463_810125,46081,NaN,NaN,NaN,NaN,QCOM,QCW2,D463,810125,...,0.000069,0.000092,NaN,1,0,0,0,1,0.0,P3M
164368,QCW2_D463_810125,46112,NaN,NaN,NaN,NaN,QCOM,QCW2,D463,810125,...,0.000069,0.000092,NaN,1,0,0,0,1,0.0,P3M
164369,QCW2_D463_810125,46142,NaN,NaN,NaN,NaN,QCOM,QCW2,D463,810125,...,0.000069,0.000092,NaN,1,0,0,0,1,0.0,P3M

In [ ]:
# df['month_date'] = (
#     pd.to_datetime(df['month_date'], unit='D', origin='1899-12-30')
#       .dt.to_period('M')
#       .dt.to_timestamp()
# )
# df['run_month'] = (
#     pd.to_datetime(df['run_month'], unit='D', origin='1899-12-30')
#       .dt.to_period('M')
#       .dt.to_timestamp()
# )

# df['month_date'] = (
#     pd.to_datetime(df['month_date']) + pd.offsets.MonthEnd(0)
# )
# df['run_month'] = (
#     pd.to_datetime(df['run_month']) + pd.offsets.MonthEnd(0)
# )

In [ ]:
# df['month_date'] = df['month_date'].astype(str)
# df['run_month'] = df['run_month'].astype(str)
# df.columns

Index(['key', 'month_date', 'pred_prophet', 'pred_rf', 'pred_value_prophet',
       'pred_value_rf', 'channel', 'asm_area_code', 'depot_code',
       'parent_material_code', 'brand_code', 'sec_vol_actuals_rum_month_value',
       'pred_best_model', 'pred_value_best_model',
       'sec_vol_actuals_rum_month_treated',
       'sec_vol_actuals_rum_month_value_treated', 'train_till', 'cov',
       'run_month', 'M month', 'pred_prophet_70%ile', 'portfolio',
       'qtr_ind_rate', 'sec_vol_actuals_rum_month', 'P3M', 'P6M', 'LY P3M',
       'LY P6M', 'LY P3M_copy', 'P3M Max', 'P3M Top 2 Mean', 'MoM P3M growth',
       'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2', 'Growth Flag',
       '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)', 'P3M_value',
       'P6M_value', 'LY P3M_value', 'LY P6M_value',
       'pred_prophet_70%ile_value', 'LY', 'LLY', 'LY value', 'LLY value',
       'Sec_Value_in_Cr_lag_1', 'Sec_Value_in_Cr_lag_2',
       'Sec_Value_in_Cr_lag_3', 'ASM', 'Depot', 'PSKU', 'class', 'Sub Channel',
       'Potential Seasonal PSKU', 'Potential Seasonal Brand', 'LL', 'UL',
       'Final Model Vol', 'P3M LY Growth Vol', 'Event Heuristic Vol',
       'Comparison Vol', 'Seasonal Heuristic Vol', 'NS_Heurstic Vol',
       'Recency NS Heuristic', 'Final Heuristic Vol', 'Final Heuristic 2 Vol',
       'Simplified Heuristc', 'P3M LY Growth Val', 'Event Heuristic Val',
       'Seasonal Heuristic Val', 'NS_Heuristic Val',
       'Recency NS Heuristic Val', 'Final Heursitic Val',
       'Final Heursitic 2 Val', 'Simplified Heuristic Val', 'LY Diff',
       'RF Model Vol', 'RF_Event Heuristic Vol', 'RF_Seasonal Heuristic Vol',
       'RF_NS_Heurstic Vol', 'RF_Recency NS Heuristic',
       'RF_Final Heuristic Vol', 'RF_Event Heuristic Val',
       'RF_Seasonal Heuristic Val', 'RF_NS_Heuristic Val',
       'RF_Recency NS Heuristic Val', 'RF_Final Heursitic Val', 'Remark',
       'Missing', 'ALL Planning Principle', 'NON ALL Planning Principle',
       'Skip basis PP', 'Heuristic > 2x Model', 'Diff', 'Comparison'],
      dtype='object')

In [ ]:
# upload_df = df[['channel','portfolio', 'brand_code', 'class',
#         'run_month', 'M month','month_date', 'ASM', 'Depot', 'PSKU','pred_prophet', 'pred_rf','Final Heuristic 2 Vol',
#         'RF_Final Heuristic Vol']].rename(
#             columns = {'brand_code':'brand', 'class':'Brand Class', 'month_date':'month','pred_prophet':'prophet vol',
#                        'pred_rf':'rf_vol', 'Final Heuristic 2 Vol':'prophet heuristic vol',
#                        'RF_Final Heuristic Vol':'rf heuristic vol'}
#         )
# upload_df

,channel,portfolio,brand,Brand Class,run_month,M month,month,ASM,Depot,PSKU,prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol
0,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M,2025-11-30,BCE1,D231,718589,5.264959,2.7,5.264959,4.50
1,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+1,2025-12-31,BCE1,D231,718589,4.547336,3.6,4.547336,4.50
2,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+2,2026-01-31,BCE1,D231,718589,7.053803,2.7,7.053803,4.50
3,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+3,2026-02-28,BCE1,D231,718589,5.662848,1.8,5.662848,4.50
4,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+4,2026-03-31,BCE1,D231,718589,0.000000,2.7,4.500000,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164365,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+1,2025-12-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164366,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+2,2026-01-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164367,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+3,2026-02-28,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164368,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+4,2026-03-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164369,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+5,2026-04-30,QCW2,D463,810125,NaN,NaN,0.640000,0.64

In [ ]:
# upload_df.columns = upload_df.columns.str.upper()
# upload_df

,CHANNEL,PORTFOLIO,BRAND,BRAND CLASS,RUN_MONTH,M MONTH,MONTH,ASM,DEPOT,PSKU,PROPHET VOL,RF_VOL,PROPHET HEURISTIC VOL,RF HEURISTIC VOL
0,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M,2025-11-30,BCE1,D231,718589,5.264959,2.7,5.264959,4.50
1,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+1,2025-12-31,BCE1,D231,718589,4.547336,3.6,4.547336,4.50
2,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+2,2026-01-31,BCE1,D231,718589,7.053803,2.7,7.053803,4.50
3,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+3,2026-02-28,BCE1,D231,718589,5.662848,1.8,5.662848,4.50
4,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+4,2026-03-31,BCE1,D231,718589,0.000000,2.7,4.500000,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164365,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+1,2025-12-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164366,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+2,2026-01-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164367,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+3,2026-02-28,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164368,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+4,2026-03-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
164369,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+5,2026-04-30,QCW2,D463,810125,NaN,NaN,0.640000,0.64

In [ ]:
# from snowflake.connector.pandas_tools import write_pandas

# write_pandas(dev_conn, upload_df, 
#             table_name = "TRN_MIL_DF_HEURISTICS_OUTPUT",
#             auto_create_table=True,
#             overwrite = False,)

(True,
 1,
 164370,
 [('rtthbeires/file0.txt',
   'LOADED',
   164370,
   164370,
   1,
   0,
   None,
   None,
   None,
   None)])

### Push shared output

In [53]:
df = pd.read_excel(
    '/data/aman_singh/acuuracy_check/Stat Demand Forecast MT_as_on_7th_aug_2026.xlsb',
    sheet_name='Base'
)

In [54]:
df['run_month'] = '2026-08-31'
df

,Channel,Sub Channel,Portfolio,Brand,Brand Class,Qtr Index Rate,Key,Month,ASM,Depot,...,LY Val (Cr),P3M Val (Cr),P6M Val (Cr),LY P3M Val (Cr),LY P6M Val (Cr),LY P3M (Rolling) Val (Cr),Pred Val (Cr),Primary P3M 0?,NPD Flag,run_month
0,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,46295,BCE1,D231,...,0.000000,0.000578,0.000463,0.000347,0.000405,0.000463,0.000000,False,NON-NPD,2026-08-31
1,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,46326,BCE1,D231,...,0.000347,0.000578,0.000463,0.000347,0.000347,0.000347,0.000446,False,NON-NPD,2026-08-31
2,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,46356,BCE1,D231,...,0.001041,0.000578,0.000463,0.000347,0.000347,0.000347,0.000858,False,NON-NPD,2026-08-31
3,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,46387,BCE1,D231,...,0.001016,0.000578,0.000463,0.000347,0.000463,0.000463,0.000813,False,NON-NPD,2026-08-31
4,MT,B2B,CNO,PCNO(R),A,349274.001420,BCE1_D231_718312,46295,BCE1,D231,...,0.001397,0.000699,0.001514,0.002328,0.001746,0.003493,0.000838,False,NON-NPD,2026-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29519,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811219,46387,MCW2,D463,...,0.000000,0.001824,0.001183,0.000000,0.000000,0.000000,0.001824,False,NON-NPD,2026-08-31
29520,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,46295,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29521,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,46326,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29522,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,46356,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29523,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,46387,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31

In [55]:
df['Month'] = (
    pd.to_datetime(df['Month'], unit='D', origin='1899-12-30')
      .dt.to_period('M')
      .dt.to_timestamp()
)
df

,Channel,Sub Channel,Portfolio,Brand,Brand Class,Qtr Index Rate,Key,Month,ASM,Depot,...,LY Val (Cr),P3M Val (Cr),P6M Val (Cr),LY P3M Val (Cr),LY P6M Val (Cr),LY P3M (Rolling) Val (Cr),Pred Val (Cr),Primary P3M 0?,NPD Flag,run_month
0,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-09-01,BCE1,D231,...,0.000000,0.000578,0.000463,0.000347,0.000405,0.000463,0.000000,False,NON-NPD,2026-08-31
1,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-10-01,BCE1,D231,...,0.000347,0.000578,0.000463,0.000347,0.000347,0.000347,0.000446,False,NON-NPD,2026-08-31
2,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-11-01,BCE1,D231,...,0.001041,0.000578,0.000463,0.000347,0.000347,0.000347,0.000858,False,NON-NPD,2026-08-31
3,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-12-01,BCE1,D231,...,0.001016,0.000578,0.000463,0.000347,0.000463,0.000463,0.000813,False,NON-NPD,2026-08-31
4,MT,B2B,CNO,PCNO(R),A,349274.001420,BCE1_D231_718312,2026-09-01,BCE1,D231,...,0.001397,0.000699,0.001514,0.002328,0.001746,0.003493,0.000838,False,NON-NPD,2026-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29519,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811219,2026-12-01,MCW2,D463,...,0.000000,0.001824,0.001183,0.000000,0.000000,0.000000,0.001824,False,NON-NPD,2026-08-31
29520,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-09-01,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29521,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-10-01,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29522,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-11-01,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31
29523,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-12-01,MCW2,D463,...,0.000000,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31

In [56]:
df.columns

Index(['Channel', 'Sub Channel', 'Portfolio', 'Brand', 'Brand Class',
       'Qtr Index Rate', 'Key', 'Month', 'ASM', 'Depot', 'PSKU',
       'LY Vol (ROUM)', 'P3M Vol (ROUM)', 'P6M Vol (ROUM)',
       'LY P3M Vol (ROUM)', 'LY P6M Vol (ROUM)', 'LY P3M (Rolling) Vol (ROUM)',
       'Pred Vol (ROUM)', 'Sec Value Lag 1 (Cr)', 'Sec Value Lag 2 (Cr)',
       'Sec Value Lag 3 (Cr)', 'LY Value Lag 1 (Cr)', 'LY Value Lag 2 (Cr)',
       'LY Value Lead 1 (Cr)', 'LY Value Lead 2 (Cr)', 'Planning Principle',
       'LY Val (Cr)', 'P3M Val (Cr)', 'P6M Val (Cr)', 'LY P3M Val (Cr)',
       'LY P6M Val (Cr)', 'LY P3M (Rolling) Val (Cr)', 'Pred Val (Cr)',
       'Primary P3M 0?', 'NPD Flag', 'run_month'],
      dtype='object')

In [ ]:
#df.drop(['Qtr Index Rate', 'Brand Class', 'LY (ROUM)', 'LY Value (in Cr)', 'Pred Value (in Cr)'], axis=1, inplace=True)

In [57]:
df['Month'] = (
    pd.to_datetime(df['Month']) + pd.offsets.MonthEnd(0)
)

In [58]:
df['run_month'] = pd.to_datetime(df['run_month'])
df['Month'] = pd.to_datetime(df['Month'])


mappings = {}

for run_month in df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings

{Timestamp('2026-08-31 00:00:00'): {Timestamp('2026-08-31 00:00:00'): 'M',
  Timestamp('2026-09-30 00:00:00'): 'M+1',
  Timestamp('2026-10-31 00:00:00'): 'M+2',
  Timestamp('2026-11-30 00:00:00'): 'M+3',
  Timestamp('2026-12-31 00:00:00'): 'M+4',
  Timestamp('2027-01-31 00:00:00'): 'M+5',
  Timestamp('2027-02-28 00:00:00'): 'M+6',
  Timestamp('2027-03-31 00:00:00'): 'M+7',
  Timestamp('2027-04-30 00:00:00'): 'M+8'}}

In [59]:
df['M month'] = df.apply(
    lambda x: mappings[x['run_month']].get(
        x['Month']
    ), axis=1
)

In [60]:
df

,Channel,Sub Channel,Portfolio,Brand,Brand Class,Qtr Index Rate,Key,Month,ASM,Depot,...,P3M Val (Cr),P6M Val (Cr),LY P3M Val (Cr),LY P6M Val (Cr),LY P3M (Rolling) Val (Cr),Pred Val (Cr),Primary P3M 0?,NPD Flag,run_month,M month
0,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-09-30,BCE1,D231,...,0.000578,0.000463,0.000347,0.000405,0.000463,0.000000,False,NON-NPD,2026-08-31,M+1
1,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-10-31,BCE1,D231,...,0.000578,0.000463,0.000347,0.000347,0.000347,0.000446,False,NON-NPD,2026-08-31,M+2
2,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-11-30,BCE1,D231,...,0.000578,0.000463,0.000347,0.000347,0.000347,0.000858,False,NON-NPD,2026-08-31,M+3
3,MT,B2B,Others,REV.LQDST,B,247926.608903,BCE1_D231_718303,2026-12-31,BCE1,D231,...,0.000578,0.000463,0.000347,0.000463,0.000463,0.000813,False,NON-NPD,2026-08-31,M+4
4,MT,B2B,CNO,PCNO(R),A,349274.001420,BCE1_D231_718312,2026-09-30,BCE1,D231,...,0.000699,0.001514,0.002328,0.001746,0.003493,0.000838,False,NON-NPD,2026-08-31,M+1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29519,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811219,2026-12-31,MCW2,D463,...,0.001824,0.001183,0.000000,0.000000,0.000000,0.001824,False,NON-NPD,2026-08-31,M+4
29520,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-09-30,MCW2,D463,...,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31,M+1
29521,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-10-31,MCW2,D463,...,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31,M+2
29522,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-11-30,MCW2,D463,...,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31,M+3
29523,MT,B2C,Foods,TRU_ELMNT,DBU,353000.000000,MCW2_D463_811220,2026-12-31,MCW2,D463,...,0.000835,0.000824,0.000000,0.000000,0.000000,0.000835,False,NON-NPD,2026-08-31,M+4

In [61]:
df['Month'] = df['Month'].astype(str)
df['run_month'] = df['run_month'].astype(str)
df.columns

Index(['Channel', 'Sub Channel', 'Portfolio', 'Brand', 'Brand Class',
       'Qtr Index Rate', 'Key', 'Month', 'ASM', 'Depot', 'PSKU',
       'LY Vol (ROUM)', 'P3M Vol (ROUM)', 'P6M Vol (ROUM)',
       'LY P3M Vol (ROUM)', 'LY P6M Vol (ROUM)', 'LY P3M (Rolling) Vol (ROUM)',
       'Pred Vol (ROUM)', 'Sec Value Lag 1 (Cr)', 'Sec Value Lag 2 (Cr)',
       'Sec Value Lag 3 (Cr)', 'LY Value Lag 1 (Cr)', 'LY Value Lag 2 (Cr)',
       'LY Value Lead 1 (Cr)', 'LY Value Lead 2 (Cr)', 'Planning Principle',
       'LY Val (Cr)', 'P3M Val (Cr)', 'P6M Val (Cr)', 'LY P3M Val (Cr)',
       'LY P6M Val (Cr)', 'LY P3M (Rolling) Val (Cr)', 'Pred Val (Cr)',
       'Primary P3M 0?', 'NPD Flag', 'run_month', 'M month'],
      dtype='object')

In [62]:
upload_df = df[['Channel','Portfolio', 'Brand', 'Brand Class',
        'run_month', 'M month','Month', 'ASM', 'Depot', 'PSKU','Pred Vol (ROUM)']]

In [63]:
upload_df

,Channel,Portfolio,Brand,Brand Class,run_month,M month,Month,ASM,Depot,PSKU,Pred Vol (ROUM)
0,MT,Others,REV.LQDST,B,2026-08-31,M+1,2026-09-30,BCE1,D231,718303,0.000000
1,MT,Others,REV.LQDST,B,2026-08-31,M+2,2026-10-31,BCE1,D231,718303,0.018000
2,MT,Others,REV.LQDST,B,2026-08-31,M+3,2026-11-30,BCE1,D231,718303,0.034600
3,MT,Others,REV.LQDST,B,2026-08-31,M+4,2026-12-31,BCE1,D231,718303,0.032800
4,MT,CNO,PCNO(R),A,2026-08-31,M+1,2026-09-30,BCE1,D231,718312,0.024000
...,...,...,...,...,...,...,...,...,...,...,...
29519,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811219,0.051667
29520,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+1,2026-09-30,MCW2,D463,811220,0.023667
29521,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+2,2026-10-31,MCW2,D463,811220,0.023667
29522,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+3,2026-11-30,MCW2,D463,811220,0.023667
29523,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811220,0.023667

In [ ]:
# upload_df[upload_df['Month'] == '2026-04-30']['Pred Vol (ROUM)'].sum()

5346018.0036901245

In [64]:
upload_df.columns = upload_df.columns.str.upper()
upload_df

,CHANNEL,PORTFOLIO,BRAND,BRAND CLASS,RUN_MONTH,M MONTH,MONTH,ASM,DEPOT,PSKU,PRED VOL (ROUM)
0,MT,Others,REV.LQDST,B,2026-08-31,M+1,2026-09-30,BCE1,D231,718303,0.000000
1,MT,Others,REV.LQDST,B,2026-08-31,M+2,2026-10-31,BCE1,D231,718303,0.018000
2,MT,Others,REV.LQDST,B,2026-08-31,M+3,2026-11-30,BCE1,D231,718303,0.034600
3,MT,Others,REV.LQDST,B,2026-08-31,M+4,2026-12-31,BCE1,D231,718303,0.032800
4,MT,CNO,PCNO(R),A,2026-08-31,M+1,2026-09-30,BCE1,D231,718312,0.024000
...,...,...,...,...,...,...,...,...,...,...,...
29519,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811219,0.051667
29520,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+1,2026-09-30,MCW2,D463,811220,0.023667
29521,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+2,2026-10-31,MCW2,D463,811220,0.023667
29522,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+3,2026-11-30,MCW2,D463,811220,0.023667
29523,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811220,0.023667

In [65]:
upload_df.dtypes

CHANNEL             object
PORTFOLIO           object
BRAND               object
BRAND CLASS         object
RUN_MONTH           object
M MONTH             object
MONTH               object
ASM                 object
DEPOT               object
PSKU                 int64
PRED VOL (ROUM)    float64
dtype: object

In [66]:
upload_df['PORTFOLIO'] = upload_df['PORTFOLIO'].astype(str)

In [67]:
# push data to snowflake
from snowflake.connector.pandas_tools import write_pandas

write_pandas(dev_conn, upload_df, 
            table_name = "TRN_MIL_DF_SHARED",
            auto_create_table=True,
            overwrite = False,)

(True,
 1,
 29524,
 [('avjjdubqpi/file0.txt',
   'LOADED',
   29524,
   29524,
   1,
   0,
   None,
   None,
   None,
   None)])

### push offtakes to primary

In [211]:
qcom_df = pd.read_excel(
    '/data/aman_singh/acuuracy_check/Qcom_Stat_demand_forecast_as_on_6th_Aug.xlsx',
    sheet_name='Base'
)

In [212]:
qcom_df

,Key,Chain,Depot,PSKU,PSKU Description,Brand,Index Rate,Portfolio,Run Month,Month Date,...,June Val,May Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,Calculated Primary Val,Chain Primary Val,Brand class,NPD Flag,Planning Principle
0,blinkit_d112_718287,Blinkit,d112,718287,PCNO 200ml JAR,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid
1,blinkit_d112_718288,Blinkit,d112,718288,SAFF GOLD 5L JAR,SAFF GOLD,138865.260689,Saffola Oils,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000583,A,NON-NPD,Valid
2,blinkit_d112_718297,Blinkit,d112,718297,PCNO 50ml BTL,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid
3,blinkit_d112_718299,Blinkit,d112,718299,PCNO 100ml BTL,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid
4,blinkit_d112_718308,Blinkit,d112,718308,PCNO 100ml JAR,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21281,Zepto_D673_808931,Zepto,d673,808931,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.001979,NaN,NaN,NaN
21282,Zepto_D673_809046,Zepto,d673,809046,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000733,NaN,NaN,NaN
21283,Zepto_D674_808931,Zepto,d674,808931,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000264,NaN,NaN,NaN
21284,Zepto_D674_809046,Zepto,d674,809046,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.002991,NaN,NaN,NaN
21285,Zepto_D674_809250,Zepto,d674,809250,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000925,NaN,NaN,NaN

In [ ]:
# qcom_df['Month Date'] = (
#     pd.to_datetime(qcom_df['Month Date']) + pd.offsets.MonthEnd(0)
# )

In [ ]:
# qcom_df['Run Month'] = (
#     pd.to_datetime(qcom_df['Run Month'], unit='D', origin='1899-12-30')
#       .dt.to_period('M')
#       .dt.to_timestamp()
# )
# qcom_df['Run Month'] = (
#     pd.to_datetime(qcom_df['Run Month']) + pd.offsets.MonthEnd(0)
# )
# qcom_df

,Key,Depot,PSKU,PSKU Desc,Brand,Portfolio,Index Rate,Run Month,Month Date,M Month,...,LY Offtake Chain FC PSKU Lead 2 Val,Actual Closing SOH Val,Actual Closing SOH Lag 1 Val,Actual Closing SOH Lag 2 Val,Final Assumed Closing SOH Val,Final Assumed Closing SOH Lag 1 Val,Safety Stock Val,Brand Class,Planning Principle,Primary P3M 0?
0,D112_709567,D112,709567,SAF OATS 400G(FRE WT SAF OATS 1KG P)-N,SAFF OATS,Foods,126480.737807,2026-02-28,2026-03-31,M+1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,Valid,True
1,D112_709567,D112,709567,SAF OATS 400G(FRE WT SAF OATS 1KG P)-N,SAFF OATS,Foods,126480.737807,2026-02-28,2026-04-30,M+2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,Valid,True
2,D112_709567,D112,709567,SAF OATS 400G(FRE WT SAF OATS 1KG P)-N,SAFF OATS,Foods,126480.737807,2026-02-28,2026-05-31,M+3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,Valid,True
3,D112_709567,D112,709567,SAF OATS 400G(FRE WT SAF OATS 1KG P)-N,SAFF OATS,Foods,126480.737807,2026-02-28,2026-06-30,M+4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,Valid,True
4,D112_718287,D112,718287,PCNO 200ml JAR,PCNO(R),CNO,309765.865129,2026-02-28,2026-03-31,M+1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,A,Valid,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30603,D677_810805,D677,810805,PA BABY FACE BODY WIPES 1KG,PABABY_GM,Skin Care,451.133000,2026-02-28,2026-06-30,M+4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,C,Valid,True
30604,D677_811181,D677,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,Saffola Oils,330000.000000,2026-02-28,2026-03-31,M+1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,C,Valid,True
30605,D677_811181,D677,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,Saffola Oils,330000.000000,2026-02-28,2026-04-30,M+2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,C,Valid,True
30606,D677_811181,D677,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,Saffola Oils,330000.000000,2026-02-28,2026-05-31,M+3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,C,Valid,True
30607,D677_811181,D677,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,Saffola Oils,330000.000000,2026-02-28,2026-06-30,M+4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,C,Valid,True

In [213]:
qcom_df['Run Month'] = pd.to_datetime(qcom_df['Run Month'])
qcom_df['Month Date'] = pd.to_datetime(qcom_df['Month Date'])

mappings ={}

for run_month in qcom_df['Run Month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


   
qcom_df['M month'] = qcom_df.apply(
    lambda x: mappings[x['Run Month']].get(
        x['Month Date']
    ), axis=1
)

In [214]:
qcom_df.columns

Index(['Key', 'Chain', 'Depot', 'PSKU', 'PSKU Description', 'Brand',
       'Index Rate', 'Portfolio', 'Run Month', 'Month Date', 'M month',
       'Primary P3M Vol', 'Norm Days', 'Safety Stock Vol',
       'Actual Closing SOH Lag 2 Vol', 'Final Assumed Closing SOH Lag 1 Vol',
       'July Vol', 'June Vol', 'May Vol', 'Offtake Actuals Lag 1 Vol',
       'Offtake Actuals Lag 2 Vol', 'Offtake Actuals Lag 3 Vol',
       'Calculated Primary Vol', 'Chain Primary vol', 'Primary P3M Val',
       'Safety Stock Val', 'Actual Closing SOH Lag 2 Val',
       'Final Assumed Closing SOH Lag 1 Val', 'Offtake P3M Val', 'July Val',
       'June Val', 'May Val', 'Offtake Actuals Lag 1 Val',
       'Offtake Actuals Lag 2 Val', 'Offtake Actuals Lag 3 Val',
       'Calculated Primary Val', 'Chain Primary Val', 'Brand class',
       'NPD Flag', 'Planning Principle'],
      dtype='object')

In [215]:
qcom_df.rename(columns = {'Calculated Depot PSKU Primary Vol':'Calculated Primary Vol'}, inplace = True)

In [216]:
portfolio_query = """SELECT DISTINCT
    MATERIAL_GROUP_CODE AS BRAND_CODE,
    SAP_PORTFOLIO_NAME AS PORTFOLIO
FROM MST_MATERIAL
WHERE COMPANY_CODE = 'MIL'
  AND LATEST_RECORD_IND = '1'
  AND MATERIAL_GROUP_CODE IS NOT NULL
  AND SAP_PORTFOLIO_NAME IS NOT NULL
ORDER BY SAP_PORTFOLIO_NAME, MATERIAL_GROUP_CODE;"""
brand_md_df = pd.read_sql(portfolio_query, prod_conn)

brand_md_df.columns = brand_md_df.columns.str.lower()
brand_md_df.rename(columns = {'brand_code':'Brand'}, inplace = True)

In [217]:

len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    brand_md_df,
    on=['Brand'],
    how='left'
)
assert len_before_merge == len(qcom_df)

In [218]:
qcom_df

,Key,Chain,Depot,PSKU,PSKU Description,Brand,Index Rate,Portfolio,Run Month,Month Date,...,May Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,Calculated Primary Val,Chain Primary Val,Brand class,NPD Flag,Planning Principle,portfolio
0,blinkit_d112_718287,Blinkit,d112,718287,PCNO 200ml JAR,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid,CNO
1,blinkit_d112_718288,Blinkit,d112,718288,SAFF GOLD 5L JAR,SAFF GOLD,138865.260689,Saffola Oils,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.000583,A,NON-NPD,Valid,SAFFOLA OILS
2,blinkit_d112_718297,Blinkit,d112,718297,PCNO 50ml BTL,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid,CNO
3,blinkit_d112_718299,Blinkit,d112,718299,PCNO 100ml BTL,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid,CNO
4,blinkit_d112_718308,Blinkit,d112,718308,PCNO 100ml JAR,PCNO(R),349274.001420,CNO,2026-08-31,2026-09-30,...,0.0,0.0,0.0,0.0,0.0,0.000000,A,NON-NPD,Valid,CNO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21281,Zepto_D673_808931,Zepto,d673,808931,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,0.001979,NaN,NaN,NaN,NaN
21282,Zepto_D673_809046,Zepto,d673,809046,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,0.000733,NaN,NaN,NaN,NaN
21283,Zepto_D674_808931,Zepto,d674,808931,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,0.000264,NaN,NaN,NaN,NaN
21284,Zepto_D674_809046,Zepto,d674,809046,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,0.002991,NaN,NaN,NaN,NaN
21285,Zepto_D674_809250,Zepto,d674,809250,NaN,NaN,NaN,NaN,NaT,NaT,...,NaN,NaN,NaN,NaN,NaN,0.000925,NaN,NaN,NaN,NaN

In [219]:
qcom_df = qcom_df.groupby(['Month Date', 'Depot', 'PSKU',
       'Brand', 'portfolio','M month','Run Month'])[['Calculated Primary Vol']].sum().reset_index()
qcom_df

,Month Date,Depot,PSKU,Brand,portfolio,M month,Run Month,Calculated Primary Vol
0,2026-09-30,d112,718287,PCNO(R),CNO,M+1,2026-08-31,0.000000
1,2026-09-30,d112,718288,SAFF GOLD,SAFFOLA OILS,M+1,2026-08-31,0.000000
2,2026-09-30,d112,718297,PCNO(R),CNO,M+1,2026-08-31,0.000000
3,2026-09-30,d112,718299,PCNO(R),CNO,M+1,2026-08-31,0.215842
4,2026-09-30,d112,718308,PCNO(R),CNO,M+1,2026-08-31,0.000000
...,...,...,...,...,...,...,...,...
9235,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9236,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9237,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.000000
9238,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.000000
9239,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.000000

In [220]:

qcom_df.rename(columns = {'Month Date':'Month', 'Final PSKU':'PSKU', 'Depot Code':'Depot', 'Run Month':'run_month','portfolio':'Portfolio'}, inplace = True)
qcom_df

,Month,Depot,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol
0,2026-09-30,d112,718287,PCNO(R),CNO,M+1,2026-08-31,0.000000
1,2026-09-30,d112,718288,SAFF GOLD,SAFFOLA OILS,M+1,2026-08-31,0.000000
2,2026-09-30,d112,718297,PCNO(R),CNO,M+1,2026-08-31,0.000000
3,2026-09-30,d112,718299,PCNO(R),CNO,M+1,2026-08-31,0.215842
4,2026-09-30,d112,718308,PCNO(R),CNO,M+1,2026-08-31,0.000000
...,...,...,...,...,...,...,...,...
9235,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9236,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9237,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.000000
9238,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.000000
9239,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.000000

In [221]:
qcom_df[qcom_df['Month'] == '2026-09-30']['Calculated Primary Vol'].sum()

139770.83919014828

In [222]:
qcom_df['Month'] = qcom_df['Month'].astype(str)
qcom_df['run_month'] = qcom_df['run_month'].astype(str)
qcom_df.columns

Index(['Month', 'Depot', 'PSKU', 'Brand', 'Portfolio', 'M month', 'run_month',
       'Calculated Primary Vol'],
      dtype='object')

In [223]:
qcom_df

,Month,Depot,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol
0,2026-09-30,d112,718287,PCNO(R),CNO,M+1,2026-08-31,0.000000
1,2026-09-30,d112,718288,SAFF GOLD,SAFFOLA OILS,M+1,2026-08-31,0.000000
2,2026-09-30,d112,718297,PCNO(R),CNO,M+1,2026-08-31,0.000000
3,2026-09-30,d112,718299,PCNO(R),CNO,M+1,2026-08-31,0.215842
4,2026-09-30,d112,718308,PCNO(R),CNO,M+1,2026-08-31,0.000000
...,...,...,...,...,...,...,...,...
9235,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9236,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000
9237,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.000000
9238,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.000000
9239,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.000000

In [224]:
upload_df = qcom_df[['Month', 'Depot', 'PSKU', 'Brand', 'Portfolio', 'M month', 'run_month',
       'Calculated Primary Vol']]

In [225]:
upload_df['Channel'] = 'QCOM'

In [226]:
upload_df

,Month,Depot,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol,Channel
0,2026-09-30,d112,718287,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
1,2026-09-30,d112,718288,SAFF GOLD,SAFFOLA OILS,M+1,2026-08-31,0.000000,QCOM
2,2026-09-30,d112,718297,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
3,2026-09-30,d112,718299,PCNO(R),CNO,M+1,2026-08-31,0.215842,QCOM
4,2026-09-30,d112,718308,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
...,...,...,...,...,...,...,...,...,...
9235,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,QCOM
9236,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,QCOM
9237,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.000000,QCOM
9238,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.000000,QCOM
9239,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.000000,QCOM

In [227]:
upload_df.columns = upload_df.columns.str.upper()
upload_df

,MONTH,DEPOT,PSKU,BRAND,PORTFOLIO,M MONTH,RUN_MONTH,CALCULATED PRIMARY VOL,CHANNEL
0,2026-09-30,d112,718287,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
1,2026-09-30,d112,718288,SAFF GOLD,SAFFOLA OILS,M+1,2026-08-31,0.000000,QCOM
2,2026-09-30,d112,718297,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
3,2026-09-30,d112,718299,PCNO(R),CNO,M+1,2026-08-31,0.215842,QCOM
4,2026-09-30,d112,718308,PCNO(R),CNO,M+1,2026-08-31,0.000000,QCOM
...,...,...,...,...,...,...,...,...,...
9235,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,QCOM
9236,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,QCOM
9237,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.000000,QCOM
9238,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.000000,QCOM
9239,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.000000,QCOM

In [228]:
# push data to snowflake
from snowflake.connector.pandas_tools import write_pandas

write_pandas(dev_conn, upload_df, 
            table_name = "TRN_MIL_DF_OFT2PRIM_SHARED",
            auto_create_table=True,
            overwrite = False,)

(True,
 1,
 9240,
 [('ewbswhjalf/file0.txt',
   'LOADED',
   9240,
   9240,
   1,
   0,
   None,
   None,
   None,
   None)])

### Push chain psku primary

In [246]:
qcom_df = pd.read_excel(
    '/data/aman_singh/acuuracy_check/Ecom_Stat_forecast_chain_psku_as_on_20th_aug_2026.xlsx',
    sheet_name='Base'
)

In [247]:
qcom_df

,Key,Chain,PSKU,PSKU Description,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,...,Primary Actuals Lag 1 Val,Primary Actuals Lag 2 Val,Primary Actuals Lag 3 Val,Offtake P3M Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,Calculated Primary Val,Brand Class,NPD Flag
0,Amazon ARIPL_715098,Amazon ARIPL,715098,COCOSOUL H&N CREAM 75ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD
1,Amazon ARIPL_715099,Amazon ARIPL,715099,COCOSOUL FOOT CREAM 75ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD
2,Amazon ARIPL_715100,Amazon ARIPL,715100,COCOSOUL REV FACE WASH-100ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD
3,Amazon ARIPL_715106,Amazon ARIPL,715106,COCOSOUL H&S CLEANSER 30ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD
4,Amazon ARIPL_715107,Amazon ARIPL,715107,COCOSOUL REV FACE WASH-30ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6601,Purplle_807725,Purplle,807725,BIO OIL NATURAL 25ML BTL,BIO OILS,3.790534e+03,SKIN CARE,2026-08-31,2026-09-30,NaN,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,I,NON-NPD
6602,Purplle_809042,Purplle,809042,PAR ADV BABY SOAP 225 GMS,PABABY_GM,3.664850e+02,SKIN CARE,2026-08-31,2026-09-30,NaN,...,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,NPD,NON-NPD
6603,Purplle_809250,Purplle,809250,LVN PS KERATIN SERUM 100ML,LVNPST_ML,2.892133e+06,PREM. HAIR NOUR.,2026-08-31,2026-09-30,NaN,...,0.0,0.0,0.0,0.000270,0.000145,0.000405,0.000260,0.0,I,NON-NPD
6604,Purplle_810673,Purplle,810673,PA ESS ROSEMARY OIL 14ML,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,NaN,...,0.0,0.0,0.0,0.000138,0.000216,0.000072,0.000126,0.0,NPD,NPD
6605,Purplle_810674,Purplle,810674,PA ESS TEA TREE OIL 14ML,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,NaN,...,0.0,0.0,0.0,0.000006,0.000018,0.000000,0.000000,0.0,NPD,NPD

In [ ]:
# qcom_df['Month Date'] = (
#     pd.to_datetime(qcom_df['Month Date']) + pd.offsets.MonthEnd(0)
# )

In [ ]:
# qcom_df['Run Month'] = (
#     pd.to_datetime(qcom_df['Run Month'], unit='D', origin='1899-12-30')
#       .dt.to_period('M')
#       .dt.to_timestamp()
# )
# qcom_df['Run Month'] = (
#     pd.to_datetime(qcom_df['Run Month']) + pd.offsets.MonthEnd(0)
# )
# qcom_df

,Key,Chain,PSKU,PSKU Desc,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,...,Offtake Actuals Lag 3 Val,LY Offtake Actuals Lag 1 Val,LY Offtake Actuals Lag 2 Val,LY Offtake Actuals Lag 3 Val,LY Offtake Actuals Lead 1 Val,LY Offtake Actuals Lead 2 Val,Calculated Primary Val,Brand Class,Planning Principle,Primary P3M 0?
0,Amazon ARIPL_718287,Amazon ARIPL,718287,PCNO 200ml JAR,PCNO(R),309765.865129,CNO,2026-02-28,2026-03-31,M+1,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,A,Valid,True
1,Amazon ARIPL_718287,Amazon ARIPL,718287,PCNO 200ml JAR,PCNO(R),309765.865129,CNO,2026-02-28,2026-04-30,M+2,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,A,Valid,True
2,Amazon ARIPL_718287,Amazon ARIPL,718287,PCNO 200ml JAR,PCNO(R),309765.865129,CNO,2026-02-28,2026-05-31,M+3,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,A,Valid,True
3,Amazon ARIPL_718287,Amazon ARIPL,718287,PCNO 200ml JAR,PCNO(R),309765.865129,CNO,2026-02-28,2026-06-30,M+4,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,A,Valid,True
4,Amazon ARIPL_718288,Amazon ARIPL,718288,SAFF GOLD 5L JAR,SAFF GOLD,137662.938527,Saffola Oils,2026-02-28,2026-03-31,M+1,...,0.28265,0.165361,0.190966,0.22004,0.159827,0.200795,0.34632,A,Valid,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11487,Nykaa_811169,Nykaa,811169,SW MINI EDP GIFT PO4 18ML,SW_SGPRF,1443.400363,Male Grooming,2026-02-28,2026-06-30,M+4,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,C,Valid,True
11488,Nykaa_811181,Nykaa,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,330000.000000,Saffola Oils,2026-02-28,2026-03-31,M+1,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,C,Valid,True
11489,Nykaa_811181,Nykaa,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,330000.000000,Saffola Oils,2026-02-28,2026-04-30,M+2,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,C,Valid,True
11490,Nykaa_811181,Nykaa,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,330000.000000,Saffola Oils,2026-02-28,2026-05-31,M+3,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,C,Valid,True
11491,Nykaa_811181,Nykaa,811181,SAFFOLA COLDPRESS CNO 1L,SAF_CDPRS,330000.000000,Saffola Oils,2026-02-28,2026-06-30,M+4,...,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,C,Valid,True

In [248]:
qcom_df['Run Month'] = pd.to_datetime(qcom_df['Run Month'])
qcom_df['Month Date'] = pd.to_datetime(qcom_df['Month Date'])

mappings ={}

for run_month in qcom_df['Run Month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


   
qcom_df['M month'] = qcom_df.apply(
    lambda x: mappings[x['Run Month']].get(
        x['Month Date']
    ), axis=1
)

In [ ]:
# qcom_df = qcom_df[qcom_df['M month'] == 'M+1']
# qcom_df

,key2,key,Chain,FC,PSKU,PSKU Desc,Brand,Index Rate,Portfolio,Run Month,...,Offtake Chain FC PSKU Lag 3 Vol,LY Offtake Actuals Chain FC PSKU Vol,LY Offtake Chain FC PSKU P3M Vol,Offtake Chain FC PSKU P3M Vol,Offtake Chain FC PSKU Lag 1 Val,Offtake Chain FC PSKU Lag 2 Val,Offtake Chain FC PSKU Lag 3 Val,LY Offtake Actuals Chain FC PSKU Val,LY Offtake Chain FC PSKU P3M Val,Offtake Chain FC PSKU P3M Val
2,Blinkit_ahmedabad a2 - feeder warehouse_718288,Blinkit_718288,Blinkit,ahmedabad a2 - feeder warehouse,718288,SAFF GOLD 5L JAR,SAFF GOLD,137662.938527,Saffola Oils,2025-11-30,...,6.873931,5.219777,3.804556,6.602009,0.107562,0.085510,0.094629,0.071857,0.052375,0.090885
9,Blinkit_ahmedabad a2 - feeder warehouse_718299,Blinkit_718299,Blinkit,ahmedabad a2 - feeder warehouse,718299,PCNO 100ml BTL,PCNO(R),309765.865129,CNO,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,Blinkit_ahmedabad a2 - feeder warehouse_718308,Blinkit_718308,Blinkit,ahmedabad a2 - feeder warehouse,718308,PCNO 100ml JAR,PCNO(R),309765.865129,CNO,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,Blinkit_ahmedabad a2 - feeder warehouse_718310,Blinkit_718310,Blinkit,ahmedabad a2 - feeder warehouse,718310,PCNO 500ml JAR,PCNO(R),309765.865129,CNO,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,Blinkit_ahmedabad a2 - feeder warehouse_718312,Blinkit_718312,Blinkit,ahmedabad a2 - feeder warehouse,718312,PCNO 1L JAR,PCNO(R),309765.865129,CNO,2025-11-30,...,0.196489,0.114393,0.065902,0.201895,0.006292,0.005917,0.006087,0.003543,0.002041,0.006254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235825,Zepto_pun-dry-mh2-koregaon_810673,Zepto_810673,Zepto,pun-dry-mh2-koregaon,810673,PA ESS ROSEMARY OIL 14ML,PA_ESS_HO,12900.000000,Hair Oils,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235832,Zepto_pun-dry-mh2-koregaon_810674,Zepto_810674,Zepto,pun-dry-mh2-koregaon,810674,PA ESS TEA TREE OIL 14ML,PA_ESS_HO,12900.000000,Hair Oils,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235839,Zepto_pun-dry-mh2-koregaon_810685,Zepto_810685,Zepto,pun-dry-mh2-koregaon,810685,SF MUESLI MANGO 400G POUCH,SAF-MUSLI,321959.667548,Foods,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235846,Zepto_pun-dry-mh2-koregaon_810738,Zepto_810738,Zepto,pun-dry-mh2-koregaon,810738,PA BABY FACE BODY WIPE 362GM,PABABY_GM,451.133000,Skin Care,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
235853,Zepto_pun-dry-mh2-koregaon_810805,Zepto_810805,Zepto,pun-dry-mh2-koregaon,810805,PA BABY FACE BODY WIPES 1KG,PABABY_GM,451.133000,Skin Care,2025-11-30,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [249]:
qcom_df.columns

Index(['Key', 'Chain', 'PSKU', 'PSKU Description', 'Brand', 'Index Rate',
       'Portfolio', 'Run Month', 'Month Date', 'M month', 'Primary P3M Vol',
       'Norm Days', 'Safety Stock Vol', 'Actual Closing SOH Lag 2 Vol',
       'Final Assumed Closing SOH Lag 1 Vol', 'Primary Actuals Lag 1 Vol',
       'Primary Actuals Lag 2 Vol', 'Primary Actuals Lag 3 Vol',
       'Offtake P3M Vol', 'Offtake Actuals Lag 1 Vol',
       'Offtake Actuals Lag 2 Vol', 'Offtake Actuals Lag 3 Vol',
       'Calculated Primary Vol', 'Primary P3M Val', 'Safety Stock Val',
       'Actual Closing SOH Lag 2 Val', 'Final Assumed Closing SOH Lag 1 Val',
       'Primary Actuals Lag 1 Val', 'Primary Actuals Lag 2 Val',
       'Primary Actuals Lag 3 Val', 'Offtake P3M Val',
       'Offtake Actuals Lag 1 Val', 'Offtake Actuals Lag 2 Val',
       'Offtake Actuals Lag 3 Val', 'Calculated Primary Val', 'Brand Class',
       'NPD Flag'],
      dtype='object')

In [250]:
qcom_df.rename(columns = {'Calculated Depot PSKU Primary Vol':'Calculated Primary Vol'}, inplace = True)

In [ ]:
# brand_md_df = pd.read_excel(r"/data/aman_singh/mt_forecast/Brand_metadata.xlsx")
# brand_md_df.rename(columns = {'brand_code':'Brand'}, inplace = True)

In [251]:

len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    brand_md_df,
    on=['Brand'],
    how='left'
)
assert len_before_merge == len(qcom_df)

In [252]:
qcom_df

,Key,Chain,PSKU,PSKU Description,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,...,Primary Actuals Lag 2 Val,Primary Actuals Lag 3 Val,Offtake P3M Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,Calculated Primary Val,Brand Class,NPD Flag,portfolio
0,Amazon ARIPL_715098,Amazon ARIPL,715098,COCOSOUL H&N CREAM 75ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD,SKIN CARE
1,Amazon ARIPL_715099,Amazon ARIPL,715099,COCOSOUL FOOT CREAM 75ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD,SKIN CARE
2,Amazon ARIPL_715100,Amazon ARIPL,715100,COCOSOUL REV FACE WASH-100ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD,SKIN CARE
3,Amazon ARIPL_715106,Amazon ARIPL,715106,COCOSOUL H&S CLEANSER 30ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD,SKIN CARE
4,Amazon ARIPL_715107,Amazon ARIPL,715107,COCOSOUL REV FACE WASH-30ML,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,DBU,NON-NPD,SKIN CARE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6601,Purplle_807725,Purplle,807725,BIO OIL NATURAL 25ML BTL,BIO OILS,3.790534e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,I,NON-NPD,SKIN CARE
6602,Purplle_809042,Purplle,809042,PAR ADV BABY SOAP 225 GMS,PABABY_GM,3.664850e+02,SKIN CARE,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,NPD,NON-NPD,SKIN CARE
6603,Purplle_809250,Purplle,809250,LVN PS KERATIN SERUM 100ML,LVNPST_ML,2.892133e+06,PREM. HAIR NOUR.,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000270,0.000145,0.000405,0.000260,0.0,I,NON-NPD,PREM. HAIR NOUR.
6604,Purplle_810673,Purplle,810673,PA ESS ROSEMARY OIL 14ML,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000138,0.000216,0.000072,0.000126,0.0,NPD,NPD,HAIR OILS
6605,Purplle_810674,Purplle,810674,PA ESS TEA TREE OIL 14ML,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,M+1,...,0.0,0.0,0.000006,0.000018,0.000000,0.000000,0.0,NPD,NPD,HAIR OILS

In [253]:
qcom_df = qcom_df.groupby(['Month Date', 'Chain', 'PSKU',
       'Brand', 'portfolio','M month','Run Month'])[['Calculated Primary Vol']].sum().reset_index()
qcom_df

,Month Date,Chain,PSKU,Brand,portfolio,M month,Run Month,Calculated Primary Vol
0,2026-09-30,Amazon ARIPL,715098,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
1,2026-09-30,Amazon ARIPL,715099,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
2,2026-09-30,Amazon ARIPL,715100,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
3,2026-09-30,Amazon ARIPL,715106,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
4,2026-09-30,Amazon ARIPL,715107,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
...,...,...,...,...,...,...,...,...
6601,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0
6602,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0
6603,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0
6604,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0
6605,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0

In [254]:

qcom_df.rename(columns = {'Month Date':'Month', 'Final PSKU':'PSKU', 'Depot Code':'Depot', 'Run Month':'run_month','portfolio':'Portfolio'}, inplace = True)
qcom_df

,Month,Chain,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol
0,2026-09-30,Amazon ARIPL,715098,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
1,2026-09-30,Amazon ARIPL,715099,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
2,2026-09-30,Amazon ARIPL,715100,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
3,2026-09-30,Amazon ARIPL,715106,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
4,2026-09-30,Amazon ARIPL,715107,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
...,...,...,...,...,...,...,...,...
6601,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0
6602,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0
6603,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0
6604,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0
6605,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0

In [255]:
qcom_df[qcom_df['Month'] == '2026-09-30']['Calculated Primary Vol'].sum()

461412.66945625364

In [256]:
qcom_df['Month'] = qcom_df['Month'].astype(str)
qcom_df['run_month'] = qcom_df['run_month'].astype(str)
qcom_df.columns

Index(['Month', 'Chain', 'PSKU', 'Brand', 'Portfolio', 'M month', 'run_month',
       'Calculated Primary Vol'],
      dtype='object')

In [257]:
qcom_df

,Month,Chain,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol
0,2026-09-30,Amazon ARIPL,715098,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
1,2026-09-30,Amazon ARIPL,715099,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
2,2026-09-30,Amazon ARIPL,715100,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
3,2026-09-30,Amazon ARIPL,715106,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
4,2026-09-30,Amazon ARIPL,715107,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0
...,...,...,...,...,...,...,...,...
6601,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0
6602,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0
6603,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0
6604,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0
6605,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0

In [258]:
upload_df = qcom_df[['Month', 'Chain', 'PSKU', 'Brand', 'Portfolio', 'M month', 'run_month',
       'Calculated Primary Vol']]

In [259]:
upload_df['Channel'] = 'Ecom'

In [260]:
upload_df

,Month,Chain,PSKU,Brand,Portfolio,M month,run_month,Calculated Primary Vol,Channel
0,2026-09-30,Amazon ARIPL,715098,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
1,2026-09-30,Amazon ARIPL,715099,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
2,2026-09-30,Amazon ARIPL,715100,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
3,2026-09-30,Amazon ARIPL,715106,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
4,2026-09-30,Amazon ARIPL,715107,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
...,...,...,...,...,...,...,...,...,...
6601,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0,Ecom
6602,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0,Ecom
6603,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0,Ecom
6604,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,Ecom
6605,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,Ecom

In [261]:
upload_df.columns = upload_df.columns.str.upper()
upload_df

,MONTH,CHAIN,PSKU,BRAND,PORTFOLIO,M MONTH,RUN_MONTH,CALCULATED PRIMARY VOL,CHANNEL
0,2026-09-30,Amazon ARIPL,715098,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
1,2026-09-30,Amazon ARIPL,715099,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
2,2026-09-30,Amazon ARIPL,715100,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
3,2026-09-30,Amazon ARIPL,715106,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
4,2026-09-30,Amazon ARIPL,715107,CO_SO_PCP,SKIN CARE,M+1,2026-08-31,0.0,Ecom
...,...,...,...,...,...,...,...,...,...
6601,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0,Ecom
6602,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0,Ecom
6603,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0,Ecom
6604,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,Ecom
6605,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,Ecom

In [262]:
# push data to snowflake
from snowflake.connector.pandas_tools import write_pandas

write_pandas(dev_conn, upload_df, 
            table_name = "TRN_MIL_DF_OFT2PRIM_CPSKU",
            auto_create_table=True,
            overwrite = False,)

(True,
 1,
 6606,
 [('cjdlndwjim/file0.txt',
   'LOADED',
   6606,
   6606,
   1,
   0,
   None,
   None,
   None,
   None)])

### push offtakes data

In [49]:
offtakes_df = pd.read_excel('/data/aman_singh/acuuracy_check/Heuristics_all_combination_qcom_depot_psku_aug_live.xlsx', sheet_name = 'Base')

In [50]:
offtakes_df.columns[50:]

Index(['OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2', 'OT_Value_in_Cr_lag_3',
       'class', 'skipped', 'seasonality_flag', 'final_trend',
       'lower_threshold', 'upper_threshold', 'recency_factor',
       'shrink_ratio_prophet', 'shrink_ratio_rf', 'p3m_ly_growth',
       'recency_heuristic_prophet_vol', 'seasonal_heuristic_prophet_vol',
       'rec_seas_heuristic_prophet_vol', 'non_seasonal_heuristic_prophet_vol',
       'final_heuristic_prophet_vol', 'final_heuristic_prophet_value',
       'final_heuristic_prophet_value_2', 'final_heuristic_prophet_vol_2',
       'recency_heuristic_rf_vol', 'seasonal_heuristic_rf_vol',
       'rec_seas_heuristic_rf_vol', 'non_seasonal_heuristic_rf_vol',
       'final_heuristic_rf_vol', 'final_heuristic_rf_value',
       'final_heuristic_rf_value_2', 'final_heuristic_rf_vol_2',
       'error_prophet_vol', 'abs_error_prophet_vol', 'error_prophet_value',
       'abs_error_prophet_value', 'error_rf_vol', 'abs_error_rf_vol',
       'error_rf_value', 'abs_error_rf_value',
       'error_prophet_heuristics_value', 'abs_error_prophet_heuristics_value',
       'error_rf_heuristics_value', 'abs_error_rf_heuristics_value',
       'seasonal_brand', 'seasonal_psku', 'ly_lag1_value', 'ly_lag2_value',
       'ly_lead1_value', 'ly_lead2_value', 'pred_prophet_60%ile_value',
       'pred_prophet_60%ile', 'shrink_ratio_60',
       'recency_heuristic_60_prophet_vol', 'seasonal_heuristic_60_prophet_vol',
       'non_seasonal_heuristic_60_prophet_vol',
       'final_heuristic_60_prophet_vol', 'final_heuristic_60_prophet_value',
       'final_heuristic_60_prophet_value_2',
       'final_heuristic_60_prophet_vol_2', 'shrink_ratio_70',
       'recency_heuristic_70_prophet_vol', 'seasonal_heuristic_70_prophet_vol',
       'non_seasonal_heuristic_70_prophet_vol',
       'final_heuristic_70_prophet_vol', 'final_heuristic_70_prophet_value',
       'final_heuristic_70_prophet_value_2',
       'final_heuristic_70_prophet_vol_2', 'Prophet Bias Bucket',
       'RF Bias Bucket', 'Heuristic Prophet Bias Bucket',
       'Heuristic Prophet RF Bucket', 'Prophet 60%ile Bias Bucket',
       'Heuristic Prophet 60%ile Bias Bucket', 'Prophet 70%ile Bias Bucket',
       'Heuristic Prophet 70%ile Bias Bucket', 'P3M_non_seasonal',
       'P6M_non_seasonal', 'P3M_non_seasonal_value', 'P6M_non_seasonal_value',
       'LY_P3M_non_seasonal', 'LY_P6M_non_seasonal',
       'LY_P3M_non_seasonal_value', 'LY_P6M_non_seasonal_value',
       'non_seasonal_growth', 'final_seasonal_month', 'final_heuristic_value',
       'month_different', 'depot'],
      dtype='object')

In [51]:
offtakes_df.rename(columns = {'run_month_x':'run_month'}, inplace = True)
offtakes_df['run_month'].unique()

<DatetimeArray>
['2026-08-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [52]:
offtakes_df.columns[100:]

Index(['recency_heuristic_60_prophet_vol', 'seasonal_heuristic_60_prophet_vol',
       'non_seasonal_heuristic_60_prophet_vol',
       'final_heuristic_60_prophet_vol', 'final_heuristic_60_prophet_value',
       'final_heuristic_60_prophet_value_2',
       'final_heuristic_60_prophet_vol_2', 'shrink_ratio_70',
       'recency_heuristic_70_prophet_vol', 'seasonal_heuristic_70_prophet_vol',
       'non_seasonal_heuristic_70_prophet_vol',
       'final_heuristic_70_prophet_vol', 'final_heuristic_70_prophet_value',
       'final_heuristic_70_prophet_value_2',
       'final_heuristic_70_prophet_vol_2', 'Prophet Bias Bucket',
       'RF Bias Bucket', 'Heuristic Prophet Bias Bucket',
       'Heuristic Prophet RF Bucket', 'Prophet 60%ile Bias Bucket',
       'Heuristic Prophet 60%ile Bias Bucket', 'Prophet 70%ile Bias Bucket',
       'Heuristic Prophet 70%ile Bias Bucket', 'P3M_non_seasonal',
       'P6M_non_seasonal', 'P3M_non_seasonal_value', 'P6M_non_seasonal_value',
       'LY_P3M_non_seasonal', 'LY_P6M_non_seasonal',
       'LY_P3M_non_seasonal_value', 'LY_P6M_non_seasonal_value',
       'non_seasonal_growth', 'final_seasonal_month', 'final_heuristic_value',
       'month_different', 'depot'],
      dtype='object')

In [53]:
offtakes_df = offtakes_df.groupby(['month_date','platform_name', 'parent_material_code', 'brand_code','portfolio','run_month', 'M month']
                    )[['pred_prophet', 'pred_rf','final_heuristic_value']].sum().reset_index()

In [54]:
offtakes_df.rename(columns = {'final_heuristic_value':'final_heuristic_prophet_value_2'}, inplace = True)

In [55]:
offtakes_df['month_date'] = offtakes_df['month_date'].astype(str)
offtakes_df['run_month'] = offtakes_df['run_month'].astype(str)
offtakes_df.columns

Index(['month_date', 'platform_name', 'parent_material_code', 'brand_code',
       'portfolio', 'run_month', 'M month', 'pred_prophet', 'pred_rf',
       'final_heuristic_prophet_value_2'],
      dtype='object')

In [56]:
upload_df = offtakes_df.copy()

In [57]:
upload_df

,month_date,platform_name,parent_material_code,brand_code,portfolio,run_month,M month,pred_prophet,pred_rf,final_heuristic_prophet_value_2
0,2026-08-31,blinkit,718288,SAFF GOLD,Saffola Oils,2026-08-31,M,66.112869,64.796201,0.971108
1,2026-08-31,blinkit,718310,PCNO(R),CNO,2026-08-31,M,0.200657,0.051654,0.000000
2,2026-08-31,blinkit,718312,PCNO(R),CNO,2026-08-31,M,10.746021,11.856935,0.354705
3,2026-08-31,blinkit,718315,PCNO(R),CNO,2026-08-31,M,0.000000,0.000000,0.000000
4,2026-08-31,blinkit,718317,H&C,Hair Oils,2026-08-31,M,0.008495,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
5497,2027-03-31,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.000000,0.001768
5498,2027-03-31,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.000000,0.001191
5499,2027-03-31,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+7,0.000000,0.000000,0.001632
5500,2027-03-31,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+7,0.000000,0.000000,0.002308
5501,2027-03-31,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+7,0.000000,0.000000,0.009429

In [58]:
upload_df['channel'] = 'QCOM'

In [59]:
upload_df.columns = upload_df.columns.str.upper()
upload_df

,MONTH_DATE,PLATFORM_NAME,PARENT_MATERIAL_CODE,BRAND_CODE,PORTFOLIO,RUN_MONTH,M MONTH,PRED_PROPHET,PRED_RF,FINAL_HEURISTIC_PROPHET_VALUE_2,CHANNEL
0,2026-08-31,blinkit,718288,SAFF GOLD,Saffola Oils,2026-08-31,M,66.112869,64.796201,0.971108,QCOM
1,2026-08-31,blinkit,718310,PCNO(R),CNO,2026-08-31,M,0.200657,0.051654,0.000000,QCOM
2,2026-08-31,blinkit,718312,PCNO(R),CNO,2026-08-31,M,10.746021,11.856935,0.354705,QCOM
3,2026-08-31,blinkit,718315,PCNO(R),CNO,2026-08-31,M,0.000000,0.000000,0.000000,QCOM
4,2026-08-31,blinkit,718317,H&C,Hair Oils,2026-08-31,M,0.008495,0.000000,0.000000,QCOM
...,...,...,...,...,...,...,...,...,...,...,...
5497,2027-03-31,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.000000,0.001768,QCOM
5498,2027-03-31,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.000000,0.001191,QCOM
5499,2027-03-31,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+7,0.000000,0.000000,0.001632,QCOM
5500,2027-03-31,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+7,0.000000,0.000000,0.002308,QCOM
5501,2027-03-31,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+7,0.000000,0.000000,0.009429,QCOM

In [60]:
upload_df[upload_df['MONTH_DATE'] == '2026-09-30']['FINAL_HEURISTIC_PROPHET_VALUE_2'].sum()

34.859430579209175

In [61]:
# push data to snowflake
from snowflake.connector.pandas_tools import write_pandas

write_pandas(dev_conn, upload_df, 
            table_name = "TRN_MIL_DF_OFFTAKES_OUTPUT",
            auto_create_table=True,
            overwrite = False)

(True,
 1,
 5502,
 [('hwougwhlct/file0.txt',
   'LOADED',
   5502,
   5502,
   1,
   0,
   None,
   None,
   None,
   None)])