In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
import pickle

import numpy as np
import pandas as pd

from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from pandas.tseries.offsets import MonthEnd, MonthBegin
from maricovault.MaricoDB import MaricoSnowflake

from joblib import Parallel, delayed

In [2]:
def get_dbconnection(db_name): 

    KEY_VAULT_NAME = "prod-pwd"
    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection

In [3]:
dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

### Helper Functions

In [272]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

def demand_driver_realign_pskus(data, channel):
    """
    Realign the old pskus to new pskus and return updated data.

    Args:
        data: pandas dataframe
        - master dataframe having all the pskus
    
    Return:
        data: pandas dataframe
        - dataframe 
    """
    realignment_data = realignment_df.copy()
    realignment_data.columns = realignment_data.columns.str.lower()
    realignment_data = realignment_data[
        (realignment_data["channel"] == channel)
        | (realignment_data["channel"] == channel + " B2C")
        | (realignment_data["channel"] == "ALL")
    ]

    data["parent_material_code"] = data["parent_material_code"].astype(int)

    for grp, grp_data in realignment_data.groupby(by=["psku old", "asm"]):
        old_psku, old_asm = grp
        new_psku = grp_data["psku new"].values[0]
        if old_asm != "ALL":
            condition = (data["parent_material_code"] == old_psku) & (
                data["asm_area_code"] == old_asm
            )
        else:
            condition = data["parent_material_code"] == old_psku

        data.loc[condition, "parent_material_code"] = new_psku

    return data

### Aggregation

In [4]:
data_query = f"""
    select * from TRN_MIL_DF_HEURISTICS_OUTPUT 
"""
df_heuristics = pd.read_sql(data_query, dev_conn)
df_heuristics

,CHANNEL,PORTFOLIO,BRAND,BRAND CLASS,RUN_MONTH,M MONTH,MONTH,ASM,DEPOT,PSKU,PROPHET VOL,RF_VOL,PROPHET HEURISTIC VOL,RF HEURISTIC VOL
0,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M,2025-11-30,BCE1,D231,718589,5.264959,2.700,5.264959,4.500
1,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+1,2025-12-31,BCE1,D231,718589,4.547336,3.600,4.547336,4.500
2,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+2,2026-01-31,BCE1,D231,718589,7.053803,2.700,7.053803,4.500
3,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+3,2026-02-28,BCE1,D231,718589,5.662848,1.800,5.662848,4.500
4,ECOM,Hair Oils,ADV-AHO-R,B,2025-11-30,M+4,2026-03-31,BCE1,D231,718589,0.000000,2.700,4.500000,4.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282199,QCOM,Male Grooming,SW_HR_WAX,C,2025-10-31,M+1,2025-11-30,QCW2,D461,718836,3.767871,4.908,5.040000,5.040
282200,QCOM,Male Grooming,SW_HR_WAX,C,2025-10-31,M+2,2025-12-31,QCW2,D461,718836,4.907447,4.932,5.040000,5.040
282201,QCOM,Male Grooming,SW_HR_WAX,C,2025-10-31,M+3,2026-01-31,QCW2,D461,718836,4.751205,4.260,5.040000,5.040
282202,QCOM,Male Grooming,SW_HR_WAX,C,2025-10-31,M+4,2026-02-28,QCW2,D461,718836,8.038001,4.776,8.038001,5.040
282203,QCOM,Male Grooming,SW_HR_WAX,C,2025-10-31,M+5,2026-03-31,QCW2,D461,718836,9.564566,5.088,8.736000,5.088

In [274]:
df_heuristics.columns = df_heuristics.columns.str.lower()
df_heuristics['run_month'] = pd.to_datetime(df_heuristics['run_month'])
df_heuristics['month'] = pd.to_datetime(df_heuristics['month'])
df_heuristics

,channel,portfolio,brand,brand class,run_month,m month,month,asm,depot,psku,prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol
0,ECOM,Hair Oils,ADV-AHO-R,B,2025-10-31,M,2025-10-31,BCE1,D231,718589,0.000000,3.085714,4.500000,4.50
1,ECOM,Hair Oils,ADV-AHO-R,B,2025-10-31,M+1,2025-11-30,BCE1,D231,718589,5.322387,3.150000,5.322387,4.50
2,ECOM,Hair Oils,ADV-AHO-R,B,2025-10-31,M+2,2025-12-31,BCE1,D231,718589,4.054349,3.600000,4.500000,4.50
3,ECOM,Hair Oils,ADV-AHO-R,B,2025-10-31,M+3,2026-01-31,BCE1,D231,718589,6.112519,3.600000,6.112519,4.50
4,ECOM,Hair Oils,ADV-AHO-R,B,2025-10-31,M+4,2026-02-28,BCE1,D231,718589,4.983325,4.178571,4.983325,4.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282199,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+1,2025-12-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
282200,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+2,2026-01-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
282201,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+3,2026-02-28,QCW2,D463,810125,NaN,NaN,0.640000,0.64
282202,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+4,2026-03-31,QCW2,D463,810125,NaN,NaN,0.640000,0.64
282203,QCOM,Male Grooming,SW_SGPRF,C,2025-11-30,M+5,2026-04-30,QCW2,D463,810125,NaN,NaN,0.640000,0.64

In [275]:
# delete_query = """
# DELETE FROM TRN_MIL_DF_SHARED
# WHERE "run_month" IN ('2025-12-31', '2026-01-31')
# """

# cur = dev_conn.cursor()
# cur.execute(delete_query)
# cur.close()

In [276]:
data_query = """
SELECT *
FROM TRN_MIL_DF_SHARED
   
"""

df = pd.read_sql(data_query, dev_conn)

In [277]:
df.columns = df.columns.str.lower()
df['run_month'] = pd.to_datetime(df['run_month'])
df['month'] = pd.to_datetime(df['month'])
df

,channel,portfolio,brand,brand class,run_month,m month,month,asm,depot,psku,pred vol (roum)
0,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+1,2026-06-30,AURG,D3A4,718288,4.124703
1,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+2,2026-07-31,AURG,D3A4,718288,5.140667
2,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+3,2026-08-31,AURG,D3A4,718288,3.992805
3,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+4,2026-09-30,AURG,D3A4,718288,4.498084
4,GT,CNO,PCNO(R),A,2026-05-31,M+1,2026-06-30,AURG,D3A4,718299,29.470186
...,...,...,...,...,...,...,...,...,...,...,...
880949,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811219,0.051667
880950,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+1,2026-09-30,MCW2,D463,811220,0.023667
880951,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+2,2026-10-31,MCW2,D463,811220,0.023667
880952,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+3,2026-11-30,MCW2,D463,811220,0.023667
880953,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811220,0.023667

In [278]:
df.groupby(['channel'])['run_month'].max()

channel
ECOM   2025-12-31
GT     2026-08-31
MT     2026-08-31
QCOM   2025-11-30
Name: run_month, dtype: datetime64[ns]

In [279]:
df[(df['month'] == '2026-04-30') & (df['channel']=='GT') & (df['run_month']=='2026-03-31')]['pred vol (roum)'].sum()

5346018.0036901245

In [280]:
# # make sure run_month is datetime
# df["run_month"] = pd.to_datetime(df["run_month"])
# upload_df["run_month"] = pd.to_datetime(upload_df["run_month"])

# # filter condition
# mask = (df["channel"] == "GT") & (df["run_month"] == "2026-01-31")

# # remove those rows
# df_filtered = df.loc[~mask]

# # concat upload_df
# final_df = pd.concat([df_filtered, upload_df], ignore_index=True)

In [281]:
df_heuristics.columns

Index(['channel', 'portfolio', 'brand', 'brand class', 'run_month', 'm month',
       'month', 'asm', 'depot', 'psku', 'prophet vol', 'rf_vol',
       'prophet heuristic vol', 'rf heuristic vol'],
      dtype='object')

In [282]:
df = df.merge(df_heuristics[['channel','asm', 'depot', 'psku', 'run_month', 'month','prophet vol', 'rf_vol',
       'prophet heuristic vol', 'rf heuristic vol']], on = ['channel','asm', 'depot', 'psku', 'run_month', 'month'],
       how = 'left')

In [283]:
df.isnull().sum()

channel                       0
portfolio                     0
brand                         0
brand class                 422
run_month                     0
m month                       0
month                         0
asm                           0
depot                         0
psku                          0
pred vol (roum)               0
prophet vol              675175
rf_vol                   675175
prophet heuristic vol    638895
rf heuristic vol         638895
dtype: int64

In [284]:
# df = df[df['Month'] == '2025-12-01']
# df

In [285]:
import numpy as np

df['final_channel'] = np.where(
    df['channel'].isin(['QCOM', 'GT']),
    df['channel'],
    np.where(
        df['channel'].isin(['ECOM', 'MT']) &
        df['asm'].astype(str).str.startswith('B'),
        'B2B',
        df['channel']
    )
)
df

,channel,portfolio,brand,brand class,run_month,m month,month,asm,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol,final_channel
0,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+1,2026-06-30,AURG,D3A4,718288,4.124703,NaN,NaN,NaN,NaN,GT
1,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+2,2026-07-31,AURG,D3A4,718288,5.140667,NaN,NaN,NaN,NaN,GT
2,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+3,2026-08-31,AURG,D3A4,718288,3.992805,NaN,NaN,NaN,NaN,GT
3,GT,Saffola Oils,SAFF GOLD,A,2026-05-31,M+4,2026-09-30,AURG,D3A4,718288,4.498084,NaN,NaN,NaN,NaN,GT
4,GT,CNO,PCNO(R),A,2026-05-31,M+1,2026-06-30,AURG,D3A4,718299,29.470186,NaN,NaN,NaN,NaN,GT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880949,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811219,0.051667,NaN,NaN,NaN,NaN,MT
880950,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+1,2026-09-30,MCW2,D463,811220,0.023667,NaN,NaN,NaN,NaN,MT
880951,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+2,2026-10-31,MCW2,D463,811220,0.023667,NaN,NaN,NaN,NaN,MT
880952,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+3,2026-11-30,MCW2,D463,811220,0.023667,NaN,NaN,NaN,NaN,MT
880953,MT,Foods,TRU_ELMNT,DBU,2026-08-31,M+4,2026-12-31,MCW2,D463,811220,0.023667,NaN,NaN,NaN,NaN,MT

In [286]:
df.columns

Index(['channel', 'portfolio', 'brand', 'brand class', 'run_month', 'm month',
       'month', 'asm', 'depot', 'psku', 'pred vol (roum)', 'prophet vol',
       'rf_vol', 'prophet heuristic vol', 'rf heuristic vol', 'final_channel'],
      dtype='object')

In [287]:
df = df.groupby(['final_channel', 'portfolio', 'brand', 'brand class', 'run_month', 'm month',
       'month', 'asm', 'depot', 'psku'])[['pred vol (roum)', 'prophet vol',
       'rf_vol', 'prophet heuristic vol', 'rf heuristic vol']].sum().reset_index()#['Channel'].unique()
df.rename(columns = {'final_channel':'channel'}, inplace = True)
df

,channel,portfolio,brand,brand class,run_month,m month,month,asm,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol
0,B2B,0,JH_FRG_L,0x2a,2026-05-31,M+1,2026-06-30,BCN2,D117,734910,0.0,0.000000,0.000000,0.0,0.0
1,B2B,0,JH_FRG_L,0x2a,2026-05-31,M+1,2026-06-30,BCN2,D117,734988,0.0,0.000000,0.000000,0.0,0.0
2,B2B,0,JH_FRG_L,0x2a,2026-05-31,M+1,2026-06-30,BCN2,D117,734993,0.0,0.000000,0.000000,0.0,0.0
3,B2B,0,JH_FRG_L,0x2a,2026-05-31,M+1,2026-06-30,BCN2,D117,734995,0.0,0.000000,0.000000,0.0,0.0
4,B2B,0,JH_FRG_L,0x2a,2026-05-31,M+1,2026-06-30,BCN2,D117,735043,0.0,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869600,QCOM,Skin Care,PURSNS_ML,C,2025-11-30,M+4,2026-03-31,QCW2,D461,809807,0.0,14.685752,2.232000,0.0,0.0
869601,QCOM,Skin Care,PURSNS_ML,C,2025-11-30,M+4,2026-03-31,QCW2,D461,809850,0.0,0.000000,0.120000,0.0,0.0
869602,QCOM,Skin Care,PURSNS_ML,C,2025-11-30,M+4,2026-03-31,QCW2,D461,809865,0.0,0.000000,0.746667,0.0,0.0
869603,QCOM,Skin Care,PURSNS_ML,C,2025-11-30,M+4,2026-03-31,QCW2,D461,809866,0.0,0.000000,0.000000,0.0,0.0
869604,QCOM,Skin Care,PURSNS_ML,C,2025-11-30,M+4,2026-03-31,QCW2,D461,809869,0.0,7.965241,2.448000,0.0,0.0

In [288]:
df[(df['run_month'] == '2026-04-30')]['channel'].unique()

array(['GT', 'MT'], dtype=object)

### Actuals

In [289]:
actuals_query = """
SELECT
    CM.channel_name,
    CM.asm_area_code,
    CM.depot_code,
    MM.parent_material_code,
    MM.material_group_code,
    LAST_DAY(MESR.month_date) AS month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
JOIN
(
    SELECT DISTINCT
        channel_name, 
        asm_area_code,
        customer_code,
        depot_code
    FROM
        mst_customer
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) CM ON MESR.distributor_code = CM.customer_code
WHERE
    month_date BETWEEN '2023-01-31' AND '2026-08-31' AND
    CM.channel_name IN ('MT', 'E-Commerce', 'Q-Commerce', 'GT')
GROUP BY 1, 2, 3, 4, 5, 6
ORDER BY 1, 2, 3, 4, 6
"""

actuals_df = pd.read_sql(
    actuals_query,
    prod_conn
)

In [290]:
actuals_df.columns = actuals_df.columns.str.lower()
actuals_df['month_date'] = pd.to_datetime(actuals_df['month_date'])

In [291]:
actuals_df.head()

,channel_name,asm_area_code,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,E-Commerce,BCE1,D231,718297,PCNO(R),2023-01-31,0.000,0.000,0.808,0.076
1,E-Commerce,BCE1,D231,718297,PCNO(R),2023-02-28,0.229,0.525,0.774,0.229
2,E-Commerce,BCE1,D231,718297,PCNO(R),2023-03-31,0.364,0.549,0.724,0.364
3,E-Commerce,BCE1,D231,718297,PCNO(R),2023-04-30,0.057,0.189,0.282,0.057
4,E-Commerce,BCE1,D231,718297,PCNO(R),2023-05-31,-0.021,0.335,0.528,-0.021

In [292]:
actuals_df.duplicated(subset=['channel_name', 'asm_area_code', 'depot_code', 'parent_material_code','month_date']).sum()

0

In [293]:
# actuals_df['key'] =  actuals_df['asm_area_code'].astype(str) + '_' + actuals_df['depot_code'].astype(str) + '_' + actuals_df['parent_material_code'].astype(str) 
# actuals_df

In [294]:
# actuals_df[(actuals_df['channel_name'] == 'GT') & (actuals_df['month_date']=='2026-02-28')]['key'].nunique()

In [295]:
actuals_df['channel_name'] = actuals_df['channel_name'].replace({
    'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})

In [296]:
actuals_df

,channel_name,asm_area_code,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,ECOM,BCE1,D231,718297,PCNO(R),2023-01-31,0.000,0.000000,0.808,0.076
1,ECOM,BCE1,D231,718297,PCNO(R),2023-02-28,0.229,0.525000,0.774,0.229
2,ECOM,BCE1,D231,718297,PCNO(R),2023-03-31,0.364,0.549000,0.724,0.364
3,ECOM,BCE1,D231,718297,PCNO(R),2023-04-30,0.057,0.189000,0.282,0.057
4,ECOM,BCE1,D231,718297,PCNO(R),2023-05-31,-0.021,0.335000,0.528,-0.021
...,...,...,...,...,...,...,...,...,...,...
2433454,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-04-30,0.000,13.636364,0.000,0.000
2433455,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-05-31,0.000,21.106628,0.000,0.000
2433456,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-06-30,0.000,21.750514,0.000,0.000
2433457,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-08-31,0.000,5.866666,0.000,0.000
2433458,QCOM,QCW2,D463,811564,SAF-MUSLI,2026-08-31,0.000,0.033334,0.000,0.000

In [297]:
import numpy as np

actuals_df['final_channel'] = np.where(
    actuals_df['channel_name'].isin(['QCOM', 'GT']),
    actuals_df['channel_name'],
    np.where(
        actuals_df['channel_name'].isin(['ECOM', 'MT']) &
        actuals_df['asm_area_code'].astype(str).str.startswith('B'),
        'B2B',
        actuals_df['channel_name']
    )
)
actuals_df

,channel_name,asm_area_code,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,final_channel
0,ECOM,BCE1,D231,718297,PCNO(R),2023-01-31,0.000,0.000000,0.808,0.076,B2B
1,ECOM,BCE1,D231,718297,PCNO(R),2023-02-28,0.229,0.525000,0.774,0.229,B2B
2,ECOM,BCE1,D231,718297,PCNO(R),2023-03-31,0.364,0.549000,0.724,0.364,B2B
3,ECOM,BCE1,D231,718297,PCNO(R),2023-04-30,0.057,0.189000,0.282,0.057,B2B
4,ECOM,BCE1,D231,718297,PCNO(R),2023-05-31,-0.021,0.335000,0.528,-0.021,B2B
...,...,...,...,...,...,...,...,...,...,...,...
2433454,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-04-30,0.000,13.636364,0.000,0.000,QCOM
2433455,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-05-31,0.000,21.106628,0.000,0.000,QCOM
2433456,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-06-30,0.000,21.750514,0.000,0.000,QCOM
2433457,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-08-31,0.000,5.866666,0.000,0.000,QCOM
2433458,QCOM,QCW2,D463,811564,SAF-MUSLI,2026-08-31,0.000,0.033334,0.000,0.000,QCOM

In [298]:
actuals_df = actuals_df.groupby(['final_channel', 'asm_area_code', 'depot_code', 'parent_material_code',
       'material_group_code', 'month_date'])[['pri_actuals_vol_rum',
       'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum().reset_index()
actuals_df

,final_channel,asm_area_code,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,B2B,BCE1,D231,702478,PADV-HRCR,2024-09-30,0.0,0.000000,0.0,0.0
1,B2B,BCE1,D231,702478,PADV-HRCR,2024-10-31,0.0,0.000000,0.0,0.0
2,B2B,BCE1,D231,702478,PADV-HRCR,2024-12-31,0.0,0.000000,0.0,0.0
3,B2B,BCE1,D231,705148,NHR-UTTAM,2024-09-30,0.0,0.000000,0.0,0.0
4,B2B,BCE1,D231,705148,NHR-UTTAM,2024-10-31,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
2356000,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-04-30,0.0,13.636364,0.0,0.0
2356001,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-05-31,0.0,21.106628,0.0,0.0
2356002,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-06-30,0.0,21.750514,0.0,0.0
2356003,QCOM,QCW2,D463,811287,PA_RSW_SR,2026-08-31,0.0,5.866666,0.0,0.0
2356004,QCOM,QCW2,D463,811564,SAF-MUSLI,2026-08-31,0.0,0.033334,0.0,0.0

In [299]:
vol_cols = [
    'pri_actuals_vol_rum',
    'pri_apo_plan_vol_rum',
    'sec_apo_plan_vol_rum',
    'sec_actuals_vol_rum'
]

actuals_df[vol_cols] = actuals_df[vol_cols].clip(lower=0)

In [300]:
actuals_df.rename(columns = {'final_channel':'channel_name'}, inplace = True)

In [301]:
tmp_df = pd.DataFrame()

for c in ['GT', 'MT', 'ECOM', 'QCOM','B2B']:
    tmp2_df = actuals_df[actuals_df['channel_name'] == c]
    tmp2_df = demand_driver_realign_pskus(tmp2_df, channel=c)
    tmp_df = pd.concat([tmp_df, tmp2_df], ignore_index=True)

In [302]:
tmp_df.duplicated(subset=['channel_name', 'asm_area_code', 'depot_code', 'parent_material_code','month_date']).sum()

31592

In [303]:
tmp_df['month_date'].unique()

<DatetimeArray>
['2023-02-28 00:00:00', '2023-03-31 00:00:00', '2023-04-30 00:00:00',
 '2023-05-31 00:00:00', '2023-06-30 00:00:00', '2023-07-31 00:00:00',
 '2023-08-31 00:00:00', '2023-09-30 00:00:00', '2023-10-31 00:00:00',
 '2023-11-30 00:00:00', '2023-12-31 00:00:00', '2024-01-31 00:00:00',
 '2024-02-29 00:00:00', '2024-03-31 00:00:00', '2024-04-30 00:00:00',
 '2024-05-31 00:00:00', '2024-06-30 00:00:00', '2024-07-31 00:00:00',
 '2024-08-31 00:00:00', '2024-09-30 00:00:00', '2024-10-31 00:00:00',
 '2024-11-30 00:00:00', '2024-12-31 00:00:00', '2025-01-31 00:00:00',
 '2025-02-28 00:00:00', '2025-03-31 00:00:00', '2025-04-30 00:00:00',
 '2025-05-31 00:00:00', '2025-06-30 00:00:00', '2025-07-31 00:00:00',
 '2025-08-31 00:00:00', '2025-09-30 00:00:00', '2025-10-31 00:00:00',
 '2025-11-30 00:00:00', '2026-01-31 00:00:00', '2026-02-28 00:00:00',
 '2023-01-31 00:00:00', '2025-12-31 00:00:00', '2026-03-31 00:00:00',
 '2026-04-30 00:00:00', '2026-05-31 00:00:00', '2026-06-30 00:00:00',
 '2026-07-31 00:00:00', '2026-08-31 00:00:00']
Length: 44, dtype: datetime64[ns]

In [304]:
tmp_df = tmp_df.groupby(
    ['channel_name', 'asm_area_code', 'depot_code', 
     'parent_material_code', 'month_date'], as_index=False
).sum()

In [305]:
tmp_df.duplicated(subset=['channel_name', 'asm_area_code', 'depot_code', 'parent_material_code','month_date']).sum()

0

In [306]:
actuals_df = tmp_df.copy()

del tmp_df, tmp2_df

In [307]:
actuals_df.head()

,channel_name,asm_area_code,depot_code,parent_material_code,month_date,material_group_code,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,B2B,BCE1,D231,702478,2024-09-30,PADV-HRCR,0.0,0.0,0.0,0.0
1,B2B,BCE1,D231,702478,2024-10-31,PADV-HRCR,0.0,0.0,0.0,0.0
2,B2B,BCE1,D231,702478,2024-12-31,PADV-HRCR,0.0,0.0,0.0,0.0
3,B2B,BCE1,D231,705148,2024-09-30,NHR-UTTAM,0.0,0.0,0.0,0.0
4,B2B,BCE1,D231,705148,2024-10-31,NHR-UTTAM,0.0,0.0,0.0,0.0

In [308]:
actuals_df['sec_actuals_vol_rum'].sum()

242542687.48399988

In [309]:
# actuals_df = actuals_df.groupby(['channel_name', 'depot_code', 'parent_material_code',
#        'material_group_code', 'month_date'])[['pri_actuals_vol_rum',
#        'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum().reset_index()
# actuals_df

In [310]:
# actuals_df[actuals_df['channel_name'] == 'GT'].to_csv('trend_GT.csv')

In [311]:
actuals_df = actuals_df.rename(columns={
    'channel_name': 'channel',
    'asm_area_code': 'asm',
    'depot_code': 'depot',
    'parent_material_code': 'psku',
    'sec_apo_plan_vol_rum': 'Consensus Vol',
    'sec_actuals_vol_rum': 'Actuals Vol'
})

In [312]:
actuals_df.columns

Index(['channel', 'asm', 'depot', 'psku', 'month_date', 'material_group_code',
       'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'Consensus Vol',
       'Actuals Vol'],
      dtype='object')

In [313]:
actuals_df = actuals_df.groupby(['channel', 'depot', 'psku', 'month_date'])[['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'Consensus Vol',
       'Actuals Vol']].sum().reset_index()

In [314]:
df = df.groupby(['channel', 'portfolio', 'brand', 'run_month', 'm month',
       'month', 'depot', 'psku'])[['pred vol (roum)', 'prophet vol',
       'rf_vol', 'prophet heuristic vol', 'rf heuristic vol']].sum().reset_index()

In [315]:
df['psku'] = df['psku'].astype(int)
actuals_df['psku'] = actuals_df['psku'].astype(int)

In [316]:
actuals_df.rename(columns = {'month_date':'month'}, inplace = True)

In [317]:
df

,channel,portfolio,brand,run_month,m month,month,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol
0,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734910,0.0,0.000000,0.000,0.0,0.0
1,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734988,0.0,0.000000,0.000,0.0,0.0
2,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734993,0.0,0.000000,0.000,0.0,0.0
3,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734995,0.0,0.000000,0.000,0.0,0.0
4,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,735043,0.0,0.000000,0.000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
631827,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810406,0.0,0.000000,0.000,0.0,0.0
631828,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810407,0.0,0.000000,0.000,0.0,0.0
631829,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,808489,0.0,9.892327,4.895,0.0,0.0
631830,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809750,0.0,0.000000,0.000,0.0,0.0
631831,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809866,0.0,0.000000,0.000,0.0,0.0

In [318]:
# duplicates = actuals_df[actuals_df.duplicated(subset=['channel','depot_code', 'parent_material_code','month_date'], keep=False)]

# # Get indices of duplicates that are NOT PABABY_ML
# indices_to_drop = duplicates[duplicates['material_group_code'] != 'PABABY_ML'].index

# # Remove those rows
# actuals_df = actuals_df.drop(indices_to_drop)

# # Verify no duplicates remain
# print(actuals_df.duplicated(subset=['channel','depot_code', 'parent_material_code','month_date']).sum())

In [319]:
actuals_df[actuals_df.duplicated(subset=['channel', 'depot', 'psku', 'month'], keep=False)]

Empty DataFrame
Columns: [channel, depot, psku, month, pri_actuals_vol_rum, pri_apo_plan_vol_rum, Consensus Vol, Actuals Vol]
Index: []

In [320]:
len_before_merge = len(df)
df = df.merge(
    actuals_df.drop([ 'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum'], axis=1),
    on=['channel', 'depot', 'psku', 'month'],
    how='left'
)
assert len_before_merge == len(df)
del len_before_merge

In [321]:
df

,channel,portfolio,brand,run_month,m month,month,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol,Consensus Vol,Actuals Vol
0,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734910,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
1,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734988,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
2,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734993,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
3,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734995,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
4,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,735043,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631827,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810406,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
631828,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810407,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
631829,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,808489,0.0,9.892327,4.895,0.0,0.0,NaN,NaN
631830,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809750,0.0,0.000000,0.000,0.0,0.0,NaN,NaN
631831,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809866,0.0,0.000000,0.000,0.0,0.0,NaN,NaN

In [322]:
df[(df['channel'] == 'GT') & (df['month'] == '2026-05-31') & (df['run_month'] == '2026-04-30')]['pred vol (roum)'].sum()

5198880.692278133

In [323]:
df[(df['channel'] == 'GT') & (df['Actuals Vol'].isna())]#['pred vol (roum)'].sum()#.isnull().sum()

,channel,portfolio,brand,run_month,m month,month,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol,Consensus Vol,Actuals Vol
147036,GT,0,PA_CN_HGO,2026-07-31,M+2,2026-09-30,D674,735655,62.46000,0.0,0.0,0.0,0.0,NaN,NaN
147037,GT,0,PA_CN_HGO,2026-07-31,M+2,2026-09-30,D674,735666,55.33500,0.0,0.0,0.0,0.0,NaN,NaN
147038,GT,0,PA_CN_HGO,2026-07-31,M+2,2026-09-30,D674,735667,55.57500,0.0,0.0,0.0,0.0,NaN,NaN
147039,GT,0,PA_CN_HGO,2026-07-31,M+2,2026-09-30,D674,735668,55.33500,0.0,0.0,0.0,0.0,NaN,NaN
147040,GT,0,PA_CN_HGO,2026-07-31,M+2,2026-09-30,D674,735670,40.59000,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374889,GT,Skin Care,PAD_BDYOL,2026-08-31,M+3,2026-11-30,D676,719118,0.00000,0.0,0.0,0.0,0.0,NaN,NaN
374890,GT,Skin Care,PAD_BDYOL,2026-08-31,M+4,2026-12-31,D115,719118,0.00000,0.0,0.0,0.0,0.0,NaN,NaN
374891,GT,Skin Care,PAD_BDYOL,2026-08-31,M+4,2026-12-31,D231,719117,2.34418,0.0,0.0,0.0,0.0,NaN,NaN
374892,GT,Skin Care,PAD_BDYOL,2026-08-31,M+4,2026-12-31,D463,719116,0.00000,0.0,0.0,0.0,0.0,NaN,NaN
374893,GT,Skin Care,PAD_BDYOL,2026-08-31,M+4,2026-12-31,D676,719118,0.00000,0.0,0.0,0.0,0.0,NaN,NaN

In [324]:
# actuals_df[(actuals_df['asm'] == 'KARN') & (actuals_df['psku'] == 718314)]
actuals_df['key'] =  actuals_df['depot'] + actuals_df['psku'].astype(str)
df['key'] = df['depot'] + df['psku'].astype(str)

In [325]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [326]:
qtr_ind_rate_df[qtr_ind_rate_df['brand_code'] == 'PCNO(R)']

   month_date brand_code  qtr_ind_rate
73 2027-03-31    PCNO(R)  349274.00142

In [327]:
len_before_merge = len(df)
df = df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'brand', 'qtr_ind_rate': 'Index Rate'}
    ),
    on=['brand'], 
    how='left'
)
assert len_before_merge == len(df)
del len_before_merge

In [328]:
df['brand'].unique()

array(['JH_FRG_L', 'PA_SHMP_R', 'PA_SHMP_S', 'NHR-UTTAM', 'PCNO FLEX',
       'PCNO(R)', 'CO_SO_VCN', 'SAF-MUSLI', 'SAFF OATS', 'SAFF SALT',
       'SAFF_ODLS', 'SAF_HONEY', 'SAF_MAYO', 'SAF_MILET', 'SAF_PNBTR',
       'SFOAT-CUP', 'SFOATS-FL', 'SFOATS_MG', 'SF_IM_CHY', 'SF_MNCHPS',
       'SF_SOYACN', 'ADV-AHO-R', 'H&C', 'H&C_ALMND', 'NHR NSJ H',
       'NHR-SABDM', 'NHRN_ALMD', 'NHR_ALOAM', 'NHR_SSAHO', 'NIHAR NHO',
       'PA-ALO-HO', 'PADV-HOT', 'PADVJAS-R', 'PADV_AMRO', 'PADV_SMPN',
       'PA_AMVITE', 'PA_CN_HO', 'PA_EXT_ML', 'PA_JASGLD', 'P_AL_GOLD',
       'P_EN_ALM', 'P_EN_BGHB', 'P_EN_CRSH', 'P_EN_RSMR', 'JH_HCR_KG',
       'JH_HCR_L', 'JH_SCR_KG', 'JH_SCR_L', 'BRD_BDOIL', 'BRD_BDSPR',
       'BRD_DOGAS', 'BRD_FSWSH', 'BRD_HROIL', 'BRD_HRWAX', 'BRD_PERFM',
       'PADV-HRCR', 'SW HRGEL', 'SW HSPRY', 'SW NOGAS', 'SW STLDEO',
       'SW_HR_WAX', 'NHR_VTEHO', 'LVN_SHMP', 'MALO-NATU', 'MALT-NATU',
       'REV.LQDST', 'REV.ST.', 'REV_LQFRG', 'HC SNS', 'LIVON',
       'LIVON S-R', 'LVN_SR_DR', 'SAFF ACTV', 'SAFF GOLD', 'SAFF KO',
       'SAFF KOCO', 'BIO OILS', 'PA-BDYLOT', 'SFOATS_GD', 'H&C DFOIL',
       'HC_PBHOIL', 'HC_PBSMP', 'NHR_ALDHO', 'NHR_AMLGD', 'NHR_RSHO',
       'NHR_SSBHO', 'PA_EN_ML', 'PA_ESS_HO', 'PA_ONI_HO', 'PA_SRM_R',
       'P_EN_ARG', 'RK_CLO_R', 'SW_HR_PWD', 'SW_SGPRF', 'HC_OSRM_R',
       'LIVON 2.0', 'LVNPST_ML', 'LVN_PRFSR', 'LVN_SRSNS', 'PADV_SWGL',
       'PA_HR_MSK', 'P_GOHR_SR', 'SAF_CDPRS', 'CO_SO_BL', 'CO_SO_PCP',
       'KAYA_GM', 'KAYA_ML', 'PABABY_CM', 'PABABY_GM', 'PABABY_ML',
       'PABABY_SP', 'PURSNS_GM', 'PURSNS_ML', 'PA_CN_HGO', 'SFOATS-PR',
       'KERALA', 'NIHAR(R)', 'OILOFMAL', 'PLX_APVGR', 'PLX_TDRCN',
       'TRU_ELMNT', 'NHR_ALOHO', 'NHR_NEH', 'NHR_SSMHO', 'PADVJAS-F',
       'PA_JAS_GD', 'JH_MKP_KG', 'BRD_FCSRB', 'BRD_HRSPR', 'BRD_POMSK',
       'NHR_AD_HO', 'NHR_UT_GD', 'NHR_UT_HO', 'OOM_AD_HO', 'OOM_GD_HO',
       'PA_GD_PLS', 'PA_NOR_HO', 'HC SNS-B', 'HC_OSRM_S', 'PAD_BDYOL',
       '4700_BCPC', 'PA_AD_CND', 'PA_RSW_SR', 'SF_MNMKHN', 'JH_MKP_L'],
      dtype=object)

In [329]:
df

,channel,portfolio,brand,run_month,m month,month,depot,psku,pred vol (roum),prophet vol,rf_vol,prophet heuristic vol,rf heuristic vol,Consensus Vol,Actuals Vol,key,Index Rate
0,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734910,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D117734910,NaN
1,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734988,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D117734988,NaN
2,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734993,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D117734993,NaN
3,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734995,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D117734995,NaN
4,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,735043,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D117735043,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631827,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810406,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D674810406,1779.273746
631828,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D674,810407,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D674810407,1779.273746
631829,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,808489,0.0,9.892327,4.895,0.0,0.0,NaN,NaN,D676808489,1779.273746
631830,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809750,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D676809750,1779.273746
631831,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+4,2026-03-31,D676,809866,0.0,0.000000,0.000,0.0,0.0,NaN,NaN,D676809866,1779.273746

In [330]:
df.isna().sum()

channel                       0
portfolio                     0
brand                         0
run_month                     0
m month                       0
month                         0
depot                         0
psku                          0
pred vol (roum)               0
prophet vol                   0
rf_vol                        0
prophet heuristic vol         0
rf heuristic vol              0
Consensus Vol            228851
Actuals Vol              228851
key                           0
Index Rate                  228
dtype: int64

In [331]:
df['Consensus Vol'] = df['Consensus Vol'].fillna(0)
df['Actuals Vol'] = df['Actuals Vol'].fillna(0)

In [332]:
df.columns

Index(['channel', 'portfolio', 'brand', 'run_month', 'm month', 'month',
       'depot', 'psku', 'pred vol (roum)', 'prophet vol', 'rf_vol',
       'prophet heuristic vol', 'rf heuristic vol', 'Consensus Vol',
       'Actuals Vol', 'key', 'Index Rate'],
      dtype='object')

In [333]:
df.rename(columns={'pred vol (roum)': 'Stat Vol'}, inplace=True)

In [334]:
df['Stat Val'] = df['Stat Vol'] * df['Index Rate'] / (10 ** 7)
df['Consensus Val'] = df['Consensus Vol'] * df['Index Rate'] / (10 ** 7)
df['Actuals Val'] = df['Actuals Vol'] * df['Index Rate'] / (10 ** 7)

In [335]:
# df[(df['channel'] == 'GT') & (df['Actuals Vol'].isna()) & (df['run_month'] == '2026-03-31') & (df['m month'] == 'M+1')]['Stat Val'].sum()

In [336]:
df[(df['run_month'] == '2026-06-30') & (df['m month'] == 'M+1') & (df['channel'] == 'GT')]['Stat Val'].sum()

419.73863614950733

In [337]:
df['Stat Error'] = df['Stat Val'] - df['Actuals Val']
df['Consensus Error'] = df['Consensus Val'] - df['Actuals Val']

df['Stat Abs Error'] = np.abs(df['Stat Error'])
df['Consensus Abs Error'] = np.abs(df['Consensus Error'])

In [338]:
df.columns

Index(['channel', 'portfolio', 'brand', 'run_month', 'm month', 'month',
       'depot', 'psku', 'Stat Vol', 'prophet vol', 'rf_vol',
       'prophet heuristic vol', 'rf heuristic vol', 'Consensus Vol',
       'Actuals Vol', 'key', 'Index Rate', 'Stat Val', 'Consensus Val',
       'Actuals Val', 'Stat Error', 'Consensus Error', 'Stat Abs Error',
       'Consensus Abs Error'],
      dtype='object')

In [339]:
for col in ['prophet vol', 'rf_vol',
       'prophet heuristic vol', 'rf heuristic vol']:
    df[f'{col}_value'] = df[col] * df['Index Rate'] / (10 ** 7)

In [340]:
df['stat_bias'] = df['Stat Error']/df['Actuals Val']

In [341]:
df = df.fillna(0)

In [342]:
df['run_month'].unique()

<DatetimeArray>
['2026-05-31 00:00:00', '2026-06-30 00:00:00', '2026-07-31 00:00:00',
 '2026-08-31 00:00:00', '2025-10-31 00:00:00', '2025-11-30 00:00:00',
 '2025-12-31 00:00:00', '2026-01-31 00:00:00', '2026-02-28 00:00:00',
 '2026-03-31 00:00:00', '2026-04-30 00:00:00']
Length: 11, dtype: datetime64[ns]

In [343]:
df = df[df['m month'] == 'M+1']#.isnull().sum()

In [344]:
import numpy as np
import pandas as pd

df['stat_bias'] = (
    df['stat_bias']
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

bins = [-np.inf, -0.15, -0.10, -0.05, 0, 0.05, 0.10, 0.15, np.inf]
labels = [
    '< -15%',
    '-15% to -10%',
    '-10% to -5%',
    '-5% to 0%',
    '0% to 5%',
    '5% to 10%',
    '10% to 15%',
    '> 15%'
]

df['stat_bias_bucket'] = pd.cut(
    df['stat_bias'],
    bins=bins,
    labels=labels,
    right=False   # e
)

In [345]:
df

,channel,portfolio,brand,run_month,m month,month,depot,psku,Stat Vol,prophet vol,...,Stat Error,Consensus Error,Stat Abs Error,Consensus Abs Error,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,stat_bias,stat_bias_bucket
0,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734910,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
1,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734988,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
2,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734993,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
3,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734995,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
4,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,735043,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631413,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+1,2025-12-31,D674,810406,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
631414,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+1,2025-12-31,D674,810407,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
631415,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+1,2025-12-31,D676,808489,0.0,23.308381,...,0.0,0.0,0.0,0.0,0.004147,0.001373,0.0,0.0,0.0,0% to 5%
631416,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+1,2025-12-31,D676,809750,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%
631417,QCOM,Skin Care,PURSNS_ML,2025-11-30,M+1,2025-12-31,D676,809866,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0% to 5%

In [346]:
df['forecast_granularity'] = 'Depot x PSKU'
df['forecast_type'] = 'secondary'

In [347]:
cols = ['forecast_granularity', 'forecast_type'] + [
    c for c in df.columns
    if c not in ['forecast_granularity', 'forecast_type']
]

df = df[cols]

In [348]:
df['run_month'].unique()

<DatetimeArray>
['2026-05-31 00:00:00', '2026-06-30 00:00:00', '2026-07-31 00:00:00',
 '2026-08-31 00:00:00', '2025-10-31 00:00:00', '2025-11-30 00:00:00',
 '2025-12-31 00:00:00', '2026-01-31 00:00:00', '2026-02-28 00:00:00',
 '2026-03-31 00:00:00', '2026-04-30 00:00:00']
Length: 11, dtype: datetime64[ns]

### Qcom

### Helper Functions

In [349]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

# realignment_df = realignment_df[
#     realignment_df['channel'].isin(['QCOM', 'QCOM B2C', 'ALL'])]


def realign_pskus(data, column, channel='QCOM'):
    realignment_data = realignment_df.copy()
    realignment_data = realignment_data[
        realignment_data['channel'].isin([channel, channel + ' B2C', 'ALL'])
    ]

    assert realignment_data['psku old'].dtype == 'int64'
    assert realignment_data['psku new'].dtype == 'int64'
    realignment_data = realignment_data[['psku old', 'psku new']].drop_duplicates()
    realignment_data = realignment_data.set_index('psku old').to_dict()['psku new']

    
    data[column] = data[column].astype(int)

    for old_psku, new_psku in realignment_data.items():
        data.loc[
            data[column] == old_psku, column
        ] = new_psku

    return data

### Forecast

In [350]:
qcom_df = pd.read_sql(
    """select * from TRN_MIL_DF_OFT2PRIM_SHARED""",
    dev_conn
)
qcom_df.columns = qcom_df.columns.str.lower()
qcom_df['run_month'] = pd.to_datetime(qcom_df['run_month'])
qcom_df['month'] = pd.to_datetime(qcom_df['month'])

In [351]:
qcom_df#[qcom_df['Channel']=='Ecom']

,month,depot,psku,brand,portfolio,m month,run_month,calculated primary vol,channel
0,2026-04-30,D111,709567,SAFF OATS,Foods,M+1,2026-03-31,0.0,Ecom
1,2026-04-30,D111,718288,SAFF GOLD,Saffola Oils,M+1,2026-03-31,0.0,Ecom
2,2026-04-30,D111,718297,PCNO(R),CNO,M+1,2026-03-31,0.0,Ecom
3,2026-04-30,D111,718299,PCNO(R),CNO,M+1,2026-03-31,0.0,Ecom
4,2026-04-30,D111,718303,REV.LQDST,Others,M+1,2026-03-31,0.0,Ecom
...,...,...,...,...,...,...,...,...,...
735999,2026-09-30,d677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM
736000,2026-09-30,d677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM
736001,2026-09-30,d677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.0,QCOM
736002,2026-09-30,d677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.0,QCOM
736003,2026-09-30,d677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.0,QCOM

### Actuals

In [352]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

# realignment_df = realignment_df[
#     realignment_df['channel'].isin(['QCOM', 'QCOM B2C', 'ALL'])]


def realign_pskus(data, column, channel='QCOM'):
    realignment_data = realignment_df.copy()
    realignment_data = realignment_data[
        realignment_data['channel'].isin([channel, channel + ' B2C', 'ALL'])
    ]

    assert realignment_data['psku old'].dtype == 'int64'
    assert realignment_data['psku new'].dtype == 'int64'
    realignment_data = realignment_data[['psku old', 'psku new']].drop_duplicates()
    realignment_data = realignment_data.set_index('psku old').to_dict()['psku new']

    
    data[column] = data[column].astype(int)

    for old_psku, new_psku in realignment_data.items():
        data.loc[
            data[column] == old_psku, column
        ] = new_psku

    return data

In [353]:
depot_psku_primary_query = """
SELECT
    CM.depot_code,
    MM.parent_material_code,
    MM.material_group_code,
    LAST_DAY(MESR.month_date) AS month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Grofers', 'Zepto', 'Kiranakart Technologies', 'Swiggy', 'ZEPTO')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
JOIN
(
    SELECT DISTINCT
        customer_code,
        depot_code
    FROM
        mst_customer
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) CM on MESR.distributor_code = CM.customer_code
where month_date BETWEEN '2023-01-01' AND '2026-08-31' 
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""

depot_psku_primary_df = pd.read_sql(
    depot_psku_primary_query,
    prod_conn
)
depot_psku_primary_df.columns = depot_psku_primary_df.columns.str.lower()
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)
depot_psku_primary_df['month_date'] = pd.to_datetime(depot_psku_primary_df['month_date'])
depot_psku_primary_df = realign_pskus(depot_psku_primary_df.copy(), 'parent_material_code')
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['depot_code', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['parent_material_code'] != 715096]
depot_psku_primary_df.duplicated(subset=['depot_code', 'parent_material_code', 'month_date']).sum()
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if depot_psku_primary_df[col].min() < 0:
        print(col)

for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].clip(lower=0)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [354]:
depot_psku_primary_df['channel'] = 'QCOM'
depot_psku_primary_df_qcom = depot_psku_primary_df.copy()

In [355]:
# depot_psku_primary_df_qcom.to_csv('Trend_qcom.csv')

In [356]:
depot_psku_primary_query = """
SELECT
    CM.depot_code,
    MM.parent_material_code,
    MM.material_group_code,
    LAST_DAY(MESR.month_date) AS month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Flipkart-National', 'Flipkart-Grocery', 'Big basket B2C', 'RK WORLDINFOCOM', 'Amazon B2C', 
        'FATEHPURIA HYGIENE', 'Nykaa', 'Flipkart-Minutes', 'Purplle', 'Myntra', 'Dealshare', 'FlipkartGrocery', 'City Mall', '1MG', 
        'ARIPL', 'First Cry', 'Meesho', 'RKWorld', 'CITIMALL', 'Firstcry', 'EMAZING DEALS', 'MYNTRA')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
JOIN
(
    SELECT DISTINCT
        customer_code,
        depot_code
    FROM
        mst_customer
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) CM on MESR.distributor_code = CM.customer_code
where month_date BETWEEN '2025-12-01' AND '2026-08-31' 
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""

depot_psku_primary_df = pd.read_sql(
    depot_psku_primary_query,
    prod_conn
)
depot_psku_primary_df.columns = depot_psku_primary_df.columns.str.lower()
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)
depot_psku_primary_df['month_date'] = pd.to_datetime(depot_psku_primary_df['month_date'])
depot_psku_primary_df = realign_pskus(depot_psku_primary_df.copy(), 'parent_material_code', channel='ECOM')
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['depot_code', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['parent_material_code'] != 715096]
depot_psku_primary_df.duplicated(subset=['depot_code', 'parent_material_code', 'month_date']).sum()
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if depot_psku_primary_df[col].min() < 0:
        print(col)

for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].clip(lower=0)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [357]:
depot_psku_primary_df['channel'] = 'ECOM'
depot_psku_primary_df_ecom = depot_psku_primary_df.copy()

In [358]:
depot_psku_primary_df = pd.concat([depot_psku_primary_df_qcom, depot_psku_primary_df_ecom], ignore_index=True)
depot_psku_primary_df

,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,channel
0,D112,715098,CO_SO_PCP,2023-07-31,0.0,0.000000,1.762,0.0,QCOM
1,D112,715098,CO_SO_PCP,2023-08-31,0.0,0.000000,1.762,0.0,QCOM
2,D112,715099,CO_SO_PCP,2023-07-31,0.0,0.000000,1.762,0.0,QCOM
3,D112,715099,CO_SO_PCP,2023-08-31,0.0,0.000000,1.762,0.0,QCOM
4,D112,715100,CO_SO_PCP,2023-02-28,0.0,0.000000,0.284,0.0,QCOM
...,...,...,...,...,...,...,...,...,...
198565,D677,811416,SAF-MUSLI,2026-07-31,0.0,0.036558,0.000,0.0,ECOM
198566,D677,811416,SAF-MUSLI,2026-08-31,0.0,0.028122,0.000,0.0,ECOM
198567,D677,811529,LVN_SHMP,2026-08-31,0.0,49.321646,0.000,0.0,ECOM
198568,D677,811530,LVN_SHMP,2026-08-31,0.0,49.321646,0.000,0.0,ECOM
198569,D677,811564,SAF-MUSLI,2026-08-31,0.0,0.058064,0.000,0.0,ECOM

In [359]:
actuals_df = depot_psku_primary_df.copy()

In [360]:
actuals_df.duplicated(subset=['channel','depot_code', 'parent_material_code','month_date']).sum()

457

In [361]:
# For duplicates, keep only the row with PABABY_ML material_group_code
duplicates = actuals_df[actuals_df.duplicated(subset=['channel','depot_code', 'parent_material_code','month_date'], keep=False)]

# Get indices of duplicates that are NOT PABABY_ML
indices_to_drop = duplicates[duplicates['material_group_code'] != 'PABABY_ML'].index

# Remove those rows
actuals_df = actuals_df.drop(indices_to_drop)

# Verify no duplicates remain
print(actuals_df.duplicated(subset=['channel','depot_code', 'parent_material_code','month_date']).sum())

0

In [362]:
actuals_df = actuals_df.groupby(['channel','depot_code', 'parent_material_code',
       'material_group_code', 'month_date'])[['pri_actuals_vol_rum',
       'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum().reset_index()
actuals_df

,channel,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,ECOM,D112,718287,PCNO(R),2025-12-31,0.0,0.020856,0.0000,0.0
1,ECOM,D112,718287,PCNO(R),2026-08-31,0.0,0.001664,0.0000,0.0
2,ECOM,D112,718288,SAFF GOLD,2026-03-31,0.0,0.000000,1.9086,0.0
3,ECOM,D112,718288,SAFF GOLD,2026-05-31,0.0,0.023180,0.0000,0.0
4,ECOM,D112,718299,PCNO(R),2026-04-30,0.0,0.030712,0.0618,0.0
...,...,...,...,...,...,...,...,...,...
197789,QCOM,D677,811287,PA_RSW_SR,2026-04-30,0.0,8.823530,0.0000,0.0
197790,QCOM,D677,811287,PA_RSW_SR,2026-05-31,0.0,14.774640,0.0000,0.0
197791,QCOM,D677,811287,PA_RSW_SR,2026-06-30,0.0,16.026694,0.0000,0.0
197792,QCOM,D677,811287,PA_RSW_SR,2026-08-31,2.4,20.454898,0.0000,2.4
197793,QCOM,D677,811564,SAF-MUSLI,2026-08-31,0.0,0.017648,0.0000,0.0

In [363]:
actuals_df.columns

Index(['channel', 'depot_code', 'parent_material_code', 'material_group_code',
       'month_date', 'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum',
       'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum'],
      dtype='object')

In [364]:
actuals_df = actuals_df.rename(columns={
    'depot_code': 'depot',
    'parent_material_code': 'psku',
    'sec_apo_plan_vol_rum': 'Consensus Vol',
    'sec_actuals_vol_rum': 'Actuals Vol',
    'month_date': 'month'
})

In [365]:
actuals_df.head()

,channel,depot,psku,material_group_code,month,pri_actuals_vol_rum,pri_apo_plan_vol_rum,Consensus Vol,Actuals Vol
0,ECOM,D112,718287,PCNO(R),2025-12-31,0.0,0.020856,0.0000,0.0
1,ECOM,D112,718287,PCNO(R),2026-08-31,0.0,0.001664,0.0000,0.0
2,ECOM,D112,718288,SAFF GOLD,2026-03-31,0.0,0.000000,1.9086,0.0
3,ECOM,D112,718288,SAFF GOLD,2026-05-31,0.0,0.023180,0.0000,0.0
4,ECOM,D112,718299,PCNO(R),2026-04-30,0.0,0.030712,0.0618,0.0

In [366]:
#qcom_df.rename(columns = {'Channel':'channel'}, inplace = True)

In [367]:
qcom_df['psku'] = qcom_df['psku'].astype(int)
actuals_df['psku'] = actuals_df['psku'].astype(int)

In [368]:
# actuals_df = actuals_df[actuals_df['month_date'] == '2025-12-31']
# actuals_df

In [369]:
qcom_df['run_month'].unique()

<DatetimeArray>
['2026-03-31 00:00:00', '2026-04-30 00:00:00', '2026-05-31 00:00:00',
 '2026-06-30 00:00:00', '2025-11-30 00:00:00', '2025-12-31 00:00:00',
 '2026-01-31 00:00:00', '2026-02-28 00:00:00', '2026-07-31 00:00:00',
 '2026-08-31 00:00:00']
Length: 10, dtype: datetime64[ns]

In [370]:
qcom_df['channel'] = qcom_df['channel'].str.upper()
qcom_df['depot'] = qcom_df['depot'].str.upper()

qcom_df

,month,depot,psku,brand,portfolio,m month,run_month,calculated primary vol,channel
0,2026-04-30,D111,709567,SAFF OATS,Foods,M+1,2026-03-31,0.0,ECOM
1,2026-04-30,D111,718288,SAFF GOLD,Saffola Oils,M+1,2026-03-31,0.0,ECOM
2,2026-04-30,D111,718297,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM
3,2026-04-30,D111,718299,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM
4,2026-04-30,D111,718303,REV.LQDST,Others,M+1,2026-03-31,0.0,ECOM
...,...,...,...,...,...,...,...,...,...
735999,2026-09-30,D677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM
736000,2026-09-30,D677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM
736001,2026-09-30,D677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.0,QCOM
736002,2026-09-30,D677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.0,QCOM
736003,2026-09-30,D677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.0,QCOM

In [371]:
len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    actuals_df.drop([ 'material_group_code', 'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum'], axis=1),
    on=['channel','depot', 'psku', 'month'],
    how='left'
)
assert len_before_merge == len(qcom_df)
del len_before_merge

In [372]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [373]:
len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'brand', 'qtr_ind_rate': 'Index Rate'}
    ),
    on=['brand'], 
    how='left'
)
assert len_before_merge == len(qcom_df)
del len_before_merge

In [374]:
qcom_df.isna().sum()

month                          0
depot                          0
psku                           0
brand                          0
portfolio                      0
m month                        0
run_month                      0
calculated primary vol         0
channel                        0
Consensus Vol             531048
Actuals Vol               531048
Index Rate                     0
dtype: int64

In [375]:
qcom_df['Consensus Vol'] = qcom_df['Consensus Vol'].fillna(0)
qcom_df['Actuals Vol'] = qcom_df['Actuals Vol'].fillna(0)

In [376]:
qcom_df['Consensus Vol'].max()

117954.72709999999

In [377]:
qcom_df.rename(columns={'calculated primary vol': 'Stat Vol'}, inplace=True)
qcom_df

,month,depot,psku,brand,portfolio,m month,run_month,Stat Vol,channel,Consensus Vol,Actuals Vol,Index Rate
0,2026-04-30,D111,709567,SAFF OATS,Foods,M+1,2026-03-31,0.0,ECOM,0.0,0.0,127515.619406
1,2026-04-30,D111,718288,SAFF GOLD,Saffola Oils,M+1,2026-03-31,0.0,ECOM,0.0,0.0,138865.260689
2,2026-04-30,D111,718297,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,0.0,349274.001420
3,2026-04-30,D111,718299,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,0.0,349274.001420
4,2026-04-30,D111,718303,REV.LQDST,Others,M+1,2026-03-31,0.0,ECOM,0.0,0.0,247926.608903
...,...,...,...,...,...,...,...,...,...,...,...,...
735999,2026-09-30,D677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,0.0,12860.631072
736000,2026-09-30,D677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,0.0,12860.631072
736001,2026-09-30,D677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.0,QCOM,0.0,0.0,260000.000000
736002,2026-09-30,D677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.0,QCOM,0.0,0.0,740.000000
736003,2026-09-30,D677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.0,QCOM,0.0,0.0,315513.490535

In [378]:
qcom_df['Stat Val'] = qcom_df['Stat Vol'] * qcom_df['Index Rate'] / (10 ** 7)
qcom_df['Consensus Val'] = qcom_df['Consensus Vol'] * qcom_df['Index Rate'] / (10 ** 7)
qcom_df['Actuals Val'] = qcom_df['Actuals Vol'] * qcom_df['Index Rate'] / (10 ** 7)

In [379]:
qcom_df['channel'].unique()

array(['ECOM', 'QCOM'], dtype=object)

In [380]:
qcom_df[(qcom_df['month'] == '2026-07-31') & (qcom_df['channel']=='ECOM') & (qcom_df['run_month']=='2026-06-30')]['Actuals Val'].sum()

41.36388310924138

In [381]:
qcom_df['Stat Error'] = qcom_df['Stat Val'] - qcom_df['Actuals Val']
qcom_df['Consensus Error'] = qcom_df['Consensus Val'] - qcom_df['Actuals Val']

qcom_df['Stat Abs Error'] = np.abs(qcom_df['Stat Error'])
qcom_df['Consensus Abs Error'] = np.abs(qcom_df['Consensus Error'])

In [382]:
qcom_df['stat_bias'] = qcom_df['Stat Error']/qcom_df['Actuals Val']
qcom_df = qcom_df.fillna(0)

import numpy as np
import pandas as pd

qcom_df['stat_bias'] = (
    qcom_df['stat_bias']
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

bins = [-np.inf, -0.15, -0.10, -0.05, 0, 0.05, 0.10, 0.15, np.inf]
labels = [
    '< -15%',
    '-15% to -10%',
    '-10% to -5%',
    '-5% to 0%',
    '0% to 5%',
    '5% to 10%',
    '10% to 15%',
    '> 15%'
]

qcom_df['stat_bias_bucket'] = pd.cut(
    qcom_df['stat_bias'],
    bins=bins,
    labels=labels,
    right=False  
)

In [383]:
qcom_df.columns = qcom_df.columns.str.lower()
qcom_df

,month,depot,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,index rate,stat val,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket
0,2026-04-30,D111,709567,SAFF OATS,Foods,M+1,2026-03-31,0.0,ECOM,0.0,...,127515.619406,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
1,2026-04-30,D111,718288,SAFF GOLD,Saffola Oils,M+1,2026-03-31,0.0,ECOM,0.0,...,138865.260689,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
2,2026-04-30,D111,718297,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,...,349274.001420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
3,2026-04-30,D111,718299,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,...,349274.001420,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
4,2026-04-30,D111,718303,REV.LQDST,Others,M+1,2026-03-31,0.0,ECOM,0.0,...,247926.608903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735999,2026-09-30,D677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,12860.631072,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
736000,2026-09-30,D677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,12860.631072,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
736001,2026-09-30,D677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,260000.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
736002,2026-09-30,D677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.0,QCOM,0.0,...,740.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
736003,2026-09-30,D677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.0,QCOM,0.0,...,315513.490535,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%

In [384]:
# df = pd.read_excel("/data/aman_singh/acuuracy_check/acc_framework_feb.xlsx")
# df.columns = df.columns.str.lower()
# df = df[df['forecast_granularity']!='Depot x PSKU']

In [385]:
df.columns = df.columns.str.lower()

In [386]:
qcom_df.columns

Index(['month', 'depot', 'psku', 'brand', 'portfolio', 'm month', 'run_month',
       'stat vol', 'channel', 'consensus vol', 'actuals vol', 'index rate',
       'stat val', 'consensus val', 'actuals val', 'stat error',
       'consensus error', 'stat abs error', 'consensus abs error', 'stat_bias',
       'stat_bias_bucket'],
      dtype='object')

In [387]:

qcom_df['forecast_granularity'] = 'Depot x PSKU'
qcom_df['forecast_type'] = 'offtakes_to_primary'
#qcom_df['channel'] = 'QCOM'
qcom_df

,month,depot,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
0,2026-04-30,D111,709567,SAFF OATS,Foods,M+1,2026-03-31,0.0,ECOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
1,2026-04-30,D111,718288,SAFF GOLD,Saffola Oils,M+1,2026-03-31,0.0,ECOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
2,2026-04-30,D111,718297,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
3,2026-04-30,D111,718299,PCNO(R),CNO,M+1,2026-03-31,0.0,ECOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
4,2026-04-30,D111,718303,REV.LQDST,Others,M+1,2026-03-31,0.0,ECOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735999,2026-09-30,D677,811267,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
736000,2026-09-30,D677,811269,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
736001,2026-09-30,D677,811279,SAF_CDPRS,SAFFOLA OILS,M+1,2026-08-31,0.0,QCOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
736002,2026-09-30,D677,811287,PA_RSW_SR,PREM. HAIR NOUR,M+1,2026-08-31,0.0,QCOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary
736003,2026-09-30,D677,811564,SAF-MUSLI,FOODS,M+1,2026-08-31,0.0,QCOM,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%,Depot x PSKU,offtakes_to_primary

In [388]:
qcom_df = qcom_df[qcom_df['m month'] == 'M+1']

In [389]:
df[(df['channel'] == 'MT') & (df['run_month'] == '2026-06-30') & (df['month'] == '2026-07-31')]['stat val'].sum()

121.04096548610876

In [390]:
final_df = pd.concat([df,qcom_df])
final_df

,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month,depot,psku,...,stat error,consensus error,stat abs error,consensus abs error,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,stat_bias,stat_bias_bucket
0,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734910,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
1,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734988,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
2,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734993,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
3,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,734995,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
4,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-05-31,M+1,2026-06-30,D117,735043,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0% to 5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735999,Depot x PSKU,offtakes_to_primary,QCOM,HAIR OILS,PA_ESS_HO,2026-08-31,M+1,2026-09-30,D677,811267,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0% to 5%
736000,Depot x PSKU,offtakes_to_primary,QCOM,HAIR OILS,PA_ESS_HO,2026-08-31,M+1,2026-09-30,D677,811269,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0% to 5%
736001,Depot x PSKU,offtakes_to_primary,QCOM,SAFFOLA OILS,SAF_CDPRS,2026-08-31,M+1,2026-09-30,D677,811279,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0% to 5%
736002,Depot x PSKU,offtakes_to_primary,QCOM,PREM. HAIR NOUR,PA_RSW_SR,2026-08-31,M+1,2026-09-30,D677,811287,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0% to 5%
736003,Depot x PSKU,offtakes_to_primary,QCOM,FOODS,SAF-MUSLI,2026-08-31,M+1,2026-09-30,D677,811564,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0% to 5%

### offtakes

In [391]:
query = """select * from TRN_MIL_DF_OFFTAKES_OUTPUT"""
df_offtakes = pd.read_sql(query, dev_conn)
df_offtakes.columns = df_offtakes.columns.str.lower()
df_offtakes['run_month'] = pd.to_datetime(df_offtakes['run_month'])
df_offtakes['month_date'] = pd.to_datetime(df_offtakes['month_date'])
df_offtakes

,month_date,platform_name,parent_material_code,brand_code,portfolio,run_month,m month,pred_prophet,pred_rf,final_heuristic_prophet_value_2,channel
0,2026-04-30,Amazon ARIPL,718288,SAFF GOLD,Saffola Oils,2026-04-30,M,28.076909,27.69528,0.421023,ECOM
1,2026-04-30,Amazon ARIPL,718321,SAFF KO,Saffola Oils,2026-04-30,M,0.000000,0.00000,0.000000,ECOM
2,2026-04-30,Amazon ARIPL,718322,SAFF KO,Saffola Oils,2026-04-30,M,7.161035,9.86000,0.188237,ECOM
3,2026-04-30,Amazon ARIPL,718323,SF_IMV_MK,Foods,2026-04-30,M,0.000000,0.00000,0.000000,ECOM
4,2026-04-30,Amazon ARIPL,718328,SAFF KOCO,Saffola Oils,2026-04-30,M,3.897973,6.99084,0.113964,ECOM
...,...,...,...,...,...,...,...,...,...,...,...
263735,2027-03-31,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.00000,0.001768,QCOM
263736,2027-03-31,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+7,0.000000,0.00000,0.001191,QCOM
263737,2027-03-31,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+7,0.000000,0.00000,0.001632,QCOM
263738,2027-03-31,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+7,0.000000,0.00000,0.002308,QCOM
263739,2027-03-31,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+7,0.000000,0.00000,0.009429,QCOM

In [392]:
df_offtakes[df_offtakes['run_month'] == '2026-06-30'].groupby(['channel'])['final_heuristic_prophet_value_2'].sum()

channel
ECOM    415.483507
QCOM    182.633027
Name: final_heuristic_prophet_value_2, dtype: float64

In [393]:
df_offtakes['run_month'].unique()

<DatetimeArray>
['2026-04-30 00:00:00', '2026-05-31 00:00:00', '2026-06-30 00:00:00',
 '2026-01-31 00:00:00', '2026-02-28 00:00:00', '2026-03-31 00:00:00',
 '2026-07-31 00:00:00', '2026-08-31 00:00:00']
Length: 8, dtype: datetime64[ns]

In [394]:
query_qcom = """select * from TEMP_TRN_DF_QCOM_OFFTAKE_CHAIN_DEPOT_PSKU
where run_month = '2026-09-30'
and month_date between '2026-01-31' and '2026-08-31'
"""
qcom_df = pd.read_sql(query_qcom, dev_conn)
qcom_df.columns = qcom_df.columns.str.lower()
qcom_df['run_month'] = pd.to_datetime(qcom_df['run_month'])
qcom_df['month_date'] = pd.to_datetime(qcom_df['month_date'])
qcom_df['channel'] = 'QCOM'
qcom_df

,month_date,key,platform_name,depot,parent_material_code,brand_code,vol_in_rum,imputed,run_month,channel
0,2026-01-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.0,1,2026-09-30,QCOM
1,2026-02-28,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.0,1,2026-09-30,QCOM
2,2026-03-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.0,1,2026-09-30,QCOM
3,2026-04-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.0,1,2026-09-30,QCOM
4,2026-05-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.0,1,2026-09-30,QCOM
...,...,...,...,...,...,...,...,...,...,...
86151,2026-04-30,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.0,1,2026-09-30,QCOM
86152,2026-05-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.0,1,2026-09-30,QCOM
86153,2026-06-30,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.0,1,2026-09-30,QCOM
86154,2026-07-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.0,1,2026-09-30,QCOM
86155,2026-08-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.0,1,2026-09-30,QCOM

In [395]:
qcom_df.columns

Index(['month_date', 'key', 'platform_name', 'depot', 'parent_material_code',
       'brand_code', 'vol_in_rum', 'imputed', 'run_month', 'channel'],
      dtype='object')

In [396]:
qcom_df = qcom_df.groupby(['channel', 'run_month', 'month_date', 'platform_name', 'parent_material_code',
       'brand_code'])['vol_in_rum'].sum().reset_index()
qcom_df

,channel,run_month,month_date,platform_name,parent_material_code,brand_code,vol_in_rum
0,QCOM,2026-09-30,2026-01-31,blinkit,718288,SAFF GOLD,62.478
1,QCOM,2026-09-30,2026-01-31,blinkit,718310,PCNO(R),0.001
2,QCOM,2026-09-30,2026-01-31,blinkit,718312,PCNO(R),5.240
3,QCOM,2026-09-30,2026-01-31,blinkit,718315,PCNO(R),0.000
4,QCOM,2026-09-30,2026-01-31,blinkit,718317,H&C,0.000
...,...,...,...,...,...,...,...
6903,QCOM,2026-09-30,2026-08-31,zepto,811019,PADV_WIPS,73.365
6904,QCOM,2026-09-30,2026-08-31,zepto,811021,PABABY_GM,26.788
6905,QCOM,2026-09-30,2026-08-31,zepto,811169,SW_SGPRF,7.280
6906,QCOM,2026-09-30,2026-08-31,zepto,811181,SAF_CDPRS,0.746
6907,QCOM,2026-09-30,2026-08-31,zepto,811287,PA_RSW_SR,36.500

In [397]:
query_ecom = """select * from TRN_DF_ECOM_OFFTAKE_CHAIN_PSKU_NEW
where run_month = '2026-09-30'
and month_date between '2026-01-31' and '2026-08-31'
"""
ecom_df = pd.read_sql(query_ecom, dev_conn)
ecom_df.columns = ecom_df.columns.str.lower()
ecom_df['run_month'] = pd.to_datetime(ecom_df['run_month'])
ecom_df['month_date'] = pd.to_datetime(ecom_df['month_date'])
ecom_df['channel'] = 'ECOM'
ecom_df

,month_date,platform_name,parent_material_code,vol_in_rum,indexbpm,brand_code,imputed,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,...,big_billion_days_lead_2,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,ratio_last_year,quarter,run_month,channel
0,2026-08-31,Amazon ARIPL,718288,40.9920,56.923648,SAFF GOLD,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM
1,2026-08-31,Amazon ARIPL,718322,16.7250,28.236405,SAFF KO,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM
2,2026-08-31,Amazon ARIPL,718328,8.4888,10.495288,SAFF KOCO,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM
3,2026-08-31,Amazon ARIPL,718330,6.6350,8.203308,SAFF KOCO,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM
4,2026-08-31,Amazon ARIPL,718341,22.1560,30.766987,SAFF GOLD,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26258,2026-04-30,Purplle,810674,0.0000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0,0.0,2,2026-09-30,ECOM
26259,2026-05-31,Purplle,810674,0.0000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0,0.0,2,2026-09-30,ECOM
26260,2026-06-30,Purplle,810674,0.0000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0,0.0,2,2026-09-30,ECOM
26261,2026-07-31,Purplle,810674,0.0140,0.001800,PA_ESS_HO,0,0,0,0,...,1,0,0,0,0,1,0.3,3,2026-09-30,ECOM
26262,2026-08-31,Purplle,810674,0.0000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,ECOM

In [398]:
ecom_df = ecom_df[['channel', 'run_month', 'month_date', 'platform_name',
       'parent_material_code', 'brand_code', 'vol_in_rum']]

In [399]:
offtake_actuals = pd.concat([qcom_df, ecom_df], ignore_index=True)
offtake_actuals

,channel,run_month,month_date,platform_name,parent_material_code,brand_code,vol_in_rum
0,QCOM,2026-09-30,2026-01-31,blinkit,718288,SAFF GOLD,62.478
1,QCOM,2026-09-30,2026-01-31,blinkit,718310,PCNO(R),0.001
2,QCOM,2026-09-30,2026-01-31,blinkit,718312,PCNO(R),5.240
3,QCOM,2026-09-30,2026-01-31,blinkit,718315,PCNO(R),0.000
4,QCOM,2026-09-30,2026-01-31,blinkit,718317,H&C,0.000
...,...,...,...,...,...,...,...
33166,ECOM,2026-09-30,2026-04-30,Purplle,810674,PA_ESS_HO,0.000
33167,ECOM,2026-09-30,2026-05-31,Purplle,810674,PA_ESS_HO,0.000
33168,ECOM,2026-09-30,2026-06-30,Purplle,810674,PA_ESS_HO,0.000
33169,ECOM,2026-09-30,2026-07-31,Purplle,810674,PA_ESS_HO,0.014
33170,ECOM,2026-09-30,2026-08-31,Purplle,810674,PA_ESS_HO,0.000

In [400]:
offtake_actuals[offtake_actuals['month_date'] == '2026-08-31'].groupby(['channel'])['vol_in_rum'].sum()

channel
ECOM    374744.849071
QCOM    124852.353110
Name: vol_in_rum, dtype: float64

In [401]:
df_offtakes['run_month'].unique()

<DatetimeArray>
['2026-04-30 00:00:00', '2026-05-31 00:00:00', '2026-06-30 00:00:00',
 '2026-01-31 00:00:00', '2026-02-28 00:00:00', '2026-03-31 00:00:00',
 '2026-07-31 00:00:00', '2026-08-31 00:00:00']
Length: 8, dtype: datetime64[ns]

In [402]:
# df_offtakes = df_offtakes[df_offtakes['run_month'].isin(['2026-02-28', '2026-01-31'])]
df_offtakes = df_offtakes[df_offtakes['m month'] == 'M+1']
#df_offtakes = df_offtakes[(df_offtakes['m month'] == 'M+1') & (df_offtakes['channel'] == 'QCOM')]

df_offtakes

,month_date,platform_name,parent_material_code,brand_code,portfolio,run_month,m month,pred_prophet,pred_rf,final_heuristic_prophet_value_2,channel
3246,2026-05-31,Amazon ARIPL,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,0.421023,ECOM
3247,2026-05-31,Amazon ARIPL,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3248,2026-05-31,Amazon ARIPL,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,0.187607,ECOM
3249,2026-05-31,Amazon ARIPL,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3250,2026-05-31,Amazon ARIPL,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,0.113964,ECOM
...,...,...,...,...,...,...,...,...,...,...,...
259955,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001768,QCOM
259956,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001191,QCOM
259957,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.001632,QCOM
259958,2026-09-30,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.002308,QCOM
259959,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,0.000000,0.00000,0.009429,QCOM

In [403]:
df_offtakes

,month_date,platform_name,parent_material_code,brand_code,portfolio,run_month,m month,pred_prophet,pred_rf,final_heuristic_prophet_value_2,channel
3246,2026-05-31,Amazon ARIPL,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,0.421023,ECOM
3247,2026-05-31,Amazon ARIPL,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3248,2026-05-31,Amazon ARIPL,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,0.187607,ECOM
3249,2026-05-31,Amazon ARIPL,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3250,2026-05-31,Amazon ARIPL,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,0.113964,ECOM
...,...,...,...,...,...,...,...,...,...,...,...
259955,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001768,QCOM
259956,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001191,QCOM
259957,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.001632,QCOM
259958,2026-09-30,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.002308,QCOM
259959,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,0.000000,0.00000,0.009429,QCOM

In [404]:
offtake_actuals['channel'].unique()

array(['QCOM', 'ECOM'], dtype=object)

In [405]:
df_offtakes['channel'].unique()

array(['ECOM', 'QCOM'], dtype=object)

In [406]:
df_offtakes

,month_date,platform_name,parent_material_code,brand_code,portfolio,run_month,m month,pred_prophet,pred_rf,final_heuristic_prophet_value_2,channel
3246,2026-05-31,Amazon ARIPL,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,0.421023,ECOM
3247,2026-05-31,Amazon ARIPL,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3248,2026-05-31,Amazon ARIPL,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,0.187607,ECOM
3249,2026-05-31,Amazon ARIPL,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM
3250,2026-05-31,Amazon ARIPL,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,0.113964,ECOM
...,...,...,...,...,...,...,...,...,...,...,...
259955,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001768,QCOM
259956,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001191,QCOM
259957,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.001632,QCOM
259958,2026-09-30,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.002308,QCOM
259959,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,0.000000,0.00000,0.009429,QCOM

In [407]:
df_offtakes['platform_name'] = df_offtakes['platform_name'].str.lower()
offtake_actuals['platform_name'] = offtake_actuals['platform_name'].str.lower()
df_offtakes['parent_material_code'] = df_offtakes['parent_material_code'].astype(int)
offtake_actuals['parent_material_code'] = offtake_actuals['parent_material_code'].astype(int)

In [408]:
offtake_actuals[['channel', 'platform_name', 'parent_material_code','month_date', 'vol_in_rum']].dtypes

channel                         object
platform_name                   object
parent_material_code             int64
month_date              datetime64[ns]
vol_in_rum                     float64
dtype: object

In [409]:
df_offtakes[['channel', 'platform_name', 'parent_material_code','month_date']].dtypes

channel                         object
platform_name                   object
parent_material_code             int64
month_date              datetime64[ns]
dtype: object

In [410]:
x = df_offtakes.copy()

In [411]:
# df_offtakes = x.copy()

In [412]:
df_offtakes = df_offtakes.merge(
    offtake_actuals[['channel', 'platform_name', 'parent_material_code','month_date', 'vol_in_rum']]
    ,
    on=['channel', 'platform_name', 'parent_material_code','month_date'],
    how='left'
)

In [413]:
df_offtakes.rename(columns={'brand_code':'brand'}, inplace=True)

In [414]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()
len_before_merge = len(df_offtakes)
df_offtakes = df_offtakes.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'brand', 'qtr_ind_rate': 'Index Rate'}
    ),
    on=['brand'], 
    how='left'
)
assert len_before_merge == len(df_offtakes)
del len_before_merge

In [415]:
df_offtakes.rename(columns={'month_date':'month', 'final_heuristic_prophet_value_2':'offtakes_forecasted_value'}, inplace=True)
df_offtakes['offtakes_forecasted_vol'] = df_offtakes['offtakes_forecasted_value'] * (10 ** 7) / df_offtakes['Index Rate']
df_offtakes['offtakes actuals val'] = df_offtakes['vol_in_rum'] * df_offtakes['Index Rate'] / (10 ** 7)
df_offtakes['offtakes error'] = df_offtakes['offtakes actuals val'] - df_offtakes['offtakes_forecasted_value'] 
df_offtakes['offtakes abs error'] = np.abs(df_offtakes['offtakes error'])
df_offtakes

,month,platform_name,parent_material_code,brand,portfolio,run_month,m month,pred_prophet,pred_rf,offtakes_forecasted_value,channel,vol_in_rum,Index Rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error
0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,0.421023,ECOM,NaN,138865.260689,30.318787,NaN,NaN,NaN
1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM,NaN,168827.536176,0.000000,NaN,NaN,NaN
2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,0.187607,ECOM,NaN,168827.536176,11.112333,NaN,NaN,NaN
3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,0.000000,ECOM,NaN,739265.904412,0.000000,NaN,NaN,NaN
4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,0.113964,ECOM,NaN,123636.889888,9.217630,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33145,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001768,QCOM,NaN,12860.631072,1.375000,NaN,NaN,NaN
33146,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001191,QCOM,NaN,12860.631072,0.926333,NaN,NaN,NaN
33147,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.001632,QCOM,NaN,366.484998,44.530000,NaN,NaN,NaN
33148,2026-09-30,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.002308,QCOM,NaN,366.484998,62.988000,NaN,NaN,NaN
33149,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,0.000000,0.00000,0.009429,QCOM,NaN,260000.000000,0.362667,NaN,NaN,NaN

In [416]:
df_offtakes[df_offtakes['channel']=='QCOM'].groupby(['month'])['offtakes actuals val'].sum()

month
2026-02-28    28.095907
2026-03-31    33.734272
2026-04-30    27.582862
2026-05-31    30.755225
2026-06-30    29.662163
2026-07-31    32.619023
2026-08-31    33.904037
2026-09-30     0.000000
Name: offtakes actuals val, dtype: float64

In [417]:
df_offtakes['offtakes_bias'] = df_offtakes['offtakes error']/df_offtakes['offtakes actuals val']
df_offtakes = df_offtakes.fillna(0)

df_offtakes['offtakes_bias'] = (
    df_offtakes['offtakes_bias']
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

bins = [-np.inf, -0.15, -0.10, -0.05, 0, 0.05, 0.10, 0.15, np.inf]
labels = [
    '< -15%',
    '-15% to -10%',
    '-10% to -5%',
    '-5% to 0%',
    '0% to 5%',
    '5% to 10%',
    '10% to 15%',
    '> 15%'
]

df_offtakes['offtakes_bias_bucket'] = pd.cut(
    df_offtakes['offtakes_bias'],
    bins=bins,
    labels=labels,
    right=False  
)

In [418]:
df_offtakes['forecast_granularity'] = 'Chain x PSKU'
df_offtakes['forecast_type'] = 'offtakes'

In [419]:
df_offtakes

,month,platform_name,parent_material_code,brand,portfolio,run_month,m month,pred_prophet,pred_rf,offtakes_forecasted_value,...,vol_in_rum,Index Rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,0.421023,...,0.0,138865.260689,30.318787,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,0.000000,...,0.0,168827.536176,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,0.187607,...,0.0,168827.536176,11.112333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,0.000000,...,0.0,739265.904412,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,0.113964,...,0.0,123636.889888,9.217630,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33145,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001768,...,0.0,12860.631072,1.375000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33146,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,0.000000,0.00000,0.001191,...,0.0,12860.631072,0.926333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33147,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.001632,...,0.0,366.484998,44.530000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33148,2026-09-30,zepto,811021,PABABY_GM,Skin Care,2026-08-31,M+1,0.000000,0.00000,0.002308,...,0.0,366.484998,62.988000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33149,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,0.000000,0.00000,0.009429,...,0.0,260000.000000,0.362667,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes

In [420]:
# df_offtakes.to_csv('acc_offtakes_till_may.csv')

In [421]:
# previous_data = pd.read_excel('/data/aman_singh/acuuracy_check/fva_and_stat_accuracy_till_june.xlsx', sheet_name = 'fva_depot_psku_final')
# previous_data

In [422]:
df_offtakes.rename(columns={'platform_name':'chain', 'parent_material_code':'psku'
                            ,'Index Rate':'index rate'}, inplace=True)
df_offtakes.drop(['vol_in_rum','pred_prophet', 'pred_rf','run_month'], axis=1, inplace=True)
df_offtakes

,month,chain,psku,brand,portfolio,m month,offtakes_forecasted_value,channel,index rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,M+1,0.421023,ECOM,138865.260689,30.318787,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,M+1,0.000000,ECOM,168827.536176,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,M+1,0.187607,ECOM,168827.536176,11.112333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,M+1,0.000000,ECOM,739265.904412,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,M+1,0.113964,ECOM,123636.889888,9.217630,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33145,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,M+1,0.001768,QCOM,12860.631072,1.375000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33146,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,M+1,0.001191,QCOM,12860.631072,0.926333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33147,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,M+1,0.001632,QCOM,366.484998,44.530000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33148,2026-09-30,zepto,811021,PABABY_GM,Skin Care,M+1,0.002308,QCOM,366.484998,62.988000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33149,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,M+1,0.009429,QCOM,260000.000000,0.362667,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes

In [423]:
df_offtakes[df_offtakes['channel']=='QCOM'].groupby(['month'])['offtakes_forecasted_value'].sum()

month
2026-02-28    31.431202
2026-03-31    34.907987
2026-04-30    31.529893
2026-05-31    34.345058
2026-06-30    32.736114
2026-07-31    34.340774
2026-08-31    33.039116
2026-09-30    34.859431
Name: offtakes_forecasted_value, dtype: float64

In [424]:
# x = pd.DataFrame(columns=previous_data.columns)
# df_offtakes = df_offtakes[df_offtakes['month'].isin(['2026-06-30','2026-07-31'])]
# offtakes_july = pd.concat([x, df_offtakes], ignore_index=True)
# offtakes_july

In [425]:
# offtakes_july.to_csv('offtakes_july.csv', index=False)

In [426]:
# final_df = pd.concat([df_stat_fva, df_offtakes], ignore_index=True)
# final_df

In [427]:
# final_df.columns

In [428]:
# final_df.to_csv('/data/aman_singh/acuuracy_check/fva_stat_offtake_accuracy.csv', index=False)

### Chain psku primary accuracy

In [429]:
qcom_df = pd.read_sql(
    """select * from TRN_MIL_DF_OFT2PRIM_CPSKU""",
    dev_conn
)
qcom_df.columns = qcom_df.columns.str.lower()
qcom_df['run_month'] = pd.to_datetime(qcom_df['run_month'])
qcom_df['month'] = pd.to_datetime(qcom_df['month'])

In [430]:
qcom_df#[qcom_df['Channel']=='Ecom']

,month,chain,psku,brand,portfolio,m month,run_month,calculated primary vol,channel
0,2025-12-31,Blinkit,718287,PCNO(R),CNO,M,2025-12-31,0.0000,Qcom
1,2025-12-31,Blinkit,718288,SAFF GOLD,Saffola Oils,M,2025-12-31,76.6195,Qcom
2,2025-12-31,Blinkit,718297,PCNO(R),CNO,M,2025-12-31,0.0000,Qcom
3,2025-12-31,Blinkit,718299,PCNO(R),CNO,M,2025-12-31,0.0000,Qcom
4,2025-12-31,Blinkit,718300,PCNO FLEX,CNO,M,2025-12-31,0.0000,Qcom
...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,Purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0000,Ecom
168467,2026-09-30,Purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0000,Ecom
168468,2026-09-30,Purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0000,Ecom
168469,2026-09-30,Purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,Ecom
168470,2026-09-30,Purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,Ecom

In [431]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

# realignment_df = realignment_df[
#     realignment_df['channel'].isin(['QCOM', 'QCOM B2C', 'ALL'])]


def realign_pskus(data, column, channel='QCOM'):
    realignment_data = realignment_df.copy()
    realignment_data = realignment_data[
        realignment_data['channel'].isin([channel, channel + ' B2C', 'ALL'])
    ]

    assert realignment_data['psku old'].dtype == 'int64'
    assert realignment_data['psku new'].dtype == 'int64'
    realignment_data = realignment_data[['psku old', 'psku new']].drop_duplicates()
    realignment_data = realignment_data.set_index('psku old').to_dict()['psku new']

    
    data[column] = data[column].astype(int)

    for old_psku, new_psku in realignment_data.items():
        data.loc[
            data[column] == old_psku, column
        ] = new_psku

    return data

In [432]:
chain_psku_primary_query = """
SELECT
    CASE
        WHEN MCM.chain = 'Kiranakart Technologies' THEN 'Zepto'
        WHEN MCM.chain = 'Grofers' THEN 'Blinkit'
        ELSE MCM.chain
    END AS chain,
    MM.parent_material_code,
    MM.material_group_code,
    LAST_DAY(MESR.month_date) AS month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Grofers', 'Zepto', 'Kiranakart Technologies', 'Swiggy', 'ZEPTO')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
JOIN
(
    SELECT DISTINCT
        customer_code,
        depot_code
    FROM
        mst_customer
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) CM on MESR.distributor_code = CM.customer_code
where month_date BETWEEN '2025-12-31' AND '2026-08-31' 
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""

depot_psku_primary_df = pd.read_sql(
    chain_psku_primary_query,
    prod_conn
)
depot_psku_primary_df.columns = depot_psku_primary_df.columns.str.lower()
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)
depot_psku_primary_df['month_date'] = pd.to_datetime(depot_psku_primary_df['month_date'])
depot_psku_primary_df = realign_pskus(depot_psku_primary_df.copy(), 'parent_material_code')
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['chain', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['parent_material_code'] != 715096]
depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if depot_psku_primary_df[col].min() < 0:
        print(col)

for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].clip(lower=0)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [433]:
depot_psku_primary_df[depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date'], keep=False)]

,chain,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
1422,Blinkit,732296,PABABY_ML,2025-12-31,0.000,0.000000,55.5023,0.000
1423,Blinkit,732296,PABABY_ML,2026-01-31,0.000,161.650358,116.1056,0.000
1424,Blinkit,732296,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,33.600
1425,Blinkit,732296,PABABY_SP,2026-01-31,0.000,0.000000,0.0000,0.000
1433,Blinkit,732297,PABABY_ML,2025-12-31,0.000,0.000000,100.1441,0.000
1434,Blinkit,732297,PABABY_ML,2026-01-31,0.000,397.753905,283.5170,0.000
1435,Blinkit,732297,PABABY_ML,2026-02-28,0.000,0.000000,0.0000,0.000
1436,Blinkit,732297,PABABY_ML,2026-06-30,9.840,0.000000,0.0000,9.840
1437,Blinkit,732297,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,137.760
1438,Blinkit,732297,PABABY_SP,2026-01-31,58.220,0.000000,0.0000,58.220
1439,Blinkit,732297,PABABY_SP,2026-02-28,39.360,230.724898,209.3269,39.360
1443,Blinkit,732297,PABABY_SP,2026-06-30,408.360,238.324204,211.8968,408.360
1950,Blinkit,811021,PABABY_GM,2026-04-30,52.128,0.000000,0.0000,52.128
1951,Blinkit,811021,PABABY_GM,2026-05-31,0.000,0.000000,0.0000,0.000
1952,Blinkit,811021,PABABY_GM,2026-07-31,69.504,0.000000,0.0000,69.504
1953,Blinkit,811021,PABABY_GM,2026-08-31,8.688,0.000000,0.0000,8.688
1954,Blinkit,811021,PADV_WIPS,2026-04-30,217.200,215.037675,247.6281,0.000
1955,Blinkit,811021,PADV_WIPS,2026-05-31,286.704,421.887556,357.7630,286.704
1957,Blinkit,811021,PADV_WIPS,2026-07-31,0.000,437.094196,544.3660,0.000
1958,Blinkit,811021,PADV_WIPS,2026-08-31,0.000,27.771786,0.0000,0.000
2442,Swiggy,718647,LIVON S-R,2025-12-31,0.000,0.000000,277.5746,50.400
2444,Swiggy,718647,LIVON S-R,2026-02-28,122.400,370.404138,296.9990,122.400
2446,Swiggy,718647,LIVON S-R,2026-04-30,0.000,195.462769,195.9974,0.000
2451,Swiggy,718647,LVNPST_ML,2025-12-31,0.000,0.000000,0.0000,0.000
2452,Swiggy,718647,LVNPST_ML,2026-02-28,0.000,0.000000,0.0000,0.000
2453,Swiggy,718647,LVNPST_ML,2026-04-30,0.000,0.000000,0.0000,0.000
3504,Swiggy,732296,PABABY_ML,2025-12-31,0.000,0.000000,119.1822,0.000
3505,Swiggy,732296,PABABY_ML,2026-01-31,0.000,141.449506,56.5511,0.000
3506,Swiggy,732296,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,283.200
3507,Swiggy,732296,PABABY_SP,2026-01-31,0.000,0.000000,0.0000,0.000
3515,Swiggy,732297,PABABY_ML,2025-12-31,0.000,0.000000,119.3315,0.000
3516,Swiggy,732297,PABABY_ML,2026-01-31,0.000,343.136823,382.8988,0.000
3517,Swiggy,732297,PABABY_ML,2026-04-30,0.000,0.000000,0.0000,0.000
3518,Swiggy,732297,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,216.480
3519,Swiggy,732297,PABABY_SP,2026-01-31,0.000,0.000000,0.0000,0.000
3522,Swiggy,732297,PABABY_SP,2026-04-30,24.600,0.000000,0.0000,24.600
4112,Swiggy,811021,PABABY_GM,2026-06-30,0.000,0.000000,0.0000,0.000
4113,Swiggy,811021,PABABY_GM,2026-07-31,0.000,0.000000,0.0000,0.000
4114,Swiggy,811021,PABABY_GM,2026-08-31,0.000,0.000000,0.0000,0.000
4117,Swiggy,811021,PADV_WIPS,2026-06-30,121.632,693.117338,528.6206,121.632
4118,Swiggy,811021,PADV_WIPS,2026-07-31,121.632,234.306716,0.0000,121.632
4119,Swiggy,811021,PADV_WIPS,2026-08-31,191.136,27.829992,0.0000,191.136
5549,Zepto,732296,PABABY_ML,2025-12-31,0.000,0.000000,159.8556,0.000
5550,Zepto,732296,PABABY_ML,2026-01-31,0.000,116.900138,247.3434,0.000
5551,Zepto,732296,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,374.400
5552,Zepto,732296,PABABY_SP,2026-01-31,144.000,0.000000,0.0000,144.000
5560,Zepto,732297,PABABY_ML,2025-12-31,0.000,0.000000,144.2246,9.840
5561,Zepto,732297,PABABY_ML,2026-01-31,0.000,289.099575,363.5744,0.000
5562,Zepto,732297,PABABY_SP,2025-12-31,0.000,0.000000,0.0000,142.680
5563,Zepto,732297,PABABY_SP,2026-01-31,418.200,0.000000,0.0000,418.200
6103,Zepto,811021,PABABY_GM,2026-04-30,60.816,0.000000,0.0000,60.816
6104,Zepto,811021,PABABY_GM,2026-05-31,8.688,0.000000,0.0000,8.688
6105,Zepto,811021,PABABY_GM,2026-08-31,0.000,0.000000,0.0000,0.000
6106,Zepto,811021,PADV_WIPS,2026-04-30,0.000,145.094015,277.0073,0.000
6107,Zepto,811021,PADV_WIPS,2026-05-31,139.008,271.728256,364.4387,139.008
6110,Zepto,811021,PADV_WIPS,2026-08-31,0.000,19.807788,0.0000,0.000

In [434]:
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['material_group_code']!='PABABY_SP']
depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()

13

In [435]:
depot_psku_primary_df[depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date'], keep=False)]

,chain,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
1950,Blinkit,811021,PABABY_GM,2026-04-30,52.128,0.000000,0.0000,52.128
1951,Blinkit,811021,PABABY_GM,2026-05-31,0.000,0.000000,0.0000,0.000
1952,Blinkit,811021,PABABY_GM,2026-07-31,69.504,0.000000,0.0000,69.504
1953,Blinkit,811021,PABABY_GM,2026-08-31,8.688,0.000000,0.0000,8.688
1954,Blinkit,811021,PADV_WIPS,2026-04-30,217.200,215.037675,247.6281,0.000
1955,Blinkit,811021,PADV_WIPS,2026-05-31,286.704,421.887556,357.7630,286.704
1957,Blinkit,811021,PADV_WIPS,2026-07-31,0.000,437.094196,544.3660,0.000
1958,Blinkit,811021,PADV_WIPS,2026-08-31,0.000,27.771786,0.0000,0.000
2442,Swiggy,718647,LIVON S-R,2025-12-31,0.000,0.000000,277.5746,50.400
2444,Swiggy,718647,LIVON S-R,2026-02-28,122.400,370.404138,296.9990,122.400
2446,Swiggy,718647,LIVON S-R,2026-04-30,0.000,195.462769,195.9974,0.000
2451,Swiggy,718647,LVNPST_ML,2025-12-31,0.000,0.000000,0.0000,0.000
2452,Swiggy,718647,LVNPST_ML,2026-02-28,0.000,0.000000,0.0000,0.000
2453,Swiggy,718647,LVNPST_ML,2026-04-30,0.000,0.000000,0.0000,0.000
4112,Swiggy,811021,PABABY_GM,2026-06-30,0.000,0.000000,0.0000,0.000
4113,Swiggy,811021,PABABY_GM,2026-07-31,0.000,0.000000,0.0000,0.000
4114,Swiggy,811021,PABABY_GM,2026-08-31,0.000,0.000000,0.0000,0.000
4117,Swiggy,811021,PADV_WIPS,2026-06-30,121.632,693.117338,528.6206,121.632
4118,Swiggy,811021,PADV_WIPS,2026-07-31,121.632,234.306716,0.0000,121.632
4119,Swiggy,811021,PADV_WIPS,2026-08-31,191.136,27.829992,0.0000,191.136
6103,Zepto,811021,PABABY_GM,2026-04-30,60.816,0.000000,0.0000,60.816
6104,Zepto,811021,PABABY_GM,2026-05-31,8.688,0.000000,0.0000,8.688
6105,Zepto,811021,PABABY_GM,2026-08-31,0.000,0.000000,0.0000,0.000
6106,Zepto,811021,PADV_WIPS,2026-04-30,0.000,145.094015,277.0073,0.000
6107,Zepto,811021,PADV_WIPS,2026-05-31,139.008,271.728256,364.4387,139.008
6110,Zepto,811021,PADV_WIPS,2026-08-31,0.000,19.807788,0.0000,0.000

In [436]:
depot_psku_primary_df = depot_psku_primary_df.groupby(['chain', 'parent_material_code', 'month_date'])[['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum',
       'sec_actuals_vol_rum']].sum().reset_index()

In [437]:
depot_psku_primary_df

,chain,parent_material_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,Blinkit,718287,2026-06-30,0.000,1.852098,0.2275,0.000
1,Blinkit,718287,2026-07-31,0.000,2.175176,0.0000,0.000
2,Blinkit,718287,2026-08-31,0.000,0.537315,0.0000,0.000
3,Blinkit,718288,2025-12-31,0.000,0.000000,76.6195,66.186
4,Blinkit,718288,2026-01-31,51.666,49.549496,52.9887,51.666
...,...,...,...,...,...,...,...
6069,Zepto,811287,2026-05-31,60.000,157.918621,122.3085,0.000
6070,Zepto,811287,2026-06-30,21.600,161.147344,179.2152,21.600
6071,Zepto,811287,2026-07-31,45.600,0.000000,0.0000,45.600
6072,Zepto,811287,2026-08-31,33.600,81.204936,83.3334,33.600
6073,Zepto,811564,2026-08-31,0.000,0.366679,0.4334,0.000

In [438]:
depot_psku_primary_df['channel'] = 'Qcom'
depot_psku_primary_df_qcom = depot_psku_primary_df.copy()

In [439]:
depot_psku_primary_query = """
SELECT
    CASE 
        WHEN MCM.chain = 'Big basket B2C' THEN 'Big Basket'
        WHEN MCM.chain = 'Flipkart-National' THEN 'Flipkart National'
        WHEN MCM.chain = 'Flipkart-Minutes' THEN 'Flipkart National'
        WHEN MCM.chain = 'Nykaa' THEN 'Nykaa'
        WHEN MCM.chain = 'Purplle' THEN 'Purplle'
        WHEN MCM.chain = 'Myntra' THEN 'Myntra'
        WHEN MCM.chain = 'MYNTRA' THEN 'Myntra'
        WHEN MCM.chain = 'Amazon B2C' THEN 'Amazon ARIPL'
        WHEN MCM.chain = 'ARIPL' THEN 'Amazon ARIPL'
        WHEN MCM.chain = 'RK WORLDINFOCOM' THEN 'Amazon RK'
        WHEN MCM.chain = 'RKWorld' THEN 'Amazon RK'
        WHEN MCM.chain = 'Flipkart-Grocery' THEN 'Flipkart Grocery'
        WHEN MCM.chain = 'FlipkartGrocery' THEN 'Flipkart Grocery'
        WHEN MCM.chain = 'Firstcry' THEN 'First Cry'
        WHEN MCM.chain = 'CITIMALL' THEN 'City Mall'
        ELSE MCM.chain
    END AS chain,
    MM.parent_material_code,
    MM.material_group_code,
    MESR.month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Flipkart-National', 'Flipkart-Grocery', 'Big basket B2C', 'RK WORLDINFOCOM', 'Amazon B2C', 
        'FATEHPURIA HYGIENE', 'Nykaa', 'Flipkart-Minutes', 'Purplle', 'Myntra', 'Dealshare', 'FlipkartGrocery', 'City Mall', '1MG', 
        'ARIPL', 'First Cry', 'Meesho', 'RKWorld', 'CITIMALL', 'Firstcry', 'EMAZING DEALS', 'MYNTRA')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
WHERE
    MESR.month_date between '2025-12-31' and '2026-08-31'
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""
depot_psku_primary_df = pd.read_sql(
    depot_psku_primary_query,
    prod_conn
)
depot_psku_primary_df.columns = depot_psku_primary_df.columns.str.lower()
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)
depot_psku_primary_df['month_date'] = pd.to_datetime(depot_psku_primary_df['month_date'])
depot_psku_primary_df = realign_pskus(depot_psku_primary_df.copy(), 'parent_material_code', channel='ECOM')
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['chain', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['parent_material_code'] != 715096]
depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if depot_psku_primary_df[col].min() < 0:
        print(col)

for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].clip(lower=0)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [440]:
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['material_group_code']!='PABABY_SP']
depot_psku_primary_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()

30

In [441]:
depot_psku_primary_df = depot_psku_primary_df.groupby(['chain', 'parent_material_code', 'month_date'])[['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum',
       'sec_actuals_vol_rum']].sum().reset_index()

In [442]:
depot_psku_primary_df['channel'] = 'Ecom'
depot_psku_primary_df_ecom = depot_psku_primary_df.copy()

In [443]:
depot_psku_primary_df = pd.concat([depot_psku_primary_df_qcom, depot_psku_primary_df_ecom], ignore_index=True)
depot_psku_primary_df

,chain,parent_material_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,channel
0,Blinkit,718287,2026-06-30,0.000,1.852098,0.2275,0.000,Qcom
1,Blinkit,718287,2026-07-31,0.000,2.175176,0.0000,0.000,Qcom
2,Blinkit,718287,2026-08-31,0.000,0.537315,0.0000,0.000,Qcom
3,Blinkit,718288,2025-12-31,0.000,0.000000,76.6195,66.186,Qcom
4,Blinkit,718288,2026-01-31,51.666,49.549496,52.9887,51.666,Qcom
...,...,...,...,...,...,...,...,...
97310,Purplle,809422,2026-06-30,0.000,0.000000,0.8518,0.000,Ecom
97311,Purplle,809423,2026-06-30,0.000,0.000000,0.7004,0.000,Ecom
97312,Purplle,811169,2026-07-31,0.000,0.000000,0.1667,0.000,Ecom
97313,Purplle,811416,2026-06-30,0.000,0.000000,0.4254,0.000,Ecom
97314,Purplle,811416,2026-07-31,0.000,0.000000,0.0671,0.000,Ecom

In [444]:
depot_psku_primary_df_ecom

,chain,parent_material_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,channel
0,1MG,724888,2026-05-31,0.0,0.0,10.6856,0.0,Ecom
1,1MG,735652,2026-07-31,0.0,0.0,12.8510,0.0,Ecom
2,1MG,736141,2026-05-31,0.0,0.0,0.6323,0.0,Ecom
3,1MG,807825,2026-05-31,0.0,0.0,0.0082,0.0,Ecom
4,1MG,808711,2026-07-31,0.0,0.0,0.7204,0.0,Ecom
...,...,...,...,...,...,...,...,...
91236,Purplle,809422,2026-06-30,0.0,0.0,0.8518,0.0,Ecom
91237,Purplle,809423,2026-06-30,0.0,0.0,0.7004,0.0,Ecom
91238,Purplle,811169,2026-07-31,0.0,0.0,0.1667,0.0,Ecom
91239,Purplle,811416,2026-06-30,0.0,0.0,0.4254,0.0,Ecom
91240,Purplle,811416,2026-07-31,0.0,0.0,0.0671,0.0,Ecom

In [445]:
actuals_df = depot_psku_primary_df.copy()

In [446]:
actuals_df.duplicated(subset=['channel','chain', 'parent_material_code','month_date']).sum()

0

In [447]:
actuals_df = actuals_df.groupby(['channel','chain', 'parent_material_code',
        'month_date'])[['pri_actuals_vol_rum',
       'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum().reset_index()
actuals_df

,channel,chain,parent_material_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,Ecom,1MG,724888,2026-05-31,0.0,0.000000,10.6856,0.0
1,Ecom,1MG,735652,2026-07-31,0.0,0.000000,12.8510,0.0
2,Ecom,1MG,736141,2026-05-31,0.0,0.000000,0.6323,0.0
3,Ecom,1MG,807825,2026-05-31,0.0,0.000000,0.0082,0.0
4,Ecom,1MG,808711,2026-07-31,0.0,0.000000,0.7204,0.0
...,...,...,...,...,...,...,...,...
97310,Qcom,Zepto,811287,2026-05-31,60.0,157.918621,122.3085,0.0
97311,Qcom,Zepto,811287,2026-06-30,21.6,161.147344,179.2152,21.6
97312,Qcom,Zepto,811287,2026-07-31,45.6,0.000000,0.0000,45.6
97313,Qcom,Zepto,811287,2026-08-31,33.6,81.204936,83.3334,33.6
97314,Qcom,Zepto,811564,2026-08-31,0.0,0.366679,0.4334,0.0

In [448]:
actuals_df.columns

Index(['channel', 'chain', 'parent_material_code', 'month_date',
       'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum',
       'sec_actuals_vol_rum'],
      dtype='object')

In [449]:
actuals_df = actuals_df.rename(columns={
    'parent_material_code': 'psku',
    'sec_apo_plan_vol_rum': 'Consensus Vol',
    'sec_actuals_vol_rum': 'Actuals Vol',
    'month_date': 'month'
})

In [450]:
actuals_df.head()

,channel,chain,psku,month,pri_actuals_vol_rum,pri_apo_plan_vol_rum,Consensus Vol,Actuals Vol
0,Ecom,1MG,724888,2026-05-31,0.0,0.0,10.6856,0.0
1,Ecom,1MG,735652,2026-07-31,0.0,0.0,12.8510,0.0
2,Ecom,1MG,736141,2026-05-31,0.0,0.0,0.6323,0.0
3,Ecom,1MG,807825,2026-05-31,0.0,0.0,0.0082,0.0
4,Ecom,1MG,808711,2026-07-31,0.0,0.0,0.7204,0.0

In [451]:
#qcom_df.rename(columns = {'Channel':'channel'}, inplace = True)

In [452]:
qcom_df['psku'] = qcom_df['psku'].astype(int)
actuals_df['psku'] = actuals_df['psku'].astype(int)

In [453]:
actuals_df['channel'] = actuals_df['channel'].str.upper()
qcom_df['channel'] = qcom_df['channel'].str.upper()
actuals_df['chain'] = actuals_df['chain'].str.lower()
qcom_df['chain'] = qcom_df['chain'].str.lower()

In [454]:
# qcom_df['channel'].unique()

In [455]:
# actuals_df = actuals_df[actuals_df['month_date'] == '2025-12-31']
# actuals_df

In [456]:
x = qcom_df.copy()

In [457]:
len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    actuals_df.drop([  'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum'], axis=1),
    on=['channel','chain', 'psku', 'month'],
    how='left'
)
assert len_before_merge == len(qcom_df)
del len_before_merge

In [458]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [459]:
len_before_merge = len(qcom_df)
qcom_df = qcom_df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'brand', 'qtr_ind_rate': 'Index Rate'}
    ),
    on=['brand'], 
    how='left'
)
assert len_before_merge == len(qcom_df)
del len_before_merge

In [460]:
qcom_df.isna().sum()

month                          0
chain                          0
psku                           0
brand                          0
portfolio                      0
m month                        0
run_month                      0
calculated primary vol         0
channel                        0
Consensus Vol             131293
Actuals Vol               131293
Index Rate                     0
dtype: int64

In [461]:
qcom_df['Consensus Vol'] = qcom_df['Consensus Vol'].fillna(0)
qcom_df['Actuals Vol'] = qcom_df['Actuals Vol'].fillna(0)

In [462]:
qcom_df['Consensus Vol'].max()

233641.5197

In [463]:
qcom_df.rename(columns={'calculated primary vol': 'Stat Vol'}, inplace=True)
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,Stat Vol,channel,Consensus Vol,Actuals Vol,Index Rate
0,2025-12-31,blinkit,718287,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05
1,2025-12-31,blinkit,718288,SAFF GOLD,Saffola Oils,M,2025-12-31,76.6195,QCOM,76.6195,66.186,1.388653e+05
2,2025-12-31,blinkit,718297,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05
3,2025-12-31,blinkit,718299,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05
4,2025-12-31,blinkit,718300,PCNO FLEX,CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,2.300000e+05
...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,3.790534e+03
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,3.664850e+02
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,2.892133e+06
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,1.286063e+04
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,1.286063e+04

In [464]:
qcom_df['Stat Val'] = qcom_df['Stat Vol'] * qcom_df['Index Rate'] / (10 ** 7)
qcom_df['Consensus Val'] = qcom_df['Consensus Vol'] * qcom_df['Index Rate'] / (10 ** 7)
qcom_df['Actuals Val'] = qcom_df['Actuals Vol'] * qcom_df['Index Rate'] / (10 ** 7)

In [465]:
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,Stat Vol,channel,Consensus Vol,Actuals Vol,Index Rate,Stat Val,Consensus Val,Actuals Val
0,2025-12-31,blinkit,718287,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05,0.000000,0.000000,0.000000
1,2025-12-31,blinkit,718288,SAFF GOLD,Saffola Oils,M,2025-12-31,76.6195,QCOM,76.6195,66.186,1.388653e+05,1.063979,1.063979,0.919094
2,2025-12-31,blinkit,718297,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05,0.000000,0.000000,0.000000
3,2025-12-31,blinkit,718299,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,3.492740e+05,0.000000,0.000000,0.000000
4,2025-12-31,blinkit,718300,PCNO FLEX,CNO,M,2025-12-31,0.0000,QCOM,0.0000,0.000,2.300000e+05,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,3.790534e+03,0.000000,0.000000,0.000000
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,3.664850e+02,0.000000,0.000000,0.000000
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,2.892133e+06,0.000000,0.000000,0.000000
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,1.286063e+04,0.000000,0.000000,0.000000
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,0.000,1.286063e+04,0.000000,0.000000,0.000000

In [466]:
qcom_df[(qcom_df['month'] == '2026-07-31') & (qcom_df['channel']=='ECOM') & (qcom_df['run_month']=='2026-06-30')]['Actuals Val'].sum()

40.53921001380108

In [467]:
qcom_df['Stat Error'] = qcom_df['Stat Val'] - qcom_df['Actuals Val']
qcom_df['Consensus Error'] = qcom_df['Consensus Val'] - qcom_df['Actuals Val']

qcom_df['Stat Abs Error'] = np.abs(qcom_df['Stat Error'])
qcom_df['Consensus Abs Error'] = np.abs(qcom_df['Consensus Error'])

In [468]:
qcom_df['stat_bias'] = qcom_df['Stat Error']/qcom_df['Actuals Val']
qcom_df = qcom_df.fillna(0)

import numpy as np
import pandas as pd

qcom_df['stat_bias'] = (
    qcom_df['stat_bias']
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

bins = [-np.inf, -0.15, -0.10, -0.05, 0, 0.05, 0.10, 0.15, np.inf]
labels = [
    '< -15%',
    '-15% to -10%',
    '-10% to -5%',
    '-5% to 0%',
    '0% to 5%',
    '5% to 10%',
    '10% to 15%',
    '> 15%'
]

qcom_df['stat_bias_bucket'] = pd.cut(
    qcom_df['stat_bias'],
    bins=bins,
    labels=labels,
    right=False  
)

In [469]:
# delivery_df = pd.read_csv('/data/aman_singh/acuuracy_check/Export View of Month Vol & APO.csv')

# delivery_df['Channel'] = delivery_df['Channel'].replace({
#     'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
# delivery_df
# delivery_df['delivery_vol'] = delivery_df['01-12-2025 Del Vol'].map(lambda x:0 if x.strip() == '-' else float(x.strip().replace(',','')))
# delivery_df = delivery_df[delivery_df['Channel'] == 'QCOM']
# delivery_df = delivery_df.groupby(['Depot','PSKU'])['delivery_vol'].sum().reset_index(
# )#.rename(columns = {'01-12-2025 Del Vol':'delivery_vol'})

# len_before_merge = len(qcom_df)
# qcom_df = qcom_df.merge(
#     delivery_df,
#     on=['Depot', 'PSKU'],
#     how='left'
# )
# assert len_before_merge == len(qcom_df)
# del len_before_merge

# qcom_df['Delivery Val'] = qcom_df['delivery_vol'] * qcom_df['Index Rate'] / (10 ** 7)

# qcom_df['Dp Error'] = qcom_df['Delivery Val'] - qcom_df['Actuals Val']

# qcom_df['Dp Abs Error'] = np.abs(qcom_df['Dp Error'])

In [470]:
qcom_df.columns = qcom_df.columns.str.lower()
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,index rate,stat val,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket
0,2025-12-31,blinkit,718287,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,3.492740e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
1,2025-12-31,blinkit,718288,SAFF GOLD,Saffola Oils,M,2025-12-31,76.6195,QCOM,76.6195,...,1.388653e+05,1.063979,1.063979,0.919094,0.144885,0.144885,0.144885,0.144885,0.157639,> 15%
2,2025-12-31,blinkit,718297,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,3.492740e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
3,2025-12-31,blinkit,718299,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,3.492740e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
4,2025-12-31,blinkit,718300,PCNO FLEX,CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,2.300000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,...,3.790534e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,...,3.664850e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0000,ECOM,0.0000,...,2.892133e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,...,1.286063e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,...,1.286063e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%

In [471]:
# df = pd.read_excel("/data/aman_singh/acuuracy_check/acc_framework_feb.xlsx")
# df.columns = df.columns.str.lower()
# df = df[df['forecast_granularity']!='Depot x PSKU']

In [472]:
# df.columns = df.columns.str.lower()

In [473]:
qcom_df.columns

Index(['month', 'chain', 'psku', 'brand', 'portfolio', 'm month', 'run_month',
       'stat vol', 'channel', 'consensus vol', 'actuals vol', 'index rate',
       'stat val', 'consensus val', 'actuals val', 'stat error',
       'consensus error', 'stat abs error', 'consensus abs error', 'stat_bias',
       'stat_bias_bucket'],
      dtype='object')

In [474]:

qcom_df['forecast_granularity'] = 'Chain x PSKU'
qcom_df['forecast_type'] = 'offtakes_to_primary'
#qcom_df['channel'] = 'QCOM'
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
0,2025-12-31,blinkit,718287,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1,2025-12-31,blinkit,718288,SAFF GOLD,Saffola Oils,M,2025-12-31,76.6195,QCOM,76.6195,...,1.063979,0.919094,0.144885,0.144885,0.144885,0.144885,0.157639,> 15%,Chain x PSKU,offtakes_to_primary
2,2025-12-31,blinkit,718297,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
3,2025-12-31,blinkit,718299,PCNO(R),CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
4,2025-12-31,blinkit,718300,PCNO FLEX,CNO,M,2025-12-31,0.0000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.0000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.0000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.0000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary

In [475]:
qcom_df = qcom_df[qcom_df['m month'] == 'M+1']

In [476]:
final_df[(final_df['month'] == '2026-08-31') & (final_df['channel'] == 'QCOM')]['actuals val'].sum()

33.89707449852139

In [477]:
final_df[(final_df['month'] == '2026-08-31')].groupby(['channel'])[['stat val', 'actuals val']].sum()

           stat val  actuals val
channel
B2B       12.932320    14.029632
ECOM      51.536347    66.819983
GT       419.780742   406.864544
MT       129.201438   111.415783
QCOM      32.715725    33.897074

In [478]:
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
1571,2026-01-31,blinkit,718287,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1572,2026-01-31,blinkit,718288,SAFF GOLD,Saffola Oils,M+1,2025-12-31,52.041436,QCOM,52.9887,...,0.735829,0.717461,0.005213,0.018368,0.005213,0.018368,0.007267,0% to 5%,Chain x PSKU,offtakes_to_primary
1573,2026-01-31,blinkit,718297,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1574,2026-01-31,blinkit,718299,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1575,2026-01-31,blinkit,718300,PCNO FLEX,CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary

In [479]:
qcom_df[(qcom_df['month'] == '2026-08-31')].groupby(['channel'])[['stat val', 'actuals val']].sum()

          stat val  actuals val
channel
ECOM     52.578989    65.998658
QCOM     32.715725    33.917431

In [480]:
df_offtakes

,month,chain,psku,brand,portfolio,m month,offtakes_forecasted_value,channel,index rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,M+1,0.421023,ECOM,138865.260689,30.318787,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,M+1,0.000000,ECOM,168827.536176,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,M+1,0.187607,ECOM,168827.536176,11.112333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,M+1,0.000000,ECOM,739265.904412,0.000000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,M+1,0.113964,ECOM,123636.889888,9.217630,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33145,2026-09-30,zepto,810971,PA_ESS_HO,Hair Oils,M+1,0.001768,QCOM,12860.631072,1.375000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33146,2026-09-30,zepto,811005,PA_ESS_HO,Hair Oils,M+1,0.001191,QCOM,12860.631072,0.926333,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33147,2026-09-30,zepto,811019,PADV_WIPS,Skin Care,M+1,0.001632,QCOM,366.484998,44.530000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33148,2026-09-30,zepto,811021,PABABY_GM,Skin Care,M+1,0.002308,QCOM,366.484998,62.988000,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes
33149,2026-09-30,zepto,811181,SAF_CDPRS,Saffola Oils,M+1,0.009429,QCOM,260000.000000,0.362667,0.0,0.0,0.0,0.0,0% to 5%,Chain x PSKU,offtakes

In [481]:
df_offtakes['month'].unique()

<DatetimeArray>
['2026-05-31 00:00:00', '2026-06-30 00:00:00', '2026-07-31 00:00:00',
 '2026-02-28 00:00:00', '2026-03-31 00:00:00', '2026-04-30 00:00:00',
 '2026-08-31 00:00:00', '2026-09-30 00:00:00']
Length: 8, dtype: datetime64[ns]

In [482]:
df_offtakes[(df_offtakes['month'] == '2026-08-31')].groupby(['channel'])[['offtakes_forecasted_value', 'offtakes actuals val']].sum()

         offtakes_forecasted_value  offtakes actuals val
channel
ECOM                     41.654975             41.307694
QCOM                     33.039116             33.904037

In [483]:
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
1571,2026-01-31,blinkit,718287,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1572,2026-01-31,blinkit,718288,SAFF GOLD,Saffola Oils,M+1,2025-12-31,52.041436,QCOM,52.9887,...,0.735829,0.717461,0.005213,0.018368,0.005213,0.018368,0.007267,0% to 5%,Chain x PSKU,offtakes_to_primary
1573,2026-01-31,blinkit,718297,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1574,2026-01-31,blinkit,718299,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1575,2026-01-31,blinkit,718300,PCNO FLEX,CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary

In [484]:
all_df = pd.concat([final_df,df_offtakes,qcom_df])

In [485]:
print(final_df.shape)
print(df_offtakes.shape)
print(qcom_df.shape)

(375431, 32)
(33150, 17)
(56283, 23)

In [486]:
all_df.shape

(464864, 40)

In [487]:
qcom_df

,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,consensus vol,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
1571,2026-01-31,blinkit,718287,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1572,2026-01-31,blinkit,718288,SAFF GOLD,Saffola Oils,M+1,2025-12-31,52.041436,QCOM,52.9887,...,0.735829,0.717461,0.005213,0.018368,0.005213,0.018368,0.007267,0% to 5%,Chain x PSKU,offtakes_to_primary
1573,2026-01-31,blinkit,718297,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1574,2026-01-31,blinkit,718299,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1575,2026-01-31,blinkit,718300,PCNO FLEX,CNO,M+1,2025-12-31,0.000000,QCOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168466,2026-09-30,purplle,807725,BIO OILS,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168467,2026-09-30,purplle,809042,PABABY_GM,SKIN CARE,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168468,2026-09-30,purplle,809250,LVNPST_ML,PREM. HAIR NOUR.,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168469,2026-09-30,purplle,810673,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
168470,2026-09-30,purplle,810674,PA_ESS_HO,HAIR OILS,M+1,2026-08-31,0.000000,ECOM,0.0000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary

In [489]:
all_df[(all_df['month'] == '2026-08-31') ].to_excel('acc_framework_aug.xlsx')

### The end

In [109]:
qcom_df.to_csv('/data/aman_singh/acuuracy_check/chain_psku_primary_accuracy_till_may.csv')

In [1]:
import pandas as pd
df = pd.read_excel('/data/aman_singh/acuuracy_check/acc_framework_may_final.xlsx', sheet_name = 'Sheet1')
df

,Unnamed: 0,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month,depot,...,stat error,consensus error,stat abs error,consensus abs error,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,stat_bias,stat_bias_bucket
0,129118,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30,M+1,2026-05-31,D673,...,0.022506,0.041685,0.022506,0.041685,0.0,0.0,0.0,0.0,0.201333,> 15%
1,129119,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30,M+1,2026-05-31,D673,...,-0.004181,-0.002461,0.004181,0.002461,0.0,0.0,0.0,0.0,-0.132249,-15% to -10%
2,129120,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30,M+1,2026-05-31,D674,...,0.003741,-0.002501,0.003741,0.002501,0.0,0.0,0.0,0.0,0.334012,> 15%
3,129121,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30,M+1,2026-05-31,D674,...,-0.020124,0.019797,0.020124,0.019797,0.0,0.0,0.0,0.0,-0.223653,< -15%
4,129122,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30,M+1,2026-05-31,D676,...,0.074692,0.070734,0.074692,0.070734,0.0,0.0,0.0,0.0,0.218949,> 15%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38287,451102,Depot x PSKU,offtakes_to_primary,ECOM,Male Grooming,SW_SGPRF,2026-04-30,M+1,2026-05-31,D677,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%
38288,451103,Depot x PSKU,offtakes_to_primary,ECOM,Saffola Oils,SAF_CDPRS,2026-04-30,M+1,2026-05-31,D677,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%
38289,451104,Depot x PSKU,offtakes_to_primary,ECOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,D677,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%
38290,451105,Depot x PSKU,offtakes_to_primary,ECOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,D677,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%
38291,451106,Depot x PSKU,offtakes_to_primary,ECOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,D677,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%

In [2]:
qcom_df = pd.read_csv('/data/aman_singh/acuuracy_check/chain_psku_primary_accuracy_till_may.csv')
qcom_df

,Unnamed: 0,month,chain,psku,brand,portfolio,m month,run_month,stat vol,channel,...,consensus val,actuals val,stat error,consensus error,stat abs error,consensus abs error,stat_bias,stat_bias_bucket,forecast_granularity,forecast_type
0,1571,2026-01-31,blinkit,718287,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
1,1572,2026-01-31,blinkit,718288,SAFF GOLD,Saffola Oils,M+1,2025-12-31,52.041436,QCOM,...,0.735829,0.717461,0.005213,0.018368,0.005213,0.018368,0.007267,0% to 5%,Chain x PSKU,offtakes_to_primary
2,1573,2026-01-31,blinkit,718297,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
3,1574,2026-01-31,blinkit,718299,PCNO(R),CNO,M+1,2025-12-31,0.000000,QCOM,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
4,1575,2026-01-31,blinkit,718300,PCNO FLEX,CNO,M+1,2025-12-31,0.000000,QCOM,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24588,86523,2026-05-31,zepto,810971,PA_ESS_HO,Hair Oils,M+1,2026-04-30,0.180968,QCOM,...,0.000102,0.011112,-0.010879,-0.011010,0.010879,0.011010,-0.979055,< -15%,Chain x PSKU,offtakes_to_primary
24589,86524,2026-05-31,zepto,811005,PA_ESS_HO,Hair Oils,M+1,2026-04-30,0.154828,QCOM,...,0.007044,0.003889,-0.003690,0.003155,0.003690,0.003155,-0.948800,< -15%,Chain x PSKU,offtakes_to_primary
24590,86525,2026-05-31,zepto,811169,SW_SGPRF,Male Grooming,M+1,2026-04-30,0.000000,QCOM,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
24591,86526,2026-05-31,zepto,811181,SAF_CDPRS,Saffola Oils,M+1,2026-04-30,0.043734,QCOM,...,0.046896,0.000000,0.001137,0.046896,0.001137,0.046896,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary
24592,86527,2026-05-31,zepto,811267,PA_ESS_HO,Hair Oils,M+1,2026-04-30,0.000000,QCOM,...,0.001049,0.000000,0.000000,0.001049,0.000000,0.001049,0.000000,0% to 5%,Chain x PSKU,offtakes_to_primary

In [15]:
offtakes_df = pd.read_csv('/data/aman_singh/acuuracy_check/acc_offtakes_till_may.csv')
offtakes_df

,Unnamed: 0,month,platform_name,parent_material_code,brand,portfolio,run_month,m month,pred_prophet,pred_rf,...,vol_in_rum,Index Rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,2026-04-30,M+1,29.403313,27.76920,...,30.2040,138865.260689,30.318787,0.419429,-0.001594,0.001594,-0.003800,-5% to 0%,Chain x PSKU,offtakes
1,1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,2026-04-30,M+1,0.000000,0.00000,...,0.0000,168827.536176,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
2,2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,2026-04-30,M+1,7.271279,16.05050,...,12.1500,168827.536176,11.112333,0.205125,0.017519,0.017519,0.085405,5% to 10%,Chain x PSKU,offtakes
3,3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,2026-04-30,M+1,0.000000,0.00000,...,0.0000,739265.904412,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
4,4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,2026-04-30,M+1,3.942144,6.99084,...,9.6561,123636.889888,9.217630,0.119385,0.005421,0.005421,0.045409,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16426,16426,2026-04-30,nykaa,810605,KAYA_ML,Skin Care,2026-03-31,M+1,0.000000,0.00000,...,0.0000,1226.374229,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16427,16427,2026-04-30,nykaa,810673,PA_ESS_HO,Hair Oils,2026-03-31,M+1,0.000000,0.00000,...,1.7640,12860.631072,1.844295,0.002269,-0.000103,0.000103,-0.045519,-5% to 0%,Chain x PSKU,offtakes
16428,16428,2026-04-30,nykaa,810674,PA_ESS_HO,Hair Oils,2026-03-31,M+1,0.000000,0.00000,...,0.5880,12860.631072,0.407243,0.000756,0.000232,0.000232,0.307410,> 15%,Chain x PSKU,offtakes
16429,16429,2026-04-30,nykaa,810738,PABABY_GM,Skin Care,2026-03-31,M+1,0.000000,0.00000,...,0.0000,366.484998,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16430,16430,2026-04-30,nykaa,810805,PABABY_GM,Skin Care,2026-03-31,M+1,0.000000,0.00000,...,26.0640,366.484998,14.705199,0.000955,0.000416,0.000416,0.435804,> 15%,Chain x PSKU,offtakes

In [16]:
offtakes_df.rename(columns={'platform_name':'chain', 'parent_material_code':'psku'
                            ,'Index Rate':'index rate'}, inplace=True)
offtakes_df.drop(['vol_in_rum','run_month'], axis=1, inplace=True)
offtakes_df

,Unnamed: 0,month,chain,psku,brand,portfolio,m month,pred_prophet,pred_rf,offtakes_forecasted_value,channel,index rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,M+1,29.403313,27.76920,0.421023,ECOM,138865.260689,30.318787,0.419429,-0.001594,0.001594,-0.003800,-5% to 0%,Chain x PSKU,offtakes
1,1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,M+1,0.000000,0.00000,0.000000,ECOM,168827.536176,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
2,2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,M+1,7.271279,16.05050,0.187607,ECOM,168827.536176,11.112333,0.205125,0.017519,0.017519,0.085405,5% to 10%,Chain x PSKU,offtakes
3,3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,M+1,0.000000,0.00000,0.000000,ECOM,739265.904412,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
4,4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,M+1,3.942144,6.99084,0.113964,ECOM,123636.889888,9.217630,0.119385,0.005421,0.005421,0.045409,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16426,16426,2026-04-30,nykaa,810605,KAYA_ML,Skin Care,M+1,0.000000,0.00000,0.000000,ECOM,1226.374229,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16427,16427,2026-04-30,nykaa,810673,PA_ESS_HO,Hair Oils,M+1,0.000000,0.00000,0.002372,ECOM,12860.631072,1.844295,0.002269,-0.000103,0.000103,-0.045519,-5% to 0%,Chain x PSKU,offtakes
16428,16428,2026-04-30,nykaa,810674,PA_ESS_HO,Hair Oils,M+1,0.000000,0.00000,0.000524,ECOM,12860.631072,0.407243,0.000756,0.000232,0.000232,0.307410,> 15%,Chain x PSKU,offtakes
16429,16429,2026-04-30,nykaa,810738,PABABY_GM,Skin Care,M+1,0.000000,0.00000,0.000000,ECOM,366.484998,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16430,16430,2026-04-30,nykaa,810805,PABABY_GM,Skin Care,M+1,0.000000,0.00000,0.000539,ECOM,366.484998,14.705199,0.000955,0.000416,0.000416,0.435804,> 15%,Chain x PSKU,offtakes

In [20]:
offtakes_df['month'].unique()
offtakes_df = offtakes_df[offtakes_df['month'].isin(['2026-04-30', '2026-05-31'])]

In [21]:
final_df = pd.concat([df,qcom_df])
final_df

,Unnamed: 0,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month,depot,...,consensus error,stat abs error,consensus abs error,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,stat_bias,stat_bias_bucket,chain
0,129118,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30 00:00:00,M+1,2026-05-31 00:00:00,D673,...,0.041685,0.022506,0.041685,0.0,0.0,0.0,0.0,0.201333,> 15%,NaN
1,129119,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30 00:00:00,M+1,2026-05-31 00:00:00,D673,...,-0.002461,0.004181,0.002461,0.0,0.0,0.0,0.0,-0.132249,-15% to -10%,NaN
2,129120,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30 00:00:00,M+1,2026-05-31 00:00:00,D674,...,-0.002501,0.003741,0.002501,0.0,0.0,0.0,0.0,0.334012,> 15%,NaN
3,129121,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30 00:00:00,M+1,2026-05-31 00:00:00,D674,...,0.019797,0.020124,0.019797,0.0,0.0,0.0,0.0,-0.223653,< -15%,NaN
4,129122,Depot x PSKU,secondary,GT,CNO,KERALA,2026-04-30 00:00:00,M+1,2026-05-31 00:00:00,D676,...,0.070734,0.074692,0.070734,0.0,0.0,0.0,0.0,0.218949,> 15%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24588,86523,Chain x PSKU,offtakes_to_primary,QCOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,NaN,...,-0.011010,0.010879,0.011010,NaN,NaN,NaN,NaN,-0.979055,< -15%,zepto
24589,86524,Chain x PSKU,offtakes_to_primary,QCOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,NaN,...,0.003155,0.003690,0.003155,NaN,NaN,NaN,NaN,-0.948800,< -15%,zepto
24590,86525,Chain x PSKU,offtakes_to_primary,QCOM,Male Grooming,SW_SGPRF,2026-04-30,M+1,2026-05-31,NaN,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto
24591,86526,Chain x PSKU,offtakes_to_primary,QCOM,Saffola Oils,SAF_CDPRS,2026-04-30,M+1,2026-05-31,NaN,...,0.046896,0.001137,0.046896,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto
24592,86527,Chain x PSKU,offtakes_to_primary,QCOM,Hair Oils,PA_ESS_HO,2026-04-30,M+1,2026-05-31,NaN,...,0.001049,0.000000,0.001049,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto

In [11]:
x = final_df.copy()

In [22]:
offtakes_df

,Unnamed: 0,month,chain,psku,brand,portfolio,m month,pred_prophet,pred_rf,offtakes_forecasted_value,channel,index rate,offtakes_forecasted_vol,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,forecast_granularity,forecast_type
0,0,2026-05-31,amazon aripl,718288,SAFF GOLD,Saffola Oils,M+1,29.403313,27.76920,0.421023,ECOM,138865.260689,30.318787,0.419429,-0.001594,0.001594,-0.003800,-5% to 0%,Chain x PSKU,offtakes
1,1,2026-05-31,amazon aripl,718321,SAFF KO,Saffola Oils,M+1,0.000000,0.00000,0.000000,ECOM,168827.536176,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
2,2,2026-05-31,amazon aripl,718322,SAFF KO,Saffola Oils,M+1,7.271279,16.05050,0.187607,ECOM,168827.536176,11.112333,0.205125,0.017519,0.017519,0.085405,5% to 10%,Chain x PSKU,offtakes
3,3,2026-05-31,amazon aripl,718323,SF_IMV_MK,Foods,M+1,0.000000,0.00000,0.000000,ECOM,739265.904412,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
4,4,2026-05-31,amazon aripl,718328,SAFF KOCO,Saffola Oils,M+1,3.942144,6.99084,0.113964,ECOM,123636.889888,9.217630,0.119385,0.005421,0.005421,0.045409,0% to 5%,Chain x PSKU,offtakes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16426,16426,2026-04-30,nykaa,810605,KAYA_ML,Skin Care,M+1,0.000000,0.00000,0.000000,ECOM,1226.374229,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16427,16427,2026-04-30,nykaa,810673,PA_ESS_HO,Hair Oils,M+1,0.000000,0.00000,0.002372,ECOM,12860.631072,1.844295,0.002269,-0.000103,0.000103,-0.045519,-5% to 0%,Chain x PSKU,offtakes
16428,16428,2026-04-30,nykaa,810674,PA_ESS_HO,Hair Oils,M+1,0.000000,0.00000,0.000524,ECOM,12860.631072,0.407243,0.000756,0.000232,0.000232,0.307410,> 15%,Chain x PSKU,offtakes
16429,16429,2026-04-30,nykaa,810738,PABABY_GM,Skin Care,M+1,0.000000,0.00000,0.000000,ECOM,366.484998,0.000000,0.000000,0.000000,0.000000,0.000000,0% to 5%,Chain x PSKU,offtakes
16430,16430,2026-04-30,nykaa,810805,PABABY_GM,Skin Care,M+1,0.000000,0.00000,0.000539,ECOM,366.484998,14.705199,0.000955,0.000416,0.000416,0.435804,> 15%,Chain x PSKU,offtakes

In [25]:
# final_df = pd.concat([final_df,offtakes_df])
#final_df
final_df.to_csv('acc_till_may.csv')

In [24]:
final_df.isnull().sum()

Unnamed: 0                         0
forecast_granularity               0
forecast_type                      0
channel                            0
portfolio                          0
brand                              0
run_month                       8129
m month                            0
month                              0
depot                          32722
psku                               0
stat vol                        8129
prophet vol                    61110
rf_vol                         61110
prophet heuristic vol          61110
rf heuristic vol               61110
consensus vol                   8129
actuals vol                     8129
key                            61110
index rate                         0
stat val                        8129
consensus val                   8129
actuals val                     8129
stat error                      8129
consensus error                 8129
stat abs error                  8129
consensus abs error             8129
prophet vol_value              61110
rf_vol_value                   61110
prophet heuristic vol_value    61110
rf heuristic vol_value         61110
stat_bias                       8129
stat_bias_bucket                8129
chain                          38292
pred_prophet                   62885
pred_rf                        62885
offtakes_forecasted_value      62885
offtakes_forecasted_vol        62885
offtakes actuals val           62885
offtakes error                 62885
offtakes abs error             62885
offtakes_bias                  62885
offtakes_bias_bucket           62885
dtype: int64

In [7]:
import pickle
with open('/data/aman_singh/acuuracy_check/prophet_models (2).pkl', 'rb') as f:
    model = pickle.load(f)

In [6]:
model['ORS_D535_731588']

{'changepoint_prior_scale': 0.01,
 'changepoint_range': 0.8,
 'seasonality_prior_scale': 2.0,
 'n_changepoints': 4,
 'yearly_seasonality': 5}

In [8]:
model['ORS_D535_731588']

{'changepoint_prior_scale': 0.01,
 'changepoint_range': 0.8,
 'seasonality_prior_scale': 0.1,
 'n_changepoints': 4,
 'yearly_seasonality': 4}

In [2]:
print(model.growth)

AttributeError: 'dict' object has no attribute 'growth'