In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
import pickle

import numpy as np
import pandas as pd

from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from pandas.tseries.offsets import MonthEnd, MonthBegin
from maricovault.MaricoDB import MaricoSnowflake

from joblib import Parallel, delayed

In [2]:
def get_dbconnection(db_name): 

    KEY_VAULT_NAME = "prod-pwd"
    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection

In [3]:
dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

### Helper Functions

In [4]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

def demand_driver_realign_pskus(data, channel):
    """
    Realign the old pskus to new pskus and return updated data.

    Args:
        data: pandas dataframe
        - master dataframe having all the pskus
    
    Return:
        data: pandas dataframe
        - dataframe 
    """
    realignment_data = realignment_df.copy()
    realignment_data.columns = realignment_data.columns.str.lower()
    realignment_data = realignment_data[
        (realignment_data["channel"] == channel)
        | (realignment_data["channel"] == channel + " B2C")
        | (realignment_data["channel"] == "ALL")
    ]

    data["parent_material_code"] = data["parent_material_code"].astype(int)

    for grp, grp_data in realignment_data.groupby(by=["psku old", "asm"]):
        old_psku, old_asm = grp
        new_psku = grp_data["psku new"].values[0]
        if old_asm != "ALL":
            condition = (data["parent_material_code"] == old_psku) & (
                data["asm_area_code"] == old_asm
            )
        else:
            condition = data["parent_material_code"] == old_psku

        data.loc[condition, "parent_material_code"] = new_psku

    return data

In [24]:
df = pd.read_excel('/data/aman_singh/acuuracy_check/acc_framework_aug.xlsx')
df

,Unnamed: 0,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month,depot,...,offtakes actuals val,offtakes error,offtakes abs error,offtakes_bias,offtakes_bias_bucket,month_date,platform_name,parent_material_code,brand_code,vol_in_rum
0,40,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44552,32284,Chain x PSKU,offtakes,QCOM,Hair Oils,PA_ESS_HO,NaT,M+1,2026-08-31,NaN,...,0.003318,0.002083,0.002083,0.627907,> 15%,NaN,NaN,NaN,NaN,NaN
44553,32285,Chain x PSKU,offtakes,QCOM,Hair Oils,PA_ESS_HO,NaT,M+1,2026-08-31,NaN,...,0.000684,-0.000378,0.000378,-0.552632,< -15%,NaN,NaN,NaN,NaN,NaN
44554,32286,Chain x PSKU,offtakes,QCOM,Skin Care,PADV_WIPS,NaT,M+1,2026-08-31,NaN,...,0.002689,0.002669,0.002669,0.992537,> 15%,NaN,NaN,NaN,NaN,NaN
44555,32287,Chain x PSKU,offtakes,QCOM,Skin Care,PABABY_GM,NaT,M+1,2026-08-31,NaN,...,0.000982,-0.002565,0.002565,-2.612613,< -15%,NaN,NaN,NaN,NaN,NaN
44556,32288,Chain x PSKU,offtakes,QCOM,Saffola Oils,SAF_CDPRS,NaT,M+1,2026-08-31,NaN,...,0.019396,0.013572,0.013572,0.699732,> 15%,NaN,NaN,NaN,NaN,NaN

In [26]:
df.drop(columns = ['month_date'],inplace = True)

In [27]:
df.columns

Index(['Unnamed: 0', 'forecast_granularity', 'forecast_type', 'channel',
       'portfolio', 'brand', 'run_month', 'm month', 'month', 'depot', 'psku',
       'stat vol', 'prophet vol', 'rf_vol', 'prophet heuristic vol',
       'rf heuristic vol', 'consensus vol', 'actuals vol', 'key', 'index rate',
       'stat val', 'consensus val', 'actuals val', 'stat error',
       'consensus error', 'stat abs error', 'consensus abs error',
       'prophet vol_value', 'rf_vol_value', 'prophet heuristic vol_value',
       'rf heuristic vol_value', 'stat_bias', 'stat_bias_bucket', 'chain',
       'offtakes_forecasted_value', 'offtakes_forecasted_vol',
       'offtakes actuals val', 'offtakes error', 'offtakes abs error',
       'offtakes_bias', 'offtakes_bias_bucket', 'platform_name',
       'parent_material_code', 'brand_code', 'vol_in_rum'],
      dtype='object')

In [28]:
df.rename(columns = {'month':'month_date'}, inplace = True)
df.drop(columns = [ 'index rate'], inplace = True)

In [29]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

len_before_merge = len(df)
df = df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'brand', 'qtr_ind_rate': 'index rate'}
    ),
    on=['brand'], 
    how='left'
)
assert len_before_merge == len(df)
del len_before_merge

In [30]:
df['channel'] = df['channel'].str.upper()

In [31]:
df.columns

Index(['Unnamed: 0', 'forecast_granularity', 'forecast_type', 'channel',
       'portfolio', 'brand', 'run_month', 'm month', 'month_date', 'depot',
       'psku', 'stat vol', 'prophet vol', 'rf_vol', 'prophet heuristic vol',
       'rf heuristic vol', 'consensus vol', 'actuals vol', 'key', 'stat val',
       'consensus val', 'actuals val', 'stat error', 'consensus error',
       'stat abs error', 'consensus abs error', 'prophet vol_value',
       'rf_vol_value', 'prophet heuristic vol_value', 'rf heuristic vol_value',
       'stat_bias', 'stat_bias_bucket', 'chain', 'offtakes_forecasted_value',
       'offtakes_forecasted_vol', 'offtakes actuals val', 'offtakes error',
       'offtakes abs error', 'offtakes_bias', 'offtakes_bias_bucket',
       'platform_name', 'parent_material_code', 'brand_code', 'vol_in_rum',
       'index rate'],
      dtype='object')

### DRM

In [12]:
delivery_df = pd.read_excel('/data/aman_singh/acuuracy_check/anaplan_snapshots_july.xlsx', sheet_name = 'DRM')

delivery_df['Channel'] = delivery_df['Channel'].replace({
    'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
delivery_df['month'] = '2026-07-31'
delivery_df['delivery_vol'] = delivery_df["Jul'26"]
# delivery_df_mar = pd.read_excel('/data/aman_singh/acuuracy_check/Mar Plans.xlsx', sheet_name = 'BAM')

# delivery_df_mar['Channel'] = delivery_df_mar['Channel'].replace({
#     'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
# delivery_df_mar['month'] = '2026-03-31'
# delivery_df_mar['delivery_vol'] = delivery_df_mar['Mar-26 Del']
# delivery_df = pd.concat([delivery_df, delivery_df_mar], ignore_index=True)
#delivery_df['delivery_vol'] = delivery_df['delivery_vol'].map(lambda x:0 if x.strip() == '-' else float(x.strip().replace(',','')))
# delivery_df.to_csv('delivery_data.csv')
delivery_df.columns = delivery_df.columns.str.lower()
delivery_df = delivery_df.groupby(['channel', 'depot','asm', 'psku','month'])['delivery_vol'].sum().reset_index(
)#.rename(columns = {'01-12-2025 Del Vol':'delivery_vol'})
delivery_df['month_date'] = pd.to_datetime(delivery_df['month'])
delivery_df.drop('month', axis=1, inplace=True)
delivery_df

      channel depot   asm    psku  delivery_vol month_date
0         B2B  D112  BCN1  718287         0.000 2026-07-31
1         B2B  D112  BCN1  718288         0.000 2026-07-31
2         B2B  D112  BCN1  718289         0.000 2026-07-31
3         B2B  D112  BCN1  718297         0.000 2026-07-31
4         B2B  D112  BCN1  718299         0.000 2026-07-31
...       ...   ...   ...     ...           ...        ...
91385    QCOM  D677  QCS2  811267         0.000 2026-07-31
91386    QCOM  D677  QCS2  811269         0.000 2026-07-31
91387    QCOM  D677  QCS2  811279         0.007 2026-07-31
91388    QCOM  D677  QCS2  811287         0.000 2026-07-31
91389    QCOM  D677  QCS2  811416         0.000 2026-07-31

[91390 rows x 6 columns]

In [13]:
delivery_df = delivery_df.groupby(['channel','depot', 'psku','month_date'])['delivery_vol'].sum().reset_index()
delivery_df

      channel depot    psku month_date  delivery_vol
0         B2B  D112  718287 2026-07-31         0.000
1         B2B  D112  718288 2026-07-31         0.000
2         B2B  D112  718289 2026-07-31         0.000
3         B2B  D112  718297 2026-07-31         0.000
4         B2B  D112  718299 2026-07-31         0.000
...       ...   ...     ...        ...           ...
64853    QCOM  D677  811267 2026-07-31         0.000
64854    QCOM  D677  811269 2026-07-31         0.000
64855    QCOM  D677  811279 2026-07-31         0.007
64856    QCOM  D677  811287 2026-07-31         0.000
64857    QCOM  D677  811416 2026-07-31         0.000

[64858 rows x 5 columns]

In [14]:
delivery_df['channel'].unique()

array(['B2B', 'CSD', 'ECOM', 'GT', 'MT', 'QCOM'], dtype=object)

In [15]:
df.columns

Index(['Unnamed: 0', 'forecast_granularity', 'forecast_type', 'channel',
       'portfolio', 'brand', 'run_month', 'm month', 'month_date', 'depot',
       'psku', 'stat vol', 'prophet vol', 'rf_vol', 'prophet heuristic vol',
       'rf heuristic vol', 'consensus vol', 'actuals vol', 'key', 'stat val',
       'consensus val', 'actuals val', 'stat error', 'consensus error',
       'stat abs error', 'consensus abs error', 'prophet vol_value',
       'rf_vol_value', 'prophet heuristic vol_value', 'rf heuristic vol_value',
       'stat_bias', 'stat_bias_bucket', 'chain', 'index rate'],
      dtype='object')

In [16]:
df[['channel', 'depot', 'psku','month_date']].dtypes

channel               object
depot                 object
psku                   int64
month_date    datetime64[ns]
dtype: object

In [17]:
df

,Unnamed: 0,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month_date,depot,...,stat abs error,consensus abs error,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,stat_bias,stat_bias_bucket,chain,index rate
0,20,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-06-30,M+1,2026-07-31,D117,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0% to 5%,NaN,NaN
1,21,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-06-30,M+1,2026-07-31,D117,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0% to 5%,NaN,NaN
2,22,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-06-30,M+1,2026-07-31,D117,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0% to 5%,NaN,NaN
3,23,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-06-30,M+1,2026-07-31,D117,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0% to 5%,NaN,NaN
4,24,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-06-30,M+1,2026-07-31,D117,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0% to 5%,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47647,149137,Chain x PSKU,offtakes_to_primary,QCOM,Male Grooming,SW_SGPRF,2026-06-30,M+1,2026-07-31,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto,1712.605337
47648,149138,Chain x PSKU,offtakes_to_primary,QCOM,Saffola Oils,SAF_CDPRS,2026-06-30,M+1,2026-07-31,NaN,...,0.021693,0.018603,NaN,NaN,NaN,NaN,-0.817974,< -15%,zepto,260000.000000
47649,149139,Chain x PSKU,offtakes_to_primary,QCOM,Hair Oils,PA_ESS_HO,2026-06-30,M+1,2026-07-31,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto,12860.631072
47650,149140,Chain x PSKU,offtakes_to_primary,QCOM,Hair Oils,PA_ESS_HO,2026-06-30,M+1,2026-07-31,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto,12860.631072
47651,149141,Chain x PSKU,offtakes_to_primary,QCOM,Saffola Oils,SAF_CDPRS,2026-06-30,M+1,2026-07-31,NaN,...,0.000000,0.008206,NaN,NaN,NaN,NaN,0.000000,0% to 5%,zepto,260000.000000

In [18]:
df['month_date'].unique()

<DatetimeArray>
['2026-07-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [19]:
delivery_df['month_date'] = pd.to_datetime(delivery_df['month_date'])
df['month_date'] = pd.to_datetime(df['month_date'], format='mixed')

In [20]:
df['forecast_type'].unique()#.isnull().sum()#['month_date'].unique()

array(['secondary', 'offtakes_to_primary'], dtype=object)

In [21]:
df.columns

Index(['Unnamed: 0', 'forecast_granularity', 'forecast_type', 'channel',
       'portfolio', 'brand', 'run_month', 'm month', 'month_date', 'depot',
       'psku', 'stat vol', 'prophet vol', 'rf_vol', 'prophet heuristic vol',
       'rf heuristic vol', 'consensus vol', 'actuals vol', 'key', 'stat val',
       'consensus val', 'actuals val', 'stat error', 'consensus error',
       'stat abs error', 'consensus abs error', 'prophet vol_value',
       'rf_vol_value', 'prophet heuristic vol_value', 'rf heuristic vol_value',
       'stat_bias', 'stat_bias_bucket', 'chain', 'index rate'],
      dtype='object')

In [22]:
df = df.merge(delivery_df, on=['channel', 'depot', 'psku','month_date'], how='left')
df.rename(columns={'delivery_vol': 'delivery_vol_drm'}, inplace=True)
df['delivery_vol_drm'].sum(), df['actuals vol'].sum()
df.columns = df.columns.str.lower()
df['delivery val_drm'] = df['delivery_vol_drm'] * df['index rate'] / (10 ** 7)

df['dp error drm'] = df['delivery val_drm'] - df['actuals val']
# df['Consensus Error_del'] = df['Consensus Val'] - df['Delivery Val']

df['dp abs error drm'] = np.abs(df['dp error drm'])
# df['Consensus Abs Error_del'] = np.abs(df['Consensus Error_del'])

In [23]:
df.shape

(47652, 38)

In [24]:
df[(df['channel'] == 'GT') & (df['month_date']=='2026-07-31')]['delivery val_drm'].sum()

410.2185867704886

### CAM

In [14]:
delivery_df = pd.read_excel('/data/aman_singh/acuuracy_check/anaplan_snapshots_aug.xlsx', sheet_name = 'CAM')

delivery_df['Channel'] = delivery_df['Channel'].replace({
    'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
delivery_df['month'] = '2026-08-31'
delivery_df['delivery_vol'] = delivery_df["Aug'26"]
# delivery_df_mar = pd.read_excel('/data/aman_singh/acuuracy_check/Mar Plans.xlsx', sheet_name = 'CAM')

# delivery_df_mar['Channel'] = delivery_df_mar['Channel'].replace({
#     'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
# delivery_df_mar['month'] = '2026-03-31'
# delivery_df_mar['delivery_vol'] = delivery_df_mar['Mar-26 Del']
# delivery_df = pd.concat([delivery_df, delivery_df_mar], ignore_index=True)
#delivery_df['delivery_vol'] = delivery_df['delivery_vol'].map(lambda x:0 if x.strip() == '-' else float(x.strip().replace(',','')))
# delivery_df.to_csv('delivery_data.csv')
delivery_df.columns = delivery_df.columns.str.lower()
delivery_df = delivery_df.groupby(['channel', 'depot','asm', 'psku','month'])['delivery_vol'].sum().reset_index(
)#.rename(columns = {'01-12-2025 Del Vol':'delivery_vol'})
delivery_df['month_date'] = pd.to_datetime(delivery_df['month'])
delivery_df.drop('month', axis=1, inplace=True)
delivery_df

      channel depot   asm    psku  delivery_vol month_date
0         B2B  D112  BCN1  718287      0.000000 2026-08-31
1         B2B  D112  BCN1  718288      0.000000 2026-08-31
2         B2B  D112  BCN1  718289      0.000000 2026-08-31
3         B2B  D112  BCN1  718297      0.000000 2026-08-31
4         B2B  D112  BCN1  718299      0.000000 2026-08-31
...       ...   ...   ...     ...           ...        ...
84858    QCOM  D677  QCS2  811267      0.000000 2026-08-31
84859    QCOM  D677  QCS2  811269      0.000000 2026-08-31
84860    QCOM  D677  QCS2  811279      0.006534 2026-08-31
84861    QCOM  D677  QCS2  811287      0.000000 2026-08-31
84862    QCOM  D677  QCS2  811416      0.000000 2026-08-31

[84863 rows x 6 columns]

In [15]:
delivery_df = delivery_df.groupby(['channel','depot', 'psku','month_date'])['delivery_vol'].sum().reset_index()
delivery_df

      channel depot    psku month_date  delivery_vol
0         B2B  D112  718287 2026-08-31      0.000000
1         B2B  D112  718288 2026-08-31      0.000000
2         B2B  D112  718289 2026-08-31      0.000000
3         B2B  D112  718297 2026-08-31      0.000000
4         B2B  D112  718299 2026-08-31      0.000000
...       ...   ...     ...        ...           ...
61332    QCOM  D677  811267 2026-08-31      0.000000
61333    QCOM  D677  811269 2026-08-31      0.000000
61334    QCOM  D677  811279 2026-08-31      0.006534
61335    QCOM  D677  811287 2026-08-31      0.000000
61336    QCOM  D677  811416 2026-08-31      0.000000

[61337 rows x 5 columns]

In [33]:
df = df.merge(delivery_df, on=['channel', 'depot', 'psku','month_date'], how='left')
df.rename(columns={'delivery_vol': 'delivery_vol_cam'}, inplace=True)
df['delivery_vol_cam'].sum(), df['actuals vol'].sum()
df.columns = df.columns.str.lower()
df['delivery val_cam'] = df['delivery_vol_cam'] * df['index rate'] / (10 ** 7)

df['dp error cam'] = df['delivery val_cam'] - df['actuals val']
# df['Consensus Error_del'] = df['Consensus Val'] - df['Delivery Val']

df['dp abs error cam'] = np.abs(df['dp error cam'])
# df['Consensus Abs Error_del'] = np.abs(df['Consensus Error_del'])

In [34]:
df

,unnamed: 0,forecast_granularity,forecast_type,channel,portfolio,brand,run_month,m month,month_date,depot,...,offtakes_bias_bucket,platform_name,parent_material_code,brand_code,vol_in_rum,index rate,delivery_vol_cam,delivery val_cam,dp error cam,dp abs error cam
0,40,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,42,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,Depot x PSKU,secondary,B2B,0,JH_FRG_L,2026-07-31,M+1,2026-08-31,D117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44552,32284,Chain x PSKU,offtakes,QCOM,Hair Oils,PA_ESS_HO,NaT,M+1,2026-08-31,NaN,...,> 15%,NaN,NaN,NaN,NaN,12860.631072,NaN,NaN,NaN,NaN
44553,32285,Chain x PSKU,offtakes,QCOM,Hair Oils,PA_ESS_HO,NaT,M+1,2026-08-31,NaN,...,< -15%,NaN,NaN,NaN,NaN,12860.631072,NaN,NaN,NaN,NaN
44554,32286,Chain x PSKU,offtakes,QCOM,Skin Care,PADV_WIPS,NaT,M+1,2026-08-31,NaN,...,> 15%,NaN,NaN,NaN,NaN,366.484998,NaN,NaN,NaN,NaN
44555,32287,Chain x PSKU,offtakes,QCOM,Skin Care,PABABY_GM,NaT,M+1,2026-08-31,NaN,...,< -15%,NaN,NaN,NaN,NaN,366.484998,NaN,NaN,NaN,NaN
44556,32288,Chain x PSKU,offtakes,QCOM,Saffola Oils,SAF_CDPRS,NaT,M+1,2026-08-31,NaN,...,> 15%,NaN,NaN,NaN,NaN,260000.000000,NaN,NaN,NaN,NaN

In [37]:
df[(df['month_date']=='2026-08-31')].groupby(['channel'])['delivery val_cam'].sum()

channel
B2B      12.889553
ECOM     67.254649
GT      431.147815
MT      125.894484
QCOM     35.289150
Name: delivery val_cam, dtype: float64

### BAM

In [42]:
delivery_df = pd.read_excel('/data/aman_singh/acuuracy_check/anaplan_snapshots_aug.xlsx', sheet_name = 'BAM')

delivery_df['Channel'] = delivery_df['Channel'].replace({
    'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
delivery_df['month'] = '2026-08-31'
delivery_df['delivery_vol'] = delivery_df["Aug'26"]
# delivery_df_mar = pd.read_excel('/data/aman_singh/acuuracy_check/Mar Plans.xlsx', sheet_name = 'BAM')

# delivery_df_mar['Channel'] = delivery_df_mar['Channel'].replace({
#     'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
# delivery_df_mar['month'] = '2026-03-31'
# delivery_df_mar['delivery_vol'] = delivery_df_mar['Mar-26 Del']
# delivery_df = pd.concat([delivery_df, delivery_df_mar], ignore_index=True)
#delivery_df['delivery_vol'] = delivery_df['delivery_vol'].map(lambda x:0 if x.strip() == '-' else float(x.strip().replace(',','')))
# delivery_df.to_csv('delivery_data.csv')
delivery_df.columns = delivery_df.columns.str.lower()
delivery_df = delivery_df.groupby(['channel', 'depot','asm', 'psku','month'])['delivery_vol'].sum().reset_index(
)#.rename(columns = {'01-12-2025 Del Vol':'delivery_vol'})
delivery_df['month_date'] = pd.to_datetime(delivery_df['month'])
delivery_df.drop('month', axis=1, inplace=True)
delivery_df

      channel depot   asm    psku  delivery_vol month_date
0         B2B  D112  BCN1  718287           0.0 2026-08-31
1         B2B  D112  BCN1  718288           0.0 2026-08-31
2         B2B  D112  BCN1  718289           0.0 2026-08-31
3         B2B  D112  BCN1  718297           0.0 2026-08-31
4         B2B  D112  BCN1  718299           0.0 2026-08-31
...       ...   ...   ...     ...           ...        ...
85937    QCOM  D677  QCS2  811269           0.0 2026-08-31
85938    QCOM  D677  QCS2  811279           0.0 2026-08-31
85939    QCOM  D677  QCS2  811287           0.0 2026-08-31
85940    QCOM  D677  QCS2  811416           0.0 2026-08-31
85941    QCOM  D677  QCS2  811564           0.0 2026-08-31

[85942 rows x 6 columns]

In [43]:
delivery_df = delivery_df.groupby(['channel','depot', 'psku','month_date'])['delivery_vol'].sum().reset_index()
delivery_df

      channel depot    psku month_date  delivery_vol
0         B2B  D112  718287 2026-08-31           0.0
1         B2B  D112  718288 2026-08-31           0.0
2         B2B  D112  718289 2026-08-31           0.0
3         B2B  D112  718297 2026-08-31           0.0
4         B2B  D112  718299 2026-08-31           0.0
...       ...   ...     ...        ...           ...
61748    QCOM  D677  811269 2026-08-31           0.0
61749    QCOM  D677  811279 2026-08-31           0.0
61750    QCOM  D677  811287 2026-08-31           0.0
61751    QCOM  D677  811416 2026-08-31           0.0
61752    QCOM  D677  811564 2026-08-31           0.0

[61753 rows x 5 columns]

In [44]:
delivery_df['delivery_vol'].sum()

6924880.645649692

In [45]:
df.shape

(44557, 49)

In [ ]:
# df.drop(columns = ['delivery_vol_bam',
#        'delivery val_bam', 'dp error bam', 'dp abs error bam'],inplace = True)

In [46]:
df = df.merge(delivery_df, on=['channel', 'depot', 'psku','month_date'], how='left')
df.rename(columns={'delivery_vol': 'delivery_vol_bam'}, inplace=True)
df['delivery_vol_bam'].sum(), df['actuals vol'].sum()
df.columns = df.columns.str.lower()
df['delivery val_bam'] = df['delivery_vol_bam'] * df['index rate'] / (10 ** 7)

df['dp error bam'] = df['delivery val_bam'] - df['actuals val']
# df['Consensus Error_del'] = df['Consensus Val'] - df['Delivery Val']

df['dp abs error bam'] = np.abs(df['dp error bam'])
# df['Consensus Abs Error_del'] = np.abs(df['Consensus Error_del'])

In [47]:
df.shape

(44557, 53)

In [48]:
df[(df['month_date']=='2026-08-31')].groupby(['channel'])['delivery val_bam'].sum()

channel
B2B      12.880525
ECOM     71.386939
GT      426.248434
MT      125.475961
QCOM     35.175791
Name: delivery val_bam, dtype: float64

In [49]:
previous_data = pd.read_excel('/data/aman_singh/acuuracy_check/fva_and_stat_accuracy_till_june.xlsx', sheet_name = 'fva_depot_psku_final')
previous_data

,forecast_granularity,forecast_type,channel,depot,psku,brand,portfolio,month,m month,stat vol,...,prophet heuristic vol,rf heuristic vol,key,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,pred_prophet,unc,NPD Flag
0,Depot x PSKU,secondary,B2B,D112,718287.0,PCNO(R),CNO,2025-11-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON-NPD
1,Depot x PSKU,secondary,B2B,D112,718287.0,PCNO(R),CNO,2025-12-31,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON-NPD
2,Depot x PSKU,secondary,B2B,D112,718297.0,PCNO(R),CNO,2025-11-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON-NPD
3,Depot x PSKU,secondary,B2B,D112,718297.0,PCNO(R),CNO,2025-12-31,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON-NPD
4,Depot x PSKU,secondary,B2B,D112,718297.0,PCNO(R),CNO,2026-01-31,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NON-NPD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306783,Chain x PSKU,offtakes_to_primary,ECOM,NaN,811181.0,SAF_CDPRS,Saffola Oils,2026-06-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NPD
306784,Chain x PSKU,offtakes_to_primary,ECOM,NaN,811267.0,PA_ESS_HO,Hair Oils,2026-06-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NPD
306785,Chain x PSKU,offtakes_to_primary,ECOM,NaN,811268.0,PA_ESS_HO,Hair Oils,2026-06-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NPD
306786,Chain x PSKU,offtakes_to_primary,ECOM,NaN,811269.0,PA_ESS_HO,Hair Oils,2026-06-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NPD
306787,Chain x PSKU,offtakes_to_primary,ECOM,NaN,811279.0,SAF_CDPRS,Saffola Oils,2026-06-30,M+1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NPD

In [51]:
x = pd.DataFrame(columns=previous_data.columns)
# df_offtakes = df_offtakes[df_offtakes['month'].isin(['2026-06-30','2026-07-31'])]
# offtakes_july = pd.concat([x, df_offtakes], ignore_index=True)
# offtakes_july
x.columns

Index(['forecast_granularity', 'forecast_type', 'channel', 'depot', 'psku',
       'brand', 'portfolio', 'month', 'm month', 'stat vol', 'actuals vol',
       'consensus vol', 'index rate', 'stat val', 'consensus val',
       'actuals val', 'stat error', 'consensus error', 'stat abs error',
       'consensus abs error', 'stat_bias', 'stat_bias_bucket',
       'delivery_vol_drm', 'delivery val_drm', 'delivery_vol_cam',
       'delivery val_cam', 'delivery_vol_bam', 'delivery val_bam',
       'brand class', 'dp error drm', 'dp abs error drm', 'dp error cam',
       'dp abs error cam', 'dp error bam', 'dp abs error bam',
       'Bias bucket drm', 'bias bucket cam', 'bias_bucket_bam',
       'bias_bucket_plan', 'chain', 'offtakes_forecasted_value',
       'offtakes_forecasted_vol', 'offtakes actuals val', 'offtakes error',
       'offtakes abs error', 'offtakes_bias', 'offtakes_bias_bucket',
       'Brand_class', 'unnamed: 0.1', 'unnamed: 0', 'run_month', 'prophet vol',
       'rf_vol', 'prophet heuristic vol', 'rf heuristic vol', 'key',
       'prophet vol_value', 'rf_vol_value', 'prophet heuristic vol_value',
       'rf heuristic vol_value', 'pred_prophet', 'unc', 'NPD Flag'],
      dtype='object')

In [52]:
df.columns

Index(['unnamed: 0', 'forecast_granularity', 'forecast_type', 'channel',
       'portfolio', 'brand', 'run_month', 'm month', 'month_date', 'depot',
       'psku', 'stat vol', 'prophet vol', 'rf_vol', 'prophet heuristic vol',
       'rf heuristic vol', 'consensus vol', 'actuals vol', 'key', 'stat val',
       'consensus val', 'actuals val', 'stat error', 'consensus error',
       'stat abs error', 'consensus abs error', 'prophet vol_value',
       'rf_vol_value', 'prophet heuristic vol_value', 'rf heuristic vol_value',
       'stat_bias', 'stat_bias_bucket', 'chain', 'offtakes_forecasted_value',
       'offtakes_forecasted_vol', 'offtakes actuals val', 'offtakes error',
       'offtakes abs error', 'offtakes_bias', 'offtakes_bias_bucket',
       'platform_name', 'parent_material_code', 'brand_code', 'vol_in_rum',
       'index rate', 'delivery_vol_cam', 'delivery val_cam', 'dp error cam',
       'dp abs error cam', 'delivery_vol_bam', 'delivery val_bam',
       'dp error bam', 'dp abs error bam'],
      dtype='object')

In [53]:
df.rename(columns = {'month_date':'month'}, inplace = True)
final_data = pd.concat([x, df])
final_data

,forecast_granularity,forecast_type,channel,depot,psku,brand,portfolio,month,m month,stat vol,...,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,pred_prophet,unc,NPD Flag,platform_name,parent_material_code,brand_code,vol_in_rum
0,Depot x PSKU,secondary,B2B,D117,734910,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Depot x PSKU,secondary,B2B,D117,734988,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Depot x PSKU,secondary,B2B,D117,734993,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Depot x PSKU,secondary,B2B,D117,734995,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Depot x PSKU,secondary,B2B,D117,735043,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44552,Chain x PSKU,offtakes,QCOM,NaN,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44553,Chain x PSKU,offtakes,QCOM,NaN,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44554,Chain x PSKU,offtakes,QCOM,NaN,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44555,Chain x PSKU,offtakes,QCOM,NaN,811021,PABABY_GM,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44556,Chain x PSKU,offtakes,QCOM,NaN,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
final_data['month'].unique()

<DatetimeArray>
['2026-08-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [55]:
final_data.isnull().sum()

forecast_granularity        0
forecast_type               0
channel                     0
depot                    4051
psku                        0
                        ...
NPD Flag                44557
platform_name           44557
parent_material_code    44557
brand_code              44557
vol_in_rum              44557
Length: 67, dtype: int64

In [56]:
final_data

,forecast_granularity,forecast_type,channel,depot,psku,brand,portfolio,month,m month,stat vol,...,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,pred_prophet,unc,NPD Flag,platform_name,parent_material_code,brand_code,vol_in_rum
0,Depot x PSKU,secondary,B2B,D117,734910,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Depot x PSKU,secondary,B2B,D117,734988,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Depot x PSKU,secondary,B2B,D117,734993,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Depot x PSKU,secondary,B2B,D117,734995,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Depot x PSKU,secondary,B2B,D117,735043,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44552,Chain x PSKU,offtakes,QCOM,NaN,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44553,Chain x PSKU,offtakes,QCOM,NaN,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44554,Chain x PSKU,offtakes,QCOM,NaN,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44555,Chain x PSKU,offtakes,QCOM,NaN,811021,PABABY_GM,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44556,Chain x PSKU,offtakes,QCOM,NaN,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_data[final_data['month'] == '2026-08-31'].to_csv('stat_fva_aug.csv')#['month'].unique()

,forecast_granularity,forecast_type,channel,depot,psku,brand,portfolio,month,m month,stat vol,...,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,pred_prophet,unc,NPD Flag,platform_name,parent_material_code,brand_code,vol_in_rum
0,Depot x PSKU,secondary,B2B,D117,734910,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Depot x PSKU,secondary,B2B,D117,734988,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Depot x PSKU,secondary,B2B,D117,734993,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Depot x PSKU,secondary,B2B,D117,734995,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Depot x PSKU,secondary,B2B,D117,735043,JH_FRG_L,0,2026-08-31,M+1,0.0,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44552,Chain x PSKU,offtakes,QCOM,NaN,810971,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44553,Chain x PSKU,offtakes,QCOM,NaN,811005,PA_ESS_HO,Hair Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44554,Chain x PSKU,offtakes,QCOM,NaN,811019,PADV_WIPS,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44555,Chain x PSKU,offtakes,QCOM,NaN,811021,PABABY_GM,Skin Care,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44556,Chain x PSKU,offtakes,QCOM,NaN,811181,SAF_CDPRS,Saffola Oils,2026-08-31,M+1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
final_data[(final_data['forecast_granularity'] == 'Chain x PSKU') & (final_data['forecast_type'] == 'offtakes_to_primary')]

,forecast_granularity,forecast_type,channel,depot,psku,brand,portfolio,month,m month,stat vol,...,rf_vol,prophet heuristic vol,rf heuristic vol,key,prophet vol_value,rf_vol_value,prophet heuristic vol_value,rf heuristic vol_value,pred_prophet,pred_rf
38292,Chain x PSKU,offtakes_to_primary,QCOM,NaN,718287,PCNO(R),CNO,2026-01-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38293,Chain x PSKU,offtakes_to_primary,QCOM,NaN,718288,SAFF GOLD,Saffola Oils,2026-01-31,M+1,52.041436,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38294,Chain x PSKU,offtakes_to_primary,QCOM,NaN,718297,PCNO(R),CNO,2026-01-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38295,Chain x PSKU,offtakes_to_primary,QCOM,NaN,718299,PCNO(R),CNO,2026-01-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38296,Chain x PSKU,offtakes_to_primary,QCOM,NaN,718300,PCNO FLEX,CNO,2026-01-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62880,Chain x PSKU,offtakes_to_primary,QCOM,NaN,810971,PA_ESS_HO,Hair Oils,2026-05-31,M+1,0.180968,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62881,Chain x PSKU,offtakes_to_primary,QCOM,NaN,811005,PA_ESS_HO,Hair Oils,2026-05-31,M+1,0.154828,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62882,Chain x PSKU,offtakes_to_primary,QCOM,NaN,811169,SW_SGPRF,Male Grooming,2026-05-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62883,Chain x PSKU,offtakes_to_primary,QCOM,NaN,811181,SAF_CDPRS,Saffola Oils,2026-05-31,M+1,0.043734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62884,Chain x PSKU,offtakes_to_primary,QCOM,NaN,811267,PA_ESS_HO,Hair Oils,2026-05-31,M+1,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN