In [232]:
import warnings
warnings.filterwarnings('ignore')

import os
import gc
import pickle

import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt

from datetime import datetime
from pandas.tseries.offsets import MonthEnd

In [233]:
os.listdir('/data/aman_singh/acuuracy_check')

['missing_keys_drm.csv',
 'Heuristics_all_combination_qcom_cp_apr_live.xlsx',
 'seasonality_all2.csv',
 'chek_nan.csv',
 'missing_keys_drm2.csv',
 'all_combination_ecom_may_pred.csv',
 'QCOM Chain FC PSKU Primary_as_on_11th_Feb_2026.xlsb',
 'soh_recent_qcom.csv',
 'combine_model+missing_forecasts_brand_asm.ipynb',
 'April-26 Plans.xlsx',
 'QCOM Chain PSKU OTP Output',
 'Heuristics_all_combination_ecom_may_live.xlsx',
 'Norms 202602.csv',
 'duplicates_after_realignment.csv',
 'ALL Channels Accuracy_fva.ipynb',
 "mt_channels Live Run may'26.csv",
 't_thres_df_2.csv',
 'ecom_chain_psku_offtake_to_secondary_v6_PROD.ipynb',
 'qcom_chain_depot_psku_primary_forecast.csv',
 "gt_channels Live Run may'26.csv",
 'seasonality.xlsx',
 'ECOM Chain PSKU Primary_as_on_12_Jan_2026 (1).xlsb',
 'QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku.ipynb',
 'soh_base_may_run.csv',
 'combine_model+missing_forecasts.ipynb',
 'Heuristics_all_combination_ecom_apr_live.xlsx',
 'trend_gt4.csv',
 'handle_missing_forecasts_brand_asm.ipynb',
 'QCOM Chain FC PSKU Primary_as_on_10_Jan_2026 (1).xlsb',
 'QCOM_FINAL_offtake_to_secondary_depot_psku.ipynb',
 'Stat Demand Forecast MT_as_on_11th_Mar_2026.xlsb',
 'soh_base_apr_run.csv',
 'Offtakes_Chain_PSKU_ECOM.xlsx',
 'handle_missing_forecasts.ipynb',
 'ALL Channels Accuracy framework.ipynb',
 'SOH - 01 May.xlsx',
 'collate_offtake_heuristics_qcom_depot_psku_backtest.ipynb',
 't_thres_df_qcom.csv',
 'backtest_qcom_cd.csv',
 'offtake_accuracy.csv',
 'accuracy_framework_data_upload.ipynb',
 'Ecom Depot Psku Primary_as_on_10th_mar.xlsx',
 'Qcom Depot Psku Primary_Forecast_as_on_12th_march (1).xlsx',
 'seasonal_anomaly_keys.csv',
 'Qcom Depot Psku Primary_Forecast_as_on_12th_march.xlsx',
 'QCOM_FINAL_offtake_to_secondary_chain_pksu_live_v4_iterative 1.ipynb',
 'Mar Plans.xlsx',
 'ECOM Chain PSKU Primary_as_on_11th_Feb_2026.xlsb',
 'trn_soh_dc_master.csv',
 'collate_brand_asm.ipynb',
 'final_collated_data_12_months_live2.xlsx',
 'brand_class_new.xlsx',
 'trend_gt3.csv',
 'dcm_table.csv',
 'all_combination_GT_channel_trend.csv',
 'SOH - 01 Apr.xlsx',
 'plan_actuals_aggregated.csv',
 'collate_brand_asm_post_processing.ipynb',
 'acc_framework_mar_apr.xlsx',
 'stat_fva_till_april.csv',
 'trend_file_train_till_31_May_2026.csv',
 'all_combination_MT_channel_trend.csv',
 'all_combination_qcom_trend.csv',
 'acc_framework_apr.xlsx',
 'QCOM Chain FC PSKU Primary_as_on_10_Dec_2025.xlsb',
 'fva_depot_psku_april.csv',
 'all_combination_qcom_cp_may_pred.csv',
 'collate_offtake_heuristics_qcom_psku_new_approach_live.ipynb',
 'Norms 202605.csv',
 'seasonal_anomaly_brands.csv',
 'Heuristics_all_combination_qcom_cd_backtest.xlsx',
 "gt_channels Live Run apr'26.csv",
 'non_co_p3m_apr.csv',
 'Trend_qcom.csv',
 'collate.ipynb',
 'final_collated_data_12_months_live.xlsx',
 'Norms 202604.csv',
 'plan_actuals_df.csv',
 '.git',
 'Stat Demand Forecast GT_as_on_11th_Mar_2026.xlsb',
 'acc_framework_apr_final.xlsx',
 'all_combination_GT_live_may.xlsx',
 'depot_asm_mappings.xlsx',
 'Marico Ltd._forecast_Jun 2026_to_Sep 2026.csv',
 'missing_df_mt_all.csv',
 'all_combination_MT_live_may.xlsx',
 'all_combination_ecom_trend.csv',
 'collate_offtake_heuristics_ecom_psku_new_approach_live.ipynb',
 'Feb Plans.xlsx',
 'prophet_data_train_till_31_May_2026.csv',
 'fva_and_stat_accuracy.xlsx',
 'QCOM_NORMS_FINAL_offtake_to_secondary_chain_pksu_live_v3 copy.ipynb',
 'process_live runs_soh_files.ipynb',
 'missing_df_all5.csv',
 'filled_outliers_all.csv',
 'Heuristics_all_combination_qcom_cp_may_live.xlsx',
 'stat_fva_till_april2.csv']

In [234]:
base_dir = '/data/aman_singh/acuuracy_check'
input_table = 'TRN_DF_QCOM_OFFTAKE_CHAIN_DEPOT_PSKU'
run_month = '2026-06-30'

In [235]:
def list_all_files_in_directory(root):
    out = []

    for path, subdirs, files in os.walk(root):
        for name in files:
            out.append(os.path.join(path, name))

    return out

In [236]:
list_all_files_in_directory(base_dir)

['/data/aman_singh/acuuracy_check/missing_keys_drm.csv',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_qcom_cp_apr_live.xlsx',
 '/data/aman_singh/acuuracy_check/seasonality_all2.csv',
 '/data/aman_singh/acuuracy_check/chek_nan.csv',
 '/data/aman_singh/acuuracy_check/missing_keys_drm2.csv',
 '/data/aman_singh/acuuracy_check/all_combination_ecom_may_pred.csv',
 '/data/aman_singh/acuuracy_check/QCOM Chain FC PSKU Primary_as_on_11th_Feb_2026.xlsb',
 '/data/aman_singh/acuuracy_check/soh_recent_qcom.csv',
 '/data/aman_singh/acuuracy_check/combine_model+missing_forecasts_brand_asm.ipynb',
 '/data/aman_singh/acuuracy_check/April-26 Plans.xlsx',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_ecom_may_live.xlsx',
 '/data/aman_singh/acuuracy_check/Norms 202602.csv',
 '/data/aman_singh/acuuracy_check/duplicates_after_realignment.csv',
 '/data/aman_singh/acuuracy_check/ALL Channels Accuracy_fva.ipynb',
 "/data/aman_singh/acuuracy_check/mt_channels Live Run may'26.csv",
 '/data/aman_singh/acuuracy_check/t_thres_df_2.csv',
 '/data/aman_singh/acuuracy_check/ecom_chain_psku_offtake_to_secondary_v6_PROD.ipynb',
 '/data/aman_singh/acuuracy_check/qcom_chain_depot_psku_primary_forecast.csv',
 "/data/aman_singh/acuuracy_check/gt_channels Live Run may'26.csv",
 '/data/aman_singh/acuuracy_check/seasonality.xlsx',
 '/data/aman_singh/acuuracy_check/ECOM Chain PSKU Primary_as_on_12_Jan_2026 (1).xlsb',
 '/data/aman_singh/acuuracy_check/QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku.ipynb',
 '/data/aman_singh/acuuracy_check/soh_base_may_run.csv',
 '/data/aman_singh/acuuracy_check/combine_model+missing_forecasts.ipynb',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_ecom_apr_live.xlsx',
 '/data/aman_singh/acuuracy_check/trend_gt4.csv',
 '/data/aman_singh/acuuracy_check/handle_missing_forecasts_brand_asm.ipynb',
 '/data/aman_singh/acuuracy_check/QCOM Chain FC PSKU Primary_as_on_10_Jan_2026 (1).xlsb',
 '/data/aman_singh/acuuracy_check/QCOM_FINAL_offtake_to_secondary_depot_psku.ipynb',
 '/data/aman_singh/acuuracy_check/Stat Demand Forecast MT_as_on_11th_Mar_2026.xlsb',
 '/data/aman_singh/acuuracy_check/soh_base_apr_run.csv',
 '/data/aman_singh/acuuracy_check/Offtakes_Chain_PSKU_ECOM.xlsx',
 '/data/aman_singh/acuuracy_check/handle_missing_forecasts.ipynb',
 '/data/aman_singh/acuuracy_check/ALL Channels Accuracy framework.ipynb',
 '/data/aman_singh/acuuracy_check/SOH - 01 May.xlsx',
 '/data/aman_singh/acuuracy_check/collate_offtake_heuristics_qcom_depot_psku_backtest.ipynb',
 '/data/aman_singh/acuuracy_check/t_thres_df_qcom.csv',
 '/data/aman_singh/acuuracy_check/backtest_qcom_cd.csv',
 '/data/aman_singh/acuuracy_check/offtake_accuracy.csv',
 '/data/aman_singh/acuuracy_check/accuracy_framework_data_upload.ipynb',
 '/data/aman_singh/acuuracy_check/Ecom Depot Psku Primary_as_on_10th_mar.xlsx',
 '/data/aman_singh/acuuracy_check/Qcom Depot Psku Primary_Forecast_as_on_12th_march (1).xlsx',
 '/data/aman_singh/acuuracy_check/seasonal_anomaly_keys.csv',
 '/data/aman_singh/acuuracy_check/Qcom Depot Psku Primary_Forecast_as_on_12th_march.xlsx',
 '/data/aman_singh/acuuracy_check/QCOM_FINAL_offtake_to_secondary_chain_pksu_live_v4_iterative 1.ipynb',
 '/data/aman_singh/acuuracy_check/Mar Plans.xlsx',
 '/data/aman_singh/acuuracy_check/ECOM Chain PSKU Primary_as_on_11th_Feb_2026.xlsb',
 '/data/aman_singh/acuuracy_check/trn_soh_dc_master.csv',
 '/data/aman_singh/acuuracy_check/collate_brand_asm.ipynb',
 '/data/aman_singh/acuuracy_check/final_collated_data_12_months_live2.xlsx',
 '/data/aman_singh/acuuracy_check/brand_class_new.xlsx',
 '/data/aman_singh/acuuracy_check/trend_gt3.csv',
 '/data/aman_singh/acuuracy_check/dcm_table.csv',
 '/data/aman_singh/acuuracy_check/all_combination_GT_channel_trend.csv',
 '/data/aman_singh/acuuracy_check/SOH - 01 Apr.xlsx',
 '/data/aman_singh/acuuracy_check/plan_actuals_aggregated.csv',
 '/data/aman_singh/acuuracy_check/collate_brand_asm_post_processing.ipynb',
 '/data/aman_singh/acuuracy_check/acc_framework_mar_apr.xlsx',
 '/data/aman_singh/acuuracy_check/stat_fva_till_april.csv',
 '/data/aman_singh/acuuracy_check/trend_file_train_till_31_May_2026.csv',
 '/data/aman_singh/acuuracy_check/all_combination_MT_channel_trend.csv',
 '/data/aman_singh/acuuracy_check/all_combination_qcom_trend.csv',
 '/data/aman_singh/acuuracy_check/acc_framework_apr.xlsx',
 '/data/aman_singh/acuuracy_check/QCOM Chain FC PSKU Primary_as_on_10_Dec_2025.xlsb',
 '/data/aman_singh/acuuracy_check/fva_depot_psku_april.csv',
 '/data/aman_singh/acuuracy_check/all_combination_qcom_cp_may_pred.csv',
 '/data/aman_singh/acuuracy_check/collate_offtake_heuristics_qcom_psku_new_approach_live.ipynb',
 '/data/aman_singh/acuuracy_check/Norms 202605.csv',
 '/data/aman_singh/acuuracy_check/seasonal_anomaly_brands.csv',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_qcom_cd_backtest.xlsx',
 "/data/aman_singh/acuuracy_check/gt_channels Live Run apr'26.csv",
 '/data/aman_singh/acuuracy_check/non_co_p3m_apr.csv',
 '/data/aman_singh/acuuracy_check/Trend_qcom.csv',
 '/data/aman_singh/acuuracy_check/collate.ipynb',
 '/data/aman_singh/acuuracy_check/final_collated_data_12_months_live.xlsx',
 '/data/aman_singh/acuuracy_check/Norms 202604.csv',
 '/data/aman_singh/acuuracy_check/plan_actuals_df.csv',
 '/data/aman_singh/acuuracy_check/Stat Demand Forecast GT_as_on_11th_Mar_2026.xlsb',
 '/data/aman_singh/acuuracy_check/acc_framework_apr_final.xlsx',
 '/data/aman_singh/acuuracy_check/all_combination_GT_live_may.xlsx',
 '/data/aman_singh/acuuracy_check/depot_asm_mappings.xlsx',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Jun 2026_to_Sep 2026.csv',
 '/data/aman_singh/acuuracy_check/missing_df_mt_all.csv',
 '/data/aman_singh/acuuracy_check/all_combination_MT_live_may.xlsx',
 '/data/aman_singh/acuuracy_check/all_combination_ecom_trend.csv',
 '/data/aman_singh/acuuracy_check/collate_offtake_heuristics_ecom_psku_new_approach_live.ipynb',
 '/data/aman_singh/acuuracy_check/Feb Plans.xlsx',
 '/data/aman_singh/acuuracy_check/prophet_data_train_till_31_May_2026.csv',
 '/data/aman_singh/acuuracy_check/fva_and_stat_accuracy.xlsx',
 '/data/aman_singh/acuuracy_check/QCOM_NORMS_FINAL_offtake_to_secondary_chain_pksu_live_v3 copy.ipynb',
 '/data/aman_singh/acuuracy_check/process_live runs_soh_files.ipynb',
 '/data/aman_singh/acuuracy_check/missing_df_all5.csv',
 '/data/aman_singh/acuuracy_check/filled_outliers_all.csv',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_qcom_cp_may_live.xlsx',
 '/data/aman_singh/acuuracy_check/stat_fva_till_april2.csv',
 '/data/aman_singh/acuuracy_check/QCOM Chain PSKU OTP Output/Backtest run/QCOM Chain Depot PSKU Primary_Backtest run_02_Jun_2026.csv',
 '/data/aman_singh/acuuracy_check/QCOM Chain PSKU OTP Output/Backtest run/QCOM Depot PSKU Primary_Backtest run_02_Jun_2026.csv',
 '/data/aman_singh/acuuracy_check/.git/index',
 '/data/aman_singh/acuuracy_check/.git/COMMIT_EDITMSG',
 '/data/aman_singh/acuuracy_check/.git/ORIG_HEAD',
 '/data/aman_singh/acuuracy_check/.git/config',
 '/data/aman_singh/acuuracy_check/.git/description',
 '/data/aman_singh/acuuracy_check/.git/HEAD',
 '/data/aman_singh/acuuracy_check/.git/logs/HEAD',
 '/data/aman_singh/acuuracy_check/.git/logs/refs/heads/main',
 '/data/aman_singh/acuuracy_check/.git/logs/refs/remotes/origin/main',
 '/data/aman_singh/acuuracy_check/.git/refs/heads/main',
 '/data/aman_singh/acuuracy_check/.git/refs/remotes/origin/main',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-push.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-commit.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-rebase.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-merge-commit.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/applypatch-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/push-to-checkout.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/fsmonitor-watchman.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-receive.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-applypatch.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/sendemail-validate.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/update.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/post-update.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/commit-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/prepare-commit-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/info/exclude',
 '/data/aman_singh/acuuracy_check/.git/objects/50/5a68c36226efc452d4009c38fd52f3d548ee86',
 '/data/aman_singh/acuuracy_check/.git/objects/50/555ca3beca18344dd0dec82724443fa7e3d133',
 '/data/aman_singh/acuuracy_check/.git/objects/0c/b4ce8ccbd2c42af00e9678b36e12db21c840b5',
 '/data/aman_singh/acuuracy_check/.git/objects/8e/408f89117abdba37da256e76a82920cc4acb1e',
 '/data/aman_singh/acuuracy_check/.git/objects/be/85d199f02441f3bff827ee72a95f33d7ba8ed0',
 '/data/aman_singh/acuuracy_check/.git/objects/e7/fa07340e3a9d4104d8563d8560ed380eeb6159',
 '/data/aman_singh/acuuracy_check/.git/objects/6d/76b06afce74369da4697cf9b8eb1bfd2d2dbb4',
 '/data/aman_singh/acuuracy_check/.git/objects/af/3a2e50d73d875546b77115c8741d4b7c4b289f',
 '/data/aman_singh/acuuracy_check/.git/objects/af/5093244dc52810897ba686596043d08fadc098',
 '/data/aman_singh/acuuracy_check/.git/objects/af/3a3a2502dd862ac27931f5997e5c37b0c07fc0',
 '/data/aman_singh/acuuracy_check/.git/objects/fa/413b46d3d90f71062146af079bcd1f7fe70294',
 '/data/aman_singh/acuuracy_check/.git/objects/d5/54f1b51312f0096f97de946ea783287e2fdb7c',
 '/data/aman_singh/acuuracy_check/.git/objects/70/dd575228c20ca1488b905e40fe921de69b5749',
 '/data/aman_singh/acuuracy_check/.git/objects/70/d67d824db31821b8704788faed015e715a78bc',
 '/data/aman_singh/acuuracy_check/.git/objects/9c/9dd5c94a2d50011052128666fb1404b8556b5a',
 '/data/aman_singh/acuuracy_check/.git/objects/9c/b01ed69ed3b7e3076c2c1d0aeb8171a20d7782',
 '/data/aman_singh/acuuracy_check/.git/objects/9c/b315ceb8762ec00895ac6ac547eeb998f0c60c',
 '/data/aman_singh/acuuracy_check/.git/objects/09/23a2907c1471553d041be0966e49a475281444',
 '/data/aman_singh/acuuracy_check/.git/objects/09/7d15c7bde8a7b49539e162764c9a6d73bc5c9d',
 '/data/aman_singh/acuuracy_check/.git/objects/09/8d2a7d3a3932d51487aa7d340d1138e85ff472',
 '/data/aman_singh/acuuracy_check/.git/objects/c4/698674abeb93550daefbdf194f2f9f44ab66af',
 '/data/aman_singh/acuuracy_check/.git/objects/57/340a15b1f8911f76529e7f820f54003a32644d',
 '/data/aman_singh/acuuracy_check/.git/objects/57/3cde6ae6e28b548bfa572f531601bd7f9167b1',
 '/data/aman_singh/acuuracy_check/.git/objects/d3/572102468a07d02d4e0dd1c88982d3527399b6',
 '/data/aman_singh/acuuracy_check/.git/objects/fe/8d2b1c0fc9241fefa78fde99b64aefdcfb2d46',
 '/data/aman_singh/acuuracy_check/.git/objects/fe/f6e2cd019f6b6868b1e83dbfee99f7eda0826d',
 '/data/aman_singh/acuuracy_check/.git/objects/fe/c85e9527fddc7d5c460f1e9f47f83af717610b',
 '/data/aman_singh/acuuracy_check/.git/objects/0d/8c380ee67e6e76fca4935239e5f096da6b015b',
 '/data/aman_singh/acuuracy_check/.git/objects/9e/b665f0d7e25ebb4482eee20ec7b6cfb123c6a3',
 '/data/aman_singh/acuuracy_check/.git/objects/9e/3aba2d0b62e5909b463f1f5e269d2a6b2cfaa8',
 '/data/aman_singh/acuuracy_check/.git/objects/f1/b912a00253097257a2027cc1da5b60f8fc29da',
 '/data/aman_singh/acuuracy_check/.git/objects/5c/85bc5b639b0c9958ce49cc02ff318b7cbdc5be',
 '/data/aman_singh/acuuracy_check/.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391',
 '/data/aman_singh/acuuracy_check/.git/objects/e6/b24f700863f2011d86ea092cffd73ba40c28f5',
 '/data/aman_singh/acuuracy_check/.git/objects/8d/7a70aead5bd4660cea0e4ccb18f1773d6398fb',
 '/data/aman_singh/acuuracy_check/.git/objects/8d/68e2e1edfc6ae9d25869fc4aa516d1a5240ad1',
 '/data/aman_singh/acuuracy_check/.git/objects/8d/3de07a81749be134c43ded50ba35aee28956df',
 '/data/aman_singh/acuuracy_check/.git/objects/8d/b5a4ada98a487cd4c9cfd54a7add5d9b059ee8',
 '/data/aman_singh/acuuracy_check/.git/objects/75/6965a687e386faa22a4baf140f707c3c5f49c4',
 '/data/aman_singh/acuuracy_check/.git/objects/12/465b5c74ad2bf64bb218f7403c9ee398af3968',
 '/data/aman_singh/acuuracy_check/.git/objects/0f/9d52a7c1b90b725d1fd0b7244a11c594a2509c',
 '/data/aman_singh/acuuracy_check/.git/objects/19/5000d3744b4e8276d0da3528254bdbdff69e31',
 '/data/aman_singh/acuuracy_check/.git/objects/19/f168d6c54ad6176c84c76c7e4e0585c6b2c4c0',
 '/data/aman_singh/acuuracy_check/.git/objects/19/8a5f8d30db364de394b4f826e1eeab2c78d9cf',
 '/data/aman_singh/acuuracy_check/.git/objects/a4/932fcc7faecb828ee4143e9b5f516a51eafae7',
 '/data/aman_singh/acuuracy_check/.git/objects/45/ae6674442ba7caff65fed1682d31435362e839',
 '/data/aman_singh/acuuracy_check/.git/objects/45/debe7d54b1484fcbbaed823530369a0453c51c',
 '/data/aman_singh/acuuracy_check/.git/objects/f6/e143d2fd722392ecef7f6f601f6fb824a9bd5f',
 '/data/aman_singh/acuuracy_check/.git/objects/f6/6802cfb3cab9b371a29b2522b80f4c303aa94a',
 '/data/aman_singh/acuuracy_check/.git/objects/f6/747d2aae291bb35eb87c51f66169832b319a41',
 '/data/aman_singh/acuuracy_check/.git/objects/4d/0fdfe4376fdbe91c999e29002b4ced574f4e5f',
 '/data/aman_singh/acuuracy_check/.git/objects/4d/4e939222e516adcbc67a747c9ed3fb06360131',
 '/data/aman_singh/acuuracy_check/.git/objects/16/4e7c97d31d433a1d7726c3ab92f1374dcc1b7f',
 '/data/aman_singh/acuuracy_check/.git/objects/7c/aee749042a26769df5cbc414c8938b62d6ad5d',
 '/data/aman_singh/acuuracy_check/.git/objects/c5/35b0eef72563a1d118fde560c6a39ca8c0beb0',
 '/data/aman_singh/acuuracy_check/.git/objects/cc/679c4b55a33e2aa75882245292e22bb7639c48',
 '/data/aman_singh/acuuracy_check/.git/objects/cc/09daa0220edbd7158c7204b6054ebb3c7088c4',
 '/data/aman_singh/acuuracy_check/.git/objects/9f/3277fa648fdfd4672db445020e3c61a91d5c2e',
 '/data/aman_singh/acuuracy_check/.git/objects/8a/003237fdcdf98017cdcb00c90346d0f67aa796',
 '/data/aman_singh/acuuracy_check/.git/objects/8a/5b03f7825d0c7a70f5e08a927998d56f3bc0db',
 '/data/aman_singh/acuuracy_check/.git/objects/59/d35e58650961d9b414e8fa26562fc731744b7f',
 '/data/aman_singh/acuuracy_check/.git/objects/65/1463d114cd395240ff20f6009f6f03b5ace3bd',
 '/data/aman_singh/acuuracy_check/.git/objects/a1/35dfe612725a0d928ebc77e2c66532f23bb878',
 '/data/aman_singh/acuuracy_check/.git/objects/a1/0e8af7c1a8e9929cc493d86384ff1dd941f951',
 '/data/aman_singh/acuuracy_check/.git/objects/cf/f697f7e76b7545ccc2f503bfb88421a386d52f',
 '/data/aman_singh/acuuracy_check/.git/objects/cf/1bcc0150c2e719ac2f42e3335afdad97d26760',
 '/data/aman_singh/acuuracy_check/.git/objects/74/d56b7e123d4e9027572838cb58068bc9f95381',
 '/data/aman_singh/acuuracy_check/.git/objects/74/25940c697ce87605833d0f1e48f2d2cecf71e2',
 '/data/aman_singh/acuuracy_check/.git/objects/58/8c2a75038d0e8d868a5fa981905deb9d37b88d',
 '/data/aman_singh/acuuracy_check/.git/objects/58/000a649c664f170c3456e8d25776c38dd573a8',
 '/data/aman_singh/acuuracy_check/.git/objects/ab/500e9c122b6b07a7faba567950d926ae42bec9',
 '/data/aman_singh/acuuracy_check/.git/objects/03/ac97ccf37beeb2e4f0bb9a3604daf95f216062',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/03e71337ffe7deb053d315f8265818d763b01f',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/c87c86274fecc75c3fa168a6895ebbddc28106',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/879b2b807691fd306b0f7ca73c36ea41a3bd81',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/9ca627bc444ed9ff026f3836bb3e7aa03ed233',
 '/data/aman_singh/acuuracy_check/.git/objects/2d/549acdb85049753aa94ccb54993b6fd9bd2f6f',
 '/data/aman_singh/acuuracy_check/.git/objects/3d/29272dd8a873f2f5a459f59ebbe7c739454fd0',
 '/data/aman_singh/acuuracy_check/.git/objects/bc/71c9e7c3285b1f6576fb16f74ad672a49506b2',
 '/data/aman_singh/acuuracy_check/.git/objects/bc/05416172e730f6fbed84bfefb9c58422ffdd14',
 '/data/aman_singh/acuuracy_check/.git/objects/ba/9407860c0eaf693011578a73c4d23152847ca9',
 '/data/aman_singh/acuuracy_check/.git/objects/ba/be558bddaae44a8d5b6df39f0f000aee99a007',
 '/data/aman_singh/acuuracy_check/.git/objects/dc/10868ed87ec60be4b6e47932af25202f9b4b78',
 '/data/aman_singh/acuuracy_check/.git/objects/dc/5a43e41ac4e0d522740642002b6a585b952c5c',
 '/data/aman_singh/acuuracy_check/.git/objects/dc/ea0622cae9c32ad2d43935adce7d1c8fde92d0',
 '/data/aman_singh/acuuracy_check/.git/objects/26/b7c99b5cfd7ac25b72e8f936f481ae0b6bd6a2',
 '/data/aman_singh/acuuracy_check/.git/objects/26/0ab5a96518f9923c0eb96aae2d6515e0d036cc',
 '/data/aman_singh/acuuracy_check/.git/objects/26/56dfca846fc891ec3986b5b632a53eb2732d77',
 '/data/aman_singh/acuuracy_check/.git/objects/34/897662b1f34b1b11bd5ca0fcfd8998867cf85b',
 '/data/aman_singh/acuuracy_check/.git/objects/a6/87762a97818feaf78b3aeb00795733a393cb4d',
 '/data/aman_singh/acuuracy_check/.git/objects/a6/18c7b7f99dcd9060ef73bea5f355cf672579e7',
 '/data/aman_singh/acuuracy_check/.git/objects/a6/c51ec0769f53b080c95848963307d081695743',
 '/data/aman_singh/acuuracy_check/.git/objects/6e/c0b9789218464a6415c8c38282dd3c53e9c9a9',
 '/data/aman_singh/acuuracy_check/.git/objects/db/b0fcd1689588852c38bf841cff7b7c8a70c187',
 '/data/aman_singh/acuuracy_check/.git/objects/db/4d8ac814a503cd6a276b2aa4bfbf5e3a72153f',
 '/data/aman_singh/acuuracy_check/.git/objects/db/f77a3dc81221241b2ca3c5a451dc5cce20cb6d',
 '/data/aman_singh/acuuracy_check/.git/objects/5e/cdf94c7dbf7c12e149c7ab25d074d8fa0213a5',
 '/data/aman_singh/acuuracy_check/.git/objects/5e/625ea8f4e3a0cfe9694ac548b07ab69bf334c8',
 '/data/aman_singh/acuuracy_check/.git/objects/5e/78cf8cd5d30875e80ca18219791e111aca883a',
 '/data/aman_singh/acuuracy_check/.git/objects/5e/9b31fa84c5472fb28e36589ae1b36e8be5ab35',
 '/data/aman_singh/acuuracy_check/.git/objects/c7/592fea969130dc6de154a79988d65417f7b950',
 '/data/aman_singh/acuuracy_check/.git/objects/c7/f39e254b338f07e8b78569aa4d1c036ed5d810',
 '/data/aman_singh/acuuracy_check/.git/objects/7e/53f3057d83ca0dcd187a7223f2d6b89e87b6ea',
 '/data/aman_singh/acuuracy_check/.git/objects/dd/d4441624dc878c82122b80574f0c74ccd6096a',
 '/data/aman_singh/acuuracy_check/.git/objects/00/e2a39415f46218118009c71b2d830dece524da',
 '/data/aman_singh/acuuracy_check/.git/objects/e1/9e07c0825a86cfa0f2c8b55b2c1de2559b82a3',
 '/data/aman_singh/acuuracy_check/.git/objects/e1/cf4a930735e4eb7b35761b1eab73d041077b4f',
 '/data/aman_singh/acuuracy_check/.git/objects/6a/79674bcb71fc151939660f0d642c81a103f4ac',
 '/data/aman_singh/acuuracy_check/.git/objects/0a/59283fc761cb525cba974499b0c5e60a72f8ee',
 '/data/aman_singh/acuuracy_check/.git/objects/22/3832d81d83fae975deab49cfc00c0adebac96f',
 '/data/aman_singh/acuuracy_check/.git/objects/35/f6784f6a61ff11a23fd4bd8bc741290f5d9cf8',
 '/data/aman_singh/acuuracy_check/.git/objects/56/0d3570297f244f94b745ef710fe57c6cb1aabb',
 '/data/aman_singh/acuuracy_check/.git/objects/60/c5a496cd4e43aeedd9be8bfdec3d89b97879e4',
 '/data/aman_singh/acuuracy_check/.git/objects/60/8788287124ea3873816cca96ab15cd16656caa',
 '/data/aman_singh/acuuracy_check/.git/objects/92/1be2fdc7467857475f242c6c5d966f3c3d6cc6',
 '/data/aman_singh/acuuracy_check/.git/objects/92/4330b07d6c64e769ba58c7860d7b13f060dd03',
 '/data/aman_singh/acuuracy_check/.git/objects/81/34279d63276a54230ba074d8dc7c37b00cc240',
 '/data/aman_singh/acuuracy_check/.git/objects/36/58fed41403607bff19abca6f870f8a8d293d94',
 '/data/aman_singh/acuuracy_check/.git/objects/06/83146ba4d03242c9a74e17a995675e94b5710b',
 '/data/aman_singh/acuuracy_check/.git/objects/06/410b7f4380d103a476117837882fe6393e0e70',
 '/data/aman_singh/acuuracy_check/.git/objects/95/aa0657ed2dc539bc4ef7fd0d5e66afc03954a4',
 '/data/aman_singh/acuuracy_check/.git/objects/07/a11e081942258cd19a2d57b078d670ad3dd53e',
 '/data/aman_singh/acuuracy_check/.git/objects/07/195be0481a44891f6392e954dcd86d2d645411',
 '/data/aman_singh/acuuracy_check/.git/objects/d2/52aafae8dc0a27f784215d09d97c52cd9cf30b',
 '/data/aman_singh/acuuracy_check/.git/objects/18/334af48a44fbff6c2499d2c2a4e32cb9002ab5',
 '/data/aman_singh/acuuracy_check/.git/objects/18/25558da7856fa5ab2433425b8c6b45c8c8072e',

In [237]:
def discover_channel(file_path):
    # file_path = file_path.split('/')

    # if 'ECOM' in file_path:
    #     return 'ECOM'
    # elif 'QCOM' in file_path:
    #     return 'QCOM'
    # elif 'MT' in file_path:
    #     return 'MT'
    # else:
    #     return 'Channel not found'

    return 'ECOM'

In [238]:
from maricovault.MaricoDB import MaricoSnowflake

def get_dbconnection(db_name):    

    KEY_VAULT_NAME = "prod-pwd"

    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'
    

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection


def read_qtr_ind_rate_table():
    """
    Fetch the club sku information from  DWH_SAP_INDEX_TURNOVER_MONTHWISE table.

    Return:
        qtr_ind_rate_data: pandas dataframe
        - dataframe contains all the results from the index rate table.
    """
    connection = get_dbconnection(db_name='PROD')
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=connection, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    connection.close()
    return qtr_ind_rate


dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

In [239]:
data_query = f"""
    select * from {input_table}
    where month_date >= '2023-01-31' and run_month = '{run_month}'
        
"""

offtake_df = pd.read_sql(data_query, dev_conn)
offtake_df.head()

,MONTH_DATE,KEY,PLATFORM_NAME,DEPOT,PARENT_MATERIAL_CODE,BRAND_CODE,VOL_IN_RUM,IMPUTED,RUN_MONTH
0,2024-05-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.145,0,2026-06-30
1,2024-06-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
2,2024-07-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
3,2024-08-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
4,2024-09-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30

In [240]:
offtake_df.columns = offtake_df.columns.str.lower()

In [241]:
# offtake_df = pd.read_csv('/data/aman_singh/mt_forecast/qcom_depot_psku_data.csv')
# offtake_df = offtake_df[offtake_df['month_date']<='2026-03-31']
# offtake_df

In [242]:
offtake_df.duplicated(
    subset=['platform_name','depot','parent_material_code', 'month_date']).sum()

0

In [243]:
offtake_df['brand_code'] = np.where(
    ((offtake_df['parent_material_code'] == 715096) &
    (offtake_df['brand_code'] == 'CO_SO_PCP')),
    'CO_SO_FS',
    offtake_df['brand_code']
)

In [244]:
# offtake_df = offtake_df[offtake_df['platform_name'].isin(
#     ['Amazon', 'Big Basket', 'Flipkart Grocery', 'Flipkart National'])]

In [245]:
offtake_df['key'] = offtake_df[['platform_name','depot','parent_material_code']].astype(str).agg('_'.join, axis=1)
# offtake_df.rename(columns={'realigned_psku': 'parent_material_code'}, inplace=True)
# offtake_df.drop([ 'run_month'], axis=1, inplace=True)
offtake_df['parent_material_code'] = offtake_df['parent_material_code'].astype(int)

In [246]:
offtake_df.duplicated(subset=['key', 'month_date']).sum()

0

In [247]:
(offtake_df['key'] == offtake_df[['platform_name','parent_material_code']].astype(str).agg('_'.join, axis=1)).all()

False

In [248]:
# realigned_df.to_csv('OT_data_debug.csv', index=False)

### Collate MIL

In [249]:
base_dir

'/data/aman_singh/acuuracy_check'

In [250]:
def collate_file(file_hint, extension='.csv'):
    collated_file = pd.DataFrame()

    run_path = f'{base_dir}'
    all_files = list_all_files_in_directory(run_path)

    for file_path in all_files:
        if file_hint in file_path:
            if extension == '.csv':
                print(file_path)
                read_file = pd.read_csv(file_path)
                # read_file['channel'] = discover_channel(file_path)
                read_file['run'] = 'run'
                read_file['step'] = file_path.split('/')[3]
                read_file['file_path'] = file_path

                collated_file = pd.concat(
                    [collated_file, read_file]
                )
                del read_file

    return collated_file

In [251]:
trend_file_df = collate_file('trend_file_train_till')
prophet_file_df = collate_file('prophet_data_train_till')

/data/aman_singh/acuuracy_check/trend_file_train_till_31_May_2026.csv
/data/aman_singh/acuuracy_check/prophet_data_train_till_31_May_2026.csv

In [252]:
# forecast_train_till_file_df = collate_file('forecast_train_till_')

In [253]:
# forecast_train_till_file_df

In [254]:
trend_file_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,vol_in_rum,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path
0,blinkit_D112_718288,2024-05-31,0.048333,0.024167,0.092660,0.048333,0.000671,0.000336,0.001287,0.000671,718288,D112,blinkit,0.145,SAFF GOLD,138865.260689,0.002014,NaN,NaN,0.145,0.002014,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
1,blinkit_D112_718288,2024-06-30,0.048333,0.024167,0.001315,0.019333,0.000671,0.000336,0.000018,0.000268,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
2,blinkit_D112_718288,2024-07-31,0.048333,0.024167,0.003047,0.004833,0.000671,0.000336,0.000042,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
3,blinkit_D112_718288,2024-08-31,0.048333,0.024167,0.004675,0.004833,0.000671,0.000336,0.000065,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
4,blinkit_D112_718288,2024-09-30,0.000000,0.024167,0.006517,0.004833,0.000000,0.000336,0.000090,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
259198,zepto_D677_810439,2026-07-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
259199,zepto_D677_810439,2026-08-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
259200,zepto_D677_810439,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...
259201,zepto_D677_810439,2026-10-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...

In [255]:
# prophet_file_df.to_csv('Prophet_file_OT_FK_AZ_BB_.csv', index=False)

In [256]:
trend_file_df.columns

Index(['key', 'month_date', 'pred_p3m', 'pred_p6m', 'pred_prophet', 'pred_rf',
       'pred_value_p3m', 'pred_value_p6m', 'pred_value_prophet',
       'pred_value_rf', 'parent_material_code', 'depot', 'platform_name',
       'vol_in_rum', 'brand_code', 'qtr_ind_rate', 'vol_in_rum_value',
       'pred_best_model', 'pred_value_best_model', 'vol_in_rum_treated',
       'vol_in_rum_value_treated', 'train_till', 'cov', 'run', 'step',
       'file_path'],
      dtype='object')

In [257]:
trend_file_df.dtypes

key                          object
month_date                   object
pred_p3m                    float64
pred_p6m                    float64
pred_prophet                float64
pred_rf                     float64
pred_value_p3m              float64
pred_value_p6m              float64
pred_value_prophet          float64
pred_value_rf               float64
parent_material_code          int64
depot                        object
platform_name                object
vol_in_rum                  float64
brand_code                   object
qtr_ind_rate                float64
vol_in_rum_value            float64
pred_best_model             float64
pred_value_best_model       float64
vol_in_rum_treated          float64
vol_in_rum_value_treated    float64
train_till                   object
cov                         float64
run                          object
step                         object
file_path                    object
dtype: object

In [258]:
trend_file_df['month_date'] = pd.to_datetime(trend_file_df['month_date'])
prophet_file_df['month_date'] = pd.to_datetime(prophet_file_df['month_date'])

trend_file_df['train_till'] = pd.to_datetime(trend_file_df['train_till'])
prophet_file_df['train_till'] = pd.to_datetime(prophet_file_df['train_till'])

trend_file_df['run_month'] = pd.to_datetime(trend_file_df['train_till'] + MonthEnd(1))
prophet_file_df['run_month'] = pd.to_datetime(prophet_file_df['train_till'] + MonthEnd(1))

In [259]:
trend_file_df.duplicated(subset=['key', 'month_date', 'run_month']).sum(), \
prophet_file_df.duplicated(subset=['key', 'month_date', 'run_month']).sum()

(0, 0)

In [260]:
mappings = {}

for run_month in trend_file_df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings

{Timestamp('2026-06-30 00:00:00'): {Timestamp('2026-06-30 00:00:00'): 'M',
  Timestamp('2026-07-31 00:00:00'): 'M+1',
  Timestamp('2026-08-31 00:00:00'): 'M+2',
  Timestamp('2026-09-30 00:00:00'): 'M+3',
  Timestamp('2026-10-31 00:00:00'): 'M+4',
  Timestamp('2026-11-30 00:00:00'): 'M+5',
  Timestamp('2026-12-31 00:00:00'): 'M+6',
  Timestamp('2027-01-31 00:00:00'): 'M+7',
  Timestamp('2027-02-28 00:00:00'): 'M+8'}}

In [261]:
trend_file_df['M month'] = trend_file_df.apply(
    lambda x: mappings[x['run_month']].get(
        x['month_date']
    ), axis=1
)

In [262]:
trend_file_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,vol_in_rum,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month
0,blinkit_D112_718288,2024-05-31,0.048333,0.024167,0.092660,0.048333,0.000671,0.000336,0.001287,0.000671,718288,D112,blinkit,0.145,SAFF GOLD,138865.260689,0.002014,NaN,NaN,0.145,0.002014,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None
1,blinkit_D112_718288,2024-06-30,0.048333,0.024167,0.001315,0.019333,0.000671,0.000336,0.000018,0.000268,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None
2,blinkit_D112_718288,2024-07-31,0.048333,0.024167,0.003047,0.004833,0.000671,0.000336,0.000042,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None
3,blinkit_D112_718288,2024-08-31,0.048333,0.024167,0.004675,0.004833,0.000671,0.000336,0.000065,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None
4,blinkit_D112_718288,2024-09-30,0.000000,0.024167,0.006517,0.004833,0.000000,0.000336,0.000090,0.000067,718288,D112,blinkit,0.000,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M
259198,zepto_D677_810439,2026-07-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1
259199,zepto_D677_810439,2026-08-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2
259200,zepto_D677_810439,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3
259201,zepto_D677_810439,2026-10-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,0.000,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4

In [263]:
trend_file_df[trend_file_df['M month'].notna()]

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,vol_in_rum,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month
25,blinkit_D112_718288,2026-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,D112,blinkit,0.0,SAFF GOLD,138865.260689,0.0,0.0,0.0,0.0,0.0,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M
26,blinkit_D112_718288,2026-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,D112,blinkit,0.0,SAFF GOLD,138865.260689,0.0,0.0,0.0,0.0,0.0,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1
27,blinkit_D112_718288,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,D112,blinkit,0.0,SAFF GOLD,138865.260689,0.0,0.0,0.0,0.0,0.0,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2
28,blinkit_D112_718288,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,D112,blinkit,0.0,SAFF GOLD,138865.260689,0.0,0.0,0.0,0.0,0.0,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3
29,blinkit_D112_718288,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,D112,blinkit,0.0,SAFF GOLD,138865.260689,0.0,0.0,0.0,0.0,0.0,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,zepto_D677_810439,2026-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810439,D677,zepto,0.0,SAF-MUSLI,315513.490535,0.0,0.0,0.0,0.0,0.0,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M
259198,zepto_D677_810439,2026-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810439,D677,zepto,0.0,SAF-MUSLI,315513.490535,0.0,0.0,0.0,0.0,0.0,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1
259199,zepto_D677_810439,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810439,D677,zepto,0.0,SAF-MUSLI,315513.490535,0.0,0.0,0.0,0.0,0.0,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2
259200,zepto_D677_810439,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810439,D677,zepto,0.0,SAF-MUSLI,315513.490535,0.0,0.0,0.0,0.0,0.0,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3
259201,zepto_D677_810439,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810439,D677,zepto,0.0,SAF-MUSLI,315513.490535,0.0,0.0,0.0,0.0,0.0,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4

In [264]:
trend_file_df[['run_month', 'train_till']].drop_duplicates().sort_values(by=['run_month'])

   run_month train_till
0 2026-06-30 2026-05-31

In [265]:
prophet_file_df[['run_month', 'train_till']].drop_duplicates().sort_values(by=['run_month'])

   run_month train_till
0 2026-06-30 2026-05-31

In [266]:
trend_file_df['M month'].unique()

array([None, 'M', 'M+1', 'M+2', 'M+3', 'M+4'], dtype=object)

In [267]:
brand_md_df = pd.read_excel(r"/data/aman_singh/mt_forecast/Brand_metadata.xlsx")

In [268]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    brand_md_df,
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(trend_file_df)

In [269]:
trend_file_df['portfolio'].isna().sum()

0

In [270]:
prophet_file_df[
    ['month_date', 'key', 'run_month']
].duplicated().sum()

0

In [271]:
prophet_file_df

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,yhat_60_%ile,yhat_70_%ile,yhat_75_%ile,trend_60_%ile,trend_70_%ile,trend_75_%ile,additive_terms,additive_terms_lower,additive_terms_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat,key,y,month_date,brand_code,qtr_ind_rate,vol_in_rum,vol_in_rum_value,yhat_value,Model_Run,Model_Type,type,train_till,run,step,file_path,run_month
0,2024-05-31,0.011367,0.073492,0.110628,0.011367,0.011367,0.096379,0.100956,0.102720,0.011367,0.011367,0.011367,0.081293,0.081293,0.081293,0.081293,0.081293,0.081293,0.0,0.0,0.0,0.092660,blinkit_D112_718288,0.145,2024-05-31,SAFF GOLD,138865.260689,0.145,0.002014,0.001287,Yes,prophet,training,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
1,2024-06-30,0.010298,-0.018289,0.021391,0.010298,0.010298,0.005674,0.009374,0.011834,0.010298,0.010298,0.010298,-0.008983,-0.008983,-0.008983,-0.008983,-0.008983,-0.008983,0.0,0.0,0.0,0.001315,blinkit_D112_718288,0.000,2024-06-30,SAFF GOLD,138865.260689,0.000,0.000000,0.000018,Yes,prophet,training,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
2,2024-07-31,0.009193,-0.015699,0.023804,0.009193,0.009193,0.007322,0.011299,0.013888,0.009193,0.009193,0.009193,-0.006147,-0.006147,-0.006147,-0.006147,-0.006147,-0.006147,0.0,0.0,0.0,0.003047,blinkit_D112_718288,0.000,2024-07-31,SAFF GOLD,138865.260689,0.000,0.000000,0.000042,Yes,prophet,training,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
3,2024-08-31,0.008089,-0.014741,0.024127,0.008089,0.008089,0.008798,0.012763,0.014733,0.008089,0.008089,0.008089,-0.003414,-0.003414,-0.003414,-0.003414,-0.003414,-0.003414,0.0,0.0,0.0,0.004675,blinkit_D112_718288,0.000,2024-08-31,SAFF GOLD,138865.260689,0.000,0.000000,0.000065,Yes,prophet,training,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
4,2024-09-30,0.007020,-0.013603,0.026860,0.007020,0.007020,0.010185,0.014201,0.016709,0.007020,0.007020,0.007020,-0.000503,-0.000503,-0.000503,-0.000503,-0.000503,-0.000503,0.0,0.0,0.0,0.006517,blinkit_D112_718288,0.000,2024-09-30,SAFF GOLD,138865.260689,0.000,0.000000,0.000090,Yes,prophet,training,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,2026-06-30,-0.000411,-0.000603,-0.000603,-0.000411,-0.000411,-0.000603,-0.000603,-0.000603,-0.000411,-0.000411,-0.000411,-0.000192,-0.000192,-0.000192,-0.000192,-0.000192,-0.000192,0.0,0.0,0.0,0.000000,zepto_D677_810439,0.000,2026-06-30,SAF-MUSLI,315513.490535,0.000,0.000000,0.000000,Yes,prophet,testing,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
259198,2026-07-31,-0.000469,-0.000693,-0.000693,-0.000470,-0.000469,-0.000693,-0.000693,-0.000693,-0.000469,-0.000469,-0.000469,-0.000224,-0.000224,-0.000224,-0.000224,-0.000224,-0.000224,0.0,0.0,0.0,0.000000,zepto_D677_810439,0.000,2026-07-31,SAF-MUSLI,315513.490535,0.000,0.000000,0.000000,Yes,prophet,testing,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
259199,2026-08-31,-0.000528,-0.000559,-0.000557,-0.000528,-0.000527,-0.000558,-0.000558,-0.000558,-0.000528,-0.000527,-0.000527,-0.000031,-0.000031,-0.000031,-0.000031,-0.000031,-0.000031,0.0,0.0,0.0,0.000000,zepto_D677_810439,0.000,2026-08-31,SAF-MUSLI,315513.490535,0.000,0.000000,0.000000,Yes,prophet,testing,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
259200,2026-09-30,-0.000584,-0.000953,-0.000950,-0.000586,-0.000583,-0.000951,-0.000951,-0.000951,-0.000584,-0.000584,-0.000584,-0.000367,-0.000367,-0.000367,-0.000367,-0.000367,-0.000367,0.0,0.0,0.0,0.000000,zepto_D677_810439,0.000,2026-09-30,SAF-MUSLI,315513.490535,0.000,0.000000,0.000000,Yes,prophet,testing,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30
259201,2026-10-31,-0.000642,-0.000700,-0.000696,-0.000645,-0.000641,-0.000698,-0.000697,-0.000697,-0.000642,-0.000642,-0.000642,-0.000055,-0.000055,-0.000055,-0.000055,-0.000055,-0.000055,0.0,0.0,0.0,0.000000,zepto_D677_810439,0.000,2026-10-31,SAF-MUSLI,315513.490535,0.000,0.000000,0.000000,Yes,prophet,testing,2026-05-31,run,acuuracy_check,/data/aman_singh/acuuracy_check/prophet_data_t...,2026-06-30

In [272]:
# Merge 70th percentile Prophet predictions
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    prophet_file_df[['month_date', 'key', 'run_month', 'yhat_70_%ile', 'yhat_60_%ile']].rename(
        columns={
            'yhat_70_%ile': 'pred_prophet_70%ile',
            'yhat_60_%ile': 'pred_prophet_60%ile'
        }
    ),
    on=['month_date', 'key', 'run_month'],
    how='left'
)
assert len(trend_file_df) == len_before_merge

In [273]:
assert trend_file_df.duplicated(
    subset=['run_month', 'month_date', 'key']
).sum() == 0

In [274]:
trend_file_df.drop('vol_in_rum', axis=1, inplace=True)

In [275]:
offtake_df.head()

,month_date,key,platform_name,depot,parent_material_code,brand_code,vol_in_rum,imputed,run_month
0,2024-05-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.145,0,2026-06-30
1,2024-06-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
2,2024-07-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
3,2024-08-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
4,2024-09-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30

In [276]:
assert offtake_df.duplicated(subset=['key', 'month_date']).sum() == 0

In [277]:
offtake_df['month_date'] = pd.to_datetime(offtake_df['month_date'])
# offtake_df['run_month'] = pd.to_datetime(offtake_df['run_month'])

In [278]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    offtake_df[['key','month_date', 'vol_in_rum']],
    on=['month_date', 'key'],
    how='left'
)
assert len(trend_file_df) == len_before_merge

In [279]:
trend_file_df.select_dtypes('number').isna().sum()

pred_p3m                         0
pred_p6m                         0
pred_prophet                     0
pred_rf                          0
pred_value_p3m                   0
pred_value_p6m                   0
pred_value_prophet               0
pred_value_rf                    0
parent_material_code             0
qtr_ind_rate                     0
vol_in_rum_value                 0
pred_best_model             219037
pred_value_best_model       219037
vol_in_rum_treated               0
vol_in_rum_value_treated         0
cov                              0
pred_prophet_70%ile              0
pred_prophet_60%ile              0
vol_in_rum                       0
dtype: int64

In [280]:
trend_file_df.select_dtypes('number').min().round()

pred_p3m                         0.0
pred_p6m                         0.0
pred_prophet                     0.0
pred_rf                          0.0
pred_value_p3m                   0.0
pred_value_p6m                   0.0
pred_value_prophet               0.0
pred_value_rf                    0.0
parent_material_code        715101.0
qtr_ind_rate                   100.0
vol_in_rum_value                 0.0
pred_best_model                  0.0
pred_value_best_model            0.0
vol_in_rum_treated               0.0
vol_in_rum_value_treated         0.0
cov                              0.0
pred_prophet_70%ile           -359.0
pred_prophet_60%ile           -366.0
vol_in_rum                       0.0
dtype: float64

In [281]:
trend_file_df['vol_in_rum'].fillna(0, inplace=True)

In [282]:
for col in [ 'pred_best_model', 'pred_value_best_model', 'pred_prophet_70%ile','pred_prophet_60%ile', 'vol_in_rum']:
    trend_file_df[col] = trend_file_df[col].clip(lower=0)

In [283]:
trend_file_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum
0,blinkit_D112_718288,2024-05-31,0.048333,0.024167,0.092660,0.048333,0.000671,0.000336,0.001287,0.000671,718288,D112,blinkit,SAFF GOLD,138865.260689,0.002014,NaN,NaN,0.145,0.002014,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.100956,0.096379,0.145
1,blinkit_D112_718288,2024-06-30,0.048333,0.024167,0.001315,0.019333,0.000671,0.000336,0.000018,0.000268,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.009374,0.005674,0.000
2,blinkit_D112_718288,2024-07-31,0.048333,0.024167,0.003047,0.004833,0.000671,0.000336,0.000042,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.011299,0.007322,0.000
3,blinkit_D112_718288,2024-08-31,0.048333,0.024167,0.004675,0.004833,0.000671,0.000336,0.000065,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.012763,0.008798,0.000
4,blinkit_D112_718288,2024-09-30,0.000000,0.024167,0.006517,0.004833,0.000000,0.000336,0.000090,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,NaN,NaN,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.014201,0.010185,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Foods,0.000000,0.000000,0.000
259198,zepto_D677_810439,2026-07-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Foods,0.000000,0.000000,0.000
259199,zepto_D677_810439,2026-08-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Foods,0.000000,0.000000,0.000
259200,zepto_D677_810439,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Foods,0.000000,0.000000,0.000
259201,zepto_D677_810439,2026-10-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Foods,0.000000,0.000000,0.000

In [284]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)

In [285]:
trend_file_df['P3M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=3, min_periods=3).mean()

trend_file_df['P6M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=6, min_periods=6).mean()

trend_file_df['LY P3M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=3, min_periods=3).mean()

trend_file_df['LY P6M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=6, min_periods=6).mean()

In [286]:
trend_file_df['LY P3M_copy'] = trend_file_df['LY P3M'].copy()

In [287]:
trend_file_df['P3M Max'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).max()

In [288]:
trend_file_df['P3M Top 2 Mean'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sort(x)[-2:].mean(), raw=True) 

# lambda x: x.nlargest(2).mean(), raw=False

In [289]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)

In [290]:
trend_file_df['MoM P3M growth'] = (
    trend_file_df.groupby(['run_month', 'key'])['P3M']
      .pct_change() * 100
)

In [291]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
trend_file_df['MoM P3M growth_lag_1'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(1)
trend_file_df['MoM P3M growth_lag_2'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(2)

In [292]:
trend_file_df['>=20%_3M_inc_month_count'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['MoM P3M growth'].shift(0)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sum(x >= 20), raw=True)

In [293]:
trend_file_df['Avg(P3M Mean, Max)'] = trend_file_df[['P3M', 'P3M Max']].mean(axis=1)

In [294]:
for col in ['P3M', 'P6M', 'LY P3M', 'P3M Max', 'P3M Top 2 Mean', 
            'MoM P3M growth', '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)',
            'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2' ]:
    # if not 'LY' in col:  'LY P6M',
    trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
    trend_file_df[col] = trend_file_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )


# for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
#     if not 'LY' in col:
#         trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
#         trend_file_df[col] = trend_file_df.groupby(['key'], as_index = True, group_keys = False)[col].apply(
#             lambda x: x.ffill()
#         )

In [295]:
# trend_file_df.to_csv('collate_check.csv', index=False)

In [296]:
for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
    trend_file_df[f'{col}_value'] = trend_file_df[col] * trend_file_df['qtr_ind_rate'] / (10 ** 7)

In [297]:
trend_file_df['vol_in_rum_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['vol_in_rum'] / (10 ** 7)
trend_file_df['pred_prophet_70%ile_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['pred_prophet_70%ile'] / (10 ** 7)
trend_file_df['pred_prophet_60%ile_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['pred_prophet_60%ile'] / (10 ** 7)

In [298]:
value_cols = [col for col in trend_file_df.columns if 'value' in col]
value_cols

['pred_value_p3m',
 'pred_value_p6m',
 'pred_value_prophet',
 'pred_value_rf',
 'vol_in_rum_value',
 'pred_value_best_model',
 'vol_in_rum_value_treated',
 'P3M_value',
 'P6M_value',
 'LY P3M_value',
 'LY P6M_value',
 'pred_prophet_70%ile_value',
 'pred_prophet_60%ile_value']

In [299]:
for col in value_cols:
    try:
        assert trend_file_df[col].min() >= 0
    except:
        print(col)
    

    # trend_file_df[col] = trend_file_df[col] / (10 ** 7)

In [300]:
trend_file_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value
1406,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,NaN,NaN,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000024,1.618828e-05
1407,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00
1408,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000006,1.131882e-07
1409,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.000025,NaN,NaN,NaN,0.000026,2.037054e-05
1410,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.000029,2.138962e-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165175,swiggy_D530_719192,2026-06-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00
165176,swiggy_D530_719192,2026-07-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00
165177,swiggy_D530_719192,2026-08-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00
165178,swiggy_D530_719192,2026-09-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00
165179,swiggy_D530_719192,2026-10-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00

In [301]:
assert trend_file_df.duplicated(
    subset=['run_month', 'brand_code', 'key', 'month_date']
).sum() == 0

In [302]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
trend_file_df['LY'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(12)

trend_file_df['LLY'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(24)


trend_file_df['LY value'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(12)

trend_file_df['LLY value'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(24)


trend_file_df['OT_Value_in_Cr_lag_1'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(1)

trend_file_df['OT_Value_in_Cr_lag_2'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(2)

trend_file_df['OT_Value_in_Cr_lag_3'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(3)

In [303]:
for col in ['OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2', 'OT_Value_in_Cr_lag_3']:
    # if not 'LY' in col:  'LY P6M',
    trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
    trend_file_df[col] = trend_file_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

In [304]:
trend_file_df.columns

Index(['key', 'month_date', 'pred_p3m', 'pred_p6m', 'pred_prophet', 'pred_rf',
       'pred_value_p3m', 'pred_value_p6m', 'pred_value_prophet',
       'pred_value_rf', 'parent_material_code', 'depot', 'platform_name',
       'brand_code', 'qtr_ind_rate', 'vol_in_rum_value', 'pred_best_model',
       'pred_value_best_model', 'vol_in_rum_treated',
       'vol_in_rum_value_treated', 'train_till', 'cov', 'run', 'step',
       'file_path', 'run_month', 'M month', 'portfolio', 'pred_prophet_70%ile',
       'pred_prophet_60%ile', 'vol_in_rum', 'P3M', 'P6M', 'LY P3M', 'LY P6M',
       'LY P3M_copy', 'P3M Max', 'P3M Top 2 Mean', 'MoM P3M growth',
       'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2',
       '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)', 'P3M_value',
       'P6M_value', 'LY P3M_value', 'LY P6M_value',
       'pred_prophet_70%ile_value', 'pred_prophet_60%ile_value', 'LY', 'LLY',
       'LY value', 'LLY value', 'OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2',
       'OT_Value_in_Cr_lag_3'],
      dtype='object')

In [305]:
# trend_file_df[['ASM', 'Depot', 'PSKU']] = trend_file_df['key'].str.split('_', expand=True)

In [306]:
trend_file_df.reset_index(drop=True, inplace=True)

In [307]:
trend_file_df.shape

(259202, 56)

In [308]:
trend_file_df['key'].nunique()

8033

In [309]:
# batch_info = pd.read_excel(
#     '/data/aniket/az_demand_forecasting-mil-sc/channel_wise_batch.xlsx'
# )

In [310]:
brand_class = pd.read_excel('/data/aman_singh/acuuracy_check/brand_class_new.xlsx')
brand_class['Channel'] = brand_class['Channel'].replace({
    'E-Commerce': 'ECOM', 'Q-Commerce': 'QCOM'})
brand_class.columns = brand_class.columns.str.lower()
brand_class = brand_class[brand_class['channel'] == 'QCOM']
brand_class = brand_class[['brand','final class']]

brand_class.rename(columns = {'brand':'brand_code','final class':'class'}, inplace = True)

In [311]:
# trend_file_df.drop(columns = ['final class'], inplace = True)

In [312]:
brand_class

    brand_code class
845  SAFF GOLD     A
846    PCNO(R)     A
847  SAFF ACTV     A
848  SFOATS-FL     A
849  SAFF OATS     A
..         ...   ...
991  PADV-HRAD     C
992  PADVJAS-F     C
993  SFFT_VNGR     C
994  PURSNS_GM     C
995  SF_IM_CHY     C

[151 rows x 2 columns]

In [313]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    brand_class, 
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(trend_file_df)
del len_before_merge

In [314]:
trend_file_df['class'].isna().sum()

1181

In [315]:
trend_file_df['class'].unique()

array(['C', 'NPD', nan, 'A', 'B'], dtype=object)

In [316]:
trend_file_df['run_month'].unique()

<DatetimeArray>
['2026-06-30 00:00:00']
Length: 1, dtype: datetime64[ns]

In [317]:
# trend_file_df[
#     # (trend_file_df['channel'].isin(['MT', 'QCOM'])) & 
#     # (trend_file_df['month_date'] > '2024-06-30') &
#     (trend_file_df['M month'].notna())
#     # (trend_file_df['class'].isin(['B', 'C']))
# ].to_csv('Heuristic_QCOM_Chain_PSKU_Offtakes_live2.csv', index=False)

missing combinations

In [318]:
model_file = trend_file_df.copy()

In [319]:
model_file['key'].nunique()

8033

In [320]:
run_month

Timestamp('2026-06-30 00:00:00')

In [321]:
data_query = f"""select * from {input_table} where month_date >= '2023-01-31' and run_month = '2026-06-30' """
qcom_df = pd.read_sql(data_query, dev_conn)
qcom_df.head()

,MONTH_DATE,KEY,PLATFORM_NAME,DEPOT,PARENT_MATERIAL_CODE,BRAND_CODE,VOL_IN_RUM,IMPUTED,RUN_MONTH
0,2024-05-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.145,0,2026-06-30
1,2024-06-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
2,2024-07-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
3,2024-08-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
4,2024-09-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30

In [322]:
qcom_df.columns = qcom_df.columns.str.lower()

In [323]:
qcom_df['key'] = qcom_df[['platform_name', 'depot','parent_material_code']].astype(str).agg('_'.join, axis=1)

In [324]:
qcom_df

,month_date,key,platform_name,depot,parent_material_code,brand_code,vol_in_rum,imputed,run_month
0,2024-05-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.145,0,2026-06-30
1,2024-06-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
2,2024-07-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
3,2024-08-31,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
4,2024-09-30,blinkit_D112_718288,blinkit,D112,718288,SAFF GOLD,0.000,1,2026-06-30
...,...,...,...,...,...,...,...,...,...
350377,2026-11-30,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.000,1,2026-06-30
350378,2026-12-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.000,1,2026-06-30
350379,2027-01-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.000,1,2026-06-30
350380,2027-02-28,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.000,1,2026-06-30
350381,2027-03-31,zepto_D677_810439,zepto,D677,810439,SAF-MUSLI,0.000,1,2026-06-30

In [325]:
model_file['run_month'] = pd.to_datetime(model_file['run_month'])
model_file['month_date'] = pd.to_datetime(model_file['month_date'])

qcom_df['run_month'] = pd.to_datetime(qcom_df['run_month'])
qcom_df['month_date'] = pd.to_datetime(qcom_df['month_date'])

In [326]:
qcom_df.shape

(350382, 9)

In [327]:
tmp_df = model_file.groupby(['key', 'run_month'])['LY'].count().reset_index()
tmp_df#.isnull().sum()
#qcom_df[~qcom_df['key'].isin(model_file['key'].unique())]
qcom_df = qcom_df.merge(tmp_df, on = ['key','run_month'], how = 'left')
missing_df = qcom_df[qcom_df['LY'].isna()]
missing_df

,month_date,key,platform_name,depot,parent_material_code,brand_code,vol_in_rum,imputed,run_month,LY
1611,2025-10-31,blinkit_D112_718592,blinkit,D112,718592,SFOATS-FL,0.0055,0,2026-06-30,NaN
1612,2025-11-30,blinkit_D112_718592,blinkit,D112,718592,SFOATS-FL,0.0185,0,2026-06-30,NaN
1613,2025-12-31,blinkit_D112_718592,blinkit,D112,718592,SFOATS-FL,0.0250,0,2026-06-30,NaN
1614,2026-01-31,blinkit_D112_718592,blinkit,D112,718592,SFOATS-FL,0.0290,0,2026-06-30,NaN
1615,2026-02-28,blinkit_D112_718592,blinkit,D112,718592,SFOATS-FL,0.0275,0,2026-06-30,NaN
...,...,...,...,...,...,...,...,...,...,...
347304,2026-11-30,zepto_D676_810439,zepto,D676,810439,SAF-MUSLI,0.0000,1,2026-06-30,NaN
347305,2026-12-31,zepto_D676_810439,zepto,D676,810439,SAF-MUSLI,0.0000,1,2026-06-30,NaN
347306,2027-01-31,zepto_D676_810439,zepto,D676,810439,SAF-MUSLI,0.0000,1,2026-06-30,NaN
347307,2027-02-28,zepto_D676_810439,zepto,D676,810439,SAF-MUSLI,0.0000,1,2026-06-30,NaN
347308,2027-03-31,zepto_D676_810439,zepto,D676,810439,SAF-MUSLI,0.0000,1,2026-06-30,NaN

In [328]:
missing_df['key'].nunique()

2958

In [329]:
trend_file_df['key'].nunique()

8033

In [330]:
missing_df.isnull().sum()

month_date                  0
key                         0
platform_name               0
depot                       0
parent_material_code        0
brand_code                  0
vol_in_rum                  0
imputed                     0
run_month                   0
LY                      51015
dtype: int64

In [331]:
missing_df['key'].nunique()

2958

In [332]:

missing_df = missing_df[['key','run_month','month_date', 'platform_name', 'depot','parent_material_code', 'brand_code',
       'vol_in_rum']]
missing_df

,key,run_month,month_date,platform_name,depot,parent_material_code,brand_code,vol_in_rum
1611,blinkit_D112_718592,2026-06-30,2025-10-31,blinkit,D112,718592,SFOATS-FL,0.0055
1612,blinkit_D112_718592,2026-06-30,2025-11-30,blinkit,D112,718592,SFOATS-FL,0.0185
1613,blinkit_D112_718592,2026-06-30,2025-12-31,blinkit,D112,718592,SFOATS-FL,0.0250
1614,blinkit_D112_718592,2026-06-30,2026-01-31,blinkit,D112,718592,SFOATS-FL,0.0290
1615,blinkit_D112_718592,2026-06-30,2026-02-28,blinkit,D112,718592,SFOATS-FL,0.0275
...,...,...,...,...,...,...,...,...
347304,zepto_D676_810439,2026-06-30,2026-11-30,zepto,D676,810439,SAF-MUSLI,0.0000
347305,zepto_D676_810439,2026-06-30,2026-12-31,zepto,D676,810439,SAF-MUSLI,0.0000
347306,zepto_D676_810439,2026-06-30,2027-01-31,zepto,D676,810439,SAF-MUSLI,0.0000
347307,zepto_D676_810439,2026-06-30,2027-02-28,zepto,D676,810439,SAF-MUSLI,0.0000
347308,zepto_D676_810439,2026-06-30,2027-03-31,zepto,D676,810439,SAF-MUSLI,0.0000

In [333]:
qtr_df = read_qtr_ind_rate_table()
qtr_df.columns = qtr_df.columns.str.lower()
qtr_df.head()

Credentials retrieved successfully for prod db.

  month_date brand_code  qtr_ind_rate
0 2027-03-31  TRU_PDRFR     850.57000
1 2027-03-31   TRU_OATS     177.07000
2 2027-03-31  TRU_QUINO     204.75000
3 2027-03-31    TRU_RAW     453.44000
4 2027-03-31  NHR_NHO_E     266.57953

In [334]:
len_before_merge = len(missing_df)

missing_df = missing_df.rename(columns={'material_group_code': 'brand_code'}).merge(
    qtr_df.drop('month_date', axis=1),
    on=['brand_code'],
    how='left'
)

assert len_before_merge == len(missing_df)

In [335]:
missing_df

,key,run_month,month_date,platform_name,depot,parent_material_code,brand_code,vol_in_rum,qtr_ind_rate
0,blinkit_D112_718592,2026-06-30,2025-10-31,blinkit,D112,718592,SFOATS-FL,0.0055,292663.137458
1,blinkit_D112_718592,2026-06-30,2025-11-30,blinkit,D112,718592,SFOATS-FL,0.0185,292663.137458
2,blinkit_D112_718592,2026-06-30,2025-12-31,blinkit,D112,718592,SFOATS-FL,0.0250,292663.137458
3,blinkit_D112_718592,2026-06-30,2026-01-31,blinkit,D112,718592,SFOATS-FL,0.0290,292663.137458
4,blinkit_D112_718592,2026-06-30,2026-02-28,blinkit,D112,718592,SFOATS-FL,0.0275,292663.137458
...,...,...,...,...,...,...,...,...,...
51010,zepto_D676_810439,2026-06-30,2026-11-30,zepto,D676,810439,SAF-MUSLI,0.0000,315513.490535
51011,zepto_D676_810439,2026-06-30,2026-12-31,zepto,D676,810439,SAF-MUSLI,0.0000,315513.490535
51012,zepto_D676_810439,2026-06-30,2027-01-31,zepto,D676,810439,SAF-MUSLI,0.0000,315513.490535
51013,zepto_D676_810439,2026-06-30,2027-02-28,zepto,D676,810439,SAF-MUSLI,0.0000,315513.490535
51014,zepto_D676_810439,2026-06-30,2027-03-31,zepto,D676,810439,SAF-MUSLI,0.0000,315513.490535

In [336]:
missing_df['month_date'] = pd.to_datetime(missing_df['month_date'])
missing_df['run_month'] = pd.to_datetime(missing_df['run_month'])


mappings = {}

for run_month in missing_df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings   
missing_df['M month'] = missing_df.apply(
    lambda x: mappings[x['run_month']].get(
        x['month_date']
    ), axis=1
)

brand_md_df = pd.read_excel(r"/data/aman_singh/mt_forecast/Brand_metadata.xlsx")
len_before_merge = len(missing_df)
missing_df = missing_df.merge(
    brand_md_df,
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(missing_df)

# Merge 70th percentile Prophet predictions

assert missing_df.duplicated(
    subset=['run_month', 'month_date', 'key']
).sum() == 0
missing_df.drop('vol_in_rum', axis=1, inplace=True)

In [337]:

offtake_df['month_date'] = pd.to_datetime(offtake_df['month_date'])
assert offtake_df.duplicated(subset=['key', 'month_date']).sum() == 0
len_before_merge = len(missing_df)
missing_df = missing_df.merge(
    offtake_df[['key', 'month_date', 'vol_in_rum']],
    on=['month_date', 'key'],
    how='left'
)
assert len(missing_df) == len_before_merge

missing_df['vol_in_rum'].fillna(0, inplace=True)
for col in [ 'vol_in_rum']:
    missing_df[col] = missing_df[col].clip(lower=0)
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['P3M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=3, min_periods=1).mean()

missing_df['P6M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=6, min_periods=6).mean()

missing_df['LY P3M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=3, min_periods=3).mean()

missing_df['LY P6M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=6, min_periods=6).mean()
missing_df['LY P3M_copy'] = missing_df['LY P3M'].copy()
missing_df['P3M Max'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).max()
missing_df['P3M Top 2 Mean'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sort(x)[-2:].mean(), raw=True) 

# lambda x: x.nlargest(2).mean(), raw=False
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['MoM P3M growth'] = (
    missing_df.groupby(['run_month', 'key'])['P3M']
      .pct_change() * 100
)
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['MoM P3M growth_lag_1'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(1)
missing_df['MoM P3M growth_lag_2'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(2)


missing_df['>=20%_3M_inc_month_count'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['MoM P3M growth'].shift(0)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sum(x >= 20), raw=True) 
missing_df['Avg(P3M Mean, Max)'] = missing_df[['P3M', 'P3M Max']].mean(axis=1)
for col in ['P3M', 'P6M', 'LY P3M', 'P3M Max', 'P3M Top 2 Mean', 
            'MoM P3M growth', '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)',
            'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2' ]:
    # if not 'LY' in col:  'LY P6M',
    missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
    missing_df[col] = missing_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )


# for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
#     if not 'LY' in col:
#         missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
#         missing_df[col] = missing_df.groupby(['key'], as_index = True, group_keys = False)[col].apply(
#             lambda x: x.ffill()
#         )
# missing_df.to_csv('collate_check.csv', index=False)
for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
    missing_df[f'{col}_value'] = missing_df[col] * missing_df['qtr_ind_rate'] / (10 ** 7)
missing_df['vol_in_rum_value'] = missing_df['qtr_ind_rate'] * missing_df['vol_in_rum'] / (10 ** 7)
value_cols = [col for col in missing_df.columns if 'value' in col]
value_cols
for col in value_cols:
    try:
        assert missing_df[col].min() >= 0
    except:
        print(col)
    

    # missing_df[col] = missing_df[col] / (10 ** 7)
missing_df
assert missing_df.duplicated(
    subset=['run_month', 'brand_code', 'key', 'month_date']
).sum() == 0
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['LY'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(12)

missing_df['LLY'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(24)


missing_df['LY value'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(12)

missing_df['LLY value'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(24)


missing_df['OT_Value_in_Cr_lag_1'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(1)

missing_df['OT_Value_in_Cr_lag_2'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(2)

missing_df['OT_Value_in_Cr_lag_3'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(3)
for col in ['OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2', 'OT_Value_in_Cr_lag_3']:
    # if not 'LY' in col:  'LY P6M',
    missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
    missing_df[col] = missing_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

missing_df.reset_index(drop=True, inplace=True)

# brand_class_df = pd.read_excel(r"/data/aman_singh/acuuracy_check/Brand_Classification.xlsb")
# brand_class_df.head()
# brand_class_df.columns = ['brand_code', 'class']

len_before_merge = len(missing_df)
missing_df = missing_df.merge(
    brand_class, 
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(missing_df)
del len_before_merge
missing_df['class'].isna().sum()
missing_df['class'].unique()

LY P3M_value

array(['C', 'NPD', 'A', 'B'], dtype=object)

In [338]:
pd.set_option('display.max_columns', None)

In [339]:
# missing_df[
#     # (missing_df['channel'].isin(['MT', 'QCOM'])) & 
#     # (missing_df['month_date'] > '2024-06-30') &
#     (missing_df['M month'].notna())
#     # (missing_df['class'].isin(['B', 'C']))
# ].to_csv('missing_combinations_QCOM_Chain_city_PSKU_Offtakes.csv', index=False)

In [340]:
model_file

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,NaN,NaN,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000024,1.618828e-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,0.000075,NaN,NaN,C
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000006,1.131882e-07,NaN,NaN,NaN,NaN,0.000000,0.000075,NaN,C
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,0.000025,NaN,NaN,NaN,0.000026,2.037054e-05,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000075,C
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.000029,2.138962e-05,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,swiggy_D530_719192,2026-06-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
259198,swiggy_D530_719192,2026-07-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
259199,swiggy_D530_719192,2026-08-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
259200,swiggy_D530_719192,2026-09-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
259201,swiggy_D530_719192,2026-10-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,719192,D530,swiggy,VEG_CLEAN,100.000000,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,6.164414,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Health & Hygiene,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,NaN,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN

In [341]:
model_file['skipped'] = 0
missing_df['skipped'] = 1
final_df = pd.concat([model_file,missing_df])
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,NaN,NaN,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000024,1.618828e-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,0
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000e+00,NaN,NaN,NaN,NaN,0.000075,NaN,NaN,C,0
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000006,1.131882e-07,NaN,NaN,NaN,NaN,0.000000,0.000075,NaN,C,0
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.000025,NaN,NaN,NaN,0.000026,2.037054e-05,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000075,C,0
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,NaN,NaN,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,-100.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,0.000029,2.138962e-05,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51010,zepto_D673_810125,2026-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,NaN,NaN,0.0,0.906667,NaN,NaN,NaN,NaN,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000178,0.000260,0.000027,NPD,1
51011,zepto_D673_810125,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,NaN,NaN,0.0,0.906667,NaN,NaN,NaN,NaN,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000178,0.000260,0.000027,NPD,1
51012,zepto_D673_810125,2027-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,NaN,NaN,0.0,0.906667,NaN,NaN,NaN,NaN,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000178,0.000260,0.000027,NPD,1
51013,zepto_D673_810125,2027-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,NaN,NaN,0.0,0.906667,NaN,NaN,NaN,NaN,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,NaN,NaN,NaN,NaN,NaN,0.56,NaN,0.000096,NaN,0.000178,0.000260,0.000027,NPD,1
51014,zepto_D673_810125,2027-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,2026-06-30,None,Male Grooming,NaN,NaN,0.0,0.906667,NaN,NaN,NaN,NaN,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,NaN,NaN,NaN,NaN,NaN,0.16,NaN,0.000027,NaN,0.000178,0.000260,0.000027,NPD,1

In [342]:
# final_df = trend_file_df.copy()

In [343]:
final_df[final_df.select_dtypes(include='number').columns] = final_df.select_dtypes(include='number').fillna(0)
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,0.0,0.0,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000024,1.618828e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000075,0.000000,0.000000,C,0
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000006,1.131882e-07,0.00,0.0,0.000000,0.0,0.000000,0.000075,0.000000,C,0
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.500000,0.000025,0.0,0.0,0.0,0.000026,2.037054e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000075,C,0
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-100.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000029,2.138962e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51010,zepto_D673_810125,2026-11-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51011,zepto_D673_810125,2026-12-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51012,zepto_D673_810125,2027-01-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51013,zepto_D673_810125,2027-02-28,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.56,0.0,0.000096,0.0,0.000178,0.000260,0.000027,NPD,1
51014,zepto_D673_810125,2027-03-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,None,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.16,0.0,0.000027,0.0,0.000178,0.000260,0.000027,NPD,1

In [344]:
final_df['month_date'] = pd.to_datetime(final_df['month_date'])
final_df['run_month'] = pd.to_datetime(final_df['run_month'])
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,0.0,0.0,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000024,1.618828e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000075,0.000000,0.000000,C,0
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000006,1.131882e-07,0.00,0.0,0.000000,0.0,0.000000,0.000075,0.000000,C,0
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.500000,0.000025,0.0,0.0,0.0,0.000026,2.037054e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000075,C,0
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-100.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000029,2.138962e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51010,zepto_D673_810125,2026-11-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51011,zepto_D673_810125,2026-12-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51012,zepto_D673_810125,2027-01-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51013,zepto_D673_810125,2027-02-28,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.56,0.0,0.000096,0.0,0.000178,0.000260,0.000027,NPD,1
51014,zepto_D673_810125,2027-03-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,None,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.16,0.0,0.000027,0.0,0.000178,0.000260,0.000027,NPD,1

In [345]:
# final_df[
#     # (final_df['channel'].isin(['MT', 'QCOM'])) & 
#     # (final_df['month_date'] > '2024-06-30') &
#     (final_df['M month'].notna())
#     # (missing_df['class'].isin(['B', 'C']))
# ].to_csv('all_combinations_QCOM_chain_PSKU_Offtakes_DEC2.csv', index=False)

In [346]:
# final_df.to_csv('heuristic_data_preprocessed_qcom_jan.csv')

In [347]:
# import pandas as pd
# final_df = pd.read_csv('/data/aman_singh/acuuracy_check/heuristic_data_preprocessed_qcom_cp_live_jan.csv')
# final_df

In [348]:
final_df[(final_df['M month'].notna())]#['key'].nunique()

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped
25,blinkit_D112_718589,2026-06-30,2.1,2.1,2.605122,1.831482,0.000104,0.000104,0.000129,0.000091,718589,D112,blinkit,ADV-AHO-R,496.828458,0.0,2.605122,0.000129,0.0,0.0,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Hair Oils,2.842577,2.725673,0.0,2.100000,2.1,0.0,0.00,0.0,2.100000,1.750000,75.000000,-14.285714,-33.333333,1.0,2.100000,0.000104,0.000104,0.0,0.000000,0.000141,0.000135,0.60,0.0,0.000030,0.0,0.000164,0.000104,0.000045,C,0
26,blinkit_D112_718589,2026-07-31,2.1,2.1,2.941165,1.718574,0.000104,0.000104,0.000146,0.000085,718589,D112,blinkit,ADV-AHO-R,496.828458,0.0,2.941165,0.000146,0.0,0.0,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Hair Oils,3.221662,3.085605,0.0,2.100000,2.1,0.0,0.10,0.2,2.100000,1.750000,75.000000,-14.285714,-33.333333,1.0,2.100000,0.000104,0.000104,0.0,0.000005,0.000160,0.000153,1.20,0.0,0.000060,0.0,0.000164,0.000104,0.000045,C,0
27,blinkit_D112_718589,2026-08-31,2.1,2.1,3.467539,2.077455,0.000104,0.000104,0.000172,0.000103,718589,D112,blinkit,ADV-AHO-R,496.828458,0.0,3.467539,0.000172,0.0,0.0,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Hair Oils,3.726857,3.589988,0.0,2.100000,2.1,0.0,0.30,0.6,2.100000,1.750000,75.000000,-14.285714,-33.333333,1.0,2.100000,0.000104,0.000104,0.0,0.000015,0.000185,0.000178,2.10,0.0,0.000104,0.0,0.000164,0.000104,0.000045,C,0
28,blinkit_D112_718589,2026-09-30,2.1,2.1,3.368910,2.326143,0.000104,0.000104,0.000167,0.000116,718589,D112,blinkit,ADV-AHO-R,496.828458,0.0,3.368910,0.000167,0.0,0.0,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Hair Oils,3.684226,3.499214,0.0,2.100000,2.1,0.0,0.65,1.3,2.100000,1.750000,75.000000,-14.285714,-33.333333,1.0,2.100000,0.000104,0.000104,0.0,0.000032,0.000183,0.000174,2.10,0.0,0.000104,0.0,0.000164,0.000104,0.000045,C,0
29,blinkit_D112_718589,2026-10-31,2.1,2.1,3.108451,2.213672,0.000104,0.000104,0.000154,0.000110,718589,D112,blinkit,ADV-AHO-R,496.828458,0.0,3.108451,0.000154,0.0,0.0,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Hair Oils,3.352689,3.217803,0.0,2.100000,2.1,0.0,1.00,1.8,2.100000,1.750000,75.000000,-14.285714,-33.333333,1.0,2.100000,0.000104,0.000104,0.0,0.000050,0.000167,0.000160,1.80,0.0,0.000089,0.0,0.000164,0.000104,0.000045,C,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51009,zepto_D673_810125,2026-10-31,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.0,0.000000,0.000000,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+4,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.00,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51010,zepto_D673_810125,2026-11-30,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.0,0.000000,0.000000,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.00,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51011,zepto_D673_810125,2026-12-31,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.0,0.000000,0.000000,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.00,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51012,zepto_D673_810125,2027-01-31,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.0,0.000000,0.000000,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.00,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1
51013,zepto_D673_810125,2027-02-28,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.0,0.000000,0.000000,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.00,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.000000,0.0,0.000000,0.000000,0.000000,0.56,0.0,0.000096,0.0,0.000178,0.000260,0.000027,NPD,1

In [349]:
final_df[final_df['month_date'] == '2026-05-31']['vol_in_rum_value'].sum()

30.927819258546695

Heuristic new approac

In [350]:
# pip install pymannkendall

In [351]:
# final_df.to_csv('brek2.csv', index=False)

In [352]:
import pandas as pd
import numpy as np
import pymannkendall as mk

def detect_trend_for_group(df_grp):
    """
    Detect final trend flag and p3m_slope_flag separately.
    Must contain 'month_date', 'vol_in_rum', 'run_month'
    """

    # ---------- 1. Sort ----------
    df_grp = df_grp.sort_values("month_date")

    # ---------- 2. Identify run_month ----------
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]

    # if no actual data → no trend
    if df_actual.empty or len(df_actual) < 4:
        return pd.Series({"trend_flag": 0, "p3m_slope_flag": 0})

    # ---------- 3. MK Trend ----------
    series = df_actual["vol_in_rum_value"].astype(float)

    try:
        mk_result = mk.original_test(series)
        if mk_result.trend == "increasing":
            mk_trend = 1
        elif mk_result.trend == "decreasing":
            mk_trend = -1
        else:
            mk_trend = 0
    except:
        mk_trend = 0

    # ---------- 4. P3M Slope ----------
    # last 4 months → take last 3 with shift
    #shifted_series = series.shift(1).dropna()

    p3m_values = series.tail(3).values
    #print(p3m_values)

    if len(p3m_values) < 3:
        slope_flag = 0
    else:
        x = np.arange(3)
        slope = np.polyfit(x, p3m_values, 1)[0]
        slope_flag = 1 if slope > 0 else (-1 if slope < 0 else 0)
        

    return pd.Series({
        "trend_flag": mk_trend,
        "p3m_slope_flag": slope_flag
    })


# ---------------------------------------------------------
# APPLY ON ENTIRE DATASET
# ---------------------------------------------------------

# trend_df = final_df.groupby(
#     ["platform_name", "parent_material_code"]
# ).apply(detect_trend_for_group).reset_index()

# trend_df = final_df[final_df['key'] == 'Zepto_721898'].groupby(
#     ["platform_name", "parent_material_code", "run_month"]
# ).apply(detect_trend_for_group).reset_index()
trend_df = final_df.groupby(
    ["platform_name", "depot","parent_material_code", "run_month"]
).apply(detect_trend_for_group).reset_index()

In [353]:
trend_df["final_trend"] = np.where(
    (trend_df["trend_flag"] == 1) & (trend_df["p3m_slope_flag"] == 1), 1,
    np.where(
        (trend_df["trend_flag"] == -1) & (trend_df["p3m_slope_flag"] == -1), -1,
        0
    )
)
trend_df

,platform_name,depot,parent_material_code,run_month,trend_flag,p3m_slope_flag,final_trend
0,blinkit,D112,718288,2026-06-30,0,0,0
1,blinkit,D112,718310,2026-06-30,-1,0,0
2,blinkit,D112,718312,2026-06-30,1,1,1
3,blinkit,D112,718317,2026-06-30,-1,0,0
4,blinkit,D112,718319,2026-06-30,-1,0,0
...,...,...,...,...,...,...,...
10986,zepto,D677,810372,2026-06-30,0,0,0
10987,zepto,D677,810405,2026-06-30,0,0,0
10988,zepto,D677,810406,2026-06-30,-1,0,0
10989,zepto,D677,810407,2026-06-30,0,0,0
10990,zepto,D677,810439,2026-06-30,0,0,0

In [354]:
trend_df[trend_df['final_trend'] == 1]

,platform_name,depot,parent_material_code,run_month,trend_flag,p3m_slope_flag,final_trend
2,blinkit,D112,718312,2026-06-30,1,1,1
13,blinkit,D112,718371,2026-06-30,1,1,1
15,blinkit,D112,718398,2026-06-30,1,1,1
20,blinkit,D112,718461,2026-06-30,1,1,1
21,blinkit,D112,718464,2026-06-30,1,1,1
...,...,...,...,...,...,...,...
10667,zepto,D674,730277,2026-06-30,1,1,1
10717,zepto,D674,809817,2026-06-30,1,1,1
10718,zepto,D674,809818,2026-06-30,1,1,1
10725,zepto,D674,809951,2026-06-30,1,1,1
10739,zepto,D674,810439,2026-06-30,1,1,1

## detect seasonality

In [355]:
from statsmodels.tsa.stattools import acf
import numpy as np
import pandas as pd

def detect_yearly_seasonality(df_grp, threshold=0.3):
    """
    Detects yearly seasonality using ACF at lag=12 only.
    Uses vol_in_rum as the metric.
    """
    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]
    series = df_actual["vol_in_rum"].astype(float).values

    # Need at least 18 points to compare last year vs this year
    if len(series) < 18:
        return 0

    # Compute ACF up to lag-12
    acf_vals = acf(series, nlags=12, fft=False)

    lag12_acf = acf_vals[12]

    # absolute ACF because seasonal correlation can be negative as well
    if abs(lag12_acf) >= threshold:
        return 1
    else:
        return 0
    

seasonality_df = final_df.groupby(
    ["platform_name", "brand_code", 'run_month']
).apply(detect_yearly_seasonality).reset_index(name="seasonality_flag")

seasonality_df

    platform_name brand_code  run_month  seasonality_flag
0         blinkit  ADV-AHO-R 2026-06-30                 0
1         blinkit   BIO OILS 2026-06-30                 0
2         blinkit  CO_SO_PCP 2026-06-30                 0
3         blinkit  CO_SO_VCN 2026-06-30                 0
4         blinkit        H&C 2026-06-30                 0
..            ...        ...        ...               ...
237         zepto   SW HRGEL 2026-06-30                 0
238         zepto   SW HSPRY 2026-06-30                 0
239         zepto  SW STLDEO 2026-06-30                 0
240         zepto  SW_HR_WAX 2026-06-30                 0
241         zepto   SW_SGPRF 2026-06-30                 0

[242 rows x 4 columns]

In [356]:
seasonality_df[seasonality_df['seasonality_flag'] == 1]

    platform_name brand_code  run_month  seasonality_flag
5         blinkit  H&C DFOIL 2026-06-30                 1
59        blinkit   SAF_MAYO 2026-06-30                 1
70        blinkit  SF_MNMKHN 2026-06-30                 1
72        blinkit  SF_SOYBRJ 2026-06-30                 1
75        blinkit   SW NOGAS 2026-06-30                 1
140        swiggy  SAF_FT_MR 2026-06-30                 1
159        swiggy  SF_SOYBRJ 2026-06-30                 1
169         zepto  CO_SO_PCP 2026-06-30                 1
173         zepto   JATAA_HO 2026-06-30                 1
177         zepto  LIVON 2.0 2026-06-30                 1

In [357]:
# seasonality_df.to_csv('seasonality_qcom.csv')

In [358]:
import numpy as np
import pandas as pd

def compute_thresholds(df_grp):
    """
    df_grp MUST contain:
    - month_date
    - vol_in_rum
    - run_month

    Returns: lower_threshold, upper_threshold, mean, std
    """

    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # --- Use ONLY actual data (strictly before run month)
    df_actual = df_grp[df_grp["month_date"] < run_month]

    series = df_actual["vol_in_rum_value"].astype(float).values

    # If no real data → return zeros
    if len(series) == 0:
        return pd.Series({
            "lower_threshold": 0,
            "upper_threshold": 0,
            "mean_value": 0,
            "std_value": 0
        })

    # --- Take last 12 months OR all available
    if len(series) > 12:
        series = series[-12:]

    mean_val = np.mean(series)
    std_val = np.std(series)

    # --- SPECIAL CASE: ≤3 data points
    if len(series) <= 3:
        lower = 0.5 * mean_val
        upper = 2 * mean_val

        return pd.Series({
            "lower_threshold": lower,
            "upper_threshold": upper,
            "mean_value": mean_val,
            "std_value": std_val
        })

    # --- Normal case (std can be zero also)
    lower = max(0,mean_val - 2*std_val)
    upper = mean_val + 3*std_val

    return pd.Series({
        "lower_threshold": lower,
        "upper_threshold": upper,
        "mean_value": mean_val,
        "std_value": std_val
    })

threshold_df = final_df.groupby(
    ["platform_name", "depot","parent_material_code", "run_month"]
).apply(compute_thresholds).reset_index()

threshold_df.head()

,platform_name,depot,parent_material_code,run_month,lower_threshold,upper_threshold,mean_value,std_value
0,blinkit,D112,718288,2026-06-30,0.000000,0.000000,0.000000,0.000000
1,blinkit,D112,718310,2026-06-30,0.000000,0.004954,0.000934,0.001340
2,blinkit,D112,718312,2026-06-30,0.008525,0.050700,0.025395,0.008435
3,blinkit,D112,718317,2026-06-30,0.000000,0.000000,0.000000,0.000000
4,blinkit,D112,718319,2026-06-30,0.000000,0.000000,0.000000,0.000000

In [359]:
final_df[final_df['key'] == 'blinkit_D112_718317']

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped
17218,blinkit_D112_718317,2023-01-31,0.900000,4.766667,3.062103,3.791643,0.000035,1.849831e-04,1.188330e-04,1.471447e-04,718317,D112,blinkit,H&C,388.076436,0.000047,0.000000,0.000000e+00,1.2,0.000047,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.303118,3.667845,1.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000167,0.000142,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,C,0
17219,blinkit_D112_718317,2023-02-28,0.900000,4.766667,2.988898,3.363310,0.000035,1.849831e-04,1.159921e-04,1.305221e-04,718317,D112,blinkit,H&C,388.076436,0.000043,0.000000,0.000000e+00,1.1,0.000043,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.252172,3.658546,1.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000165,0.000142,0.0,0.0,0.000000,0.000000,0.000047,0.000000,0.000000,C,0
17220,blinkit_D112_718317,2023-03-31,0.900000,4.766667,2.734864,3.165810,0.000035,1.849831e-04,1.061336e-04,1.228576e-04,718317,D112,blinkit,H&C,388.076436,0.000016,0.000000,0.000000e+00,0.4,0.000016,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.020145,3.363739,0.4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000156,0.000131,0.0,0.0,0.000000,0.000000,0.000043,0.000047,0.000000,C,0
17221,blinkit_D112_718317,2023-04-30,0.900000,4.766667,5.053947,7.911143,0.000035,1.849831e-04,1.961318e-04,3.070128e-04,718317,D112,blinkit,H&C,388.076436,0.000407,0.000000,0.000000e+00,10.5,0.000407,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,6.135255,5.474826,10.5,0.900000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.900000,0.000035,0.000000e+00,0.000000,0.000000e+00,0.000238,0.000212,0.0,0.0,0.000000,0.000000,0.000016,0.000043,0.000047,C,0
17222,blinkit_D112_718317,2023-05-31,4.000000,4.766667,5.061839,6.945500,0.000155,1.849831e-04,1.964380e-04,2.695385e-04,718317,D112,blinkit,H&C,388.076436,0.000427,0.000000,0.000000e+00,11.0,0.000427,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,6.320910,5.642212,11.0,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,344.444444,0.000000,0.000000,0.0,4.000000,0.000155,0.000000e+00,0.000000,0.000000e+00,0.000245,0.000219,0.0,0.0,0.000000,0.000000,0.000407,0.000016,0.000043,C,0
17223,blinkit_D112_718317,2023-06-30,7.300000,4.766667,3.035071,4.898333,0.000283,1.849831e-04,1.177839e-04,1.900928e-04,718317,D112,blinkit,H&C,388.076436,0.000171,0.000000,0.000000e+00,4.4,0.000171,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.388820,3.801981,4.4,7.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,82.500000,344.444444,0.000000,0.0,7.300000,0.000283,0.000000e+00,0.000000,0.000000e+00,0.000170,0.000148,0.0,0.0,0.000000,0.000000,0.000427,0.000407,0.000016,C,0
17224,blinkit_D112_718317,2023-07-31,8.633333,4.766667,4.290371,7.315238,0.000335,1.849831e-04,1.664992e-04,2.838872e-04,718317,D112,blinkit,H&C,388.076436,0.000334,0.000000,0.000000e+00,8.6,0.000334,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,5.605988,4.920248,8.6,8.633333,4.766667,0.000000,0.000000,0.000000,7.300000,5.650000,18.264840,82.500000,344.444444,2.0,7.966667,0.000335,1.849831e-04,0.000000,0.000000e+00,0.000218,0.000191,0.0,0.0,0.000000,0.000000,0.000171,0.000427,0.000407,C,0
17225,blinkit_D112_718317,2023-08-31,8.000000,6.000000,5.029637,8.003571,0.000310,2.328459e-04,1.951884e-04,3.105997e-04,718317,D112,blinkit,H&C,388.076436,0.000427,0.000000,0.000000e+00,11.0,0.000427,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,6.309734,5.713179,11.0,8.000000,6.000000,0.000000,0.000000,0.000000,8.633333,7.966667,-7.335907,18.264840,82.500000,1.0,8.316667,0.000310,2.328459e-04,0.000000,0.000000e+00,0.000245,0.000222,0.0,0.0,0.000000,0.000000,0.000334,0.000171,0.000427,C,0
17226,blinkit_D112_718317,2023-09-30,8.000000,7.650000,3.270613,6.041905,0.000310,2.968785e-04,1.269248e-04,2.344721e-04,718317,D112,blinkit,H&C,388.076436,0.000194,0.000000,0.000000e+00,5.0,0.000194,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.452845,3.820155,5.0,8.000000,7.650000,0.000000,0.000000,0.000000,8.633333,8.316667,0.000000,-7.335907,18.264840,0.0,8.316667,0.000310,2.968785e-04,0.000000,0.000000e+00,0.000173,0.000148,0.0,0.0,0.000000,0.000000,0.000427,0.000334,0.000171,C,0
17227,blinkit_D112_718317,2023-10-31,8.200000,8.416667,1.835977,4.297381,0.000318,3.266310e-04,7.124995e-05,1.667712e-04,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,3.063012,2.466524,0.0,8.200000,8.416667,0.000000,0.000000,0.000000,8.633333,8.316667,2.500000,0.000000,-7.335907,0.0,8.416667,0.000318,3.266310e-04,0.000000,0.000000e+00,0.000119,0.000096,0.0,0.0,0.000000,0.000000,0.000194,0.000427,0.000334,C,0
17228,blinkit_D112_718317,2023-11-30,5.333333,6.666667,1.975607,0.502143,0.000207,2.587176e-04,7.666863e-05,1.948698e-05,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,3.220482,2.596192,0.0,5.333333,6.666667,0.000000,0.000000,0.000000,8.200000,8.100000,-34.959350,2.500000,0.000000,0.0,6.766667,0.000207,2.587176e-04,0.000000,0.000000e+00,0.000125,0.000101,0.0,0.0,0.000000,0.000000,0.000000,0.000194,0.000427,C,0
17229,blinkit_D112_718317,2023-12-31,1.666667,4.833333,1.906809,0.557810,0.000065,1.875703e-04,7.399876e-05,2.164727e-05,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.997789,2.473780,0.0,1.666667,4.833333,0.000000,0.000000,0.000000,8.200000,8.100000,-68.750000,-34.959350,2.500000,0.0,4.933333,0.000065,1.875703e-04,0.000000,0.000000e+00,0.000116,0.000096,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000194,C,0
17230,blinkit_D112_718317,2024-01-31,0.000000,4.100000,1.383967,0.032833,0.000000,1.591113e-04,5.370851e-05,1.274184e-06,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.685706,2.026968,0.0,0.000000,4.100000,0.000000,0.000000,0.000000,8.200000,6.766667,-100.000000,-68.750000,-34.959350,0.0,4.100000,0.000000,1.591113e-04,0.000000,0.000000e+00,0.000104,0.000079,1.2,0.0,0.000047,0.000000,0.000000,0.000000,0.000000,C,0
17231,blinkit_D112_718317,2024-02-29,0.000000,2.666667,1.344076,0.145833,0.000000,1.034870e-04,5.216042e-05,5.659448e-06,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.619616,2.033485,0.0,0.000000,2.666667,0.000000,0.000000,0.000000,5.333333,3.500000,-100.000000,-100.000000,-68.750000,0.0,2.666667,0.000000,1.034870e-04,0.000000,0.000000e+00,0.000102,0.000079,1.1,0.0,0.000043,0.000000,0.000000,0.000000,0.000000,C,0
17232,blinkit_D112_718317,2024-03-31,0.000000,0.833333,1.074465,0.006538,0.000000,3.233970e-05,4.169746e-05,2.537423e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.188794,1.568392,0.0,0.000000,0.833333,0.000000,0.000000,0.000000,1.666667,0.833333,-100.000000,-100.000000,-100.000000,0.0,0.833333,0.000000,3.233970e-05,0.000000,0.000000e+00,0.000085,0.000061,0.4,0.0,0.000016,0.000000,0.000000,0.000000,0.000000,C,0
17233,blinkit_D112_718317,2024-04-30,0.000000,0.000000,3.331477,0.035253,0.000000,0.000000e+00,1.292868e-04,1.368076e-06,718317,D112,blinkit,H&C,388.076436,0.000008,0.000000,0.000000e+00,0.2,0.000008,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.645112,4.025115,0.2,0.000000,0.000000,0.900000,0.000000,0.900000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000e+00,0.000035,0.000000e+00,0.000180,0.000156,10.5,0.0,0.000407,0.000000,0.000000,0.000000,0.000000,C,0
17234,blinkit_D112_718317,2024-05-31,0.066667,0.033333,3.412173,0.005000,0.000003,1.293588e-06,1.324184e-04,1.940382e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.607580,4.092666,0.0,0.066667,0.033333,4.000000,0.000000,4.000000,0.000000,0.000000,inf,-100.000000,-100.000000,0.0,0.033333,0.000003,1.293588e-06,0.000155,0.000000e+00,0.000179,0.000159,11.0,0.0,0.000427,0.000000,0.000008,0.000000,0.000000,C,0
17235,blinkit_D112_718317,2024-06-30,0.066667,0.033333,1.403881,0.001538,0.000003,1.293588e-06,5.448132e-05,5.970407e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.817718,2.121175,0.0,0.066667,0.033333,7.300000,0.000000,7.300000,0.066667,0.033333,0.000000,inf,-100.000000,0.0,0.066667,0.000003,1.293588e-06,0.000283,0.000000e+00,0.000109,0.000082,4.4,0.0,0.000171,0.000000,0.000000,0.000008,0.000000,C,0
17236,blinkit_D112_718317,2024-07-31,0.066667,0.033333,2.557615,0.002372,0.000003,1.293588e-06,9.925501e-05,9.204377e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,3.768944,3.182413,0.0,0.066667,0.033333,8.633333,4.766667,8.633333,0.066667,0.066667,0.000000,0.000000,inf,0.0,0.066667,0.000003,1.293588e-06,0.000335,1.849831e-04,0.000146,0.000124,8.6,0.0,0.000334,0.000000,0.000000,0.000000,0.000008,C,0
17237,blinkit_D112_718317,2024-08-31,0.000000,0.033333,3.303609,0.000833,0.000000,1.293588e-06,1.282053e-04,3.233970e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,4.595956,3.857307,0.0,0.000000,0.033333,8.000000,6.000000,8.000000,0.066667,0.066667,-100.000000,0.000000,0.000000,0.0,0.033333,0.000000,1.293588e-06,0.000310,2.328459e-04,0.000178,0.000150,11.0,0.0,0.000427,0.000000,0.000000,0.000000,0.000000,C,0
17238,blinkit_D112_718317,2024-09-30,0.000000,0.033333,1.608012,0.001538,0.000000,1.293588e-06,6.240316e-05,5.970407e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.873598,2.116255,0.0,0.000000,0.033333,8.000000,7.650000,8.000000,0.066667,0.066667,-100.000000,-100.000000,0.000000,0.0,0.033333,0.000000,1.293588e-06,0.000310,2.968785e-04,0.000112,0.000082,5.0,0.0,0.000194,0.000000,0.000000,0.000000,0.000000,C,0
17239,blinkit_D112_718317,2024-10-31,0.000000,0.033333,0.160230,0.008086,0.000000,1.293588e-06,6.218167e-06,3.138017e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,1.374582,0.751376,0.0,0.000000,0.033333,8.200000,8.416667,8.200000,0.066667,0.033333,-100.000000,-100.000000,-100.000000,0.0,0.033333,0.000000,1.293588e-06,0.000318,3.266310e-04,0.000053,0.000029,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,C,0
17240,blinkit_D112_718317,2024-11-30,0.000000,0.000000,0.264824,0.103000,0.000000,0.000000e+00,1.027721e-05,3.997187e-06,718317,D112,blinkit,H&C,388.076436,0.000012,0.000000,0.000000e+00,0.3,0.000012,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,1.371589,0.748220,0.3,0.000000,0.000000,5.333333,6.666667,5.333333,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000e+00,0.000207,2.587176e-04,0.000053,0.000029,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,C,0
17241,blinkit_D112_718317,2024-12-31,0.100000,0.050000,0.203472,1.093333,0.000004,1.940382e-06,7.896283e-06,4.242969e-05,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,1.430827,0.733950,0.0,0.100000,0.050000,1.666667,4.833333,1.666667,0.000000,0.000000,inf,-100.000000,-100.000000,0.0,0.050000,0.000004,1.940382e-06,0.000065,1.875703e-04,0.000056,0.000028,0.0,0.0,0.000000,0.000000,0.000012,0.000000,0.000000,C,0
17242,blinkit_D112_718317,2025-01-31,0.100000,0.050000,0.000000,0.057833,0.000004,1.940382e-06,0.000000e+00,2.244375e-06,718317,D112,blinkit,H&C,388.076436,0.000004,0.000000,0.000000e+00,0.1,0.000004,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.906821,0.341474,0.1,0.100000,0.050000,0.000000,4.100000,0.000000,0.100000,0.050000,0.000000,inf,-100.000000,0.0,0.100000,0.000004,1.940382e-06,0.000000,1.591113e-04,0.000035,0.000013,0.0,1.2,0.000000,0.000047,0.000000,0.000012,0.000000,C,0
17243,blinkit_D112_718317,2025-02-28,0.133333,0.066667,0.000000,0.045000,0.000005,2.587176e-06,0.000000e+00,1.746344e-06,718317,D112,blinkit,H&C,388.076436,0.000004,0.000000,0.000000e+00,0.1,0.000004,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.878072,0.303403,0.1,0.133333,0.066667,0.000000,2.666667,0.000000,0.100000,0.100000,33.333333,0.000000,inf,0.0,0.116667,0.000005,2.587176e-06,0.000000,1.034870e-04,0.000034,0.000012,0.0,1.1,0.000000,0.000043,0.000004,0.000000,0.000012,C,0
17244,blinkit_D112_718317,2025-03-31,0.066667,0.083333,0.000000,0.010000,0.000003,3.233970e-06,0.000000e+00,3.880764e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.662805,0.041969,0.0,0.066667,0.083333,0.000000,0.833333,0.000000,0.133333,0.116667,-50.000000,33.333333,0.000000,1.0,0.100000,0.000003,3.233970e-06,0.000000,3.233970e-05,0.000026,0.000002,0.0,0.4,0.000000,0.000016,0.000004,0.000004,0.000000,C,0
17245,blinkit_D112_718317,2025-04-30,0.066667,0.083333,1.667223,1.067253,0.000003,3.233970e-06,6.470098e-05,4.141756e-05,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,3.063542,2.372990,0.0,0.066667,0.083333,0.000000,0.000000,0.000000,0.133333,0.116667,0.000000,-50.000000,33.333333,1.0,0.100000,0.000003,3.233970e-06,0.000000,0.000000e+00,0.000119,0.000092,0.2,10.5,0.000008,0.000407,0.000000,0.000004,0.000004,C,0
17246,blinkit_D112_718317,2025-05-31,0.033333,0.083333,1.723837,0.005833,0.000001,3.233970e-06,6.689806e-05,2.263779e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.928748,2.263936,0.0,0.033333,0.083333,0.066667,0.033333,0.066667,0.133333,0.100000,-50.000000,0.000000,-50.000000,0.0,0.083333,0.000001,3.233970e-06,0.000003,1.293588e-06,0.000114,0.000088,0.0,11.0,0.000000,0.000427,0.000000,0.000000,0.000004,C,0
17247,blinkit_D112_718317,2025-06-30,0.000000,0.033333,0.000000,0.000000,0.000000,1.293588e-06,0.000000e+00,0.000000e+00,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.851488,0.231542,0.0,0.000000,0.033333,0.066667,0.033333,0.066667,0.066667,0.066667,-100.000000,-50.000000,0.000000,0.0,0.033333,0.000000,1.293588e-06,0.000003,1.293588e-06,0.000033,0.000009,0.0,4.4,0.000000,0.000171,0.000000,0.000000,0.000000,C,0
17248,blinkit_D112_718317,2025-07-31,0.000000,0.033333,0.895793,0.002372,0.000000,1.293588e-06,3.476363e-05,9.204377e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.049933,1.443820,0.0,0.000000,0.033333,0.066667,0.033333,0.066667,0.066667,0.050000,-100.000000,-100.000000,-50.000000,0.0,0.033333,0.000000,1.293588e-06,0.000003,1.293588e-06,0.000080,0.000056,0.0,8.6,0.000000,0.000334,0.000000,0.000000,0.000000,C,0
17249,blinkit_D112_718317,2025-08-31,0.000000,0.016667,1.640749,0.002372,0.000000,6.467941e-07,6.367361e-05,9.204377e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,2.820208,2.271425,0.0,0.000000,0.016667,0.000000,0.033333,0.000000,0.033333,0.016667,-100.000000,-100.000000,-100.000000,0.0,0.016667,0.000000,6.467941e-07,0.000000,1.293588e-06,0.000109,0.000088,0.0,11.0,0.000000,0.000427,0.000000,0.000000,0.000000,C,0
17250,blinkit_D112_718317,2025-09-30,0.000000,0.000000,0.000000,0.001538,0.000000,0.000000e+00,0.000000e+00,5.970407e-08,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,1.176424,0.493468,0.0,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,1.293588e-06,0.000046,0.000019,0.0,5.0,0.000000,0.000194,0.000000,0.000000,0.000000,C,0
17251,blinkit_D112_718317,2025-10-31,0.000000,0.000000,0.000000,0.008086,0.000000,0.000000e+00,0.000000e+00,3.138017e-07,718317,D112,blinkit,H&C,388.076436,0.000000,0.000000,0.000000e+00,0.0,0.000000,2026-05-31,2.413462,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.033333,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000e+00,0.000000,1.293588e-06,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,C,0

In [360]:
trend_df = trend_df.merge(threshold_df, on = ['platform_name', 'depot','parent_material_code', 'run_month'], how = 'left')
trend_df

,platform_name,depot,parent_material_code,run_month,trend_flag,p3m_slope_flag,final_trend,lower_threshold,upper_threshold,mean_value,std_value
0,blinkit,D112,718288,2026-06-30,0,0,0,0.000000,0.000000,0.000000,0.000000
1,blinkit,D112,718310,2026-06-30,-1,0,0,0.000000,0.004954,0.000934,0.001340
2,blinkit,D112,718312,2026-06-30,1,1,1,0.008525,0.050700,0.025395,0.008435
3,blinkit,D112,718317,2026-06-30,-1,0,0,0.000000,0.000000,0.000000,0.000000
4,blinkit,D112,718319,2026-06-30,-1,0,0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
10986,zepto,D677,810372,2026-06-30,0,0,0,0.000000,0.000000,0.000000,0.000000
10987,zepto,D677,810405,2026-06-30,0,0,0,0.000000,0.000000,0.000000,0.000000
10988,zepto,D677,810406,2026-06-30,-1,0,0,0.000000,0.000000,0.000000,0.000000
10989,zepto,D677,810407,2026-06-30,0,0,0,0.000000,0.000000,0.000000,0.000000
10990,zepto,D677,810439,2026-06-30,0,0,0,0.000000,0.000000,0.000000,0.000000

In [361]:
# trend_df.to_csv('t_thres_df_qcom.csv')

In [362]:
final_df = final_df.merge(seasonality_df, on = ["platform_name", "brand_code", 'run_month'], how = 'left')
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped,seasonality_flag
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,0.0,0.0,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000024,1.618828e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0,0
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000075,0.000000,0.000000,C,0,0
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000006,1.131882e-07,0.00,0.0,0.000000,0.0,0.000000,0.000075,0.000000,C,0,0
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.500000,0.000025,0.0,0.0,0.0,0.000026,2.037054e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000075,C,0,0
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-100.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000029,2.138962e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310212,zepto_D673_810125,2026-11-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0
310213,zepto_D673_810125,2026-12-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0
310214,zepto_D673_810125,2027-01-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0
310215,zepto_D673_810125,2027-02-28,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.56,0.0,0.000096,0.0,0.000178,0.000260,0.000027,NPD,1,0
310216,zepto_D673_810125,2027-03-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,None,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.16,0.0,0.000027,0.0,0.000178,0.000260,0.000027,NPD,1,0

In [363]:
trend_df.columns

Index(['platform_name', 'depot', 'parent_material_code', 'run_month',
       'trend_flag', 'p3m_slope_flag', 'final_trend', 'lower_threshold',
       'upper_threshold', 'mean_value', 'std_value'],
      dtype='object')

In [364]:
final_df = final_df.merge(trend_df[['platform_name', 'depot','parent_material_code', 'run_month',
                                    'final_trend','lower_threshold', 'upper_threshold']], on = ["platform_name", "depot","parent_material_code", 'run_month'], how = 'left')
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped,seasonality_flag,final_trend,lower_threshold,upper_threshold
0,blinkit_D112_718589,2024-05-31,0.5,0.25,0.193725,0.943558,0.000025,0.000012,0.000010,0.000047,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000075,0.0,0.0,1.5,0.000075,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.474310,0.325832,1.5,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000024,1.618828e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0,0,1,0.000008,0.000221
1,blinkit_D112_718589,2024-06-30,0.5,0.25,0.000000,0.840701,0.000025,0.000012,0.000000,0.000042,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000075,0.000000,0.000000,C,0,0,1,0.000008,0.000221
2,blinkit_D112_718589,2024-07-31,0.5,0.25,0.000000,0.327961,0.000025,0.000012,0.000000,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.125969,0.002278,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000006,1.131882e-07,0.00,0.0,0.000000,0.0,0.000000,0.000075,0.000000,C,0,0,1,0.000008,0.000221
3,blinkit_D112_718589,2024-08-31,0.5,0.25,0.244806,0.327961,0.000025,0.000012,0.000012,0.000016,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.531383,0.410012,0.0,0.500000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.500000,0.000025,0.0,0.0,0.0,0.000026,2.037054e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000075,C,0,0,1,0.000008,0.000221
4,blinkit_D112_718589,2024-09-30,0.0,0.25,0.279075,0.423717,0.000000,0.000012,0.000014,0.000021,718589,D112,blinkit,ADV-AHO-R,496.828458,0.000000,0.0,0.0,0.0,0.000000,2026-05-31,1.169268,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Hair Oils,0.580217,0.430523,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,-100.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000029,2.138962e-05,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,C,0,0,1,0.000008,0.000221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310212,zepto_D673_810125,2026-11-30,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+5,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0,0,0.000000,0.000403
310213,zepto_D673_810125,2026-12-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+6,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0,0,0.000000,0.000403
310214,zepto_D673_810125,2027-01-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+7,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.00,0.0,0.000000,0.0,0.000178,0.000260,0.000027,NPD,1,0,0,0.000000,0.000403
310215,zepto_D673_810125,2027-02-28,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,M+8,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.56,0.0,0.000096,0.0,0.000178,0.000260,0.000027,NPD,1,0,0,0.000000,0.000403
310216,zepto_D673_810125,2027-03-31,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810125,D673,zepto,SW_SGPRF,1712.605337,0.000000,0.0,0.0,0.0,0.000000,NaT,0.000000,NaN,NaN,NaN,2026-06-30,None,Male Grooming,0.000000,0.000000,0.0,0.906667,0.0,0.0,0.0,0.0,0.746667,0.553333,21.428571,107.407407,28.571429,3.0,0.826667,0.000155,0.0,0.0,0.0,0.000000,0.000000e+00,0.16,0.0,0.000027,0.0,0.000178,0.000260,0.000027,NPD,1,0,0,0.000000,0.000403

In [ ]:
# final_df[final_df['skipped'] == 1]['lower_threshold'].sum()

6.408238205290727

In [366]:
final_df = final_df.sort_values(['key', 'run_month','month_date'])

# base LY


# LY lags
final_df['ly_lag1_value'] = (
    final_df
    .groupby(['key', 'run_month'])['vol_in_rum_value']
    .shift(13)
)

final_df['ly_lag2_value'] = (
    final_df
    .groupby(['key', 'run_month'])['vol_in_rum_value']
    .shift(14)
)

# LY leads
final_df['ly_lead1_value'] = (
    final_df
    .groupby(['key', 'run_month'])['vol_in_rum_value']
    .shift(11)
)

final_df['ly_lead2_value'] = (
    final_df
    .groupby(['key', 'run_month'])['vol_in_rum_value']
    .shift(10)
)

In [126]:
# final_df['stat_bias'] = final_df['Stat Error']/final_df['Actuals Val']
# final_df = final_df.fillna(0)

# import numpy as np
# import pandas as pd

# final_df['stat_bias'] = (
#     final_df['stat_bias']
#     .replace([np.inf, -np.inf], 0)
#     .fillna(0)
# )

# bins = [-np.inf, -0.15, -0.10, -0.05, 0, 0.05, 0.10, 0.15, np.inf]
# labels = [
#     '< -15%',
#     '-15% to -10%',
#     '-10% to -5%',
#     '-5% to 0%',
#     '0% to 5%',
#     '5% to 10%',
#     '10% to 15%',
#     '> 15%'
# ]

# final_df['stat_bias_bucket'] = pd.cut(
#     final_df['stat_bias'],
#     bins=bins,
#     labels=labels,
#     right=False  
# )

In [ ]:
# final_df[(final_df['month_date'] == '2026-03-31') & (final_df['run_month'] == '2026-01-31')]['P3M_value'].sum()

26.37755518302953

In [368]:
brand_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'brand')
brand_seas.columns = brand_seas.columns.str.lower()
brand_seas.rename(columns={'brand':'brand_code', 'months_num':'month', 'flag':'is_seasonal_month'}, inplace=True)

final_df['month_date'] = pd.to_datetime(final_df['month_date'])
final_df['month'] = final_df['month_date'].dt.month
final_df = final_df.merge(brand_seas, on = ['brand_code', 'month'], how = 'left')
final_df['is_seasonal_month'].fillna(0, inplace=True)

psku_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'psku')
psku_seas.columns = psku_seas.columns.str.lower()
psku_seas.rename(columns={'months_num':'month', 'flag':'is_seasonal_month_psku'}, inplace=True)

final_df = final_df.merge(psku_seas[['parent_material_code', 'month','is_seasonal_month_psku']], on = ['parent_material_code', 'month'], how = 'left')
final_df['is_seasonal_month_psku'].fillna(0, inplace=True)
final_df['final_seasonal_month'] = np.where(
    (final_df['is_seasonal_month'] == 1) | (final_df['is_seasonal_month_psku'] == 1), 1, 0
)

In [369]:
final_df['run_month'] = pd.to_datetime(final_df['run_month'])
def compute_adjusted_pm(df_grp, window, column, year_shift=0):
    df_grp = df_grp.sort_values("month_date")

    run_month = df_grp["run_month"].iloc[0]

    # define cutoff
    end_date = run_month - pd.DateOffset(years=year_shift)

    # keep only eligible history (before run month & non-event)
    hist = df_grp[
        (df_grp["month_date"] < end_date) &
        (df_grp["final_seasonal_month"] == 0)
    ]

    if hist.empty:
        return np.nan

    # take last `window` non-event months
    hist = hist.tail(window)

    # if len(hist) < window:
    #     return np.nan   # optional, keeps behavior strict

    return hist[column].mean()

adj_df = final_df.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "P3M_non_seasonal": compute_adjusted_pm(x, 3,'vol_in_rum',0),
        "P6M_non_seasonal": compute_adjusted_pm(x, 6,'vol_in_rum',0),
        "P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'vol_in_rum_value',0),
        "P6M_non_seasonal_value": compute_adjusted_pm(x, 6,'vol_in_rum_value',0)
    })
).reset_index()
adj_df


adj_ly_df = final_df.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "LY_P3M_non_seasonal": compute_adjusted_pm(x, 3,'vol_in_rum',year_shift=1),
        "LY_P6M_non_seasonal": compute_adjusted_pm(x, 6,'vol_in_rum', year_shift=1),
        "LY_P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'vol_in_rum_value', year_shift=1),
        "LY_P6M_non_seasonal_value": compute_adjusted_pm(x, 6,"vol_in_rum_value", year_shift=1)
    })
).reset_index()

adj_df = adj_df.merge(adj_ly_df, on = ['key', 'run_month'], how = 'left')
#adj_df[adj_df['key'] == 'reliance_b2c_2_haryana_718488']
adj_df

,key,run_month,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,blinkit_D112_718288,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
1,blinkit_D112_718310,2026-06-30,0.000000,0.010500,0.00000,0.000367,0.025500,0.025500,0.000891,0.000891
2,blinkit_D112_718312,2026-06-30,0.992333,0.758833,0.03466,0.026504,0.965667,0.787333,0.033728,0.027500
3,blinkit_D112_718317,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.033333,0.000000,0.000001
4,blinkit_D112_718319,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
10986,zepto_D677_810372,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.050000,0.050000,0.000009,0.000009
10987,zepto_D677_810405,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.015000,0.000000,0.000003
10988,zepto_D677_810406,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.012000,0.000000,0.000002
10989,zepto_D677_810407,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000000,0.007500,0.000000,0.000001
10990,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.00000,0.000000,0.000700,0.000700,0.000022,0.000022

In [370]:
final_df.shape

(310217, 71)

In [371]:
# adj_df.to_csv('seasonal_p3m_qcom.csv', index=False)
#all[all['month_date'].isin(['2025-11-30','2025-12-31','2026-01-31'])].groupby(['key','run_month','month_date','final_seasonal_month'])['vol_in_rum'].sum().reset_index().to_csv('seasonal_month_check.csv', index=False)
final_df = final_df.merge(
    adj_df,
    on=['key'],
    how="left"
)
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month_x,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,blinkit_D112_718288,2024-05-31,0.048333,0.024167,0.092660,0.048333,0.000671,0.000336,0.001287,0.000671,718288,D112,blinkit,SAFF GOLD,138865.260689,0.002014,0.0,0.0,0.145,0.002014,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.100956,0.096379,0.145,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.001402,0.001338,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,5,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000
1,blinkit_D112_718288,2024-06-30,0.048333,0.024167,0.001315,0.019333,0.000671,0.000336,0.000018,0.000268,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.009374,0.005674,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000130,0.000079,0.0,0.0,0.0,0.0,0.002014,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,6,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000
2,blinkit_D112_718288,2024-07-31,0.048333,0.024167,0.003047,0.004833,0.000671,0.000336,0.000042,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.011299,0.007322,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000157,0.000102,0.0,0.0,0.0,0.0,0.000000,0.002014,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,7,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000
3,blinkit_D112_718288,2024-08-31,0.048333,0.024167,0.004675,0.004833,0.000671,0.000336,0.000065,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.012763,0.008798,0.000,0.048333,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.048333,0.000671,0.0,0.0,0.0,0.000177,0.000122,0.0,0.0,0.0,0.0,0.000000,0.000000,0.002014,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000
4,blinkit_D112_718288,2024-09-30,0.000000,0.024167,0.006517,0.004833,0.000000,0.000336,0.000090,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.014201,0.010185,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000197,0.000141,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310212,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000022,NaN,0.0,0.0,6,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022
310213,zepto_D677_810439,2026-07-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000022,0.0,0.0,7,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022
310214,zepto_D677_810439,2026-08-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000233,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,8,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022
310215,zepto_D677_810439,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,9,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022
310216,zepto_D677_810439,2026-10-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,10,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022

In [372]:
all_brand = final_df.groupby(['brand_code', 'run_month_x','month_date'])['vol_in_rum_value'].sum().reset_index()
def detect_month_anomaly(df, brand_code, month_num, threshold=0.25, months_window=3):
    """
    Detect if a specific month's vol_in_rum_value is >25% different 
    from past 3 months & next 3 months, and if pattern repeats in last 2 years.
    
    Parameters:
    - df: input dataframe with 'month_date', 'vol_in_rum_value'
    - brand_code: filter by this brand code
    - month_num: month to check (6, 7, 8, 9)
    - threshold: 25% difference threshold
    - months_window: number of months before and after to compare
    """
    
    df_brand = df[df['brand_code'] == brand_code].sort_values('month_date').copy()
    
    if df_brand.empty:
        return None
    
    df_brand['year'] = df_brand['month_date'].dt.year
    df_brand['month'] = df_brand['month_date'].dt.month
    
    years = sorted(df_brand['year'].unique())
    current_year = years[-1]
    past_years = [y for y in years if y < current_year][-2:]
    
    anomalies = []
    
    for year in past_years:
        df_year = df_brand[df_brand['year'] == year].sort_values('month_date')
        
        month_data = df_year[df_year['month'] == month_num]
        if month_data.empty:
            continue
        
        month_value = month_data['vol_in_rum_value'].iloc[0]
        
        past_months = [(month_num - i - 1) % 12 + 1 for i in range(1, months_window + 1)]
        next_months = [(month_num + i - 1) % 12 + 1 for i in range(1, months_window + 1)]
        
        past_m = df_year[df_year['month'].isin(past_months)]['vol_in_rum_value']
        next_m = df_year[df_year['month'].isin(next_months)]['vol_in_rum_value']
        
        comparison_values = pd.concat([past_m])
        
        if comparison_values.empty:
            continue
        
        pct_diffs = []
        for comp_value in comparison_values:
            if comp_value != 0:
                pct_diff = (month_value - comp_value) / comp_value
                pct_diffs.append(pct_diff)
        
        if pct_diffs:
            positive_diffs = [p for p in pct_diffs if p > 0]
            negative_diffs = [p for p in pct_diffs if p < 0]
            same_sign = len(positive_diffs) == len(pct_diffs) or len(negative_diffs) == len(pct_diffs)
            is_anomaly = len([p for p in pct_diffs if abs(p) > threshold]) == len(pct_diffs) and same_sign
        else:
            is_anomaly = False

        anomalies.append({
            'brand_code': brand_code,
            'month': month_num,
            'year': year,
            'month_value': month_value,
            'num_months_compared': len(comparison_values),
            'pct_diffs_from_each': pct_diffs,
            'min_pct_diff': min(pct_diffs) * 100 if pct_diffs else None,
            'max_pct_diff': max(pct_diffs) * 100 if pct_diffs else None,
            'is_anomaly': is_anomaly,
            'direction': 'higher' if month_value > comparison_values.mean() else 'lower'
        })
    
    if len(anomalies) == 2:
        pattern_repeats = anomalies[0]['is_anomaly'] and anomalies[1]['is_anomaly']
        return pd.DataFrame(anomalies), pattern_repeats
    
    return pd.DataFrame(anomalies), False


# Check months 6, 7, 8, 9
brands = all_brand['brand_code'].unique()
results = []

for month in [7, 8, 9,10]:
    for brand in brands:
        df_result, repeats = detect_month_anomaly(all_brand, brand, month)
        if df_result is not None and not df_result.empty:
            df_result['pattern_repeats'] = repeats
            results.append(df_result)

anomaly_summary = pd.concat(results, ignore_index=True)
print(anomaly_summary[anomaly_summary['pattern_repeats'] == True])

    brand_code  month  year  month_value  num_months_compared  \
33   LVN_SRSNS      7  2025     0.000377                    3
34   LVN_SRSNS      7  2026     0.000000                    3
53   PABABY_GM      7  2025     0.039688                    3
54   PABABY_GM      7  2026     0.000000                    3
64   PADV_SMPN      7  2025     0.000733                    2
65   PADV_SMPN      7  2026     0.000000                    3
75   PA_EXT_ML      7  2025     0.085042                    3
76   PA_EXT_ML      7  2026     0.000000                    3
94    P_EN_ALM      7  2025     0.013483                    3
95    P_EN_ALM      7  2026     0.000000                    3
127  SAF_CDPRS      7  2025     0.214136                    1
128  SAF_CDPRS      7  2026     0.000000                    3
133  SAF_FT_MR      7  2024     0.000000                    3
134  SAF_FT_MR      7  2025     0.000000                    3
164  SF_IM_CHY      7  2025     0.000780                    3
165  SF_IM_CHY      7  2026     0.000000                    3
180  SW STLDEO      7  2025     0.103507                    3
181  SW STLDEO      7  2026     0.000000                    3
184   SW_SGPRF      7  2025     0.004268                    3
185   SW_SGPRF      7  2026     0.000000                    3
202     HC SNS      8  2025     0.000067                    1
203     HC SNS      8  2026     0.000000                    3
206    KAYA_GM      8  2025     0.020252                    3
207    KAYA_GM      8  2026     0.000000                    3
222  LVN_SRSNS      8  2025     0.000181                    3
223  LVN_SRSNS      8  2026     0.000000                    3
255  PADV_SWGL      8  2025     0.000479                    3
256  PADV_SWGL      8  2026     0.000000                    3
262   PA_EN_ML      8  2025     0.000577                    1
263   PA_EN_ML      8  2026     0.000000                    3
264  PA_ESS_HO      8  2025     0.013954                    1
265  PA_ESS_HO      8  2026     0.000000                    3
266  PA_EXT_ML      8  2025     0.132082                    3
267  PA_EXT_ML      8  2026     0.000000                    3
274   PA_SRM_R      8  2025     0.001020                    1
275   PA_SRM_R      8  2026     0.000000                    3
301  REV_LQFRG      8  2025     0.000878                    3
302  REV_LQFRG      8  2026     0.000000                    3
319  SAF_CDPRS      8  2025     0.362518                    2
320  SAF_CDPRS      8  2026     0.000000                    3
325  SAF_FT_MR      8  2024     0.000000                    3
326  SAF_FT_MR      8  2025     0.000000                    3
329   SAF_MAYO      8  2024     0.000219                    3
330   SAF_MAYO      8  2025     0.000011                    3
333  SAF_PNBTR      8  2025     0.101520                    3
334  SAF_PNBTR      8  2026     0.000000                    3
341  SFFT_VNGR      8  2024     0.000530                    3
342  SFFT_VNGR      8  2025     0.000000                    3
360  SF_MNMKHN      8  2024     0.001818                    3
361  SF_MNMKHN      8  2025     0.000000                    3
370   SW NOGAS      8  2025     0.000211                    3
371   SW NOGAS      8  2026     0.000000                    3
521   SAF_MAYO      9  2024     0.000148                    3
522   SAF_MAYO      9  2025     0.000000                    3
533  SFFT_VNGR      9  2024     0.000149                    3
534  SFFT_VNGR      9  2025     0.000000                    3
552  SF_MNMKHN      9  2024     0.001053                    3
553  SF_MNMKHN      9  2025     0.000000                    3

                                   pct_diffs_from_each  min_pct_diff  \
33   [-0.673758865248227, -0.6166666666666667, -0.4...    -67.375887
34                                        [-1.0, -1.0]   -100.000000
53   [0.7936645962732921, 0.5113568961306306, 0.294...     29.466794
54                                        [-1.0, -1.0]   -100.000000
64                          [3.5, 0.46511627906976744]     46.511628
65                                              [-1.0]   -100.000000
75   [12.026833631484795, 0.7627693052529656, 1.575...     76.276931
76                                        [-1.0, -1.0]   -100.000000
94   [0.44434894714224316, 0.30829116387699484, 0.2...     29.718255
95                                        [-1.0, -1.0]   -100.000000
127                                [2.469250210614996]    246.925021
128                                       [-1.0, -1.0]   -100.000000
133                                       [-1.0, -1.0]   -100.000000
134                                             [-1.0]   -100.000000
164  [1.5172413793103448, 2.0000000000000004, 0.440...     44.078947
165                                             [-1.0]   -100.000000
180  [0.7780849691272693, 0.5082864290181363, 0.406...     40.647325
181                                       [-1.0, -1.0]   -100.000000
184  [-0.2839080459770115, -0.48576145274453153, -0...    -48.576145
185                                       [-1.0, -1.0]   -100.000000
202                               [0.6666666666666666]     66.666667
203                                             [-1.0]   -100.000000
206  [-0.509921071664413, -0.72117362912604, -0.371...    -72.117363
207                                             [-1.0]   -100.000000
222  [-0.8166666666666667, -0.75, -0.5217391304347826]    -81.666667
223                                             [-1.0]   -100.000000
255  [0.4411764705882354, 0.8846153846153848, 0.361...     36.111111
256                                             [-1.0]   -100.000000
262                               [2.0000000000000004]    200.000000
263                                             [-1.0]   -100.000000
264                               [0.4846743295019157]     48.467433
265                                             [-1.0]   -100.000000
266  [1.7378358750907772, 3.000707463742483, 0.5531...     55.314474
267                                             [-1.0]   -100.000000
274                                [4.666666666666667]    466.666667
275                                             [-1.0]   -100.000000
301  [0.6799999999999998, 0.9534883720930231, 0.647...     64.705882
302                                             [-1.0]   -100.000000
319            [4.873209772535804, 0.6929334628460418]     69.293346
320                                             [-1.0]   -100.000000
325                                             [-1.0]   -100.000000
326                                             [-1.0]   -100.000000
329  [-0.867579908675799, -0.8696629213483146, -0.6...    -86.966292
330  [-0.9736842105263158, -0.6666666666666666, -0....    -97.368421
333  [-0.3845329249617152, -0.3595219123505976, -0....    -45.027713
334                                             [-1.0]   -100.000000
341  [-0.26415094339622636, -0.27777777777777773, -...    -27.777778
342                                 [-1.0, -1.0, -1.0]   -100.000000
360  [-0.9179442905392584, -0.8438498618859339, -0....    -91.794429
361                                       [-1.0, -1.0]   -100.000000
370  [-0.6351351351351351, -0.5263157894736842, -0....    -63.513514
371                                             [-1.0]   -100.000000
521  [-0.9123595505617978, -0.7621951219512195, -0....    -91.235955
522                                 [-1.0, -1.0, -1.0]   -100.000000
533  [-0.7962962962962964, -0.7962962962962964, -0....    -79.629630
534                                       [-1.0, -1.0]   -100.000000
552  [-0.9095127191319576, -0.7339137821193459, -0....    -90.951272
553                                             [-1.0]   -100.000000

     max_pct_diff  is_anomaly direction  pattern_repeats
33     -47.727273        True     lower             True
34    -100.000000        True     lower             True
53      79.366460        True    higher             True
54    -100.000000        True     lower             True
64     350.000000        True    higher             True
65    -100.000000        True     lower             True
75    1202.683363        True    higher             True
76    -100.000000        True     lower             True
94      44.434895        True    higher             True
95    -100.000000        True     lower             True
127    246.925021        True    higher             True
128   -100.000000        True     lower             True
133   -100.000000        True     lower             True
134   -100.000000        True     lower             True
164    200.000000        True    higher             True
165   -100.000000        True     lower             True
180     77.808497        True    higher             True
181   -100.000000        True     lower             True
184    -27.346939        True     lower             True
185   -100.000000        True     lower             True
202     66.666667        True    higher             True
203   -100.000000        True     lower             True
206    -37.180056        True     lower             True
207   -100.000000        True     lower             True
222    -52.173913        True     lower             True
223   -100.000000        True     lower             True
255     88.461538        True    higher             True
256   -100.000000        True     lower             True
262    200.000000        True    higher             True
263   -100.000000        True     lower             True
264     48.467433        True    higher             True
265   -100.000000        True     lower             True
266    300.070746        True    higher             True
267   -100.000000        True     lower             True
274    466.666667        True    higher             True
275   -100.000000        True     lower             True
301     95.348837        True    higher             True
302   -100.000000        True     lower             True
319    487.320977        True    higher             True
320   -100.000000        True     lower             True
325   -100.000000        True     lower             True
326   -100.000000        True     lower             True
329    -64.634146        True     lower             True
330    -66.666667        True     lower             True
333    -35.952191        True     lower             True
334   -100.000000        True     lower             True
341    -26.415094        True     lower             True
342   -100.000000        True     lower             True
360    -54.082608        True     lower             True
361   -100.000000        True     lower             True
370    -34.146341        True     lower             True
371   -100.000000        True     lower             True
521    -32.758621        True     lower             True
522   -100.000000        True     lower             True
533    -71.794872        True     lower             True
534   -100.000000        True     lower             True
552    -42.051104        True     lower             True
553   -100.000000        True     lower             True

In [ ]:
# mnth = 6
# all_brand = final_df.groupby(['brand_code', 'run_month_x','month_date'])['vol_in_rum_value'].sum().reset_index()
# def detect_april_anomaly(df, brand_code, threshold=0.25, months_window=3):
#     """
#     Detect if April's vol_in_rum_value is >25% different 
#     from past 3 months & next 3 months, and if pattern repeats in last 2 years.
    
#     Parameters:
#     - df: input dataframe with 'month_date', 'vol_in_rum_value', 'run_month'
#     - brand_code: filter by this brand code
#     - threshold: 25% difference threshold
#     - months_window: number of months before and after April to compare
    
#     """
    
#     # Filter for brand and sort by month_date
#     df_brand = df[df['brand_code'] == brand_code].sort_values('month_date').copy()
    
#     if df_brand.empty:
#         return None
    
#     # Extract year and month
#     df_brand['year'] = df_brand['month_date'].dt.year
#     df_brand['month'] = df_brand['month_date'].dt.month
    
#     # Get unique years (excluding current year if incomplete)
#     years = sorted(df_brand['year'].unique())
#     current_year = years[-1]
#     past_years = [y for y in years if y < current_year][-2:]  # Last 2 years
    
#     anomalies = []
    
#     # Check each past year's April
#     for year in past_years:
#         df_year = df_brand[df_brand['year'] == year].sort_values('month_date')
        
#         # Get April data (month == 4)
#         april_data = df_year[df_year['month'] == mnth]
#         if april_data.empty:
#             continue
        
#         april_value = april_data['vol_in_rum_value'].iloc[0]
#         april_month = mnth
        
#         # Dynamically calculate past and next months
#         past_months = [(april_month - i - 1) % 12 + 1 for i in range(1,months_window+1)]
#         print(past_months)
#         next_months = [(april_month + i - 1) % 12 + 1 for i in range(1, months_window + 1)]
#         print(next_months)
        
#         # Get past and next months values
#         past_3m = df_year[df_year['month'].isin(past_months)]['vol_in_rum_value']
#         next_3m = df_year[df_year['month'].isin(next_months)]['vol_in_rum_value']
        
#         # Combine all comparison months
#         comparison_values = pd.concat([past_3m, next_3m])
        
#         if comparison_values.empty:
#             continue
        
#         # Calculate mean of comparison months
#         #mean_value = comparison_values.mean()
        
#         # Calculate percentage difference
#         pct_diffs = []
#         for comp_value in comparison_values:
#             if comp_value != 0:
#                 pct_diff = (april_value - comp_value) / comp_value
#                 pct_diffs.append(pct_diff)
        
#         # April is anomalous if it's >25% different from ALL comparison months
#         # AND all differences have the same sign (all positive or all negative)
#         if pct_diffs:
#             positive_diffs = [p for p in pct_diffs if p > 0]
#             negative_diffs = [p for p in pct_diffs if p < 0]
#             same_sign = len(positive_diffs) == len(pct_diffs) or len(negative_diffs) == len(pct_diffs)
#             is_anomaly = len([p for p in pct_diffs if abs(p) > threshold]) == len(pct_diffs) and same_sign
#         else:
#             is_anomaly = False

#         anomalies.append({
#             'brand_code': brand_code,
#             'year': year,
#             'april_value': april_value,
#             'num_months_compared': len(comparison_values),
#             'pct_diffs_from_each': pct_diffs,
#             'min_pct_diff': min(pct_diffs) * 100 if pct_diffs else None,
#             'max_pct_diff': max(pct_diffs) * 100 if pct_diffs else None,
#             'is_anomaly': is_anomaly,
#             'direction': 'higher' if april_value > comparison_values.mean() else 'lower'
#         })
    
#     # Check if pattern repeats in both years
#     if len(anomalies) == 2:
#         pattern_repeats = anomalies[0]['is_anomaly'] and anomalies[1]['is_anomaly']
#         return pd.DataFrame(anomalies), pattern_repeats
    
#     return pd.DataFrame(anomalies), False


# # Usage: Apply to each brand code
# brands = all_brand['brand_code'].unique()
# results = []

# for brand in brands:
#     df_result, repeats = detect_april_anomaly(all_brand, brand)
#     if df_result is not None and not df_result.empty:
#         df_result['pattern_repeats'] = repeats
#         results.append(df_result)


# anomaly_summary = pd.concat(results, ignore_index=True)
# print(anomaly_summary[anomaly_summary['pattern_repeats'] == True])

[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
[4, 3, 2]
[6, 7, 8]
   brand_code  year  april_value  num_months_compared  \
35  NHR-UTTAM  2024     0.000000                    6
36  NHR-UTTAM  2025     0.000063                    6

                                  pct_diffs_from_each  min_pct_diff  \
35                                             [-1.0]   -100.000000
36  [-0.9193548387096775, -0.8979591836734693, -0....    -91.935484

    max_pct_diff  is_anomaly direction  pattern_repeats
35        -100.0        True     lower             True
36         -37.5        True     lower             True

In [134]:
final_df.shape

(29328, 79)

In [373]:
final_brands = anomaly_summary[anomaly_summary['pattern_repeats'] == True].drop_duplicates(subset=['brand_code','month'])[['brand_code', 'month','direction', 'min_pct_diff', 'max_pct_diff']]
final_brands['month_different'] = 1
final_df['month'] = final_df['month_date'].dt.month
final_df = final_df.merge(final_brands[['brand_code', 'month','month_different']], on = ['brand_code','month'], how = 'left')
final_df['month_different'].fillna(0, inplace=True)
final_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,depot,platform_name,brand_code,qtr_ind_rate,vol_in_rum_value,pred_best_model,pred_value_best_model,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month_x,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,class,skipped,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value,month_different
0,blinkit_D112_718288,2024-05-31,0.048333,0.024167,0.092660,0.048333,0.000671,0.000336,0.001287,0.000671,718288,D112,blinkit,SAFF GOLD,138865.260689,0.002014,0.0,0.0,0.145,0.002014,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.100956,0.096379,0.145,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.001402,0.001338,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,5,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000,0.0
1,blinkit_D112_718288,2024-06-30,0.048333,0.024167,0.001315,0.019333,0.000671,0.000336,0.000018,0.000268,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.009374,0.005674,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000130,0.000079,0.0,0.0,0.0,0.0,0.002014,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,6,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000,0.0
2,blinkit_D112_718288,2024-07-31,0.048333,0.024167,0.003047,0.004833,0.000671,0.000336,0.000042,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.011299,0.007322,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000157,0.000102,0.0,0.0,0.0,0.0,0.000000,0.002014,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,7,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000,0.0
3,blinkit_D112_718288,2024-08-31,0.048333,0.024167,0.004675,0.004833,0.000671,0.000336,0.000065,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.012763,0.008798,0.000,0.048333,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.048333,0.000671,0.0,0.0,0.0,0.000177,0.000122,0.0,0.0,0.0,0.0,0.000000,0.000000,0.002014,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000,0.0
4,blinkit_D112_718288,2024-09-30,0.000000,0.024167,0.006517,0.004833,0.000000,0.000336,0.000090,0.000067,718288,D112,blinkit,SAFF GOLD,138865.260689,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,5.000000,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,None,Saffola Oils,0.014201,0.010185,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000197,0.000141,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,A,0,0,0,0.0,0.0,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0000,0.0000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310212,zepto_D677_810439,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000022,NaN,0.0,0.0,6,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022,0.0
310213,zepto_D677_810439,2026-07-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+1,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000022,0.0,0.0,7,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022,0.0
310214,zepto_D677_810439,2026-08-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+2,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000233,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,8,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022,0.0
310215,zepto_D677_810439,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+3,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,9,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022,0.0
310216,zepto_D677_810439,2026-10-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,810439,D677,zepto,SAF-MUSLI,315513.490535,0.000000,0.0,0.0,0.000,0.000000,2026-05-31,3.605551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-06-30,M+4,Foods,0.000000,0.000000,0.000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,NPD,0,0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,10,0.0,NaN,0.0,0,2026-06-30,0.0,0.0,0.0,0.0,0.0007,0.0007,0.000022,0.000022,0.0

In [378]:
final_df[final_df['month_date'] == '2026-09-30']['P3M_value'].sum()

31.533487973702506

In [381]:
final_df.to_csv('/data/aman_singh/acuuracy_check/all_combination_qcom_trend.csv')

In [380]:
final_df[(final_df['M month'].notna())].to_csv('/data/aman_singh/acuuracy_check/all_combination_qcom_cp_july_pred.csv')