In [1]:
import warnings
warnings.filterwarnings('ignore')

import os

import gc
import pickle

import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt

from datetime import datetime
from pandas.tseries.offsets import MonthEnd

input_table = 'TRN_DF_ECOM_OFFTAKE_CHAIN_PSKU_NEW'
month_run = '2026-09-30'
os.listdir('/data/aman_singh/acuuracy_check')

['MARICO LIMITED_swiggy_jul.xlsx',
 'Stat Demand Forecast GT_as_on_6th_July_2026.xlsb',
 'soh_data_ecom.csv',
 'anaplan_snapshots_july.xlsx',
 'qcom_chain_forecast_oct.csv',
 'combine_model+missing_forecasts_brand_asm.ipynb',
 'Alternate_export_file (2).xlsx',
 'QCOM Chain PSKU OTP Output',
 'all_combination_qcom_aug_pred.csv',
 'key_check.csv',
 'Marico Ltd._forecast_May 2026_to_Aug 2026_blinkit.csv',
 'ALL Channels Accuracy_fva.ipynb',
 'all_combination_ecom_aug_pred.csv',
 'offtakes_monthly_aggregated.csv',
 'Stat Demand Forecast MT_as_on_9th_June_2026.xlsb',
 'ecom_chain_psku_offtake_to_secondary_v6_PROD.ipynb',
 'all_combination_MT_live_aug.csv',
 'seasonality.xlsx',
 'chain_forecast live.ipynb',
 'soh_qcom_till_mar26.csv',
 'Marico_Limited_projection_july_zepto.csv',
 'Qcom_chain_fc_psku_forecast_as_on_11th_may_2026.xlsx',
 'qcom_stat_chain_forecast_acc_comparison.xlsx',
 'missing_df_gt_all.csv',
 'Marico Ltd._forecast_Jun 2026_to_Sep 2026_blinkit.csv',
 'qcom_chain_forecast_sep.csv',
 'QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku.ipynb',
 'FINAL ECOM Chain PSKU OTP',
 'qcom_chain_forecast_aug3.csv',
 'qcom_chain_forecast_all_months.csv',
 'combine_model+missing_forecasts.ipynb',
 'City Mappings QCOM.xlsb',
 'Marico_Limited_projection_may_zepto.csv',
 '.gitignore',
 "mt_channels Live Run sep'26.csv",
 'QCOM_FINAL_offtake_to_secondary_depot_psku.ipynb',
 'ecom_input_data.csv',
 'plan_actuals_df_ecom.csv',
 'SOH Data - 01 Aug.xlsx',
 'prophet_data_train_till_31_Aug_2026 (3).csv',
 'stat_fva_july.csv',
 'last_date_soh.csv',
 'stat_fva_till_june.csv',
 'fva_and_stat_accuracy_till_june.xlsx',
 'Offtakes_Chain_PSKU_ECOM.xlsx',
 'handle_missing_forecasts.ipynb',
 'Marico Ltd._forecast_Jul 2026_to_Oct 2026_blinkit.csv',
 "Daily Offtake Tracker - Aug'26 (2).xlsb",
 'qcom_primary_daily.csv',
 'ALL Channels Accuracy framework.ipynb',
 'acc_framework_june.xlsx',
 'trend_file_train_till_31_Aug_2026 (2).csv',
 'material_master_df.csv',
 'collate_offtake_heuristics_qcom_depot_psku_backtest.ipynb',
 'Stat Demand Forecast GT_as_on_6th_June_2026.xlsb',
 'trend_file_train_till_31_Aug_2026 (3).csv',
 'accuracy_framework_data_upload.ipynb',
 'Marico_Limited_projection_june_zepto.csv',
 'all_combination_MT_live_sep.csv',
 'Marico Ltd._forecast_Apr 2026_to_Jul 2026_blinkit.csv',
 'MARICO LIMITED_swiggy_aug.xlsx',
 'missing_item_to_psku_mappings2.csv',
 'qcom_chain_forecast_aug2.csv',
 'soh_qcom_daily.csv',
 'ecom_primary_daily.csv',
 'plan_actuals_ok.csv',
 'blinkit_chain_forecast2.csv',
 'Marico_Limited_projection_aug_zepto.csv',
 'Marico Ltd._forecast_Aug 2026_to_Nov 2026_blinkit.csv',
 'all_combination_GT_channel_trend.csv',
 'plan_actuals_aggregated3.csv',
 'Qcom_chain_depot_psku_2.xlsx',
 'MARICO LIMITED_swiggy_jun.xlsx',
 'plan_actuals_aggregated_qcom.csv',
 'blinkit_chain_forecast.csv',
 'primary_qcom.csv',
 'all_combination_MT_channel_trend.csv',
 'all_combination_qcom_trend.csv',
 'Ecom_chain_psku_primary_as_on_10th_june_2026.xlsx',
 'all_combination_GT_live_aug.csv',
 'Marico_Limited_projection_sep_zepto.csv',
 'chain_forecast.ipynb',
 'Ecom_chain_psku_forecast_as_on_12th_may_2026.xlsx',
 'acc_framework_july.xlsx',
 'Heuristics_all_combination_qcom_depot_psku_aug_live.xlsx',
 'Trend_qcom.csv',
 'Heuristics_all_combination_ecom_aug_live.xlsx',
 'collate.ipynb',
 'qcom_chain_forecast_sep2.csv',
 'Norms 202608.csv',
 '.git',
 'soh_base_aug_run.csv',
 'Ecom_depot_psku_forecast_as_on_10th_june_2026.xlsx',
 'QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku_backtest.ipynb',
 'missing_df_mt_all.csv',
 'offtakes_july.csv',
 'MARICO LIMITED_swiggy_sep.xlsx',
 'all_combination_ecom_trend.csv',
 'collate_offtake_heuristics_ecom_psku_new_approach_live.ipynb',
 'Heuristics_all_combination_ecom_july_live.xlsx',
 'negative_data_mesr.csv',
 "gt_channels Live Run aug'26.csv",
 'brand_month_anomaly_summary.csv',
 'prophet_data_train_till_31_Aug_2026 (2).csv',
 'Marico Ltd._forecast_Sep 2026_to_Dec 2026_blinkit.csv',
 'process_live runs_soh_files.ipynb',
 'missing_item_to_psku_mappings.csv',
 'missing_item_to_psku_mappingsswiggy.csv',
 'anaplan_snapshots_june.xlsx']

In [2]:
base_dir = '/data/aman_singh/acuuracy_check'

In [3]:
def list_all_files_in_directory(root):
    out = []

    for path, subdirs, files in os.walk(root):
        for name in files:
            out.append(os.path.join(path, name))

    return out

In [4]:
list_all_files_in_directory(base_dir)

['/data/aman_singh/acuuracy_check/MARICO LIMITED_swiggy_jul.xlsx',
 '/data/aman_singh/acuuracy_check/Stat Demand Forecast GT_as_on_6th_July_2026.xlsb',
 '/data/aman_singh/acuuracy_check/soh_data_ecom.csv',
 '/data/aman_singh/acuuracy_check/anaplan_snapshots_july.xlsx',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_oct.csv',
 '/data/aman_singh/acuuracy_check/combine_model+missing_forecasts_brand_asm.ipynb',
 '/data/aman_singh/acuuracy_check/Alternate_export_file (2).xlsx',
 '/data/aman_singh/acuuracy_check/all_combination_qcom_aug_pred.csv',
 '/data/aman_singh/acuuracy_check/key_check.csv',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_May 2026_to_Aug 2026_blinkit.csv',
 '/data/aman_singh/acuuracy_check/ALL Channels Accuracy_fva.ipynb',
 '/data/aman_singh/acuuracy_check/all_combination_ecom_aug_pred.csv',
 '/data/aman_singh/acuuracy_check/offtakes_monthly_aggregated.csv',
 '/data/aman_singh/acuuracy_check/Stat Demand Forecast MT_as_on_9th_June_2026.xlsb',
 '/data/aman_singh/acuuracy_check/ecom_chain_psku_offtake_to_secondary_v6_PROD.ipynb',
 '/data/aman_singh/acuuracy_check/all_combination_MT_live_aug.csv',
 '/data/aman_singh/acuuracy_check/seasonality.xlsx',
 '/data/aman_singh/acuuracy_check/chain_forecast live.ipynb',
 '/data/aman_singh/acuuracy_check/soh_qcom_till_mar26.csv',
 '/data/aman_singh/acuuracy_check/Marico_Limited_projection_july_zepto.csv',
 '/data/aman_singh/acuuracy_check/Qcom_chain_fc_psku_forecast_as_on_11th_may_2026.xlsx',
 '/data/aman_singh/acuuracy_check/qcom_stat_chain_forecast_acc_comparison.xlsx',
 '/data/aman_singh/acuuracy_check/missing_df_gt_all.csv',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Jun 2026_to_Sep 2026_blinkit.csv',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_sep.csv',
 '/data/aman_singh/acuuracy_check/QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku.ipynb',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_aug3.csv',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_all_months.csv',
 '/data/aman_singh/acuuracy_check/combine_model+missing_forecasts.ipynb',
 '/data/aman_singh/acuuracy_check/City Mappings QCOM.xlsb',
 '/data/aman_singh/acuuracy_check/Marico_Limited_projection_may_zepto.csv',
 '/data/aman_singh/acuuracy_check/.gitignore',
 "/data/aman_singh/acuuracy_check/mt_channels Live Run sep'26.csv",
 '/data/aman_singh/acuuracy_check/QCOM_FINAL_offtake_to_secondary_depot_psku.ipynb',
 '/data/aman_singh/acuuracy_check/ecom_input_data.csv',
 '/data/aman_singh/acuuracy_check/plan_actuals_df_ecom.csv',
 '/data/aman_singh/acuuracy_check/SOH Data - 01 Aug.xlsx',
 '/data/aman_singh/acuuracy_check/prophet_data_train_till_31_Aug_2026 (3).csv',
 '/data/aman_singh/acuuracy_check/stat_fva_july.csv',
 '/data/aman_singh/acuuracy_check/last_date_soh.csv',
 '/data/aman_singh/acuuracy_check/stat_fva_till_june.csv',
 '/data/aman_singh/acuuracy_check/fva_and_stat_accuracy_till_june.xlsx',
 '/data/aman_singh/acuuracy_check/Offtakes_Chain_PSKU_ECOM.xlsx',
 '/data/aman_singh/acuuracy_check/handle_missing_forecasts.ipynb',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Jul 2026_to_Oct 2026_blinkit.csv',
 "/data/aman_singh/acuuracy_check/Daily Offtake Tracker - Aug'26 (2).xlsb",
 '/data/aman_singh/acuuracy_check/qcom_primary_daily.csv',
 '/data/aman_singh/acuuracy_check/ALL Channels Accuracy framework.ipynb',
 '/data/aman_singh/acuuracy_check/acc_framework_june.xlsx',
 '/data/aman_singh/acuuracy_check/trend_file_train_till_31_Aug_2026 (2).csv',
 '/data/aman_singh/acuuracy_check/material_master_df.csv',
 '/data/aman_singh/acuuracy_check/collate_offtake_heuristics_qcom_depot_psku_backtest.ipynb',
 '/data/aman_singh/acuuracy_check/Stat Demand Forecast GT_as_on_6th_June_2026.xlsb',
 '/data/aman_singh/acuuracy_check/trend_file_train_till_31_Aug_2026 (3).csv',
 '/data/aman_singh/acuuracy_check/accuracy_framework_data_upload.ipynb',
 '/data/aman_singh/acuuracy_check/Marico_Limited_projection_june_zepto.csv',
 '/data/aman_singh/acuuracy_check/all_combination_MT_live_sep.csv',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Apr 2026_to_Jul 2026_blinkit.csv',
 '/data/aman_singh/acuuracy_check/MARICO LIMITED_swiggy_aug.xlsx',
 '/data/aman_singh/acuuracy_check/missing_item_to_psku_mappings2.csv',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_aug2.csv',
 '/data/aman_singh/acuuracy_check/soh_qcom_daily.csv',
 '/data/aman_singh/acuuracy_check/ecom_primary_daily.csv',
 '/data/aman_singh/acuuracy_check/plan_actuals_ok.csv',
 '/data/aman_singh/acuuracy_check/blinkit_chain_forecast2.csv',
 '/data/aman_singh/acuuracy_check/Marico_Limited_projection_aug_zepto.csv',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Aug 2026_to_Nov 2026_blinkit.csv',
 '/data/aman_singh/acuuracy_check/all_combination_GT_channel_trend.csv',
 '/data/aman_singh/acuuracy_check/plan_actuals_aggregated3.csv',
 '/data/aman_singh/acuuracy_check/Qcom_chain_depot_psku_2.xlsx',
 '/data/aman_singh/acuuracy_check/MARICO LIMITED_swiggy_jun.xlsx',
 '/data/aman_singh/acuuracy_check/plan_actuals_aggregated_qcom.csv',
 '/data/aman_singh/acuuracy_check/blinkit_chain_forecast.csv',
 '/data/aman_singh/acuuracy_check/primary_qcom.csv',
 '/data/aman_singh/acuuracy_check/all_combination_MT_channel_trend.csv',
 '/data/aman_singh/acuuracy_check/all_combination_qcom_trend.csv',
 '/data/aman_singh/acuuracy_check/Ecom_chain_psku_primary_as_on_10th_june_2026.xlsx',
 '/data/aman_singh/acuuracy_check/all_combination_GT_live_aug.csv',
 '/data/aman_singh/acuuracy_check/Marico_Limited_projection_sep_zepto.csv',
 '/data/aman_singh/acuuracy_check/chain_forecast.ipynb',
 '/data/aman_singh/acuuracy_check/Ecom_chain_psku_forecast_as_on_12th_may_2026.xlsx',
 '/data/aman_singh/acuuracy_check/acc_framework_july.xlsx',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_qcom_depot_psku_aug_live.xlsx',
 '/data/aman_singh/acuuracy_check/Trend_qcom.csv',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_ecom_aug_live.xlsx',
 '/data/aman_singh/acuuracy_check/collate.ipynb',
 '/data/aman_singh/acuuracy_check/qcom_chain_forecast_sep2.csv',
 '/data/aman_singh/acuuracy_check/Norms 202608.csv',
 '/data/aman_singh/acuuracy_check/soh_base_aug_run.csv',
 '/data/aman_singh/acuuracy_check/Ecom_depot_psku_forecast_as_on_10th_june_2026.xlsx',
 '/data/aman_singh/acuuracy_check/QCOM_NORMS_FINAL_offtake_to_secondary_chain_depot_psku_backtest.ipynb',
 '/data/aman_singh/acuuracy_check/missing_df_mt_all.csv',
 '/data/aman_singh/acuuracy_check/offtakes_july.csv',
 '/data/aman_singh/acuuracy_check/MARICO LIMITED_swiggy_sep.xlsx',
 '/data/aman_singh/acuuracy_check/all_combination_ecom_trend.csv',
 '/data/aman_singh/acuuracy_check/collate_offtake_heuristics_ecom_psku_new_approach_live.ipynb',
 '/data/aman_singh/acuuracy_check/Heuristics_all_combination_ecom_july_live.xlsx',
 '/data/aman_singh/acuuracy_check/negative_data_mesr.csv',
 "/data/aman_singh/acuuracy_check/gt_channels Live Run aug'26.csv",
 '/data/aman_singh/acuuracy_check/brand_month_anomaly_summary.csv',
 '/data/aman_singh/acuuracy_check/prophet_data_train_till_31_Aug_2026 (2).csv',
 '/data/aman_singh/acuuracy_check/Marico Ltd._forecast_Sep 2026_to_Dec 2026_blinkit.csv',
 '/data/aman_singh/acuuracy_check/process_live runs_soh_files.ipynb',
 '/data/aman_singh/acuuracy_check/missing_item_to_psku_mappings.csv',
 '/data/aman_singh/acuuracy_check/missing_item_to_psku_mappingsswiggy.csv',
 '/data/aman_singh/acuuracy_check/anaplan_snapshots_june.xlsx',
 '/data/aman_singh/acuuracy_check/QCOM Chain PSKU OTP Output/live_runs/QCOM Chain Depot PSKU Primary_live_runs_06_Aug_2026.csv',
 '/data/aman_singh/acuuracy_check/QCOM Chain PSKU OTP Output/live_runs/QCOM Depot PSKU Primary_live_runs_06_Aug_2026.csv',
 '/data/aman_singh/acuuracy_check/FINAL ECOM Chain PSKU OTP/Aug26 Live Run/ECOM Chain PSKU Primary_Aug26 Live Run.csv',
 '/data/aman_singh/acuuracy_check/FINAL ECOM Chain PSKU OTP/Aug26 Live Run/ECOM Depot PSKU Primary_Aug26 Live Run.csv',
 '/data/aman_singh/acuuracy_check/.git/index',
 '/data/aman_singh/acuuracy_check/.git/COMMIT_EDITMSG',
 '/data/aman_singh/acuuracy_check/.git/config',
 '/data/aman_singh/acuuracy_check/.git/description',
 '/data/aman_singh/acuuracy_check/.git/HEAD',
 '/data/aman_singh/acuuracy_check/.git/logs/HEAD',
 '/data/aman_singh/acuuracy_check/.git/logs/refs/heads/main',
 '/data/aman_singh/acuuracy_check/.git/logs/refs/remotes/origin/main',
 '/data/aman_singh/acuuracy_check/.git/refs/heads/main',
 '/data/aman_singh/acuuracy_check/.git/refs/remotes/origin/main',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-push.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-commit.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-rebase.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-merge-commit.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/applypatch-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/push-to-checkout.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/fsmonitor-watchman.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-receive.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/pre-applypatch.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/sendemail-validate.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/update.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/post-update.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/commit-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/hooks/prepare-commit-msg.sample',
 '/data/aman_singh/acuuracy_check/.git/info/exclude',
 '/data/aman_singh/acuuracy_check/.git/objects/0c/0a5ad57d1754105e40aa3aadbb7b6d7133b6bc',
 '/data/aman_singh/acuuracy_check/.git/objects/a2/5fd88f633e53e2d9a8857ce76cbfb65ea03bb7',
 '/data/aman_singh/acuuracy_check/.git/objects/be/94eafe3dc4aa1ebe29bf1cf408785599bb203d',
 '/data/aman_singh/acuuracy_check/.git/objects/6d/86fae873d4219eb9100c6fdc721ad7ae2dc2cf',
 '/data/aman_singh/acuuracy_check/.git/objects/e8/0496254f79aa0b30b97e03f6de7f19d5d66c31',
 '/data/aman_singh/acuuracy_check/.git/objects/ce/05967b2f73a4c5af50fb06b8f69b5decfc8281',
 '/data/aman_singh/acuuracy_check/.git/objects/30/d7f93c03c1096e63aebbd63eeffde7a0941284',
 '/data/aman_singh/acuuracy_check/.git/objects/a3/29c4f0456c378d0d9269e3952844a175aefc13',
 '/data/aman_singh/acuuracy_check/.git/objects/57/de8854f7322d07d4005302c3fd4c030f088ddd',
 '/data/aman_singh/acuuracy_check/.git/objects/0d/1eb919891a606cadf41bc5722e972577f51ce0',
 '/data/aman_singh/acuuracy_check/.git/objects/8d/80e1aec91a0f4b9df42a09acfdd7c3cab4e928',
 '/data/aman_singh/acuuracy_check/.git/objects/12/71d9fcf50665dbe0fd147cbdd7419a9294b2d7',
 '/data/aman_singh/acuuracy_check/.git/objects/0f/89b09fb7cea20acd4fa39d7d0739739c5e8233',
 '/data/aman_singh/acuuracy_check/.git/objects/19/5a1d691bd3836cb93bce2650e6477879b02e40',
 '/data/aman_singh/acuuracy_check/.git/objects/45/ae6674442ba7caff65fed1682d31435362e839',
 '/data/aman_singh/acuuracy_check/.git/objects/2f/8441152e95974a6f6e0c970362b36d281d438d',
 '/data/aman_singh/acuuracy_check/.git/objects/2f/976022fca0c83b39134055cf8cf3de996801e5',
 '/data/aman_singh/acuuracy_check/.git/objects/59/53cf28573c13727c6f8600b71b37fc7c9bab4b',
 '/data/aman_singh/acuuracy_check/.git/objects/cf/1f324ff12639a4020819bb7a8ac85b79b61c1d',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/57b9a83cbb9e854be90b3d2b60d6fe4f1a3728',
 '/data/aman_singh/acuuracy_check/.git/objects/8f/2c2cb05140164d127bbf2963da7dafd35081f9',
 '/data/aman_singh/acuuracy_check/.git/objects/3d/4dbc7eb22bbd1eb5ae4e18055da3cf143a42da',
 '/data/aman_singh/acuuracy_check/.git/objects/34/a3c77cd9f98c95e2d55bb6c4e296519eb3ccf4',
 '/data/aman_singh/acuuracy_check/.git/objects/a6/91cd1db6ff5c1432ef901fb3c125b41030627e',
 '/data/aman_singh/acuuracy_check/.git/objects/c7/8724b9ae7b98fe32213ce635ad68d3c5ae88ed',
 '/data/aman_singh/acuuracy_check/.git/objects/7e/b7779c5206691b08b6dca9718cf969968682ef',
 '/data/aman_singh/acuuracy_check/.git/objects/7e/517ef9a93427a4e681b23ba3aa087d4d851fb0',
 '/data/aman_singh/acuuracy_check/.git/objects/dd/3cd2362c53b64f7276ad9b559904fc64c061bb',
 '/data/aman_singh/acuuracy_check/.git/objects/1e/c99abf830f2a5c85f45f8fa39cf0642cbe44dc',
 '/data/aman_singh/acuuracy_check/.git/objects/56/2a11dfe35621e886e15d39330fa9bb6c3587b1',
 '/data/aman_singh/acuuracy_check/.git/objects/36/05dc3473086f8ef9ac586c93903f7680f5a40c',
 '/data/aman_singh/acuuracy_check/.git/objects/36/7917dadcc4b5a7fbed14450d727e4581b5055e',
 '/data/aman_singh/acuuracy_check/.git/objects/06/83146ba4d03242c9a74e17a995675e94b5710b',
 '/data/aman_singh/acuuracy_check/.git/objects/95/9329175634cec9f164a2a097005c4d5e383c7f',
 '/data/aman_singh/acuuracy_check/.git/objects/33/eb7ed68b19a30a1679ac9810b44f2d0dde91b4',
 '/data/aman_singh/acuuracy_check/.git/objects/88/e80a12d399c342e1b1992d5c550b3a47221abe',
 '/data/aman_singh/acuuracy_check/.git/objects/a7/fc389e01ee52c345dcee4b9af7fb28fab24579',
 '/data/aman_singh/acuuracy_check/.git/objects/f7/ae11863645092a0153ae9f3793929057224827',
 '/data/aman_singh/acuuracy_check/.git/objects/2c/a7d53fc27c836261428d01445b8b210abe82b6',
 '/data/aman_singh/acuuracy_check/.git/objects/b4/2b9e1ab8ff8628ccf55a91591d913fefd90236',
 '/data/aman_singh/acuuracy_check/.git/objects/de/4dc1cd44fcca0cfddaeebe4eb07d7f7decc975',
 '/data/aman_singh/acuuracy_check/.git/objects/23/dfffa046c844b9307c1400d16dfa0f1bf27ff2',
 '/data/aman_singh/acuuracy_check/.git/objects/b3/19b623edbc68282a8a66473fa9973099629073',
 '/data/aman_singh/acuuracy_check/.git/objects/94/4c5dee0deae38c815042bae735202aa13013c4',
 '/data/aman_singh/acuuracy_check/.git/objects/01/3cc9f3bc449dcdaf46a4f4b4778813225e9987',
 '/data/aman_singh/acuuracy_check/.git/objects/55/ab37a607dc3cb82e95153a1276393cf51356a0',
 '/data/aman_singh/acuuracy_check/.git/objects/a5/270830e67776a9c36093b3b89fee561fdecaef',
 '/data/aman_singh/acuuracy_check/.git/objects/a5/3a0a886e5dd51680bb75e3d0427612cd6c682f',
 '/data/aman_singh/acuuracy_check/.git/objects/5f/7b04891a39d56fa63a7730ecb1234448c33648',
 '/data/aman_singh/acuuracy_check/.git/objects/32/809fa6fb8f7cc5ea4995c6045a40b9ebafb46a',
 '/data/aman_singh/acuuracy_check/.git/objects/d6/aaacf693b7c9b3b0b9d165300b5f6fee85de7d',
 '/data/aman_singh/acuuracy_check/.git/objects/2b/de0128bc4ad7dedbe31a3e8bcb8ce0d2ac22b1',
 '/data/aman_singh/acuuracy_check/.git/objects/67/fc2ab927985db844ed1c632f241de34ff5023c',
 '/data/aman_singh/acuuracy_check/.git/objects/85/9b116a8d9af3af1776eabb46adb2fa97ece62d',
 '/data/aman_singh/acuuracy_check/.git/objects/3c/4617a5b82de89daae680d0c71db52e360362e2',
 '/data/aman_singh/acuuracy_check/.git/objects/e2/577184286eabb18572a2641d3fc7a99331f9d6',
 '/data/aman_singh/acuuracy_check/.git/objects/e4/2501dec1059fd0228b2659896acec5f0b6a4af',
 '/data/aman_singh/acuuracy_check/.git/objects/80/fd3de644c376de1929f57c391a54e99b616e90',
 '/data/aman_singh/acuuracy_check/.git/objects/b5/de1813bc5a147552c0980bd5dca123b690fc2a',
 '/data/aman_singh/acuuracy_check/.git/objects/df/048da83a01caa1685a25da9f4084f239a544c1',
 '/data/aman_singh/acuuracy_check/.git/objects/83/3731c157e7b563e9b98321691fae36624619c0',
 '/data/aman_singh/acuuracy_check/.git/objects/b9/2b0d4b20ebbff94b43a9fcc483aba8a87e1405',
 '/data/aman_singh/acuuracy_check/.git/objects/e9/8d1bba33fa126677903cdcdba0100cb7df57d2',
 '/data/aman_singh/acuuracy_check/.git/objects/d0/67eaa1bbdcc08f7970bf596d051bb1d336e086',
 '/data/aman_singh/acuuracy_check/.git/objects/64/884228f2c7605bc86d39f0d38cb8f7e91ca00e',
 '/data/aman_singh/acuuracy_check/.git/objects/99/35c8081bd6f6f0bcb51aaec0e2d51a73695572',
 '/data/aman_singh/acuuracy_check/.git/objects/99/7df2bfef763ce9a84af0c97ee065cabebbb83e',
 '/data/aman_singh/acuuracy_check/.git/objects/b1/3e29f362a0165cc0a42cf5c0bdaf25d494aa0b',
 '/data/aman_singh/acuuracy_check/.git/objects/e5/8935dfd70e47c65952926c332fa017c21e7d98',
 '/data/aman_singh/acuuracy_check/.git/objects/e5/e3358bf2211903f0e090c46364b35104802a2c',
 '/data/aman_singh/acuuracy_check/.git/objects/f0/00ee77e6eb664259f25b709428f490ae4e2828',
 '/data/aman_singh/acuuracy_check/.git/objects/10/0b7a2527e66b3966a37f49b9e47993866a0a8e',
 '/data/aman_singh/acuuracy_check/.git/objects/10/30ac4bedba0b1a95469abc2edd6d528ca59213',
 '/data/aman_singh/acuuracy_check/.git/objects/93/7dad62f84529776ebbd14c2b29e723450268ce']

In [5]:
def discover_channel(file_path):
    # file_path = file_path.split('/')

    # if 'ECOM' in file_path:
    #     return 'ECOM'
    # elif 'QCOM' in file_path:
    #     return 'QCOM'
    # elif 'MT' in file_path:
    #     return 'MT'
    # else:
    #     return 'Channel not found'

    return 'ECOM'

In [6]:
from maricovault.MaricoDB import MaricoSnowflake

def get_dbconnection(db_name):    

    KEY_VAULT_NAME = "prod-pwd"

    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'
    

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection


def read_qtr_ind_rate_table():
    """
    Fetch the club sku information from  DWH_SAP_INDEX_TURNOVER_MONTHWISE table.

    Return:
        qtr_ind_rate_data: pandas dataframe
        - dataframe contains all the results from the index rate table.
    """
    connection = get_dbconnection(db_name='PROD')
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=connection, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    connection.close()
    return qtr_ind_rate


dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

In [7]:
data_query = f"""
    select * from {input_table}
    where month_date >= '2023-01-01' and run_month = '{month_run}'
        
"""

offtake_df = pd.read_sql(data_query, dev_conn)
offtake_df.head()

,MONTH_DATE,PLATFORM_NAME,PARENT_MATERIAL_CODE,VOL_IN_RUM,INDEXBPM,BRAND_CODE,IMPUTED,BIG_BILLION_DAYS,BIG_BILLION_DAYS_LAG_1,BIG_BILLION_DAYS_LAG_2,BIG_BILLION_DAYS_LEAD_1,BIG_BILLION_DAYS_LEAD_2,GREAT_INDIAN_FESTIVAL,GREAT_INDIAN_FESTIVAL_LAG_1,GREAT_INDIAN_FESTIVAL_LAG_2,GREAT_INDIAN_FESTIVAL_LEAD_1,GREAT_INDIAN_FESTIVAL_LEAD_2,RATIO_LAST_YEAR,QUARTER,RUN_MONTH
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,1,0,0,0,0,1,0,NaN,3,2026-09-30
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,0,0,1,0,0,0,0,NaN,3,2026-09-30
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,0,0,0,1,0,0,0,0.0,4,2026-09-30
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,0,0,0,0,1,0,0,0.0,4,2026-09-30
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,0,0,0,0,0,0,0,0.0,4,2026-09-30

In [8]:
offtake_df.columns = offtake_df.columns.str.lower()

In [9]:
offtake_df.duplicated(
    subset=['platform_name','parent_material_code', 'month_date']).sum()

0

In [10]:
offtake_df['brand_code'] = np.where(
    ((offtake_df['parent_material_code'] == 715096) &
    (offtake_df['brand_code'] == 'CO_SO_PCP')),
    'CO_SO_FS',
    offtake_df['brand_code']
)

In [11]:
# offtake_df = offtake_df[offtake_df['platform_name'].isin(
#     ['Amazon', 'Big Basket', 'Flipkart Grocery', 'Flipkart National'])]

In [12]:
offtake_df['key'] = offtake_df[['platform_name','parent_material_code']].astype(str).agg('_'.join, axis=1)
# offtake_df.rename(columns={'realigned_psku': 'parent_material_code'}, inplace=True)
# offtake_df.drop([ 'run_month'], axis=1, inplace=True)
offtake_df['parent_material_code'] = offtake_df['parent_material_code'].astype(int)

In [13]:
offtake_df.duplicated(subset=['key', 'month_date']).sum()

0

In [14]:
(offtake_df['key'] == offtake_df[['platform_name','parent_material_code']].astype(str).agg('_'.join, axis=1)).all()

True

In [15]:
# realigned_df.to_csv('OT_data_debug.csv', index=False)

### Collate MIL

In [16]:
base_dir

'/data/aman_singh/acuuracy_check'

In [17]:
def collate_file(file_hint, extension='.csv'):
    collated_file = pd.DataFrame()

    run_path = f'{base_dir}'
    all_files = list_all_files_in_directory(run_path)

    for file_path in all_files:
        if file_hint in file_path:
            if extension == '.csv':
                print(file_path)
                read_file = pd.read_csv(file_path)
                # read_file['channel'] = discover_channel(file_path)
                read_file['run'] = 'run'
                read_file['step'] = file_path.split('/')[3]
                read_file['file_path'] = file_path

                collated_file = pd.concat(
                    [collated_file, read_file]
                )
                del read_file

    return collated_file

In [18]:
trend_file_df = collate_file('trend_file_train_till')
prophet_file_df = collate_file('prophet_data_train_till')

/data/aman_singh/acuuracy_check/trend_file_train_till_31_Aug_2026 (2).csv
/data/aman_singh/acuuracy_check/trend_file_train_till_31_Aug_2026 (3).csv
/data/aman_singh/acuuracy_check/prophet_data_train_till_31_Aug_2026 (3).csv
/data/aman_singh/acuuracy_check/prophet_data_train_till_31_Aug_2026 (2).csv

In [19]:
# forecast_train_till_file_df = collate_file('forecast_train_till_')

In [20]:
# forecast_train_till_file_df

In [21]:
trend_file_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,...,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2
0,Big Basket_715100,2023-01-31,0.000000,0.500,0.683333,0.277047,0.414000,0.000000,0.000061,0.000083,...,2026-08-31,2.107859,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN
1,Big Basket_715100,2023-02-28,0.400000,0.500,0.683333,0.447159,0.388000,0.000049,0.000061,0.000083,...,2026-08-31,2.107859,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN
2,Big Basket_715100,2023-03-31,0.400000,0.500,0.683333,0.348119,0.636000,0.000049,0.000061,0.000083,...,2026-08-31,2.107859,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN
3,Big Basket_715100,2023-04-30,0.516525,0.500,0.683333,0.503479,0.698000,0.000063,0.000061,0.000083,...,2026-08-31,2.107859,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN
4,Big Basket_715100,2023-05-31,0.577489,0.600,0.683333,0.462091,0.934000,0.000070,0.000073,0.000083,...,2026-08-31,2.107859,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28187,Amazon RK_811169,2026-12-31,68.148123,45.032,25.229333,217.169779,43.804837,0.011671,0.007712,0.004321,...,2026-08-31,1.562788,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0
28188,Amazon RK_811169,2027-01-31,60.052730,45.032,25.229333,27.816534,44.391717,0.010285,0.007712,0.004321,...,2026-08-31,1.562788,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0
28189,Amazon RK_811169,2027-02-28,57.863904,45.032,25.229333,17.475662,44.938704,0.009910,0.007712,0.004321,...,2026-08-31,1.562788,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0
28190,Amazon RK_811169,2027-03-31,51.147642,45.032,25.229333,35.288319,44.351824,0.008760,0.007712,0.004321,...,2026-08-31,1.562788,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0
28191,Amazon RK_811169,2027-04-30,68.006639,45.032,25.229333,20.845392,44.351824,0.011647,0.007712,0.004321,...,2026-08-31,1.562788,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0

In [22]:
trend_file_df.columns

Index(['key', 'month_date', 'pred_SARIMA', 'pred_p3m', 'pred_p6m',
       'pred_prophet', 'pred_rf', 'pred_value_SARIMA', 'pred_value_p3m',
       'pred_value_p6m', 'pred_value_prophet', 'pred_value_rf',
       'parent_material_code', 'platform_name', 'vol_in_rum', 'brand_code',
       'big_billion_days', 'big_billion_days_lag_1', 'big_billion_days_lag_2',
       'big_billion_days_lead_1', 'big_billion_days_lead_2', 'ratio_last_year',
       'quarter', 'qtr_ind_rate', 'vol_in_rum_value', 'vol_in_rum_treated',
       'vol_in_rum_value_treated', 'train_till', 'cov', 'run', 'step',
       'file_path', 'great_indian_festival', 'great_indian_festival_lag_1',
       'great_indian_festival_lag_2', 'great_indian_festival_lead_1',
       'great_indian_festival_lead_2'],
      dtype='object')

In [23]:
trend_file_df['platform_name'].unique()

array(['Big Basket', 'Flipkart Grocery', 'Flipkart National', 'Meesho',
       'Myntra', 'Nykaa', 'Purplle', 'Amazon RK'], dtype=object)

In [24]:
trend_file_df['month_date'] = pd.to_datetime(trend_file_df['month_date'])
prophet_file_df['month_date'] = pd.to_datetime(prophet_file_df['month_date'])

trend_file_df['train_till'] = pd.to_datetime(trend_file_df['train_till'])
prophet_file_df['train_till'] = pd.to_datetime(prophet_file_df['train_till'])

trend_file_df['run_month'] = pd.to_datetime(trend_file_df['train_till'] + MonthEnd(1))
prophet_file_df['run_month'] = pd.to_datetime(prophet_file_df['train_till'] + MonthEnd(1))

In [25]:
trend_file_df.duplicated(subset=['key', 'month_date', 'run_month']).sum(), \
prophet_file_df.duplicated(subset=['key', 'month_date', 'run_month']).sum()

(0, 0)

In [26]:
mappings = {}

for run_month in trend_file_df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings

{Timestamp('2026-09-30 00:00:00'): {Timestamp('2026-09-30 00:00:00'): 'M',
  Timestamp('2026-10-31 00:00:00'): 'M+1',
  Timestamp('2026-11-30 00:00:00'): 'M+2',
  Timestamp('2026-12-31 00:00:00'): 'M+3',
  Timestamp('2027-01-31 00:00:00'): 'M+4',
  Timestamp('2027-02-28 00:00:00'): 'M+5',
  Timestamp('2027-03-31 00:00:00'): 'M+6',
  Timestamp('2027-04-30 00:00:00'): 'M+7',
  Timestamp('2027-05-31 00:00:00'): 'M+8'}}

In [27]:
trend_file_df['M month'] = trend_file_df.apply(
    lambda x: mappings[x['run_month']].get(
        x['month_date']
    ), axis=1
)

In [28]:
trend_file_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,...,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month
0,Big Basket_715100,2023-01-31,0.000000,0.500,0.683333,0.277047,0.414000,0.000000,0.000061,0.000083,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,None
1,Big Basket_715100,2023-02-28,0.400000,0.500,0.683333,0.447159,0.388000,0.000049,0.000061,0.000083,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,None
2,Big Basket_715100,2023-03-31,0.400000,0.500,0.683333,0.348119,0.636000,0.000049,0.000061,0.000083,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,None
3,Big Basket_715100,2023-04-30,0.516525,0.500,0.683333,0.503479,0.698000,0.000063,0.000061,0.000083,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,None
4,Big Basket_715100,2023-05-31,0.577489,0.600,0.683333,0.462091,0.934000,0.000070,0.000073,0.000083,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28187,Amazon RK_811169,2026-12-31,68.148123,45.032,25.229333,217.169779,43.804837,0.011671,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3
28188,Amazon RK_811169,2027-01-31,60.052730,45.032,25.229333,27.816534,44.391717,0.010285,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4
28189,Amazon RK_811169,2027-02-28,57.863904,45.032,25.229333,17.475662,44.938704,0.009910,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5
28190,Amazon RK_811169,2027-03-31,51.147642,45.032,25.229333,35.288319,44.351824,0.008760,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6
28191,Amazon RK_811169,2027-04-30,68.006639,45.032,25.229333,20.845392,44.351824,0.011647,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7

In [29]:
trend_file_df[trend_file_df['M month'].notna()]

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,...,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month
44,Big Basket_715100,2026-09-30,0.000339,0.000,0.000000,0.045320,0.148000,4.136640e-08,0.000000,0.000000,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M
45,Big Basket_715100,2026-10-31,0.000339,0.000,0.000000,0.000000,0.052000,4.136640e-08,0.000000,0.000000,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+1
46,Big Basket_715100,2026-11-30,0.000339,0.000,0.000000,0.000000,0.062000,4.136640e-08,0.000000,0.000000,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+2
47,Big Basket_715100,2026-12-31,0.000339,0.000,0.000000,0.000000,0.060000,4.136640e-08,0.000000,0.000000,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+3
48,Big Basket_715100,2027-01-31,0.000339,0.000,0.000000,0.000000,0.010000,4.136640e-08,0.000000,0.000000,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28187,Amazon RK_811169,2026-12-31,68.148123,45.032,25.229333,217.169779,43.804837,1.167108e-02,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3
28188,Amazon RK_811169,2027-01-31,60.052730,45.032,25.229333,27.816534,44.391717,1.028466e-02,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4
28189,Amazon RK_811169,2027-02-28,57.863904,45.032,25.229333,17.475662,44.938704,9.909803e-03,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5
28190,Amazon RK_811169,2027-03-31,51.147642,45.032,25.229333,35.288319,44.351824,8.759572e-03,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6
28191,Amazon RK_811169,2027-04-30,68.006639,45.032,25.229333,20.845392,44.351824,1.164685e-02,0.007712,0.004321,...,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7

In [30]:
trend_file_df[['run_month', 'train_till']].drop_duplicates().sort_values(by=['run_month'])

   run_month train_till
0 2026-09-30 2026-08-31

In [31]:
prophet_file_df[['run_month', 'train_till']].drop_duplicates().sort_values(by=['run_month'])

   run_month train_till
0 2026-09-30 2026-08-31

In [32]:
trend_file_df['M month'].unique()

array([None, 'M', 'M+1', 'M+2', 'M+3', 'M+4', 'M+5', 'M+6', 'M+7'],
      dtype=object)

In [33]:
portfolio_query = """SELECT DISTINCT
    MATERIAL_GROUP_CODE AS BRAND_CODE,
    SAP_PORTFOLIO_NAME AS PORTFOLIO
FROM MST_MATERIAL
WHERE COMPANY_CODE = 'MIL'
  AND LATEST_RECORD_IND = '1'
  AND MATERIAL_GROUP_CODE IS NOT NULL
  AND SAP_PORTFOLIO_NAME IS NOT NULL
ORDER BY SAP_PORTFOLIO_NAME, MATERIAL_GROUP_CODE;"""
brand_md_df = pd.read_sql(portfolio_query, prod_conn)

brand_md_df.columns = brand_md_df.columns.str.lower()
brand_md_df

    brand_code     portfolio
0    BD_BDOL_M        BEARDO
1    BD_HRWX_M        BEARDO
2    BRD_BDCOL        BEARDO
3    BRD_BDOIL        BEARDO
4    BRD_BDSPR        BEARDO
..         ...           ...
316  PURSNS_GM     SKIN CARE
317  PURSNS_ML     SKIN CARE
318  TO_CL_OTG     SKIN CARE
319  TO_CL_OTM     SKIN CARE
320  PLX_TDRCN  WATER PREMIX

[321 rows x 2 columns]

In [34]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    brand_md_df,
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(trend_file_df)

In [35]:
trend_file_df['portfolio'].isna().sum()

0

In [36]:
prophet_file_df[
    ['month_date', 'key', 'run_month']
].duplicated().sum()

0

In [37]:
prophet_file_df

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,yhat_60_%ile,yhat_70_%ile,yhat_75_%ile,trend_60_%ile,...,big_billion_days_lag_2,big_billion_days_lag_2_lower,big_billion_days_lag_2_upper,big_billion_days_lead_1,big_billion_days_lead_1_lower,big_billion_days_lead_1_upper,big_billion_days_lead_2,big_billion_days_lead_2_lower,big_billion_days_lead_2_upper,run_month
0,2023-01-31,6.999279,3.666499,13.874915,6.999279,6.999279,9.841779,10.975879,11.638436,6.999279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
1,2023-02-28,7.062260,4.010215,14.064195,7.062260,7.062260,9.866562,10.809280,11.391360,7.062260,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
2,2023-03-31,7.131989,7.761451,17.241591,7.131989,7.131989,13.354994,14.483759,15.012760,7.131989,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
3,2023-04-30,7.199468,1.555820,11.180071,7.199468,7.199468,7.644643,8.557544,9.139753,7.199468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
4,2023-05-31,7.269197,3.903925,13.459261,7.269197,7.269197,9.764510,10.657385,11.194470,7.269197,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74030,2026-12-31,0.000021,-0.000756,0.000657,0.000021,0.000021,0.000103,0.000290,0.000364,0.000021,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-09-30
74031,2027-01-31,-0.000049,-0.000560,0.000914,-0.000049,-0.000049,0.000335,0.000480,0.000556,-0.000049,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-09-30
74032,2027-02-28,-0.000112,0.000167,0.001592,-0.000112,-0.000112,0.000993,0.001153,0.001243,-0.000112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-09-30
74033,2027-03-31,-0.000182,-0.000992,0.000461,-0.000182,-0.000182,-0.000106,0.000022,0.000093,-0.000182,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-09-30
74034,2027-04-30,-0.000249,-0.000930,0.000605,-0.000249,-0.000249,-0.000003,0.000141,0.000221,-0.000249,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-09-30

In [38]:
# Merge 70th percentile Prophet predictions
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    prophet_file_df[['month_date', 'key', 'run_month', 'yhat_70_%ile','yhat_60_%ile']].rename(
        columns={
            'yhat_70_%ile': 'pred_prophet_70%ile',
            'yhat_60_%ile': 'pred_prophet_60%ile'
        }
    ),
    on=['month_date', 'key', 'run_month'],
    how='left'
)
assert len(trend_file_df) == len_before_merge

In [39]:
assert trend_file_df.duplicated(
    subset=['run_month', 'month_date', 'key']
).sum() == 0

In [40]:
trend_file_df.drop('vol_in_rum', axis=1, inplace=True)

In [41]:
offtake_df.head()

,month_date,platform_name,parent_material_code,vol_in_rum,indexbpm,brand_code,imputed,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,...,big_billion_days_lead_2,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,ratio_last_year,quarter,run_month,key
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,...,0,0,0,0,1,0,NaN,3,2026-09-30,Amazon ARIPL_718288
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,...,0,1,0,0,0,0,NaN,3,2026-09-30,Amazon ARIPL_718288
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,...,0,0,1,0,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,...,0,0,0,1,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,...,0,0,0,0,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288

In [42]:
assert offtake_df.duplicated(subset=['key', 'month_date']).sum() == 0

In [43]:
offtake_df['month_date'] = pd.to_datetime(offtake_df['month_date'])
offtake_df['run_month'] = pd.to_datetime(offtake_df['run_month'])

In [44]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    offtake_df[['key', 'run_month','month_date', 'vol_in_rum']],
    on=['run_month','month_date', 'key'],
    how='left'
)
assert len(trend_file_df) == len_before_merge

In [45]:
trend_file_df.select_dtypes('number').isna().sum()

pred_SARIMA                       665
pred_p3m                            0
pred_p6m                            0
pred_prophet                    29249
pred_rf                             0
pred_value_SARIMA                 665
pred_value_p3m                      0
pred_value_p6m                      0
pred_value_prophet              29249
pred_value_rf                       0
parent_material_code                0
big_billion_days                28192
big_billion_days_lag_1          28192
big_billion_days_lag_2          28192
big_billion_days_lead_1         28192
big_billion_days_lead_2         28192
ratio_last_year                 10979
quarter                             0
qtr_ind_rate                        0
vol_in_rum_value                    0
vol_in_rum_treated                  0
vol_in_rum_value_treated            0
cov                                 0
great_indian_festival           97833
great_indian_festival_lag_1     97833
great_indian_festival_lag_2     97833
great_indian_festival_lead_1    97833
great_indian_festival_lead_2    97833
pred_prophet_70%ile             29249
pred_prophet_60%ile             29249
vol_in_rum                          0
dtype: int64

In [46]:
trend_file_df.select_dtypes('number').min().round()

pred_SARIMA                      -9983.0
pred_p3m                             0.0
pred_p6m                             0.0
pred_prophet                         0.0
pred_rf                              0.0
pred_value_SARIMA                   -2.0
pred_value_p3m                       0.0
pred_value_p6m                       0.0
pred_value_prophet                   0.0
pred_value_rf                        0.0
parent_material_code            709538.0
big_billion_days                     0.0
big_billion_days_lag_1               0.0
big_billion_days_lag_2               0.0
big_billion_days_lead_1              0.0
big_billion_days_lead_2              0.0
ratio_last_year                      0.0
quarter                              1.0
qtr_ind_rate                         0.0
vol_in_rum_value                     0.0
vol_in_rum_treated                   0.0
vol_in_rum_value_treated             0.0
cov                                  0.0
great_indian_festival                0.0
great_indian_festival_lag_1          0.0
great_indian_festival_lag_2          0.0
great_indian_festival_lead_1         0.0
great_indian_festival_lead_2         0.0
pred_prophet_70%ile             -69031.0
pred_prophet_60%ile             -71467.0
vol_in_rum                           0.0
dtype: float64

In [47]:
trend_file_df['vol_in_rum'].fillna(0, inplace=True)

In [48]:
for col in [ 'pred_prophet_70%ile','pred_prophet_60%ile', 'vol_in_rum']:
    trend_file_df[col] = trend_file_df[col].clip(lower=0)

In [49]:
trend_file_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,...,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum
0,Big Basket_715100,2023-01-31,0.000000,0.500,0.683333,0.277047,0.414000,0.000000,0.000061,0.000083,...,NaN,NaN,NaN,NaN,2026-09-30,None,SKIN CARE,0.378995,0.320915,0.4
1,Big Basket_715100,2023-02-28,0.400000,0.500,0.683333,0.447159,0.388000,0.000049,0.000061,0.000083,...,NaN,NaN,NaN,NaN,2026-09-30,None,SKIN CARE,0.552390,0.497567,0.4
2,Big Basket_715100,2023-03-31,0.400000,0.500,0.683333,0.348119,0.636000,0.000049,0.000061,0.000083,...,NaN,NaN,NaN,NaN,2026-09-30,None,SKIN CARE,0.452613,0.399174,0.7
3,Big Basket_715100,2023-04-30,0.516525,0.500,0.683333,0.503479,0.698000,0.000063,0.000061,0.000083,...,NaN,NaN,NaN,NaN,2026-09-30,None,SKIN CARE,0.612685,0.558479,0.7
4,Big Basket_715100,2023-05-31,0.577489,0.600,0.683333,0.462091,0.934000,0.000070,0.000073,0.000083,...,NaN,NaN,NaN,NaN,2026-09-30,None,SKIN CARE,0.567723,0.514688,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126020,Amazon RK_811169,2026-12-31,68.148123,45.032,25.229333,217.169779,43.804837,0.011671,0.007712,0.004321,...,0.0,0.0,0.0,0.0,2026-09-30,M+3,MALE GROOMING,218.679051,218.013277,0.0
126021,Amazon RK_811169,2027-01-31,60.052730,45.032,25.229333,27.816534,44.391717,0.010285,0.007712,0.004321,...,0.0,0.0,0.0,0.0,2026-09-30,M+4,MALE GROOMING,29.142235,28.444851,0.0
126022,Amazon RK_811169,2027-02-28,57.863904,45.032,25.229333,17.475662,44.938704,0.009910,0.007712,0.004321,...,0.0,0.0,0.0,0.0,2026-09-30,M+5,MALE GROOMING,18.745705,18.023569,0.0
126023,Amazon RK_811169,2027-03-31,51.147642,45.032,25.229333,35.288319,44.351824,0.008760,0.007712,0.004321,...,0.0,0.0,0.0,0.0,2026-09-30,M+6,MALE GROOMING,36.808766,36.108290,0.0
126024,Amazon RK_811169,2027-04-30,68.006639,45.032,25.229333,20.845392,44.351824,0.011647,0.007712,0.004321,...,0.0,0.0,0.0,0.0,2026-09-30,M+7,MALE GROOMING,22.058220,21.404589,0.0

In [50]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)

In [51]:
trend_file_df['P3M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=3, min_periods=3).mean()

trend_file_df['P6M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=6, min_periods=6).mean()

trend_file_df['LY P3M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=3, min_periods=3).mean()

trend_file_df['LY P6M'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=6, min_periods=6).mean()

In [52]:
trend_file_df['LY P3M_copy'] = trend_file_df['LY P3M'].copy()

In [53]:
trend_file_df['P3M Max'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).max()

In [54]:
trend_file_df['P3M Top 2 Mean'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sort(x)[-2:].mean(), raw=True) 

# lambda x: x.nlargest(2).mean(), raw=False

In [55]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)

In [56]:
trend_file_df['MoM P3M growth'] = (
    trend_file_df.groupby(['run_month', 'key'])['P3M']
      .pct_change() * 100
)

In [57]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
trend_file_df['MoM P3M growth_lag_1'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(1)
trend_file_df['MoM P3M growth_lag_2'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(2)

In [58]:
trend_file_df['>=20%_3M_inc_month_count'] = trend_file_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['MoM P3M growth'].shift(0)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sum(x >= 20), raw=True)

In [59]:
trend_file_df['Avg(P3M Mean, Max)'] = trend_file_df[['P3M', 'P3M Max']].mean(axis=1)

In [60]:
for col in ['P3M', 'P6M', 'LY P3M', 'P3M Max', 'P3M Top 2 Mean', 
            'MoM P3M growth', '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)',
            'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2' ]:
    # if not 'LY' in col:  'LY P6M',
    trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
    trend_file_df[col] = trend_file_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )


# for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
#     if not 'LY' in col:
#         trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
#         trend_file_df[col] = trend_file_df.groupby(['key'], as_index = True, group_keys = False)[col].apply(
#             lambda x: x.ffill()
#         )

In [61]:
for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
    trend_file_df[f'{col}_value'] = trend_file_df[col] * trend_file_df['qtr_ind_rate'] / (10 ** 7)

In [62]:
trend_file_df['vol_in_rum_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['vol_in_rum'] / (10 ** 7)
trend_file_df['pred_prophet_70%ile_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['pred_prophet_70%ile'] / (10 ** 7)
trend_file_df['pred_prophet_60%ile_value'] = trend_file_df['qtr_ind_rate'] * trend_file_df['pred_prophet_60%ile'] / (10 ** 7)

In [63]:
value_cols = [col for col in trend_file_df.columns if 'value' in col]
value_cols

['pred_value_SARIMA',
 'pred_value_p3m',
 'pred_value_p6m',
 'pred_value_prophet',
 'pred_value_rf',
 'vol_in_rum_value',
 'vol_in_rum_value_treated',
 'P3M_value',
 'P6M_value',
 'LY P3M_value',
 'LY P6M_value',
 'pred_prophet_70%ile_value',
 'pred_prophet_60%ile_value']

In [64]:
for col in value_cols:
    try:
        assert trend_file_df[col].min() >= 0
    except:
        print(col)
    

    # trend_file_df[col] = trend_file_df[col] / (10 ** 7)

pred_value_SARIMA

In [65]:
trend_file_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,...,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value
99484,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,NaN,0.4590,0.000000e+00,0.000025,0.000056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99485,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,NaN,0.3690,2.235727e-05,0.000025,0.000056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99486,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,NaN,0.9486,8.124736e-06,0.000025,0.000056,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99487,Amazon RK_718472,2024-02-29,7.076602e-01,0.51,1.125,NaN,1.4706,3.515857e-05,0.000025,0.000056,...,NaN,NaN,NaN,0.51,0.000025,NaN,NaN,NaN,NaN,NaN
99488,Amazon RK_718472,2024-03-31,8.456983e-01,0.90,1.125,NaN,2.0844,4.201670e-05,0.000045,0.000056,...,NaN,NaN,NaN,0.90,0.000045,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7457,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,NaN,0.0000,-8.050627e-316,0.000000,0.000000,...,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN
7458,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,NaN,0.0000,-1.579926e-309,0.000000,0.000000,...,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN
7459,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,NaN,0.0000,-1.151388e-315,0.000000,0.000000,...,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN
7460,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,NaN,0.0000,-1.506390e-309,0.000000,0.000000,...,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN
7461,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,NaN,0.0000,-1.463731e-315,0.000000,0.000000,...,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN

In [66]:
assert trend_file_df.duplicated(
    subset=['run_month', 'brand_code', 'key', 'month_date']
).sum() == 0

In [67]:
trend_file_df = trend_file_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
trend_file_df['LY'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(12)

trend_file_df['LLY'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(24)


trend_file_df['LY value'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(12)

trend_file_df['LLY value'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(24)


trend_file_df['OT_Value_in_Cr_lag_1'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(1)

trend_file_df['OT_Value_in_Cr_lag_2'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(2)

trend_file_df['OT_Value_in_Cr_lag_3'] = trend_file_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(3)

In [68]:
for col in ['OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2', 'OT_Value_in_Cr_lag_3']:
    # if not 'LY' in col:  'LY P6M',
    trend_file_df.loc[trend_file_df['month_date'] > trend_file_df['run_month'], [col]] = np.nan
    trend_file_df[col] = trend_file_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

In [69]:
trend_file_df.columns

Index(['key', 'month_date', 'pred_SARIMA', 'pred_p3m', 'pred_p6m',
       'pred_prophet', 'pred_rf', 'pred_value_SARIMA', 'pred_value_p3m',
       'pred_value_p6m', 'pred_value_prophet', 'pred_value_rf',
       'parent_material_code', 'platform_name', 'brand_code',
       'big_billion_days', 'big_billion_days_lag_1', 'big_billion_days_lag_2',
       'big_billion_days_lead_1', 'big_billion_days_lead_2', 'ratio_last_year',
       'quarter', 'qtr_ind_rate', 'vol_in_rum_value', 'vol_in_rum_treated',
       'vol_in_rum_value_treated', 'train_till', 'cov', 'run', 'step',
       'file_path', 'great_indian_festival', 'great_indian_festival_lag_1',
       'great_indian_festival_lag_2', 'great_indian_festival_lead_1',
       'great_indian_festival_lead_2', 'run_month', 'M month', 'portfolio',
       'pred_prophet_70%ile', 'pred_prophet_60%ile', 'vol_in_rum', 'P3M',
       'P6M', 'LY P3M', 'LY P6M', 'LY P3M_copy', 'P3M Max', 'P3M Top 2 Mean',
       'MoM P3M growth', 'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2',
       '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)', 'P3M_value',
       'P6M_value', 'LY P3M_value', 'LY P6M_value',
       'pred_prophet_70%ile_value', 'pred_prophet_60%ile_value', 'LY', 'LLY',
       'LY value', 'LLY value', 'OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2',
       'OT_Value_in_Cr_lag_3'],
      dtype='object')

In [70]:
# trend_file_df[['ASM', 'Depot', 'PSKU']] = trend_file_df['key'].str.split('_', expand=True)

In [71]:
trend_file_df.reset_index(drop=True, inplace=True)

In [72]:
trend_file_df.shape

(126025, 67)

In [73]:
trend_file_df['key'].nunique()

2892

In [74]:
# batch_info = pd.read_excel(
#     '/data/aniket/az_demand_forecasting-mil-sc/channel_wise_batch.xlsx'
# )

In [75]:
# brand_class_df = pd.read_excel(r"/data/aman_singh/acuuracy_check/Brand_Classification.xlsb")
# brand_class_df.head()

In [76]:
# brand_class_df.columns = ['brand_code', 'class']

In [77]:
# len_before_merge = len(trend_file_df)
# trend_file_df = trend_file_df.merge(
#     brand_class_df, 
#     on=['brand_code'],
#     how='left'
# )
# assert len_before_merge == len(trend_file_df)
# del len_before_merge

In [78]:
# trend_file_df['class'].isna().sum()

In [79]:
# trend_file_df['class'].unique()

missing combinations

In [80]:
# model_file = pd.read_csv("/data/aman_singh/acuuracy_check/Heuristic_QCOM_Chain_PSKU_Offtakes_live2.csv")
# model_file

In [81]:
model_file = trend_file_df.copy()

In [82]:
model_file['key'].nunique()

2892

In [83]:
run_month

Timestamp('2026-09-30 00:00:00')

In [84]:
data_query = f"""
    select * from {input_table}
    where month_date >= '2023-01-01' and run_month = '{month_run}'
        
"""
qcom_df = pd.read_sql(data_query, dev_conn)
qcom_df.head()

,MONTH_DATE,PLATFORM_NAME,PARENT_MATERIAL_CODE,VOL_IN_RUM,INDEXBPM,BRAND_CODE,IMPUTED,BIG_BILLION_DAYS,BIG_BILLION_DAYS_LAG_1,BIG_BILLION_DAYS_LAG_2,BIG_BILLION_DAYS_LEAD_1,BIG_BILLION_DAYS_LEAD_2,GREAT_INDIAN_FESTIVAL,GREAT_INDIAN_FESTIVAL_LAG_1,GREAT_INDIAN_FESTIVAL_LAG_2,GREAT_INDIAN_FESTIVAL_LEAD_1,GREAT_INDIAN_FESTIVAL_LEAD_2,RATIO_LAST_YEAR,QUARTER,RUN_MONTH
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,1,0,0,0,0,1,0,NaN,3,2026-09-30
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,0,0,1,0,0,0,0,NaN,3,2026-09-30
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,0,0,0,1,0,0,0,0.0,4,2026-09-30
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,0,0,0,0,1,0,0,0.0,4,2026-09-30
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,0,0,0,0,0,0,0,0.0,4,2026-09-30

In [85]:
qcom_df.columns = qcom_df.columns.str.lower()

In [86]:
qcom_df['key'] = qcom_df[['platform_name', 'parent_material_code']].astype(str).agg('_'.join, axis=1)

In [87]:
model_file['run_month'] = pd.to_datetime(model_file['run_month'])
model_file['month_date'] = pd.to_datetime(model_file['month_date'])

qcom_df['run_month'] = pd.to_datetime(qcom_df['run_month'])
qcom_df['month_date'] = pd.to_datetime(qcom_df['month_date'])

In [88]:
tmp_df = model_file.groupby(['key', 'run_month'])['LY'].count().reset_index()
tmp_df#.isnull().sum()
#qcom_df[~qcom_df['key'].isin(model_file['key'].unique())]
qcom_df = qcom_df.merge(tmp_df, on = ['key', 'run_month'], how = 'left')
missing_df = qcom_df[qcom_df['LY'].isna()]
missing_df

,month_date,platform_name,parent_material_code,vol_in_rum,indexbpm,brand_code,imputed,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,...,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,ratio_last_year,quarter,run_month,key,LY
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,...,0,0,0,1,0,NaN,3,2026-09-30,Amazon ARIPL_718288,NaN
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,...,1,0,0,0,0,NaN,3,2026-09-30,Amazon ARIPL_718288,NaN
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,...,0,1,0,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288,NaN
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,...,0,0,1,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288,NaN
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,...,0,0,0,0,0,0.0,4,2026-09-30,Amazon ARIPL_718288,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141752,2027-02-28,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,NaN,1,2026-09-30,Purplle_810674,NaN
141753,2027-03-31,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,NaN,1,2026-09-30,Purplle_810674,NaN
141754,2027-04-30,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0.0,2,2026-09-30,Purplle_810674,NaN
141755,2027-05-31,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0.0,2,2026-09-30,Purplle_810674,NaN
141756,2027-06-30,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,...,0,0,0,0,0,0.0,2,2026-09-30,Purplle_810674,NaN

In [89]:
missing_df['key'].nunique()

646

In [90]:
missing_df = missing_df[['key','run_month','month_date', 'platform_name', 'parent_material_code', 'brand_code',
       'vol_in_rum']]
missing_df

,key,run_month,month_date,platform_name,parent_material_code,brand_code,vol_in_rum
0,Amazon ARIPL_718288,2026-09-30,2026-08-31,Amazon ARIPL,718288,SAFF GOLD,40.992
1,Amazon ARIPL_718288,2026-09-30,2026-09-30,Amazon ARIPL,718288,SAFF GOLD,0.000
2,Amazon ARIPL_718288,2026-09-30,2026-10-31,Amazon ARIPL,718288,SAFF GOLD,0.000
3,Amazon ARIPL_718288,2026-09-30,2026-11-30,Amazon ARIPL,718288,SAFF GOLD,0.000
4,Amazon ARIPL_718288,2026-09-30,2026-12-31,Amazon ARIPL,718288,SAFF GOLD,0.000
...,...,...,...,...,...,...,...
141752,Purplle_810674,2026-09-30,2027-02-28,Purplle,810674,PA_ESS_HO,0.000
141753,Purplle_810674,2026-09-30,2027-03-31,Purplle,810674,PA_ESS_HO,0.000
141754,Purplle_810674,2026-09-30,2027-04-30,Purplle,810674,PA_ESS_HO,0.000
141755,Purplle_810674,2026-09-30,2027-05-31,Purplle,810674,PA_ESS_HO,0.000
141756,Purplle_810674,2026-09-30,2027-06-30,Purplle,810674,PA_ESS_HO,0.000

In [91]:
qtr_df = read_qtr_ind_rate_table()
qtr_df.columns = qtr_df.columns.str.lower()
qtr_df.head()

Credentials retrieved successfully for prod db.

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [92]:
len_before_merge = len(missing_df)

missing_df = missing_df.rename(columns={'material_group_code': 'brand_code'}).merge(
    qtr_df.drop('month_date', axis=1),
    on=['brand_code'],
    how='left'
)

assert len_before_merge == len(missing_df)

In [93]:
missing_df

,key,run_month,month_date,platform_name,parent_material_code,brand_code,vol_in_rum,qtr_ind_rate
0,Amazon ARIPL_718288,2026-09-30,2026-08-31,Amazon ARIPL,718288,SAFF GOLD,40.992,138865.260689
1,Amazon ARIPL_718288,2026-09-30,2026-09-30,Amazon ARIPL,718288,SAFF GOLD,0.000,138865.260689
2,Amazon ARIPL_718288,2026-09-30,2026-10-31,Amazon ARIPL,718288,SAFF GOLD,0.000,138865.260689
3,Amazon ARIPL_718288,2026-09-30,2026-11-30,Amazon ARIPL,718288,SAFF GOLD,0.000,138865.260689
4,Amazon ARIPL_718288,2026-09-30,2026-12-31,Amazon ARIPL,718288,SAFF GOLD,0.000,138865.260689
...,...,...,...,...,...,...,...,...
9943,Purplle_810674,2026-09-30,2027-02-28,Purplle,810674,PA_ESS_HO,0.000,12860.631072
9944,Purplle_810674,2026-09-30,2027-03-31,Purplle,810674,PA_ESS_HO,0.000,12860.631072
9945,Purplle_810674,2026-09-30,2027-04-30,Purplle,810674,PA_ESS_HO,0.000,12860.631072
9946,Purplle_810674,2026-09-30,2027-05-31,Purplle,810674,PA_ESS_HO,0.000,12860.631072
9947,Purplle_810674,2026-09-30,2027-06-30,Purplle,810674,PA_ESS_HO,0.000,12860.631072

In [94]:
missing_df['month_date'] = pd.to_datetime(missing_df['month_date'])
missing_df['run_month'] = pd.to_datetime(missing_df['run_month'])


mappings = {}

for run_month in missing_df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 11):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings   
missing_df['M month'] = missing_df.apply(
    lambda x: mappings[x['run_month']].get(
        x['month_date']
    ), axis=1
)


len_before_merge = len(missing_df)
missing_df = missing_df.merge(
    brand_md_df,
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(missing_df)

# Merge 70th percentile Prophet predictions

assert missing_df.duplicated(
    subset=['run_month', 'month_date', 'key']
).sum() == 0
missing_df.drop('vol_in_rum', axis=1, inplace=True)

In [95]:
missing_df['M month'].unique()

array([None, 'M', 'M+1', 'M+2', 'M+3', 'M+4', 'M+5', 'M+6', 'M+7', 'M+8',
       'M+9'], dtype=object)

In [96]:
offtake_df['run_month'] = pd.to_datetime(offtake_df['run_month'])
offtake_df['month_date'] = pd.to_datetime(offtake_df['month_date'])
assert offtake_df.duplicated(subset=['key', 'month_date']).sum() == 0
len_before_merge = len(missing_df)
missing_df = missing_df.merge(
    offtake_df[['key', 'month_date', 'vol_in_rum']],
    on=['month_date', 'key'],
    how='left'
)
assert len(missing_df) == len_before_merge

missing_df['vol_in_rum'].fillna(0, inplace=True)
for col in [ 'vol_in_rum']:
    missing_df[col] = missing_df[col].clip(lower=0)
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)

In [97]:
missing_df['P3M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=3, min_periods=1).mean()

missing_df['P6M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(1)\
                                .rolling(window=6, min_periods=3).mean()

missing_df['LY P3M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=3, min_periods=3).mean()

missing_df['LY P6M'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['vol_in_rum'].shift(13)\
                                .rolling(window=6, min_periods=6).mean()

In [98]:

missing_df['LY P3M_copy'] = missing_df['LY P3M'].copy()
missing_df['P3M Max'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).max()
missing_df['P3M Top 2 Mean'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['P3M'].shift(1)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sort(x)[-2:].mean(), raw=True) 

# lambda x: x.nlargest(2).mean(), raw=False
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['MoM P3M growth'] = (
    missing_df.groupby(['run_month', 'key'])['P3M']
      .pct_change() * 100
)
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['MoM P3M growth_lag_1'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(1)
missing_df['MoM P3M growth_lag_2'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['MoM P3M growth'].shift(2)


missing_df['>=20%_3M_inc_month_count'] = missing_df.groupby(['run_month', 'key'], as_index = False, group_keys = False)['MoM P3M growth'].shift(0)\
                                .rolling(window=3, min_periods=3).apply(lambda x: np.sum(x >= 20), raw=True) 
missing_df['Avg(P3M Mean, Max)'] = missing_df[['P3M', 'P3M Max']].mean(axis=1)
for col in ['P3M', 'P6M', 'LY P3M', 'P3M Max', 'P3M Top 2 Mean', 
            'MoM P3M growth', '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)',
            'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2' ]:
    # if not 'LY' in col:  'LY P6M',
    missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
    missing_df[col] = missing_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )


# for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
#     if not 'LY' in col:
#         missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
#         missing_df[col] = missing_df.groupby(['key'], as_index = True, group_keys = False)[col].apply(
#             lambda x: x.ffill()
#         )
# missing_df.to_csv('collate_check.csv', index=False)
for col in ['P3M', 'P6M', 'LY P3M', 'LY P6M']:
    missing_df[f'{col}_value'] = missing_df[col] * missing_df['qtr_ind_rate'] / (10 ** 7)
missing_df['vol_in_rum_value'] = missing_df['qtr_ind_rate'] * missing_df['vol_in_rum'] / (10 ** 7)
value_cols = [col for col in missing_df.columns if 'value' in col]
value_cols
for col in value_cols:
    try:
        assert missing_df[col].min() >= 0
    except:
        print(col)
    

    # missing_df[col] = missing_df[col] / (10 ** 7)
missing_df
assert missing_df.duplicated(
    subset=['run_month', 'brand_code', 'key', 'month_date']
).sum() == 0
missing_df = missing_df.sort_values(
    ['run_month', 'brand_code', 'key', 'month_date']
)
missing_df['LY'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(12)

missing_df['LLY'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum'].shift(24)


missing_df['LY value'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(12)

missing_df['LLY value'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(24)


missing_df['OT_Value_in_Cr_lag_1'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(1)

missing_df['OT_Value_in_Cr_lag_2'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(2)

missing_df['OT_Value_in_Cr_lag_3'] = missing_df.groupby(
    ['run_month', 'brand_code', 'key']
)['vol_in_rum_value'].shift(3)
for col in ['OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2', 'OT_Value_in_Cr_lag_3']:
    # if not 'LY' in col:  'LY P6M',
    missing_df.loc[missing_df['month_date'] > missing_df['run_month'], [col]] = np.nan
    missing_df[col] = missing_df.groupby(['run_month','key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

missing_df.reset_index(drop=True, inplace=True)

# brand_class_df = pd.read_excel(r"/data/aman_singh/acuuracy_check/Brand_Classification.xlsb")
# brand_class_df.head()
# brand_class_df.columns = ['brand_code', 'class']

# len_before_merge = len(missing_df)
# missing_df = missing_df.merge(
#     brand_class_df, 
#     on=['brand_code'],
#     how='left'
# )
# assert len_before_merge == len(missing_df)
# del len_before_merge
# missing_df['class'].isna().sum()
# missing_df['class'].unique()

LY P3M_value

In [99]:
pd.set_option('display.max_columns', None)

In [100]:
# missing_df[
#     # (missing_df['channel'].isin(['MT', 'QCOM'])) & 
#     # (missing_df['month_date'] > '2024-06-30') &
#     (missing_df['M month'].notna())
#     # (missing_df['class'].isin(['B', 'C']))
# ].to_csv('missing_combinations_QCOM_Chain_city_PSKU_Offtakes.csv', index=False)

In [101]:
model_file

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,NaN,0.4590,0.000000e+00,0.000025,0.000056,NaN,0.000023,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,0.000000,4,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,NaN,0.3690,2.235727e-05,0.000025,0.000056,NaN,0.000018,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,NaN,4,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000022,NaN,NaN
2,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,NaN,0.9486,8.124736e-06,0.000025,0.000056,NaN,0.000047,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,2.400000,1,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000022,NaN
3,Amazon RK_718472,2024-02-29,7.076602e-01,0.51,1.125,NaN,1.4706,3.515857e-05,0.000025,0.000056,NaN,0.000073,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,7.200000,1,496.828458,0.000080,1.62,0.000080,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.62,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.51,0.000025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000054,0.000000,0.000022
4,Amazon RK_718472,2024-03-31,8.456983e-01,0.90,1.125,NaN,2.0844,4.201670e-05,0.000045,0.000056,NaN,0.000104,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,5.294118,1,496.828458,0.000134,2.70,0.000134,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,2.70,0.90,NaN,NaN,NaN,NaN,NaN,NaN,76.470588,NaN,NaN,NaN,0.90,0.000045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000080,0.000054,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126020,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,NaN,0.0000,-8.050627e-316,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,4,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+3,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126021,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,NaN,0.0000,-1.579926e-309,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+4,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126022,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,NaN,0.0000,-1.151388e-315,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+5,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126023,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,NaN,0.0000,-1.506390e-309,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+6,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126024,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,NaN,0.0000,-1.463731e-315,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,2,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+7,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

In [102]:
model_file['skipped'] = 0
missing_df['skipped'] = 1
final_df = pd.concat([model_file,missing_df])
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped
0,Amazon RK_718472,2023-11-30,0.000000,0.51,1.125,NaN,0.4590,0.000000,0.000025,0.000056,NaN,0.000023,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,0.000000,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Amazon RK_718472,2023-12-31,0.450000,0.51,1.125,NaN,0.3690,0.000022,0.000025,0.000056,NaN,0.000018,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,NaN,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000022,NaN,NaN,0
2,Amazon RK_718472,2024-01-31,0.163532,0.51,1.125,NaN,0.9486,0.000008,0.000025,0.000056,NaN,0.000047,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,2.400000,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000022,NaN,0
3,Amazon RK_718472,2024-02-29,0.707660,0.51,1.125,NaN,1.4706,0.000035,0.000025,0.000056,NaN,0.000073,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,7.200000,1.0,496.828458,0.000080,1.62,0.000080,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.62,0.510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.51,0.000025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000054,0.000000,0.000022,0
4,Amazon RK_718472,2024-03-31,0.845698,0.90,1.125,NaN,2.0844,0.000042,0.000045,0.000056,NaN,0.000104,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,5.294118,1.0,496.828458,0.000134,2.70,0.000134,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,2.70,0.900000,NaN,NaN,NaN,NaN,NaN,NaN,76.470588,NaN,NaN,NaN,0.90,0.000045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000080,0.000054,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9943,Flipkart Grocery_811169,2027-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811169,Flipkart Grocery,SW_SGPRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1712.605337,0.000000,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+5,MALE GROOMING,NaN,NaN,0.00,53.973333,50.56,NaN,NaN,NaN,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.027731,1
9944,Flipkart Grocery_811169,2027-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811169,Flipkart Grocery,SW_SGPRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1712.605337,0.000000,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+6,MALE GROOMING,NaN,NaN,0.00,53.973333,50.56,NaN,NaN,NaN,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.027731,1
9945,Flipkart Grocery_811169,2027-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811169,Flipkart Grocery,SW_SGPRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1712.605337,0.000000,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+7,MALE GROOMING,NaN,NaN,0.00,53.973333,50.56,NaN,NaN,NaN,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,NaN,NaN,NaN,NaN,67.52,NaN,0.011564,NaN,0.000000,0.000000,0.027731,1
9946,Flipkart Grocery_811169,2027-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811169,Flipkart Grocery,SW_SGPRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1712.605337,0.000000,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+8,MALE GROOMING,NaN,NaN,0.00,53.973333,50.56,NaN,NaN,NaN,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,NaN,NaN,NaN,NaN,23.36,NaN,0.004001,NaN,0.000000,0.000000,0.027731,1
9947,Flipkart Grocery_811169,2027-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,811169,Flipkart Grocery,SW_SGPRF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1712.605337,0.000000,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+9,MALE GROOMING,NaN,NaN,0.00,53.973333,50.56,NaN,NaN,NaN,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,NaN,NaN,NaN,NaN,161.92,NaN,0.027731,NaN,0.000000,0.000000,0.027731,1

In [103]:
final_df[final_df.select_dtypes(include='number').columns] = final_df.select_dtypes(include='number').fillna(0)
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped
0,Amazon RK_718472,2023-11-30,0.000000,0.51,1.125,0.0,0.4590,0.000000,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.000000,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0
1,Amazon RK_718472,2023-12-31,0.450000,0.51,1.125,0.0,0.3690,0.000022,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.000000,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000022,0.000000,0.000000,0
2,Amazon RK_718472,2024-01-31,0.163532,0.51,1.125,0.0,0.9486,0.000008,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.400000,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000022,0.000000,0
3,Amazon RK_718472,2024-02-29,0.707660,0.51,1.125,0.0,1.4706,0.000035,0.000025,0.000056,0.0,0.000073,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,7.200000,1.0,496.828458,0.000080,1.62,0.000080,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.62,0.510000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.51,0.000025,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000054,0.000000,0.000022,0
4,Amazon RK_718472,2024-03-31,0.845698,0.90,1.125,0.0,2.0844,0.000042,0.000045,0.000056,0.0,0.000104,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,5.294118,1.0,496.828458,0.000134,2.70,0.000134,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,2.70,0.900000,0.00,0.0,0.0,0.0,0.000000,0.000000,76.470588,0.000000,0.000000,0.0,0.90,0.000045,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000080,0.000054,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9943,Flipkart Grocery_811169,2027-02-28,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.027731,1
9944,Flipkart Grocery_811169,2027-03-31,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.027731,1
9945,Flipkart Grocery_811169,2027-04-30,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,67.52,0.0,0.011564,0.0,0.000000,0.000000,0.027731,1
9946,Flipkart Grocery_811169,2027-05-31,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+8,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,23.36,0.0,0.004001,0.0,0.000000,0.000000,0.027731,1
9947,Flipkart Grocery_811169,2027-06-30,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+9,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,161.92,0.0,0.027731,0.0,0.000000,0.000000,0.027731,1

In [104]:
final_df['month_date'] = pd.to_datetime(final_df['month_date'])
final_df['run_month'] = pd.to_datetime(final_df['run_month'])
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped
0,Amazon RK_718472,2023-11-30,0.000000,0.51,1.125,0.0,0.4590,0.000000,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.000000,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0
1,Amazon RK_718472,2023-12-31,0.450000,0.51,1.125,0.0,0.3690,0.000022,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.000000,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000022,0.000000,0.000000,0
2,Amazon RK_718472,2024-01-31,0.163532,0.51,1.125,0.0,0.9486,0.000008,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.400000,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.000000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000022,0.000000,0
3,Amazon RK_718472,2024-02-29,0.707660,0.51,1.125,0.0,1.4706,0.000035,0.000025,0.000056,0.0,0.000073,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,7.200000,1.0,496.828458,0.000080,1.62,0.000080,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.62,0.510000,0.00,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.51,0.000025,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000054,0.000000,0.000022,0
4,Amazon RK_718472,2024-03-31,0.845698,0.90,1.125,0.0,2.0844,0.000042,0.000045,0.000056,0.0,0.000104,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,5.294118,1.0,496.828458,0.000134,2.70,0.000134,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,2.70,0.900000,0.00,0.0,0.0,0.0,0.000000,0.000000,76.470588,0.000000,0.000000,0.0,0.90,0.000045,0.000000,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000080,0.000054,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9943,Flipkart Grocery_811169,2027-02-28,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.027731,1
9944,Flipkart Grocery_811169,2027-03-31,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,0.00,0.0,0.000000,0.0,0.000000,0.000000,0.027731,1
9945,Flipkart Grocery_811169,2027-04-30,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,67.52,0.0,0.011564,0.0,0.000000,0.000000,0.027731,1
9946,Flipkart Grocery_811169,2027-05-31,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+8,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,23.36,0.0,0.004001,0.0,0.000000,0.000000,0.027731,1
9947,Flipkart Grocery_811169,2027-06-30,0.000000,0.00,0.000,0.0,0.0000,0.000000,0.000000,0.000000,0.0,0.000000,811169,Flipkart Grocery,SW_SGPRF,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1712.605337,0.000000,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+9,MALE GROOMING,0.0,0.0,0.00,53.973333,50.56,0.0,0.0,0.0,84.266667,73.013333,-12.607945,-26.708861,85.446009,1.0,69.12,0.009244,0.008659,0.0,0.0,0.0,0.0,161.92,0.0,0.027731,0.0,0.000000,0.000000,0.027731,1

Heuristic new approac

In [105]:
# pip install pymannkendall

identify events

In [106]:
final_df['month_date'] = pd.to_datetime(final_df['month_date'])
final_df['run_month'] = pd.to_datetime(final_df['run_month'])

In [107]:
import numpy as np 
import pandas as pd 
EVENT_MONTHS = [9, 10, 11] # Sep, Oct, Nov
def detect_event_months(df_grp):
    df_grp = df_grp.sort_values("month_date").copy()
    run_month = df_grp["run_month"].max()

    # only historical data
    hist = df_grp[df_grp["month_date"] < run_month].copy()

    # initialize
    df_grp["event_month_flag"] = 0
    df_grp["event_uplift_factor"] = 0.0

    if len(hist) < 12:
        df_grp["event_sensitive_flag"] = 0
        return df_grp

    event_sensitive = 0

    # loop year-wise
    for year in hist["month_date"].dt.year.unique():

        year_df = hist[hist["month_date"].dt.year == year]

        for _, row in year_df.iterrows():

            month = row["month_date"].month

            if month not in EVENT_MONTHS:
                continue

            curr_date = row["month_date"]

            # previous 12 months before this month
            prev_12m = hist[
                (hist["month_date"] < curr_date) &
                (hist["month_date"] >= curr_date - pd.DateOffset(months=12)) &
                (~hist["month_date"].dt.month.isin(EVENT_MONTHS))  # 
            ]

            if len(prev_12m) < 6:
                continue

            prev_12m_avg = prev_12m["vol_in_rum_value"].mean()

            if prev_12m_avg <= 0 or np.isnan(prev_12m_avg):
                continue

            uplift = row["vol_in_rum_value"] / prev_12m_avg

            if uplift > 2:
                mask = df_grp["month_date"] == curr_date
                df_grp.loc[mask, "event_month_flag"] = 1
                df_grp.loc[mask, "event_uplift_factor"] = uplift
                event_sensitive = 1

    df_grp["event_sensitive_flag"] = event_sensitive
    return df_grp

In [108]:
final_df = (
    final_df
    .groupby(
        ["platform_name", "parent_material_code", "run_month"],
        group_keys=False
    )
    .apply(detect_event_months)
)

In [109]:
final_df[(final_df['event_month_flag'] == 1) & (final_df['platform_name'] == 'Flipkart National') & ((final_df['parent_material_code'] == 718939))]

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag
83853,Flipkart National_718939,2023-09-30,115.150444,111.709333,86.266000,171.536028,176.732041,1.353521,1.313073,1.014003,2.016298,2.077374,718939,Flipkart National,SAFF ACTV,0.0,0.0,0.0,1.0,0.0,2.617885,3.0,117543.724493,2.186454,186.012000,2.186454,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,185.198916,178.205189,186.012000,111.709333,86.266000,0.000000,0.000000,0.000000,99.329333,90.655333,12.463589,21.160915,34.787470,2.0,105.519333,1.313073,1.014003,0.000000,0.000000,2.176897,2.094690,0.000,0.000,0.000000,0.000000,1.593188,0.996912,1.349120,0,1,2.251920,1
83854,Flipkart National_718939,2023-10-31,115.150444,135.454667,108.718000,346.055442,263.838097,1.353521,1.592185,1.277912,4.067665,3.101251,718939,Flipkart National,SAFF ACTV,1.0,0.0,0.0,0.0,0.0,2.498109,4.0,117543.724493,4.293919,365.304000,4.293919,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,361.233141,352.709551,365.304000,135.454667,108.718000,0.000000,0.000000,0.000000,111.709333,105.519333,21.256356,12.463589,21.160915,2.0,123.582000,1.592185,1.277912,0.000000,0.000000,4.246069,4.145879,0.000,0.000,0.000000,0.000000,2.186454,1.593188,0.996912,0,1,4.422486,1
83855,Flipkart National_718939,2023-11-30,115.150444,228.952000,164.140667,174.251399,125.617429,1.353521,2.691187,1.929371,2.048216,1.476554,718939,Flipkart National,SAFF ACTV,0.0,1.0,0.0,0.0,0.0,0.496041,4.0,117543.724493,2.220166,188.880000,2.220166,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,187.718577,180.629523,188.880000,228.952000,164.140667,0.000000,0.000000,0.000000,135.454667,123.582000,69.024815,21.256356,12.463589,2.0,182.203333,2.691187,1.929371,0.000000,0.000000,2.206514,2.123187,0.000,0.000,0.000000,0.000000,4.293919,2.186454,1.593188,0,1,2.286641,1
83865,Flipkart National_718939,2024-09-30,165.746347,115.513333,84.795333,330.841799,287.062012,1.948244,1.357787,0.996716,3.888838,3.374234,718939,Flipkart National,SAFF ACTV,1.0,0.0,0.0,1.0,0.0,1.872679,3.0,117543.724493,3.490061,296.916000,3.490061,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,344.494747,338.364965,296.916000,115.513333,84.795333,111.709333,86.266000,111.709333,99.206667,85.028667,16.437067,40.022206,31.017309,2.0,107.360000,1.357787,0.996716,1.313073,1.014003,4.049320,3.977268,186.012,0.000,2.186454,0.000000,2.056310,1.234820,0.782230,0,1,3.377611,1
83866,Flipkart National_718939,2024-10-31,293.762738,192.302667,131.576667,260.594021,283.801945,3.452997,2.260397,1.546601,3.063119,3.335914,718939,Flipkart National,SAFF ACTV,1.0,1.0,0.0,0.0,0.0,3.270130,4.0,117543.724493,2.815877,239.560000,2.815877,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,274.219153,266.852309,239.560000,192.302667,131.576667,135.454667,108.718000,135.454667,115.513333,107.360000,66.476597,16.437067,40.022206,2.0,153.908000,2.260397,1.546601,1.592185,1.277912,3.223274,3.136681,365.304,0.000,4.293919,0.000000,3.490061,2.056310,1.234820,0,1,2.725149,1
83877,Flipkart National_718939,2025-09-30,224.162488,58.683584,70.581792,298.011783,272.026706,2.634889,0.689789,0.829645,3.502941,3.197503,718939,Flipkart National,SAFF ACTV,1.0,0.0,0.0,1.0,0.0,2.992904,3.0,117543.724493,3.910201,332.659284,3.910201,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,314.037230,306.285008,332.659284,58.683584,70.581792,115.513333,84.795333,115.513333,82.480000,75.158000,-1.106741,-12.523840,-17.754607,0.0,70.581792,0.689789,0.829645,1.357787,0.996716,3.691311,3.600188,296.916,186.012,3.490061,2.186454,0.784084,0.827425,0.457856,0,1,4.159334,1
83878,Flipkart National_718939,2025-10-31,260.849149,156.586012,112.211006,271.735368,249.215492,3.066118,1.840570,1.318970,3.194079,2.929372,718939,Flipkart National,SAFF ACTV,1.0,1.0,0.0,0.0,0.0,2.073873,4.0,117543.724493,3.206438,272.786808,3.206438,2026-08-31,0.751393,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,SAFFOLA OILS,284.650010,277.455065,272.786808,156.586012,112.211006,192.302667,131.576667,192.302667,67.836000,63.588164,166.831031,-1.106741,-12.523840,1.0,112.211006,1.840570,1.318970,2.260397,1.546601,3.345882,3.261310,239.560,365.304,2.815877,4.293919,3.910201,0.784084,0.827425,0,1,3.410732,1

In [110]:
def compute_adjusted_pm(df_grp, window, column, year_shift=0):
    df_grp = df_grp.sort_values("month_date")

    run_month = df_grp["run_month"].iloc[0]

    # define cutoff
    end_date = run_month - pd.DateOffset(years=year_shift)

    # keep only eligible history (before run month & non-event)
    hist = df_grp[
        (df_grp["month_date"] < end_date) &
        (df_grp["event_month_flag"] == 0)
    ]

    if hist.empty:
        return np.nan

    # take last `window` non-event months
    hist = hist.tail(window)

    # if len(hist) < window:
    #     return np.nan   # optional, keeps behavior strict

    return hist[column].mean()

In [111]:
adj_df = final_df.groupby(
    ["platform_name", "parent_material_code", "run_month"]
).apply(
    lambda x: pd.Series({
        "P3M_adj": compute_adjusted_pm(x, 3,'vol_in_rum',0),
        "P6M_adj": compute_adjusted_pm(x, 6,'vol_in_rum',0),
        "P3M_adj_value": compute_adjusted_pm(x, 3,'vol_in_rum_value',0),
        "P6M_adj_value": compute_adjusted_pm(x, 6,'vol_in_rum_value',0)
    })
).reset_index()

final_df = final_df.merge(
    adj_df,
    on=["platform_name", "parent_material_code", "run_month"],
    how="left"
)

In [112]:
adj_ly_df = final_df.groupby(
    ["platform_name", "parent_material_code", "run_month"]
).apply(
    lambda x: pd.Series({
        "LY_P3M_adj": compute_adjusted_pm(x, 3,'vol_in_rum',year_shift=1),
        "LY_P6M_adj": compute_adjusted_pm(x, 6,'vol_in_rum', year_shift=1),
        "LY_P3M_adj_value": compute_adjusted_pm(x, 3,'vol_in_rum_value', year_shift=1),
        "LY_P6M_adj_value": compute_adjusted_pm(x, 6,"vol_in_rum_value", year_shift=1)
    })
).reset_index()

In [113]:
final_df = final_df.merge(
    adj_ly_df,
    on=["platform_name", "parent_material_code", "run_month"],
    how="left"
)
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,0.0,0.4590,0.000000e+00,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
1,Meesho_718472,2025-12-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.002119,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,42.66,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN
2,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,0.0,0.3690,2.235727e-05,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000022,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
3,Meesho_718472,2026-01-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.000456,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,9.18,42.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.66,0.002119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002119,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN
4,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,0.0,0.9486,8.124736e-06,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.4,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000022,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,0.0,0.0000,-8.050627e-316,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,4.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
135969,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,0.0,0.0000,-1.579926e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
135970,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,0.0,0.0000,-1.151388e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
135971,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,0.0,0.0000,-1.506390e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0
135972,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,0.0,0.0000,-1.463731e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0

In [114]:
qtr_df = read_qtr_ind_rate_table()
qtr_df.columns = qtr_df.columns.str.lower()
qtr_df.head()


len_before_merge = len(final_df)

final_df = final_df.merge(
    qtr_df.drop('month_date', axis=1),
    on=['brand_code'],
    how='left'
)

assert len_before_merge == len(final_df)

Credentials retrieved successfully for prod db.

In [115]:
import pandas as pd
import numpy as np
import pymannkendall as mk

def detect_trend_for_group(df_grp):
    """
    Detect final trend flag and p3m_slope_flag separately.
    Must contain 'month_date', 'vol_in_rum', 'run_month'
    """

    # ---------- 1. Sort ----------
    df_grp = df_grp.sort_values("month_date")

    # ---------- 2. Identify run_month ----------
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]

    # if no actual data → no trend
    if df_actual.empty or len(df_actual) < 4:
        return pd.Series({"trend_flag": 0, "p3m_slope_flag": 0})

    # ---------- 3. MK Trend ----------
    series = df_actual["vol_in_rum_value"].astype(float)

    try:
        mk_result = mk.original_test(series)
        if mk_result.trend == "increasing":
            mk_trend = 1
        elif mk_result.trend == "decreasing":
            mk_trend = -1
        else:
            mk_trend = 0
    except:
        mk_trend = 0

    # ---------- 4. P3M Slope ----------
    # last 4 months → take last 3 with shift
    #shifted_series = series.shift(1).dropna()

    p3m_values = series.tail(3).values
    #print(p3m_values)

    if len(p3m_values) < 3:
        slope_flag = 0
    else:
        x = np.arange(3)
        slope = np.polyfit(x, p3m_values, 1)[0]
        slope_flag = 1 if slope > 0 else (-1 if slope < 0 else 0)
        

    return pd.Series({
        "trend_flag": mk_trend,
        "p3m_slope_flag": slope_flag
    })


# ---------------------------------------------------------
# APPLY ON ENTIRE DATASET
# ---------------------------------------------------------

# trend_df = final_df.groupby(
#     ["platform_name", "parent_material_code"]
# ).apply(detect_trend_for_group).reset_index()

# trend_df = final_df[final_df['key'] == 'Zepto_721898'].groupby(
#     ["platform_name", "parent_material_code", "run_month"]
# ).apply(detect_trend_for_group).reset_index()
trend_df = final_df.groupby(
    ["platform_name", "parent_material_code", "run_month"]
).apply(detect_trend_for_group).reset_index()

In [116]:
trend_df["final_trend"] = np.where(
    (trend_df["trend_flag"] == 1) & (trend_df["p3m_slope_flag"] == 1), 1,
    np.where(
        (trend_df["trend_flag"] == -1) & (trend_df["p3m_slope_flag"] == -1), -1,
        0
    )
)
trend_df

,platform_name,parent_material_code,run_month,trend_flag,p3m_slope_flag,final_trend
0,Amazon ARIPL,718288,2026-09-30,0,0,0
1,Amazon ARIPL,718322,2026-09-30,0,0,0
2,Amazon ARIPL,718328,2026-09-30,0,0,0
3,Amazon ARIPL,718330,2026-09-30,0,0,0
4,Amazon ARIPL,718341,2026-09-30,0,0,0
...,...,...,...,...,...,...
3533,Purplle,807725,2026-09-30,-1,0,0
3534,Purplle,809042,2026-09-30,0,0,0
3535,Purplle,809250,2026-09-30,-1,-1,-1
3536,Purplle,810673,2026-09-30,0,-1,0
3537,Purplle,810674,2026-09-30,0,-1,0

## detect seasonality

In [117]:
from statsmodels.tsa.stattools import acf
import numpy as np
import pandas as pd

def detect_yearly_seasonality(df_grp, threshold=0.3):
    """
    Detects yearly seasonality using ACF at lag=12 only.
    Uses vol_in_rum as the metric.
    """
    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]
    series = df_actual["vol_in_rum"].astype(float).values

    # Need at least 18 points to compare last year vs this year
    if len(series) < 18:
        return 0

    # Compute ACF up to lag-12
    acf_vals = acf(series, nlags=12, fft=False)

    lag12_acf = acf_vals[12]

    # absolute ACF because seasonal correlation can be negative as well
    if abs(lag12_acf) >= threshold:
        return 1
    else:
        return 0
    

seasonality_df = final_df.groupby(
    ["platform_name", "brand_code", 'run_month']
).apply(detect_yearly_seasonality).reset_index(name="seasonality_flag")

seasonality_df

    platform_name brand_code  run_month  seasonality_flag
0    Amazon ARIPL  CO_SO_VCN 2026-09-30                 0
1    Amazon ARIPL  SAF-MUSLI 2026-09-30                 0
2    Amazon ARIPL  SAFF ACTV 2026-09-30                 0
3    Amazon ARIPL  SAFF GOLD 2026-09-30                 0
4    Amazon ARIPL    SAFF KO 2026-09-30                 0
..            ...        ...        ...               ...
681       Purplle  P_GOHR_SR 2026-09-30                 0
682       Purplle   SW HRGEL 2026-09-30                 0
683       Purplle   SW NOGAS 2026-09-30                 0
684       Purplle  SW STLDEO 2026-09-30                 0
685       Purplle  SW_HR_WAX 2026-09-30                 0

[686 rows x 4 columns]

In [118]:
# seasonality_df.to_csv('seasonal_ecom.csv')

In [119]:
import numpy as np
import pandas as pd

def compute_thresholds(df_grp):
    """
    df_grp MUST contain:
    - month_date
    - vol_in_rum
    - run_month

    Returns: lower_threshold, upper_threshold, mean, std
    """

    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # --- Use ONLY actual data (strictly before run month)
    df_actual = df_grp[df_grp["month_date"] < run_month]

    series = df_actual["vol_in_rum_value"].astype(float).values

    # If no real data → return zeros
    if len(series) == 0:
        return pd.Series({
            "lower_threshold": 0,
            "upper_threshold": 0,
            "mean_value": 0,
            "std_value": 0
        })

    # --- Take last 12 months OR all available
    if len(series) > 12:
        series = series[-12:]

    mean_val = np.mean(series)
    std_val = np.std(series)

    # --- SPECIAL CASE: ≤3 data points
    if len(series) <= 3:
        lower = 0.5 * mean_val
        upper = 2 * mean_val

        return pd.Series({
            "lower_threshold": lower,
            "upper_threshold": upper,
            "mean_value": mean_val,
            "std_value": std_val
        })

    # --- Normal case (std can be zero also)
    lower = max(0,mean_val - 2*std_val)
    upper = mean_val + 3*std_val

    return pd.Series({
        "lower_threshold": lower,
        "upper_threshold": upper,
        "mean_value": mean_val,
        "std_value": std_val
    })

threshold_df = final_df.groupby(
    ["platform_name", "parent_material_code", "run_month"]
).apply(compute_thresholds).reset_index()

threshold_df.head()

,platform_name,parent_material_code,run_month,lower_threshold,upper_threshold,mean_value,std_value
0,Amazon ARIPL,718288,2026-09-30,0.284618,1.138473,0.569236,0.0
1,Amazon ARIPL,718322,2026-09-30,0.141182,0.564728,0.282364,0.0
2,Amazon ARIPL,718328,2026-09-30,0.052476,0.209906,0.104953,0.0
3,Amazon ARIPL,718330,2026-09-30,0.041017,0.164066,0.082033,0.0
4,Amazon ARIPL,718341,2026-09-30,0.153835,0.615340,0.307670,0.0

In [120]:
trend_df = trend_df.merge(threshold_df, on = ['platform_name', 'parent_material_code', 'run_month'], how = 'left')
trend_df

,platform_name,parent_material_code,run_month,trend_flag,p3m_slope_flag,final_trend,lower_threshold,upper_threshold,mean_value,std_value
0,Amazon ARIPL,718288,2026-09-30,0,0,0,0.284618,1.138473,0.569236,0.000000
1,Amazon ARIPL,718322,2026-09-30,0,0,0,0.141182,0.564728,0.282364,0.000000
2,Amazon ARIPL,718328,2026-09-30,0,0,0,0.052476,0.209906,0.104953,0.000000
3,Amazon ARIPL,718330,2026-09-30,0,0,0,0.041017,0.164066,0.082033,0.000000
4,Amazon ARIPL,718341,2026-09-30,0,0,0,0.153835,0.615340,0.307670,0.000000
...,...,...,...,...,...,...,...,...,...,...
3533,Purplle,807725,2026-09-30,-1,0,0,0.000000,0.000000,0.000000,0.000000
3534,Purplle,809042,2026-09-30,0,0,0,0.000000,0.000000,0.000000,0.000000
3535,Purplle,809250,2026-09-30,-1,-1,-1,0.000000,0.000659,0.000186,0.000158
3536,Purplle,810673,2026-09-30,0,-1,0,0.000000,0.000300,0.000105,0.000065
3537,Purplle,810674,2026-09-30,0,-1,0,0.000000,0.000394,0.000069,0.000108

In [121]:
# trend_df.to_csv('t_s_t_df_ecom.csv')

In [122]:
final_df = final_df.merge(seasonality_df, on = ["platform_name", "brand_code", 'run_month'], how = 'left')
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,0.0,0.4590,0.000000e+00,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0
1,Meesho_718472,2025-12-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.002119,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,42.66,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN,496.828458,0
2,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,0.0,0.3690,2.235727e-05,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000022,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0
3,Meesho_718472,2026-01-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.000456,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,9.18,42.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.66,0.002119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002119,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN,496.828458,0
4,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,0.0,0.9486,8.124736e-06,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.4,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000022,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,0.0,0.0000,-8.050627e-316,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,4.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0
135969,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,0.0,0.0000,-1.579926e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0
135970,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,0.0,0.0000,-1.151388e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0
135971,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,0.0,0.0000,-1.506390e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0
135972,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,0.0,0.0000,-1.463731e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0

In [123]:
trend_df.columns

Index(['platform_name', 'parent_material_code', 'run_month', 'trend_flag',
       'p3m_slope_flag', 'final_trend', 'lower_threshold', 'upper_threshold',
       'mean_value', 'std_value'],
      dtype='object')

In [124]:
final_df = final_df.merge(trend_df[['platform_name', 'parent_material_code', 'run_month',
                                    'final_trend','lower_threshold', 'upper_threshold']], on = ["platform_name", "parent_material_code", 'run_month'], how = 'left')
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,0.0,0.4590,0.000000e+00,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
1,Meesho_718472,2025-12-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.002119,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,42.66,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN,496.828458,0,0,0.0,0.002273
2,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,0.0,0.3690,2.235727e-05,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000022,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
3,Meesho_718472,2026-01-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.000456,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,9.18,42.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.66,0.002119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002119,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,NaN,NaN,NaN,NaN,496.828458,0,0,0.0,0.002273
4,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,0.0,0.9486,8.124736e-06,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.4,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000022,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,0.0,0.0000,-8.050627e-316,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,4.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135969,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,0.0,0.0000,-1.579926e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135970,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,0.0,0.0000,-1.151388e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135971,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,0.0,0.0000,-1.506390e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135972,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,0.0,0.0000,-1.463731e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000

In [125]:
final_df[final_df.select_dtypes(include='number').columns] = final_df.select_dtypes(include='number').fillna(0)
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,0.0,0.4590,0.000000e+00,0.000025,0.000056,0.0,0.000023,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.45,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
1,Meesho_718472,2025-12-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.002119,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,42.66,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.002273
2,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,0.0,0.3690,2.235727e-05,0.000025,0.000056,0.0,0.000018,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,4.0,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000022,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
3,Meesho_718472,2026-01-31,0.000000e+00,0.00,0.000,0.0,0.0000,0.000000e+00,0.000000,0.000000,0.0,0.000000,718472,Meesho,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,496.828458,0.000456,0.00,0.000000,NaT,0.000000,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,9.18,42.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,42.66,0.002119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002119,0.000000,0.0,1,0,0.0,0,0.0,0.63,0.0,0.000031,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.002273
4,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,0.0,0.9486,8.124736e-06,0.000025,0.000056,0.0,0.000047,718472,Amazon RK,ADV-AHO-R,0.0,0.0,0.0,0.0,0.0,2.4,1.0,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,0.0,0.0,1.08,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000022,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,496.828458,0,0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,0.0,0.0000,-8.050627e-316,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,4.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+3,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135969,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,0.0,0.0000,-1.579926e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+4,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135970,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,0.0,0.0000,-1.151388e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+5,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135971,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,0.0,0.0000,-1.506390e-309,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+6,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000
135972,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,0.0,0.0000,-1.463731e-315,0.000000,0.000000,0.0,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,0.0,2.0,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,M+7,HEALTH & HYGIENE,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.0,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0,0,0.0,0,0.0,0.00,0.0,0.000000,0.0,0.0,0.0,0.0,100.000000,0,0,0.0,0.000000

In [126]:
final_df.drop(columns = ['big_billion_days', 'big_billion_days_lag_1', 'big_billion_days_lag_2',
       'big_billion_days_lead_1', 'big_billion_days_lead_2', 'great_indian_festival',
       'great_indian_festival_lag_1', 'great_indian_festival_lag_2',
       'great_indian_festival_lead_1', 'great_indian_festival_lead_2'], inplace = True)

In [127]:
final_df.columns

Index(['key', 'month_date', 'pred_SARIMA', 'pred_p3m', 'pred_p6m',
       'pred_prophet', 'pred_rf', 'pred_value_SARIMA', 'pred_value_p3m',
       'pred_value_p6m', 'pred_value_prophet', 'pred_value_rf',
       'parent_material_code', 'platform_name', 'brand_code',
       'ratio_last_year', 'quarter', 'qtr_ind_rate_x', 'vol_in_rum_value',
       'vol_in_rum_treated', 'vol_in_rum_value_treated', 'train_till', 'cov',
       'run', 'step', 'file_path', 'run_month', 'M month', 'portfolio',
       'pred_prophet_70%ile', 'pred_prophet_60%ile', 'vol_in_rum', 'P3M',
       'P6M', 'LY P3M', 'LY P6M', 'LY P3M_copy', 'P3M Max', 'P3M Top 2 Mean',
       'MoM P3M growth', 'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2',
       '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)', 'P3M_value',
       'P6M_value', 'LY P3M_value', 'LY P6M_value',
       'pred_prophet_70%ile_value', 'pred_prophet_60%ile_value', 'LY', 'LLY',
       'LY value', 'LLY value', 'OT_Value_in_Cr_lag_1', 'OT_Value_in_Cr_lag_2',
       'OT_Value_in_Cr_lag_3', 'skipped', 'event_month_flag',
       'event_uplift_factor', 'event_sensitive_flag', 'P3M_adj', 'P6M_adj',
       'P3M_adj_value', 'P6M_adj_value', 'LY_P3M_adj', 'LY_P6M_adj',
       'LY_P3M_adj_value', 'LY_P6M_adj_value', 'qtr_ind_rate_y',
       'seasonality_flag', 'final_trend', 'lower_threshold',
       'upper_threshold'],
      dtype='object')

In [128]:
missing_df['LY P3M'].sum()

0.0

In [129]:
final_df = final_df.sort_values(['key', 'month_date'])

# base LY


# LY lags
final_df['ly_lag1_value'] = (
    final_df
    .groupby(['key'])['vol_in_rum_value']
    .shift(13)
)

final_df['ly_lag2_value'] = (
    final_df
    .groupby(['key'])['vol_in_rum_value']
    .shift(14)
)

# LY leads
final_df['ly_lead1_value'] = (
    final_df
    .groupby(['key'])['vol_in_rum_value']
    .shift(11)
)

final_df['ly_lead2_value'] = (
    final_df
    .groupby(['key'])['vol_in_rum_value']
    .shift(10)
)

In [130]:
final_df[final_df['month_date'] == '2026-08-31']['P3M_value'].sum()

40.83999553258664

In [131]:
brand_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'brand')
brand_seas.columns = brand_seas.columns.str.lower()
brand_seas.rename(columns={'brand':'brand_code', 'months_num':'month', 'flag':'is_seasonal_month'}, inplace=True)

final_df['month_date'] = pd.to_datetime(final_df['month_date'])
final_df['month'] = final_df['month_date'].dt.month
final_df = final_df.merge(brand_seas, on = ['brand_code', 'month'], how = 'left')
final_df['is_seasonal_month'].fillna(0, inplace=True)

psku_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'psku')
psku_seas.columns = psku_seas.columns.str.lower()
psku_seas.rename(columns={'months_num':'month', 'flag':'is_seasonal_month_psku'}, inplace=True)

final_df = final_df.merge(psku_seas[['parent_material_code', 'month','is_seasonal_month_psku']], on = ['parent_material_code', 'month'], how = 'left')
final_df['is_seasonal_month_psku'].fillna(0, inplace=True)
final_df['final_seasonal_month'] = np.where(
    (final_df['is_seasonal_month'] == 1) | (final_df['is_seasonal_month_psku'] == 1), 1, 0
)

In [132]:
final_df['run_month'] = pd.to_datetime(final_df['run_month'])
def compute_adjusted_pm(df_grp, window, column, year_shift=0):
    df_grp = df_grp.sort_values("month_date")

    run_month = df_grp["run_month"].iloc[0]

    # define cutoff
    end_date = run_month - pd.DateOffset(years=year_shift)

    # keep only eligible history (before run month & non-event)
    hist = df_grp[
        (df_grp["month_date"] < end_date) &
        (df_grp["final_seasonal_month"] == 0)
    ]

    if hist.empty:
        return np.nan

    # take last `window` non-event months
    hist = hist.tail(window)

    # if len(hist) < window:
    #     return np.nan   # optional, keeps behavior strict

    return hist[column].mean()

adj_df = final_df.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "P3M_non_seasonal": compute_adjusted_pm(x, 3,'vol_in_rum',0),
        "P6M_non_seasonal": compute_adjusted_pm(x, 6,'vol_in_rum',0),
        "P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'vol_in_rum_value',0),
        "P6M_non_seasonal_value": compute_adjusted_pm(x, 6,'vol_in_rum_value',0)
    })
).reset_index()
adj_df


adj_ly_df = final_df.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "LY_P3M_non_seasonal": compute_adjusted_pm(x, 3,'vol_in_rum',year_shift=1),
        "LY_P6M_non_seasonal": compute_adjusted_pm(x, 6,'vol_in_rum', year_shift=1),
        "LY_P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'vol_in_rum_value', year_shift=1),
        "LY_P6M_non_seasonal_value": compute_adjusted_pm(x, 6,"vol_in_rum_value", year_shift=1)
    })
).reset_index()

adj_df = adj_df.merge(adj_ly_df, on = ['key', 'run_month'], how = 'left')
#adj_df[adj_df['key'] == 'reliance_b2c_2_haryana_718488']
adj_df

,key,run_month,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,Amazon ARIPL_718288,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
1,Amazon ARIPL_718322,2026-09-30,16.725000,16.725000,0.282364,0.282364,NaN,NaN,NaN,NaN
2,Amazon ARIPL_718328,2026-09-30,8.488800,8.488800,0.104953,0.104953,NaN,NaN,NaN,NaN
3,Amazon ARIPL_718330,2026-09-30,6.635000,6.635000,0.082033,0.082033,NaN,NaN,NaN,NaN
4,Amazon ARIPL_718341,2026-09-30,22.156000,22.156000,0.307670,0.307670,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3533,Purplle_807725,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.000,0.00000,0.000000,0.000000
3534,Purplle_809042,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.900,0.90000,0.000033,0.000033
3535,Purplle_809250,2026-09-30,0.000633,0.000700,0.000183,0.000202,0.001,0.00125,0.000289,0.000362
3536,Purplle_810673,2026-09-30,0.074667,0.074667,0.000096,0.000096,NaN,NaN,NaN,NaN
3537,Purplle_810674,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN

In [133]:
final_df.shape

(135973, 83)

In [134]:
#adj_df.to_csv('seasonal_p3m_qcom.csv', index=False)
#all[all['month_date'].isin(['2025-11-30','2025-12-31','2026-01-31'])].groupby(['key','run_month','month_date','final_seasonal_month'])['vol_in_rum'].sum().reset_index().to_csv('seasonal_month_check.csv', index=False)
final_df = final_df.merge(
    adj_df,
    on=['key'],
    how="left"
)
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month_x,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,Amazon ARIPL_718288,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.569236,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,None,SAFFOLA OILS,0.0,0.0,40.992,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
1,Amazon ARIPL_718288,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
2,Amazon ARIPL_718288,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+1,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,10,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
3,Amazon ARIPL_718288,2026-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+2,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,11,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
4,Amazon ARIPL_718288,2026-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+3,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,12,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Purplle_810674,2027-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+5,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.224,0.0,0.000288,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,NaN,NaN,0.000180,0.000000,2,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135969,Purplle_810674,2027-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+6,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.140,0.0,0.000180,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000288,NaN,0.000000,0.000000,3,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135970,Purplle_810674,2027-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+7,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000180,0.000288,0.000000,0.000000,4,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135971,Purplle_810674,2027-05-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+8,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.121333,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000180,0.000000,0.000018,5,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135972,Purplle_810674,2027-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+9,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.046667,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000000,0.000018,0.000000,6,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN

In [135]:
final_df.rename(columns = {"run_month_x":'run_month'}, inplace = True)

In [136]:
all_brand = final_df.groupby(['brand_code', 'run_month','month_date'])['vol_in_rum_value'].sum().reset_index()
all_brand

     brand_code  run_month month_date  vol_in_rum_value
0     ADV-AHO-R 2026-09-30 2023-01-31          0.383727
1     ADV-AHO-R 2026-09-30 2023-02-28          0.299053
2     ADV-AHO-R 2026-09-30 2023-03-31          0.283299
3     ADV-AHO-R 2026-09-30 2023-04-30          0.269135
4     ADV-AHO-R 2026-09-30 2023-05-31          0.242577
...         ...        ...        ...               ...
5923  VEG_CLEAN 2026-09-30 2026-12-31          0.000000
5924  VEG_CLEAN 2026-09-30 2027-01-31          0.000000
5925  VEG_CLEAN 2026-09-30 2027-02-28          0.000000
5926  VEG_CLEAN 2026-09-30 2027-03-31          0.000000
5927  VEG_CLEAN 2026-09-30 2027-04-30          0.000000

[5928 rows x 4 columns]

In [137]:
all_brand.dtypes

brand_code                  object
run_month           datetime64[ns]
month_date          datetime64[ns]
vol_in_rum_value           float64
dtype: object

In [144]:
import pandas as pd


def detect_month_anomaly(
    df,
    brand_code,
    threshold=0.25,
    months_window=3,
    future_months=4
):
    """
    Logic:

    1. Get run_month dynamically.
    2. Analyze the next 4 months after run_month.
    3. For each future month:
         - Look at that month's value in Last Year (LY)
         - Compare it with the 3 months immediately preceding
           the run_month in LY.
    4. Do the exact same comparison for 2 Years Ago.
    5. A future month is finalized as an anomaly only when
       BOTH LY and 2Y-ago show the anomaly.
    6. For a given year, all_df 3 percentage differences must:
         - exceed 25%
         - have the same direction
    """

    # =========================================================
    # 1. Filter brand
    # =========================================================

    df_brand = df[
        df['brand_code'] == brand_code
    ].copy()

    if df_brand.empty:
        return None, False

    # =========================================================
    # 2. Convert dates
    # =========================================================

    df_brand['month_date'] = pd.to_datetime(
        df_brand['month_date']
    )

    df_brand['run_month'] = pd.to_datetime(
        df_brand['run_month']
    )

    # Normalize month_date to month-end so that
    # comparisons work consistently.
    df_brand['month_date'] = (
        df_brand['month_date']
        + pd.offsets.MonthEnd(0)
    )

    # =========================================================
    # 3. Determine run month dynamically
    # =========================================================

    run_month = df_brand['run_month'].max()

    run_month = (
        pd.Timestamp(run_month)
        + pd.offsets.MonthEnd(0)
    )

    # =========================================================
    # 4. Determine next 4 months
    # =========================================================

    target_dates = [
        run_month + pd.DateOffset(months=i)
        for i in range(1, future_months + 1)
    ]

    # Example:
    #
    # run_month = Sep 2026
    #
    # target_dates:
    # Oct 2026
    # Nov 2026
    # Dec 2026
    # Jan 2027

    # =========================================================
    # 5. Historical years
    # =========================================================

    # For each target month we evaluate:
    #
    # LY
    # 2Y ago
    #
    # Example:
    #
    # Oct 2026
    #   -> Oct 2025
    #   -> Oct 2024

    historical_offsets = [1, 2]

    results = []

    # =========================================================
    # 6. Process each future month
    # =========================================================

    for target_date in target_dates:

        year_results = {}

        # -----------------------------------------------------
        # For LY and 2Y ago
        # -----------------------------------------------------

        for year_offset in historical_offsets:

            # -------------------------------------------------
            # Target historical date
            # -------------------------------------------------

            historical_target_date = (
                target_date
                - pd.DateOffset(years=year_offset)
                + pd.offsets.MonthEnd(0)
            )
            print('historical_target_date',historical_target_date)

            # -------------------------------------------------
            # Fixed comparison months
            #
            # These are based on the run month.
            #
            # Example:
            #
            # run_month = Sep 2026
            #
            # LY:
            # target = Oct 2025
            # comparison = Jul, Jun, May 2025
            #
            # 2Y:
            # target = Oct 2024
            # comparison = Jul, Jun, May 2024
            # -------------------------------------------------

            comparison_dates = [
                (
                    run_month
                    - pd.DateOffset(months=i)
                    - pd.DateOffset(years=year_offset)
                    + pd.offsets.MonthEnd(0)
                )
                for i in range(1, months_window + 1)
            ]

            # -------------------------------------------------
            # Get target value
            # -------------------------------------------------

            target_value_series = df_brand.loc[
                df_brand['month_date'] == historical_target_date,
                'vol_in_rum_value'
            ]

            if target_value_series.empty:
                year_results[year_offset] = None
                continue

            target_value = target_value_series.iloc[0]

            # -------------------------------------------------
            # Get comparison values
            # -------------------------------------------------

            comparison_values = []

            missing_comparison = False

            for comparison_date in comparison_dates:

                value_series = df_brand.loc[
                    df_brand['month_date'] == comparison_date,
                    'vol_in_rum_value'
                ]

                if value_series.empty:
                    missing_comparison = True
                    break

                comparison_values.append(
                    value_series.iloc[0]
                )

            if missing_comparison:
                year_results[year_offset] = None
                continue

            # -------------------------------------------------
            # Calculate percentage differences
            # -------------------------------------------------

            pct_diffs = []

            for comparison_value in comparison_values:

                if comparison_value == 0:
                    continue

                pct_diff = (
                    (target_value - comparison_value)
                    / comparison_value
                )

                pct_diffs.append(pct_diff)

            # Need all_df 3 comparisons
            if len(pct_diffs) != months_window:

                year_results[year_offset] = None
                continue

            # -------------------------------------------------
            # Check same direction
            # -------------------------------------------------

            all_positive = all(
                p > 0 for p in pct_diffs
            )

            all_negative = all(
                p < 0 for p in pct_diffs
            )

            same_direction = (
                all_positive or all_negative
            )

            # -------------------------------------------------
            # Check threshold
            # -------------------------------------------------

            all_above_threshold = all(
                abs(p) > threshold
                for p in pct_diffs
            )

            # -------------------------------------------------
            # Final anomaly for this historical year
            # -------------------------------------------------

            is_anomaly = (
                same_direction
                and all_above_threshold
            )

            direction = None

            if all_positive:
                direction = 'higher'

            elif all_negative:
                direction = 'lower'

            # -------------------------------------------------
            # Store year result
            # -------------------------------------------------

            year_results[year_offset] = {
                'historical_target_date': historical_target_date,
                'target_value': target_value,

                'comparison_dates': comparison_dates,
                'comparison_values': comparison_values,

                'pct_diffs': pct_diffs,

                'min_pct_diff': min(pct_diffs) * 100,
                'max_pct_diff': max(pct_diffs) * 100,

                'same_direction': same_direction,
                'all_above_threshold': all_above_threshold,

                'is_anomaly': is_anomaly,
                'direction': direction
            }

        # =====================================================
        # 7. Final anomaly requires BOTH years
        # =====================================================

        ly_result = year_results.get(1)
        two_year_result = year_results.get(2)

        pattern_repeats = (
            ly_result is not None
            and two_year_result is not None
            and ly_result['is_anomaly']
            and two_year_result['is_anomaly']
        )

        # =====================================================
        # 8. Store final result
        # =====================================================

        row = {
            'brand_code': brand_code,

            'run_month': run_month,

            'target_month': target_date,

            'target_year': target_date.year,

            # -----------------------------
            # Last Year
            # -----------------------------

            'ly_target_date': (
                ly_result['historical_target_date']
                if ly_result else None
            ),

            'ly_target_value': (
                ly_result['target_value']
                if ly_result else None
            ),

            'ly_comparison_dates': (
                ly_result['comparison_dates']
                if ly_result else None
            ),

            'ly_comparison_values': (
                ly_result['comparison_values']
                if ly_result else None
            ),

            'ly_pct_diffs': (
                ly_result['pct_diffs']
                if ly_result else None
            ),

            'ly_min_pct_diff': (
                ly_result['min_pct_diff']
                if ly_result else None
            ),

            'ly_max_pct_diff': (
                ly_result['max_pct_diff']
                if ly_result else None
            ),

            'ly_direction': (
                ly_result['direction']
                if ly_result else None
            ),

            'ly_is_anomaly': (
                ly_result['is_anomaly']
                if ly_result else False
            ),

            # -----------------------------
            # 2 Years Ago
            # -----------------------------

            'two_year_target_date': (
                two_year_result['historical_target_date']
                if two_year_result else None
            ),

            'two_year_target_value': (
                two_year_result['target_value']
                if two_year_result else None
            ),

            'two_year_comparison_dates': (
                two_year_result['comparison_dates']
                if two_year_result else None
            ),

            'two_year_comparison_values': (
                two_year_result['comparison_values']
                if two_year_result else None
            ),

            'two_year_pct_diffs': (
                two_year_result['pct_diffs']
                if two_year_result else None
            ),

            'two_year_min_pct_diff': (
                two_year_result['min_pct_diff']
                if two_year_result else None
            ),

            'two_year_max_pct_diff': (
                two_year_result['max_pct_diff']
                if two_year_result else None
            ),

            'two_year_direction': (
                two_year_result['direction']
                if two_year_result else None
            ),

            'two_year_is_anomaly': (
                two_year_result['is_anomaly']
                if two_year_result else False
            ),

            # -----------------------------
            # FINAL
            # -----------------------------

            'pattern_repeats': pattern_repeats,

            'is_final_anomaly': pattern_repeats
        }

        results.append(row)

    # =========================================================
    # 9. Return
    # =========================================================

    result_df = pd.DataFrame(results)

    return result_df, result_df['is_final_anomaly'].any()


# =============================================================
# RUN FOR ALL BRANDS
# =============================================================

brands = all_brand['brand_code'].unique()

results = []

for brand in brands:

    df_result, repeats = detect_month_anomaly(
        all_brand,
        brand_code=brand,
        threshold=0.25,
        months_window=3,
        future_months=4
    )

    if df_result is not None and not df_result.empty:
        results.append(df_result)


# =============================================================
# FINAL OUTPUT
# =============================================================

if results:

    anomaly_summary = pd.concat(
        results,
        ignore_index=True
    )

else:

    anomaly_summary = pd.DataFrame()

historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00
historical_target_date 2024-10-31 00:00:00
historical_target_date 2025-11-30 00:00:00
historical_target_date 2024-11-30 00:00:00
historical_target_date 2025-12-31 00:00:00
historical_target_date 2024-12-31 00:00:00
historical_target_date 2026-01-31 00:00:00
historical_target_date 2025-01-31 00:00:00
historical_target_date 2025-10-31 00:00:00

In [143]:
all_brand

     brand_code  run_month month_date  vol_in_rum_value
0     ADV-AHO-R 2026-09-30 2023-01-31          0.383727
1     ADV-AHO-R 2026-09-30 2023-02-28          0.299053
2     ADV-AHO-R 2026-09-30 2023-03-31          0.283299
3     ADV-AHO-R 2026-09-30 2023-04-30          0.269135
4     ADV-AHO-R 2026-09-30 2023-05-31          0.242577
...         ...        ...        ...               ...
5923  VEG_CLEAN 2026-09-30 2026-12-31          0.000000
5924  VEG_CLEAN 2026-09-30 2027-01-31          0.000000
5925  VEG_CLEAN 2026-09-30 2027-02-28          0.000000
5926  VEG_CLEAN 2026-09-30 2027-03-31          0.000000
5927  VEG_CLEAN 2026-09-30 2027-04-30          0.000000

[5928 rows x 4 columns]

In [150]:
anomaly_summary.rename(columns={'target_month':'month_date'}, inplace=True)
# anomaly_summary.rename(columns={'month':'month_date'}, inplace=True)

anomaly_summary

,brand_code,run_month,month_date,target_year,ly_target_date,ly_target_value,ly_comparison_dates,ly_comparison_values,ly_pct_diffs,ly_min_pct_diff,ly_max_pct_diff,ly_direction,ly_is_anomaly,two_year_target_date,two_year_target_value,two_year_comparison_dates,two_year_comparison_values,two_year_pct_diffs,two_year_min_pct_diff,two_year_max_pct_diff,two_year_direction,two_year_is_anomaly,pattern_repeats,is_final_anomaly
0,ADV-AHO-R,2026-09-30,2026-10-30,2026,2025-10-31,0.206206,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.18684824006863368, 0.20371506938269301, 0.1...","[0.10360240585829697, 0.012228343710597356, 0....",1.222834,13.937585,higher,False,2024-10-31,0.245509,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.19305814864559792, 0.2569099955315343, 0.22...","[0.27168305406516163, -0.044378263391993904, 0...",-4.437826,27.168305,None,False,False,False
1,ADV-AHO-R,2026-09-30,2026-11-30,2026,2025-11-30,0.183749,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.18684824006863368, 0.20371506938269301, 0.1...","[-0.016586808196084747, -0.09800966268404103, ...",-9.800966,1.529069,None,False,2024-11-30,0.179298,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.19305814864559792, 0.2569099955315343, 0.22...","[-0.07127340984932096, -0.3020970798684974, -0...",-30.209708,-7.127341,lower,False,False,False
2,ADV-AHO-R,2026-09-30,2026-12-30,2026,2025-12-31,0.200907,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.18684824006863368, 0.20371506938269301, 0.1...","[0.07524422865226219, -0.01378188478432125, 0....",-1.378188,11.009844,None,False,2024-12-31,0.156940,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.19305814864559792, 0.2569099955315343, 0.22...","[-0.18708346854749236, -0.3891239605492168, -0...",-38.912396,-18.708347,lower,False,False,False
3,ADV-AHO-R,2026-09-30,2027-01-30,2027,2026-01-31,0.238354,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.18684824006863368, 0.20371506938269301, 0.1...","[0.27565530921448006, 0.17003592411305482, 0.3...",17.003592,31.700588,higher,False,2025-01-31,0.220992,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.19305814864559792, 0.2569099955315343, 0.22...","[0.1446902589961271, -0.1398085476696965, -0.0...",-13.980855,14.469026,None,False,False,False
4,BIO OILS,2026-09-30,2026-10-30,2026,2025-10-31,0.547372,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.5252750755063238, 0.6749405003562554, 0.572...","[0.042067320702433, -0.18900704539774632, -0.0...",-18.900705,4.206732,None,False,2024-10-31,0.748361,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.6385267402554331, 0.7160564172680984, 0.633...","[0.17201237140329947, 0.045114911345030394, 0....",4.511491,18.097204,higher,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,SW_SGPRF,2026-09-30,2027-01-30,2027,2026-01-31,0.130562,"[2025-08-31 00:00:00, 2025-07-31 00:00:00, 202...","[0.24525193461569286, 0.2468549332107062, 0.28...","[-0.46764056869919846, -0.4710975440543917, -0...",-54.084656,-46.764057,lower,True,2025-01-31,0.056615,"[2024-08-31 00:00:00, 2024-07-31 00:00:00, 202...","[0.08873008248679538, 0.10227679069892724, 0.4...","[-0.36193784983593896, -0.44645010046885464, -...",-86.301177,-36.193785,lower,True,True,True
528,VEG_CLEAN,2026-09-30,2026-10-30,2026,NaT,NaN,None,None,None,NaN,NaN,None,False,NaT,NaN,None,None,None,NaN,NaN,None,False,False,False
529,VEG_CLEAN,2026-09-30,2026-11-30,2026,NaT,NaN,None,None,None,NaN,NaN,None,False,NaT,NaN,None,None,None,NaN,NaN,None,False,False,False
530,VEG_CLEAN,2026-09-30,2026-12-30,2026,NaT,NaN,None,None,None,NaN,NaN,None,False,NaT,NaN,None,None,None,NaN,NaN,None,False,False,False
531,VEG_CLEAN,2026-09-30,2027-01-30,2027,NaT,NaN,None,None,None,NaN,NaN,None,False,NaT,NaN,None,None,None,NaN,NaN,None,False,False,False

In [ ]:

# def detect_month_anomaly(df, brand_code, month_num, mon=9,threshold=0.25, months_window=3):
#     """
#     Detect if a specific month's vol_in_rum_value is >25% different 
#     from past 3 months & next 3 months, and if pattern repeats in last 2 years.
    
#     Parameters:
#     - df: input dataframe with 'month_date', 'vol_in_rum_value'
#     - brand_code: filter by this brand code
#     - month_num: month to check (6, 7, 8, 9)
#     - threshold: 25% difference threshold
#     - months_window: number of months before and after to compare
#     """
    
#     df_brand = df[df['brand_code'] == brand_code].sort_values('month_date').copy()
    
#     if df_brand.empty:
#         return None
    
#     df_brand['year'] = df_brand['month_date'].dt.year
#     df_brand['month'] = df_brand['month_date'].dt.month
    
#     years = sorted(df_brand['year'].unique())
#     current_year = years[-1]
#     past_years = [y for y in years if y < current_year][-2:]
    
#     anomalies = []
    
#     for year in past_years:
#         df_year = df_brand[df_brand['year'] == year].sort_values('month_date')
        
#         month_data = df_year[df_year['month'] == month_num]
#         if month_data.empty:
#             continue
        
#         month_value = month_data['vol_in_rum_value'].iloc[0]
        
#         past_months = [(mon - i - 1) % 12 for i in range(1, months_window + 1)]
#         print(past_months)
#         next_months = [(mon + i - 1) % 12 + 1 for i in range(1, months_window + 1)]
        
#         past_m = df_year[df_year['month'].isin(past_months)]['vol_in_rum_value']
#         next_m = df_year[df_year['month'].isin(next_months)]['vol_in_rum_value']
        
#         comparison_values = pd.concat([past_m])
        
#         if comparison_values.empty:
#             continue
        
#         pct_diffs = []
#         for comp_value in comparison_values:
#             if comp_value != 0:
#                 pct_diff = (month_value - comp_value) / comp_value
#                 pct_diffs.append(pct_diff)
        
#         if pct_diffs:
#             positive_diffs = [p for p in pct_diffs if p > 0]
#             negative_diffs = [p for p in pct_diffs if p < 0]
#             same_sign = len(positive_diffs) == len(pct_diffs) or len(negative_diffs) == len(pct_diffs)
#             is_anomaly = len([p for p in pct_diffs if abs(p) > threshold]) == len(pct_diffs) and same_sign
#         else:
#             is_anomaly = False

#         anomalies.append({
#             'brand_code': brand_code,
#             'month': month_num,
#             'year': year,
#             'month_value': month_value,
#             'num_months_compared': len(comparison_values),
#             'pct_diffs_from_each': pct_diffs,
#             'min_pct_diff': min(pct_diffs) * 100 if pct_diffs else None,
#             'max_pct_diff': max(pct_diffs) * 100 if pct_diffs else None,
#             'is_anomaly': is_anomaly,
#             'direction': 'higher' if month_value > comparison_values.mean() else 'lower'
#         })
    
#     if len(anomalies) == 2:
#         pattern_repeats = anomalies[0]['is_anomaly'] and anomalies[1]['is_anomaly']
#         return pd.DataFrame(anomalies), pattern_repeats
    
#     return pd.DataFrame(anomalies), False


# # Check months 6, 7, 8, 9
# brands = all_brand['brand_code'].unique()
# results = []

# for month in [9,10,11,12]:
#     for brand in brands:
#         df_result, repeats = detect_month_anomaly(all_brand, brand, month)
#         if df_result is not None and not df_result.empty:
#             df_result['pattern_repeats'] = repeats
#             results.append(df_result)

# anomaly_summary = pd.concat(results, ignore_index=True)
# # print(anomaly_summary[anomaly_summary['pattern_repeats'] == True])

[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]
[7, 6, 5]

In [148]:
final_df#.shape

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,Amazon ARIPL_718288,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.569236,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,None,SAFFOLA OILS,0.0,0.0,40.992,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
1,Amazon ARIPL_718288,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
2,Amazon ARIPL_718288,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+1,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,10,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
3,Amazon ARIPL_718288,2026-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+2,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,11,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
4,Amazon ARIPL_718288,2026-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+3,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,12,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Purplle_810674,2027-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+5,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.224,0.0,0.000288,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,NaN,NaN,0.000180,0.000000,2,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135969,Purplle_810674,2027-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+6,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.140,0.0,0.000180,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000288,NaN,0.000000,0.000000,3,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135970,Purplle_810674,2027-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+7,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000180,0.000288,0.000000,0.000000,4,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135971,Purplle_810674,2027-05-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+8,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.121333,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000180,0.000000,0.000018,5,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN
135972,Purplle_810674,2027-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+9,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.046667,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000000,0.000018,0.000000,6,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN

In [151]:
xx = final_df.copy()

In [152]:
final_brands = anomaly_summary[anomaly_summary['pattern_repeats'] == True].drop_duplicates(subset=['brand_code','month_date'])[['brand_code', 'month_date','two_year_direction']]
final_brands['month_different'] = 1
final_df['month'] = final_df['month_date'].dt.month
final_df = final_df.merge(final_brands[['brand_code', 'month_date','month_different']], on = ['brand_code','month_date'], how = 'left')
final_df['month_different'].fillna(0, inplace=True)
final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value,month_different
0,Amazon ARIPL_718288,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.569236,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,None,SAFFOLA OILS,0.0,0.0,40.992,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN,0.0
1,Amazon ARIPL_718288,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN,0.0
2,Amazon ARIPL_718288,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+1,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,10,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN,0.0
3,Amazon ARIPL_718288,2026-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+2,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,11,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN,0.0
4,Amazon ARIPL_718288,2026-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+3,SAFFOLA OILS,0.0,0.0,0.000,20.496000,8.198400,0.0,0.0,0.000000,0.000000,0.000000,inf,0.0,0.0,0.0,20.496000,0.284618,0.113847,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.569236,0.000000,0.0,1,0,0.0,0,40.992000,40.992000,0.569236,0.569236,0.0,0.0,0.0,0.0,138865.260689,0,0,0.284618,1.138473,NaN,NaN,NaN,NaN,12,0.0,NaN,0.0,0,2026-09-30,40.992000,40.992000,0.569236,0.569236,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,Purplle_810674,2027-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+5,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.224,0.0,0.000288,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,NaN,NaN,0.000180,0.000000,2,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN,0.0
135969,Purplle_810674,2027-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+6,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.140,0.0,0.000180,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000288,NaN,0.000000,0.000000,3,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN,0.0
135970,Purplle_810674,2027-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+7,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.000000,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000180,0.000288,0.000000,0.000000,4,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN,0.0
135971,Purplle_810674,2027-05-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+8,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.121333,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000180,0.000000,0.000018,5,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN,0.0
135972,Purplle_810674,2027-06-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-09-30,M+9,HAIR OILS,0.0,0.0,0.000,0.004667,0.025667,0.0,0.0,0.046667,0.046667,0.025667,0.0,inf,-100.0,0.0,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.000018,0.0,1,0,0.0,0,0.004667,0.025667,0.000006,0.000033,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000394,0.000000,0.000000,0.000018,0.000000,6,0.0,NaN,0.0,0,2026-09-30,0.004667,0.025667,0.000006,0.000033,NaN,NaN,NaN,NaN,0.0

In [ ]:
# final_df[final_df['month_different'] == 1]

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value,month_different
1791,Amazon RK_718360,2026-11-30,3.076125e+01,22.383333,12.675000,11.885842,8.401973,1.602311e-03,0.001166,0.000660,0.000619,0.000438,718360,Amazon RK,MALO-NATU,0.000000,4.0,520.886058,0.0,0.0,0.0,2026-08-31,2.172464,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,OTHERS,12.905836,12.374995,0.0,22.383333,12.675000,0.0,0.008333,0.016667,21.966667,14.475000,1.896813,214.558473,135.393258,2.0,22.175000,0.001166,0.000660,0.000000,4.340717e-07,0.000672,0.000645,0.0,0.00,0.000000,0.000000,0.000529,0.002341,0.000628,0,0,0.0,0,22.383333,12.675000,0.001166,0.000660,0.0,0.000000,0.000000,0.000000e+00,520.886058,0,0,0.000000,0.002279,0.000000,0.000003,0.000000,0.000000,11,0.0,NaN,0.0,0,2026-09-30,22.383333,12.675000,0.001166,0.000660,0.0,0.000000,0.000000,0.000000e+00,1.0
2205,Amazon RK_718447,2026-11-30,4.575000e+02,361.200000,308.900000,899.834480,703.444750,1.721849e-02,0.013594,0.011626,0.033866,0.026475,718447,Amazon RK,PADV-HOT,3.076367,4.0,376.360353,0.0,0.0,0.0,2026-08-31,1.075659,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,HAIR OILS,1002.285746,951.302314,0.0,361.200000,308.900000,273.6,309.650000,253.500000,301.800000,284.000000,19.681909,13.373403,3.741231,0.0,331.500000,0.013594,0.011626,0.010297,1.165400e-02,0.037722,0.035803,1063.5,780.30,0.040026,0.029367,0.017218,0.013222,0.010342,0,0,0.0,1,361.200000,308.900000,0.013594,0.011626,273.6,268.950000,0.010297,1.012221e-02,376.360353,0,1,0.000000,0.048174,0.006504,0.014520,0.036379,0.002371,11,1.0,oct-jan,0.0,1,2026-09-30,361.200000,308.900000,0.013594,0.011626,273.6,268.950000,0.010297,1.012221e-02,1.0
2257,Amazon RK_718449,2026-11-30,2.544274e+01,38.570000,21.565000,20.066738,33.775734,9.575638e-04,0.001452,0.000812,0.000755,0.001271,718449,Amazon RK,PADV-HOT,0.140741,4.0,376.360353,0.0,0.0,0.0,2026-08-31,1.381425,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,HAIR OILS,27.569405,24.187724,0.0,38.570000,21.565000,0.0,0.000000,0.000000,30.780000,22.420000,25.308642,118.918919,208.333333,3.0,34.675000,0.001452,0.000812,0.000000,0.000000e+00,0.001038,0.000910,0.0,0.00,0.000000,0.000000,0.001394,0.001888,0.001073,0,0,0.0,0,38.570000,21.565000,0.001452,0.000812,0.0,0.000000,0.000000,0.000000e+00,376.360353,0,0,0.000000,0.002332,0.000000,0.000000,0.000000,0.000000,11,1.0,oct-jan,0.0,1,2026-09-30,38.570000,21.565000,0.001452,0.000812,0.0,0.000000,0.000000,0.000000e+00,1.0
2300,Amazon RK_718450,2026-11-30,-1.583970e+00,0.000000,0.000000,0.000000,0.000000,-5.961433e-05,0.000000,0.000000,0.000000,0.000000,718450,Amazon RK,PADV-HOT,0.439850,4.0,376.360353,0.0,0.0,0.0,2026-08-31,1.488024,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,HAIR OILS,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,3.51,0.000000,0.000132,0.000000,0.000000,0.000000,0,0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.015000,0.000000,5.645405e-07,376.360353,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11,1.0,oct-jan,0.0,1,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.0,0.015000,0.000000,5.645405e-07,1.0
2342,Amazon RK_718458,2026-11-30,5.584204e-03,0.000000,0.000000,0.000000,0.000000,1.052587e-07,0.000000,0.000000,0.000000,0.000000,718458,Amazon RK,NHR-SABDM,0.000000,4.0,188.493651,0.0,0.0,0.0,2026-08-31,3.155077,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,HAIR OILS,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,188.493651,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11,0.0,NaN,0.0,0,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134118,Purplle_719004,2026-11-30,8.407544e-47,0.000000,0.000000,0.000000,1.763944,5.473625e-51,0.000000,0.000000,0.000000,0.000115,719004,Purplle,SW NOGAS,2.118735,4.0,651.037289,0.0,0.0,0.0,2026-08-31,1.496551,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,MALE GROOMING,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.020000,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.302075e-06,0.000000,0.000000,0.0,5.28,0.000000,0.000344,0.000000,0.000000,0.000000,0,0,0.0,1,0.000000,0.000000,0.000000,0.000000,0.0,0.380000,0.000000,2.473942e-05,651.037289,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11,0.0,NaN,0.0,0,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.0,0.380000,0.000000,2.473942e-05,1.0
134322,Purplle_719105,2026-11-30,-2.139727e-05,0.000000,0.000000,0.000000,0.000000,-1.393042e-09,0.000000,0.000000,0.000000,0.000000,719105,Purplle,SW NOGAS,0.000000,4.0,651.037289,0.0,0.0,0.0,2026-08-31,3.820610,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,MALE GROOMING,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,651.037289,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11,0.0,NaN,0.0,0,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000e+00,1.0
134540,Purplle_720670,2026-11-30,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,720670,Purplle,PA-BDYLOT,0.000000,0.0,231.078684,0.0,0.0,0.0,NaT,0.000000,NaN,NaN,NaN,2026-09-30,M+2,SKIN CARE,0.000000,0.000000,0.0,1.800000,0.720000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,inf,0.000000,0.0,1.800000,0.000042,0.000017,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.000000,0.000083,0.000000,1,0,0.0,0,1.800000,1.800000,0.000042,0.000042,0.0,0.000000,0.000000,0.000000e+00,231.078684,0,0,0.000021,0.000083,NaN,NaN,NaN,NaN,11,1.0,sept-dec,0.0,1,2026-09-30,1.800000,1.800000,0.000042,0.000042,NaN,NaN,NaN,NaN,1.0
134564,Purplle_720674,2026-11-30,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,720674,Purplle,PA-BDYLOT,0.000000,4.0,231.078684,0.0,0.0,0.0,2026-08-31,3.741657,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,SKIN CARE,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,-100.000000,-100.000000,-100.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0.0,0,0.000000,0.000000,0.000000,0.000000,0.5,0.500000,0.000012,1.155393e-05,231.078684,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11,1.0,sept-dec,0.0,1,2026-09-30,0.000000,0.000000,0.000000,0.000000,0.5,0.500000,0.000012,1.155393e-05,1.0
134616,Purplle_720709,2026-11-30,1.237887e+00,0.066667,0.033333,0.000000,1.759762,6.735006e-05,0.000004,0.000002,0.000000,0.000096,720709,Purplle,PA_ONI_HO,0.204545,4.0,544.072880,0.0,0.0,0.0,2026-08-31,0.991465,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,2026-09-30,M+2,HAIR OILS,0.000000,0.000000,0.0,0.066667,0.033333,6.2,5.366667,1.000000,0.066667,0.066667,0.000000,0.000000,inf,0.0,0.066667,0.000004,0.000002,0.000337,2.919858e-04,0.000000,0.000000,0.6,18.20,0.000033,0.000990,0.000000,0.000000,0.000011,0,0,0.0,1,0.066667,0.033333,0.000004,0.000002,6.2,9.366667,0.000337,5.096149e-04,544.072880,0,-1,0.000000,0.000152,0.000163,0.000000,0.000000,0.000000,11,0.0,NaN,0.0,0,2026-09-30,0.066667,0.033333,0.000004,0.000002,6.2,9.366667,0.000337,5.096149e-04,1.0

In [ ]:
# final_brands = anomaly_summary[anomaly_summary['pattern_repeats'] == True].drop_duplicates(subset=['brand_code'])[['brand_code', 'direction', 'min_pct_diff', 'max_pct_diff']]
# final_brands['month_different'] = 1
# final_df = final_df.merge(final_brands[['brand_code', 'month_different']], on = 'brand_code', how = 'left')
# final_df['month_different'].fillna(0, inplace=True)
# final_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,ratio_last_year,quarter,qtr_ind_rate_x,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3,skipped,event_month_flag,event_uplift_factor,event_sensitive_flag,P3M_adj,P6M_adj,P3M_adj_value,P6M_adj_value,LY_P3M_adj,LY_P6M_adj,LY_P3M_adj_value,LY_P6M_adj_value,qtr_ind_rate_y,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value,month,is_seasonal_month,seasonal_months,is_seasonal_month_psku,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value,month_different
0,Amazon ARIPL_718288,2026-07-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.471503,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,None,SAFFOLA OILS,0.0,0.0,33.954,0.000000,0.0000,0.0,0.0,0.000000,0.000000,0.000,0.0,0.0,0.000000,0.0,0.000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000000,0.0,0.0,1,0,0.0,0,33.954000,33.954,0.471503,0.471503,0.0,0.0,0.0,0.0,138865.260689,0,0,0.235752,0.943006,NaN,NaN,NaN,NaN,7,0.0,NaN,0.0,0,2026-08-31,33.954000,33.954,0.471503,0.471503,NaN,NaN,NaN,NaN,1.0
1,Amazon ARIPL_718288,2026-08-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M,SAFFOLA OILS,0.0,0.0,0.000,16.977000,6.7908,0.0,0.0,0.000000,0.000000,0.000,inf,0.0,0.000000,0.0,16.977,0.235752,0.094301,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.471503,0.0,0.0,1,0,0.0,0,33.954000,33.954,0.471503,0.471503,0.0,0.0,0.0,0.0,138865.260689,0,0,0.235752,0.943006,NaN,NaN,NaN,NaN,8,0.0,NaN,0.0,0,2026-08-31,33.954000,33.954,0.471503,0.471503,NaN,NaN,NaN,NaN,1.0
2,Amazon ARIPL_718288,2026-09-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+1,SAFFOLA OILS,0.0,0.0,0.000,16.977000,6.7908,0.0,0.0,0.000000,0.000000,0.000,inf,0.0,0.000000,0.0,16.977,0.235752,0.094301,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.471503,0.0,0.0,1,0,0.0,0,33.954000,33.954,0.471503,0.471503,0.0,0.0,0.0,0.0,138865.260689,0,0,0.235752,0.943006,NaN,NaN,NaN,NaN,9,0.0,NaN,0.0,0,2026-08-31,33.954000,33.954,0.471503,0.471503,NaN,NaN,NaN,NaN,1.0
3,Amazon ARIPL_718288,2026-10-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+2,SAFFOLA OILS,0.0,0.0,0.000,16.977000,6.7908,0.0,0.0,0.000000,0.000000,0.000,inf,0.0,0.000000,0.0,16.977,0.235752,0.094301,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.471503,0.0,0.0,1,0,0.0,0,33.954000,33.954,0.471503,0.471503,0.0,0.0,0.0,0.0,138865.260689,0,0,0.235752,0.943006,NaN,NaN,NaN,NaN,10,0.0,NaN,0.0,0,2026-08-31,33.954000,33.954,0.471503,0.471503,NaN,NaN,NaN,NaN,1.0
4,Amazon ARIPL_718288,2026-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,718288,Amazon ARIPL,SAFF GOLD,0.0,0.0,138865.260689,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+3,SAFFOLA OILS,0.0,0.0,0.000,16.977000,6.7908,0.0,0.0,0.000000,0.000000,0.000,inf,0.0,0.000000,0.0,16.977,0.235752,0.094301,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.471503,0.0,0.0,1,0,0.0,0,33.954000,33.954,0.471503,0.471503,0.0,0.0,0.0,0.0,138865.260689,0,0,0.235752,0.943006,NaN,NaN,NaN,NaN,11,0.0,NaN,0.0,0,2026-08-31,33.954000,33.954,0.471503,0.471503,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133231,Purplle_810674,2027-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+5,HAIR OILS,0.0,0.0,0.000,0.004667,0.0630,0.0,0.0,0.000000,0.121333,0.084,inf,-100.0,-61.538462,0.0,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000018,0.0,0.0,1,0,0.0,0,0.004667,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000419,NaN,NaN,0.000288,0.000180,1,0.0,NaN,0.0,0,2026-08-31,0.004667,0.063,0.000006,0.000081,NaN,NaN,NaN,NaN,1.0
133232,Purplle_810674,2027-02-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+6,HAIR OILS,0.0,0.0,0.000,0.004667,0.0630,0.0,0.0,0.000000,0.121333,0.084,inf,-100.0,-61.538462,0.0,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,0.224,0.0,0.000288,0.0,0.000018,0.0,0.0,1,0,0.0,0,0.004667,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000419,NaN,NaN,0.000180,0.000000,2,0.0,NaN,0.0,0,2026-08-31,0.004667,0.063,0.000006,0.000081,NaN,NaN,NaN,NaN,1.0
133233,Purplle_810674,2027-03-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+7,HAIR OILS,0.0,0.0,0.000,0.004667,0.0630,0.0,0.0,0.000000,0.121333,0.084,inf,-100.0,-61.538462,0.0,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,0.140,0.0,0.000180,0.0,0.000018,0.0,0.0,1,0,0.0,0,0.004667,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000419,0.000288,NaN,0.000000,0.000000,3,0.0,NaN,0.0,0,2026-08-31,0.004667,0.063,0.000006,0.000081,NaN,NaN,NaN,NaN,1.0
133234,Purplle_810674,2027-04-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+8,HAIR OILS,0.0,0.0,0.000,0.004667,0.0630,0.0,0.0,0.000000,0.121333,0.084,inf,-100.0,-61.538462,0.0,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000018,0.0,0.0,1,0,0.0,0,0.004667,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000419,0.000180,0.000288,0.000000,0.000000,4,0.0,NaN,0.0,0,2026-08-31,0.004667,0.063,0.000006,0.000081,NaN,NaN,NaN,NaN,1.0
133235,Purplle_810674,2027-05-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,810674,Purplle,PA_ESS_HO,0.0,0.0,12860.631072,0.000000,0.0,0.0,NaT,0.0,NaN,NaN,NaN,2026-08-31,M+9,HAIR OILS,0.0,0.0,0.000,0.004667,0.0630,0.0,0.0,0.121333,0.121333,0.084,inf,-100.0,-61.538462,0.0,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,0.000,0.0,0.000000,0.0,0.000018,0.0,0.0,1,0,0.0,0,0.004667,0.063,0.000006,0.000081,0.0,0.0,0.0,0.0,12860.631072,0,0,0.000000,0.000419,0.000000,0.000180,0.000000,0.000018,5,0.0,NaN,0.0,0,2026-08-31,0.004667,0.063,0.000006,0.000081,NaN,NaN,NaN,NaN,1.0

In [165]:
final_df[(final_df['M month'].notna())].to_csv(f'/data/aman_singh/acuuracy_check/all_combination_ecom_{month_run}_pred.csv')

In [166]:
final_df.to_csv('/data/aman_singh/acuuracy_check/all_combination_ecom_trend.csv')

In [154]:
final_df[final_df['month_date'] == '2026-10-31']['pred_value_prophet'].sum()

50.02404523409474

### some checks

In [155]:
query = f"""select * from {input_table}
where run_month = '{month_run}' """

data = pd.read_sql(con=dev_conn, sql=query)
data.columns = data.columns.str.lower()
data

,month_date,platform_name,parent_material_code,vol_in_rum,indexbpm,brand_code,imputed,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,ratio_last_year,quarter,run_month
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,1,0,0,0,0,1,0,NaN,3,2026-09-30
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,0,0,1,0,0,0,0,NaN,3,2026-09-30
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,0,0,0,1,0,0,0,0.0,4,2026-09-30
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,0,0,0,0,1,0,0,0.0,4,2026-09-30
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,0,0,0,0,0,0,0,0.0,4,2026-09-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141752,2027-02-28,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,0,0,0,0,0,0,0,NaN,1,2026-09-30
141753,2027-03-31,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,0,0,0,0,0,0,0,NaN,1,2026-09-30
141754,2027-04-30,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,0,0,0,0,0,0,0,0.0,2,2026-09-30
141755,2027-05-31,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,0,0,0,0,0,0,0,0.0,2,2026-09-30
141756,2027-06-30,Purplle,810674,0.000,0.000000,PA_ESS_HO,1,0,0,0,0,0,0,0,0,0,0,0.0,2,2026-09-30

In [156]:
data['key'] = (
    data['platform_name'].astype(str) + '_' +
    data['parent_material_code'].astype(str)
)
data = data[data['key'].isin(trend_file_df['key'].unique())]

In [157]:
trend_file_df

,key,month_date,pred_SARIMA,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_SARIMA,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,parent_material_code,platform_name,brand_code,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,ratio_last_year,quarter,qtr_ind_rate,vol_in_rum_value,vol_in_rum_treated,vol_in_rum_value_treated,train_till,cov,run,step,file_path,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,run_month,M month,portfolio,pred_prophet_70%ile,pred_prophet_60%ile,vol_in_rum,P3M,P6M,LY P3M,LY P6M,LY P3M_copy,P3M Max,P3M Top 2 Mean,MoM P3M growth,MoM P3M growth_lag_1,MoM P3M growth_lag_2,>=20%_3M_inc_month_count,"Avg(P3M Mean, Max)",P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,pred_prophet_60%ile_value,LY,LLY,LY value,LLY value,OT_Value_in_Cr_lag_1,OT_Value_in_Cr_lag_2,OT_Value_in_Cr_lag_3
0,Amazon RK_718472,2023-11-30,0.000000e+00,0.51,1.125,NaN,0.4590,0.000000e+00,0.000025,0.000056,NaN,0.000023,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,0.000000,4,496.828458,0.000022,0.45,0.000022,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,1.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Amazon RK_718472,2023-12-31,4.499998e-01,0.51,1.125,NaN,0.3690,2.235727e-05,0.000025,0.000056,NaN,0.000018,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,NaN,4,496.828458,0.000000,0.00,0.000000,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,1.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000022,NaN,NaN
2,Amazon RK_718472,2024-01-31,1.635320e-01,0.51,1.125,NaN,0.9486,8.124736e-06,0.000025,0.000056,NaN,0.000047,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,2.400000,1,496.828458,0.000054,1.08,0.000054,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000022,NaN
3,Amazon RK_718472,2024-02-29,7.076602e-01,0.51,1.125,NaN,1.4706,3.515857e-05,0.000025,0.000056,NaN,0.000073,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,7.200000,1,496.828458,0.000080,1.62,0.000080,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,1.62,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.51,0.000025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000054,0.000000,0.000022
4,Amazon RK_718472,2024-03-31,8.456983e-01,0.90,1.125,NaN,2.0844,4.201670e-05,0.000045,0.000056,NaN,0.000104,718472,Amazon RK,ADV-AHO-R,NaN,NaN,NaN,NaN,NaN,5.294118,1,496.828458,0.000134,2.70,0.000134,2026-08-31,2.702665,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,0.0,0.0,0.0,0.0,0.0,2026-09-30,None,HAIR OILS,NaN,NaN,2.70,0.90,NaN,NaN,NaN,NaN,NaN,NaN,76.470588,NaN,NaN,NaN,0.90,0.000045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000080,0.000054,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126020,Big Basket_719192,2026-12-31,-8.050627e-311,0.00,0.000,NaN,0.0000,-8.050627e-316,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,4,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+3,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126021,Big Basket_719192,2027-01-31,-1.579926e-304,0.00,0.000,NaN,0.0000,-1.579926e-309,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+4,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126022,Big Basket_719192,2027-02-28,-1.151388e-310,0.00,0.000,NaN,0.0000,-1.151388e-315,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+5,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126023,Big Basket_719192,2027-03-31,-1.506390e-304,0.00,0.000,NaN,0.0000,-1.506390e-309,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,1,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+6,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
126024,Big Basket_719192,2027-04-30,-1.463731e-310,0.00,0.000,NaN,0.0000,-1.463731e-315,0.000000,0.000000,NaN,0.000000,719192,Big Basket,VEG_CLEAN,0.0,0.0,0.0,0.0,0.0,NaN,2,100.000000,0.000000,0.00,0.000000,2026-08-31,4.783100,run,acuuracy_check,/data/aman_singh/acuuracy_check/trend_file_tra...,NaN,NaN,NaN,NaN,NaN,2026-09-30,M+7,HEALTH & HYGIENE,NaN,NaN,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,-100.000000,-100.0,-100.0,0.0,0.00,0.000000,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000

In [158]:
import pandas as pd

as_of_date = pd.to_datetime(month_run)  # month-end for Feb 2026
data['month_date'] = pd.to_datetime(data['month_date'])
filtered = data[
    
    (data['month_date'] < as_of_date) &
    (data['month_date'] >= as_of_date - pd.DateOffset(months=3))
]

In [159]:
# assert p3m equals
x = filtered.groupby(['month_date'])['vol_in_rum'].sum().reset_index()['vol_in_rum'].mean()
y = trend_file_df[trend_file_df['month_date'] == month_run]['P3M'].sum()
assert(int(x)==int(y))

In [160]:
(x,y)

(266474.77709504537, 266474.7770950415)

In [161]:
ly_end = as_of_date - pd.DateOffset(years=1)
ly_start = ly_end - pd.DateOffset(months=3)

filtered = data[
    
    (data['month_date'] < ly_end) &
    (data['month_date'] >= ly_start )
]

In [162]:
# p3m ly check may not equal but should be close
x = filtered.groupby(['month_date'])['vol_in_rum'].sum().reset_index()['vol_in_rum'].mean()
y = trend_file_df[trend_file_df['month_date'] == month_run]['LY P3M'].sum()
(x,y)

(270739.84984885, 270374.1616822037)

In [163]:
# p3m consistency check
as_of_date = pd.to_datetime(month_run)

next_3_months = pd.date_range(
    start=as_of_date + pd.offsets.MonthEnd(1),
    periods=3,
    freq='M'
)
for dt in next_3_months:
    p3m_sum = trend_file_df.loc[
        trend_file_df['month_date'] == dt, 'P3M'
    ].sum()
    
    print(f"P3M sum for {dt.date()}: {p3m_sum}")

P3M sum for 2026-10-31: 266474.7770950415
P3M sum for 2026-11-30: 266474.7770950415
P3M sum for 2026-12-31: 266474.7770950415

### The end

In [106]:
import numpy as np
import pandas as pd

df = final_df.copy()

# --------------------------------------------------
# 1. SAFE FACTOR FUNCTIONS (NO ERRORS)
# --------------------------------------------------

def safe_div(a, b):
    """Safe division: if error or b<=0 → return 1."""
    try:
        if b is None or b == 0:
            return 1
        return a / b
    except:
        return 1

# recency factor = p3m/p6m (cap at 2)
df["recency_factor"] = df.apply(
    lambda r: min(2, safe_div(r["P3M_value"], r["P6M_value"])),
    axis=1
)

def safe_shrink(r,column_name):
    try:
        ratio = r[column_name] / r["P3M_value"]
        return 1 / np.sqrt(ratio)
    except:
        return 1

df["shrink_ratio_prophet"] = df.apply(lambda r: safe_shrink(r, "pred_value_prophet"), axis=1)
df["shrink_ratio_rf"] = df.apply(lambda r: safe_shrink(r, "pred_value_rf"), axis=1)

# seasonality factor = p3m / p3mLY (cap at 2)
df["seasonality_factor"] = df.apply(
    lambda r: min(2, safe_div(r["P3M_value"], r["LY P3M_value"])),
    axis=1
)


# shrink_ratio = 1 / sqrt(max(forecast/p3m,1)) → safe



# --------------------------------------------------
# 2. HEURISTICS
# --------------------------------------------------

# Recency heuristic: max(recency_factor * P3M, forecast)
df["recency_heuristic_prophet_value"] = df.apply(
    lambda r: max(r["recency_factor"] * r["P3M_value"], r["pred_value_prophet"]),
    axis=1
)

# Seasonality heuristic: max(seasonality_value, forecast)
df["seasonality_heuristic_prophet_value"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY value'], r["pred_value_prophet"]),
    axis=1
)

# Recency + Seasonality combined
df["recency_seasonality_heuristic_prophet_value"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY value'] * r["recency_factor"],
                  r["pred_value_prophet"]),
    axis=1
)

# Non-seasonal heuristic
df["non_seasonal_heuristic_prophet_value"] = df["pred_value_prophet"] * df["shrink_ratio_prophet"]


# --------------------------------------------------
# 3. FINAL DECISION TREE + skipped condition
# --------------------------------------------------

def apply_final_logic(r):

    # Rule 1: skipped → force P3M
    if r.get("skipped", 0) == 1:
        return r["P3M_value"]

    
    # Rule 3: Heuristic combinations
    if r["final_trend"] == 1 and r["seasonality_flag"] == 0:
        return r["recency_heuristic_prophet_value"]


    if r["final_trend"] != 1 and r["seasonality_flag"] == 1:
        return r["seasonality_heuristic_prophet_value"]
    
    if r["final_trend"] == 1 and r["seasonality_flag"] == 1:
        return r["recency_seasonality_heuristic_prophet_value"]

    # Default: (0,0)
    return r["non_seasonal_heuristic_prophet_value"]


df["final_heuristic_prophet_value"] = df.apply(apply_final_logic, axis=1)

In [107]:
df["recency_heuristic_rf_value"] = df.apply(
    lambda r: max(r["recency_factor"] * r["P3M_value"], r["pred_value_rf"]),
    axis=1
)

# Seasonality heuristic: max(seasonality_value, forecast)
df["seasonality_heuristic_rf_value"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY value'], r["pred_value_rf"]),
    axis=1
)

# Recency + Seasonality combined
df["recency_seasonality_heuristic_rf_value"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY value'] * r["recency_factor"],
                  r["pred_value_rf"]),
    axis=1
)

# Non-seasonal heuristic
df["non_seasonal_heuristic_rf_value"] = df["pred_value_rf"] * df["shrink_ratio_rf"]


# --------------------------------------------------
# 3. FINAL DECISION TREE + skipped condition
# --------------------------------------------------

def apply_final_logic(r):

    # Rule 1: skipped → force P3M
    if r.get("skipped", 0) == 1:
        return r["P3M_value"]

    
    # Rule 3: Heuristic combinations
    if r["final_trend"] == 1 and r["seasonality_flag"] == 0:
        return r["recency_heuristic_rf_value"]


    if r["final_trend"] != 1 and r["seasonality_flag"] == 1:
        return r["seasonality_heuristic_rf_value"]
    
    if r["final_trend"] == 1 and r["seasonality_flag"] == 1:
        return r["recency_seasonality_heuristic_rf_value"]

    # Default: (0,0)
    return r["non_seasonal_heuristic_rf_value"]


df["final_heuristic_rf_value"] = df.apply(apply_final_logic, axis=1)

In [108]:
df["error_prophet"] = df["pred_value_prophet"] - df["vol_in_rum_value"]
df["abs_error_prophet"] = df["error_prophet"].abs()

df["error_rf"] = df["pred_value_rf"] - df["vol_in_rum_value"]
df["abs_error_rf"] = df["error_rf"].abs()

df["error_final_heuristic_prophet"] = df["final_heuristic_prophet_value"] - df["vol_in_rum_value"]
df["abs_error_final_heuristic_prophet"] = df["error_final_heuristic_prophet"].abs()

df["error_final_heuristic_rf"] = df["final_heuristic_rf_value"] - df["vol_in_rum_value"]
df["abs_error_final_heuristic_rf"] = df["error_final_heuristic_rf"].abs()

In [109]:
df["recency_heuristic_rf"] = df.apply(
    lambda r: max(r["recency_factor"] * r["P3M"], r["pred_rf"]),
    axis=1
)

# Seasonality heuristic: max(seasonality_value, forecast)
df["seasonality_heuristic_rf"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY'], r["pred_rf"]),
    axis=1
)

# Recency + Seasonality combined
df["recency_seasonality_heuristic_rf"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY'] * r["recency_factor"],
                  r["pred_rf"]),
    axis=1
)

# Non-seasonal heuristic
df["non_seasonal_heuristic_rf"] = df["pred_rf"] * df["shrink_ratio_rf"]


# --------------------------------------------------
# 3. FINAL DECISION TREE + skipped condition
# --------------------------------------------------

def apply_final_logic(r):

    # Rule 1: skipped → force P3M
    if r.get("skipped", 0) == 1:
        return r["P3M_value"]

    
    # Rule 3: Heuristic combinations
    if r["final_trend"] == 1 and r["seasonality_flag"] == 0:
        return r["recency_heuristic_rf"]


    if r["final_trend"] != 1 and r["seasonality_flag"] == 1:
        return r["seasonality_heuristic_rf"]
    
    if r["final_trend"] == 1 and r["seasonality_flag"] == 1:
        return r["recency_seasonality_heuristic_rf"]

    # Default: (0,0)
    return r["non_seasonal_heuristic_rf"]


df["final_heuristic_rf"] = df.apply(apply_final_logic, axis=1)

In [110]:
df["recency_heuristic_prophet"] = df.apply(
    lambda r: max(r["recency_factor"] * r["P3M"], r["pred_prophet"]),
    axis=1
)

# Seasonality heuristic: max(seasonality_value, forecast)
df["seasonality_heuristic_prophet"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY'], r["pred_prophet"]),
    axis=1
)

# Recency + Seasonality combined
df["recency_seasonality_heuristic_prophet"] = df.apply(
    lambda r: max(r["seasonality_factor"]*r['LY'] * r["recency_factor"],
                  r["pred_prophet"]),
    axis=1
)

# Non-seasonal heuristic
df["non_seasonal_heuristic_prophet"] = df["pred_prophet"] * df["shrink_ratio_prophet"]


# --------------------------------------------------
# 3. FINAL DECISION TREE + skipped condition
# --------------------------------------------------

def apply_final_logic(r):

    # Rule 1: skipped → force P3M
    if r.get("skipped", 0) == 1:
        return r["P3M_value"]

    
    # Rule 3: Heuristic combinations
    if r["final_trend"] == 1 and r["seasonality_flag"] == 0:
        return r["recency_heuristic_prophet"]


    if r["final_trend"] != 1 and r["seasonality_flag"] == 1:
        return r["seasonality_heuristic_prophet"]
    
    if r["final_trend"] == 1 and r["seasonality_flag"] == 1:
        return r["recency_seasonality_heuristic_prophet"]

    # Default: (0,0)
    return r["non_seasonal_heuristic_prophet"]


df["final_heuristic_prophet"] = df.apply(apply_final_logic, axis=1)

In [112]:
df.to_csv('Heuristics_all_combination_ecom_cp.csv')

In [114]:
df[(df['M month'].notna())].to_csv('Heuristics_all_combination_ecom_cp2.csv')

In [2]:
import pandas as pd
final_df = pd.read_csv('Heuristics_all_combination_ecom_cp.csv')

/tmp/ipykernel_2052077/3783379672.py:2: DtypeWarning: Columns (20,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  final_df = pd.read_csv('Heuristics_all_combination_ecom_cp.csv')

In [6]:
import numpy as np
import pandas as pd

def compute_thresholds(df_grp):
    """
    df_grp MUST contain:
    - month_date
    - vol_in_rum
    - run_month

    Returns: lower_threshold, upper_threshold, mean, std
    """

    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # --- Use ONLY actual data (strictly before run month)
    df_actual = df_grp[df_grp["month_date"] < run_month]

    series = df_actual["vol_in_rum_value"].astype(float).values

    # If no real data → return zeros
    if len(series) == 0:
        return pd.Series({
            "lower_threshold": 0,
            "upper_threshold": 0,
            "mean_value": 0,
            "std_value": 0
        })

    # --- Take last 12 months OR all available
    if len(series) > 12:
        series = series[-12:]

    mean_val = np.mean(series)
    std_val = np.std(series)

    # --- SPECIAL CASE: ≤3 data points
    if len(series) <= 3:
        lower = 0.5 * mean_val
        upper = 2 * mean_val

        return pd.Series({
            "lower_threshold": lower,
            "upper_threshold": upper,
            "mean_value": mean_val,
            "std_value": std_val
        })

    # --- Normal case (std can be zero also)
    lower = max(0,mean_val - 2*std_val)
    upper = mean_val + 3*std_val

    return pd.Series({
        "lower_threshold": lower,
        "upper_threshold": upper,
        "mean_value": mean_val,
        "std_value": std_val
    })

threshold_df = final_df.groupby(
    ["platform_name", "parent_material_code", "run_month"]
).apply(compute_thresholds).reset_index()

threshold_df.head()

,platform_name,parent_material_code,run_month,lower_threshold,upper_threshold,mean_value,std_value
0,Amazon ARIPL,718288,2025-12-31,0.134916,0.345766,0.219256,0.042170
1,Amazon ARIPL,718321,2025-12-31,0.000000,0.000000,0.000000,0.000000
2,Amazon ARIPL,718322,2025-12-31,0.060035,0.108314,0.079347,0.009656
3,Amazon ARIPL,718323,2025-12-31,0.000000,0.000000,0.000000,0.000000
4,Amazon ARIPL,718328,2025-12-31,0.016588,0.032115,0.022799,0.003105

In [7]:
threshold_df.to_csv('ecom_threshold.csv')

In [162]:
final_df[(final_df['M month'].notna())].to_csv('Heuristics_all_combination_qcom_cp_chk.csv')

In [129]:
final_df[final_df['month_date'] == '2026-02-28']['LY P3M_value'].sum()

123.92211585241307

In [49]:
df['TREND'].unique()

array([ 1,  0, -1])

In [96]:
prophet_output = collate_file('prophet_data_train_till')

downloaded_results\new_pipeline\202508-09_FK_Others_Offtakes\train_till_30_Jun_2025\prophet_results\prophet_data_train_till_30_Jun_2025.csv
downloaded_results\new_pipeline\202508-09_FK_Others_Offtakes\train_till_31_Jul_2025\prophet_results\prophet_data_train_till_31_Jul_2025.csv
downloaded_results\new_pipeline\202509_AZ_BB_Offtakes\train_till_30_Jun_2025\prophet_results\prophet_data_train_till_30_Jun_2025.csv
downloaded_results\new_pipeline\202509_AZ_BB_Offtakes\train_till_31_Jul_2025\prophet_results\prophet_data_train_till_31_Jul_2025.csv

In [100]:
len_before_merge = len(offtake_df)
offtake_df = offtake_df.merge(
    read_qtr_ind_rate_table()[['brand_code', 'qtr_ind_rate']] ,
    on=['brand_code'],
    how='left'
)
assert len_before_merge == len(offtake_df)

Credentials retrieved successfully for prod db.

In [ ]:
offtake_df

In [104]:
offtake_df['OT_Value_in_Cr'] = offtake_df['vol_in_rum'] * offtake_df['qtr_ind_rate'] / (10 ** 7)

In [105]:
offtake_df.to_csv('Offtake_realigned_base.csv', index=False)

In [108]:
trend_file_df[trend_file_df['run_month'].isin(['2025-10-31'])].to_csv('Trend_File_Oct_Live_Run_OT.csv', index=False)

In [107]:
trend_file_df[trend_file_df['run_month'].isin(['2025-07-31', '2025-08-31'])].to_csv('Trend_File_SepAug_OT.csv', index=False)

In [97]:
prophet_output.to_csv('ECOM_Prophet_Trend_OT_Chain_PSKU_AugSep.csv', index=False)

In [81]:
forecast_df = trend_file_df[trend_file_df['month_date'] >= trend_file_df['run_month']]

forecast_df

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,LY P6M,P3M_value,P6M_value,LY P3M_value,LY P6M_value,pred_prophet_70%ile_value,LY,LLY,LY value,LLY value
26,Amazon_718589,2025-03-31,1312.900000,1293.400000,1824.634404,945.661643,0.059090,0.058213,0.082122,0.042562,...,841.200000,0.059090,0.058213,0.027878,0.037860,0.082122,717.3,1428.0,0.032284,0.064271
27,Amazon_718589,2025-04-30,1312.900000,1293.400000,1894.995393,1306.938750,0.059090,0.058213,0.085289,0.058822,...,792.800000,0.059090,0.058213,0.036843,0.035682,0.085289,1053.0,1040.4,0.047393,0.046826
28,Amazon_718589,2025-05-31,1312.900000,1293.400000,2055.487818,1194.591429,0.059090,0.058213,0.092512,0.053765,...,682.250000,0.059090,0.058213,0.039944,0.030706,0.092512,1241.1,1236.3,0.055859,0.055643
29,Amazon_718589,2025-06-30,1312.900000,1293.400000,1713.411024,989.591786,0.059090,0.058213,0.077116,0.044539,...,811.600000,0.059090,0.058213,0.045178,0.036528,0.077116,797.4,1176.0,0.035889,0.052929
56,Amazon_722188,2025-03-31,0.666667,6.400000,0.000000,471.682496,0.000030,0.000288,0.000000,0.021229,...,782.533333,0.000030,0.000288,0.043045,0.035220,0.000000,806.4,236.8,0.036294,0.010658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120425,Flipkart National_809422,2025-10-31,211.833333,159.550000,262.584032,129.597491,0.030576,0.023029,0.037901,0.018706,...,207.383333,0.030576,0.023029,0.009040,0.029934,0.046132,0.8,NaN,0.000115,NaN
120442,Flipkart National_809423,2025-07-31,75.000000,53.533333,0.000000,169.044957,0.010826,0.007727,0.000000,0.024400,...,NaN,0.010826,0.007727,0.057582,NaN,0.008194,243.4,NaN,0.035132,NaN
120443,Flipkart National_809423,2025-08-31,75.000000,53.533333,0.000000,117.175693,0.010826,0.007727,0.000000,0.016913,...,NaN,0.010826,0.007727,0.054599,NaN,0.000000,99.6,NaN,0.014376,NaN
120444,Flipkart National_809423,2025-09-30,75.000000,53.533333,0.000000,111.920263,0.010826,0.007727,0.000000,0.016155,...,286.050000,0.010826,0.007727,0.048200,0.041288,0.000000,75.4,NaN,0.010883,NaN
120445,Flipkart National_809423,2025-10-31,75.000000,53.533333,0.000000,115.694153,0.010826,0.007727,0.000000,0.016699,...,269.200000,0.010826,0.007727,0.020131,0.038856,0.000000,27.0,NaN,0.003897,NaN

In [98]:
trend_file_df[trend_file_df['run_month'] == '2025-08-31'].to_csv('Trend_file_Sep.csv', index=False)

In [82]:
forecast_df['is_na'] = forecast_df['vol_in_rum'].isna()
forecast_df.groupby(['run_month', 'month_date'])['is_na'].sum()

run_month   month_date
2025-03-31  2025-03-31    0
            2025-04-30    0
            2025-05-31    0
            2025-06-30    0
2025-04-30  2025-04-30    0
            2025-05-31    0
            2025-06-30    0
            2025-07-31    0
2025-05-31  2025-05-31    0
            2025-06-30    0
            2025-07-31    0
            2025-08-31    0
2025-06-30  2025-06-30    0
            2025-07-31    0
            2025-08-31    0
            2025-09-30    0
2025-07-31  2025-07-31    0
            2025-08-31    0
            2025-09-30    0
            2025-10-31    0
Name: is_na, dtype: int64

In [83]:
forecast_df.drop('is_na', axis=1, inplace=True)

In [84]:
pred_value_cols = [col for col in trend_file_df.columns if 'value' in col and 'pred' in col]
pred_value_cols

['pred_value_p3m',
 'pred_value_p6m',
 'pred_value_prophet',
 'pred_value_rf',
 'pred_value_best_model',
 'pred_prophet_70%ile_value']

In [85]:
for col in pred_value_cols:
    trend_file_df[f'error_{col}'] = trend_file_df[col] - trend_file_df['vol_in_rum_value']
    trend_file_df[f'abs_error_{col}'] = np.abs(trend_file_df[col] - trend_file_df['vol_in_rum_value'])

In [86]:
trend_file_df.to_csv('Trend_file_OT_FK_AZ_BB.csv', index=False)

In [85]:
feature_importance_df = collate_file('feature_importance_train_till')

downloaded_results\202504-08_AZ_BB_ChainPSKU_OT_run\train_till_28_Feb_2025\ml_results\feature_importance_train_till_28_Feb_2025.csv
downloaded_results\202504-08_AZ_BB_ChainPSKU_OT_run\train_till_30_Apr_2025\ml_results\feature_importance_train_till_30_Apr_2025.csv
downloaded_results\202504-08_AZ_BB_ChainPSKU_OT_run\train_till_30_Jun_2025\ml_results\feature_importance_train_till_30_Jun_2025.csv
downloaded_results\202504-08_AZ_BB_ChainPSKU_OT_run\train_till_31_Mar_2025\ml_results\feature_importance_train_till_31_Mar_2025.csv
downloaded_results\202504-08_AZ_BB_ChainPSKU_OT_run\train_till_31_May_2025\ml_results\feature_importance_train_till_31_May_2025.csv

In [87]:
feature_importance_df.to_excel('202505-AZ_BB_OT_Feature_Imp.xlsx', index=False)

In [11]:
collate_file('prophet_data_train_till_').to_excel('202504-08_Prophet_File.xlsx', index=False)

downloaded_results\ECOM_ChainPSKU_OT_run\train_till_28_Feb_2025\prophet_results\prophet_data_train_till_28_Feb_2025.csv
downloaded_results\ECOM_ChainPSKU_OT_run\train_till_30_Apr_2025\prophet_results\prophet_data_train_till_30_Apr_2025.csv
downloaded_results\ECOM_ChainPSKU_OT_run\train_till_30_Jun_2025\prophet_results\prophet_data_train_till_30_Jun_2025.csv
downloaded_results\ECOM_ChainPSKU_OT_run\train_till_31_Mar_2025\prophet_results\prophet_data_train_till_31_Mar_2025.csv
downloaded_results\ECOM_ChainPSKU_OT_run\train_till_31_May_2025\prophet_results\prophet_data_train_till_31_May_2025.csv

### Secondary

In [87]:
sec_query = """SELECT 
    chain,
    parent_material_code, 
    month_date, 
    SUM(sec_actuals_vol_rum_month) AS sec_vol_actuals_rum_month,
    SUM(sec_apo_plan_vol_rum_month) AS sec_apo_plan_vol_rum_month
FROM (
    SELECT 
        month_date, 
        distributor_code, 
        material_code, 
        sec_actuals_vol_rum_month, 
        sec_apo_plan_vol_rum_month
    FROM 
        dwh_bpm_dist_brand_mth_sbp 
    WHERE 
        month_date BETWEEN '2022-04-01' AND '2025-12-31'
) A
JOIN (
    SELECT DISTINCT
        customer, 
        chain
    FROM 
        mst_chain_master 
    WHERE 
        chain_type = 'E Com B2C'
) CC
    ON A.distributor_Code = CC.customer
JOIN (
    SELECT 
        material_code, 
        parent_material_code 
    FROM 
        mst_material 
    WHERE 
        company_code = 'MIL' 
        AND latest_record_ind = 1
) M 
    ON A.material_code = M.material_code
GROUP BY 
    chain,
    parent_material_code, 
    month_date
ORDER BY 
    chain,
    parent_material_code, 
    month_date;
"""


results = pd.read_sql(con=prod_conn, sql=sec_query)
sales_data = pd.DataFrame(results)
sales_data.columns = sales_data.columns.str.lower()
sales_data = sales_data.rename(columns={'parent_material1_code':'parent_material_code'})

In [88]:
sales_data['month_date'] = pd.to_datetime(sales_data['month_date'])

In [89]:
sales_data['chain'] = sales_data['chain'].replace({
    'Grofers': 'Blinkit',
    'Amazon B2C': 'Amazon ARIPL',
    'Flipkart-Grocery': 'Flipkart Grocery',
    'FlipkartGrocery': 'Flipkart Grocery',
    'Flipkart-National': 'Flipkart National',
    'RK WORLDINFOCOM': 'Amazon RK',
    'ZEPTO': 'Zepto',
    'Kiranakart Technologies': 'Zepto',
    'Big basket B2B': 'Big Basket',
    'Big basket B2C': 'Big Basket',
    'Myntra': 'MYNTRA'
})

In [90]:
chains = ['Big Basket', 'Blinkit', 'Amazon ARIPL', 'Flipkart Grocery',
       'Flipkart National', 'Swiggy', 'Zepto', 'Amazon RK', 'City Mall',
       '1MG', 'Dealshare', 'Meesho', 'Nykaa', 'First Cry', 'MYNTRA',
       'Purplle']

In [91]:
for chain in chains:
    if chain not in sales_data['chain'].unique():
        print(chain)

In [92]:
dev_conn = get_dbconnection('DEV')
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment_2""",
    dev_conn
)

realignment_df.columns = realignment_df.columns.str.lower()

def realign_pskus(data, channel='ECOM'):
    realignment_data = realignment_df.copy()
    realignment_data = realignment_data[
        (realignment_data["channel"] == channel)
        | (realignment_data["channel"] == channel + " B2C")
        | (realignment_data["channel"] == "All")
    ]
    assert realignment_data['psku old'].dtype == 'int64'
    assert realignment_data['psku new'].dtype == 'int64'
    realignment_data = realignment_data[['psku old', 'psku new']].drop_duplicates()
    realignment_data = realignment_data.set_index('psku old').to_dict()['psku new']
    
    data["parent_material_code"] = data["parent_material_code"].astype(int)

    for old_psku, new_psku in realignment_data.items():
        data.loc[
            data['parent_material_code'] == old_psku, "parent_material_code"
        ] = new_psku

    return data

Credentials retrieved successfully for dev db.

In [93]:
realigned_df = realign_pskus(sales_data.copy())

In [94]:
realigned_df = realigned_df.groupby(
    ['chain', 'parent_material_code', 'month_date'], as_index=False
).sum()

In [95]:
old_pskus = realignment_df[
    (realignment_df["channel"] == "ECOM")
    | (realignment_df["channel"] == "ECOM" + " B2C")
    | (realignment_df["channel"] == "All")
]['psku old'].unique()

for psku in old_pskus:
    assert psku not in realigned_df['parent_material_code'].unique()

In [96]:
realigned_df['key'] = realigned_df['chain'] + '_' + realigned_df['parent_material_code'].astype(str) 
realigned_df['month_date'] = pd.to_datetime(realigned_df['month_date'])

realigned_df.duplicated(subset=['key', 'month_date']).sum()

0

In [97]:
realigned_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()

0

In [99]:
realigned_df

,chain,parent_material_code,month_date,sec_vol_actuals_rum_month,sec_apo_plan_vol_rum_month,key
0,1MG,715095,2024-01-31,0.0,0.000,1MG_715095
1,1MG,715096,2023-05-31,0.0,0.000,1MG_715096
2,1MG,715096,2023-06-30,0.0,0.189,1MG_715096
3,1MG,715096,2023-07-31,0.0,0.016,1MG_715096
4,1MG,715096,2023-08-31,0.0,0.000,1MG_715096
...,...,...,...,...,...,...
1081559,imli,807033,2025-04-30,0.0,0.000,imli_807033
1081560,imli,807033,2025-05-31,0.0,0.000,imli_807033
1081561,imli,807033,2025-06-30,0.0,0.000,imli_807033
1081562,imli,807033,2025-07-31,0.0,0.000,imli_807033
1081563,imli,807033,2025-08-31,0.0,0.000,imli_807033

In [105]:
trend_file_df['platform_name'].unique()

array(['Amazon', 'Big Basket', 'Flipkart Grocery', 'Flipkart National'],
      dtype=object)

In [106]:
trend_file_df['platform_updated'] = np.where(
    trend_file_df['platform_name'] == 'Amazon', 
    np.where(
        trend_file_df['portfolio'].isin(['Foods', 'Saffola Oils']), 
        'Amazon ARIPL', 
        'Amazon RK'
    ),
    trend_file_df['platform_name']
)

In [108]:
trend_file_df['platform_updated'].unique()

array(['Amazon RK', 'Big Basket', 'Flipkart Grocery', 'Flipkart National',
       'Amazon ARIPL'], dtype=object)

In [109]:
trend_file_df.groupby(
    'platform_name'
)['platform_updated'].unique()

platform_name
Amazon               [Amazon RK, Amazon ARIPL]
Big Basket                        [Big Basket]
Flipkart Grocery            [Flipkart Grocery]
Flipkart National          [Flipkart National]
Name: platform_updated, dtype: object

In [102]:
trend_file_df['portfolio']

0             Hair Oils
1             Hair Oils
2             Hair Oils
3             Hair Oils
4             Hair Oils
              ...
120441    Male Grooming
120442    Male Grooming
120443    Male Grooming
120444    Male Grooming
120445    Male Grooming
Name: portfolio, Length: 120446, dtype: object

In [113]:
trend_file_df['key'] = trend_file_df[
    ['platform_updated', 'parent_material_code']].astype(str).agg('_'.join, axis=1)

In [116]:
len_before_merge = len(trend_file_df)
trend_file_df = trend_file_df.merge(
    realigned_df[['key', 'month_date', 'sec_vol_actuals_rum_month']],
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(trend_file_df)
del len_before_merge