In [1]:
import pandas as pd

In [2]:
from maricovault.MaricoDB import MaricoSnowflake

def get_dbconnection(db_name):    

    KEY_VAULT_NAME = "prod-pwd"

    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'
    

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection


def read_qtr_ind_rate_table():
    """
    Fetch the club sku information from  DWH_SAP_INDEX_TURNOVER_MONTHWISE table.

    Return:
        qtr_ind_rate_data: pandas dataframe
        - dataframe contains all the results from the index rate table.
    """
    connection = get_dbconnection(db_name='PROD')
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=connection, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    connection.close()
    return qtr_ind_rate


dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

In [3]:
model = pd.read_csv("/data/aman_singh/acuuracy_check/mt_channels Live Run jun'26.csv")
missing = pd.read_csv("/data/aman_singh/acuuracy_check/missing_df_mt_all.csv")

In [4]:
print(model['M month'].unique())

['0' 'M' 'M+1' 'M+2' 'M+3' 'M+4' 'M+5' 'M+6' 'M+7']

In [5]:
print(missing['M month'].unique())

['0' 'M' 'M+1' 'M+2' 'M+3' 'M+4' 'M+5' 'M+6' 'M+7']

In [6]:
model['key'].nunique()

4776

In [7]:
#missing = missing[missing['M month'].notna()]

In [8]:
print(missing['M month'].unique())

['0' 'M' 'M+1' 'M+2' 'M+3' 'M+4' 'M+5' 'M+6' 'M+7']

In [9]:
model['skipped'] = 0
missing['skipped'] = 1

In [10]:
all = pd.concat([
    model, missing
], ignore_index=True)

In [11]:
all['channel'].unique()

array(['MT'], dtype=object)

In [12]:
all.duplicated(subset=['channel', 'key', 'month_date']).sum()

0

In [13]:
# all.to_csv("ALL COMBINATIONS gt Live Run jan'25.csv", index=False)

In [14]:
# all.to_csv('All_combination_Nov25_live_with_festivals.csv', index=False)

In [15]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,npt_eve,print_spends_in_lacs,tv_spends_in_lacs,radio_spends_in_lacs,npt,pt,npd,update_timestamp,drive,outlier
0,BCS1_D530_718472,2023-01-31,57.6,99.9,263.555732,23.58,0.002862,0.004963,0.013094,0.001172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BCS1_D530_718472,2023-02-28,57.6,99.9,262.888668,50.70,0.002862,0.004963,0.013061,0.002519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BCS1_D530_718472,2023-03-31,57.6,99.9,242.359795,29.94,0.002862,0.004963,0.012041,0.001488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BCS1_D530_718472,2023-04-30,57.6,99.9,206.727192,26.22,0.002862,0.004963,0.010271,0.001303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BCS1_D530_718472,2023-05-31,41.4,99.9,162.234479,26.10,0.002057,0.004963,0.008060,0.001297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239206,MCW2_D463_811220,2026-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239207,MCW2_D463_811220,2026-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239208,MCW2_D463_811220,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239209,MCW2_D463_811220,2027-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
all.columns[:60]

Index(['key', 'month_date', 'pred_p3m', 'pred_p6m', 'pred_prophet', 'pred_rf',
       'pred_value_p3m', 'pred_value_p6m', 'pred_value_prophet',
       'pred_value_rf', 'channel', 'asm_area_code', 'depot_code',
       'parent_material_code', 'brand_code', 'diwali', 'diwali_lead_1',
       'diwali_lead_2', 'ganesh_chaturthi', 'ganesh_chaturthi_lead_1',
       'ganesh_chaturthi_lead_2', 'sec_vol_actuals_rum_month_value',
       'pred_best_model', 'pred_value_best_model',
       'sec_vol_actuals_rum_month_treated',
       'sec_vol_actuals_rum_month_value_treated', 'train_till', 'cov', 'run',
       'step', 'file_path', 'run_month', 'M month', 'pred_prophet_60%ile',
       'pred_prophet_70%ile', 'portfolio', 'qtr_ind_rate',
       'sec_vol_actuals_rum_month', 'P3M', 'P6M', 'LY P3M', 'LY P6M',
       'LY P3M_copy', 'P3M Max', 'P3M Top 2 Mean', 'MoM P3M growth',
       'MoM P3M growth_lag_1', 'MoM P3M growth_lag_2',
       '>=20%_3M_inc_month_count', 'Avg(P3M Mean, Max)', 'P3M_value',
       'P6M_value', 'LY P3M_value', 'LY P6M_value',
       'pred_prophet_70%ile_value', 'pred_prophet_60%ile_value', 'LY', 'LLY',
       'LY value', 'LLY value'],
      dtype='object')

In [17]:
all.columns[60:]

Index(['Sec_Value_in_Cr_lag_1', 'Sec_Value_in_Cr_lag_2',
       'Sec_Value_in_Cr_lag_3', 'ASM', 'Depot', 'PSKU', 'class', 'skipped',
       'npd_flag', 'free', 'extra_vol_co', 'other_co', 'price_off_co',
       'seasonal_month_flag', 'fill_rate', 'republic_day', 'holi',
       'good_friday', 'maharashtra_day', 'bakri_eid', 'independence_day',
       'gandhi_jayanthi', 'dussehra', 'christmas', 'ramzan_eid', 'new_year',
       'gudi_padwa', 'rm_price', 'raw_material', 'mrp', 'ec', 'pc', 'btl_flag',
       'grp_npt', 'npt_aft', 'npt_morn', 'grp_pt', 'pt_eve', 'npt_eve',
       'print_spends_in_lacs', 'tv_spends_in_lacs', 'radio_spends_in_lacs',
       'npt', 'pt', 'npd', 'update_timestamp', 'drive', 'outlier'],
      dtype='object')

In [18]:
import pandas as pd
import numpy as np
import pymannkendall as mk

def detect_trend_for_group(df_grp):
    """
    Detect final trend flag and p3m_slope_flag separately.
    Must contain 'month_date', 'vol_in_rum', 'run_month'
    """

    # ---------- 1. Sort ----------
    df_grp = df_grp.sort_values("month_date")

    # ---------- 2. Identify run_month ----------
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]

    # if no actual data → no trend
    if df_actual.empty or len(df_actual) < 4:
        return pd.Series({"trend_flag": 0, "p3m_slope_flag": 0})

    # ---------- 3. MK Trend ----------
    series = df_actual["sec_vol_actuals_rum_month_value"].astype(float)

    try:
        mk_result = mk.original_test(series)
        if mk_result.trend == "increasing":
            mk_trend = 1
        elif mk_result.trend == "decreasing":
            mk_trend = -1
        else:
            mk_trend = 0
    except:
        mk_trend = 0

    # ---------- 4. P3M Slope ----------
    # last 4 months → take last 3 with shift
    #shifted_series = series.shift(1).dropna()

    p3m_values = series.tail(3).values
    #print(p3m_values)

    if len(p3m_values) < 3:
        slope_flag = 0
    else:
        x = np.arange(3)
        slope = np.polyfit(x, p3m_values, 1)[0]
        slope_flag = 1 if slope > 0 else (-1 if slope < 0 else 0)
        

    return pd.Series({
        "trend_flag": mk_trend,
        "p3m_slope_flag": slope_flag
    })


# ---------------------------------------------------------
# APPLY ON ENTIRE DATASET
# ---------------------------------------------------------

# trend_df = final_df.groupby(
#     ["platform_name", "parent_material_code"]
# ).apply(detect_trend_for_group).reset_index()

# trend_df = final_df[final_df['key'] == 'Zepto_721898'].groupby(
#     ["platform_name", "parent_material_code", "run_month"]
# ).apply(detect_trend_for_group).reset_index()
trend_df = all.groupby(
    ['channel','key',"run_month"]
).apply(detect_trend_for_group).reset_index()

In [19]:
trend_df["final_trend"] = np.where(
    (trend_df["trend_flag"] == 1) & (trend_df["p3m_slope_flag"] == 1), 1,
    np.where(
        (trend_df["trend_flag"] == -1) & (trend_df["p3m_slope_flag"] == -1), -1,
        0
    )
)
trend_df

,channel,key,run_month,trend_flag,p3m_slope_flag,final_trend
0,MT,BCE1_D231_718303,2026-06-30,-1,1,0
1,MT,BCE1_D231_718312,2026-06-30,0,-1,0
2,MT,BCE1_D231_718317,2026-06-30,0,1,0
3,MT,BCE1_D231_718318,2026-06-30,-1,1,0
4,MT,BCE1_D231_718322,2026-06-30,-1,0,0
...,...,...,...,...,...,...
7023,MT,MCW2_D463_811097,2026-06-30,0,1,0
7024,MT,MCW2_D463_811100,2026-06-30,0,0,0
7025,MT,MCW2_D463_811218,2026-06-30,0,-1,0
7026,MT,MCW2_D463_811219,2026-06-30,0,1,0
7027,MT,MCW2_D463_811220,2026-06-30,0,1,0

In [20]:
trend_df[trend_df['final_trend'] == 1]

,channel,key,run_month,trend_flag,p3m_slope_flag,final_trend
45,MT,BCE1_D231_725327,2026-06-30,1,1,1
84,MT,BCE2_D465_718318,2026-06-30,1,1,1
108,MT,BCE2_D465_718617,2026-06-30,1,1,1
117,MT,BCE2_D465_719045,2026-06-30,1,1,1
122,MT,BCE2_D465_724154,2026-06-30,1,1,1
...,...,...,...,...,...,...
6945,MT,MCW2_D463_721195,2026-06-30,1,1,1
6946,MT,MCW2_D463_721196,2026-06-30,1,1,1
6947,MT,MCW2_D463_721427,2026-06-30,1,1,1
6988,MT,MCW2_D463_731857,2026-06-30,1,1,1
6996,MT,MCW2_D463_735192,2026-06-30,1,1,1

## detect seasonality

In [21]:
from statsmodels.tsa.stattools import acf
import numpy as np
import pandas as pd

def detect_yearly_seasonality(df_grp, threshold=0.3):
    """
    Detects yearly seasonality using ACF at lag=12 only.
    Uses vol_in_rum as the metric.
    """
    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # actual data = months < run_month
    df_actual = df_grp[df_grp["month_date"] < run_month]
    series = df_actual["sec_vol_actuals_rum_month_value"].astype(float).values

    # Need at least 18 points to compare last year vs this year
    if len(series) < 18:
        return 0

    # Compute ACF up to lag-12
    acf_vals = acf(series, nlags=12, fft=False)

    lag12_acf = acf_vals[12]

    # absolute ACF because seasonal correlation can be negative as well
    if abs(lag12_acf) >= threshold:
        return 1
    else:
        return 0
    

seasonality_df = all.groupby(
    ['channel','ASM', 'Depot', 'brand_code',"run_month"]
).apply(detect_yearly_seasonality).reset_index(name="seasonality_flag")

seasonality_df

/data/aman_singh/.env_myvenv/lib/python3.10/site-packages/statsmodels/tsa/stattools.py:702: RuntimeWarning: invalid value encountered in divide
  acf = avf[: nlags + 1] / avf[0]
/data/aman_singh/.env_myvenv/lib/python3.10/site-packages/statsmodels/tsa/stattools.py:702: RuntimeWarning: invalid value encountered in divide
  acf = avf[: nlags + 1] / avf[0]

     channel   ASM Depot brand_code   run_month  seasonality_flag
0         MT  BCE1  D231        H&C  2026-06-30                 0
1         MT  BCE1  D231  H&C_ALMND  2026-06-30                 0
2         MT  BCE1  D231  LIVON S-R  2026-06-30                 0
3         MT  BCE1  D231  NHR-SABDM  2026-06-30                 0
4         MT  BCE1  D231  NHR_VTEHO  2026-06-30                 0
...      ...   ...   ...        ...         ...               ...
1978      MT  MCW2  D463  SF_MNCHPS  2026-06-30                 0
1979      MT  MCW2  D463  SF_SOYACN  2026-06-30                 0
1980      MT  MCW2  D463   SW HRGEL  2026-06-30                 0
1981      MT  MCW2  D463  SW_HR_WAX  2026-06-30                 0
1982      MT  MCW2  D463  TRU_ELMNT  2026-06-30                 0

[1983 rows x 6 columns]

In [22]:
seasonality_df[seasonality_df['seasonality_flag'] == 1]

     channel   ASM Depot brand_code   run_month  seasonality_flag
195       MT  BCN2  D117   P_EN_ALM  2026-06-30                 1
288       MT  BCS2  D673  ADV-AHO-R  2026-06-30                 1
366       MT  BCW1  D314  PA_SHMP_R  2026-06-30                 1
396       MT  BCW1  D354  PA_EXT_ML  2026-06-30                 1
432       MT  BCW1  D464  PA_SHMP_R  2026-06-30                 1
456       MT  BCW2  D356  PA-ALO-HO  2026-06-30                 1
471       MT  BCW2  D356  SAFF GOLD  2026-06-30                 1
544       MT  MCE1  D231  LVN_PRFSR  2026-06-30                 1
555       MT  MCE1  D231   PADV-HOT  2026-06-30                 1
797       MT  MCE2  D463    SAFF KO  2026-06-30                 1
808       MT  MCE2  D465  MALT-NATU  2026-06-30                 1
825       MT  MCE2  D465  P_AL_GOLD  2026-06-30                 1
834       MT  MCE2  D465    SAFF KO  2026-06-30                 1
864       MT  MCE2  D535   PADV-HOT  2026-06-30                 1
898       MT  MCE2  D535  SW STLDEO  2026-06-30                 1
921       MT  MCN1  D112  PADVJAS-R  2026-06-30                 1
931       MT  MCN1  D112  P_AL_GOLD  2026-06-30                 1
1105      MT  MCN2  D115  SF_MNCHPS  2026-06-30                 1
1134      MT  MCN2  D117  PA_EXT_ML  2026-06-30                 1
1166      MT  MCN2  D117  SW_HR_WAX  2026-06-30                 1
1177      MT  MCS1  D530     HC SNS  2026-06-30                 1
1267      MT  MCS1  D572  PADV_SMPN  2026-06-30                 1
1303      MT  MCS1  D572   SW NOGAS  2026-06-30                 1
1329      MT  MCS1  D674  PADV_SMPN  2026-06-30                 1
1369      MT  MCS1  D676  LVN_PRFSR  2026-06-30                 1
1390      MT  MCS1  D676  P_AL_GOLD  2026-06-30                 1
1420      MT  MCS1  D676   SW_SGPRF  2026-06-30                 1
1428      MT  MCS2  D673    KAYA_ML  2026-06-30                 1
1432      MT  MCS2  D673  LVN_PRFSR  2026-06-30                 1
1434      MT  MCS2  D673  LVN_SRSNS  2026-06-30                 1
1442      MT  MCS2  D673  PABABY_CM  2026-06-30                 1
1450      MT  MCS2  D673  PADV_SMPN  2026-06-30                 1
1493      MT  MCS2  D673  SW STLDEO  2026-06-30                 1
1528      MT  MCS2  D674  P_AL_GOLD  2026-06-30                 1
1551      MT  MCS2  D674  SF_MNCHPS  2026-06-30                 1
1576      MT  MCS2  D676  PADV_SMPN  2026-06-30                 1
1632      MT  MCS2  D677  PA-ALO-HO  2026-06-30                 1
1635      MT  MCS2  D677  PADV-HRCR  2026-06-30                 1
1636      MT  MCS2  D677  PADVJAS-R  2026-06-30                 1
1637      MT  MCS2  D677  PADV_SMPN  2026-06-30                 1
1668      MT  MCS2  D677  SW STLDEO  2026-06-30                 1
1768      MT  MCW1  D354   SW_SGPRF  2026-06-30                 1
1823      MT  MCW2  D356    KAYA_GM  2026-06-30                 1
1863      MT  MCW2  D356    SAFF KO  2026-06-30                 1
1871      MT  MCW2  D356  SAF_PNBTR  2026-06-30                 1
1876      MT  MCW2  D356  SF_MNCHPS  2026-06-30                 1
1879      MT  MCW2  D356  SW STLDEO  2026-06-30                 1
1880      MT  MCW2  D356  SW_HR_WAX  2026-06-30                 1
1892      MT  MCW2  D461  PA-ALO-HO  2026-06-30                 1
1947      MT  MCW2  D463   PADV-HOT  2026-06-30                 1
1958      MT  MCW2  D463  P_AL_GOLD  2026-06-30                 1
1967      MT  MCW2  D463    SAFF KO  2026-06-30                 1

In [23]:
# seasonality_df.to_csv('seasonality_all2.csv')

In [24]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,npt_eve,print_spends_in_lacs,tv_spends_in_lacs,radio_spends_in_lacs,npt,pt,npd,update_timestamp,drive,outlier
0,BCS1_D530_718472,2023-01-31,57.6,99.9,263.555732,23.58,0.002862,0.004963,0.013094,0.001172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BCS1_D530_718472,2023-02-28,57.6,99.9,262.888668,50.70,0.002862,0.004963,0.013061,0.002519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BCS1_D530_718472,2023-03-31,57.6,99.9,242.359795,29.94,0.002862,0.004963,0.012041,0.001488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BCS1_D530_718472,2023-04-30,57.6,99.9,206.727192,26.22,0.002862,0.004963,0.010271,0.001303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BCS1_D530_718472,2023-05-31,41.4,99.9,162.234479,26.10,0.002057,0.004963,0.008060,0.001297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239206,MCW2_D463_811220,2026-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239207,MCW2_D463_811220,2026-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239208,MCW2_D463_811220,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
239209,MCW2_D463_811220,2027-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
import numpy as np
import pandas as pd

def compute_thresholds(df_grp):
    """
    df_grp MUST contain:
    - month_date
    - vol_in_rum
    - run_month

    Returns: lower_threshold, upper_threshold, mean, std
    """

    df_grp = df_grp.sort_values("month_date")
    run_month = df_grp["run_month"].max()

    # --- Use ONLY actual data (strictly before run month)
    df_actual = df_grp[df_grp["month_date"] < run_month]

    series = df_actual["sec_vol_actuals_rum_month_value"].astype(float).values

    # If no real data → return zeros
    if len(series) == 0:
        return pd.Series({
            "lower_threshold": 0,
            "upper_threshold": 0,
            "mean_value": 0,
            "std_value": 0
        })

    # --- Take last 12 months OR all available
    if len(series) > 12:
        series = series[-12:]

    mean_val = np.mean(series)
    std_val = np.std(series)

    # --- SPECIAL CASE: ≤3 data points
    if len(series) <= 3:
        lower = 0.5 * mean_val
        upper = 2 * mean_val

        return pd.Series({
            "lower_threshold": lower,
            "upper_threshold": upper,
            "mean_value": mean_val,
            "std_value": std_val
        })

    # --- Normal case (std can be zero also)
    lower = max(0,mean_val - 2*std_val)
    upper = mean_val + 3*std_val

    return pd.Series({
        "lower_threshold": lower,
        "upper_threshold": upper,
        "mean_value": mean_val,
        "std_value": std_val
    })

threshold_df = all.groupby(
    ["channel", "key","run_month"]
).apply(compute_thresholds).reset_index()

threshold_df.head()

,channel,key,run_month,lower_threshold,upper_threshold,mean_value,std_value
0,MT,BCE1_D231_718303,2026-06-30,0.000000,0.001521,0.000461,0.000353
1,MT,BCE1_D231_718312,2026-06-30,0.000169,0.005568,0.002328,0.001080
2,MT,BCE1_D231_718317,2026-06-30,0.000000,0.006868,0.001164,0.001901
3,MT,BCE1_D231_718318,2026-06-30,0.000000,0.005676,0.000978,0.001566
4,MT,BCE1_D231_718322,2026-06-30,0.000000,0.005366,0.000929,0.001479

In [26]:
trend_df = trend_df.merge(threshold_df, on = ["channel", "key","run_month"], how = 'left')
trend_df

,channel,key,run_month,trend_flag,p3m_slope_flag,final_trend,lower_threshold,upper_threshold,mean_value,std_value
0,MT,BCE1_D231_718303,2026-06-30,-1,1,0,0.000000,0.001521,0.000461,0.000353
1,MT,BCE1_D231_718312,2026-06-30,0,-1,0,0.000169,0.005568,0.002328,0.001080
2,MT,BCE1_D231_718317,2026-06-30,0,1,0,0.000000,0.006868,0.001164,0.001901
3,MT,BCE1_D231_718318,2026-06-30,-1,1,0,0.000000,0.005676,0.000978,0.001566
4,MT,BCE1_D231_718322,2026-06-30,-1,0,0,0.000000,0.005366,0.000929,0.001479
...,...,...,...,...,...,...,...,...,...,...
7023,MT,MCW2_D463_811097,2026-06-30,0,1,0,0.000000,0.000571,0.000132,0.000146
7024,MT,MCW2_D463_811100,2026-06-30,0,0,0,0.000088,0.000353,0.000177,0.000000
7025,MT,MCW2_D463_811218,2026-06-30,0,-1,0,0.000000,0.002735,0.000909,0.000609
7026,MT,MCW2_D463_811219,2026-06-30,0,1,0,0.000000,0.002794,0.000680,0.000705
7027,MT,MCW2_D463_811220,2026-06-30,0,1,0,0.000000,0.002852,0.000962,0.000630

In [27]:
# trend_df.to_csv('t_thres_df_2.csv')

In [28]:
all.shape

(239210, 108)

In [29]:
all = all.merge(seasonality_df, on = ['channel','ASM', 'Depot', 'brand_code',"run_month"], how = 'left')
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,print_spends_in_lacs,tv_spends_in_lacs,radio_spends_in_lacs,npt,pt,npd,update_timestamp,drive,outlier,seasonality_flag
0,BCS1_D530_718472,2023-01-31,57.6,99.9,263.555732,23.58,0.002862,0.004963,0.013094,0.001172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,BCS1_D530_718472,2023-02-28,57.6,99.9,262.888668,50.70,0.002862,0.004963,0.013061,0.002519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,BCS1_D530_718472,2023-03-31,57.6,99.9,242.359795,29.94,0.002862,0.004963,0.012041,0.001488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,BCS1_D530_718472,2023-04-30,57.6,99.9,206.727192,26.22,0.002862,0.004963,0.010271,0.001303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,BCS1_D530_718472,2023-05-31,41.4,99.9,162.234479,26.10,0.002057,0.004963,0.008060,0.001297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
239206,MCW2_D463_811220,2026-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
239207,MCW2_D463_811220,2026-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
239208,MCW2_D463_811220,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
239209,MCW2_D463_811220,2027-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [30]:
trend_df.columns

Index(['channel', 'key', 'run_month', 'trend_flag', 'p3m_slope_flag',
       'final_trend', 'lower_threshold', 'upper_threshold', 'mean_value',
       'std_value'],
      dtype='object')

In [31]:
all = all.merge(trend_df[["channel", "key","run_month",
                                    'final_trend','lower_threshold', 'upper_threshold']], on = ["channel", "key","run_month"], how = 'left')
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,npt,pt,npd,update_timestamp,drive,outlier,seasonality_flag,final_trend,lower_threshold,upper_threshold
0,BCS1_D530_718472,2023-01-31,57.6,99.9,263.555732,23.58,0.002862,0.004963,0.013094,0.001172,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.009318
1,BCS1_D530_718472,2023-02-28,57.6,99.9,262.888668,50.70,0.002862,0.004963,0.013061,0.002519,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.009318
2,BCS1_D530_718472,2023-03-31,57.6,99.9,242.359795,29.94,0.002862,0.004963,0.012041,0.001488,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.009318
3,BCS1_D530_718472,2023-04-30,57.6,99.9,206.727192,26.22,0.002862,0.004963,0.010271,0.001303,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.009318
4,BCS1_D530_718472,2023-05-31,41.4,99.9,162.234479,26.10,0.002057,0.004963,0.008060,0.001297,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.009318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.002852
239206,MCW2_D463_811220,2026-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.002852
239207,MCW2_D463_811220,2026-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.002852
239208,MCW2_D463_811220,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.002852
239209,MCW2_D463_811220,2027-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.002852

In [32]:
all = all.sort_values(['channel','key', 'month_date'])

# base LY


# LY lags
all['ly_lag1_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(13)
)

all['ly_lag2_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(14)
)

# LY leads
all['ly_lead1_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(11)
)

all['ly_lead2_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(10)
)

In [33]:
all[all.select_dtypes(include='number').columns] = all.select_dtypes(include='number').fillna(0)
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,drive,outlier,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value
104138,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104139,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104140,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104141,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104142,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.001624
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.001624,0.000000

In [34]:
# all.to_csv('break.csv')

In [35]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,drive,outlier,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value
104138,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104139,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104140,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104141,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
104142,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,0.0,0.0,0,0,0.0,0.001521,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.000000
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.000000,0.001624
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.002852,0.0,0.0,0.001624,0.000000

In [36]:
brand_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'brand')
brand_seas.columns = brand_seas.columns.str.lower()
brand_seas.rename(columns={'brand':'brand_code', 'months_num':'month', 'flag':'is_seasonal_month'}, inplace=True)

all['month_date'] = pd.to_datetime(all['month_date'])
all['month'] = all['month_date'].dt.month
all = all.merge(brand_seas, on = ['brand_code', 'month'], how = 'left')
all['is_seasonal_month'].fillna(0, inplace=True)

psku_seas = pd.read_excel('/data/aman_singh/acuuracy_check/seasonality.xlsx', sheet_name = 'psku')
psku_seas.columns = psku_seas.columns.str.lower()
psku_seas.rename(columns={'months_num':'month', 'flag':'is_seasonal_month_psku'}, inplace=True)

all = all.merge(psku_seas[['parent_material_code', 'month','is_seasonal_month_psku']], on = ['parent_material_code', 'month'], how = 'left')
all['is_seasonal_month_psku'].fillna(0, inplace=True)
all['final_seasonal_month'] = np.where(
    (all['is_seasonal_month'] == 1) | (all['is_seasonal_month_psku'] == 1), 1, 0
)

/tmp/ipykernel_2204806/2808109073.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  all['month'] = all['month_date'].dt.month

In [37]:
all['run_month'] = pd.to_datetime(all['run_month'])
def compute_adjusted_pm(df_grp, window, column, year_shift=0):
    df_grp = df_grp.sort_values("month_date")

    run_month = df_grp["run_month"].iloc[0]

    # define cutoff
    end_date = run_month - pd.DateOffset(years=year_shift)

    # keep only eligible history (before run month & non-event)
    hist = df_grp[
        (df_grp["month_date"] < end_date) &
        (df_grp["final_seasonal_month"] == 0)
    ]

    if hist.empty:
        return np.nan

    # take last `window` non-event months
    hist = hist.tail(window)

    # if len(hist) < window:
    #     return np.nan   # optional, keeps behavior strict

    return hist[column].mean()

adj_df = all.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "P3M_non_seasonal": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month',0),
        "P6M_non_seasonal": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month',0),
        "P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month_value',0),
        "P6M_non_seasonal_value": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month_value',0)
    })
).reset_index()
adj_df


adj_ly_df = all.groupby(
    ['key', "run_month"]
).apply(
    lambda x: pd.Series({
        "LY_P3M_non_seasonal": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month',year_shift=1),
        "LY_P6M_non_seasonal": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month', year_shift=1),
        "LY_P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month_value', year_shift=1),
        "LY_P6M_non_seasonal_value": compute_adjusted_pm(x, 6,"sec_vol_actuals_rum_month_value", year_shift=1)
    })
).reset_index()

adj_df = adj_df.merge(adj_ly_df, on = ['key', 'run_month'], how = 'left')
#adj_df[adj_df['key'] == 'reliance_b2c_2_haryana_718488']
adj_df

,key,run_month,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,BCE1_D231_718303,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021000,0.000116,0.000521
1,BCE1_D231_718312,2026-06-30,0.040000,0.056667,0.001397,0.001979,0.000000,0.050000,0.000000,0.001746
2,BCE1_D231_718317,2026-06-30,14.400000,19.200000,0.000559,0.000745,0.000000,9.600000,0.000000,0.000373
3,BCE1_D231_718318,2026-06-30,28.800000,26.400000,0.001118,0.001025,9.600000,21.600000,0.000373,0.000838
4,BCE1_D231_718322,2026-06-30,0.000000,0.000000,0.000000,0.000000,0.093333,0.113333,0.001576,0.001913
...,...,...,...,...,...,...,...,...,...,...
7023,MCW2_D463_811097,2026-06-30,0.001667,0.003750,0.000059,0.000132,NaN,NaN,NaN,NaN
7024,MCW2_D463_811100,2026-06-30,0.005000,0.005000,0.000177,0.000177,NaN,NaN,NaN,NaN
7025,MCW2_D463_811218,2026-06-30,0.024000,0.025750,0.000847,0.000909,NaN,NaN,NaN,NaN
7026,MCW2_D463_811219,2026-06-30,0.010333,0.019250,0.000365,0.000680,NaN,NaN,NaN,NaN
7027,MCW2_D463_811220,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

In [38]:
#adj_df.to_csv('seasonal_p3m_mt.csv', index=False)
#all[all['month_date'].isin(['2025-11-30','2025-12-31','2026-01-31'])].groupby(['key','run_month','month_date','final_seasonal_month'])['vol_in_rum'].sum().reset_index().to_csv('seasonal_month_check.csv', index=False)
all = all.merge(
    adj_df,
    on=['key'],
    how="left"
)
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
1,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
2,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
3,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
4,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

In [39]:
# all[(all['month']==4) & (all['final_seasonal_month'] == 1)]['brand_code'].unique()

In [40]:
all[(all['final_seasonal_month'] == 1)]['brand_code'].unique()

array(['REV.LQDST', 'PCNO(R)', 'REV.ST.', 'PADV-HOT', 'SF_SOYACN',
       'SAF_HONEY', 'PA-BDYLOT', 'SW STLDEO', 'NHR_SSAHO', 'PA_CN_HO'],
      dtype=object)

In [41]:
# all[all['brand_code']=='PADV-HOT'].groupby(['key'])['sec_vol_actuals_rum_month_value'].sum().reset_index().sort_values('sec_vol_actuals_rum_month_value', ascending=False)

In [42]:
# all[all['key']=='DELM_D115_718449'].to_csv('ses_chek.csv')

In [43]:
all[all['month_date']<='2026-03-31']

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
1,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
2,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
3,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
4,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239175,MCW2_D463_811218,2026-03-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.024000,0.025750,0.000847,0.000909,NaN,NaN,NaN,NaN
239186,MCW2_D463_811219,2026-02-28,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.010333,0.019250,0.000365,0.000680,NaN,NaN,NaN,NaN
239187,MCW2_D463_811219,2026-03-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.010333,0.019250,0.000365,0.000680,NaN,NaN,NaN,NaN
239198,MCW2_D463_811220,2026-02-28,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239199,MCW2_D463_811220,2026-03-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

### co p3m

In [44]:
# query = """select * from TRN_MIL_CO_DATA where month_date >= '2025-01-31'"""
# co_df = pd.read_sql(query, con=dev_conn)
# co_df

In [45]:
# co_df.columns = co_df.columns.str.lower()
# co_df.columns

In [46]:
# all = pd.read_csv('break.csv')
# all

In [47]:
# all['co_flag'] = ((all['extra_vol_co'] == 1) | (all['other_co'] == 1) | (all['price_off_co'] == 1)).astype(int)
# all

In [48]:
# all[all['co_flag'] == 1]

In [49]:
# co_df = co_df[co_df['co_flag'] == 1]
# co_df = co_df[co_df['channel'] == 'GT']
# co_df

In [50]:
# co_df['asm_area_code'].unique()

In [51]:
# realignment_df = pd.read_sql(
#     'select * from trn_mil_asm_psku_realignment',
#     dev_conn
# )
# realignment_df.columns = realignment_df.columns.str.lower()

# def demand_driver_realign_pskus(data):
#         """
#         Realign the old pskus to new pskus and return updated data.

#         Args:
#             data: pandas dataframe
#             - master dataframe having all the pskus
        
#         Return:
#             data: pandas dataframe
#             - dataframe 
#         """
#         realignment_data = realignment_df.copy()
#         realignment_data.columns = realignment_data.columns.str.lower()
#         realignment_data = realignment_data[
#             (realignment_data["channel"] == 'GT')
#             | (realignment_data["channel"] == 'GT' + " B2C")
#             | (realignment_data["channel"] == "ALL")
#         ]

#         data["parent_material_code"] = data["parent_material_code"].astype(int)

#         for grp, grp_data in realignment_data.groupby(by=["psku old", "asm"]):
#             old_psku, old_asm = grp
#             new_psku = grp_data["psku new"].values[0]
#             if old_asm != "ALL":
#                 condition = (data["parent_material_code"] == old_psku) & (
#                     data["asm_area_code"] == old_asm
#                 )
#             else:
#                 condition = data["parent_material_code"] == old_psku

#             data.loc[condition, "parent_material_code"] = new_psku

#         return data

In [52]:
# co_data = co_df.rename( columns= {'regionhierarchy':'asm_area_code'})
# co_data = co_data.replace( { True:1 , False:0})
# co_data = co_data[[ "month_date", 'asm_area_code', "parent_material_code", 'extra_vol_co', 'price_off_co', 'other_co']]
# co_data = demand_driver_realign_pskus(co_data)
# co_data = co_data.groupby(["month_date", 'asm_area_code', "parent_material_code"], as_index=False).max()
# co_data["month_date"] = pd.to_datetime(co_data["month_date"])


# ### (old_asm, new_asm)
# # asm_change_info = [('HUB', 'KARC'), ('HUB', 'KARN'), ('WUP', 'NUP'), ('TPT', 'KUR')]
# asm_change_info = {
#     'KARC': {'old_asm': 'HUB', 'data_available_from': '2025-01-31'},
#     'KARN': {'old_asm': 'HUB', 'data_available_from': '2025-01-31'},
#     'NUP': {'old_asm': 'WUP', 'data_available_from': '2025-01-31'},
#     'KUR': {'old_asm': 'TPT', 'data_available_from': None}
# }


# for new_asm in asm_change_info.keys():
#     old_asm = asm_change_info[new_asm]['old_asm']
#     data_available_from = asm_change_info[new_asm]['data_available_from']

#     if data_available_from is not None:
#         old_asm_df = co_data[
#             (co_data['asm_area_code'] == old_asm) &
#             (co_data['month_date'] < pd.to_datetime(data_available_from))
#         ]
#     else:
#         old_asm_df = co_data[
#             (co_data['asm_area_code'] == old_asm)
#         ]

#     new_asm_df = old_asm_df.copy()
#     new_asm_df['asm_area_code'] = new_asm
#     co_data = pd.concat([co_data, new_asm_df])
    
# co_data = co_data.drop_duplicates()
# assert co_data.duplicated(
#     subset=['asm_area_code', 'parent_material_code', 'month_date']
# ).sum() == 0
# ###

# # co_data = co_data.reset_index(drop=True)
# co_data = co_data.fillna(0)
# all["month_date"] = pd.to_datetime(all["month_date"])

# all = pd.merge(
#     all,
#     co_data,
#     on=["month_date", 'asm_area_code',"parent_material_code"],
#     how="left",
# )

In [53]:
# all

In [54]:
# all = all.fillna(0)
# all['co_flag'] = ((all['extra_vol_co_y'] == 1) | (all['other_co_y'] == 1) | (all['price_off_co_y'] == 1)).astype(int)
# all[all['co_flag'] == 1]

In [55]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
1,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
2,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
3,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
4,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

In [56]:
all.rename(columns = {'run_month_x':'run_month'}, inplace = True)

In [57]:
# all['run_month'] = pd.to_datetime(all['run_month'])
# def compute_adjusted_pm(df_grp, window, column, year_shift=0):
#     df_grp = df_grp.sort_values("month_date")

#     run_month = df_grp["run_month"].iloc[0]

#     # define cutoff
#     end_date = run_month - pd.DateOffset(years=year_shift)

#     # keep only eligible history (before run month & non-event)
#     hist = df_grp[
#         (df_grp["month_date"] < end_date) &
#         (df_grp["co_flag"] == 0)
#     ]

#     if hist.empty:
#         return np.nan

#     # take last `window` non-event months
#     hist = hist.tail(window)

#     # if len(hist) < window:
#     #     return np.nan   # optional, keeps behavior strict

#     return hist[column].mean()

# adj_df = all.groupby(
#     ['key', "run_month"]
# ).apply(
#     lambda x: pd.Series({
#         "P3M_non_co": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month',0),
#         "P6M_non_co": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month',0),
#         "P3M_non_co_value": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month_value',0),
#         "P6M_non_co_value": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month_value',0)
#     })
# ).reset_index()
# adj_df


# # adj_ly_df = all.groupby(
# #     ['key', "run_month"]
# # ).apply(
# #     lambda x: pd.Series({
# #         "LY_P3M_non_seasonal": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month',year_shift=1),
# #         "LY_P6M_non_seasonal": compute_adjusted_pm(x, 6,'sec_vol_actuals_rum_month', year_shift=1),
# #         "LY_P3M_non_seasonal_value": compute_adjusted_pm(x, 3,'sec_vol_actuals_rum_month_value', year_shift=1),
# #         "LY_P6M_non_seasonal_value": compute_adjusted_pm(x, 6,"sec_vol_actuals_rum_month_value", year_shift=1)
# #     })
# # ).reset_index()

# # adj_df = adj_df.merge(adj_ly_df, on = ['key', 'run_month'], how = 'left')
# #adj_df[adj_df['key'] == 'reliance_b2c_2_haryana_718488']
# adj_df

In [58]:
# all = all.merge(adj_df, on=['key', 'run_month'], how = 'left')

In [59]:
# all.columns[:60]

In [60]:
# adj_df.to_csv('non_co_p3m_apr.csv')

### co p3m end

In [61]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
0,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
1,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
2,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
3,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
4,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

In [62]:
all['M month'].unique()
all[all['M month']!='0']

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,final_seasonal_month,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value
41,BCE1_D231_718303,2026-06-30,0.023333,0.0185,0.020045,0.0263,0.000578,0.000459,0.000497,0.000652,...,1,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
42,BCE1_D231_718303,2026-07-31,0.023333,0.0185,0.015209,0.0196,0.000578,0.000459,0.000377,0.000486,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
43,BCE1_D231_718303,2026-08-31,0.023333,0.0185,0.017840,0.0195,0.000578,0.000459,0.000442,0.000483,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
44,BCE1_D231_718303,2026-09-30,0.023333,0.0185,0.000000,0.0152,0.000578,0.000459,0.000000,0.000377,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
45,BCE1_D231_718303,2026-10-31,0.023333,0.0185,0.012638,0.0153,0.000578,0.000459,0.000313,0.000379,...,0,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239206,MCW2_D463_811220,2026-10-31,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239207,MCW2_D463_811220,2026-11-30,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239208,MCW2_D463_811220,2026-12-31,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN
239209,MCW2_D463_811220,2027-01-31,0.000000,0.0000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,0,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN

### Current month different logic

In [63]:
# all = pd.read_excel("/data/aman_singh/acuuracy_check/all_combination_GT_channel_trend2.xlsx", sheet_name='all_combination_GT_channel_tren')
# all

In [64]:
x = all.copy()

In [65]:
all.rename(columns = {'run_month_x':'run_month'}, inplace = True)

In [66]:
all_brand = all.groupby(['channel','brand_code', 'run_month','month_date'])['sec_vol_actuals_rum_month_value'].sum().reset_index()
all_brand

     channel brand_code  run_month month_date  sec_vol_actuals_rum_month_value
0         MT  ADV-AHO-R 2026-06-30 2023-01-31                         0.239381
1         MT  ADV-AHO-R 2026-06-30 2023-02-28                         0.466323
2         MT  ADV-AHO-R 2026-06-30 2023-03-31                         0.298219
3         MT  ADV-AHO-R 2026-06-30 2023-04-30                         0.228353
4         MT  ADV-AHO-R 2026-06-30 2023-05-31                         0.272233
...      ...        ...        ...        ...                              ...
3665      MT  TRU_ELMNT 2026-06-30 2026-09-30                         0.000000
3666      MT  TRU_ELMNT 2026-06-30 2026-10-31                         0.000000
3667      MT  TRU_ELMNT 2026-06-30 2026-11-30                         0.000000
3668      MT  TRU_ELMNT 2026-06-30 2026-12-31                         0.000000
3669      MT  TRU_ELMNT 2026-06-30 2027-01-31                         0.000000

[3670 rows x 5 columns]

In [67]:

def detect_month_anomaly(df, brand_code, month_num, threshold=0.25, months_window=3):
    """
    Detect if a specific month's sec_vol_actuals_rum_month_value is >25% different 
    from past 3 months & next 3 months, and if pattern repeats in last 2 years.
    
    Parameters:
    - df: input dataframe with 'month_date', 'sec_vol_actuals_rum_month_value'
    - brand_code: filter by this brand code
    - month_num: month to check (6, 7, 8, 9)
    - threshold: 25% difference threshold
    - months_window: number of months before and after to compare
    """
    
    df_brand = df[df['brand_code'] == brand_code].sort_values('month_date').copy()
    
    if df_brand.empty:
        return None
    
    df_brand['year'] = df_brand['month_date'].dt.year
    df_brand['month'] = df_brand['month_date'].dt.month
    
    years = sorted(df_brand['year'].unique())
    current_year = years[-1]
    past_years = [y for y in years if y < current_year][-2:]
    
    anomalies = []
    
    for year in past_years:
        df_year = df_brand[df_brand['year'] == year].sort_values('month_date')
        
        month_data = df_year[df_year['month'] == month_num]
        if month_data.empty:
            continue
        
        month_value = month_data['sec_vol_actuals_rum_month_value'].iloc[0]
        
        past_months = [(month_num - i - 1) % 12 + 1 for i in range(1, months_window + 1)]
        next_months = [(month_num + i - 1) % 12 + 1 for i in range(1, months_window + 1)]
        
        past_m = df_year[df_year['month'].isin(past_months)]['sec_vol_actuals_rum_month_value']
        next_m = df_year[df_year['month'].isin(next_months)]['sec_vol_actuals_rum_month_value']
        
        comparison_values = pd.concat([past_m])
        
        if comparison_values.empty:
            continue
        
        pct_diffs = []
        for comp_value in comparison_values:
            if comp_value != 0:
                pct_diff = (month_value - comp_value) / comp_value
                pct_diffs.append(pct_diff)
        
        if pct_diffs:
            positive_diffs = [p for p in pct_diffs if p > 0]
            negative_diffs = [p for p in pct_diffs if p < 0]
            same_sign = len(positive_diffs) == len(pct_diffs) or len(negative_diffs) == len(pct_diffs)
            is_anomaly = len([p for p in pct_diffs if abs(p) > threshold]) == len(pct_diffs) and same_sign
        else:
            is_anomaly = False

        anomalies.append({
            'brand_code': brand_code,
            'month': month_num,
            'year': year,
            'month_value': month_value,
            'num_months_compared': len(comparison_values),
            'pct_diffs_from_each': pct_diffs,
            'min_pct_diff': min(pct_diffs) * 100 if pct_diffs else None,
            'max_pct_diff': max(pct_diffs) * 100 if pct_diffs else None,
            'is_anomaly': is_anomaly,
            'direction': 'higher' if month_value > comparison_values.mean() else 'lower'
        })
    
    if len(anomalies) == 2:
        pattern_repeats = anomalies[0]['is_anomaly'] and anomalies[1]['is_anomaly']
        return pd.DataFrame(anomalies), pattern_repeats
    
    return pd.DataFrame(anomalies), False


# Check months 6, 7, 8, 9
brands = all_brand['brand_code'].unique()
results = []

for month in [7, 8, 9,10]:
    for brand in brands:
        df_result, repeats = detect_month_anomaly(all_brand, brand, month)
        if df_result is not None and not df_result.empty:
            df_result['pattern_repeats'] = repeats
            results.append(df_result)

anomaly_summary = pd.concat(results, ignore_index=True)
print(anomaly_summary[anomaly_summary['pattern_repeats'] == True])

    brand_code  month  year  month_value  num_months_compared  \
6    CO_SO_VCN      7  2025     0.038903                    3
7    CO_SO_VCN      7  2026     0.000000                    3
12   H&C_ALMND      7  2025     0.221044                    3
13   H&C_ALMND      7  2026     0.000000                    3
27      KERALA      7  2025     0.000000                    3
..         ...    ...   ...          ...                  ...
336  SFOATS_GD      8  2026     0.000000                    3
351  SW STLDEO      8  2025     0.342135                    3
352  SW STLDEO      8  2026     0.000000                    3
357   SW_SGPRF      8  2025     0.006936                    3
358   SW_SGPRF      8  2026     0.000000                    3

                                   pct_diffs_from_each  min_pct_diff  \
6    [0.42168674698798747, 0.9291553133515412, 0.47...     42.168675
7                                         [-1.0, -1.0]   -100.000000
12   [2.3891323342867294, 2.9703390971440604, 0.674...     67.420716
13                                        [-1.0, -1.0]   -100.000000
27                                        [-1.0, -1.0]   -100.000000
..                                                 ...           ...
336                                             [-1.0]   -100.000000
351  [1.9812546746447524, 0.33459590675093354, 0.53...     33.459591
352                                             [-1.0]   -100.000000
357  [-0.29071803852888217, -0.7789301310043677, -0...    -77.893013
358                                             [-1.0]   -100.000000

     max_pct_diff  is_anomaly direction  pattern_repeats
6       92.915531        True    higher             True
7     -100.000000        True     lower             True
12     297.033910        True    higher             True
13    -100.000000        True     lower             True
27    -100.000000        True     lower             True
..            ...         ...       ...              ...
336   -100.000000        True     lower             True
351    198.125467        True    higher             True
352   -100.000000        True     lower             True
357    -29.071804        True     lower             True
358   -100.000000        True     lower             True

[68 rows x 11 columns]

/tmp/ipykernel_2204806/1346502785.py:93: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  anomaly_summary = pd.concat(results, ignore_index=True)

In [68]:
all.shape

(239210, 130)

In [69]:
final_brands = anomaly_summary[anomaly_summary['pattern_repeats'] == True].drop_duplicates(subset=['brand_code','month'])[['brand_code', 'month','direction', 'min_pct_diff', 'max_pct_diff']]
final_brands['month_different'] = 1
all['month'] = all['month_date'].dt.month
all = all.merge(final_brands[['brand_code', 'month','month_different']], on = ['brand_code','month'], how = 'left')
all['month_different'].fillna(0, inplace=True)
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,run_month_y,P3M_non_seasonal,P6M_non_seasonal,P3M_non_seasonal_value,P6M_non_seasonal_value,LY_P3M_non_seasonal,LY_P6M_non_seasonal,LY_P3M_non_seasonal_value,LY_P6M_non_seasonal_value,month_different
0,BCE1_D231_718303,2023-01-31,0.018667,0.037167,0.039707,0.0196,0.000463,0.000921,0.000984,0.000486,...,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521,0.0
1,BCE1_D231_718303,2023-02-28,0.018667,0.037167,0.035127,0.0196,0.000463,0.000921,0.000871,0.000486,...,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521,0.0
2,BCE1_D231_718303,2023-03-31,0.018667,0.037167,0.037903,0.0209,0.000463,0.000921,0.000940,0.000518,...,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521,0.0
3,BCE1_D231_718303,2023-04-30,0.018667,0.037167,0.045280,0.0392,0.000463,0.000921,0.001123,0.000972,...,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521,0.0
4,BCE1_D231_718303,2023-05-31,0.037333,0.037167,0.051044,0.0307,0.000926,0.000921,0.001266,0.000761,...,2026-06-30,0.013667,0.016167,0.000339,0.000401,0.004667,0.021,0.000116,0.000521,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239205,MCW2_D463_811220,2026-09-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN,0.0
239206,MCW2_D463_811220,2026-10-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN,0.0
239207,MCW2_D463_811220,2026-11-30,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN,0.0
239208,MCW2_D463_811220,2026-12-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN,0.0
239209,MCW2_D463_811220,2027-01-31,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,...,2026-06-30,0.021000,0.027250,0.000741,0.000962,NaN,NaN,NaN,NaN,0.0

In [72]:
all[all['M month'] != '0'].to_csv('all_combination_MT_live_june.csv')

In [74]:
all[all['month_date']<='2026-06-30'].to_csv('/data/aman_singh/acuuracy_check/all_combination_MT_channel_trend.csv')

In [71]:
all[all['month_date'] == '2026-07-31']['P3M_value'].sum()

124.65898072585463

In [52]:
with pd.ExcelWriter('all_combination_MT_live_apr.xlsx', engine='xlsxwriter') as writer:
    all[all['M month'] != '0'].to_excel(
        writer,
        sheet_name='Base',
        index=False
    )
    
    trend_df.to_excel(
        writer,
        sheet_name='threshold',
        index=False
    )

In [29]:
all[all['M month'].notna()].to_csv('/data/aman_singh/acuuracy_check/all_combination_MT_live_feb.csv')

In [2]:
import pandas as pd
all = pd.read_csv('/data/aman_singh/acuuracy_check/all_combination_all_channels_pred3.csv')
all

,Unnamed: 0,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,...,drive,outlier,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value
0,97238,BCE1_D231_718297,2023-01-31,0.223000,0.121,0.097515,0.022833,0.006908,0.003748,0.003021,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
1,97239,BCE1_D231_718297,2023-02-28,0.223000,0.121,0.119242,0.014767,0.006908,0.003748,0.003694,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
2,97240,BCE1_D231_718297,2023-03-31,0.223000,0.121,0.165967,0.033167,0.006908,0.003748,0.005141,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
3,97241,BCE1_D231_718297,2023-04-30,0.223000,0.121,0.121937,0.036867,0.006908,0.003748,0.003777,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
4,97242,BCE1_D231_718297,2023-05-31,0.216667,0.121,0.083432,0.028267,0.006712,0.003748,0.002584,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547679,532698,QCW2_D463_810674,2026-02-28,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
547680,532699,QCW2_D463_810674,2026-03-31,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
547681,532700,QCW2_D463_810674,2026-04-30,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
547682,532701,QCW2_D463_810674,2026-05-31,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
547683,532702,QCW2_D463_810674,2026-06-30,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0

In [25]:
all

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,drive,outlier,seasonality_flag,final_trend,lower_threshold,upper_threshold,ly_lag1_value,ly_lag2_value,ly_lead1_value,ly_lead2_value
97238,BCE1_D231_718297,2023-01-31,0.223000,0.121,0.097515,0.022833,0.006908,0.003748,0.003021,0.000707,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
97239,BCE1_D231_718297,2023-02-28,0.223000,0.121,0.119242,0.014767,0.006908,0.003748,0.003694,0.000457,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
97240,BCE1_D231_718297,2023-03-31,0.223000,0.121,0.165967,0.033167,0.006908,0.003748,0.005141,0.001027,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
97241,BCE1_D231_718297,2023-04-30,0.223000,0.121,0.121937,0.036867,0.006908,0.003748,0.003777,0.001142,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
97242,BCE1_D231_718297,2023-05-31,0.216667,0.121,0.083432,0.028267,0.006712,0.003748,0.002584,0.000876,...,0.0,0.0,0,0,0.0,0.001429,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532698,QCW2_D463_810674,2026-02-28,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
532699,QCW2_D463_810674,2026-03-31,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
532700,QCW2_D463_810674,2026-04-30,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
532701,QCW2_D463_810674,2026-05-31,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0
532702,QCW2_D463_810674,2026-06-30,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0,0,0.0,0.006011,0.0,0.0,0.0,0.0

In [23]:
all = all.sort_values(['channel','key', 'month_date'])

# base LY


# LY lags
all['ly_lag1_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(13)
)

all['ly_lag2_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(14)
)

# LY leads
all['ly_lead1_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(11)
)

all['ly_lead2_value'] = (
    all
    .groupby(['channel','key'])['sec_vol_actuals_rum_month_value']
    .shift(10)
)

In [24]:
all = all.fillna(0)

In [54]:
all[['key','month_date','ly_lag1_value','ly_lag2_value','ly_lead1_value','ly_lead2_value']].to_csv('lead_chk.csv')

In [50]:
all[all['key']=='AURG_D3A4_718288'][['month_date','sec_vol_actuals_rum_month_value','ly_lag1_value','ly_lead1_value']]

,month_date,sec_vol_actuals_rum_month_value,ly_lag1_value,ly_lead1_value
205621,2023-01-31,0.043763,NaN,NaN
205622,2023-02-28,0.021888,NaN,NaN
205623,2023-03-31,0.041092,NaN,NaN
205624,2023-04-30,0.036068,NaN,NaN
205625,2023-05-31,0.032351,NaN,NaN
205626,2023-06-30,0.034416,NaN,NaN
205627,2023-07-31,0.034760,NaN,NaN
205628,2023-08-31,0.036756,NaN,NaN
205629,2023-09-30,0.039096,NaN,NaN
205630,2023-10-31,0.038546,NaN,NaN
205631,2023-11-30,0.040198,NaN,NaN
205632,2023-12-31,0.038201,NaN,0.043763
205633,2024-01-31,0.044190,NaN,0.021888
205634,2024-02-29,0.031938,0.043763,0.041092
205635,2024-03-31,0.028565,0.021888,0.036068
205636,2024-04-30,0.045153,0.041092,0.032351
205637,2024-05-31,0.034072,0.036068,0.034416
205638,2024-06-30,0.042607,0.032351,0.034760
205639,2024-07-31,0.033521,0.034416,0.036756
205640,2024-08-31,0.044121,0.034760,0.039096
205641,2024-09-30,0.075783,0.036756,0.038546
205642,2024-10-31,0.057130,0.039096,0.040198
205643,2024-11-30,0.028565,0.038546,0.038201
205644,2024-12-31,0.054790,0.040198,0.044190
205645,2025-01-31,0.062292,0.038201,0.031938
205646,2025-02-28,0.035655,0.044190,0.028565
205647,2025-03-31,0.038683,0.031938,0.045153
205648,2025-04-30,0.045153,0.028565,0.034072
205649,2025-05-31,0.048526,0.045153,0.042607
205650,2025-06-30,0.052587,0.034072,0.033521
205651,2025-07-31,0.064426,0.042607,0.044121
205652,2025-08-31,0.050040,0.033521,0.075783
205653,2025-09-30,0.056373,0.044121,0.057130
205654,2025-10-31,0.064289,0.075783,0.028565
205655,2025-11-30,0.046530,0.057130,0.054790
205656,2025-12-31,0.055203,0.028565,0.062292
205657,2026-01-31,NaN,0.054790,0.035655
205658,2026-02-28,NaN,0.062292,0.038683
205659,2026-03-31,NaN,0.035655,0.045153
205660,2026-04-30,NaN,0.038683,0.048526
205661,2026-05-31,NaN,0.045153,0.052587
205662,2026-06-30,NaN,0.048526,0.064426