In [1]:
import warnings
warnings.filterwarnings('ignore')

import os
import pickle

import numpy as np
import pandas as pd

from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from pandas.tseries.offsets import MonthEnd, MonthBegin
from maricovault.MaricoDB import MaricoSnowflake

from joblib import Parallel, delayed

In [2]:
def get_dbconnection(db_name): 

    KEY_VAULT_NAME = "prod-pwd"
    if db_name == 'PROD':
        db_name = 'prod'
    else:
        db_name = 'dev'

    msf = MaricoSnowflake(KEY_VAULT_NAME)
    msf.get_db_credentials(db_name=db_name)
    msf.connect()
    dbconnection = msf.get_connection()
    
    return dbconnection

In [3]:
dev_conn = get_dbconnection('DEV')
prod_conn = get_dbconnection('PROD')

Credentials retrieved successfully for dev db.

Credentials retrieved successfully for prod db.

### Helper Functions

In [4]:
realignment_df = pd.read_sql(
    """select * from trn_mil_asm_psku_realignment""",
    dev_conn
)
realignment_df.columns = realignment_df.columns.str.lower()

realignment_df = realignment_df[
    realignment_df['channel'].isin(['ECOM', 'ECOM B2C', 'ALL'])]


def realign_pskus(data, column):
    realignment_data = realignment_df.copy()
    assert realignment_data['psku old'].dtype == 'int64'
    assert realignment_data['psku new'].dtype == 'int64'
    realignment_data = realignment_data[['psku old', 'psku new']].drop_duplicates()
    realignment_data = realignment_data.set_index('psku old').to_dict()['psku new']

    
    data[column] = data[column].astype(int)

    for old_psku, new_psku in realignment_data.items():
        data.loc[
            data[column] == old_psku, column
        ] = new_psku

    return data

In [5]:
realignment_df

,psku realignment master,parent material_code old,asm,channel,new parent_material code,deletion indicator?,psku old,psku new
1,726067_ALL_E-Commerce,726067_SMO CLS MSL 500G MILLET MT ECOM B2C,ALL,ECOM,730975_SMO CLS MSL 550G MILLET MT ECOM,None,726067,730975
8,726065_ALL_E-Commerce,726065_SMO VEG TWST 500G MILLET MT ECOM,ALL,ECOM,731006_SMO VEG TWST 550G MILLET MT ECOM,None,726065,731006
9,726066_ALL_E-Commerce,726066_SMO PEP TOM 500G MILLET MT ECOM,ALL,ECOM,731008_SMO PEP TOM 550G MILLET MT ECOM,None,726066,731008
10,718574_ALL_E-Commerce,718574_SMO MSL&COR 500g PCH,ALL,ECOM,731007_SMO MAS COR 550G MILLET MT ECOM,None,718574,731007
135,718588_ALL_E-Commerce,718588_SETWET HAIRGEL ULTIMATE HOLD 250ml JAR,ALL,ECOM,730277_SW SPORTS EXTREM 250ML MT ECOM NF,None,718588,730277
...,...,...,...,...,...,...,...,...
444,725000_ALL_E-Commerce,725000_NHR NSSA 175ML BOT PARENT,ALL,ECOM,736141_NHR SRSO AMLBDM 175ML,None,725000,736141
445,730151_ALL_E-Commerce,730151_SW COL+CHM+SWG PACK OF 3 (180x3),ALL,ECOM,718734_SETWET STYLEDEO CL+CH+SWG 450ml CAN,None,730151,718734
447,730149_ALL_E-Commerce,730149_SW COL+CHM+MIS PACK OF 3 (180X3),ALL,ECOM,718731_SETWET STYLDEO CL+CH+MC ECOM 450ml CAN,None,730149,718731
449,718641_ALL_E-Commerce,718641_SETWET STYLEDEO CHARM AVATAR 150ml CAN,ALL,ECOM,718640_SETWET STYLEDEO COOL AVATAR 150ml CAN,None,718641,718640
451,718643_ALL_E-Commerce,718643_SETWET STYLEDEO MISCHIEF AVATR 150ml CAN,ALL,ECOM,718640_SETWET STYLEDEO COOL AVATAR 150ml CAN,None,718643,718640

In [6]:
from tqdm import tqdm

def impute_missing_dates(
        df,
        freq='M',
        key=['CHAIN', 'PARENT_MATERIAL_CODE'], 
        date_col='MONTH_DATE',
        max_date='2026-12-31'
    ):

    impute_df = df.copy()
    impute_df[date_col] = pd.to_datetime(impute_df[date_col])
    impute_df['key'] = impute_df[key].astype(str).agg('_'.join, axis=1)
    min_dates_df = impute_df.groupby(
        'key', as_index=False
    )[date_col].min()

    def impute_missing_dates_key(key, min_date, max_date):
        df_imputed = pd.DataFrame(
            pd.date_range(min_date, max_date, freq=freq),
            columns=[date_col]
        )
        df_imputed['key'] = key
        return df_imputed
    
    outputs = Parallel(n_jobs=-1)(
        delayed(impute_missing_dates_key)(row['key'], row[date_col], max_date)
        for idx, row in tqdm(min_dates_df.iterrows())
    )
    df_full = pd.concat(outputs)
    df_full.reset_index(drop=True, inplace=True)

    df_full = df_full.merge(
        impute_df, on=['key', date_col], how='left',
    )

    return df_full

### Primary Actuals + Sec Plan Data

In [7]:
plan_actuals_query = """
SELECT
    CASE 
        WHEN MCM.chain = 'Big basket B2C' THEN 'Big Basket'
        WHEN MCM.chain = 'Flipkart-National' THEN 'Flipkart National'
        WHEN MCM.chain = 'Flipkart-Minutes' THEN 'Flipkart National'
        WHEN MCM.chain = 'Nykaa' THEN 'Nykaa'
        WHEN MCM.chain = 'Myntra' THEN 'Myntra'
        WHEN MCM.chain = 'MYNTRA' THEN 'Myntra'
        WHEN MCM.chain = 'Amazon B2C' THEN 'Amazon ARIPL'
        WHEN MCM.chain = 'ARIPL' THEN 'Amazon ARIPL'
        WHEN MCM.chain = 'RK WORLDINFOCOM' THEN 'Amazon RK'
        WHEN MCM.chain = 'RKWorld' THEN 'Amazon RK'
        WHEN MCM.chain = 'Flipkart-Grocery' THEN 'Flipkart Grocery'
        WHEN MCM.chain = 'FlipkartGrocery' THEN 'Flipkart Grocery'
        WHEN MCM.chain = 'Firstcry' THEN 'First Cry'
        WHEN MCM.chain = 'CITIMALL' THEN 'City Mall'
        WHEN MCM.chain = 'Meesho' THEN 'Meesho'
        ELSE MCM.chain
    END AS chain,
    MM.parent_material_code,
    MM.material_group_code,
    MESR.month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Flipkart-National', 'Flipkart-Grocery', 'Big basket B2C', 'RK WORLDINFOCOM', 'Amazon B2C', 
        'FATEHPURIA HYGIENE', 'Nykaa', 'Flipkart-Minutes', 'Purplle', 'Myntra', 'Dealshare', 'FlipkartGrocery', 'City Mall', '1MG', 
        'ARIPL', 'First Cry', 'Meesho', 'RKWorld', 'CITIMALL', 'Firstcry', 'EMAZING DEALS', 'MYNTRA')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
WHERE
    MESR.month_date > '2022-12-31'
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""

plan_actuals_df = pd.read_sql(
    plan_actuals_query,
    prod_conn
)

In [8]:
# plan_actuals_query = """
# SELECT
#     CASE 
#         WHEN MCM.chain = 'Big basket B2C' THEN 'Big Basket'
#         WHEN MCM.chain = 'Flipkart-National' THEN 'Flipkart National'
#         WHEN MCM.chain = 'Flipkart-Minutes' THEN 'Flipkart National'
#         WHEN MCM.chain = 'Nykaa' THEN 'Nykaa'
#         WHEN MCM.chain = 'Myntra' THEN 'Myntra'
#         WHEN MCM.chain = 'MYNTRA' THEN 'Myntra'
#         WHEN MCM.chain = 'Amazon B2C' THEN 'Amazon ARIPL'
#         WHEN MCM.chain = 'ARIPL' THEN 'Amazon ARIPL'
#         WHEN MCM.chain = 'RK WORLDINFOCOM' THEN 'Amazon RK'
#         WHEN MCM.chain = 'RKWorld' THEN 'Amazon RK'
#         WHEN MCM.chain = 'Flipkart-Grocery' THEN 'Flipkart Grocery'
#         WHEN MCM.chain = 'FlipkartGrocery' THEN 'Flipkart Grocery'
#         WHEN MCM.chain = 'Firstcry' THEN 'First Cry'
#         WHEN MCM.chain = 'CITIMALL' THEN 'City Mall'
#         WHEN MCM.chain = 'Meesho' THEN 'Meesho'
#         ELSE MCM.chain
#     END AS chain,
#     MM.parent_material_code,
#     MM.material_group_code,
#     MESR.distributor_code,
#     MESR.month_date,
#     SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
#     SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
#     SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
#     SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
# FROM
#     dwh_bpm_dist_sku_daily MESR
# JOIN 
# (
#     SELECT
#         customer,
#         chain_type,
#         chain
#     FROM
#         mst_chain_master
#     WHERE
#         chain_type = 'E Com B2C' AND 
#         chain IN ('Flipkart-National', 'Flipkart-Grocery', 'Big basket B2C', 'RK WORLDINFOCOM', 'Amazon B2C', 
#         'FATEHPURIA HYGIENE', 'Nykaa', 'Flipkart-Minutes', 'Purplle', 'Myntra', 'Dealshare', 'FlipkartGrocery', 'City Mall', '1MG', 
#         'ARIPL', 'First Cry', 'Meesho', 'RKWorld', 'CITIMALL', 'Firstcry', 'EMAZING DEALS', 'MYNTRA')
# ) MCM ON MESR.distributor_code = MCM.customer
# JOIN
# (
#     SELECT
#         material_code,
#         parent_material_code,
#         material_group_code,
#         uom_reporting,
#         vol_per_unit
#     FROM 
#         mst_material
#     WHERE
#         company_code='MIL' AND
#         latest_record_ind=1
# ) MM ON MESR.material_code = MM.material_code
# WHERE
#     MESR.month_date > '2022-12-31' and MESR.month_date <= '2026-03-31'
# GROUP BY 1, 2, 3, 4,5
# ORDER BY 1, 3, 2, 4,5
# """

# plan_actuals_df = pd.read_sql(
#     plan_actuals_query,
#     prod_conn
# )

In [9]:
top_chains = ['Amazon ARIPL', 'Amazon RK', 'Big Basket', 'Flipkart Grocery',
       'Flipkart National', 'Myntra', 'Nykaa','Meesho']

In [10]:
plan_actuals_df['CHAIN'].unique()

array(['1MG', 'Amazon ARIPL', 'Amazon RK', 'Big Basket', 'City Mall',
       'Dealshare', 'EMAZING DEALS', 'FATEHPURIA HYGIENE', 'First Cry',
       'Flipkart Grocery', 'Flipkart National', 'Myntra', 'Purplle'],
      dtype=object)

In [11]:
plan_actuals_df.columns = plan_actuals_df.columns.str.lower()
plan_actuals_df['month_date'] = pd.to_datetime(plan_actuals_df['month_date'])
plan_actuals_df

,chain,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,1MG,718472,ADV-AHO-R,2023-01-01,0.0,0.437000,0.0000,0.0
1,1MG,718472,ADV-AHO-R,2023-02-28,0.0,0.000000,0.1870,0.0
2,1MG,718472,ADV-AHO-R,2023-03-31,0.0,0.000000,0.2380,0.0
3,1MG,718472,ADV-AHO-R,2023-04-30,0.0,0.000000,0.0220,0.0
4,1MG,718472,ADV-AHO-R,2023-06-01,0.0,0.117000,0.0000,0.0
...,...,...,...,...,...,...,...,...
454589,Purplle,809423,SW_SGPRF,2024-06-01,0.0,25.242491,0.0000,0.0
454590,Purplle,809423,SW_SGPRF,2026-06-30,0.0,0.000000,0.7004,0.0
454591,Purplle,810125,SW_SGPRF,2024-12-31,0.0,0.000000,8.0000,0.0
454592,Purplle,810125,SW_SGPRF,2025-01-31,0.0,0.000000,0.0480,0.0
454593,Purplle,810125,SW_SGPRF,2026-07-31,0.0,0.000000,0.1667,0.0

In [12]:
# plan_actuals_df.to_csv('ecom_primary_daily.csv', index=False)

In [13]:
plan_actuals_df.duplicated(subset=['chain', 'parent_material_code', 'material_group_code', 'month_date']).sum()

0

In [14]:
plan_actuals_df = realign_pskus(plan_actuals_df.copy(), column='parent_material_code')

In [15]:
plan_actuals_df.duplicated(subset=['chain', 'parent_material_code', 'material_group_code', 'month_date']).sum()

8216

In [16]:
plan_actuals_df.columns

Index(['chain', 'parent_material_code', 'material_group_code', 'month_date',
       'pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum',
       'sec_actuals_vol_rum'],
      dtype='object')

In [17]:
material_master_df = pd.read_sql(
    """select * from mst_material 
    where latest_record_ind=1 and company_code='MIL'""",
    prod_conn
)
material_master_df.columns = material_master_df.columns.str.lower()
assert material_master_df.duplicated(
    subset=['company_code', 'material_code']).sum() == 0

material_master_df['material_code'] = material_master_df['material_code'].astype(np.int64)
material_master_df.duplicated(subset=['material_code', 'parent_material_code', 'material_group_code']).sum()

0

In [18]:
plan_actuals_df = plan_actuals_df.groupby(
    ['chain', 'parent_material_code', 'month_date'],
    as_index=False
)[['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum',
       'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum()

# material_master_df[['parent_material_code', 'brand_code']].dtypes
material_master_df['parent_material_code'] = material_master_df['parent_material_code'].astype(int)
material_master_df.loc[material_master_df['parent_material_code'].isin([725930,731857]), 'material_group_code'] = 'H&C_ALMND'

# offtake_df.drop(columns = ['brand_code'],inplace = True)
len_before_merge = len(plan_actuals_df)
plan_actuals_df = plan_actuals_df.merge(
    material_master_df[['parent_material_code', 'material_group_code']].drop_duplicates(),
    left_on=['parent_material_code'],right_on = ['parent_material_code'],
    how='left'
)
assert len_before_merge == len(plan_actuals_df)

In [19]:
plan_actuals_df['month_date'] = plan_actuals_df['month_date'] + MonthEnd(0)

In [20]:
plan_actuals_df = plan_actuals_df[
    (plan_actuals_df['parent_material_code'] != 715096)
]

In [21]:
715096 in plan_actuals_df['parent_material_code'].values

False

In [22]:
plan_actuals_df = plan_actuals_df.groupby(
    ['chain', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()

In [23]:
plan_actuals_df.shape

(119443, 8)

In [24]:
plan_actuals_df = impute_missing_dates(
    plan_actuals_df.copy(),
    key=['chain', 'parent_material_code'],
    date_col='month_date'
)

8819it [00:02, 3527.26it/s]

In [25]:
cols = ['chain', 'parent_material_code', 'material_group_code']

plan_actuals_df[cols] = plan_actuals_df.groupby('key')[cols].transform(lambda x: x.ffill().bfill())

In [26]:
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    plan_actuals_df[col] = plan_actuals_df[col].fillna(0)

In [27]:
plan_actuals_df['parent_material_code'] = plan_actuals_df['parent_material_code'].astype(int)

In [28]:
plan_actuals_df.duplicated(subset=['key', 'month_date']).sum()

0

In [29]:
plan_actuals_df.shape

(306072, 9)

In [30]:
# # For duplicates, keep only the row with PABABY_ML material_group_code
# duplicates = plan_actuals_df[plan_actuals_df.duplicated(subset=['key', 'month_date'], keep=False)]

# # Get indices of duplicates that are NOT PABABY_ML
# indices_to_drop = duplicates[duplicates['material_group_code'] != 'PABABY_ML'].index

# # Remove those rows
# plan_actuals_df = plan_actuals_df.drop(indices_to_drop)

# # Verify no duplicates remain
# print(plan_actuals_df.duplicated(subset=['key', 'month_date']).sum())

In [31]:
plan_actuals_df.shape

(306072, 9)

In [32]:
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if plan_actuals_df[col].min() < 0:
        print(col)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [33]:
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    plan_actuals_df[col] = plan_actuals_df[col].clip(lower=0)

In [34]:
plan_actuals_df.duplicated(subset=['key', 'month_date']).sum()

0

In [35]:
plan_actuals_df.sort_values(['key', 'month_date'], inplace=True)

In [36]:
plan_actuals_df['Primary P3M'] = plan_actuals_df.groupby(
    ['key'], 
    as_index = False, group_keys = False
)['pri_actuals_vol_rum'].shift(1).rolling(window=3, min_periods=1).mean()

In [37]:
others_df = plan_actuals_df[
    ~plan_actuals_df['chain'].isin(top_chains)
]
plan_actuals_df = plan_actuals_df[
    plan_actuals_df['chain'].isin(top_chains)
]

In [38]:
print(others_df['chain'].unique())
print(plan_actuals_df['chain'].unique())

['1MG' 'City Mall' 'Dealshare' 'EMAZING DEALS' 'FATEHPURIA HYGIENE'
 'First Cry' 'Purplle']
['Amazon ARIPL' 'Amazon RK' 'Big Basket' 'Flipkart Grocery'
 'Flipkart National' 'Myntra']

In [39]:
plan_actuals_df['chain'].unique()

array(['Amazon ARIPL', 'Amazon RK', 'Big Basket', 'Flipkart Grocery',
       'Flipkart National', 'Myntra'], dtype=object)

In [40]:
# x = plan_actuals_df.copy()
# x.rename(columns = {'material_group_code':'Brand'},inplace = True)
# len_before_merge = len(x)
# x = x.merge(
#     qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
#         'brand_code': 'Brand',
#         'qtr_ind_rate': 'Index Rate'
#     }),
#     on=['Brand'],
#     how='left'
# )
# assert len_before_merge == len(x)
# del len_before_merge
# x.dtypes
# x['plan_actuals_val'] = x['sec_actuals_vol_rum']*x['Index Rate']/10**7
# x.groupby(['month_date'])['plan_actuals_val'].sum().reset_index()#[20:]

In [41]:
# qtr_ind_rate_df

In [42]:
# x['sec_actuals_vol_rum'].sum()

In [43]:
plan_actuals_df.to_csv('plan_actuals_ok.csv')

In [44]:
plan_actuals_df['sec_actuals_vol_rum'].sum()

12517516.633000001

### Offtakes

In [45]:
# offtakes_monthly_query = """
# SELECT
#     OTM.platform_name AS chain,
#     MM.parent_material_code,
#     MM.material_group_code,
#     OTM.month_date,
#     SUM(vol_in_rum) AS vol_in_roum
# FROM 
#     dwh_ecommplatform_offtake OTM 
# JOIN
# (
#     SELECT
#         material_code,
#         parent_material_code,
#         material_group_code,
#         uom_reporting,
#         vol_per_unit
#     FROM 
#         mst_material
#     WHERE
#         company_code='MIL' AND
#         latest_record_ind=1
# ) MM ON OTM.material_code = MM.material_code
# WHERE
#     OTM.platform_name NOT IN ('Blinkit', 'Swiggy', 'Zepto', 'Others', 'Amazon D2C', 'Flipkart D2C') AND
#     OTM.month_date > '2022-12-31' 
# GROUP BY 1, 2, 3, 4
# ORDER BY 1, 2, 3, 4
# """ 

# offtakes_monthly_df = pd.read_sql(
#     offtakes_monthly_query,
#     prod_conn
# )

In [46]:
# offtakes_monthly_df.columns = offtakes_monthly_df.columns.str.lower()

In [47]:
# offtakes_monthly_df['month_date'] = pd.to_datetime(offtakes_monthly_df['month_date'])
# offtakes_monthly_df['parent_material_code'] = offtakes_monthly_df['parent_material_code'].astype(int)

In [48]:
# offtakes_monthly_df.rename(columns={'vol_in_roum': 'offtake_vol_rum'}, inplace=True)

In [49]:
# offtakes_monthly_df

In [50]:
# offtakes_monthly_df['month_date'].max()

In [51]:
mmonth_df = pd.read_sql("""
    SELECT * 
    FROM 
        TRN_DF_ECOM_OFFTAKE_CHAIN_PSKU_NEW
    WHERE
        
        run_month='2026-09-30'
""", 
    dev_conn
)

In [52]:
mmonth_df.columns = mmonth_df.columns.str.lower()

In [53]:
mmonth_df['month_date'] = pd.to_datetime(mmonth_df['month_date'])
mmonth_df['parent_material_code'] = mmonth_df['parent_material_code'].astype(int)

In [54]:
mmonth_df.head()

,month_date,platform_name,parent_material_code,vol_in_rum,indexbpm,brand_code,imputed,big_billion_days,big_billion_days_lag_1,big_billion_days_lag_2,big_billion_days_lead_1,big_billion_days_lead_2,great_indian_festival,great_indian_festival_lag_1,great_indian_festival_lag_2,great_indian_festival_lead_1,great_indian_festival_lead_2,ratio_last_year,quarter,run_month
0,2026-08-31,Amazon ARIPL,718288,40.992,56.923648,SAFF GOLD,0,0,0,0,1,0,0,0,0,1,0,NaN,3,2026-09-30
1,2026-09-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,1,0,0,0,0,1,0,0,0,0,NaN,3,2026-09-30
2,2026-10-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,1,0,0,0,0,1,0,0,0,0.0,4,2026-09-30
3,2026-11-30,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,1,0,0,0,0,1,0,0,0.0,4,2026-09-30
4,2026-12-31,Amazon ARIPL,718288,0.000,0.000000,SAFF GOLD,1,0,0,0,0,0,0,0,0,0,0,0.0,4,2026-09-30

In [55]:
mmonth_df = mmonth_df.groupby(
    ['platform_name', 'parent_material_code', 'brand_code', 'month_date'],
    as_index=False
)['vol_in_rum'].sum()

In [56]:
mmonth_df.rename(
    columns = {'platform_name': 'chain', 'brand_code': 'material_group_code', 'vol_in_rum': 'offtake_vol_rum'},
    inplace=True
)

In [57]:
# offtakes_monthly_df = pd.concat([
#     offtakes_monthly_df,
#     mmonth_df
# ])
offtakes_monthly_df = mmonth_df.copy()

In [58]:
offtakes_monthly_df[offtakes_monthly_df['month_date'] == '2026-07-31']['offtake_vol_rum'].sum()

385655.90783351

In [59]:
offtakes_monthly_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()

0

In [60]:
portfolio_query = """SELECT DISTINCT
    MATERIAL_GROUP_CODE AS BRAND_CODE,
    SAP_PORTFOLIO_NAME AS PORTFOLIO
FROM MST_MATERIAL
WHERE COMPANY_CODE = 'MIL'
  AND LATEST_RECORD_IND = '1'
  AND MATERIAL_GROUP_CODE IS NOT NULL
  AND SAP_PORTFOLIO_NAME IS NOT NULL
ORDER BY SAP_PORTFOLIO_NAME, MATERIAL_GROUP_CODE;"""
brand_md_df = pd.read_sql(portfolio_query, prod_conn)
brand_md_df.columns = brand_md_df.columns.str.lower()
brand_md_df.head()

  brand_code portfolio
0  BD_BDOL_M    BEARDO
1  BD_HRWX_M    BEARDO
2  BRD_BDCOL    BEARDO
3  BRD_BDOIL    BEARDO
4  BRD_BDSPR    BEARDO

In [61]:
len_before_merge = len(offtakes_monthly_df)
offtakes_monthly_df = offtakes_monthly_df.merge(
    brand_md_df.rename(columns={'brand_code': 'material_group_code'}),
    on=['material_group_code'],
    how='left'
)
assert len_before_merge == len(offtakes_monthly_df)

In [62]:
offtakes_monthly_df[offtakes_monthly_df['portfolio'].isna()]

Empty DataFrame
Columns: [chain, parent_material_code, material_group_code, month_date, offtake_vol_rum, portfolio]
Index: []

In [63]:
offtakes_monthly_df['chain'] = np.where(
    (offtakes_monthly_df['chain'] == 'Amazon'),
    np.where(
        offtakes_monthly_df['portfolio'].isin(['Saffola Oils', 'Foods']),
        'Amazon ARIPL',
        'Amazon RK'
    ),
    offtakes_monthly_df['chain']
)

In [64]:
offtakes_monthly_df[offtakes_monthly_df['chain'].str.startswith('Amazon')][['chain', 'portfolio']].drop_duplicates()

              chain         portfolio
0      Amazon ARIPL      SAFFOLA OILS
88     Amazon ARIPL             FOODS
935       Amazon RK               CNO
969       Amazon RK      SAFFOLA OILS
1165      Amazon RK         HAIR OILS
1381      Amazon RK             FOODS
1435      Amazon RK            OTHERS
1572      Amazon RK     MALE GROOMING
1734      Amazon RK  PREM. HAIR NOUR.
2910      Amazon RK         SKIN CARE
16456     Amazon RK     CLEAN & CONDI
17802     Amazon RK   PREM. HAIR NOUR

In [65]:
offtakes_monthly_df['chain'].unique()

array(['Amazon ARIPL', 'Amazon RK', 'Big Basket', 'Flipkart Grocery',
       'Flipkart National', 'Meesho', 'Myntra', 'Nykaa', 'Purplle'],
      dtype=object)

In [66]:
offtakes_monthly_df['parent_material_code'] = offtakes_monthly_df['parent_material_code'].astype(int)

In [67]:
offtakes_monthly_df['key'] = offtakes_monthly_df[['chain', 'parent_material_code']].astype(str).agg('_'.join, axis=1)

In [68]:
offtakes_monthly_df

,chain,parent_material_code,material_group_code,month_date,offtake_vol_rum,portfolio,key
0,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,40.992,SAFFOLA OILS,Amazon ARIPL_718288
1,Amazon ARIPL,718288,SAFF GOLD,2026-09-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288
2,Amazon ARIPL,718288,SAFF GOLD,2026-10-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288
3,Amazon ARIPL,718288,SAFF GOLD,2026-11-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288
4,Amazon ARIPL,718288,SAFF GOLD,2026-12-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288
...,...,...,...,...,...,...,...
141752,Purplle,810674,PA_ESS_HO,2027-02-28,0.000,HAIR OILS,Purplle_810674
141753,Purplle,810674,PA_ESS_HO,2027-03-31,0.000,HAIR OILS,Purplle_810674
141754,Purplle,810674,PA_ESS_HO,2027-04-30,0.000,HAIR OILS,Purplle_810674
141755,Purplle,810674,PA_ESS_HO,2027-05-31,0.000,HAIR OILS,Purplle_810674
141756,Purplle,810674,PA_ESS_HO,2027-06-30,0.000,HAIR OILS,Purplle_810674

In [69]:
offtakes_monthly_df.duplicated(subset=['key', 'month_date']).sum()

0

In [70]:
715096 in offtakes_monthly_df['parent_material_code'].values

True

In [71]:
offtakes_monthly_df = offtakes_monthly_df[
    offtakes_monthly_df['parent_material_code'] != 715096
]

In [72]:
offtakes_monthly_df['offtake_vol_rum'].min()

0.0

In [73]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate
qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [74]:
qtr_ind_rate_df

    month_date        brand_code  qtr_ind_rate
0   2027-03-31         CMX_WELPD    3014.00000
1   2027-03-31         4700_BCPC     222.00000
2   2027-03-31         CMX_PRTPD    3014.00000
3   2027-03-31         PA_CN_HGO     488.15200
4   2027-03-31         TRU_RAWDF     800.00000
..         ...               ...           ...
352 2018-03-31        PADV-HRAHF       0.00000
353 2018-03-31         PAR T HFS       0.00000
354 2020-03-31  LIVON HG Shampoo       0.00000
355 2020-03-31           NHO ACE       0.00000
356 2018-03-31        SMO Premix  197307.93822

[357 rows x 3 columns]

In [75]:
# x = offtakes_monthly_df.copy()
# x.rename(columns = {'material_group_code':'Brand'},inplace = True)
# len_before_merge = len(x)
# x = x.merge(
#     qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
#         'brand_code': 'Brand',
#         'qtr_ind_rate': 'Index Rate'
#     }),
#     on=['Brand'],
#     how='left'
# )
# assert len_before_merge == len(x)
# del len_before_merge
# x['offtake_val'] = x['offtake_vol_rum']*x['Index Rate']/10**7
# x.groupby(['month_date'])['offtake_val'].sum().reset_index()[20:]

### SOH

In [76]:
soh_df = pd.read_csv('/data/aman_singh/acuuracy_check/soh_base_sep_run.csv')

In [77]:
soh_df.columns = soh_df.columns.str.lower()

In [78]:
soh_df

,chain,fsn,soh,material_code,desc,brand,uom,vol per unit,vol,fy index,...,month,day,month.1,unnamed: 18,unnamed: 19,unnamed: 20,unnamed: 21,unnamed: 41,unnamed: 42,unnamed: 43
0,Blinkit,10000059,3131.0,707136,SAF TOTAL 5LT JAR,SAFF KO,KL,5000.0000,15.655000,182263.023590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Blinkit,10000062,500.0,722897,SMO 38G CUR&PEP HDC,SFOATS-FL,TO,38.0000,0.019000,252810.051419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Blinkit,10000063,2711.0,722898,SMO 38G MAS&COR HDC,SFOATS-FL,TO,38.0000,0.103018,252810.051419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Blinkit,10000361,1542.0,809267,SAFF SALT PLUS 1 KG PCH,SAFF SALT,TO,1000.0000,1.542000,25994.993781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Blinkit,10000362,3387.0,713333,SAF TASTY PLUS 1L PCH,SAFF KOCO,KL,1000.0000,3.387000,145305.652227,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95572,Flipkart National,EDOGQCF6KADPGUHV,1.0,EDOGQCF6KADPGUHV,PCNO R 600ML EJ,PCNO(R),KL,600.0000,0.000600,349274.001420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95573,Flipkart National,CAFHYQ5GVVM3AT4H,1.0,CAFHYQ5GVVM3AT4H,SMO GOURME SPICY 400GM 24P,SFOATS-FL,TO,400.0000,0.000400,292663.137458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95574,Flipkart National,CAFEUHZHD3RKAHVG,1.0,CAFEUHZHD3RKAHVG,SMO 38G CLS MSL MILLET,SFOATS-FL,TO,37.9997,0.000038,292663.137458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95575,Flipkart National,BBCHAE2Y5VK4B2YM,1.0,BBCHAE2Y5VK4B2YM,BABY COMBO OIL400+OIL200ML,PABABY_ML,L,600.0000,0.600000,435.822760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95576,Flipkart National,HOLHCKSGHDGCGZ2T,1.0,HOLHCKSGHDGCGZ2T,NSA BDM 500ML(36),NHR-SABDM,L,500.0000,0.500000,188.493651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
soh_df.groupby(['chain'])['date'].max()

chain
Amazon ARIPL         2026-09-01
Amazon RK            2026-09-01
BB                   2025-03-22
Big Basket           2026-09-01
Blinkit              2026-09-01
Flipkart Grocery     2026-09-01
Flipkart Mintues     2025-10-31
Flipkart Minutes     2026-09-01
Flipkart National    2026-09-03
Flipkart-Grocery     2026-07-01
Meesho               2026-09-01
Myntra               2026-09-01
Nykaa                2026-09-01
Purplle              2025-11-17
Swiggy               2026-09-01
ZEPTO                2026-09-01
Zepto                2026-08-01
Name: date, dtype: object

In [80]:
import numpy as np
soh_df['date'] = np.where(
    soh_df['date'] > '2026-07-31',
    '2026-07-31',
    soh_df['date']
)

In [81]:
soh_df.groupby(['chain'])['date'].max()

chain
Amazon ARIPL         2026-07-31
Amazon RK            2026-07-31
BB                   2025-03-22
Big Basket           2026-07-31
Blinkit              2026-07-31
Flipkart Grocery     2026-07-31
Flipkart Mintues     2025-10-31
Flipkart Minutes     2026-07-31
Flipkart National    2026-07-31
Flipkart-Grocery     2026-07-01
Meesho               2026-07-31
Myntra               2026-07-31
Nykaa                2026-07-31
Purplle              2025-11-17
Swiggy               2026-07-31
ZEPTO                2026-07-31
Zepto                2026-07-31
Name: date, dtype: object

In [82]:
material_master = pd.read_sql("""
SELECT * 
FROM
    mst_material
WHERE
    company_code='MIL' AND
    latest_record_ind=1
""",
    prod_conn
)

In [83]:
material_master.columns = material_master.columns.str.lower()
material_master['material_code'] = material_master['material_code'].astype(int)

In [84]:
soh_df.columns

Index(['chain', 'fsn', 'soh', 'material_code', 'desc', 'brand', 'uom',
       'vol per unit', 'vol', 'fy index', 'bpm in lacs', 'category',
       'ecom brands', 'file', 'vol in kl', 'psku', 'pdes', 'date', 'asin',
       'asin.1', 'platform_name.1', 'product_title', 'ean', 'units',
       'material_group_code', 'uom_reporting', 'vol_per_unit', 'vol_in_lit',
       'vol in rum', 'indexrate', 'indexbpm', 'club sku', 'roum',
       'roum divide', 'month', 'day', 'month.1', 'unnamed: 18', 'unnamed: 19',
       'unnamed: 20', 'unnamed: 21', 'unnamed: 41', 'unnamed: 42',
       'unnamed: 43'],
      dtype='object')

In [85]:
material_master.columns

Index(['company_code', 'material_code', 'material_desc', 'material_group_code',
       'material_group_desc', 'division_code', 'division_name', 'uom_base',
       'uom_weight', 'gross_weight', 'net_weight', 'parent_material_desc',
       'material_type', 'material_type_desc', 'uom_sales', 'uom_reporting',
       'mg1_code', 'mg1_desc', 'mg2_code', 'mg2_desc', 'mg3_code', 'mg3_desc',
       'mg4_code', 'mg4_desc', 'mg5_code', 'mg5_desc', 'profit_centre_code',
       'vol_per_unit', 'unit_per_case_nbr', 'convert_to_ton', 'convert_to_kl',
       'convert_to_l', 'convert_to_kg', 'convert_to_ml', 'convert_to_gm',
       'csd_id', 'ean_id', 'standard_cost_amt', 'source_system_id',
       'last_bi_updt_date', 'last_src_updt_date', 'material_sk',
       'effective_start_date', 'effective_end_date', 'latest_record_ind',
       'version_nbr', 'parent_material_code', 'parent_material1_code',
       'parent_material1_desc', 'shelf_life_days',
       'manual_material_group_desc', 'manual_mg1_desc',
       'material_group_desc_mkt', 'co_type', 'deletion_flag', 'manual_mlage',
       'sku_size_manual', 'sku_size_ml_gm_manual', 'volum', 'voleh',
       'product_hierarchy', 'conv_buom_to_ruom', 'conv_buom_to_csuom',
       'sap_category_name', 'sap_franchise_name', 'sap_portfolio_name',
       'old_material', 'lifecycle_flag', 'material_creation_date',
       'sap_club_sku', 'convert_to_st', 'material_changed_date',
       'convert_to_pak'],
      dtype='object')

In [86]:
for sku in soh_df['material_code'].unique():
    try:
        int(sku)
    except:
        print(sku)

Combo
COCOS00000021
KAYA_8906027070014
KAYA_8906027070106
KAYA_8906027070120
KAYA_8906027070786
KAYA_8906027070977
KAYA_8906027070984
KAYA_8906027070991
KAYA_NYKA00001008
KAYAX00000019
KAYAX00000027
KAYAX00000029
KAYAX00000034
KAYAX00000038
KAYAX00000051
KAYAX00000053
KAYAX00000068
L_8901088062374
L_8901088062381
L_8901088062398
LIVON00000014
LIVON00000016
LIVON00000018
LIVON00000023
LIVON00000025
LIVON00000026
M_8901088023573
M_8901088026864
M_8901088045681
M_8901088047265
M_8901088062473
M_8901088062497
M_8901088064576
NYBO000000001
NYKPARA000001
NYKY000000004
NYKY000000005
NYPRAOFF00001
P_8901088045674
PARAC00000005
PARAC00000006
PARAC00000008
PARAC00000017
PARAC00000018
PARAC00000021
PARAC00000043
PARAC00000053
PARAC00000055
PARAC00000057
PARAC00000058
PARAC00000059
PARAC00000061
PARAC00000066
PARAC00000069
PARAC00000070
PARAC00000072
PARAC00000091
PARAC00000095
PARAC00000096
PARAC00000097
PARAC00000098
PARAC00000099
PARAC00000108
PARAC00000111
PARAC00000114
PARAC00000116
PARAC00000117
PARAC00000118
PARAC00000120
PARAC00000121
PARAC00000123
PARAC00000124
PARAC00000125
PARAC00000131
PARAC00000143
PARAC00000144
PARAC00000145
PARAC00000146
PARAC00000147
PARAC00000148
PARAC00000149
PARAC00000150
PARAC00000151
PARAC00000152
PARAC00000154
PARAC00000155
PARAC00000157
PARAC00000158
PARAC00000160
PARAC00000161
PARAC00000163
PARAC00000165
PARAC00000166
PARAC00000168
PARAC00000169
PARAC00000170
PARAC00000171
PARAC00000172
PARAC00000179
PARAC00000181
00128d5d-d85d-40ed-b70b-c5fa9f10cac0
00f3f58c-c7f7-4b55-a374-e5469ad19223
01400883-9518-4f73-9c9f-593130e0d414
021c7b96-7a79-492b-9226-f74c9e5ce670
0273ef06-8fa6-49e5-8b69-715d2bc3e60b
03843645-8523-4571-8c92-7b3b5d292930
0422ef1e-68be-4140-b30b-d29bb1cd6441
04e9c26c-4d9f-4e06-b2aa-9ac341adb3a8
05c644df-5c16-4250-b4d9-21b04b050737
05ec7310-a311-4221-998f-9eef6d5f9ea8
076213c2-f24b-4ac8-9d74-95c0e3b3b2cf
07b3e65b-12b5-40f2-bce3-64f2555294f1
07e1e546-cd3f-4f3c-808f-db63d50a7e5f
07e626b7-e197-4ff3-9d4e-15b68b905d84
088aec98-7309-4daf-afea-c761f30c8d08
0917d301-ca4b-4887-b000-85268d8b46e6
096e4b13-5131-49fd-9d82-d6a5331aa353
0c0f8bd7-ee5a-4069-8ce6-80512cbaac45
0d37d813-6ceb-476a-a994-c6a8c086f08f
0d5e5472-76e6-413e-897d-81d12ff4dd67
0d8ecd26-452c-4217-92db-1a8cbb615165
0df95392-4aea-4e77-9af9-f5328ea17183
107f0406-e2a5-41cb-a072-bd0ee952a202
10e34453-4f75-4c41-813d-858be8b82ef2
125d6f64-7a8e-44b3-8789-95630af21bbd
12d5b5ac-342e-4f5d-b35e-1ae4bb645ae1
132c0b63-8270-4f87-b76e-86d3f07805e8
149465fe-cce1-4bdb-8c01-50c3a67f7a4d
16142d2a-55f8-42fc-82ab-5364cb56bf9e
1682f40d-b48e-497d-9231-17cd04af96e4
16ac9186-cfa5-4e25-87c0-c40936296be7
18e80b6c-a99b-4bf6-a73b-1550595534b5
19823d3a-a52a-43e9-84b3-498de8bcda2f
19b1933c-37b2-4bc9-afcf-ddcda90af224
1a1f4324-0541-4342-8842-f71a25ae4bd1
1b87057c-2b1c-43de-847f-c54ce52df1c3
1e227e35-8483-405a-a7a1-1a747812ce2c
1eb90f74-570c-4721-a735-2014bb31d7fb
1ecef729-ac17-4f2f-b7da-04b9bb3e0673
20ac4215-0fef-4122-9ea9-972ff31f877c
21b228d5-34fb-4758-86dd-f1976abc9278
222ec1ba-89ab-4472-8075-c70ebc31158b
22ca0c99-a2d9-4809-b5eb-6971d80db9c6
235a08fa-e0c8-45af-8e42-3203a085b63d
23730b99-4c5f-4446-90c2-067f734c7138
25f79f6e-98bc-4ec1-94b5-283f1561ff94
2637780c-b773-412c-9f8b-d8cae9ac2dde
26c1f539-8aea-45ec-86d8-21a6a42a5d67
289ac796-827e-4070-aabd-6d727ed62bdc
28a02ab0-1d62-4b7f-9973-86504306af8e
292f1828-6db0-4af6-9abd-b8e9095452ae
29b306e4-5656-4326-ad7f-4ecd98abf3d8
2dce3c23-4253-45b1-a7c8-00c26b07d3df
2f161de9-57d2-417a-a2d8-aef6e7cd0cef
2f2e2a4f-8535-4cf7-8309-13bf74456acd
2f99e894-5788-4eac-9142-605924f388b3
302b11bc-817c-4a1e-9d52-63535664bd1b
3148a355-6d95-4297-99ac-5a09312b4043
33e9bf4a-3af8-479f-b397-5f2e2cd40b02
341816fa-03ef-4c43-912a-38157210f9a9
3864ac09-986c-490b-bc86-32d4c892fa23
3d390a74-d96c-4424-839d-c40176645b51
3e2994b2-34e9-487e-bddd-8c65c97002b0
3e992065-6aa9-4af9-acbe-a2ebc80aa045
409efc37-abd1-4023-8d33-7a7d3b74ec05
41d6215c-58fa-4446-9098-5835dfb76660
42583ca6-6d56-44ba-b013-3b1d1ffb1634
4599756e-e251-4eaf-beaf-86abc2376480
4616a9ce-8306-46f9-a630-f19772b403be
46959139-b08c-4b16-bbe4-38fa7c24b775
4a0955ba-8d0a-4cef-a8e9-6a1e5c1b9f81
4b622f2b-2012-48be-abe5-95518b7aadb1
4c22cb88-bfac-4d24-9810-8cb061d5aaf1
4c7cde80-9149-4f68-a264-83d54b8c08dc
4d9913da-86d4-4520-9985-1948e50ac1c5
4e2169d3-023a-4523-956c-88ab1486b10a
4f0d4cca-9181-4e69-bd9e-c223f510421c
4fb7224d-3bbb-4838-821e-870263b606de
510b58e3-a2ce-43db-86bc-66278a694427
52677d2e-7a68-474e-bedf-64be89cbcda9
5403f563-1dbb-47e0-ad26-31b77238606c
55c07906-f02f-4f6a-b682-bf6e21e2c1c4
55e79199-434e-47a0-9cf6-c5c57e06051d
56233823-3fb0-421f-a520-480400baba97
570ddfa8-3860-4eb3-84d5-211ce24e6e92
58954a1f-b5cf-497c-a540-088501c22035
589bce9e-e0bc-467d-a6d0-10838a165e43
58f34ee5-ab92-4fa8-be9e-d82f5fa8751d
5a729de3-2c3f-48f2-be32-34f456ac39f8
5cba3f8d-c541-43f6-ad14-9a734fc0eb3e
5e5bcd45-af96-47d8-af95-2261cafe3fe5
5e7b1f49-e860-4546-b553-8656d1ed6d6a
5f600e6d-ea2d-47a5-9a80-b97ee103ef6d
60963468-92f1-45d8-a876-e5fe20606a2d
6096352f-c4f1-4f9b-9df2-80ec599177d6
60bb9c9f-5279-4aa2-8f50-88bb263d8a21
60d4ae96-a445-4d6b-ab23-3551a941c352
63f0a473-516d-4203-81d5-7be84f8a9cea
6487e35d-fd29-49b1-9321-99c2b56c5fc7
65841b74-a873-402a-8b78-561f96225eb6
65ebaabf-146e-4c96-8628-5ec74725d3cf
66f3360f-4da2-4a01-9be2-fa9ed98271a7
68f57fed-5ef1-485d-8588-6a71280dc339
6a2e2775-7627-4b4c-a376-4fa0f4728116
6bd2e90b-9686-4890-b9f4-b964fce35007
6bdcceb3-679b-4f45-90e4-a6f42a98acd6
6c8ad9a6-3d6f-4ee0-9195-1a38d973a2de
6caeea39-5658-4059-8878-9ae21bfc414f
70187bd1-dfe6-4c1d-94af-e0d52d5f446d
70417fdd-f6f1-4def-8e39-fc7196b5d37a
709bd327-baf4-4104-a46d-fdba2b80b99c
72e0feeb-726e-4d50-9113-4f519ebc2fb8
7443da8d-4e59-483d-a3ac-2f09ffb8fbac
74b18095-39e8-43d4-8cee-715d192fb689
7535f744-da57-4afe-86c1-f4fdb9e558e8
75f96881-aa1a-41d6-b334-f2a5a8c05cbc
78579bf1-1e88-4094-8181-d3a2ced0b045
7a33ef15-0787-4b18-8dff-b493a7c149ac
7aae2a78-9912-409b-ae1d-50f541b9c62e
7aca45e8-fe30-4a80-9bd5-792a986df3e5
7b438464-3263-4df0-8a59-7dc587b2dc26
7f995e90-48aa-4d51-bf7f-c2a1c4a4e1ab
8091ae64-cb5d-47c9-a177-e7e45e0d8fd9
81f24788-2bae-4be8-aa45-c79d2c42e0fd
833aa7e0-242b-4720-9e5b-7483802d9c0e
83b57fab-0eb4-405e-a1fd-a35926fdfe65
83d93779-2359-4f4b-bf04-37a27e3864ae
859e0f22-95ba-4ce6-91a0-d368bed37980
86893606-3184-44f6-9cb3-5878fcb6019d
885cbe65-bca5-475f-baf4-c9e55f68686c
8aab1f88-4b23-4cd5-b9b7-cb7c233f012e
8d4f1967-12a2-4f0f-ba5f-a1c1a080af24
8eaee9c8-d4c0-49f0-976d-d2be8b654d80
8f240876-5282-49f0-a30c-64d6020bbd7c
8f3f4370-a392-4ce7-b1c7-05bc15c9752e
8f794ffa-a8b0-4999-b63b-cf25aa9e341b
90719707-b8f3-4311-8084-ad0a8f4d0f51
91faee32-194a-4c3f-979c-4b940b72bb5c
91fc69e9-a256-4477-a501-ae56ec51a123
934bb13e-a492-4dcb-a0cc-32eef594d3fe
94992269-825a-4378-b888-15358052c2bb
97fdf929-7930-4499-9dd3-2922b2bb85e6
984acc5f-cd07-488e-883b-569ee9bdabe0
98e61771-0e39-47ac-af90-33d9d5417aa4
991643c9-e641-4ea6-804e-7da20deb52c0
99dd604c-b73f-4ce6-8f63-b9677e3c8390
9c38641f-5d05-4818-9cf1-9a584c645a74
9dbf8ccc-ae6d-449c-a35e-0c06dbf5a586
9ea2c807-7903-4f8a-afc3-b83d076f14a5
9eb24ad0-4a66-4d49-a53c-b3b542060593
a098ec95-c110-467c-9b07-95340fdd1051
a10750e0-fdc0-4538-a4fd-072e48bafbfe
a19cf8e1-ccc8-4a4d-8e27-1a619286a8da
a215ab5c-abdd-4a9f-9de0-fd0fc5fba984
a2749fe9-07c3-46fb-8dd8-ec254c035476
a687568d-4090-408a-a657-b9ac634199f8
a74eaad2-e93b-46d3-8e6d-d11a56d38632
a76321b5-9ccf-4810-b72a-dacbb15027b8
aa0c9f75-71a4-4b3e-ad98-ccb756f40545
aa0e4a15-f04f-43ab-8b8f-b923aab90e3a
aa56e993-5668-4576-993f-b3db75a585a2
aaa43e9e-89dc-4c74-acc9-1aa50c57ff1c
ab5f5a5a-859c-447e-9bdf-c772b0061e6a
abbd836e-f2d9-404a-84b8-275c0fb7b8d5
aca47ae2-f913-4920-a2b8-73197065a510
ad81a66b-c4f3-4e77-b7c2-d18247a60e4c
ae016e0e-310b-4e1f-b45f-81d1c8f1182e
ae1b1c5b-2622-4154-90a3-23a2a19b6e1b
b1058a4f-09d1-4435-8bf4-581a07406fa9
b20b7119-cea6-4fa4-a590-8fc19c52895d
b2406960-6429-49e1-9ce6-589508173e20
b4706f8c-069e-4c8e-8d47-5e214dc34b93
b5e4398f-ca77-4985-bcfe-db2b5342f352
b76c3a50-cc26-424b-851d-606da32a73c5
b7ad0b31-a48e-45af-ae9f-b6ccfa9da2b2
b91e81a8-2788-4b0b-a889-d73995127770
b952c6a6-98c7-4369-9365-725c40ea1606
ba19d51b-1b55-4d33-a1da-8ddb70e9ec42
ba325731-073e-4530-aa32-54b06526130e
ba902c51-d36d-4e37-aca3-7e8594eb12ab
bdb2302e-6274-4b99-ad19-3339b6cba494
bed7b085-741d-4342-b14c-fba2f1b7e805
bf4af905-050d-4878-be6d-d2ff195b3e1b
c3ff56d1-5864-4e38-b218-39df8485c4ec
c41c8a9f-f8d7-4aa0-b5bb-39a8905d50bf
c482801f-ba66-4e2b-9bbb-f54e548544e9
c7255b10-f226-4d2f-9d45-1e5c97f8517e
c8aadb8b-6f13-44e9-baf8-a12a79521d2a
cae2e985-0ea5-430e-a36b-d67db38440a9
cba15ac5-3b90-40c4-9a52-85deeb78307d
cd2fd63b-5cd6-48b0-9253-514d579b18f2
ce884476-8180-431c-90f9-78b2d350bffc
ce9c76b1-d2df-4b96-9fc0-46a7e9b16be5
cee5fd8d-0637-4e6a-bcf5-6d97ebfd3681
cee6db0c-b58b-4b54-9822-03fffed41a8e
cf8552ad-c42e-4980-917b-b49424b27162
d3c1b46d-5a17-4d16-8dbc-1df1f3bc891f
d45a8dc7-f0d9-487d-b826-b1fa9553b86c
d4f54b4b-855b-4bc8-8071-622a56a7137b
da45a5b1-6152-44a6-a41d-57b598936441
dc722c5c-38f0-4260-abf8-4ce6c9e884d7
dc8fe828-a358-4e0a-9c33-8b4132b76c13
de8bf368-a9d4-46e8-a913-0924ccea307d
e011578a-374b-406a-890d-f092005c203d
e14564e8-eb16-452b-b18e-04f088f4f99e
e17eb792-db73-4cb5-a612-0a329aab171c
e27060bf-3cc9-4586-a336-d09e3eca61e6
e2eeab46-1109-41ae-b90b-a9c3a429e62e
e519dbb8-61d1-48b7-b61d-aa17446fd420
e5788690-7ac5-496a-be12-8525156f0504
e6ab8174-00bd-4a14-b59f-494502928958
e7cd4f49-3d13-4e32-a6c9-a78ec9881c5e
e8bbe024-7ec1-4a36-95b3-120a17575809
ead3ac77-3808-4138-92d4-88fefb00292b
ebe9cdc5-ba87-41de-9365-c5743faeed1f
ed63ad7f-5365-4b22-8a24-841803566de4
ef969827-79f7-4716-b4c6-4525a6d134de
f0e0ef4b-2a02-4e13-8498-35b32f554274
f0e6676e-c9fc-4b96-a0ef-cd5247ae592a
f11e78fe-a341-41a7-8109-81bc5a2609de
f1b1c703-46a6-43e2-8b49-43c6a193a2a2
f1de8105-abca-4c45-b45c-6703f4b798dd
f2e74ceb-1506-4266-bad9-98363bfe69c2
f409f811-b480-4ee2-bb2b-a0c8b8b0b47c
f4b01d90-e285-4617-822d-9aacd5265816
f702765e-ea47-41a5-90e8-3c797e6b29fe
f77f7b39-68fd-47f2-9ede-10ec41b22095
f881826f-130e-495b-a6cb-03f089aaa68f
f9435600-2d79-477d-942d-19d0c7307403
f9bf067d-72f7-4e2a-8e42-2db42579f9fa
f9dacf29-3a8f-4d9e-90c2-f2acb4dbd253
fa1b347b-9200-410a-831b-4471c4b2c3c8
fc0bdd04-2f61-4a5c-9126-486b4c041a76
fd3c932f-93e2-4de7-b372-6c699f0b97bb
fd7408fc-944e-47b5-a6a9-f7e5b8457234
fe28a5db-897d-4ae0-a494-57dbac436075
Kaya E_Face Wash_100_2
Kaya_30_wipes_2
Kaya_Cleansing_30_wipes_2
Kaya_E_30_wipes_2
Kaya_Face Wash_100_2
Livon_50ML_Purple_Pack of 2
Livon_50ML_Purple_Pack of 3
Mediker_Anti-Lice_Pack of 2_50ML
Parachute_Biotin_Pack of 2_300ML
Parachute_Keratin_Pack of 2_300ML
B003NQESIS
B00FYWZE96
B00HR2CFVQ
B00L13WLFW
B00N2WT1C6
B00NYZTUVS
B00P4EYXF0
B00PR9N7XG
B00PR9N8A8
B00QV90A72
B00QV90GHG
B00QV90M6G
B00R5FEJIW
B00UTGC5HG
B00UTGCS0K
B01CHUVWWK
B07D5D9NWT
B07D5D9Q21
B07D5DN9P2
B07D5FG9R5
B07DCVG4VF
B07DCZKRVJ
B07G2VBBCJ
B07JGP7XK3
B07Q968G9Q
B07ZL1S3HD
B08B42PZC2
B08B44K4YS
B08B44N8JY
B08B57CF5P
B08MK7P8LC
B08WQN25MK
B08WQPPNSQ
B08WQPZ1JB
B092VSDQVN
B09DCKTL6R
B09FFD93MK
B09KV1R96H
B09PZ2NDT2
B09V35WW5Q
B09V35XFTM
B09V368KGJ
B09YDB6SPC
B09YDBCVC8
B09YDBP5MG
B09YDC3KZ9
B09ZDDRM7G
B09ZKVB5RL
B09ZL1LGNF
B0B1DDB542
B0B4WY36MC
B0B9ZQHGBT
B0BJFC2LS8
B0BSWYLD95
B0CL6HHMV4
B0CNX7RZ5C
B0CNX8GQ1J
B0CWLFJ5DF
B0CWLL6VQP
B0CWLLDG5K
B0CWLLWGR8
B0CWLP15LD
B0DCK2XWQ7
B0DCK52K47
B0DCK5BKZW
B0DN5KCP6N
B0DNPYBSRJ
B0DNPYJXCW
B0DNQ2114T
B0DRD5VJFG
B0DRD8Z31B
B0DS2GCTKG
B0DTPZDFPT
B0DVLMFNW3
B0DVLMJGBW
B0DVLN496Q
B0DVLNY83Y
B0DVLYNKPQ
B0F4DKH1WS
B0F4DMWX9J
B0FCS6NQKL
B0FCSG1552
B0FCXSCSZN
B0FGQB8RKZ
B0FJRZP6JW
B0FS6GCRDG
B0G1SKX4CM
B0GGHLBJL3
B0GGJ2TH8Z
B0GWRH9JLZ
B0GWRJ6BGH
B0H1JMCXHF
B002Q0PJ3K
B003O7DXLO
B0048CCGPS
B008DY631U
B008KH260C
B008KH2AUS
B008KH4HWC
B008KH67QQ
B008KH67ZM
B008NG0WZ6
B009NQUOB2
B00A8VQ5D2
B00AYKRUUO
B00CBRHLJ8
B00CBRHUEO
B00CBRHXFU
B00CBRHYKO
B00CBRI64W
B00CBRIKIE
B00CBRILZQ
B00CBRIPW0
B00CBRIQII
B00CBRIRDM
B00CBRIRYG
B00CBRISWC
B00CBRJ1SM
B00CBRJ34E
B00CBRJ5MO
B00CBRJ6H8
B00DRE2OFK
B00FRE7KTS
B00FRE7PFM
B00FRE7VBA
B00FYXN75S
B00FYXN7X0
B00GMBZWWC
B00GMC02XK
B00GMC04BK
B00K3TVBKG
B00K3TVKOS
B013E97N58
B013E997MK
B015WAUHZK
B01A8H2I0E
B01FK7RI2K
B01HBA97KK
B01IMU5BX0
B01LWPEJEP
B01LXOJC5V
B01MYZ7S50
B01N4DFORZ
B01N5CSEPU
B01NBK2V4R
B071CV4TN5
B0722884PT
B073TZG92R
B077BQY647
B077BTPPVX
B077HRJF54
B077HT24D7
B077HTJ33T
B078H9BXKY
B0791B4KXF
B079HWW3NM
B079Q17WXZ
B079QBB5YT
B07BDNCTFC
B07BDNGTYC
B07CCZP58S
B07DD2RZS4
B07DDGBSGH
B07GVMXBTP
B07GVT58MX
B07JLBKC67
B07JLP5J13
B07KZB82QC
B07MBFFRB1
B07R25DLY9
B07S2SKYTH
B07WLDJS3L
B07ZKV6L4Q
B0824B9GLL
B082SRNQWN
B082SSFPNF
B082VL4PYF
B082VTLBSS
B0847TLVJQ
B08FQYSQNN
B08J1DC484
B08JDKSH39
B09HC6WFM7
B09HC85ZPS
B09J5C7J7L
B09PBHX5FS
B09QKNHJNC
B09SLW3P71
B09SLWMVCL
B0B46VNL2B
B0C62H76QN
B0C62J1GKY
B0C62J9F77
B0C62JN1FR
B0C62KL9TC
B0C6XT96MC
B0C94BYFY5
B0C94H3P6G
B0CFLQMFGY
B0CG15FW2C
B0CG16N3P4
B0CG17DT8T
B0CG9PGDBV
B0CG9PNC4Q
B0CG9PV4DP
B0CG9R66NN
B0CGM3H7SN
B0CGM6PQBP
B0CGM6R518
B0CGM73L7H
B0CM3DWYBT
B0CM3FCQ2B
B0CSYYF6B7
B0CTHK1FS1
B0CTHKQ2Z3
B0CTHLW2Q4
B0CWRLX2D4
B0CWRW7ZKM
B0D2XZWGKB
B0D2Y1B1MN
B0D66FNXJ5
B0D817PBF7
B0D9YMT9KM
B0DN5YVDBK
B0DNQWB449
B0DQ8K4WVK
B0DQ8K5DV4
B0DQ8T5NTG
B0DRP4QKD8
B0DW47LW1V
B0DW48B5MT
B0F1N9LV2W
B0F3P7QX1T
B0F3XJTV5Z
B0F3XMTZG6
B0F4DPL9SD
B0F4DRJ157
B0F6D1D2XV
B0F6D57KHJ
B0F6D6R1H6
B0F7HFDQJL
B0FBGQ6SS9
B0FBGTNH92
B0FBGW4HK4
B0FBS1PFVX
B0FCFSX424
B0FCFXML6Z
B0FGY2NWLZ
B0FM7VN577
B0FNMZS3KB
B0FNN4954M
B0FTYZ1VCW
B0FTZ1LRDV
B0FY67CG6W
B0FY6C3GXS
B0FZH52RFN
B0FZH83ZCF
B0FZH9448V
B0G2596RRV
B0G25QF3H9
B0G25S6HTH
B0G25SH1ML
B0G25SQ341
B0GHP4JKCH
B0GHQYG78T
B0GQHV7JJM
B0GQTTK2K6
B0GQTVW6JG
B0GQTVZD8G
B0GQTZ4GZJ
B0GQV1MH6W
B0GQV1NDZB
B0GQV23K14
B0GQV2536Z
B0GQV3FWGW
B0GQV427TJ
B0GQV48W6G
B0GQV4SB1M
B0GQV4ZTPF
B0GQV53F9M
B0GQV61J3D
B0GQV87X3B
B0GQV895L5
B0GQV8C119
B0GQV94SDM
B0GQVB8B91
B0GQVD3L2T
B0GQVGGSSM
B0GQVGHRYB
B0GQVY3L2W
B0GR5Y9L63
B0GR61FSTP
B0GR61SGL2
B0GR64BRB5
B0GRVG1BH2
B0GT8SRWNG
B0GT8ZGZ4T
B0GT91H554
B0GTRTR6VK
B0GV1FF2DK
B0GW8RY1J3
B0H34621W9
B0H4W74JKR
B0H4W77FWJ
B0H4WC2TG4
B0H4WG41LB
B0H4WH7ZMM
B0H4WJB22Y
B0H4WK97XJ
B0H4WM1SJ4
B0H4WMFP7V
B0H4WMSQZZ
B0H4WSD1YK
BBCH3G5FKJHHAGZZ
BBCH3G5FS6DDBZ4M
BBCHAMW9FNXCPJZ4
BEOEUC2DYQJQ5SZ2
BEOHF3X5EZWCBYHE
BEOHF3X5PX7G4FZT
BEOHHSH3ZJENC6HE
BSTFTYBTDZHU3YA4
BWSGSF6F4GTFY2GU
BWSGSF6FZ8RG4TYH
BWSH5NZZQY2GQ7UW
BWSH5NZZRANZU8XB
CAFETMJQS4EGKKHH
CAFETMJQY5DHCCZE
CAFETMJQYFJ7HQTJ
CAFEUHZH6GZXG37B
CAFEUHZHD3RKAHVG
CAFEUHZHHZHQPRTM
CAFEUHZHU42DVTKZ
CAFEUHZHWZASEN3H
CAFF5FY5KXWSZCUC
CAFF5FY5RHXEY22G
CAFF5FY5TPUZR7YA
CAFF5FY5UNXKUVZE
CAFF7THHYGH5DKVD
CAFFPHTPNJUJYYKC
CAFFVHF5GTSZGQTH
CAFG2CHCF6TUDXTT
CAFG2CHXFDDTF5CG
CAFG7CFFAVCQHXXN
CAFGEFHXCJGNYQHR
CAFGJ66WZP9QZ8XQ
CAFGVJNFZWNZREKS
CAFGYJ7B5HHHCHHQ
CAFGYJ7BA2HHYMAE
CAFGYJ7BAZYJJRQ2
CAFGYJ7BFQ9VMSGH
CAFGYJ7BH23CSM3X
CAFGYJ7BHHHMAQQT
CAFGZKEJTSMUXG4M
CAFH3GY7BZGWPCRZ
CAFH3GY7WRWNFH34
CAFH3S89DZN8EQJ8
CAFH3S89RDGEEG38
CAFH3XTUFC8ZCDYP
CAFH3XTUGD4PUS3G
CAFH7UZGEAHT6TFF
CAFH7UZGVNS9X436
CAFH82Q2GJGGSPUX
CAFHBWCA5GF9XNVC
CAFHBWCAGJ2VFYVH
CAFHD9B6ZKAUHPFR
CAFHDFZVCWXVNMFS
CAFHDXTUHRTZGXWY
CAFHJZFNGZB46BYR
CAFHJZFNS6SBGS95
CAFHYQ5GVVM3AT4H
CAFHYXSH4QACHWGH
CAFHYXSHM4PZGGYH
CAFHYXSHQX2ASFQD
CAFHYXSHRVAQZTBS
CAFHYXSHYFAVFPQU
CAFHYXSHYZZHMND5
CAGGRF452UVCMPPA
CAGGRF453CNUCDDZ
CBKH3YJS6HXY4YZZ
CBKH3YJS9FZXWBEE
CBKH3YJSTXBSPCWB
CHNG5C3MHA4UHRKM
CHNG5C3MKSJGDSCN
CHPGJ672TSQVEUYQ
CHPGJ672YJ9FSRUA
CNDHH7Y5JS2DE6MB
CNDHH7Y5XUHP6ZUW
CNRD9XUPUTUM8GFA
CNREQ73YRMKGBHRT
DEOEF67ZHXG7FJJN
DEOEF67ZMERHKRX4
DEOEF67ZMHNYDF2Y
DEOEF67ZYDJFBXZJ
DEOEHXY95VN84UXU
DEOEM2KYVKYX9YQ8
DEOEMHPYZGAZGVCZ
DEOF27GU2HB2JDKK
DEOF27GUHBJXSMYF
DEOFGHCKGZR58Q6X
DEOFGHCKNDP3RNP6
DEOFVFAY3XKEGEKJ
DEOFVFAYZBRE4P2Q
DEOGEPFMXTFPCHHR
DEOGEPFTEAJBM357
DEOGEPFZZYZ7PHDE
DEOGY7SQQAHBHCZF
DEOHB3HQHYVN2T2U
DEOHB3HQZRQ4HZK8
DEOHCKXDPWJHRQJP
DEOHE8UU2RRRSYYM
DEOHE8UU5FHNSGGP
DEOHE8UUGU5ZXDF4
EDOET83CFQYH9JXK
EDOET83F9PZTDGAD
EDOET83FKANDJPFZ
EDOET83FNMMHPFNE
EDOET83FPF985AYZ
EDOET83FRKAWKTGG
EDOET83G3QFMGRCH
EDOET83GFXWTRG44
EDOF77H3QZGGXMBM
EDOFGH3URXFPNGER
EDOFHZYQHEAFSBZH
EDOFME2RCZ9AVURA
EDOFZFT5CBZ9MAWF
EDOG7C9U7CPHJKPZ
EDOG9GCUZKHZAAXZ
EDOGEDZQ9GSTQGAK
EDOGEDZQDFF6SEXY
EDOGEDZQMUGHYURG
EDOGEDZQPFTRJA4H
EDOGK3FMG6JHVSHT
EDOGQCF6KADPGUHV
EDOGZDEQEUEJMFNG
EDOH76DKFKHK9CQQ
EDOH76DKYZZBETRT
EDOH8ZFM2HVHFSEX
EDOH8ZFM57NDFCGP
EDOH8ZFMNWZQBSNZ
EDOHD6ZCAGF2XX2A
EDOHDNPBRNJ6G8FQ
EDOHHPCCHGH56CDH
EDOHMHKY94V5XH7Q
EDOHMHKYMKSGGYD4
FLTEQ73BBRWKQYWE
FMCH3HF4ASRG28T7
FSFEB2RQ2TGCJEVA
FSFEB2RQBFG8GMQQ
FSFEB2RQHH7K4CZE
FSFEB2RQZVTYFT4H
FSFFHNSKMDUGHXFG
FSFGMPHSBHGG38KQ
FSFGMPHSCGRJCZEH
HNYFSGQV2JGEFZNG
HNYFSGQVFH59EWY4
HNYFSH4M6FMX44XY
HNYFVHFFGGEREUFU
HNYGH9YPPU3TFKXX
HNYGYU63NGBBRPZN
HNYHFHGY6ZX3UHUJ
HNYHFMBETVWYE5Q6
HNYHHQQYEZTXP32P
HOLDMVGZMVPEWUYH
HOLETDMMDZN9CK7M
HOLETDMMHP4H8JZ4
HOLETDMMKJGFHJDF
HOLETDMXAFXF3MFH
HOLETDMXFUTSMXUY
HOLETDMXFXREFKMF
HOLETDMXGGFGHEYT
HOLETDMXHF3EHMNU
HOLETDMXMMYWSZUJ
HOLETDMXRBWG398H
HOLETDMXTGHZH2YZ
HOLETDMXZRBUY9MM
HOLETDN66RUVNCFE
HOLETDN6T3NKSGKG
HOLF589RHA9FDMVA
HOLF65NGBDMVFQVH
HOLF65NGTYUUDJHM
HOLF77HMBM2FGQVP
HOLF8WHUEFDBRXF4
HOLF9Z4ZK5TWHNHQ
HOLFBKYYZ9PZ2N3D
HOLFHFQANRPWA7YJ
HOLFJ2YCGRQMD5QH
HOLFJ2YCMFUFMZMW
HOLFME35JJ6HDZYG
HOLFMHSTVU9NCERV
HOLFMQAGJGMAQ7CH
HOLFTRGGCAZ2USEG
HOLFTVV6FPABJQ3V
HOLFXERWGTYWXGK9
HOLFZGZDRESSDUUW
HOLG7PQEYWKUZGMK
HOLG9GG3VRHBJVPQ
HOLGBHZNFRPGG5BY
HOLGBHZNSZSUWCYT
HOLGBWQPCPCKVCED
HOLGBWQPGSBTEJMT
HOLGBWQPJH8SH9X6
HOLGCVAHBJWHNFFP
HOLGFH8DNYH3TEPD
HOLGG5B7ABRVS9JG
HOLGMFXH4XCVD8DC
HOLGMFXHYDQNMR8K
HOLGMFXHZFQH2XKJ
HOLGSBUR4KYZZZVH
HOLGSBUSHTG797PF
HOLGSBUT7CKBFDGX
HOLGSBUT7FQ7GDEN
HOLGSBUUHFSZYX7K
HOLGSBXHHTXUZ7TE
HOLGSBXHVUKNDH4C
HOLGUAFZTPAFKGVE
HOLH7RDDBEGZRAYM
HOLH7RDDRQQRFADA
HOLH7RDDTDGY5EQW
HOLHBF3ZJSU4JNYJ
HOLHBK9FGWH7HCGS
HOLHBK9FTNSQCQXF
HOLHBY9FC5WDGGXJ
HOLHBYACGNGSQQH4
HOLHC5DKUBKEFW6R
HOLHCJRHR7ZTJ5HD
HOLHCKSGHDGCGZ2T
HOLHCKSGPXPJSPJH
HOLHCKSGUX5HTJV6
HOLHD74DCYHXZVTV
HOLHD74DDEBDZZBY
HOLHE48N7YMX2HKF
HOLHGERCAAXUEDKK
HOLHGERCJHFZUUSA
HOLHGNM9PPXYKPBX
HOLHGNNJZF6GFRHR
HOLHHCFFAZFVMKY5
HOLHHCFFTJBZGCXB
HSMDDAZEGXVQ2PD4
HSMDDAZEPBP4XEZ7
HSME7YWESFANWA7B
HSMEMWKET3P2MXFA
HSMFBB94CYFZJBMZ
HSMFBEEKKMCFFRT7
HSMFTWZGY9FPHGBA
HSMG2ZY5MRY4QY83
HSMG5NJHVVZYWZ9V
HSMGA3FNFSG2H9TF
HSMGQ65FFHGQSVEY
HSMGXM2FJVCF7S6B
HSMGXM2FNQJDUQ54
HSMHD2RJEYFXZURY
HSMHD2RJGUMXGX8F
HSMHGMHJXGEFPWKG
HSYD9YWKGNMBJ3HF
HSYD9YWKRYHGAUHD
HSYDQF2BZFYQMGNX
HSYDQF2BZXJDSMYY
HSYET849GZYZVYJN
HSYET849UGR9MGGT
HSYEZW68H8YAWGSW
HSYFHXHXTD6N3BS3
HSYFHXHXTMHYTBPY
HSYFZGNAUA3ZXK7Y
HSYG2GX6CCGS98NV
HSYH94JD9GXF22WP
HSYHCV8AR7FZ46EP
HSYHHFVHNYSSUCEQ
JASGCVAZ8GMVKMZU
JASGCVAZCSGDS2RH
JASGCVAZPSKGGZ8A
MSCDA3SYNKW4NQQ9
MSCDE7AHYXKQT8HS
MSCEUFZN7NMQHD9W
MSCEUFZNFQGSR8GB
MSCEUFZNJKKUUFQ7
MSCEUFZNNNUYDRSJ
MSCEUFZNP6VVGMPT
MSCEUFZNRQW8PGQK
MSCEUFZNXTGQ7GAJ
MSCEUFZNYM8JGTQW
MSCEUFZNZ35VSY9A
MSCFTYYAWQJWWTRY
MSCFTYYDTQCZVCEY
MSCFTYYG2ADPPTJX
MSCFTYYMPHQ6JH4G
MSCG5QZWEDHFKV6Q
MSCG5QZWH4FKHD6C
MSCG7A8MHYM5KYPV
MSCG7A9JK3DEWG3S
MSCGPU6EKNBWZMDB
MSCGPU6EQYXQFVUA
MSCGSF9JBJJESM4J
MSCGSHFNGKHRXKCP
MSCGSHFNPPZQGFGH
MSCGYK6HWKWUGFHQ
MSOGPU6DEVH5JNV2
MSOGXHREYUFKAYYP
PERGQCZGUYDRRC7J
PERGUTXRFZAEKTMR
PERGUTYCESVYQSUY
PERGWCFFNSPEKZVV
PERGY589PMGSSFEV
PERH3S9KW9SUHXUQ
SMPGBDRQADYAEFRD
SMPGPU6EGETAZK3Z
SMPGSF99YCGDVKH6
SMPHE5EJCSDGAPDD
SMPHE5EJFWGGKVN5
SMPHH7XNBMPZF3FZ
SMPHH7XNDNR4Z4UG
SMPHH7XNFEEW6B5N
SMPHH7XNG5CEKFJU
SMPHH7XNG7XSFECB
SMPHH7XNGXJBZTGZ
SMPHH7XNKADMV5DA
SMPHH7XNMCVUGZFV
SMPHH7XNQCXYGMG8
SMPHH7XNSSPJ2AQD
SMPHH7XNTYMCK8XY
SMPHH7XNW5AUXGHS
SMPHH7XNWQH9ZNBJ
SMPHHHZA4EHYZMSY
SMPHHHZASXDRX7GD
SMPHHHZC6EGZSH7H
SMPHZJ26KW5FVGKY
SMPHZJ26S5XP9HTD
SOPGPU6D4JEVDQ6U
SYCFXVBHKQEMD8ST
SYCFYGS3VUNZUUD3
SYCFYGS3Z8GWMFQC
TLCH2GGHCB8B7M3Q
TLCHFK7WEJ6HKNYZ
WIPHBWADB6FNPEJH
WIPHEGQDGYXATFJC
HOLFVFXY9TJ8KXBJ
PERHH2P3TMRXEDCU
MSCGSHFNBGGEH6GG
FSFHGVFFFHGGGWP8
FSFHGVFFCFGERNE5
SMPHH7XNR2STDRHY
MSCH2SG8YFRFMFAW
HSYGBWRE3QE9CWZZ
CBKHMFUHCJJKMJ6Q
SNRFY96TBAWV8XXR
HOLHFR6HFMBB5Y7B
HSYETZHYHGQ6P94J
HNYG8D36FHXDJRHX
SMPHH7XN3CDDWZ6Y
HOLHBYACBXRP6YRD
CBKHMFUHDGYHXAC7
CAFHNCY7MGGDFPSN
HSYEZXYQ6RAVZFKC
HTTH7CFAGRJZRZWY
BEOEUC2DCZKAAW2B
SNRFY96TB3EY9JVK
HSMHD2RJCZAJPZZU
CNRD9XUPFCFXMZZU
HSYH94JDWCFUCHUV
BSTF9ZARKWUEPGF4
HSYEZW68RVA7B95G
SMPHH7XNZCUZEWPN
EDOH8ZFMFRXZPAKH
HOLHAGBRCUY4AH5G
SMPFY96MHNCTTBDQ
HSYEZW68KRBCFHCV
SMPHH7XNCDJREE2Q
HOLHD2RSGSYA9KSB
SMPHH7XNXW4YFXRF
TNRDA3G2FRCHC4GT
BEOHJWF9FWVCG3WG
MSCHDVE8MCTTGXQU

In [87]:
soh_df = soh_df[soh_df['material_code'] != 'Combo']

In [90]:
soh_df['material_code'].unique()

array(['707136', '722897', '722898', ..., 'EDOG8F2CQTXYCS5C',
       'HSYFX5Y2D7ZGHCHV', 'BBCHAE2Y5VK4B2YM'], dtype=object)

In [88]:
soh_df['material_code'] = soh_df['material_code'].astype(int)

ValueError: invalid literal for int() with base 10: 'COCOS00000021'

In [ ]:
soh_df.columns

Index(['chain', 'fsn', 'soh', 'material_code', 'desc', 'brand', 'uom',
       'vol per unit', 'vol', 'fy index', 'bpm in lacs', 'category',
       'ecom brands', 'file', 'vol in kl', 'psku', 'pdes', 'date', 'asin',
       'asin.1', 'platform_name.1', 'product_title', 'ean', 'units',
       'material_group_code', 'uom_reporting', 'vol_per_unit', 'vol_in_lit',
       'vol in rum', 'indexrate', 'indexbpm', 'club sku', 'roum',
       'roum divide', 'month', 'day', 'month.1', 'unnamed: 18', 'unnamed: 19',
       'unnamed: 20', 'unnamed: 21', 'unnamed: 41', 'unnamed: 42'],
      dtype='object')

In [ ]:
soh_df.drop(['material_group_code', 'vol_per_unit', 'uom_reporting'], axis=1, inplace=True)

In [ ]:
len_before_merge = len(soh_df)
soh_df = soh_df.merge(
    material_master[['material_code', 'parent_material_code', 'material_group_code', 'vol_per_unit', 'uom_reporting']],
    on=['material_code'],
    how='left'
)
assert len_before_merge == len(soh_df)
del len_before_merge

In [ ]:
# soh_df[soh_df['parent_material_code'].isna()]

In [ ]:
soh_df = soh_df[soh_df['parent_material_code'].notna()]

In [ ]:
soh_df['parent_material_code'] = soh_df['parent_material_code'].astype(int)

In [ ]:
soh_df['chain'] = soh_df['chain'].replace({
    'MYNTRA': 'Myntra',
    'BB': 'Big Basket',
    'Flipkart Mintues': 'Flipkart National',
    'Flipkart Minutes': 'Flipkart National'
})

In [ ]:
sorted(soh_df['chain'].unique())

['Amazon ARIPL',
 'Amazon RK',
 'Big Basket',
 'Blinkit',
 'Flipkart Grocery',
 'Flipkart National',
 'Flipkart-Grocery',
 'Meesho',
 'Myntra',
 'Nykaa',
 'Purplle',
 'Swiggy',
 'Zepto']

In [ ]:
soh_df

,chain,fsn,soh,material_code,desc,brand,uom,vol per unit,vol,fy index,...,unnamed: 18,unnamed: 19,unnamed: 20,unnamed: 21,unnamed: 41,unnamed: 42,parent_material_code,material_group_code,vol_per_unit,uom_reporting
0,Blinkit,10000059,3131.0,707136,SAF TOTAL 5LT JAR,SAFF KO,KL,5000.0,15.655000,182263.023590,...,NaN,NaN,NaN,NaN,NaN,NaN,718322,SAFF KO,5000.0000,KL
1,Blinkit,10000062,500.0,722897,SMO 38G CUR&PEP HDC,SFOATS-FL,TO,38.0,0.019000,252810.051419,...,NaN,NaN,NaN,NaN,NaN,NaN,718492,SFOATS-FL,37.9997,TO
2,Blinkit,10000063,2711.0,722898,SMO 38G MAS&COR HDC,SFOATS-FL,TO,38.0,0.103018,252810.051419,...,NaN,NaN,NaN,NaN,NaN,NaN,718494,SFOATS-FL,37.9997,TO
3,Blinkit,10000361,1542.0,809267,SAFF SALT PLUS 1 KG PCH,SAFF SALT,TO,1000.0,1.542000,25994.993781,...,NaN,NaN,NaN,NaN,NaN,NaN,807029,SAFF SALT,1000.0000,TO
4,Blinkit,10000362,3387.0,713333,SAF TASTY PLUS 1L PCH,SAFF KOCO,KL,1000.0,3.387000,145305.652227,...,NaN,NaN,NaN,NaN,NaN,NaN,718328,SAFF KOCO,1000.0000,KL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92826,Flipkart Grocery,TLCHFK7WEJ6HKNYZ,4.0,809047,PA BABY POWDER 200 GMS,PABABY_GM,KG,200.0,0.800000,366.484998,...,NaN,NaN,NaN,NaN,NaN,NaN,809046,PABABY_GM,200.0000,KG
92827,Flipkart National,TLCHFK7WEJ6HKNYZ,1062.0,809047,PA BABY POWDER 200 GMS,PABABY_GM,KG,200.0,212.400000,366.484998,...,NaN,NaN,NaN,NaN,NaN,NaN,809046,PABABY_GM,200.0000,KG
92828,Flipkart Grocery,WIPHBWADB6FNPEJH,29.0,810688,PA BABY FACE BDY WIPE 362G,PABABY_GM,KG,362.0,10.498000,366.484998,...,NaN,NaN,NaN,NaN,NaN,NaN,810738,PABABY_GM,362.0000,KG
92829,Flipkart National,WIPHBWADB6FNPEJH,285.0,810688,PA BABY FACE BDY WIPE 362G,PABABY_GM,KG,362.0,103.170000,366.484998,...,NaN,NaN,NaN,NaN,NaN,NaN,810738,PABABY_GM,362.0000,KG
92830,Flipkart National,WIPHEGQDGYXATFJC,1.0,811028,PA BABY WIPE 365GM PO3,PADV_WIPS,KG,1095.0,1.095000,366.484998,...,NaN,NaN,NaN,NaN,NaN,NaN,811019,PADV_WIPS,1095.0000,KG

In [ ]:
soh_df['current_soh'] = soh_df['soh'] * soh_df['vol_per_unit'] / soh_df['uom_reporting'].map(
    lambda x: (10 ** 6) if x in ('KL', 'TO') else (10 ** 3)
)

In [ ]:
soh_df.dtypes

chain                    object
fsn                      object
soh                     float64
material_code             int64
desc                     object
brand                    object
uom                      object
vol per unit            float64
vol                     float64
fy index                float64
bpm in lacs             float64
category                 object
ecom brands              object
file                     object
vol in kl               float64
psku                     object
pdes                     object
date                     object
asin                     object
asin.1                   object
platform_name.1          object
product_title            object
ean                     float64
units                   float64
vol_in_lit              float64
vol in rum              float64
indexrate               float64
indexbpm                float64
club sku                 object
roum                    float64
roum divide             float64
month                   float64
day                     float64
month.1                  object
unnamed: 18             float64
unnamed: 19             float64
unnamed: 20             float64
unnamed: 21             float64
unnamed: 41             float64
unnamed: 42             float64
parent_material_code      int64
material_group_code      object
vol_per_unit            float64
uom_reporting            object
current_soh             float64
dtype: object

In [ ]:
soh_df.rename(
    columns={'date': 'inv date'},
    inplace=True
)

In [ ]:
soh_df = realign_pskus(soh_df.copy(), 'parent_material_code')

In [ ]:
soh_df = soh_df.groupby(
    ['chain', 'parent_material_code', 'inv date'], as_index=False
)['current_soh'].sum().rename(columns={
    'inv date': 'as_on_date'
})

In [ ]:
soh_df['key'] = soh_df[['chain', 'parent_material_code']].astype(str).agg('_'.join, axis=1)

In [ ]:
soh_df['as_on_date'] = pd.to_datetime(soh_df['as_on_date'])

In [ ]:
soh_df['run_month'] = soh_df['as_on_date'] + MonthEnd(0)

In [ ]:
soh_df.dtypes

chain                           object
parent_material_code             int64
as_on_date              datetime64[ns]
current_soh                    float64
key                             object
run_month               datetime64[ns]
dtype: object

In [ ]:
soh_df

,chain,parent_material_code,as_on_date,current_soh,key,run_month
0,Amazon ARIPL,718288,2024-12-14,16.794,Amazon ARIPL_718288,2024-12-31
1,Amazon ARIPL,718288,2025-01-25,28.038,Amazon ARIPL_718288,2025-01-31
2,Amazon ARIPL,718288,2025-02-22,23.850,Amazon ARIPL_718288,2025-02-28
3,Amazon ARIPL,718288,2025-03-29,9.204,Amazon ARIPL_718288,2025-03-31
4,Amazon ARIPL,718288,2025-04-19,7.044,Amazon ARIPL_718288,2025-04-30
...,...,...,...,...,...,...
44615,Zepto,811181,2026-07-31,0.526,Zepto_811181,2026-07-31
44616,Zepto,811287,2026-05-01,9.500,Zepto_811287,2026-05-31
44617,Zepto,811287,2026-06-01,55.600,Zepto_811287,2026-06-30
44618,Zepto,811287,2026-07-01,35.900,Zepto_811287,2026-07-31
44619,Zepto,811287,2026-07-31,33.300,Zepto_811287,2026-07-31

In [ ]:
date_wise_soh_vol_sum = soh_df.groupby(['as_on_date'], as_index=False)['current_soh'].sum()

In [ ]:
date_wise_soh_vol_sum[date_wise_soh_vol_sum['current_soh'] == 0]

Empty DataFrame
Columns: [as_on_date, current_soh]
Index: []

In [ ]:
soh_df[
    soh_df['as_on_date'].isin(
        date_wise_soh_vol_sum[date_wise_soh_vol_sum['current_soh'] == 0]['as_on_date'].unique()
    )
]['current_soh'].sum()

0.0

In [ ]:
soh_df = soh_df[
    ~soh_df['as_on_date'].isin(
        date_wise_soh_vol_sum[date_wise_soh_vol_sum['current_soh'] == 0]['as_on_date'].unique()
    )
]

In [ ]:
715096 in soh_df['parent_material_code'].values

False

In [ ]:
soh_df[['chain', 'as_on_date']].drop_duplicates().sort_values(by=['chain', 'as_on_date'])

              chain as_on_date
0      Amazon ARIPL 2024-12-14
1      Amazon ARIPL 2025-01-25
2      Amazon ARIPL 2025-02-22
3      Amazon ARIPL 2025-03-29
4      Amazon ARIPL 2025-04-19
...             ...        ...
40472         Zepto 2026-04-01
40451         Zepto 2026-05-01
40452         Zepto 2026-06-01
40453         Zepto 2026-07-01
40454         Zepto 2026-07-31

[242 rows x 2 columns]

In [ ]:
soh_df[soh_df['chain'] == 'Amazon ARIPL'].head(60)

,chain,parent_material_code,as_on_date,current_soh,key,run_month
0,Amazon ARIPL,718288,2024-12-14,16.794,Amazon ARIPL_718288,2024-12-31
1,Amazon ARIPL,718288,2025-01-25,28.038,Amazon ARIPL_718288,2025-01-31
2,Amazon ARIPL,718288,2025-02-22,23.850,Amazon ARIPL_718288,2025-02-28
3,Amazon ARIPL,718288,2025-03-29,9.204,Amazon ARIPL_718288,2025-03-31
4,Amazon ARIPL,718288,2025-04-19,7.044,Amazon ARIPL_718288,2025-04-30
5,Amazon ARIPL,718288,2025-05-31,12.048,Amazon ARIPL_718288,2025-05-31
6,Amazon ARIPL,718288,2025-06-19,9.138,Amazon ARIPL_718288,2025-06-30
7,Amazon ARIPL,718288,2025-07-31,6.840,Amazon ARIPL_718288,2025-07-31
8,Amazon ARIPL,718288,2025-08-02,17.118,Amazon ARIPL_718288,2025-08-31
9,Amazon ARIPL,718288,2025-10-05,18.864,Amazon ARIPL_718288,2025-10-31
10,Amazon ARIPL,718288,2025-10-31,21.618,Amazon ARIPL_718288,2025-10-31
11,Amazon ARIPL,718288,2025-11-30,18.432,Amazon ARIPL_718288,2025-11-30
12,Amazon ARIPL,718288,2025-12-31,23.574,Amazon ARIPL_718288,2025-12-31
13,Amazon ARIPL,718288,2026-02-02,21.156,Amazon ARIPL_718288,2026-02-28
14,Amazon ARIPL,718288,2026-03-02,97.428,Amazon ARIPL_718288,2026-03-31
15,Amazon ARIPL,718288,2026-04-02,21.540,Amazon ARIPL_718288,2026-04-30
16,Amazon ARIPL,718288,2026-04-29,8.850,Amazon ARIPL_718288,2026-04-30
17,Amazon ARIPL,718288,2026-06-02,14.796,Amazon ARIPL_718288,2026-06-30
18,Amazon ARIPL,718288,2026-07-01,28.008,Amazon ARIPL_718288,2026-07-31
19,Amazon ARIPL,718288,2026-07-31,20.424,Amazon ARIPL_718288,2026-07-31
20,Amazon ARIPL,718312,2024-12-14,0.040,Amazon ARIPL_718312,2024-12-31
21,Amazon ARIPL,718312,2025-01-25,0.037,Amazon ARIPL_718312,2025-01-31
22,Amazon ARIPL,718312,2025-02-22,0.038,Amazon ARIPL_718312,2025-02-28
23,Amazon ARIPL,718312,2025-03-29,0.036,Amazon ARIPL_718312,2025-03-31
24,Amazon ARIPL,718312,2025-04-19,0.033,Amazon ARIPL_718312,2025-04-30
25,Amazon ARIPL,718312,2025-05-31,0.015,Amazon ARIPL_718312,2025-05-31
26,Amazon ARIPL,718312,2025-07-31,0.004,Amazon ARIPL_718312,2025-07-31
27,Amazon ARIPL,718312,2025-08-02,0.012,Amazon ARIPL_718312,2025-08-31
28,Amazon ARIPL,718312,2026-04-29,0.287,Amazon ARIPL_718312,2026-04-30
29,Amazon ARIPL,718322,2024-12-14,7.285,Amazon ARIPL_718322,2024-12-31
30,Amazon ARIPL,718322,2025-01-25,4.065,Amazon ARIPL_718322,2025-01-31
31,Amazon ARIPL,718322,2025-02-22,4.560,Amazon ARIPL_718322,2025-02-28
32,Amazon ARIPL,718322,2025-03-29,3.275,Amazon ARIPL_718322,2025-03-31
33,Amazon ARIPL,718322,2025-04-19,3.690,Amazon ARIPL_718322,2025-04-30
34,Amazon ARIPL,718322,2025-05-31,3.045,Amazon ARIPL_718322,2025-05-31
35,Amazon ARIPL,718322,2025-06-19,1.835,Amazon ARIPL_718322,2025-06-30
36,Amazon ARIPL,718322,2025-07-31,1.400,Amazon ARIPL_718322,2025-07-31
37,Amazon ARIPL,718322,2025-08-02,7.005,Amazon ARIPL_718322,2025-08-31
38,Amazon ARIPL,718322,2025-10-05,5.565,Amazon ARIPL_718322,2025-10-31
39,Amazon ARIPL,718322,2025-10-31,3.690,Amazon ARIPL_718322,2025-10-31
40,Amazon ARIPL,718322,2025-11-30,6.095,Amazon ARIPL_718322,2025-11-30
41,Amazon ARIPL,718322,2025-12-31,6.430,Amazon ARIPL_718322,2025-12-31
42,Amazon ARIPL,718322,2026-02-02,27.785,Amazon ARIPL_718322,2026-02-28
43,Amazon ARIPL,718322,2026-03-02,68.430,Amazon ARIPL_718322,2026-03-31
44,Amazon ARIPL,718322,2026-04-02,25.180,Amazon ARIPL_718322,2026-04-30
45,Amazon ARIPL,718322,2026-04-29,15.015,Amazon ARIPL_718322,2026-04-30
46,Amazon ARIPL,718322,2026-06-02,9.480,Amazon ARIPL_718322,2026-06-30
47,Amazon ARIPL,718322,2026-07-01,15.755,Amazon ARIPL_718322,2026-07-31
48,Amazon ARIPL,718322,2026-07-31,5.760,Amazon ARIPL_718322,2026-07-31
49,Amazon ARIPL,718328,2024-12-14,0.695,Amazon ARIPL_718328,2024-12-31
50,Amazon ARIPL,718328,2025-01-25,2.219,Amazon ARIPL_718328,2025-01-31
51,Amazon ARIPL,718328,2025-02-22,1.120,Amazon ARIPL_718328,2025-02-28
52,Amazon ARIPL,718328,2025-03-29,0.824,Amazon ARIPL_718328,2025-03-31
53,Amazon ARIPL,718328,2025-04-19,1.850,Amazon ARIPL_718328,2025-04-30
54,Amazon ARIPL,718328,2025-05-31,1.381,Amazon ARIPL_718328,2025-05-31
55,Amazon ARIPL,718328,2025-06-19,1.465,Amazon ARIPL_718328,2025-06-30
56,Amazon ARIPL,718328,2025-07-31,0.391,Amazon ARIPL_718328,2025-07-31
57,Amazon ARIPL,718328,2025-08-02,5.058,Amazon ARIPL_718328,2025-08-31
58,Amazon ARIPL,718328,2025-10-05,2.259,Amazon ARIPL_718328,2025-10-31
59,Amazon ARIPL,718328,2025-10-31,0.884,Amazon ARIPL_718328,2025-10-31

### Forecasts

In [ ]:
forecasts = pd.read_excel(
    r"/data/aman_singh/acuuracy_check/Heuristics_all_combination_ecom_sep_live.xlsx",
    sheet_name='base'
)
forecasts = forecasts[forecasts['key'].notna()]
forecasts.head()

,key,month_date,pred_p3m,pred_p6m,pred_prophet,pred_rf,pred_value_p3m,pred_value_p6m,pred_value_prophet,pred_value_rf,...,pred_value_SARIMA,shrink_ratio_sarima,recency_heuristic_sarima,seasonal_heuristic_sarima,non_seasonal_heuristic_sarima,final_heuristic_sarima,final_heuristic_sarima_value,final_heuristic_sarima_value_2,ratio_last_year,quarter
0,Amazon ARIPL_718288,2026-08-31,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,1.0,33.954000,33.954,33.954000,33.954,0.471503,0.471503,1.443409,3
1,Flipkart National_722208,2026-09-30,0.0,0.016667,121.598226,195.280425,0.0,0.000231,1.688577,2.711767,...,0.719459,1.0,51.809888,0.000,51.809888,0.000,0.000000,0.000000,0.000000,0
2,Amazon ARIPL_718288,2026-10-31,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,1.0,33.954000,33.954,33.954000,33.954,0.471503,0.471503,1.087573,3
3,Amazon ARIPL_718288,2026-11-30,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,1.0,33.954000,33.954,33.954000,33.954,0.471503,0.471503,1.266715,4
4,Amazon ARIPL_718288,2026-12-31,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,1.0,33.954000,33.954,33.954000,33.954,0.471503,0.471503,1.184903,4

In [ ]:
forecasts['parent_material_code'] = forecasts['parent_material_code'].astype(int)

In [ ]:
forecasts.columns

Index(['key', 'month_date', 'pred_p3m', 'pred_p6m', 'pred_prophet', 'pred_rf',
       'pred_value_p3m', 'pred_value_p6m', 'pred_value_prophet',
       'pred_value_rf',
       ...
       'pred_value_SARIMA', 'shrink_ratio_sarima', 'recency_heuristic_sarima',
       'seasonal_heuristic_sarima', 'non_seasonal_heuristic_sarima',
       'final_heuristic_sarima', 'final_heuristic_sarima_value',
       'final_heuristic_sarima_value_2', 'ratio_last_year', 'quarter'],
      dtype='object', length=162)

In [ ]:
forecasts['Final Heuristic Prophet Vol'] = forecasts['final Heuristic Value'] * (10 ** 7) / forecasts['qtr_ind_rate_x']
forecasts.rename(columns = {'run_month_x': 'run_month'}, inplace=True)

In [ ]:
forecasts = forecasts[['key', 'month_date', 'platform_name', 'parent_material_code', 'brand_code', 
                       'run_month', 'M month', 'Final Heuristic Prophet Vol', 'skipped']]

In [ ]:
forecasts['run_month'].unique()

<DatetimeArray>
['2026-08-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [ ]:
forecasts.duplicated(['key', 'run_month', 'month_date']).sum()

0

In [ ]:
forecasts[forecasts.duplicated(['key', 'run_month', 'month_date'])]

Empty DataFrame
Columns: [key, month_date, platform_name, parent_material_code, brand_code, run_month, M month, Final Heuristic Prophet Vol, skipped]
Index: []

In [ ]:
forecasts['platform_name'].unique()

array(['Amazon ARIPL', 'Flipkart National', 'Flipkart Grocery',
       'Big Basket', 'Amazon RK', 'Meesho', 'Myntra', 'Nykaa', 'Purplle'],
      dtype=object)

In [ ]:
# forecasts.rename(columns={'Final Heuristic Prophet 2 Vol': 'Final Heuristic Prophet Vol'}, inplace=True)

In [ ]:
top_chains

['Amazon ARIPL',
 'Amazon RK',
 'Big Basket',
 'Flipkart Grocery',
 'Flipkart National',
 'Myntra',
 'Nykaa',
 'Meesho']

### Collate Everything

In [ ]:
print(f"SOH", soh_df['chain'].unique())
print("Offtakes:", offtakes_monthly_df['chain'].unique())
print("Plan Actuals:", plan_actuals_df['chain'].unique())

SOH ['Amazon ARIPL' 'Amazon RK' 'Big Basket' 'Blinkit' 'Flipkart Grocery'
 'Flipkart National' 'Flipkart-Grocery' 'Meesho' 'Myntra' 'Nykaa'
 'Purplle' 'Swiggy' 'Zepto']
Offtakes: ['Amazon ARIPL' 'Amazon RK' 'Big Basket' 'Flipkart Grocery'
 'Flipkart National' 'Meesho' 'Myntra' 'Nykaa' 'Purplle']
Plan Actuals: ['Amazon ARIPL' 'Amazon RK' 'Big Basket' 'Flipkart Grocery'
 'Flipkart National' 'Myntra']

In [ ]:
offtakes_monthly_df

,chain,parent_material_code,material_group_code,month_date,offtake_vol_rum,portfolio,key
0,Amazon ARIPL,718288,SAFF GOLD,2026-07-31,33.954,SAFFOLA OILS,Amazon ARIPL_718288
1,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288
2,Amazon ARIPL,718288,SAFF GOLD,2026-09-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288
3,Amazon ARIPL,718288,SAFF GOLD,2026-10-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288
4,Amazon ARIPL,718288,SAFF GOLD,2026-11-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288
...,...,...,...,...,...,...,...
138925,Purplle,810674,PA_ESS_HO,2027-01-31,0.000,HAIR OILS,Purplle_810674
138926,Purplle,810674,PA_ESS_HO,2027-02-28,0.000,HAIR OILS,Purplle_810674
138927,Purplle,810674,PA_ESS_HO,2027-03-31,0.000,HAIR OILS,Purplle_810674
138928,Purplle,810674,PA_ESS_HO,2027-04-30,0.000,HAIR OILS,Purplle_810674
138929,Purplle,810674,PA_ESS_HO,2027-05-31,0.000,HAIR OILS,Purplle_810674

In [ ]:
final_df = plan_actuals_df[
    ['key', 'chain', 'parent_material_code', 'material_group_code']
].drop_duplicates()

In [ ]:
duplicates = final_df[final_df.duplicated(subset=['key'], keep=False)]
duplicates

Empty DataFrame
Columns: [key, chain, parent_material_code, material_group_code]
Index: []

In [ ]:
# For duplicates, keep only the row with PABABY_ML material_group_code
duplicates = final_df[final_df.duplicated(subset=['key'], keep=False)]

# Get indices of duplicates that are NOT PABABY_ML
indices_to_drop = duplicates[duplicates['material_group_code'] != 'PABABY_ML'].index

# Remove those rows
final_df = final_df.drop(indices_to_drop)

# Verify no duplicates remain
print(final_df.duplicated(subset=['key']).sum())

0

In [ ]:
forecasts['run_month'].unique()

<DatetimeArray>
['2026-08-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [ ]:
tmp_df = pd.DataFrame()

for rm in ['2026-09-30']: 
    mth_dates = [pd.to_datetime(rm) + MonthEnd(i) for i in range(-1, 9)]
    for mth_dt in mth_dates:
        tmp_df2 = final_df.copy()
        tmp_df2['run_month'] = pd.to_datetime(rm)
        tmp_df2['month_date'] = pd.to_datetime(mth_dt)

        tmp_df = pd.concat([tmp_df, tmp_df2], ignore_index=True)
        del tmp_df2

final_df = tmp_df.copy()    
del tmp_df

### Merge Plan

In [ ]:
plan_actuals_df.duplicated(subset=['key', 'month_date']).sum()

0

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    plan_actuals_df[['key', 'month_date', 'pri_actuals_vol_rum', 'sec_apo_plan_vol_rum', 'Primary P3M']],
    on=['key', 'month_date'],
    how='left'
)
assert len(final_df) == len_before_merge
del len_before_merge

In [ ]:
final_df.duplicated(subset=['key', 'month_date']).sum()

0

In [ ]:
plan_actuals_df[plan_actuals_df['month_date']<'2026-06-30'].to_csv('/data/aman_singh/acuuracy_check/plan_actuals_df_ecom.csv', index=False)

In [ ]:
final_df.sort_values(by=['run_month', 'key', 'month_date'], inplace=True)

In [ ]:
for col in ['Primary P3M']:
    # if not 'LY' in col:  'LY P6M',
    final_df.loc[final_df['month_date'] > final_df['run_month'], [col]] = np.nan
    final_df[col] = final_df.groupby(['run_month', 'key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

### Merge offtakes

In [ ]:
final_df['key'].nunique()

4764

In [ ]:
offtakes_monthly_df['key'].nunique()

3536

In [ ]:
yy = final_df.copy()

In [ ]:
### Monthly Actual Offtakes
len_before_merge = len(final_df)
final_df = final_df.merge(
    offtakes_monthly_df[['month_date', 'key', 'offtake_vol_rum']].rename(columns={
        'offtake_vol_rum': 'Offtake Chain PSKU'
    }),
    on=['month_date', 'key'],
    how='left'
)   
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df[final_df['month_date'] == '2026-05-31']['key'].nunique()

0

In [ ]:
# x = final_df.copy()
# x.rename(columns = {'material_group_code':'Brand'},inplace = True)
# len_before_merge = len(x)
# x = x.merge(
#     qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
#         'brand_code': 'Brand',
#         'qtr_ind_rate': 'Index Rate'
#     }),
#     on=['Brand'],
#     how='left'
# )
# assert len_before_merge == len(x)
# del len_before_merge
# x['offtake_val'] = x['Offtake Chain PSKU']*x['Index Rate']/10**7
# x.groupby(['month_date'])['offtake_val'].sum().reset_index()#[20:]

In [ ]:
# lits = []
# for k in offtakes_monthly_df[offtakes_monthly_df['month_date'] == '2026-05-31']['key'].unique():
#     if(k not in final_df['key'].unique()):
#         lits.append(k)

In [ ]:
# lits

In [ ]:
# len(lits)

In [ ]:
# final_df[final_df['Offtake Chain PSKU'].isna()]

In [ ]:
mappings = {}

for run_month in final_df['run_month'].unique():
    # run_month = pd.to_datetime(run_month)

    if not run_month in mappings:
        mappings[run_month] = {}

    mappings[run_month][run_month] = 'M'

    for idx in range(1, 9):
        mappings[run_month][run_month + MonthEnd(idx)] = f"M+{idx}"


mappings

{Timestamp('2026-08-31 00:00:00'): {Timestamp('2026-08-31 00:00:00'): 'M',
  Timestamp('2026-09-30 00:00:00'): 'M+1',
  Timestamp('2026-10-31 00:00:00'): 'M+2',
  Timestamp('2026-11-30 00:00:00'): 'M+3',
  Timestamp('2026-12-31 00:00:00'): 'M+4',
  Timestamp('2027-01-31 00:00:00'): 'M+5',
  Timestamp('2027-02-28 00:00:00'): 'M+6',
  Timestamp('2027-03-31 00:00:00'): 'M+7',
  Timestamp('2027-04-30 00:00:00'): 'M+8'}}

In [ ]:
final_df['M month'] = final_df.apply(
    lambda x: mappings[x['run_month']].get(x['month_date'], np.nan),
    axis=1
)

In [ ]:
final_df[['run_month', 'month_date', 'M month']].drop_duplicates()

   run_month month_date M month
0 2026-08-31 2026-07-31     NaN
1 2026-08-31 2026-08-31       M
2 2026-08-31 2026-09-30     M+1
3 2026-08-31 2026-10-31     M+2
4 2026-08-31 2026-11-30     M+3
5 2026-08-31 2026-12-31     M+4
6 2026-08-31 2027-01-31     M+5
7 2026-08-31 2027-02-28     M+6
8 2026-08-31 2027-03-31     M+7
9 2026-08-31 2027-04-30     M+8

### Merge Forecasts

In [ ]:
forecasts.head()

,key,month_date,platform_name,parent_material_code,brand_code,run_month,M month,Final Heuristic Prophet Vol,skipped
0,Amazon ARIPL_718288,2026-08-31,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,M,33.954,1
1,Flipkart National_722208,2026-09-30,Flipkart National,722208,SAFF GOLD,2026-08-31,M+1,0.000,0
2,Amazon ARIPL_718288,2026-10-31,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,M+2,33.954,1
3,Amazon ARIPL_718288,2026-11-30,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,M+3,33.954,1
4,Amazon ARIPL_718288,2026-12-31,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,M+4,33.954,1

In [ ]:
forecasts.duplicated(subset=['key', 'month_date', 'run_month']).sum()

0

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    forecasts[['key', 'month_date', 'run_month', 'Final Heuristic Prophet Vol']],
    on=['key', 'month_date', 'run_month'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df.rename(columns={'Final Heuristic Prophet Vol': 'Offtake Chain PSKU Forecast Vol'}, inplace=True)

### Norms

In [ ]:
soh_df['as_on_date'].min()

Timestamp('2024-12-03 00:00:00')

In [ ]:
soh_df[~soh_df['chain'].isin(top_chains)]['chain'].unique()

array(['Blinkit', 'Flipkart-Grocery', 'Purplle', 'Swiggy', 'Zepto'],
      dtype=object)

In [ ]:
soh_df[soh_df['key'] == 'Amazon ARIPL_718288']

,chain,parent_material_code,as_on_date,current_soh,key,run_month
0,Amazon ARIPL,718288,2024-12-14,16.794,Amazon ARIPL_718288,2024-12-31
1,Amazon ARIPL,718288,2025-01-25,28.038,Amazon ARIPL_718288,2025-01-31
2,Amazon ARIPL,718288,2025-02-22,23.850,Amazon ARIPL_718288,2025-02-28
3,Amazon ARIPL,718288,2025-03-29,9.204,Amazon ARIPL_718288,2025-03-31
4,Amazon ARIPL,718288,2025-04-19,7.044,Amazon ARIPL_718288,2025-04-30
5,Amazon ARIPL,718288,2025-05-31,12.048,Amazon ARIPL_718288,2025-05-31
6,Amazon ARIPL,718288,2025-06-19,9.138,Amazon ARIPL_718288,2025-06-30
7,Amazon ARIPL,718288,2025-07-31,6.840,Amazon ARIPL_718288,2025-07-31
8,Amazon ARIPL,718288,2025-08-02,17.118,Amazon ARIPL_718288,2025-08-31
9,Amazon ARIPL,718288,2025-10-05,18.864,Amazon ARIPL_718288,2025-10-31
10,Amazon ARIPL,718288,2025-10-31,21.618,Amazon ARIPL_718288,2025-10-31
11,Amazon ARIPL,718288,2025-11-30,18.432,Amazon ARIPL_718288,2025-11-30
12,Amazon ARIPL,718288,2025-12-31,23.574,Amazon ARIPL_718288,2025-12-31
13,Amazon ARIPL,718288,2026-02-02,21.156,Amazon ARIPL_718288,2026-02-28
14,Amazon ARIPL,718288,2026-03-02,97.428,Amazon ARIPL_718288,2026-03-31
15,Amazon ARIPL,718288,2026-04-02,21.540,Amazon ARIPL_718288,2026-04-30
16,Amazon ARIPL,718288,2026-04-29,8.850,Amazon ARIPL_718288,2026-04-30
17,Amazon ARIPL,718288,2026-06-02,14.796,Amazon ARIPL_718288,2026-06-30
18,Amazon ARIPL,718288,2026-07-01,28.008,Amazon ARIPL_718288,2026-07-31
19,Amazon ARIPL,718288,2026-07-31,20.424,Amazon ARIPL_718288,2026-07-31

In [ ]:
avg_inventory = soh_df[
    (soh_df['chain'].isin(top_chains))
].groupby(
    ['key'], as_index=False
)['current_soh'].mean()

In [ ]:
soh_df['as_on_date'].min(), soh_df['as_on_date'].max()

(Timestamp('2024-12-03 00:00:00'), Timestamp('2026-07-31 00:00:00'))

In [ ]:
avg_daily_offtakes = offtakes_monthly_df[
    (offtakes_monthly_df['month_date'] > '2024-11-30') &
    (offtakes_monthly_df['month_date'] < '2026-08-01')
].copy()
avg_daily_offtakes['days'] = avg_daily_offtakes['month_date'].dt.day
avg_daily_offtakes = avg_daily_offtakes.groupby(
    ['key'], as_index=False
)[['offtake_vol_rum', 'days']].sum()

In [ ]:
avg_daily_offtakes

                      key  offtake_vol_rum  days
0     Amazon ARIPL_718288          33.9540    31
1     Amazon ARIPL_718322          15.1300    31
2     Amazon ARIPL_718328           8.4060    31
3     Amazon ARIPL_718330           6.1650    31
4     Amazon ARIPL_718341          17.6810    31
...                   ...              ...   ...
3531       Purplle_807725           0.0000   608
3532       Purplle_809042           1.8000   396
3533       Purplle_809250           0.0223   608
3534       Purplle_810673           0.5740   181
3535       Purplle_810674           0.3780   181

[3536 rows x 3 columns]

In [ ]:
avg_daily_offtakes['avg_offtakes_vol_rum'] = avg_daily_offtakes['offtake_vol_rum'] / avg_daily_offtakes['days']

In [ ]:
norm_days = avg_inventory.merge(
    avg_daily_offtakes[['key', 'avg_offtakes_vol_rum']],
    on=['key'],
    how='left'
) 
assert len(norm_days) == len(avg_inventory)

In [ ]:
norm_days

                      key  current_soh  avg_offtakes_vol_rum
0     Amazon ARIPL_718288    21.238200              1.095290
1     Amazon ARIPL_718312     0.055778                   NaN
2     Amazon ARIPL_718322    11.267250              0.488065
3     Amazon ARIPL_718328     4.171900              0.271161
4     Amazon ARIPL_718330     3.980500              0.198871
...                   ...          ...                   ...
2663         Nykaa_810673     1.972250              0.059221
2664         Nykaa_810674     1.050000              0.017182
2665         Nykaa_811005     1.512000                   NaN
2666         Nykaa_811019    40.098000              0.493175
2667         Nykaa_811021    16.290000              0.078351

[2668 rows x 3 columns]

In [ ]:
norm_days['norm_days'] = norm_days['current_soh'] / norm_days['avg_offtakes_vol_rum']

In [ ]:
# norm_days['norm_days'] = np.minimum(np.maximum(norm_days['norm_days'] - 30, 0), 30)

norm_days['norm_days'] = np.maximum(np.minimum(norm_days['norm_days'], 30), 5)

In [ ]:
norm_days['norm_days'] = norm_days['norm_days'].fillna(5)

In [ ]:
norms = final_df.copy()

In [ ]:
norms = norms[['key', 'run_month', 'month_date', 'Offtake Chain PSKU Forecast Vol']]

In [ ]:
norms['total_days_in_month'] = norms['month_date'].dt.day

In [ ]:
norms.isnull().sum()

key                                    0
run_month                              0
month_date                             0
Offtake Chain PSKU Forecast Vol    27878
total_days_in_month                    0
dtype: int64

In [ ]:
norms

,key,run_month,month_date,Offtake Chain PSKU Forecast Vol,total_days_in_month
0,Amazon ARIPL_715098,2026-08-31,2026-07-31,NaN,31
1,Amazon ARIPL_715098,2026-08-31,2026-08-31,NaN,31
2,Amazon ARIPL_715098,2026-08-31,2026-09-30,NaN,30
3,Amazon ARIPL_715098,2026-08-31,2026-10-31,NaN,31
4,Amazon ARIPL_715098,2026-08-31,2026-11-30,NaN,30
...,...,...,...,...,...
47635,Myntra_811564,2026-08-31,2026-12-31,NaN,31
47636,Myntra_811564,2026-08-31,2027-01-31,NaN,31
47637,Myntra_811564,2026-08-31,2027-02-28,NaN,28
47638,Myntra_811564,2026-08-31,2027-03-31,NaN,31
47639,Myntra_811564,2026-08-31,2027-04-30,NaN,30

In [ ]:
norms.isnull().sum()

key                                    0
run_month                              0
month_date                             0
Offtake Chain PSKU Forecast Vol    27878
total_days_in_month                    0
dtype: int64

In [ ]:
len_before_merge = len(norms)
norms = norms.merge(
    norm_days[['key', 'norm_days']],
    on=['key'],
    how='left'
)
assert len_before_merge == len(norms)
del len_before_merge

In [ ]:
norms['safety_stock'] = norms['Offtake Chain PSKU Forecast Vol'] *  norms['norm_days'] / norms['total_days_in_month']

In [ ]:
norm_days[norm_days.duplicated(subset=['key'])]

Empty DataFrame
Columns: [key, current_soh, avg_offtakes_vol_rum, norm_days]
Index: []

In [ ]:
final_df[final_df['key'] == 'Amazon ARIPL_715098']

,key,chain,parent_material_code,material_group_code,run_month,month_date,pri_actuals_vol_rum,sec_apo_plan_vol_rum,Primary P3M,Offtake Chain PSKU,M month,Offtake Chain PSKU Forecast Vol
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-07-31,0.0,0.0,0.0,NaN,NaN,NaN
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-08-31,0.0,0.0,0.0,NaN,M,NaN
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-09-30,0.0,0.0,0.0,NaN,M+1,NaN
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-10-31,0.0,0.0,0.0,NaN,M+2,NaN
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-11-30,0.0,0.0,0.0,NaN,M+3,NaN
5,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-12-31,0.0,0.0,0.0,NaN,M+4,NaN
6,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2027-01-31,NaN,NaN,0.0,NaN,M+5,NaN
7,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2027-02-28,NaN,NaN,0.0,NaN,M+6,NaN
8,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2027-03-31,NaN,NaN,0.0,NaN,M+7,NaN
9,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2027-04-30,NaN,NaN,0.0,NaN,M+8,NaN

In [ ]:
final_df[final_df.duplicated(subset=['key', 'run_month', 'month_date'])]#['material_group_code'].unique()

Empty DataFrame
Columns: [key, chain, parent_material_code, material_group_code, run_month, month_date, pri_actuals_vol_rum, sec_apo_plan_vol_rum, Primary P3M, Offtake Chain PSKU, M month, Offtake Chain PSKU Forecast Vol]
Index: []

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    norms.drop(['Offtake Chain PSKU Forecast Vol', 'total_days_in_month', 'norm_days'], axis=1).rename(columns={
        'safety_stock': 'norms_soh'
    }),
    on=['key', 'run_month', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
norms['month_date'] = norms['month_date'] - MonthEnd(1)

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    norms.drop(['Offtake Chain PSKU Forecast Vol', 'total_days_in_month'], axis=1),
    on=['key', 'run_month', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df.sort_values(
    by=['run_month', 'material_group_code', 'key', 'month_date'], inplace=True
)

In [ ]:
final_df['safety_stock'] = final_df['safety_stock'].fillna(0)

In [ ]:
chain_wise_max_soh_dates = soh_df[soh_df['chain'].isin(top_chains)].groupby(
    ['run_month', 'chain'], as_index=False
)['as_on_date'].max()

chain_wise_max_soh_dates

     run_month              chain as_on_date
0   2024-12-31       Amazon ARIPL 2024-12-14
1   2024-12-31          Amazon RK 2024-12-19
2   2024-12-31         Big Basket 2024-12-21
3   2024-12-31   Flipkart Grocery 2024-12-16
4   2024-12-31  Flipkart National 2024-12-20
..         ...                ...        ...
124 2026-07-31   Flipkart Grocery 2026-07-31
125 2026-07-31  Flipkart National 2026-07-31
126 2026-07-31             Meesho 2026-07-31
127 2026-07-31             Myntra 2026-07-31
128 2026-07-31              Nykaa 2026-07-31

[129 rows x 3 columns]

In [ ]:
chain_wise_max_soh_dates = (
    chain_wise_max_soh_dates
    .groupby('chain')
    .apply(lambda x: dict(zip(x['run_month'], x['as_on_date'])))
    .to_dict()
)

In [ ]:
last_date_soh = pd.DataFrame()

for c in chain_wise_max_soh_dates.keys():
    for rm in chain_wise_max_soh_dates[c].keys():
        last_date_soh = pd.concat([
            last_date_soh,
            soh_df[
                (soh_df['chain'] == c) &
                (soh_df['as_on_date'] == chain_wise_max_soh_dates[c][rm])
            ]
        ])

In [ ]:
last_date_soh['as_on_date'] = last_date_soh['as_on_date'] + MonthEnd(0)

In [ ]:
last_date_soh.groupby(['as_on_date'])['current_soh'].sum()

as_on_date
2024-12-31    246778.066431
2025-01-31    311218.299326
2025-02-28    192679.204553
2025-03-31    244457.303018
2025-04-30    366643.182600
2025-05-31    319795.321935
2025-06-30    398319.051492
2025-07-31    114248.954225
2025-08-31    698712.990596
2025-09-30    774083.078400
2025-10-31    397742.700376
2025-11-30    251355.181461
2025-12-31    435443.790881
2026-01-31    483352.629753
2026-02-28     69373.308492
2026-03-31    282498.423831
2026-04-30    294009.295182
2026-05-31    405360.322214
2026-06-30    428900.652800
2026-07-31    727605.579907
Name: current_soh, dtype: float64

In [ ]:
soh_df

,chain,parent_material_code,as_on_date,current_soh,key,run_month
0,Amazon ARIPL,718288,2024-12-14,16.794,Amazon ARIPL_718288,2024-12-31
1,Amazon ARIPL,718288,2025-01-25,28.038,Amazon ARIPL_718288,2025-01-31
2,Amazon ARIPL,718288,2025-02-22,23.850,Amazon ARIPL_718288,2025-02-28
3,Amazon ARIPL,718288,2025-03-29,9.204,Amazon ARIPL_718288,2025-03-31
4,Amazon ARIPL,718288,2025-04-19,7.044,Amazon ARIPL_718288,2025-04-30
...,...,...,...,...,...,...
44615,Zepto,811181,2026-07-31,0.526,Zepto_811181,2026-07-31
44616,Zepto,811287,2026-05-01,9.500,Zepto_811287,2026-05-31
44617,Zepto,811287,2026-06-01,55.600,Zepto_811287,2026-06-30
44618,Zepto,811287,2026-07-01,35.900,Zepto_811287,2026-07-31
44619,Zepto,811287,2026-07-31,33.300,Zepto_811287,2026-07-31

In [ ]:
# soh_df.to_csv('soh_data_ecom.csv')

In [ ]:
# last_date_soh.to_csv('last_date_soh.csv')

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    last_date_soh[['key', 'as_on_date', 'current_soh']].rename(
        columns={
            'as_on_date': 'month_date',
            'current_soh': 'Actual Closing SOH'
        }
    ),
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)

del len_before_merge

In [ ]:
final_df.sort_values(by=['run_month', 'key', 'month_date'], inplace=True)

In [ ]:
final_df['Actual Closing SOH_Lag_1'] = final_df.groupby(
    ['run_month', 'key']
)['Actual Closing SOH'].shift(1)

final_df['Actual Closing SOH Lag 2'] = final_df.groupby(
    ['run_month', 'key']
)['Actual Closing SOH'].shift(2)

In [ ]:
final_df['safety_stock'].sum()

3627319.152435735

In [ ]:
final_df['safety_stock'].min()

0.0

In [ ]:
# final_df['Assumed Closing SOH'] = np.where(
#     final_df['M month'] == 'M',  
#     final_df['Actual Closing SOH_Lag_1'].fillna(0) + final_df['sec_apo_plan_vol_rum'].fillna(0) \
#     - final_df['Offtake Chain PSKU Forecast Vol'].fillna(0),
#     final_df['safety_stock']
# )

final_df['Assumed Closing SOH'] = final_df['safety_stock']

In [ ]:
final_df['Assumed Closing SOH'] = final_df['Assumed Closing SOH'].clip(lower=0.0)

In [ ]:
final_df['Assumed Closing SOH_Lag_1'] = final_df.groupby(
    ['run_month', 'key']
)['Assumed Closing SOH'].shift(1)

final_df['Assumed Closing SOH Lag 2'] = final_df.groupby(
    ['run_month', 'key']
)['Assumed Closing SOH'].shift(2)

In [ ]:
final_df = final_df[
    ~final_df['material_group_code'].isin(['NC FREE', 'HC FREE'])
]

In [ ]:
final_df.isna().sum()

key                                    0
chain                                  0
parent_material_code                   0
material_group_code                    0
run_month                              0
month_date                             0
pri_actuals_vol_rum                24389
sec_apo_plan_vol_rum               24389
Primary P3M                           21
Offtake Chain PSKU                 30850
M month                             6092
Offtake Chain PSKU Forecast Vol    36312
norms_soh                          42704
norm_days                          39752
safety_stock                           0
Actual Closing SOH                 59339
Actual Closing SOH_Lag_1           59339
Actual Closing SOH Lag 2           59339
Assumed Closing SOH                    0
Assumed Closing SOH_Lag_1           6092
Assumed Closing SOH Lag 2          12184
dtype: int64

In [ ]:
final_df.shape

(60920, 21)

### Add P3M, LY

In [ ]:
actuals_df = plan_actuals_df.copy()
actuals_df['month_date'] = actuals_df['month_date'] + MonthEnd(0)

In [ ]:
actuals_df = actuals_df.groupby(
    ['key', 'month_date'], as_index=False
)[['pri_actuals_vol_rum', 'sec_actuals_vol_rum']].sum()

In [ ]:
actuals_df.duplicated(subset=['key', 'month_date']).sum()

0

In [ ]:
actuals_df['month_date'].min()

Timestamp('2023-01-31 00:00:00')

In [ ]:
actuals_df.sort_values(by=['key', 'month_date'], inplace=True)

In [ ]:
actuals_df['Primary P3M redundant'] = actuals_df.groupby(
['key'], as_index = False, group_keys = False)['pri_actuals_vol_rum'].shift(1)\
                            .rolling(window=3, min_periods=1).mean()

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    actuals_df.rename(columns={
        'pri_actuals_vol_rum': 'Primary Actuals Vol',
        'sec_actuals_vol_rum': 'Sec Actuals Vol'
    }),
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
ly_actuals_df = actuals_df.copy()

In [ ]:
ly_actuals_df['month_date'] = ly_actuals_df['month_date'] + MonthEnd(12)

In [ ]:
ly_actuals_df.rename(columns={
        'pri_actuals_vol_rum': 'LY Primary Actuals Vol',
        'sec_actuals_vol_rum': 'LY Sec Actuals Vol',
        'Primary P3M redundant': 'LY Primary P3M'
    })

,key,month_date,LY Primary Actuals Vol,LY Sec Actuals Vol,LY Primary P3M
0,Amazon ARIPL_715098,2024-07-31,0.0,0.0,NaN
1,Amazon ARIPL_715098,2024-08-31,0.0,0.0,0.0
2,Amazon ARIPL_715098,2024-09-30,0.0,0.0,0.0
3,Amazon ARIPL_715098,2024-10-31,0.0,0.0,0.0
4,Amazon ARIPL_715098,2024-11-30,0.0,0.0,0.0
...,...,...,...,...,...
218487,Nykaa_811564,2027-08-31,0.0,0.0,0.0
218488,Nykaa_811564,2027-09-30,0.0,0.0,0.0
218489,Nykaa_811564,2027-10-31,0.0,0.0,0.0
218490,Nykaa_811564,2027-11-30,0.0,0.0,0.0
218491,Nykaa_811564,2027-12-31,0.0,0.0,0.0

In [ ]:
ly_actuals_df.sort_values(by=['key', 'month_date'], inplace=True)

In [ ]:
ly_actuals_df['pri_actuals_vol_rum_lag_1'] = ly_actuals_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(1)

ly_actuals_df['pri_actuals_vol_rum_lag_2'] = ly_actuals_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(2)

ly_actuals_df['pri_actuals_vol_rum_lag_3'] = ly_actuals_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(3)


ly_actuals_df['pri_actuals_vol_rum_lead_1'] = ly_actuals_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(-1)

ly_actuals_df['pri_actuals_vol_rum_lead_2'] = ly_actuals_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(-2)

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    ly_actuals_df.rename(columns={
        'pri_actuals_vol_rum': 'LY Primary Actuals Vol',
        'sec_actuals_vol_rum': 'LY Sec Actuals Vol',
        'Primary P3M redundant': 'LY Primary P3M', 
        'pri_actuals_vol_rum_lag_1': 'LY Primary Actuals Lag 1 Vol',
        'pri_actuals_vol_rum_lag_2': 'LY Primary Actuals Lag 2 Vol',
        'pri_actuals_vol_rum_lag_3': 'LY Primary Actuals Lag 3 Vol',
        'pri_actuals_vol_rum_lead_1': 'LY Primary Actuals Lead 1 Vol',
        'pri_actuals_vol_rum_lead_2': 'LY Primary Actuals Lead 2 Vol',
    }),
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
prev_offtakes_monthly_df = offtakes_monthly_df.copy()

In [ ]:
final_offtakes_historical_df = prev_offtakes_monthly_df.copy()

In [ ]:
final_offtakes_historical_df.duplicated(subset=['chain', 'parent_material_code', 'month_date']).sum()

0

In [ ]:
final_offtakes_historical_df['key'] = final_offtakes_historical_df[['chain', 'parent_material_code']].astype(str).agg(
    '_'.join, axis=1
)

In [ ]:

final_offtakes_historical_df.sort_values(
    by=['key', 'month_date'], inplace=True
)

In [ ]:
final_offtakes_historical_df['P3M'] = final_offtakes_historical_df.groupby(
    ['key'], as_index = False, group_keys = False)['offtake_vol_rum'].shift(1)\
                                .rolling(window=3, min_periods=3).mean()

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    final_offtakes_historical_df[['key', 'month_date', 'offtake_vol_rum', 'P3M']].rename(
        columns={'P3M': 'Offtake P3M', 'offtake_vol_rum': 'Offtake Actuals Vol'}
    ),
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
ly_final_offtakes_historical_df = final_offtakes_historical_df.copy()

In [ ]:

ly_final_offtakes_historical_df.sort_values(
    by=['key', 'month_date'], inplace=True
)

In [ ]:
ly_final_offtakes_historical_df['month_date'].min()

Timestamp('2023-01-31 00:00:00')

In [ ]:
ly_final_offtakes_historical_df['month_date'] = ly_final_offtakes_historical_df['month_date'] + MonthEnd(12)
ly_final_offtakes_historical_df.head()

,chain,parent_material_code,material_group_code,month_date,offtake_vol_rum,portfolio,key,P3M
0,Amazon ARIPL,718288,SAFF GOLD,2027-07-31,33.954,SAFFOLA OILS,Amazon ARIPL_718288,NaN
1,Amazon ARIPL,718288,SAFF GOLD,2027-08-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288,NaN
2,Amazon ARIPL,718288,SAFF GOLD,2027-09-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288,NaN
3,Amazon ARIPL,718288,SAFF GOLD,2027-10-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288,11.318
4,Amazon ARIPL,718288,SAFF GOLD,2027-11-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288,0.000

In [ ]:
ly_final_offtakes_historical_df['LY Offtake Actuals Lag 1 Vol'] = ly_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(1)

ly_final_offtakes_historical_df['LY Offtake Actuals Lag 2 Vol'] = ly_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(2)

ly_final_offtakes_historical_df['LY Offtake Actuals Lag 3 Vol'] = ly_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(3)

In [ ]:
ly_final_offtakes_historical_df['LY Offtake Actuals Lead 1 Vol'] = ly_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(-1)

ly_final_offtakes_historical_df['LY Offtake Actuals Lead 2 Vol'] = ly_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(-2)

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    ly_final_offtakes_historical_df[['key', 'month_date', 'offtake_vol_rum', 'P3M', 
                                     'LY Offtake Actuals Lag 1 Vol', 'LY Offtake Actuals Lag 2 Vol', 
                                     'LY Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lead 1 Vol',
                                     'LY Offtake Actuals Lead 2 Vol']].rename(
        columns={'P3M': 'LY Offtake P3M', 'offtake_vol_rum': 'LY Offtake Actuals Vol'}
    ),
    on=['key', 'month_date'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df.sort_values(by=['run_month', 'key', 'month_date'], inplace=True)

In [ ]:
for col in ['Primary P3M', 'LY Primary P3M', 'Offtake P3M', 'LY Offtake P3M', 'Primary P3M redundant']:
    # if not 'LY' in col:  'LY P6M',
    final_df.loc[final_df['month_date'] > final_df['run_month'], [col]] = np.nan
    final_df[col] = final_df.groupby(['run_month', 'key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

In [ ]:
final_offtakes_historical_df.sort_values(by=['key', 'month_date'], inplace=True)

In [ ]:
lags_df = plan_actuals_df.copy()

In [ ]:
lags_df

,month_date,key,chain,parent_material_code,material_group_code,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,Primary P3M
24455,2023-07-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,8.3240,0.0,0.0
24456,2023-08-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,8.3240,0.0,0.0
24457,2023-09-30,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
24458,2023-10-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
24459,2023-11-30,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
339843,2026-08-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.65975,0.4953,0.0,0.0
339844,2026-09-30,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339845,2026-10-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339846,2026-11-30,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339847,2026-12-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0

In [ ]:
lags_df.sort_values(by=['key', 'month_date'], inplace=True)

In [ ]:
lags_df

,month_date,key,chain,parent_material_code,material_group_code,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum,Primary P3M
24455,2023-07-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,8.3240,0.0,0.0
24456,2023-08-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,8.3240,0.0,0.0
24457,2023-09-30,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
24458,2023-10-31,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
24459,2023-11-30,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,0.0,0.00000,0.0000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
339843,2026-08-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.65975,0.4953,0.0,0.0
339844,2026-09-30,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339845,2026-10-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339846,2026-11-30,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0
339847,2026-12-31,Nykaa_811564,Nykaa,811564,SAF-MUSLI,0.0,0.00000,0.0000,0.0,0.0

In [ ]:
lags_df['Primary_Lag_2'] = lags_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(1)

lags_df['Primary_Lag_3'] = lags_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(2)

In [ ]:
lags_df['month_date'] = lags_df['month_date'] + MonthEnd(1)

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    lags_df[['key', 'month_date', 'pri_actuals_vol_rum', 'Primary_Lag_2', 'Primary_Lag_3']].rename(columns={
        'month_date': 'run_month',
        'pri_actuals_vol_rum': 'Primary_Lag_1'
    }),
    on=['key', 'run_month'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
lags_final_offtakes_historical_df = final_offtakes_historical_df.copy()

lags_final_offtakes_historical_df.sort_values(by=['key', 'month_date'], inplace=True)
lags_final_offtakes_historical_df['OT_Lag_2'] = lags_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(1)

lags_final_offtakes_historical_df['OT_Lag_3'] = lags_final_offtakes_historical_df.groupby(
    ['key']
)['offtake_vol_rum'].shift(2)

In [ ]:
# x = lags_final_offtakes_historical_df.copy()
# x.rename(columns = {'material_group_code':'Brand'},inplace = True)
# len_before_merge = len(x)
# x = x.merge(
#     qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
#         'brand_code': 'Brand',
#         'qtr_ind_rate': 'Index Rate'
#     }),
#     on=['Brand'],
#     how='left'
# )
# assert len_before_merge == len(x)
# del len_before_merge
# x['offtake_val_lag3'] = x['OT_Lag_3']*x['Index Rate']/10**7
# x['offtake_val_lag2'] = x['OT_Lag_2']*x['Index Rate']/10**7
# x['offtake_val_lag1'] = x['offtake_vol_rum']*x['Index Rate']/10**7
# x

In [ ]:
# x.columns
# x[x['month_date'] == '2026-06-30'][['offtake_val_lag3', 'offtake_val_lag2',
#        'offtake_val_lag1']].sum()

In [ ]:
# x[(x['key'].isin(final_df['key'].unique())) & (x['month_date'] == '2026-06-30')][['offtake_val_lag3', 'offtake_val_lag2',
#        'offtake_val_lag1']].sum()

In [ ]:
# x[(~x['key'].isin(final_df['key'].unique())) & (x['month_date'] == '2026-06-30')].to_csv('key_check.csv')

In [ ]:
lags_final_offtakes_historical_df

,chain,parent_material_code,material_group_code,month_date,offtake_vol_rum,portfolio,key,P3M,OT_Lag_2,OT_Lag_3
0,Amazon ARIPL,718288,SAFF GOLD,2026-07-31,33.954,SAFFOLA OILS,Amazon ARIPL_718288,NaN,NaN,NaN
1,Amazon ARIPL,718288,SAFF GOLD,2026-08-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288,NaN,33.954,NaN
2,Amazon ARIPL,718288,SAFF GOLD,2026-09-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288,NaN,0.000,33.954
3,Amazon ARIPL,718288,SAFF GOLD,2026-10-31,0.000,SAFFOLA OILS,Amazon ARIPL_718288,11.318,0.000,0.000
4,Amazon ARIPL,718288,SAFF GOLD,2026-11-30,0.000,SAFFOLA OILS,Amazon ARIPL_718288,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...
138925,Purplle,810674,PA_ESS_HO,2027-01-31,0.000,HAIR OILS,Purplle_810674,0.000,0.000,0.000
138926,Purplle,810674,PA_ESS_HO,2027-02-28,0.000,HAIR OILS,Purplle_810674,0.000,0.000,0.000
138927,Purplle,810674,PA_ESS_HO,2027-03-31,0.000,HAIR OILS,Purplle_810674,0.000,0.000,0.000
138928,Purplle,810674,PA_ESS_HO,2027-04-30,0.000,HAIR OILS,Purplle_810674,0.000,0.000,0.000
138929,Purplle,810674,PA_ESS_HO,2027-05-31,0.000,HAIR OILS,Purplle_810674,0.000,0.000,0.000

In [ ]:
lags_final_offtakes_historical_df['month_date'] = lags_final_offtakes_historical_df['month_date'] + MonthEnd(1)

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    lags_final_offtakes_historical_df[['key', 'month_date', 'offtake_vol_rum', 'OT_Lag_2', 'OT_Lag_3']].rename(columns={
        'month_date': 'run_month',
        'offtake_vol_rum': 'OT_Lag_1'
    }),
    on=['key', 'run_month'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df

,key,chain,parent_material_code,material_group_code,run_month,month_date,pri_actuals_vol_rum,sec_apo_plan_vol_rum,Primary P3M,Offtake Chain PSKU,...,LY Offtake Actuals Lag 2 Vol,LY Offtake Actuals Lag 3 Vol,LY Offtake Actuals Lead 1 Vol,LY Offtake Actuals Lead 2 Vol,Primary_Lag_1,Primary_Lag_2,Primary_Lag_3,OT_Lag_1,OT_Lag_2,OT_Lag_3
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-07-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-08-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-09-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-10-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-11-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-01-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-02-28,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-03-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-04-30,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# x = final_df.copy()
# x.rename(columns = {'material_group_code':'Brand'},inplace = True)
# len_before_merge = len(x)
# x = x.merge(
#     qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
#         'brand_code': 'Brand',
#         'qtr_ind_rate': 'Index Rate'
#     }),
#     on=['Brand'],
#     how='left'
# )
# assert len_before_merge == len(x)
# del len_before_merge
# x['offtake_val'] = x['OT_Lag_2']*x['Index Rate']/10**7
# x.groupby(['month_date'])['offtake_val'].sum().reset_index()#[20:]

In [ ]:
final_df

,key,chain,parent_material_code,material_group_code,run_month,month_date,pri_actuals_vol_rum,sec_apo_plan_vol_rum,Primary P3M,Offtake Chain PSKU,...,LY Offtake Actuals Lag 2 Vol,LY Offtake Actuals Lag 3 Vol,LY Offtake Actuals Lead 1 Vol,LY Offtake Actuals Lead 2 Vol,Primary_Lag_1,Primary_Lag_2,Primary_Lag_3,OT_Lag_1,OT_Lag_2,OT_Lag_3
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-07-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-08-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-09-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-10-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-11-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-01-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-02-28,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-03-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-04-30,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# final_df.to_csv('ECOM_OTP_v0_check.csv', index=False)

In [ ]:
forecasts['run_month'].unique()

<DatetimeArray>
['2026-08-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [ ]:
def calculate_primary_iteratively(key_df):
    key_df = key_df.sort_values('month_date').copy()
    key_df = key_df[key_df['month_date'] >= key_df['run_month']]

    # Fill NaNs
    fill_cols = [
        'Offtake Chain PSKU Forecast Vol',
        'safety_stock',
        'Actual Closing SOH_Lag_1'
    ]
    key_df[fill_cols] = key_df[fill_cols].fillna(0)

    _key = key_df['key'].iloc[0]
    _run_month = key_df['run_month'].iloc[0]

    outputs = []
    prev_soh = None

    for _, row in key_df.iterrows():
        forecast = row['Offtake Chain PSKU Forecast Vol']
        safety_stock = row['safety_stock']

        if row['M month'] == 'M':
            opening_soh = row['Actual Closing SOH_Lag_1']
        else:
            opening_soh = prev_soh

        primary_vol = max(
            forecast + safety_stock - opening_soh,
            0
        )

        assumed_closing_soh = max(
            opening_soh + primary_vol - forecast,
            0
        )

        outputs.append({
            'run_month': _run_month,
            'key': _key,
            'month_date': row['month_date'],
            'Calculated Primary Vol': primary_vol,
            'Final Assumed Closing SOH Vol': assumed_closing_soh
        })

        prev_soh = assumed_closing_soh

    return outputs

In [ ]:
# # final_df['Calculated Primary Vol'] = np.where(
# #     final_df['M month'] == 'M',
# #     final_df['sec_apo_plan_vol_rum'],
# #     final_df['Offtake Chain PSKU Forecast Vol'].fillna(0) + \
# #         final_df['safety_stock'].fillna(0) - \
# #         final_df['Assumed Closing SOH_Lag_1'].fillna(0)
# # )


# final_df['Calculated Primary Vol'] = final_df['Offtake Chain PSKU Forecast Vol'].fillna(0) + \
#     final_df['safety_stock'].fillna(0) - final_df['Assumed Closing SOH_Lag_1'].fillna(0)

In [ ]:
# final_df['Calculated Primary Vol'] = final_df['Calculated Primary Vol'].clip(lower=0)

In [ ]:
final_df

,key,chain,parent_material_code,material_group_code,run_month,month_date,pri_actuals_vol_rum,sec_apo_plan_vol_rum,Primary P3M,Offtake Chain PSKU,...,LY Offtake Actuals Lag 2 Vol,LY Offtake Actuals Lag 3 Vol,LY Offtake Actuals Lead 1 Vol,LY Offtake Actuals Lead 2 Vol,Primary_Lag_1,Primary_Lag_2,Primary_Lag_3,OT_Lag_1,OT_Lag_2,OT_Lag_3
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-07-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-08-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-09-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-10-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-11-30,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-01-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-02-28,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-03-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-04-30,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
calculated_primary = []

for (_, _), group_df in tqdm(final_df.groupby(['run_month', 'key'])):
    calculated_primary.extend(
        calculate_primary_iteratively(group_df)
    )

calculated_primary_df = pd.DataFrame(calculated_primary)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6092/6092 [00:14<00:00, 435.12it/s]

In [ ]:
del calculated_primary

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    calculated_primary_df,
    on=['run_month', 'month_date', 'key'],
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df['Calculated Primary Vol'].min(), final_df['Final Assumed Closing SOH Vol'].min()

(0.0, 0.0)

In [ ]:
final_df.sort_values(by=['run_month', 'key', 'month_date'], inplace=True)

In [ ]:
final_df['Final Assumed Closing SOH Lag 1 Vol'] = final_df.groupby(
    ['run_month', 'key']
)['Final Assumed Closing SOH Vol'].shift(1)

final_df['Final Assumed Closing SOH Lag 2 Vol'] = final_df.groupby(
    ['run_month', 'key']
)['Final Assumed Closing SOH Vol'].shift(2)

In [ ]:
final_df

,key,chain,parent_material_code,material_group_code,run_month,month_date,pri_actuals_vol_rum,sec_apo_plan_vol_rum,Primary P3M,Offtake Chain PSKU,...,Primary_Lag_1,Primary_Lag_2,Primary_Lag_3,OT_Lag_1,OT_Lag_2,OT_Lag_3,Calculated Primary Vol,Final Assumed Closing SOH Vol,Final Assumed Closing SOH Lag 1 Vol,Final Assumed Closing SOH Lag 2 Vol
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-07-31,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-08-31,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-09-30,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,NaN
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-10-31,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,2026-08-31,2026-11-30,0.0,0.0,0.0,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-01-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-02-28,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-03-31,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,2026-08-31,2027-04-30,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [ ]:
brand_md_df

    brand_code     portfolio
0    BD_BDOL_M        BEARDO
1    BD_HRWX_M        BEARDO
2    BRD_BDCOL        BEARDO
3    BRD_BDOIL        BEARDO
4    BRD_BDSPR        BEARDO
..         ...           ...
315  PURSNS_GM     SKIN CARE
316  PURSNS_ML     SKIN CARE
317  TO_CL_OTG     SKIN CARE
318  TO_CL_OTM     SKIN CARE
319  PLX_TDRCN  WATER PREMIX

[320 rows x 2 columns]

In [ ]:
def read_qtr_ind_rate_table():
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=prod_conn, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    
    return qtr_ind_rate

In [ ]:
qtr_ind_rate_df = read_qtr_ind_rate_table()
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(
        columns={'brand_code': 'material_group_code'}
    ),
    on=['material_group_code'], 
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
len_before_merge = len(final_df)
final_df = final_df.merge(
    brand_md_df.rename(
        columns={'brand_code': 'material_group_code'}
    ),
    on=['material_group_code'], 
    how='left'
)
assert len_before_merge == len(final_df)
del len_before_merge

In [ ]:
final_df.columns

Index(['key', 'chain', 'parent_material_code', 'material_group_code',
       'run_month', 'month_date', 'pri_actuals_vol_rum',
       'sec_apo_plan_vol_rum', 'Primary P3M', 'Offtake Chain PSKU', 'M month',
       'Offtake Chain PSKU Forecast Vol', 'norms_soh', 'norm_days',
       'safety_stock', 'Actual Closing SOH', 'Actual Closing SOH_Lag_1',
       'Actual Closing SOH Lag 2', 'Assumed Closing SOH',
       'Assumed Closing SOH_Lag_1', 'Assumed Closing SOH Lag 2',
       'Primary Actuals Vol', 'Sec Actuals Vol', 'Primary P3M redundant',
       'LY Primary Actuals Vol', 'LY Sec Actuals Vol', 'LY Primary P3M',
       'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
       'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
       'LY Primary Actuals Lead 2 Vol', 'Offtake Actuals Vol', 'Offtake P3M',
       'LY Offtake Actuals Vol', 'LY Offtake P3M',
       'LY Offtake Actuals Lag 1 Vol', 'LY Offtake Actuals Lag 2 Vol',
       'LY Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lead 1 Vol',
       'LY Offtake Actuals Lead 2 Vol', 'Primary_Lag_1', 'Primary_Lag_2',
       'Primary_Lag_3', 'OT_Lag_1', 'OT_Lag_2', 'OT_Lag_3',
       'Calculated Primary Vol', 'Final Assumed Closing SOH Vol',
       'Final Assumed Closing SOH Lag 1 Vol',
       'Final Assumed Closing SOH Lag 2 Vol', 'qtr_ind_rate', 'portfolio'],
      dtype='object')

In [ ]:
final_df = final_df.rename(columns={
    'key': 'Key',
    'chain': 'Chain',
    'parent_material_code': 'PSKU',
    'material_group_code': 'Brand',
    'run_month': 'Run Month',
    'month_date': 'Month Date',
    'pri_actuals_vol_rum': 'Primary Till Date Actuals Vol',
    'sec_apo_plan_vol_rum': 'Secondary Plan Vol',
    'Primary P3M': 'Primary P3M Vol',
    'Offtake Chain PSKU': 'Offtake Chain PSKU Vol',
    'norms_soh': 'Norms SOH',
    'norm_days': 'Norm Days',
    'safety_stock': 'Safety Stock Vol',
    'Actual Closing SOH': 'Actual Closing SOH Vol',
    'Actual Closing SOH_Lag_1': 'Actual Closing SOH Lag 1 Vol',
    'Actual Closing SOH Lag 2': 'Actual Closing SOH Lag 2 Vol',
    'Assumed Closing SOH': 'Assumed Closing SOH Vol',
    'Assumed Closing SOH_Lag_1': 'Assumed Closing SOH Lag 1 Vol',
    'Primary P3M redundant': 'Primary P3M redundant Vol',
    'LY Primary P3M': 'LY Primary P3M Vol',
    'Offtake P3M': 'Offtake P3M Vol',
    'LY Offtake P3M': 'LY Offtake P3M Vol',
    'Primary_Lag_1': 'Primary Actuals Lag 1 Vol',
    'Primary_Lag_2': 'Primary Actuals Lag 2 Vol',
    'Primary_Lag_3': 'Primary Actuals Lag 3 Vol',
    'OT_Lag_1': 'Offtake Actuals Lag 1 Vol',
    'OT_Lag_2': 'Offtake Actuals Lag 2 Vol',
    'OT_Lag_3': 'Offtake Actuals Lag 3 Vol',
    'qtr_ind_rate': 'Index Rate',
    'portfolio': 'Portfolio'
})

In [ ]:
final_df.columns

Index(['Key', 'Chain', 'PSKU', 'Brand', 'Run Month', 'Month Date',
       'Primary Till Date Actuals Vol', 'Secondary Plan Vol',
       'Primary P3M Vol', 'Offtake Chain PSKU Vol', 'M month',
       'Offtake Chain PSKU Forecast Vol', 'Norms SOH', 'Norm Days',
       'Safety Stock Vol', 'Actual Closing SOH Vol',
       'Actual Closing SOH Lag 1 Vol', 'Actual Closing SOH Lag 2 Vol',
       'Assumed Closing SOH Vol', 'Assumed Closing SOH Lag 1 Vol',
       'Assumed Closing SOH Lag 2', 'Primary Actuals Vol', 'Sec Actuals Vol',
       'Primary P3M redundant Vol', 'LY Primary Actuals Vol',
       'LY Sec Actuals Vol', 'LY Primary P3M Vol',
       'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
       'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
       'LY Primary Actuals Lead 2 Vol', 'Offtake Actuals Vol',
       'Offtake P3M Vol', 'LY Offtake Actuals Vol', 'LY Offtake P3M Vol',
       'LY Offtake Actuals Lag 1 Vol', 'LY Offtake Actuals Lag 2 Vol',
       'LY Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lead 1 Vol',
       'LY Offtake Actuals Lead 2 Vol', 'Primary Actuals Lag 1 Vol',
       'Primary Actuals Lag 2 Vol', 'Primary Actuals Lag 3 Vol',
       'Offtake Actuals Lag 1 Vol', 'Offtake Actuals Lag 2 Vol',
       'Offtake Actuals Lag 3 Vol', 'Calculated Primary Vol',
       'Final Assumed Closing SOH Vol', 'Final Assumed Closing SOH Lag 1 Vol',
       'Final Assumed Closing SOH Lag 2 Vol', 'Index Rate', 'Portfolio'],
      dtype='object')

In [ ]:
final_df = final_df[[
    'Key', 'Chain', 'PSKU', 'Brand', 'Index Rate',
    'Portfolio', 'Run Month', 'Month Date',  'M month',

    'Primary Till Date Actuals Vol', 'Secondary Plan Vol',
    'Primary P3M Vol', 'Offtake Chain PSKU Vol',

    'Offtake Chain PSKU Forecast Vol', 'Norms SOH', 'Norm Days',
    'Safety Stock Vol', 
    
    'Actual Closing SOH Vol', 'Actual Closing SOH Lag 1 Vol', 
    'Actual Closing SOH Lag 2 Vol', 'Assumed Closing SOH Vol',
    'Assumed Closing SOH Lag 1 Vol', 'Final Assumed Closing SOH Vol', 
    'Final Assumed Closing SOH Lag 1 Vol', 
    
    'Primary Actuals Vol', 'Sec Actuals Vol', 'Primary P3M redundant Vol',
    'LY Primary Actuals Vol', 'LY Sec Actuals Vol', 'LY Primary P3M Vol',
    'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol', 'Primary Actuals Lag 3 Vol',
    'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
    'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
    'LY Primary Actuals Lead 2 Vol',

    'Offtake Actuals Vol', 'Offtake P3M Vol', 'LY Offtake Actuals Vol',
    'LY Offtake P3M Vol', 
    'Offtake Actuals Lag 1 Vol', 'Offtake Actuals Lag 2 Vol',
    'Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lag 1 Vol', 
    'LY Offtake Actuals Lag 2 Vol', 'LY Offtake Actuals Lag 3 Vol', 
    'LY Offtake Actuals Lead 1 Vol', 'LY Offtake Actuals Lead 2 Vol', 

    'Calculated Primary Vol'
]]

In [ ]:
vol_to_val_cols = [col for col in final_df.columns if 'Vol' in col]
vol_to_val_cols

['Primary Till Date Actuals Vol',
 'Secondary Plan Vol',
 'Primary P3M Vol',
 'Offtake Chain PSKU Vol',
 'Offtake Chain PSKU Forecast Vol',
 'Safety Stock Vol',
 'Actual Closing SOH Vol',
 'Actual Closing SOH Lag 1 Vol',
 'Actual Closing SOH Lag 2 Vol',
 'Assumed Closing SOH Vol',
 'Assumed Closing SOH Lag 1 Vol',
 'Final Assumed Closing SOH Vol',
 'Final Assumed Closing SOH Lag 1 Vol',
 'Primary Actuals Vol',
 'Sec Actuals Vol',
 'Primary P3M redundant Vol',
 'LY Primary Actuals Vol',
 'LY Sec Actuals Vol',
 'LY Primary P3M Vol',
 'Primary Actuals Lag 1 Vol',
 'Primary Actuals Lag 2 Vol',
 'Primary Actuals Lag 3 Vol',
 'LY Primary Actuals Lag 1 Vol',
 'LY Primary Actuals Lag 2 Vol',
 'LY Primary Actuals Lag 3 Vol',
 'LY Primary Actuals Lead 1 Vol',
 'LY Primary Actuals Lead 2 Vol',
 'Offtake Actuals Vol',
 'Offtake P3M Vol',
 'LY Offtake Actuals Vol',
 'LY Offtake P3M Vol',
 'Offtake Actuals Lag 1 Vol',
 'Offtake Actuals Lag 2 Vol',
 'Offtake Actuals Lag 3 Vol',
 'LY Offtake Actuals Lag 1 Vol',
 'LY Offtake Actuals Lag 2 Vol',
 'LY Offtake Actuals Lag 3 Vol',
 'LY Offtake Actuals Lead 1 Vol',
 'LY Offtake Actuals Lead 2 Vol',
 'Calculated Primary Vol']

In [ ]:
for col in vol_to_val_cols:
    final_df[col[:-3] + 'Val'] = final_df[col].fillna(0) * final_df['Index Rate'] / (10 ** 7)

In [ ]:
final_df

,Key,Chain,PSKU,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,Primary Till Date Actuals Vol,...,LY Offtake P3M Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,LY Offtake Actuals Lag 1 Val,LY Offtake Actuals Lag 2 Val,LY Offtake Actuals Lag 3 Val,LY Offtake Actuals Lead 1 Val,LY Offtake Actuals Lead 2 Val,Calculated Primary Val
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-07-31,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-08-31,M,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-09-30,M+1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-10-31,M+2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-11-30,M+3,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2026-12-31,M+4,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-01-31,M+5,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-02-28,M+6,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-03-31,M+7,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-04-30,M+8,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
final_df.duplicated(subset=['Run Month', 'Key', 'Month Date']).sum()

0

In [ ]:
final_df['Calculated Primary Vol'].sum()

3712488.165752257

### Depot PSKU

#### Aggregate to PSKU first

In [ ]:
psku_df = final_df.groupby(
    ['PSKU', 'Brand', 'Portfolio', 'Run Month', 'Month Date'],
    as_index=False
)['Calculated Primary Vol'].sum()

In [ ]:
psku_df = psku_df[psku_df['Month Date'] >= psku_df['Run Month']]

In [ ]:
psku_df

,PSKU,Brand,Portfolio,Run Month,Month Date,Calculated Primary Vol
1,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-08-31,0.0
2,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-09-30,0.0
3,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-10-31,0.0
4,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-11-30,0.0
5,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-12-31,0.0
...,...,...,...,...,...,...
9795,811564,SAF-MUSLI,FOODS,2026-08-31,2026-12-31,0.0
9796,811564,SAF-MUSLI,FOODS,2026-08-31,2027-01-31,0.0
9797,811564,SAF-MUSLI,FOODS,2026-08-31,2027-02-28,0.0
9798,811564,SAF-MUSLI,FOODS,2026-08-31,2027-03-31,0.0
9799,811564,SAF-MUSLI,FOODS,2026-08-31,2027-04-30,0.0

In [ ]:
psku_df['Calculated Primary Vol'].sum()

3712488.1657522568

In [ ]:
others_df = others_df.groupby(
    ['parent_material_code', 'material_group_code', 'month_date'], as_index=False
)['Primary P3M'].sum()

len_before_merge = len(others_df)
others_df = others_df.merge(
    brand_md_df.rename(
        columns={'brand_code': 'material_group_code'}
    ),
    on='material_group_code',
    how='left'
)
assert len_before_merge == len(others_df)
del len_before_merge

others_df = others_df.rename(columns={
    'parent_material_code': 'PSKU',
    'material_group_code': 'Brand',
    'month_date': 'Month Date',
    'Primary P3M': 'Calculated Primary Vol',
    'portfolio': 'Portfolio'
})

In [ ]:
others_df['Calculated Primary Vol'].sum()

1358123.369500002

In [ ]:
psku_df['Calculated Primary Vol'].min()

0.0

In [ ]:
final_others_forecast = pd.DataFrame()

for rm in psku_df['Run Month'].unique():
    tmp = others_df.copy()
    tmp['Run Month'] = rm
    tmp = tmp[tmp['Month Date'] <= psku_df[psku_df['Run Month'] == rm]['Month Date'].max()]
    tmp = tmp[tmp['Month Date'] >= rm]
    final_others_forecast = pd.concat([final_others_forecast, tmp], ignore_index=True)
    del tmp

In [ ]:
psku_df = pd.concat(
    [psku_df, final_others_forecast], ignore_index=True
)

In [ ]:
psku_df = psku_df.groupby(
    ['PSKU', 'Brand', 'Portfolio', 'Run Month', 'Month Date'],
    as_index=False
)['Calculated Primary Vol'].sum()

In [ ]:
psku_df['Calculated Primary Vol'].sum()

3735737.1894189236

In [ ]:
depot_psku_primary_query = """
SELECT
    CM.depot_code,
    MM.parent_material_code,
    MM.material_group_code,
    LAST_DAY(MESR.month_date) AS month_date,
    SUM(pri_actuals_vol_rum) AS pri_actuals_vol_rum,
    SUM(pri_apo_plan_vol_rum) AS pri_apo_plan_vol_rum,
    SUM(MESR.sec_apo_plan_vol_rum) AS sec_apo_plan_vol_rum,
    SUM(MESR.sec_actuals_vol_rum) AS sec_actuals_vol_rum
FROM
    dwh_bpm_dist_sku_daily MESR
JOIN 
(
    SELECT
        customer,
        chain_type,
        chain
    FROM
        mst_chain_master
    WHERE
        chain_type = 'E Com B2C' AND 
        chain IN ('Flipkart-National', 'Flipkart-Grocery', 'Big basket B2C', 'RK WORLDINFOCOM', 'Amazon B2C', 
        'FATEHPURIA HYGIENE', 'Nykaa', 'Flipkart-Minutes', 'Purplle', 'Myntra', 'Dealshare', 'FlipkartGrocery', 'City Mall', '1MG', 
        'ARIPL', 'First Cry', 'Meesho', 'RKWorld', 'CITIMALL', 'Firstcry', 'EMAZING DEALS', 'MYNTRA')
) MCM ON MESR.distributor_code = MCM.customer
JOIN
(
    SELECT
        material_code,
        parent_material_code,
        material_group_code,
        uom_reporting,
        vol_per_unit
    FROM 
        mst_material
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) MM ON MESR.material_code = MM.material_code
JOIN
(
    SELECT DISTINCT
        customer_code,
        depot_code
    FROM
        mst_customer
    WHERE
        company_code='MIL' AND
        latest_record_ind=1
) CM on MESR.distributor_code = CM.customer_code
GROUP BY 1, 2, 3, 4
ORDER BY 1, 3, 2, 4
"""

depot_psku_primary_df = pd.read_sql(
    depot_psku_primary_query,
    prod_conn
)

In [ ]:
depot_psku_primary_df

,DEPOT_CODE,PARENT_MATERIAL_CODE,MATERIAL_GROUP_CODE,MONTH_DATE,PRI_ACTUALS_VOL_RUM,PRI_APO_PLAN_VOL_RUM,SEC_APO_PLAN_VOL_RUM,SEC_ACTUALS_VOL_RUM
0,D111,718471,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
1,D111,718471,ADV-AHO-R,2017-07-31,0.0,0.000000,NaN,0.0
2,D111,718472,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
3,D111,718472,ADV-AHO-R,2017-07-31,0.0,0.000000,NaN,0.0
4,D111,718473,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
...,...,...,...,...,...,...,...,...
342387,D677,810179,SW_SGPRF,2026-06-30,0.0,21.831578,0.0,0.0
342388,D677,810179,SW_SGPRF,2026-07-31,0.0,7.823442,0.0,0.0
342389,D677,810179,SW_SGPRF,2026-08-31,0.0,20.021340,0.0,0.0
342390,D677,811169,SW_SGPRF,2026-03-31,0.0,9.818184,0.0,0.0
342391,D677,811169,SW_SGPRF,2026-04-30,0.0,0.210208,0.0,0.0

In [ ]:
depot_psku_primary_df.columns = depot_psku_primary_df.columns.str.lower()
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)

In [ ]:
depot_psku_primary_df = realign_pskus(depot_psku_primary_df.copy(), 'parent_material_code')

In [ ]:
depot_psku_primary_df

,depot_code,parent_material_code,material_group_code,month_date,pri_actuals_vol_rum,pri_apo_plan_vol_rum,sec_apo_plan_vol_rum,sec_actuals_vol_rum
0,D111,718471,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
1,D111,718471,ADV-AHO-R,2017-07-31,0.0,0.000000,NaN,0.0
2,D111,718472,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
3,D111,718472,ADV-AHO-R,2017-07-31,0.0,0.000000,NaN,0.0
4,D111,718473,ADV-AHO-R,2017-04-30,0.0,0.000000,NaN,0.0
...,...,...,...,...,...,...,...,...
342387,D677,810179,SW_SGPRF,2026-06-30,0.0,21.831578,0.0,0.0
342388,D677,810179,SW_SGPRF,2026-07-31,0.0,7.823442,0.0,0.0
342389,D677,810179,SW_SGPRF,2026-08-31,0.0,20.021340,0.0,0.0
342390,D677,811169,SW_SGPRF,2026-03-31,0.0,9.818184,0.0,0.0
342391,D677,811169,SW_SGPRF,2026-04-30,0.0,0.210208,0.0,0.0

In [ ]:
material_master_df = pd.read_sql(
    """select * from mst_material 
    where latest_record_ind=1 and company_code='MIL'""",
    prod_conn
)
material_master_df.columns = material_master_df.columns.str.lower()
assert material_master_df.duplicated(
    subset=['company_code', 'material_code']).sum() == 0

material_master_df['material_code'] = material_master_df['material_code'].astype(np.int64)
material_master_df.duplicated(subset=['material_code', 'parent_material_code', 'material_group_code']).sum()

0

In [ ]:
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['depot_code', 'parent_material_code', 'month_date'],
    as_index=False
)[['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum',
       'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']].sum()

# material_master_df[['parent_material_code', 'brand_code']].dtypes
material_master_df['parent_material_code'] = material_master_df['parent_material_code'].astype(int)
material_master_df.loc[material_master_df['parent_material_code'].isin([725930,731857]), 'material_group_code'] = 'H&C_ALMND'

# offtake_df.drop(columns = ['brand_code'],inplace = True)
len_before_merge = len(depot_psku_primary_df)
depot_psku_primary_df = depot_psku_primary_df.merge(
    material_master_df[['parent_material_code', 'material_group_code']].drop_duplicates(),
    left_on=['parent_material_code'],right_on = ['parent_material_code'],
    how='left'
)
assert len_before_merge == len(depot_psku_primary_df)

In [ ]:
depot_psku_primary_df = depot_psku_primary_df.groupby(
    ['depot_code', 'parent_material_code', 'material_group_code', 'month_date'], as_index=False, dropna=False
).sum()

In [ ]:
depot_psku_primary_df = depot_psku_primary_df[depot_psku_primary_df['parent_material_code'] != 715096]

In [ ]:
depot_psku_primary_df.duplicated(subset=['depot_code', 'parent_material_code', 'month_date']).sum()

0

In [ ]:
depot_psku_primary_df.shape

(335113, 8)

In [ ]:
# # For duplicates, keep only the row with PABABY_ML material_group_code
# duplicates = depot_psku_primary_df[depot_psku_primary_df.duplicated(subset=['depot_code', 'parent_material_code', 'month_date'], keep=False)]

# # Get indices of duplicates that are NOT PABABY_ML
# indices_to_drop = duplicates[duplicates['material_group_code'] != 'PABABY_ML'].index

# # Remove those rows
# depot_psku_primary_df = depot_psku_primary_df.drop(indices_to_drop)

# # Verify no duplicates remain
# print(depot_psku_primary_df.duplicated(subset=['depot_code', 'parent_material_code', 'month_date']).sum())

In [ ]:
depot_psku_primary_df.shape

(335113, 8)

In [ ]:
depot_psku_primary_df = impute_missing_dates(
    depot_psku_primary_df.copy(),
    key=['depot_code', 'parent_material_code'],
    date_col='month_date'
)

19004it [00:04, 4035.61it/s]

In [ ]:
cols = ['depot_code', 'parent_material_code', 'material_group_code']

depot_psku_primary_df[cols] = depot_psku_primary_df.groupby('key')[cols].transform(lambda x: x.ffill().bfill())

In [ ]:
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].fillna(0)

In [ ]:
depot_psku_primary_df['parent_material_code'] = depot_psku_primary_df['parent_material_code'].astype(int)

In [ ]:
depot_psku_primary_df.duplicated(subset=['key', 'month_date']).sum()

0

In [ ]:
for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    if depot_psku_primary_df[col].min() < 0:
        print(col)

for col in ['pri_actuals_vol_rum', 'pri_apo_plan_vol_rum', 'sec_apo_plan_vol_rum', 'sec_actuals_vol_rum']:
    depot_psku_primary_df[col] = depot_psku_primary_df[col].clip(lower=0)

pri_actuals_vol_rum
sec_actuals_vol_rum

In [ ]:
depot_psku_primary_df.sort_values(by=['key', 'month_date'], inplace=True)

In [ ]:
depot_psku_primary_df['Primary P3M Vol'] = depot_psku_primary_df.groupby(
    ['key'], 
    as_index = False, group_keys = False
)['pri_actuals_vol_rum'].shift(1).rolling(window=3, min_periods=1).mean()

In [ ]:
depot_psku_primary_df['Primary Actuals Lag 1 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(1)

depot_psku_primary_df['Primary Actuals Lag 2 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(2)

depot_psku_primary_df['Primary Actuals Lag 3 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(3)

depot_psku_primary_df['LY Primary Actuals Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(12)

depot_psku_primary_df['LY Primary Actuals Lag 1 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(13)

depot_psku_primary_df['LY Primary Actuals Lag 2 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(14)

depot_psku_primary_df['LY Primary Actuals Lag 3 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(15)


depot_psku_primary_df['LY Primary Actuals Lead 1 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(11)

depot_psku_primary_df['LY Primary Actuals Lead 2 Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['pri_actuals_vol_rum'].shift(10)

In [ ]:
depot_psku_primary_df['LY Primary P3M Vol'] = depot_psku_primary_df.groupby(
    ['key']
)['Primary P3M Vol'].shift(12)

In [ ]:
depot_psku_primary_df = depot_psku_primary_df.rename(columns={
    'key': 'Key',
    'depot_code': 'Depot',
    'parent_material_code': 'PSKU',
    'material_group_code': 'Brand',
    'month_date': 'Month Date',
    'pri_actuals_vol_rum': 'Primary Actuals Vol',
    'pri_apo_plan_vol_rum': 'Primary Plan Vol',
    'sec_actuals_vol_rum': 'Secondary Actuals Vol',
    'sec_apo_plan_vol_rum': 'Secondary Plan Vol'
})

In [ ]:
depot_psku_primary_df

,Month Date,Key,Depot,PSKU,Brand,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,Secondary Actuals Vol,Primary P3M Vol,Primary Actuals Lag 1 Vol,Primary Actuals Lag 2 Vol,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol
0,2017-04-30,D111_709567,D111,709567,SAFF OATS,0.0,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-05-31,D111_709567,D111,709567,SAFF OATS,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-06-30,D111_709567,D111,709567,SAFF OATS,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-07-31,D111_709567,D111,709567,SAFF OATS,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-31,D111_709567,D111,709567,SAFF OATS,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961897,2026-08-31,D677_811564,D677,811564,SAF-MUSLI,0.0,0.0808,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961898,2026-09-30,D677_811564,D677,811564,SAF-MUSLI,0.0,0.0000,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961899,2026-10-31,D677_811564,D677,811564,SAF-MUSLI,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961900,2026-11-30,D677_811564,D677,811564,SAF-MUSLI,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
961901,2026-12-31,D677_811564,D677,811564,SAF-MUSLI,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_depot_psku_df = depot_psku_primary_df[['Key', 'Depot', 'PSKU', 'Brand']].drop_duplicates()

In [ ]:
psku_df['Calculated Primary Vol'].sum()

3735737.1894189236

In [ ]:
x = psku_df.copy()

In [ ]:
# # For duplicates, keep only the row with PABABY_ML material_group_code
# duplicates = psku_df[psku_df.duplicated(subset=['PSKU','Run Month', 'Month Date'], keep=False)]

# # Get indices of duplicates that are NOT PABABY_ML
# indices_to_drop = duplicates[duplicates['Brand'] != 'PABABY_ML'].index

# # Remove those rows
# psku_df = psku_df.drop(indices_to_drop)

# # Verify no duplicates remain
# print(psku_df.duplicated(subset=['PSKU','Run Month', 'Month Date']).sum())

In [ ]:
psku_df['Calculated Primary Vol'].sum()

3735737.1894189236

In [ ]:
tmp_df = pd.DataFrame()

for rm in ['2026-09-30']: 
    mth_dates = [pd.to_datetime(rm) + MonthEnd(i) for i in range(-1, 9)]
    for mth_dt in mth_dates:
        tmp_df2 = final_depot_psku_df.copy()
        tmp_df2['Run Month'] = pd.to_datetime(rm)
        tmp_df2['Month Date'] = pd.to_datetime(mth_dt)

        tmp_df = pd.concat([tmp_df, tmp_df2], ignore_index=True)
        del tmp_df2

final_depot_psku_df = tmp_df.copy()    
del tmp_df

In [ ]:
psku_df

,PSKU,Brand,Portfolio,Run Month,Month Date,Calculated Primary Vol
0,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-08-31,0.0
1,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-09-30,0.0
2,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-10-31,0.0
3,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-11-30,0.0
4,715098,CO_SO_PCP,SKIN CARE,2026-08-31,2026-12-31,0.0
...,...,...,...,...,...,...
8840,811564,SAF-MUSLI,FOODS,2026-08-31,2026-12-31,0.0
8841,811564,SAF-MUSLI,FOODS,2026-08-31,2027-01-31,0.0
8842,811564,SAF-MUSLI,FOODS,2026-08-31,2027-02-28,0.0
8843,811564,SAF-MUSLI,FOODS,2026-08-31,2027-03-31,0.0
8844,811564,SAF-MUSLI,FOODS,2026-08-31,2027-04-30,0.0

In [ ]:
len_before_merge = len(final_depot_psku_df)
final_depot_psku_df = final_depot_psku_df.merge(
    psku_df[['PSKU', 'Run Month', 'Month Date', 'Calculated Primary Vol']], 
    on=['PSKU', 'Run Month', 'Month Date'],
    how='left'
)
assert len_before_merge == len(final_depot_psku_df)
del len_before_merge

In [ ]:
final_depot_psku_df['Calculated Primary Vol'].sum()

86256847.24094369

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN
1,D111_710981,D111,710981,PA_MEN_AH,2026-08-31,2026-07-31,NaN
2,D111_711040,D111,711040,PCNO GOLD,2026-08-31,2026-07-31,NaN
3,D111_711041,D111,711041,PCNO GOLD,2026-08-31,2026-07-31,NaN
4,D111_711042,D111,711042,PCNO GOLD,2026-08-31,2026-07-31,NaN
...,...,...,...,...,...,...,...
190035,D677_811269,D677,811269,PA_ESS_HO,2026-08-31,2027-04-30,0.000000
190036,D677_811279,D677,811279,SAF_CDPRS,2026-08-31,2027-04-30,0.000000
190037,D677_811287,D677,811287,PA_RSW_SR,2026-08-31,2027-04-30,96.157549
190038,D677_811416,D677,811416,SAF-MUSLI,2026-08-31,2027-04-30,0.000000
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.000000

In [ ]:
# x = final_depot_psku_df.groupby(['PSKU','Month Date'])['Calculated Primary Vol'].mean().reset_index()
# x[x['Month Date']>'2026-06-30']['Calculated Primary Vol'].sum()

In [ ]:
depot_psku_primary_df.columns

Index(['Month Date', 'Key', 'Depot', 'PSKU', 'Brand', 'Primary Actuals Vol',
       'Primary Plan Vol', 'Secondary Plan Vol', 'Secondary Actuals Vol',
       'Primary P3M Vol', 'Primary Actuals Lag 1 Vol',
       'Primary Actuals Lag 2 Vol', 'Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Vol', 'LY Primary Actuals Lag 1 Vol',
       'LY Primary Actuals Lag 2 Vol', 'LY Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Lead 1 Vol', 'LY Primary Actuals Lead 2 Vol',
       'LY Primary P3M Vol'],
      dtype='object')

In [ ]:
len_before_merge = len(final_depot_psku_df)
final_depot_psku_df = final_depot_psku_df.merge(
    depot_psku_primary_df[['Depot', 'PSKU', 'Month Date', 'Primary Actuals Vol',
       'Primary Plan Vol', 'Secondary Plan Vol', 'Secondary Actuals Vol',
       'Primary P3M Vol', 'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Vol',  'LY Primary Actuals Lag 1 Vol',
       'LY Primary Actuals Lag 2 Vol', 'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol', 
       'LY Primary Actuals Lead 2 Vol',
       'LY Primary P3M Vol']], 
    on=['Depot', 'PSKU', 'Month Date'],
    how='left'
)
assert len_before_merge == len(final_depot_psku_df)
del len_before_merge

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 1 Vol,Primary Actuals Lag 2 Vol,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,D111_710981,D111,710981,PA_MEN_AH,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,D111_711040,D111,711040,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,D111_711041,D111,711041,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,D111_711042,D111,711042,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190035,D677_811269,D677,811269,PA_ESS_HO,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190036,D677_811279,D677,811279,SAF_CDPRS,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190037,D677_811287,D677,811287,PA_RSW_SR,2026-08-31,2027-04-30,96.157549,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190038,D677_811416,D677,811416,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_depot_psku_df.columns

Index(['Key', 'Depot', 'PSKU', 'Brand', 'Run Month', 'Month Date',
       'Calculated Primary Vol', 'Primary Actuals Vol', 'Primary Plan Vol',
       'Secondary Plan Vol', 'Secondary Actuals Vol', 'Primary P3M Vol',
       'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Vol',
       'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
       'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
       'LY Primary Actuals Lead 2 Vol', 'LY Primary P3M Vol'],
      dtype='object')

In [ ]:
final_depot_psku_df['Primary P3M copy Vol'] = final_depot_psku_df['Primary P3M Vol'].copy()

In [ ]:
final_depot_psku_df['Primary P3M Vol'] = final_depot_psku_df['Primary P3M Vol'].fillna(0)

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 2 Vol,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol,Primary P3M copy Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,D111_710981,D111,710981,PA_MEN_AH,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,D111_711040,D111,711040,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,D111_711041,D111,711041,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,D111_711042,D111,711042,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190035,D677_811269,D677,811269,PA_ESS_HO,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190036,D677_811279,D677,811279,SAF_CDPRS,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190037,D677_811287,D677,811287,PA_RSW_SR,2026-08-31,2027-04-30,96.157549,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190038,D677_811416,D677,811416,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_depot_psku_df['PSKU Primary P3M Sum Vol'] = final_depot_psku_df.groupby(
    ['Run Month', 'Month Date', 'PSKU']
)['Primary P3M Vol'].transform('sum')

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol,Primary P3M copy Vol,PSKU Primary P3M Sum Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,D111_710981,D111,710981,PA_MEN_AH,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,D111_711040,D111,711040,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,D111_711041,D111,711041,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,D111_711042,D111,711042,PCNO GOLD,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190035,D677_811269,D677,811269,PA_ESS_HO,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190036,D677_811279,D677,811279,SAF_CDPRS,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190037,D677_811287,D677,811287,PA_RSW_SR,2026-08-31,2027-04-30,96.157549,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190038,D677_811416,D677,811416,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [ ]:
final_depot_psku_df.sort_values(by=['Run Month', 'Key', 'Month Date'], inplace=True)

In [ ]:
final_depot_psku_df.columns

Index(['Key', 'Depot', 'PSKU', 'Brand', 'Run Month', 'Month Date',
       'Calculated Primary Vol', 'Primary Actuals Vol', 'Primary Plan Vol',
       'Secondary Plan Vol', 'Secondary Actuals Vol', 'Primary P3M Vol',
       'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Vol',
       'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
       'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
       'LY Primary Actuals Lead 2 Vol', 'LY Primary P3M Vol',
       'Primary P3M copy Vol', 'PSKU Primary P3M Sum Vol'],
      dtype='object')

In [ ]:
for col in ['Primary P3M Vol', 'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol', 
            'Primary Actuals Lag 3 Vol', 'PSKU Primary P3M Sum Vol']:
    # if not 'LY' in col:  'LY P6M',
    final_depot_psku_df.loc[final_depot_psku_df['Month Date'] > final_depot_psku_df['Run Month'], [col]] = np.nan
    final_depot_psku_df[col] = final_depot_psku_df.groupby(['Run Month', 'Key'], as_index = True, group_keys = False)[col].apply(
        lambda x: x.ffill()
    )

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol,Primary P3M copy Vol,PSKU Primary P3M Sum Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19004,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-08-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38008,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-09-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57012,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-10-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76016,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-11-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114023,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
133027,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-01-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
152031,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-02-28,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
171035,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-03-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [ ]:
final_depot_psku_df.columns

Index(['Key', 'Depot', 'PSKU', 'Brand', 'Run Month', 'Month Date',
       'Calculated Primary Vol', 'Primary Actuals Vol', 'Primary Plan Vol',
       'Secondary Plan Vol', 'Secondary Actuals Vol', 'Primary P3M Vol',
       'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Vol',
       'LY Primary Actuals Lag 1 Vol', 'LY Primary Actuals Lag 2 Vol',
       'LY Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lead 1 Vol',
       'LY Primary Actuals Lead 2 Vol', 'LY Primary P3M Vol',
       'Primary P3M copy Vol', 'PSKU Primary P3M Sum Vol'],
      dtype='object')

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 3 Vol,LY Primary Actuals Vol,LY Primary Actuals Lag 1 Vol,LY Primary Actuals Lag 2 Vol,LY Primary Actuals Lag 3 Vol,LY Primary Actuals Lead 1 Vol,LY Primary Actuals Lead 2 Vol,LY Primary P3M Vol,Primary P3M copy Vol,PSKU Primary P3M Sum Vol
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19004,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-08-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38008,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-09-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57012,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-10-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
76016,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-11-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114023,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
133027,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-01-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
152031,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-02-28,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
171035,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-03-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [ ]:
final_depot_psku_df['PSKU P3M Contribution'] = final_depot_psku_df['Primary P3M Vol'] / final_depot_psku_df['PSKU Primary P3M Sum Vol']

In [ ]:
final_depot_psku_df['PSKU P3M Contribution'].isnull().sum()

111538

In [ ]:
# x = final_depot_psku_df.groupby(['PSKU','Month Date'])['Calculated Primary Vol'].mean().reset_index()
# x[x['Month Date']>'2026-06-30']['Calculated Primary Vol'].sum()

In [ ]:
final_depot_psku_df['Calculated Depot PSKU Primary Vol'] = final_depot_psku_df['Calculated Primary Vol'] \
    * final_depot_psku_df['PSKU P3M Contribution']

In [ ]:
final_depot_psku_df.rename(columns={'Calculated Primary Vol': 'Calculated PSKU Primary Vol'}, inplace=True)

In [ ]:
final_depot_psku_df['Calculated Depot PSKU Primary Vol'].sum()

3711755.0559739764

In [ ]:
vol_to_val_cols = [col for col in final_depot_psku_df.columns if ('Vol' in col) and ('copy' not in col)]
vol_to_val_cols

['Calculated PSKU Primary Vol',
 'Primary Actuals Vol',
 'Primary Plan Vol',
 'Secondary Plan Vol',
 'Secondary Actuals Vol',
 'Primary P3M Vol',
 'Primary Actuals Lag 1 Vol',
 'Primary Actuals Lag 2 Vol',
 'Primary Actuals Lag 3 Vol',
 'LY Primary Actuals Vol',
 'LY Primary Actuals Lag 1 Vol',
 'LY Primary Actuals Lag 2 Vol',
 'LY Primary Actuals Lag 3 Vol',
 'LY Primary Actuals Lead 1 Vol',
 'LY Primary Actuals Lead 2 Vol',
 'LY Primary P3M Vol',
 'PSKU Primary P3M Sum Vol',
 'Calculated Depot PSKU Primary Vol']

In [ ]:
qtr_ind_rate_df.head()

  month_date brand_code  qtr_ind_rate
0 2027-03-31  CMX_WELPD      3014.000
1 2027-03-31  4700_BCPC       222.000
2 2027-03-31  CMX_PRTPD      3014.000
3 2027-03-31  PA_CN_HGO       488.152
4 2027-03-31  TRU_RAWDF       800.000

In [ ]:
len_before_merge = len(final_depot_psku_df)
final_depot_psku_df = final_depot_psku_df.merge(
    qtr_ind_rate_df.drop('month_date', axis=1).rename(columns={
        'brand_code': 'Brand',
        'qtr_ind_rate': 'Index Rate'
    }),
    on=['Brand'],
    how='left'
)
assert len_before_merge == len(final_depot_psku_df)
del len_before_merge

In [ ]:
for col in vol_to_val_cols:
    final_depot_psku_df[col[:-3] + 'Val'] = final_depot_psku_df[col] * final_depot_psku_df['Index Rate'] / (10 ** 7)

In [ ]:
final_depot_psku_df

,Key,Depot,PSKU,Brand,Run Month,Month Date,Calculated PSKU Primary Vol,Primary Actuals Vol,Primary Plan Vol,Secondary Plan Vol,...,Primary Actuals Lag 3 Val,LY Primary Actuals Val,LY Primary Actuals Lag 1 Val,LY Primary Actuals Lag 2 Val,LY Primary Actuals Lag 3 Val,LY Primary Actuals Lead 1 Val,LY Primary Actuals Lead 2 Val,LY Primary P3M Val,PSKU Primary P3M Sum Val,Calculated Depot PSKU Primary Val
0,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-07-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-08-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-09-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-10-31,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,D111_709567,D111,709567,SAFF OATS,2026-08-31,2026-11-30,NaN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190035,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2026-12-31,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
190036,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-01-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
190037,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-02-28,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
190038,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-03-31,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
190039,D677_811564,D677,811564,SAF-MUSLI,2026-08-31,2027-04-30,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [ ]:
final_depot_psku_df['Calculated Depot PSKU Primary Val'] = final_depot_psku_df['Calculated Depot PSKU Primary Val'].fillna(0)

In [ ]:
final_depot_psku_df['M Month'] = final_depot_psku_df.apply(
    lambda x: mappings[x['Run Month']].get(x['Month Date'], np.nan),
    axis=1
)

In [ ]:
final_depot_psku_df = final_depot_psku_df[final_depot_psku_df['M Month'].notna()]

In [ ]:
final_depot_psku_df.groupby(
    ['Run Month', 'Month Date', 'PSKU']
)['PSKU P3M Contribution'].max().max()

1.0

In [ ]:
final_df.columns

Index(['Key', 'Chain', 'PSKU', 'Brand', 'Index Rate', 'Portfolio', 'Run Month',
       'Month Date', 'M month', 'Primary Till Date Actuals Vol',
       'Secondary Plan Vol', 'Primary P3M Vol', 'Offtake Chain PSKU Vol',
       'Offtake Chain PSKU Forecast Vol', 'Norms SOH', 'Norm Days',
       'Safety Stock Vol', 'Actual Closing SOH Vol',
       'Actual Closing SOH Lag 1 Vol', 'Actual Closing SOH Lag 2 Vol',
       'Assumed Closing SOH Vol', 'Assumed Closing SOH Lag 1 Vol',
       'Final Assumed Closing SOH Vol', 'Final Assumed Closing SOH Lag 1 Vol',
       'Primary Actuals Vol', 'Sec Actuals Vol', 'Primary P3M redundant Vol',
       'LY Primary Actuals Vol', 'LY Sec Actuals Vol', 'LY Primary P3M Vol',
       'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lag 1 Vol',
       'LY Primary Actuals Lag 2 Vol', 'LY Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Lead 1 Vol', 'LY Primary Actuals Lead 2 Vol',
       'Offtake Actuals Vol', 'Offtake P3M Vol', 'LY Offtake Actuals Vol',
       'LY Offtake P3M Vol', 'Offtake Actuals Lag 1 Vol',
       'Offtake Actuals Lag 2 Vol', 'Offtake Actuals Lag 3 Vol',
       'LY Offtake Actuals Lag 1 Vol', 'LY Offtake Actuals Lag 2 Vol',
       'LY Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lead 1 Vol',
       'LY Offtake Actuals Lead 2 Vol', 'Calculated Primary Vol',
       'Primary Till Date Actuals Val', 'Secondary Plan Val',
       'Primary P3M Val', 'Offtake Chain PSKU Val',
       'Offtake Chain PSKU Forecast Val', 'Safety Stock Val',
       'Actual Closing SOH Val', 'Actual Closing SOH Lag 1 Val',
       'Actual Closing SOH Lag 2 Val', 'Assumed Closing SOH Val',
       'Assumed Closing SOH Lag 1 Val', 'Final Assumed Closing SOH Val',
       'Final Assumed Closing SOH Lag 1 Val', 'Primary Actuals Val',
       'Sec Actuals Val', 'Primary P3M redundant Val',
       'LY Primary Actuals Val', 'LY Sec Actuals Val', 'LY Primary P3M Val',
       'Primary Actuals Lag 1 Val', 'Primary Actuals Lag 2 Val',
       'Primary Actuals Lag 3 Val', 'LY Primary Actuals Lag 1 Val',
       'LY Primary Actuals Lag 2 Val', 'LY Primary Actuals Lag 3 Val',
       'LY Primary Actuals Lead 1 Val', 'LY Primary Actuals Lead 2 Val',
       'Offtake Actuals Val', 'Offtake P3M Val', 'LY Offtake Actuals Val',
       'LY Offtake P3M Val', 'Offtake Actuals Lag 1 Val',
       'Offtake Actuals Lag 2 Val', 'Offtake Actuals Lag 3 Val',
       'LY Offtake Actuals Lag 1 Val', 'LY Offtake Actuals Lag 2 Val',
       'LY Offtake Actuals Lag 3 Val', 'LY Offtake Actuals Lead 1 Val',
       'LY Offtake Actuals Lead 2 Val', 'Calculated Primary Val'],
      dtype='object')

In [ ]:
final_df['Calculated Primary Val'].sum(), final_depot_psku_df['Calculated Depot PSKU Primary Val'].sum()

(411.64627575143714, 410.54188559605967)

In [ ]:
final_df[final_df['Month Date']=='2026-09-30']['Calculated Primary Val'].sum()

51.18818563457459

In [ ]:
final_df['Chain'].unique()

array(['Amazon ARIPL', 'Amazon RK', 'Big Basket', 'Flipkart Grocery',
       'Flipkart National', 'Meesho', 'Myntra', 'Nykaa'], dtype=object)

In [ ]:
final_depot_psku_df.isnull().sum()

Key                                       0
Depot                                     0
PSKU                                      0
Brand                                     0
Run Month                                 0
Month Date                                0
Calculated PSKU Primary Vol           28383
Primary Actuals Vol                   76016
Primary Plan Vol                      76016
Secondary Plan Vol                    76016
Secondary Actuals Vol                 76016
Primary P3M Vol                           0
Primary Actuals Lag 1 Vol               423
Primary Actuals Lag 2 Vol              1449
Primary Actuals Lag 3 Vol              2331
LY Primary Actuals Vol                87011
LY Primary Actuals Lag 1 Vol          88341
LY Primary Actuals Lag 2 Vol          89505
LY Primary Actuals Lag 3 Vol          90637
LY Primary Actuals Lead 1 Vol         85819
LY Primary Actuals Lead 2 Vol         84690
LY Primary P3M Vol                    87011
Primary P3M copy Vol                  76016
PSKU Primary P3M Sum Vol                  0
PSKU P3M Contribution                100476
Calculated Depot PSKU Primary Vol    100480
Index Rate                                0
Calculated PSKU Primary Val           28383
Primary Actuals Val                   76016
Primary Plan Val                      76016
Secondary Plan Val                    76016
Secondary Actuals Val                 76016
Primary P3M Val                           0
Primary Actuals Lag 1 Val               423
Primary Actuals Lag 2 Val              1449
Primary Actuals Lag 3 Val              2331
LY Primary Actuals Val                87011
LY Primary Actuals Lag 1 Val          88341
LY Primary Actuals Lag 2 Val          89505
LY Primary Actuals Lag 3 Val          90637
LY Primary Actuals Lead 1 Val         85819
LY Primary Actuals Lead 2 Val         84690
LY Primary P3M Val                    87011
PSKU Primary P3M Sum Val                  0
Calculated Depot PSKU Primary Val         0
M Month                                   0
dtype: int64

In [ ]:
final_df[final_df['Month Date']=='2026-09-30']['Offtake Actuals Lag 1 Val'].sum()

42.49894498911772

In [ ]:
final_df

,Key,Chain,PSKU,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,Primary Till Date Actuals Vol,...,LY Offtake P3M Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,LY Offtake Actuals Lag 1 Val,LY Offtake Actuals Lag 2 Val,LY Offtake Actuals Lag 3 Val,LY Offtake Actuals Lead 1 Val,LY Offtake Actuals Lead 2 Val,Calculated Primary Val
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-07-31,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-08-31,M,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-09-30,M+1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-10-31,M+2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1220.081000,SKIN CARE,2026-08-31,2026-11-30,M+3,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60915,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2026-12-31,M+4,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60916,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-01-31,M+5,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60917,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-02-28,M+6,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60918,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-03-31,M+7,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60919,Nykaa_811564,Nykaa,811564,SAF-MUSLI,315513.490535,FOODS,2026-08-31,2027-04-30,M+8,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
remain = lags_final_offtakes_historical_df[['key', 'month_date', 'offtake_vol_rum', 'OT_Lag_2', 'OT_Lag_3']].rename(
    columns = {
        'month_date': 'run_month',
        'offtake_vol_rum': 'Offtake Actuals Lag 1 Vol',
        'OT_Lag_2': 'Offtake Actuals Lag 2 Vol',
        'OT_Lag_3': 'Offtake Actuals Lag 3 Vol'}
)
remain = remain[remain['run_month'] == '2026-09-30']
remain = remain[~remain['key'].isin(final_df['Key'].unique())]

# Extract parent_material_code from the last 6 digits of the 'key' column
remain['parent_material_code'] = remain['key'].str[-6:]

remain

,key,run_month,Offtake Actuals Lag 1 Vol,Offtake Actuals Lag 2 Vol,Offtake Actuals Lag 3 Vol,parent_material_code
957,Amazon RK_710542,2026-08-31,0.0000,0.0000,0.0000,710542
1096,Amazon RK_718301,2026-08-31,0.0000,0.0000,0.0000,718301
2366,Amazon RK_718458,2026-08-31,0.0000,0.0000,0.0000,718458
2609,Amazon RK_718466,2026-08-31,0.0000,0.0000,0.0000,718466
2815,Amazon RK_718477,2026-08-31,0.0000,0.0000,0.0000,718477
...,...,...,...,...,...,...
138829,Purplle_807725,2026-08-31,0.0000,0.0000,0.0000,807725
138852,Purplle_809042,2026-08-31,0.0000,0.0000,0.0000,809042
138887,Purplle_809250,2026-08-31,0.0005,0.0014,0.0009,809250
138903,Purplle_810673,2026-08-31,0.1680,0.0560,0.0980,810673
138919,Purplle_810674,2026-08-31,0.0140,0.0000,0.0000,810674

In [ ]:
material_master_df.rename(columns={'material_group_code': 'brand_code'}, inplace=True)
remain['parent_material_code'] = remain['parent_material_code'].astype(int)

In [ ]:
len_before_merge = len(remain)
remain = remain.merge(
    material_master_df[['parent_material_code', 'brand_code']].drop_duplicates(),
    left_on=['parent_material_code'],right_on = ['parent_material_code'],
    how='left'
)
assert len_before_merge == len(remain)

def read_qtr_ind_rate_table():
    """
    Fetch the club sku information from  DWH_SAP_INDEX_TURNOVER_MONTHWISE table.

    Return:
        qtr_ind_rate_data: pandas dataframe
        - dataframe contains all the results from the index rate table.
    """
    connection = get_dbconnection(db_name='PROD')
    query = """select * from DWH_SAP_INDEX_TURNOVER_MONTHWISE 
                where latest_rate_flag=1 and company_code='MIL'"""
    qtr_ind_rate_data = pd.read_sql(con=connection, sql=query)
    qtr_ind_rate_data.columns = qtr_ind_rate_data.columns.str.lower()
    qtr_ind_rate =  qtr_ind_rate_data[['date', 'brand_code', 'turnover']]
    qtr_ind_rate = qtr_ind_rate.rename(columns= {'date':'month_date', 'turnover':'qtr_ind_rate'})
    connection.close()
    return qtr_ind_rate


qtr_df = read_qtr_ind_rate_table()
qtr_df.columns = qtr_df.columns.str.lower()
qtr_df.head()


len_before_merge = len(remain)

remain = remain.rename(columns={'material_group_code': 'brand_code'}).merge(
    qtr_df.drop('month_date', axis=1),
    on=['brand_code'],
    how='left'
)

assert len_before_merge == len(remain)

Credentials retrieved successfully for prod db.

In [ ]:
remain['Offtake Actuals Lag 1 Val'] = remain['Offtake Actuals Lag 1 Vol'] * remain['qtr_ind_rate'] / (10 ** 7)
remain['Offtake Actuals Lag 2 Val'] = remain['Offtake Actuals Lag 2 Vol'] * remain['qtr_ind_rate'] / (10 ** 7)
remain['Offtake Actuals Lag 3 Val'] = remain['Offtake Actuals Lag 3 Vol'] * remain['qtr_ind_rate'] / (10 ** 7)
remain

,key,run_month,Offtake Actuals Lag 1 Vol,Offtake Actuals Lag 2 Vol,Offtake Actuals Lag 3 Vol,parent_material_code,brand_code,qtr_ind_rate,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val
0,Amazon RK_710542,2026-08-31,0.0000,0.0000,0.0000,710542,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000
1,Amazon RK_718301,2026-08-31,0.0000,0.0000,0.0000,718301,PCNO FLEX,2.300000e+05,0.000000,0.000000,0.000000
2,Amazon RK_718458,2026-08-31,0.0000,0.0000,0.0000,718458,NHR-SABDM,1.884937e+02,0.000000,0.000000,0.000000
3,Amazon RK_718466,2026-08-31,0.0000,0.0000,0.0000,718466,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000
4,Amazon RK_718477,2026-08-31,0.0000,0.0000,0.0000,718477,NHR-UTTAM,2.500000e+05,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
524,Purplle_807725,2026-08-31,0.0000,0.0000,0.0000,807725,BIO OILS,3.790534e+03,0.000000,0.000000,0.000000
525,Purplle_809042,2026-08-31,0.0000,0.0000,0.0000,809042,PABABY_GM,3.664850e+02,0.000000,0.000000,0.000000
526,Purplle_809250,2026-08-31,0.0005,0.0014,0.0009,809250,LVNPST_ML,2.892133e+06,0.000145,0.000405,0.000260
527,Purplle_810673,2026-08-31,0.1680,0.0560,0.0980,810673,PA_ESS_HO,1.286063e+04,0.000216,0.000072,0.000126
528,Purplle_810674,2026-08-31,0.0140,0.0000,0.0000,810674,PA_ESS_HO,1.286063e+04,0.000018,0.000000,0.000000

In [ ]:
remain = remain.rename(columns={
    'key': 'Key',
    'run_month': 'Run Month',
    'parent_material_code': 'PSKU',
    'brand_code': 'Brand',
    'qtr_ind_rate': 'Index Rate'
})

remain

,Key,Run Month,Offtake Actuals Lag 1 Vol,Offtake Actuals Lag 2 Vol,Offtake Actuals Lag 3 Vol,PSKU,Brand,Index Rate,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val
0,Amazon RK_710542,2026-08-31,0.0000,0.0000,0.0000,710542,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000
1,Amazon RK_718301,2026-08-31,0.0000,0.0000,0.0000,718301,PCNO FLEX,2.300000e+05,0.000000,0.000000,0.000000
2,Amazon RK_718458,2026-08-31,0.0000,0.0000,0.0000,718458,NHR-SABDM,1.884937e+02,0.000000,0.000000,0.000000
3,Amazon RK_718466,2026-08-31,0.0000,0.0000,0.0000,718466,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000
4,Amazon RK_718477,2026-08-31,0.0000,0.0000,0.0000,718477,NHR-UTTAM,2.500000e+05,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
524,Purplle_807725,2026-08-31,0.0000,0.0000,0.0000,807725,BIO OILS,3.790534e+03,0.000000,0.000000,0.000000
525,Purplle_809042,2026-08-31,0.0000,0.0000,0.0000,809042,PABABY_GM,3.664850e+02,0.000000,0.000000,0.000000
526,Purplle_809250,2026-08-31,0.0005,0.0014,0.0009,809250,LVNPST_ML,2.892133e+06,0.000145,0.000405,0.000260
527,Purplle_810673,2026-08-31,0.1680,0.0560,0.0980,810673,PA_ESS_HO,1.286063e+04,0.000216,0.000072,0.000126
528,Purplle_810674,2026-08-31,0.0140,0.0000,0.0000,810674,PA_ESS_HO,1.286063e+04,0.000018,0.000000,0.000000

In [ ]:
final_df.columns

Index(['Key', 'Chain', 'PSKU', 'Brand', 'Index Rate', 'Portfolio', 'Run Month',
       'Month Date', 'M month', 'Primary Till Date Actuals Vol',
       'Secondary Plan Vol', 'Primary P3M Vol', 'Offtake Chain PSKU Vol',
       'Offtake Chain PSKU Forecast Vol', 'Norms SOH', 'Norm Days',
       'Safety Stock Vol', 'Actual Closing SOH Vol',
       'Actual Closing SOH Lag 1 Vol', 'Actual Closing SOH Lag 2 Vol',
       'Assumed Closing SOH Vol', 'Assumed Closing SOH Lag 1 Vol',
       'Final Assumed Closing SOH Vol', 'Final Assumed Closing SOH Lag 1 Vol',
       'Primary Actuals Vol', 'Sec Actuals Vol', 'Primary P3M redundant Vol',
       'LY Primary Actuals Vol', 'LY Sec Actuals Vol', 'LY Primary P3M Vol',
       'Primary Actuals Lag 1 Vol', 'Primary Actuals Lag 2 Vol',
       'Primary Actuals Lag 3 Vol', 'LY Primary Actuals Lag 1 Vol',
       'LY Primary Actuals Lag 2 Vol', 'LY Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Lead 1 Vol', 'LY Primary Actuals Lead 2 Vol',
       'Offtake Actuals Vol', 'Offtake P3M Vol', 'LY Offtake Actuals Vol',
       'LY Offtake P3M Vol', 'Offtake Actuals Lag 1 Vol',
       'Offtake Actuals Lag 2 Vol', 'Offtake Actuals Lag 3 Vol',
       'LY Offtake Actuals Lag 1 Vol', 'LY Offtake Actuals Lag 2 Vol',
       'LY Offtake Actuals Lag 3 Vol', 'LY Offtake Actuals Lead 1 Vol',
       'LY Offtake Actuals Lead 2 Vol', 'Calculated Primary Vol',
       'Primary Till Date Actuals Val', 'Secondary Plan Val',
       'Primary P3M Val', 'Offtake Chain PSKU Val',
       'Offtake Chain PSKU Forecast Val', 'Safety Stock Val',
       'Actual Closing SOH Val', 'Actual Closing SOH Lag 1 Val',
       'Actual Closing SOH Lag 2 Val', 'Assumed Closing SOH Val',
       'Assumed Closing SOH Lag 1 Val', 'Final Assumed Closing SOH Val',
       'Final Assumed Closing SOH Lag 1 Val', 'Primary Actuals Val',
       'Sec Actuals Val', 'Primary P3M redundant Val',
       'LY Primary Actuals Val', 'LY Sec Actuals Val', 'LY Primary P3M Val',
       'Primary Actuals Lag 1 Val', 'Primary Actuals Lag 2 Val',
       'Primary Actuals Lag 3 Val', 'LY Primary Actuals Lag 1 Val',
       'LY Primary Actuals Lag 2 Val', 'LY Primary Actuals Lag 3 Val',
       'LY Primary Actuals Lead 1 Val', 'LY Primary Actuals Lead 2 Val',
       'Offtake Actuals Val', 'Offtake P3M Val', 'LY Offtake Actuals Val',
       'LY Offtake P3M Val', 'Offtake Actuals Lag 1 Val',
       'Offtake Actuals Lag 2 Val', 'Offtake Actuals Lag 3 Val',
       'LY Offtake Actuals Lag 1 Val', 'LY Offtake Actuals Lag 2 Val',
       'LY Offtake Actuals Lag 3 Val', 'LY Offtake Actuals Lead 1 Val',
       'LY Offtake Actuals Lead 2 Val', 'Calculated Primary Val'],
      dtype='object')

In [ ]:
remain = remain.merge(
    brand_md_df.rename(
        columns={'brand_code': 'Brand'}
    ),
    on='Brand',
    how='left'
)
remain

,Key,Run Month,Offtake Actuals Lag 1 Vol,Offtake Actuals Lag 2 Vol,Offtake Actuals Lag 3 Vol,PSKU,Brand,Index Rate,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,portfolio
0,Amazon RK_710542,2026-08-31,0.0000,0.0000,0.0000,710542,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000,CNO
1,Amazon RK_718301,2026-08-31,0.0000,0.0000,0.0000,718301,PCNO FLEX,2.300000e+05,0.000000,0.000000,0.000000,CNO
2,Amazon RK_718458,2026-08-31,0.0000,0.0000,0.0000,718458,NHR-SABDM,1.884937e+02,0.000000,0.000000,0.000000,HAIR OILS
3,Amazon RK_718466,2026-08-31,0.0000,0.0000,0.0000,718466,PCNO(R),3.492740e+05,0.000000,0.000000,0.000000,CNO
4,Amazon RK_718477,2026-08-31,0.0000,0.0000,0.0000,718477,NHR-UTTAM,2.500000e+05,0.000000,0.000000,0.000000,CNO
...,...,...,...,...,...,...,...,...,...,...,...,...
524,Purplle_807725,2026-08-31,0.0000,0.0000,0.0000,807725,BIO OILS,3.790534e+03,0.000000,0.000000,0.000000,SKIN CARE
525,Purplle_809042,2026-08-31,0.0000,0.0000,0.0000,809042,PABABY_GM,3.664850e+02,0.000000,0.000000,0.000000,SKIN CARE
526,Purplle_809250,2026-08-31,0.0005,0.0014,0.0009,809250,LVNPST_ML,2.892133e+06,0.000145,0.000405,0.000260,PREM. HAIR NOUR.
527,Purplle_810673,2026-08-31,0.1680,0.0560,0.0980,810673,PA_ESS_HO,1.286063e+04,0.000216,0.000072,0.000126,HAIR OILS
528,Purplle_810674,2026-08-31,0.0140,0.0000,0.0000,810674,PA_ESS_HO,1.286063e+04,0.000018,0.000000,0.000000,HAIR OILS

In [ ]:
remain['Chain'] = remain['Key'].apply(lambda x: x.split('_')[0])
remain.rename(columns={'portfolio': 'Portfolio'}, inplace=True)
remain['Month Date'] = remain['Run Month'] + MonthEnd(1)

In [ ]:
cccc = final_df.copy()
final_df.shape

(60920, 91)

In [ ]:
# final_df = cccc.copy()

In [ ]:
final_df = pd.concat([final_df, remain], ignore_index=True)
final_df

,Key,Chain,PSKU,Brand,Index Rate,Portfolio,Run Month,Month Date,M month,Primary Till Date Actuals Vol,...,LY Offtake P3M Val,Offtake Actuals Lag 1 Val,Offtake Actuals Lag 2 Val,Offtake Actuals Lag 3 Val,LY Offtake Actuals Lag 1 Val,LY Offtake Actuals Lag 2 Val,LY Offtake Actuals Lag 3 Val,LY Offtake Actuals Lead 1 Val,LY Offtake Actuals Lead 2 Val,Calculated Primary Val
0,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-07-31,NaN,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-08-31,M,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-09-30,M+1,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-10-31,M+2,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,Amazon ARIPL_715098,Amazon ARIPL,715098,CO_SO_PCP,1.220081e+03,SKIN CARE,2026-08-31,2026-11-30,M+3,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61444,Purplle_807725,Purplle,807725,BIO OILS,3.790534e+03,SKIN CARE,2026-08-31,2026-09-30,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
61445,Purplle_809042,Purplle,809042,PABABY_GM,3.664850e+02,SKIN CARE,2026-08-31,2026-09-30,NaN,NaN,...,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
61446,Purplle_809250,Purplle,809250,LVNPST_ML,2.892133e+06,PREM. HAIR NOUR.,2026-08-31,2026-09-30,NaN,NaN,...,NaN,0.000145,0.000405,0.000260,NaN,NaN,NaN,NaN,NaN,NaN
61447,Purplle_810673,Purplle,810673,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,NaN,NaN,...,NaN,0.000216,0.000072,0.000126,NaN,NaN,NaN,NaN,NaN,NaN
61448,Purplle_810674,Purplle,810674,PA_ESS_HO,1.286063e+04,HAIR OILS,2026-08-31,2026-09-30,NaN,NaN,...,NaN,0.000018,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_df['Chain'].unique()

array(['Amazon ARIPL', 'Amazon RK', 'Big Basket', 'Flipkart Grocery',
       'Flipkart National', 'Meesho', 'Myntra', 'Nykaa', 'Purplle'],
      dtype=object)

In [ ]:
final_depot_psku_df[final_depot_psku_df['Month Date']=='2026-09-30']['LY Primary Actuals Val'].sum()

43.479482483713

In [ ]:
final_depot_psku_df.columns

Index(['Key', 'Depot', 'PSKU', 'Brand', 'Run Month', 'Month Date',
       'Calculated PSKU Primary Vol', 'Primary Actuals Vol',
       'Primary Plan Vol', 'Secondary Plan Vol', 'Secondary Actuals Vol',
       'Primary P3M Vol', 'Primary Actuals Lag 1 Vol',
       'Primary Actuals Lag 2 Vol', 'Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Vol', 'LY Primary Actuals Lag 1 Vol',
       'LY Primary Actuals Lag 2 Vol', 'LY Primary Actuals Lag 3 Vol',
       'LY Primary Actuals Lead 1 Vol', 'LY Primary Actuals Lead 2 Vol',
       'LY Primary P3M Vol', 'Primary P3M copy Vol',
       'PSKU Primary P3M Sum Vol', 'PSKU P3M Contribution',
       'Calculated Depot PSKU Primary Vol', 'Index Rate',
       'Calculated PSKU Primary Val', 'Primary Actuals Val',
       'Primary Plan Val', 'Secondary Plan Val', 'Secondary Actuals Val',
       'Primary P3M Val', 'Primary Actuals Lag 1 Val',
       'Primary Actuals Lag 2 Val', 'Primary Actuals Lag 3 Val',
       'LY Primary Actuals Val', 'LY Primary Actuals Lag 1 Val',
       'LY Primary Actuals Lag 2 Val', 'LY Primary Actuals Lag 3 Val',
       'LY Primary Actuals Lead 1 Val', 'LY Primary Actuals Lead 2 Val',
       'LY Primary P3M Val', 'PSKU Primary P3M Sum Val',
       'Calculated Depot PSKU Primary Val', 'M Month'],
      dtype='object')

In [ ]:
final_df[final_df.select_dtypes(include=['number']).columns] = final_df.select_dtypes(include=['number']).fillna(0)

final_df.isnull().sum()

Key                              0
Chain                            0
PSKU                             0
Brand                            0
Index Rate                       0
                                ..
LY Offtake Actuals Lag 2 Val     0
LY Offtake Actuals Lag 3 Val     0
LY Offtake Actuals Lead 1 Val    0
LY Offtake Actuals Lead 2 Val    0
Calculated Primary Val           0
Length: 91, dtype: int64

## SAVE

In [1096]:
VERSION = 'Aug26 Live Run'

In [1097]:
os.makedirs(f'FINAL ECOM Chain PSKU OTP/{VERSION}')

In [ ]:
final_depot_psku_df.to_csv(f'FINAL ECOM Chain PSKU OTP/{VERSION}/ECOM Depot PSKU Primary_{VERSION}.csv', index=False)
final_df.to_csv(f'FINAL ECOM Chain PSKU OTP/{VERSION}/ECOM Chain PSKU Primary_{VERSION}.csv', index=False)

In [311]:
norm_days.to_csv(f'FINAL ECOM Chain PSKU OTP/{VERSION}/Norm Days {VERSION}.csv', index=False)
norms.to_csv(f'FINAL ECOM Chain PSKU OTP/{VERSION}/Norms {VERSION}.csv', index=False)

In [312]:
soh_df.to_csv(f'FINAL ECOM Chain PSKU OTP/{VERSION}/SOH {VERSION}.csv', index=False)